### ISSUE TITLE
Inline-C not allowed

### ISSUE THREAD

**Issue by rmalenko** [nexcess/magento-turpentine#1000]
varnishd (varnish-4.0.2 revision bfe7cd1)
Turpentine - latest from GIT
Magento ver. 1.9.0.1

![Magento Turpentine](https://dl.dropboxusercontent.com/u/16852973/Selection_007.png)

After restart varnish I have got error message in log:
```
Message from VCC-compiler:
Inline-C not allowed
('input' Line 2 Pos 1)
C{
##
Running VCC-compiler failed, exited with 2
VCL compilation failed
```
Varnish config
`/usr/sbin/varnishd -a :80 -T localhost:6082 -p cli_buffer=81920 -p feature=+esi_ignore_other_elements -p vcc_allow_inline_c=on -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,512m`

defauld.vcl
```
vcl 4.0;
C{
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <pthread.h>
static pthread_mutex_t lrand_mutex = PTHREAD_MUTEX_INITIALIZER;
void generate_uuid(char* buf) {
pthread_mutex_lock(&lrand_mutex);
long a = lrand48();
long b = lrand48();
long c = lrand48();
long d = lrand48();
pthread_mutex_unlock(&lrand_mutex);
sprintf(buf, "frontend=%08lx%04lx%04lx%04lx%04lx%08lx",
a,
b & 0xffff,
(b & ((long)0x0fff0000) >> 16) | 0x4000,
(c & 0x0fff) | 0x8000,
(c & (long)0xffff0000) >> 16,
d
);
return;
}
}C
import std
...
```

**Comment by miguelbalparda** [comment]
Have you checked the documentation? There is at least one closed issue with the same problem plus a documented way to start varnish allowing inline c.

**Comment by rmalenko** [comment]
@miguelbalparda yes, I have read documentation and ran Varnish with this keys
`
/usr/sbin/varnishd -a :80 -T localhost:6082 -p cli_buffer=81920 -p feature=+esi_ignore_other_elements -p vcc_allow_inline_c=on -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,512m
`
