### ISSUE TITLE
SUPEE-6788 - Does this affect magento-turpentine?

### ISSUE THREAD

**Issue by loginid** [nexcess/magento-turpentine#1002]
Hi all,

Hope everyone is well.

Does this security patch affect the turpentine extension?

Thank you.

**Comment by miguelbalparda** [comment]
From https://github.com/nexcess/magento-turpentine/blob/master/app/code/community/Nexcessnet/Turpentine/etc/config.xml#L473 you can see there shouldn't be any issues with the controllers.

As you can see here https://github.com/nexcess/magento-turpentine/search?utf8=%E2%9C%93&q=addFieldtoFilter&type=Code we don't use any addFieldtoFilter. 

The only thing left are the use of variables allowing access to private information, which we are not using, so I would say the extension is secured.

**Comment by loginid** [comment]
Thanks Miguel!! :D
