### ISSUE TITLE
No X-Varnish headers when debug mode enabled and ip added to Allowed IPs for developer

### ISSUE THREAD

**Issue by leohartx** [nexcess/magento-turpentine#1007]
This is my website http://coral.magent.io , i have installed varnish 4.0 with nginx, php-fpm and turpentine.
after finished configuring and applied VCL file successfully, it seems not working.

i can see numbers changing in varnishstat but there is no X-Varnish headers even when debug mode is enabled and my ip and http://www.isvarnishworking.com ip adress added to 'Allowed IPs'.

i also tried to disable these line to make sure it won't apply unset varnish headers
https://github.com/nexcess/magento-turpentine/blob/master/app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl#L410-L424

but it's not working, how do i debug this issue ?

**Comment by miguelbalparda** [comment]
I don't think this is a Turpentine issue but an issue with your environment and installation. I will close this issue and mark it as invalid but feel fre to keep the conversation going here.
