### ISSUE TITLE
Include turpentine vcl in default.vcl for support of multiple magento installations

### ISSUE THREAD

**Issue by kirladu** [nexcess/magento-turpentine#1008]
Hello,
we need to support multiple magento installations using turpentine on one single server.

This should be accomplished as explained here:
http://info.varnish-software.com/blog/virtual-hosts-varnish

Content of default.vcl:
```
vcl 4.0;
sub vcl_recv {
       if (! req.http.Host) {
          return (synth(404, "Need a host header"));
       }

       set req.http.Host = regsub(req.http.Host, "^www\.", "");
       set req.http.Host = regsub(req.http.Host, ":80$", "");

       if (req.http.Host == "domain1.com") {
          include "/var/www/domain1.com/magento/var/default.vcl";
       }

       if (req.http.Host == "domain2.com") {
          include "/var/www/domain2.com/magento/var/default.vcl";
       }
}
```

Include vcl can be opened, but compilation fails where the turpentine vcl starts.

Error message is:
```
Message from VCC-compiler:
Expected an action, 'if', '{' or '}'
('/var/www/domain1.com/magento/var/default.vcl' Line 1 Pos 1)
vcl 4.0;
###-----
Running VCC-compiler failed, exited with 2
```

Is it a problem with compiling the inline C within the turpentine vcl?
Does anybody know how to solve or fix this? If not - any ideas for a workaround?

Thx for your support in advance!

**Comment by miguelbalparda** [comment]
This is definitely not a Turpentine issue but something you want to accomplish with varnish. Ill close the issue but feel free to continue the discussion here if anyone wants to chime in.
