### ISSUE TITLE
PRoblem admin with this extension

### ISSUE THREAD

**Issue by enriquepery** [nexcess/magento-turpentine#1011]
Hi,

I have too many problems with this extension in the admin of Magento.

When i try to go to some pages inside the admin it redirects always to dashboard.

 If i logout and open in a private session it works but only for 1 or 2 pages.

Please could someone help me?

**Comment by miguelbalparda** [comment]
Why do you think this is related to Varnish/Turpentine?

**Comment by aricwatson** [comment]
Closing for lack of feedback.
