### ISSUE TITLE
Double IPs in logs

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#1013]
I am not using mod_remoteip, mod_cloudflare or mod_rpaf for getting visitors IP address in Apache log. I had some issues with these modules and I had to edit apache2.conf (Debian) for clear solution. Here is the change I've done:

#LogFormat "<strong>%h</strong> %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "<strong>%{X-Forwarded-For}i</strong> %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined

Everything is working as expected. When Varnish uses Turpentine generated file, in Apache log I get 2 identically IPs. This issue is coming from this statement: 

<code>
sub vcl_recv {
if (req.restarts == 0) {
if (req.http.X-Forwarded-For) {
set req.http.X-Forwarded-For =
req.http.X-Forwarded-For + ", " + client.ip;
} else {
set req.http.X-Forwarded-For = client.ip;
}
}
</code>

To get rid one of the IPs I have to comment string concatenate. Now only one IP is in Apache log:

req.http.X-Forwarded-For <strong>/* COMMENTED + ", " + client.ip HERE */</strong>;

Is it a setting in Magento backend/ Turpentine extension for this issue? If I am saving the file, my comment change is gone. I have to edit again the file.

**Comment by aricwatson** [comment]
> To get rid one of the IPs I have to comment string concatenate.

I'm not sure I understand - can you post the code you're using that's getting over-written when you save changes.

There's a configuration option that may help you - [*Apply VCL On Config Change*](https://github.com/nexcess/magento-turpentine/wiki/Configuration#general-options) will prevent your changes from automatically being overwritten when you make other changes.

**Comment by ADDISON74** [comment]
Hi @aricwatson please check again my post. Before using Varnish I used Pound listening on both ports 80 and 443. Apache behind a proxy server won't process correctly the visitor IP. I tested mod_rpaf, mod_cloudflare and mod_remoteip. I was not satisfied, so I changed Log directive in Apache configuration file, replacing %h with %{X-Forwarded-For} everything worked as expected. In my virtual host log I can see the visitor IP.

Next step was setting Varnish between Pound and Apache. I let Pound on the same outside ports and put Varnish listening on port 8090. Once it was working great, I checked again Apache logs, now I have to visitor IPs, splited by a comma (e.g. 192.168.159.100, 192.168.159.100). I knew Turpentine VCL file added something and I checked the its content. You can see above in sub vcl_recv this string concatenate: 

set req.http.X-Forwarded-For = req.http.X-Forwarded-For + ", " + client.ip;

This creates me trouble having two IPs in my Apache log. Well I commented the last part as above in bold. Once I commented that part in my Apache log I get only one IP.

Please considering this situation, a Turpentine user is not using mod_rpaf or mod_remoteip, and getting visitor real IP he can edit Log directive. If there is already X-Forwarded-For in his log, he will get another one from Turpentine configuration file. That's why I got 2 IPs in my Apache log.

Hope you understand and find a solution.

**Comment by ADDISON74** [comment]
If Pound is listening on port 80 I am getting 3 IPs in Apache log. Here is an example: 

192.168.159.1, 192.168.159.100, 192.168.159.100 - - [22/Nov/2015:20:50:05 +0200] "GET /phpinfo.php HTTP/1.1" 200 79666 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36"

My configuration is Pound (80, 443) => Varnish (8090) => Apache (8080).

If I am running a php script on webserver to get phpinfo here is how X-Forward-For header looks like:

_SERVER["HTTP_X_FORWARDED_FOR"]  192.168.159.1, 192.168.159.100, 192.168.159.100

192.168.159.1 = visitor's IP
192.168.159.100 = server IP

You should take in consideration this configuration when more IPs are into X-Forwarded-For array. The first one is the most important, it is client.ip. As it is now Turpentine VCL file it adds more IPs to X-Forwarded-For which is not OK, it is missing a configuration when Varnish is not listen on incoming 80 port.

**Comment by ADDISON74** [comment]
Well, when your server is behind a proxy server mod_rpaf is working to provide in your logs visitor's IP address. But what happens when you have a chain of load balancing/proxy servers? You will get the chain as key=>value in X-Forwarded-For. The first one is client_ip address. For this case I have two solutions:

1) Building a mod_rpaf version which can deal with a chain of load balancing/proxy servers. By default mod_rpaf cannot do that. Here is one resource for understanding this solution:

https://uksysadmin.wordpress.com/2011/06/27/mod_rpaf-extract-real-ip-from-behind-load-reverse-proxyload-balancer/

I am investigating if once built this module provide solution out of the box (this one seems to be the most active): https://github.com/gnif/mod_rpaf.

Here is an example: 
X-Forwarded-For: 192.168.100.227 (Visitor's IP), 209.88.21.195, 10.58.59.219, 193.168.123.123

RPAFproxy_ips 10. 209. 193.168. in /etc/apache2/mods-available/rpaf.conf will pick in this case 192.168.100.277. With this custom built of mod_rpaf you can pick up any IP you want from X-Forwarded-For.

2) Set an environment variable in your Apache configuration (apache2.conf in Debian) or the root of your virtual host .htaccess to extract visitor IP address from X-Forwarded-For array. Then use this variable in your default Apache Log or CustomLog. 

SetEnvIf X-Forwarded-For "^(\d{1,3}+\.\d{1,3}+\.\d{1,3}+\.\d{1,3}+).*" XFFCLIENTIP=$1

XFFCLIENTIP takes the first key value in X-Forwarded-For array. Use this variable in your logs.

Varnish just adds its server IP address into this chain, nothing wrong with that.
