### ISSUE TITLE
Turpentine, Varnish, Magento on bitnami stack powered by AWS

### ISSUE THREAD

**Issue by AUSWinner** [nexcess/magento-turpentine#1015]
Having trouble with implementing varnish and turpentine with ESI enabled.
I'm running magento 1.9.2 with theme by neoshop, on a bitnami stack running off AWS ec2 instance. The whole page will load, but I'll lose the header block when I add a product to the cart. I've enabled debug info via the Varnish Options within Turpentine, i've noticed that it debug injects ESI URL, which I've copied and pasted inside my browser and it shows a error code 500 Server error 

Here is my turpentine esi logs
[turpentine_esi.txt](https://github.com/nexcess/magento-turpentine/files/36521/turpentine_esi.txt)

Cheers.

**Comment by aricwatson** [comment]
Are you seeing anything in your server logs for the 500 error?

**Comment by aricwatson** [comment]
Closing for lack of feedback.
