### ISSUE TITLE
Error determining Varnish version: Got unexpected response code from Varnish: 500 - Failed to load configurator

### ISSUE THREAD

**Issue by risamnang** [nexcess/magento-turpentine#1016]
Hello,

I'm using Magento 1.9.2 and I installed Varnish 4.1 with nginx.

I followed steps to install varnish on my VPS using this instructions https://github.com/nexcess/magento-turpentine/wiki/Installation, except the "2. Configure Varnish" part since I'm on ubuntu.

In the magento admin panel when I click on Varnish management buttons (Apply Varnish Config, Save varnish config...) 
I get this error : Error determining Varnish version: Got unexpected response code from Varnish: 500 - Failed to apply the VCL to 127.0.0.1:6082: Failed to load configurator

Could anyone give me a hand please ?

**Comment by miguelbalparda** [comment]
Have you selected the correct Varnish version in the admin? Which version of Turpentine are you using?

**Comment by risamnang** [comment]
I'm using Turpentine 0.6.7 and for the varnish version, I set to "Auto".

**Comment by miguelbalparda** [comment]
Try selecting the correct version, that should fix your issue.

**Comment by risamnang** [comment]
Ok right thanks, one last thing, I've got this error : Failed to apply the VCL to 127.0.0.1:6082: Varnish data to write over length limit by 1499 characters.

I read the instruction to this problem here : https://github.com/nexcess/magento-turpentine/wiki/FAQ#i-upgraded-to-turpentine-06-and-are-the-add-to-cart-buttons-look-broken

But it tell only of centOS OS, and I'm on ubuntu, do you know how to solve this please ?

**Comment by miguelbalparda** [comment]
Please close this issue of solved and open a new one.
