### ISSUE TITLE
Failed to apply the VCL to 127.0.0.1:6082: Varnish data to write over length limit by 1499 characters on ubuntu

### ISSUE THREAD

**Issue by risamnang** [nexcess/magento-turpentine#1017]
Hello again :),

when using Varnish management system, I got this error : Failed to apply the VCL to 127.0.0.1:6082: Varnish data to write over length limit by 1499 characters.

I read the instruction to this problem here : https://github.com/nexcess/magento-turpentine/wiki/FAQ#i-upgraded-to-turpentine-06-and-are-the-add-to-cart-buttons-look-broken

But it tells only of centOS OS, and I'm on ubuntu, do you know how to solve this please ?

**Comment by miguelbalparda** [comment]
Instuctins are the same despite the OS. The issue is not with Turpentine but with Varnish. I suggwat you to check http://stackoverflow.com/questions/25565665/change-varnish-cli-buffer-param-to-10000

**Comment by risamnang** [comment]
I followed the instruction and succefully changed the cli_buffer params and I still have the same message when clicking on "Apply Varnish Config". Do you know why please ?

**Comment by miguelbalparda** [comment]
Which value did you used for cli_buffer?

**Comment by risamnang** [comment]
I used the value 16384

**Comment by risamnang** [comment]
That's ok, the problem was because I restarted Varnish and it reapplied default value cli_buffer.
