### ISSUE TITLE
Failed to apply the VCL to 127.0.0.1:6082: Got unexpected response code from Varnish: 106 Message from VCC-compiler: Inline-C not allowed ('input' Line 2 Pos 1) C{ ## Running VCC-compiler failed, exited with 2 VCL compilation failed

### ISSUE THREAD

**Issue by risamnang** [nexcess/magento-turpentine#1018]
This message is displayed when using "Apply Varnish Config".

Could anyone help me please ?

I ran into this topic but I'm not sure to understand :
http://magento.stackexchange.com/questions/82791/varnish-turpentine-failed-to-apply-the-v

**Comment by miguelbalparda** [comment]
Have you checked the documentation? Your issue is like the last one you opened and the solution is pass a parameter to allow inline C to Varnish.

**Comment by risamnang** [comment]
Right ! Thanks, it is solved, thanks for your help Miguel !
