### ISSUE TITLE
{{form_key_esi_placeholder}} not replaced in URLs

### ISSUE THREAD

**Issue by mikeschaekermann** [nexcess/magento-turpentine#1021]
I found that when the VCL fix for form keys is disabled the `{{form_key_esi_placeholder}}` which is supposed to be replaced by the following event observer and method `Nexcessnet_Turpentine_Model_Observer_Esi::replaceFormKeyPlaceholder()`:

```
<http_response_send_before>
    <observers>
        <turpentine_esi_replace_form_key_placeholder>
            <class>turpentine/observer_esi</class>
            <method>replaceFormKeyPlaceholder</method>
        </turpentine_esi_replace_form_key_placeholder>
    </observers>
</http_response_send_before>
```

does not correctly replace the form key placeholder inside URLs because the curly brackets will be URL-encoded when read from the response body. For example, an add-to-wishlist URL would look similar to this:

`https://yourdomain.com/de/wishlist/index/add/product/123/form_key/%7B%7Bform_key_esi_placeholder%7D%7D/`

and will therefore not be replaced by the command:

```
$responseBody = str_replace( '{{form_key_esi_placeholder}}',
    $esiHelper->buildEsiIncludeFragment(
        $esiHelper->getFormKeyEsiUrl() ),
    $responseBody );
```

Everything seems to work fine if I change it to the following:

```
$esiDirective = $esiHelper->buildEsiIncludeFragment($esiHelper->getFormKeyEsiUrl());
$placeholder = '{{form_key_esi_placeholder}}';
$needles = [ $placeholder,  urlencode( $placeholder ) ];
$responseBody = str_replace( $needles, $esiDirective, $responseBody );
```

Then, the only problem remaining is that if a URL is base64-encoded to be used as a referer parameter for a login or registration form the `str_replace` method will not catch the placeholder string.

Is this a bug or am I using the extension in a wrong way?

Have a great day!
Mike

**Comment by aricwatson** [comment]
Hi Mike,

Sorry for the delay getting to this - busy time of year around here!

I can't seem to replicate this issue with formkeys, they seem to be working fine. For example, you can check out our [demo site](http://turpentine-master.devsupport.nexcess.net/)

**Comment by aricwatson** [comment]
Closing for lack of feedback.

**Comment by sprankhub** [comment]
We have exactly the same problem now and are happy to work on a solution together with you guys @aricwatson @miguelbalparda ;-) We use Turpentine 0.7.2, Varnish 4.1 and Magento 1.9.2.4. The wishlist link looks like this:

`https://www.shop.de/wishlist/index/add/product/1/form_key/%7B%7Bform_key_esi_placeholder%7D%7D/`

It seems as if the placeholder `{{form_key_esi_placeholder}}` is URL-encoded and therefore the replacement does not work. The option `Use VCL fix` is enabled.

I also checked your demo shop, but it does not seem to use Varnish any more. For instance, http://turpentine-master.devsupport.nexcess.net/men/new-arrivals/linen-blazer.html does not load under 100ms, so that I think Varnish is not active.

Do you have any idea why this could happen and how we can debug the issue?

@mikeschaekermann did you already find a solution for this issue?

**Comment by mikeschaekermann** [comment]
Sorry, I don't think we found a solution to the base64-encoded URLs in referer parameters. However, I don't exactly remember -- too long ago. Maybe @otherjustin may know? :)

**Comment by onigunn** [comment]
Got the same issue, this fixed it
app/code/community/Nexcessnet/Turpentine/Model/Observer/Esi.php#197
```
/**
     * Replace the form key placeholder with the ESI include fragment
     *
     * @param  Varien_Object $eventObject
     * @return null
     */
    public function replaceFormKeyPlaceholder($eventObject) {
        if (Mage::registry('replace_form_key')) {
            $esiHelper = Mage::helper('turpentine/esi');
            $response = $eventObject->getResponse();
            $responseBody = $response->getBody();
            $formKeyPlaceholder = '{{form_key_esi_placeholder}}';
            $encodedFormKeyPlaceholder = rawurlencode($formKeyPlaceholder);
            $responseBody = str_replace(
                array($formKeyPlaceholder, $encodedFormKeyPlaceholder),
                $esiHelper->buildEsiIncludeFragment(
                    $esiHelper->getFormKeyEsiUrl() ),
                $responseBody);
            $response->setBody($responseBody);
        }
    }

Just pass a encoded form key as search needle array to `str_replace`. If you guys like, I can prepare a PR.

**Comment by sprankhub** [comment]
@mikeschaekermann could you re-open the issue? I think it is not solved. It works with your workaround, which also replaces the encoded form key placeholder, but this should probably be merged into the extension.

**Comment by mikeschaekermann** [comment]
@sprankhub I can't re-open the issue. Can you re-open it, @aricwatson?

**Comment by felixbuenemann** [comment]
Still seeing this issue with turpentine 0.7.5, magento 1.9.3.9, varnish 4.1.11, also for the wishlinks form target.
