### ISSUE TITLE
Change output via PHP & control cache-control-header

### ISSUE THREAD

**Issue by q23** [nexcess/magento-turpentine#1022]
Hi,

if we save a product via magento backend the turpentine varnish is smart enough to present changes in frontend right after hiting save. thats great.

BUT
if we change a product on a programmatically way with php
$_product->setStoreId(0)->setData('comingsoon_to_date', false)->save();
how to tell the turpentine to renew the page? if i force another cache-control-header with shift+f5 it works as expected.

looking forward for your help.

robert

**Comment by miguelbalparda** [comment]
Check https://github.com/nexcess/magento-turpentine/blob/35d44f51e84de419c189eea2baa0ec89c7a2ba39/app/code/community/Nexcessnet/Turpentine/etc/config.xml#L311 wherer you will see some events that match what you are looking for. By dispatching some of those, Varnish cache will be flushed.

**Comment by q23** [comment]
great! but how to dispatch it via php?

**Comment by miguelbalparda** [comment]
Check http://www.demacmedia.com/magento-commerce/mini-tutorial-dispatching-your-own-event-in-magento/

**Comment by q23** [comment]
thank you!

**Comment by q23** [comment]
hi miguelbalparda,
sorry to bother you. is this right:
Mage::dispatchEvent( 'turpentine_ban_product_cache',
and why cant i find this event somewhere? or should i use
Mage::dispatchEvent( 'turpentine_varnish_catalog_product_save_commit_after
?
