### ISSUE TITLE
Question: X-Varnish-Store header is empty for default store

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#1025]
In backend "Enable Debug Info" option is set to Enable. Frontend is Magento RWD default, multi-stores, 3 languages (English, French, German).

I would like to know why <strong>X-Varnish-Store</strong> header is empty for the default store (english), but for the other stores is set to french or german? Is this a correct behavior? Please see the images bellow.

<strong>English store</strong>

![english](https://cloud.githubusercontent.com/assets/8360474/11454307/daaf5fc8-962f-11e5-8b48-84a2af4f4500.jpg)

<strong>French store</strong>

![french](https://cloud.githubusercontent.com/assets/8360474/11454310/e8383cb4-962f-11e5-9f93-21d5e6eab663.jpg)

**Comment by aricwatson** [comment]
The header is set based on the existence of a "store" cookie:

```
if (req.http.Cookie ~ "\bstore=") {
    set req.http.X-Varnish-Store = regsub(
        req.http.Cookie, ".*\bstore=([^;]*).*", "\1");
}
```
Then it's later used to build up the hash used to store the value with Varnish, to make sure different store data is stored separately. Standard magento behavior is to not set a `store` cookie for the default store, but to set it when the user switches to the other stores - so this header will basically reflect that behavior.

**Comment by ADDISON74** [comment]
I appreciate for your answer. I will close this question.
