### ISSUE TITLE
After restart varnish I have got error message in log: Inline-C not allowed

### ISSUE THREAD

**Issue by rmalenko** [nexcess/magento-turpentine#1026]
Hello,

Help me, please. 

**vcc_allow_inline_c=on - is enabled**

reloaded - systemctl daemon-reload

```The Varnish start with /usr/sbin/varnishd -p feature=+esi_ignore_other_elements -p vcc_allow_inline_c=on -p cli_buffer=81920 -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m ```

```
Message from VCC-compiler:
Inline-C not allowed
('input' Line 2 Pos 1)
C{
##
Running VCC-compiler failed, exited with 2
VCL compilation failed
```

varnish-4.0.2 revision bfe7cd1
Turpentine - latest (today cloned from git)

**Comment by rmalenko** [comment]
https://gist.github.com/rmalenko/77610d804373d7fd6268

**Comment by ADDISON74** [comment]
This is not a Turpentine issue, it is related to Varnish. Your configuration seems to be just fine. What Varnish package are you using? Is it from Varnish repository? Did you try searching Google for this issue related to your operating system?

**Comment by rmalenko** [comment]
@ADDISON74 
I have installed Debian 8.1 and varnish-4.0.2 revision bfe7cd1 from the Debian repository
After upgrade to (varnish-4.1.0 revision 3041728) from Varnish repository I have got the same error.

**Comment by rmalenko** [comment]
```
varnish> param.show vcc_allow_inline_c
200        
vcc_allow_inline_c
        Value is: on [bool]
        Default is: off

        Allow inline C code in VCL.

```

**Comment by aricwatson** [comment]
@rmalenko [this issue](https://github.com/nexcess/magento-turpentine/issues/948#issuecomment-141805671) might be useful for your problem.

**Comment by rmalenko** [comment]
@aricwatson  thank you a lot. It helps me.

**Comment by aricwatson** [comment]
Thanks - let us know if you have any other questions!
