### ISSUE TITLE
Compatibility with GoMage LightCheckout

### ISSUE THREAD

**Issue by sprankhub** [nexcess/magento-turpentine#1030]
To make Varnish/Turpentine compatible with [GoMage LightCheckout](https://www.gomage.com/gomage-lightcheckout.html), you have to include the following in your layout XML. It ensures that the checkout is not cached.

    <gomage_checkout_onepage_index>
        <turpentine_cache_flag value="0"/>
    </gomage_checkout_onepage_index>

    <gomage_checkout_onepage_methods>
        <turpentine_cache_flag value="0"/>
    </gomage_checkout_onepage_methods>

    <gomage_checkout_onepage_paymentmethod>
        <turpentine_cache_flag value="0"/>
    </gomage_checkout_onepage_paymentmethod>

    <gomage_checkout_onepage_centinel>
        <turpentine_cache_flag value="0"/>
    </gomage_checkout_onepage_centinel>

    <gomage_checkout_onepage_review>
        <turpentine_cache_flag value="0"/>
    </gomage_checkout_onepage_review>

    <gomage_checkout_onepage_customerlogin>
        <turpentine_cache_flag value="0"/>
    </gomage_checkout_onepage_customerlogin>

    <gomage_checkout_onepage_review>
        <turpentine_cache_flag value="0"/>
    </gomage_checkout_onepage_review>

    <gomage_checkout_onepage_forgotpassword>
        <turpentine_cache_flag value="0"/>
    </gomage_checkout_onepage_forgotpassword>

    <gomage_checkout_onepage_ajax>
        <turpentine_cache_flag value="0"/>
    </gomage_checkout_onepage_ajax>

    <gomage_checkout_onepage_save>
        <turpentine_cache_flag value="0"/>
    </gomage_checkout_onepage_save>

Not sure if you want to add this somewhere in the documentation, e.g. in the [Wiki Compatibility page](https://github.com/nexcess/magento-turpentine/wiki/Compatibility).

**Comment by miguelbalparda** [comment]
Done, added and pointed to this issue. Thank you!
