### ISSUE TITLE
Problem - Auto clear cart in checkout

### ISSUE THREAD

**Issue by augpaschal** [nexcess/magento-turpentine#1033]
We wil describe out problem in detail.

We had a site on magento 1.7 which has your extension (without using ssl on site)

We created a new site in magento 1.9, with new tempate.

Both in dev and live installation we use One Step Check Out Pro ( http://www.mage-world.com/magento-one-step-checkout-extension.html )

In two cases (live and dev site) we use cache with varnish (using the turpentine extension).

When we made the switch  the dev site (where is played in a subdomain ) to play live (at main domain) we observed the following regarding the process of orders :

The problem was that when somebody went directly to a product page (or maybe the checkout page with ssl was the first page with ssl which viewd by guest) and add the product to the cart, when then did checkout (onepagecheckoutpro) then automatically emptied the cart and go to a page saying that there are no products in cart.

If you had browsed the site and then had entered the product page he normally could complete the order.

Then we tried to disable ssl (secure ssl = "http ..." =), we made clear varnish and then they took us the message that we told you ( XMLHttpRequest cannot load https://www.e-shoes.gr/onestepcheckout/index/save_34c554118af7879869c106e5653fc0ab/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.e-shoes.gr' is therefore not allowed access.)

Any idea?

**Comment by miguelbalparda** [comment]
You should check #846 to see the different ways we handle form_key and how to fix the issue you are having.
