### ISSUE TITLE
Compatibility with Prime Checkout

### ISSUE THREAD

**Issue by sprankhub** [nexcess/magento-turpentine#1035]
The following changes should ensure the compatibility with Prime Checkout.

    <checkout_prime_debug>
        <turpentine_cache_flag value="0"/>
    </checkout_prime_debug>

    <checkout_prime_index>
        <turpentine_cache_flag value="0"/>
    </checkout_prime_index>

    <checkout_prime_login_step_info>
        <turpentine_cache_flag value="0"/>
    </checkout_prime_login_step_info>

    <checkout_prime_payment_step_info>
        <turpentine_cache_flag value="0"/>
    </checkout_prime_payment_step_info>

    <checkout_prime_progress>
        <turpentine_cache_flag value="0"/>
    </checkout_prime_progress>

    <checkout_prime_review>
        <turpentine_cache_flag value="0"/>
    </checkout_prime_review>

    <checkout_prime_savepayment>
        <turpentine_cache_flag value="0"/>
    </checkout_prime_savepayment>

    <checkout_prime_shipping_step_info>
        <turpentine_cache_flag value="0"/>
    </checkout_prime_shipping_step_info>

    <checkout_prime_getstepinfo>
        <turpentine_cache_flag value="0"/>
    </checkout_prime_getstepinfo>

    <checkout_prime_saveorder>
        <turpentine_cache_flag value="0"/>
    </checkout_prime_saveorder>

    <checkout_prime_getaddress>
        <turpentine_cache_flag value="0"/>
    </checkout_prime_getaddress>

    <checkout_prime_savemethod>
        <turpentine_cache_flag value="0"/>
    </checkout_prime_savemethod>

    <checkout_prime_failure>
        <turpentine_cache_flag value="0"/>
    </checkout_prime_failure>

    <checkout_prime_saveshippingmethod>
        <turpentine_cache_flag value="0"/>
    </checkout_prime_saveshippingmethod>

    <checkout_prime_savecoupon>
        <turpentine_cache_flag value="0"/>
    </checkout_prime_savecoupon>

    <checkout_prime_savebilling>
        <turpentine_cache_flag value="0"/>
    </checkout_prime_savebilling>

    <checkout_prime_success>
        <turpentine_cache_flag value="0"/>
    </checkout_prime_success>

    <checkout_prime_saveshipping>
        <turpentine_cache_flag value="0"/>
    </checkout_prime_saveshipping>

    <checkout_prime_shippingmethod>
        <turpentine_cache_flag value="0"/>
    </checkout_prime_shippingmethod>

    <checkout_prime_getadditional>
        <turpentine_cache_flag value="0"/>
    </checkout_prime_getadditional>

You may want to link this issue in the [wiki](https://github.com/nexcess/magento-turpentine/wiki/Compatibility) again.

But I think you should (also) add these handles to your layout XML. It does not really have any disadvantages (besided the bigger file), but helps that this integration works out-of-the-box for more stores.

**Comment by miguelbalparda** [comment]
@sprankhub feel free to submit a PR with these changes. I just added this to the wiki.
