### ISSUE TITLE
Site Footer is missing when Varnish cache is turned on

### ISSUE THREAD

**Issue by konasports** [nexcess/magento-turpentine#1037]
Hello, I am having some trouble setting up Varnish with Turpentine. I was finally able to get it mostly working. We use nginx and php-fpm. When I turn cache on in admin, save the vcl file and apply the vcl I get no errors and varnish seems to run fine except the footer of every page is missing. I have looked up the problem and tried a few of the known fixes. Turning off gzip compression in the nginx config for port 80 does not have any effect. If I disable all cache except the main varnish cache the page loads with the footer, when I enable the esi cache the footer is lost again. I enabled the debug and block logging in varnish config. I enabled the custom log file too, but I can't find where the log file gets saved... I did notice that the esi comments are strange in the footer it starts outside and ends inside... is this normal? http:\\dev.konasurfco.com

**Comment by aricwatson** [comment]
>  I enabled the custom log file too, but I can't find where the log file gets saved...

By default this is in the `[magento root]/var/log` directory

> I did notice that the esi comments are strange in the footer it starts outside and ends inside... is this normal? 

I don't think I've seen that before. What ESI caching policies are you setting on the footer block? You could try not hole-punching for that block by using the `disableEsiInjection` option - unless of course you need the footer to be cached privately.

**Comment by konasports** [comment]
Thanks for the reply.

1. I just checked the [magento]/var folder and there isn't a log folder inside it. I created one and set full permissions, but a turpentine.log file hasn't appeared in it, so either it is having trouble creating one, or it's in a different place?

2. I have turpentine set with the defaults in admin. I don't see any options mentioning ESI and I am using the generated vcl file (it is symlinked to default.vcl) The footer block itself from what I understand is loaded in 2 sections. The left links (loaded from a phtml template page) and the custom buttons block (loaded from a cms block in admin) How this ties in with varnish and ESI I am not sure. Is there a tutorial on how to adjust the ESI policies for certain blocks?

**Comment by ADDISON74** [comment]
Enable the following option in Varnish Options:

- Enable Debug Info
- Enable Block Logging

Flush Cache Storage, restart Varnish service, clear your browser cache and cookies then reload the page. Inspect in Chrome the page. You should see green tags surrounding your footer block (e.g. ). If you don't see this check if these green tags are in your source code. If they are you should check your footer block name. As I see it hs a custom theme not Magento default. I confirm in default theme footer has ESI policy.

**Comment by konasports** [comment]
Yes I am using a custom theme. It is derived from the rwd theme (Which is included in magento 1.9 by default)

I have enabled both of those options in admin. There are a number of ESI START and END tags in the source code. The ESI START [footer] is before the footer-container and the ESI END [footer] is inside the empty footer div.

I was able to find some ESI instructions here: https://github.com/nexcess/magento-turpentine/wiki/ESI_Cache_Policy
I will try a few different things from these instructions and let you know how it turns out.

**Comment by konasports** [comment]
Ok, so now I get no ESI comments at all. I have disabled and enabled the varnish caches in admin repeatedly, turned debug and block logging on and off. Restarted nginx and varnish and I've got nothing. I changed no files and have been stumped for 3 hours now. I have no clue what happened and am very frustrated...

**Comment by aricwatson** [comment]
Hang in there, it certainly can be confusing.

My usual 'debug mode' set up is to have logging turned on (including block logging). Turn of all the different cache types under 'cache management' *except* for the two turpentine related cache types.

Then, restart apache/nginx and Varnish. Login to the back-end and apply the VCL from the 'cache management' screen. Now, in an incognito window go to the front end of the site. Click through to a 2nd page, or reload the page (remember, the first page is passed through Varnish). You should see the ESI comments now, which means that Varnish/Turpentine are working.

>  There are a number of ESI START and END tags in the source code. The ESI START [footer] is before the footer-container and the ESI END [footer] is inside the empty footer div.

This sounds like an issue with your layout, like perhaps your footer are actually is comprised of more than one block? If you can get the debug messages working, look for messages regarding the footer block. Also, check for other errors in your exception log.

**Comment by ADDISON74** [comment]
@aricwatson You mentioned disabling all cache types except the two turpentine. From your experience in production do you keep Magento default caches disable? Personally I disabled only Block HTML output because of ___SID issue, but normally I keep them all enable. Reading all the issues there are Turpentine users keeping them all enable or disable.

**Comment by aricwatson** [comment]
> From your experience in production do you keep Magento default caches disable?

No, I don't believe we do. Of course it varies by client. For the demo site, I've enabled all of the caches except for the block html cache type. 

But for debugging/developing I turn them off. Varnish already makes things tricky enough, so I try to minimize the complications.

**Comment by konasports** [comment]
Hi guys, just a quick update on my progress. After learning the xml related to the ESI processing I added a local.xml and set disableEsiInjection for the footer block. The footer now shows while varnish is turned on. Does this mean that the footer isn't cached now? It seems to be a step in the right direction. Maybe now I can get the block names for the things inside the footer and cache them separately.

**Comment by aricwatson** [comment]
Actually, it means it's cached as a part of the whole page cache. As long as you have no need for it to be cached separately (i.e. as a private block) it should be fine.

**Comment by konasports** [comment]
Ok, that's good then. I don't need it to be separate, it's just the newsletter signup and some static links. I did try to set ESI on the two blocks separately, but the footer.newsletter block doesn't show up (It may be what broke the footer to begin with) and the static links are in a cms page which is not supported according to #782 

Thanks for the help!
