### ISSUE TITLE
Caching seems to be user-/session-based

### ISSUE THREAD

**Issue by skrollme** [nexcess/magento-turpentine#1038]
Hi Folks, 
our customer has a existing setup with a loadbalancer and 2 Apaches (one per server with shared htdocs) and now wants a Varnish as FPC.
The hoster set up the Varnishes (yes, 2 Varnish servers) behind the LB which access them round-robin. Each Varnish uses both Apaches as backends.

Turpentine is installed on both Apaches and both Varnish are configured to use the VCL written by Turpentine. No extra or custom VCL. Magento is able to access the Varnishes for control-requests (both Varnishes are entered in the Serverlist). Everything seems to be fine at this point. I also attached our Turpentine config and the vcl_hash() below.
At the Frontend we use ESI Tags to include the header (including the mini-cart, but whole block marked as "private" via layouts) and other user-specifig blocks which works. I see the Varnish requesting the ESI Blocks in the Varnishlog.

*The problem we are facing is, that the Varnish seems to Cache the pages on a per-session/user-basis.*

*Example:*
* Varnish (re)start
* I open up Chrome (Dev-Toolbar closed, no Bypass-Headers, e.g.) shop.com/page1.html (not logged in, cookies cleared)
 * First Request slow (OK)
 * Second Request fast (OK)
* I open up an Incognito-Tab in Chrome (or an other browser because Useragent-String is not hashed) and request shop.com/page1.html
 * First Request slow *(NOT OK)*
 * Second Request fast 

Do I have the wrong expectations? Shouldn't the Varnish Cache the whole page (with or without header-ESI-block ?) a deliver it fast, even for new (session-less) users?

_What I tried so far:_
* A lot of combinations of config-settings
* Commenting out the "useragent"-part in vcl_hash
* Commenting out the "accept-encoding"-part in vcl_hash

![General](https://cloud.githubusercontent.com/assets/1336659/11659682/b186e412-9dc9-11e5-9e7d-cb97353cd87c.png)
![Normalize TTL](https://cloud.githubusercontent.com/assets/1336659/11659706/d8aeb394-9dc9-11e5-9ffb-4ffb73111e81.png)
![URLs](https://cloud.githubusercontent.com/assets/1336659/11660484/9c80d5ba-9dcd-11e5-9572-c1630fc43f97.png)

```
sub vcl_hash {
	if(false && req.http.X-Varnish-Cache-Url) {
		hash_data(req.http.X-Varnish-Cache-Url);
	} else {
		hash_data(req.url);
	}
	
	if (req.http.Host) {
		hash_data(req.http.Host);
	} else {
		hash_data(server.ip);
	}
	
	hash_data(req.http.Ssl-Offloaded);
	
	if (req.http.X-Normalized-User-Agent) {
		hash_data(req.http.X-Normalized-User-Agent);
	}
	
	if (req.http.Accept-Encoding) {
		hash_data(req.http.Accept-Encoding);
	}
	
	if (req.http.X-Varnish-Store || req.http.X-Varnish-Currency) {
		hash_data("s=" + req.http.X-Varnish-Store + "&c=" + req.http.X-Varnish-Currency);
	}
	
	if (req.http.X-Varnish-Esi-Access == "private" && req.http.Cookie ~ "frontend=") {
		hash_data(regsub(req.http.Cookie, "^.*?frontend=([^;]*);*.*$", "\1"));
	}
	
	if (req.http.X-Varnish-Esi-Access == "customer_group" && req.http.Cookie ~ "customer_group=") {
		hash_data(regsub(req.http.Cookie, "^.*?customer_group=([^;]*);*.*$", "\1"));
	}
	return (hash);
}
```

**Comment by aricwatson** [comment]
>  Shouldn't the Varnish Cache the whole page (with or without header-ESI-block ?) a deliver it fast, even for new (session-less) users?

By default, this is *not* true - the first request for each session gets passed through to get a valid session set up. This is primarily because of formkey issues that were causing users to end up with an empty cart after adding a product, if they did so from their first access to the site, for example. 

You can use the [Use VCL Fix](https://github.com/nexcess/magento-turpentine/wiki/Configuration#general-options) option in the back-end to switch to an observer-based fix for this problem which may give you better performance - but will necessitate disabling CRSF protection.

**Comment by skrollme** [comment]
Thanks for your reply but I am not sure if the session-setup stuff explains the following scenario which I see in the shop:

Starting with fresh no sessions/cookies:
* Browser 1
 * open shop.com/page1.html => slow (ok)
 * open shop.com/page1.html again => fast (ok)
 * open shop.com/page2.html => slow (ok)
 * open shop.com/page2.html => fast (ok)
* Browser 2
 * open shop.com/page1.html => slow (nah... but is is the session-setup you mentioned, right?)
 * open shop.com/page1.html again => fast (ok)
 * open shop.com/page2.html => slow *(not OK for me, session is set up on page1.html and Browser1 already cached this page earlier)*

**Comment by aricwatson** [comment]
>Browser 2
>open shop.com/page1.html => slow (nah... but is is the session-setup you mentioned, right?)

Yes - if you look at the page source on this request you shouldn't see any ESI include HTML comment "stuff."

>open shop.com/page1.html again => fast (ok)
>open shop.com/page2.html => slow (not OK for me, session is set up on page1.html and Browser1 already cached this page earlier)

Yes - however there may be some elements on page 2 that are cached privately (per session) and haven't yet been cached for this session.  Or there could be some problem that's causing the page to bypass Varnish. Do you see any ESI html comments on the page that's loading slowly? If you turn on debugging in Turpentine, do you see any errors in the logs?

**Comment by aricwatson** [comment]
Closing for lack of feedback.
