### ISSUE TITLE
Issue with SSL

### ISSUE THREAD

**Issue by augpaschal** [nexcess/magento-turpentine#1039]
I open my page (new.mysite.gr) in incognito.
Cookie-> frontend	4722c11d25034503836a605e401553eb	new.mysite.gr
Then i click the link to connect in my account and i go to customer/account/login/ (with https)
Now the cookies are-> 
frontend	4722c11d25034503836a605e401553eb	 .new.mysite.gr			
frontend	4722c11d25034503836a605e401553eb	new.mysite.gr		
frontend_cid	u5swvO9SViLZihBo	.new.mysite.gr
I enter username / password but i redirect in same page  ( customer/account/login/ )
Cookies -> 
customer_group	1	.new.mysite.gr			
frontend	4722c11d25034503836a605e401553eb 	.new.mysite.gr				
frontend	j4h0a42k8buon36aim012v40g0	new.mysite.gr			
frontend_cid	vo4YlS3mPnArA2Lt	.new.mysite.gr

Then i delete the cookie -> frontend	4722c11d25034503836a605e401553eb 	.new.mysite.gr	
and retry to login. Now i enter to my account.

Can anyone help me to solve my problem?

I have install turpentine from magento connect and i have 0.6.7 version and 1.9.2.1 magento

Also i find that this file https://github.com/jharrisonau/magento-turpentine/blob/d3f9562e116d71780e177fb298ec8a075d89fc46/app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl has some differences from the file in my server.

**Comment by ADDISON74** [comment]
Is it the default Magento theme? When 1.9 was released many developers complained about they could not create accounts or login. It was related to adding keys in forms. Just disable varnish and see if you get the same issue.

**Comment by augpaschal** [comment]
No, it isnt default theme. I disabled varnish and i haven't that issue. Also when i deleted the cookie and i could login if i go to pages in which i have enter before login it display link to connect (no welcome message)

**Comment by augpaschal** [comment]
Why i have differences between  https://github.com/jharrisonau/magento-turpentine/blob/d3f9562e116d71780e177fb298ec8a075d89fc46/app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl  and the file in my installation (0.6.7)?

**Comment by miguelbalparda** [comment]
@augpaschal that file is not in our repo. We don't control the content of that file.

**Comment by augpaschal** [comment]
@miguelbalparda sorry :-) thanks
