### ISSUE TITLE
Problem with menu css

### ISSUE THREAD

**Issue by augpaschal** [nexcess/magento-turpentine#1040]
I have problem with my menu css when i enter a page which isn't cached (maybe).

If i put in comment the following code

    <reference name="header">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <flush_events>
                        <wishlist_item_save_after/>
                        <wishlist_item_delete_after/>
                        <sales_quote_save_after/>
                    </flush_events>
                </params>
            </action>
        </reference>

then the menu css is ok.

Is this correct way to fix css ?

**Comment by augpaschal** [comment]
Ok, it is fixed

I put

<reference name="top.links">
        <action method="setEsiOptions">
            <params>
                <access>private</access>
                <flush_events>
                    <wishlist_item_save_after/>
                    <wishlist_item_delete_after/>
                    <sales_quote_save_after/>
                </flush_events>
            </params>
        </action>
    </reference>

instead of

<reference name="header">
        <action method="setEsiOptions">
            <params>
                <access>private</access>
                <flush_events>
                    <wishlist_item_save_after/>
                    <wishlist_item_delete_after/>
                    <sales_quote_save_after/>
                </flush_events>
            </params>
        </action>
    </reference>

**Comment by ivantnt** [comment]
Hello Augpaschal thank you very much this also work for me?...do you know why it happens?...thank you very much
