### ISSUE TITLE
No changes to default.vcl

### ISSUE THREAD

**Issue by kevin25** [nexcess/magento-turpentine#1041]
Hello,

I am using varnishd (varnish-4.1.0 revision 3041728
I gave default.vcl full permissions. Btw, no changes from backend wrote to default.vcl. It's weird. Any idea?

**Comment by TableDeMassageElectrique** [comment]
Is that the option "Config File Location" is configured ?
Config > Varnish Options
https://github.com/nexcess/magento-turpentine/wiki/Configuration
Config File Location: Set the location for the plugin to save generated VCLs to. {{root_dir}} is automatically replaced with Magento's base directory. It is not recommended that you set this to /etc/varnish/default.vcl as Magento will not likely have write access to that location (and probably shouldn't either). You should instead symlink /etc/varnish/default.vcl to the whatever you choose for this (or the default).

**Comment by kevin25** [comment]
Yep. i did the same. I put the default.vcl at the default path under var/. But nothing changed on it.

**Comment by TableDeMassageElectrique** [comment]
Do you check owner and group of your default.vcl file ?

**Comment by kevin25** [comment]
Yep. The same owner as the web directory. I tried to chown the web user also but didn't work out.

**Comment by TableDeMassageElectrique** [comment]
Do you have a message when you click on "Apply Varnish Config" ?
I have this message : "VCL successfully applied to 127.0.0.1:6082" and you ?

**Comment by aricwatson** [comment]
Closing for lack of feedback.

**Comment by kevin25** [comment]
I just saw the message:

The configuration has been saved.
