### ISSUE TITLE
Welcome message cached

### ISSUE THREAD

**Issue by augpaschal** [nexcess/magento-turpentine#1042]
I am in homepage, then i enter account by login form, and the welcome message is "Welcome My Name"
If i go again in home page the message is "Welcome in xxx.com" as it was before login.

Welcome message is printed 
```
<p class="welcome-msg"><?php echo $this->getChildHtml('welcome'); ?> <?php echo $this->getAdditionalHtml(); ?></p>
```

How can i fix that. any idea?

**Comment by aricwatson** [comment]
What block is it a part of? And what ESI caching policies have been established for that block?

**Comment by augpaschal** [comment]
It is inside header.

In turpentine xml has
```
<reference name="header">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <flush_events>
                        <wishlist_item_save_after/>
                        <wishlist_item_delete_after/>
                        <sales_quote_save_after/>
                    </flush_events>
                </params>
            </action>
        </reference>
```
in local.xml i have put 
```
<action method="setEsiOptions">
                <params>
                    <disableEsiInjection>1</disableEsiInjection>
                </params>
            </action>
        </reference>
```
because without that my menu (megamenu) ins't displayed correct (without css)

**Comment by augpaschal** [comment]
Any suggestion?

**Comment by aricwatson** [comment]
The problem is that you're disabling ESI injection for the header block. Which means that the header block isn't cached separately, it's cached along with the rest of the page.

If it were cached separately, I'd advise finding an event to set in `flush_events` and flush the header after user login.

**Comment by aricwatson** [comment]
Closing for lack of feedback.
