### ISSUE TITLE
Question: What is the difference between GET Parameters and Ignore GET Parameters?

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#1044]
According to Wiki: 

<strong>GET Parameters</strong> = list of GET variables that prevent caching. This is a comma-separated list of GET request parameters (ex: var in http://www.example.com/somepage?var=foobar) that will prevent Varnish from caching a page.

<strong>Ignore GET Parameters</strong> = list of GET variables that will be ignored for caching. This is a separated list of GET request parameters that will be ignored by Varnish.

What is the difference between them technically, ignore versus prevent? Here is why I am asking this. I have an URL with a GET variable named q (header search box). Where shall I insert this variable as option for not being cached?

**Comment by aricwatson** [comment]
*GET Parameters* will cause a page to *not* be cached, if that parameter is present in the request URL

*Ignore GET Parameters* - these parameters will effectively be *stripped* from the request by Varnish - which can help improve caching performance.

>  I have an URL with a GET variable named q (header search box). Where shall I insert this variable as option for not being cached?

You could put 'q' in the *Ignore GET Parameters* option - however you will run into a problem when you try to search - the entered search parameter gets stripped, and Magento will then just redirect back to the homepage. The way around this is to just add the search results page URL to the URL blacklist, so it is not cached.

However, I don't think there's really any benefit to this - that 'q' parameter is only used by the search form (as far as I know) - so you're not really accomplishing much in terms of improving performance.

**Comment by ADDISON74** [comment]
I agree. There are no benefits setting up q parameter in ignore. I already did this and search is not working being redirected to home page. I am glad you clarified these two options.

**Comment by aricwatson** [comment]
No problem! Let us know if you have other questions.
