### ISSUE TITLE
Question: URL Blacklist

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#1045]
From Wiki: 

<strong>URL Blacklist</strong> = This is a list of URL patterns (relative to the Magento root, one per line) that Varnish should never cache. Note that the admin section and API are automatically included.

I read many posts where from a relative path to Magento root Turpentine users extracted only a part ot it. Is this a correct approach?

For example: 
http://www.mydomain.com/catalogsearch/result/?q=word

I would like not caching pages with /catalogsearch/result/?q=. Relative path is /catalogsearch/result/. Using in textarea:

/catalog/result/ or 
/catalog/ or 
/result/ 

will produce the same result?

Do I need to use / at the beginning and the end of a path? (e.g. /catalog/result/) Or just catalog/result/?

**Comment by ADDISON74** [comment]
Example 1: Can I use characters like * and ? for giving the full path from root?
(e.g. /catalogsearch/ * / or / * /result/ or /catalog*/result)?

Example 2: If I use just a word from path let's say result (without /), will it be considered http://www.mydomain.com/result or any URL containing result?
(e.g. http://www.mydomain.com/catalogsearch/result/)?

**Comment by aricwatson** [comment]
What you enter in that field is used to build a regular expression in the generated VCL file. For example, here's the line that's generated with the default settings:

    if (req.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?(?:admin|api|cron\.php)" ||

You can see the `cron\.php` that's entered by default in the URL blacklist text field, as well as other values generated from other config options. 

> Example 1: Can I use characters like * and ? for giving the full path from root?
(e.g. /catalogsearch/ * / or / * /result/ or /catalog*/result)?

I don't believe so - I'd suggest sticking with something like `catalogsearch/result/` which should be specific enough I'd think.

> Example 2: If I use just a word from path let's say result (without /), will it be considered

Yes - you can see in the generated regex that it uses `admin|api` to black list the admin and api URLs.

**Comment by ADDISON74** [comment]
I appreciate for your help. This is what I needed to know. It won't be a problem creating regex.
