### ISSUE TITLE
Is it possible to purge the turpentine/varnish cache from a php shell script?

### ISSUE THREAD

**Issue by konasports** [nexcess/magento-turpentine#1046]
Hello,
We are transferring from a different varnish cache solution. Inventory is run daily on the server through a php shell script and the Unirgy import module. The script updates inventory, then runs reindex-all and purges the cache. The old varnish module allowed me to purge the varnish cache per product from within the inventory script: purge($product_sku, true, true); Is there a similar way to purge varnish with the turpentine extension from the inventory script?

**Comment by aricwatson** [comment]
Depending on how your script is implemented, it may be unnecessary. Turpentine should be clearing the product page when the `catalog_product_save_commit_after` event is triggered. If that's not happening, you may be able to write your own script to run using `banProductPageCache()` from `app/code/community/Nexcessnet/Turpentine/Model/Observer/Ban.php`. Turpentine will also clear the cached product pages on the `cataloginventory_stock_item_save_after` event - which may also be being triggered by your script. 

Alternatively, you can also clear pages via the *Flush Matching Urls* on the *cache management* screen - there may be some way to make use of that functionality.

**Comment by konasports** [comment]
Ok, that's good to know. I will have to see if one of those events gets triggered by the inventory script. I notice that there isn't a "flush varnish" button on the cache management page in admin. Does varnish get flushed with the "flush magento cache" button or only when you "refresh" the cache indexes associated with varnish?

**Comment by aricwatson** [comment]
It looks like *flush magento cache* does flush the Varnish page cache - but not the ESI block cache. So, you're probably better off refreshing the specific Varnish cache types on the *cache management* page.

**Comment by konasports** [comment]
Thank you for the information, you've helped me out a lot.
