### ISSUE TITLE
Generated VCL not compatible with Varnish 2.1.5

### ISSUE THREAD

**Issue by vova3379** [nexcess/magento-turpentine#1047]
We have installed the latest Turpentine and are finding:

    Upon setting version to 2.1.5 in the Magento backend, the generated VCL doesn't seem to be compatible with Varnish 2.1.5

The current Varnish version on server is 2.1.5.

Following is the error we are getting when we perform a VCL syntax check, 

[root@hobrc shop]# varnishd -C -f var/default.vcl
Message from VCC-compiler:
Syntax error in condition, expected '(', '!' or variable name, found 'false'
(input Line 172 Pos 4)
if(false && req.http.X-Varnish-Cache-Url) {
---#####-----------------------------------

VARNISH VCL NOT WORKING:

if (req.http.X-Opt-Enable-Get-Excludes == "true" &&
req.url ~ "(?:[?&](?:__SID|XDEBUG_PROFILE)(?=[&=]|$))") {
return (pass);
}
if (req.url ~ "[?&](utm_source|utm_medium|utm_campaign|utm_content|utm_term|gclid|cx|ie|cof|siteurl)=") {
set req.url = regsuball(req.url, "(?:(\?)?|&)(?:utm_source|utm_medium|utm_campaign|utm_content|utm_term|gclid|cx|ie|cof|siteurl)=[^&]+", "\1");
set req.url = regsuball(req.url, "(?:(\?)&|\?$)", "\1");
}
if(req.http.X-Opt-Send-Unmodified-Url == "true") {
set req.http.X-Varnish-Cache-Url = req.url;
set req.url = req.http.X-Varnish-Origin-Url;
unset req.http.X-Varnish-Origin-Url;
}
return (lookup);
}
}
sub vcl_pipe {
remove bereq.http.X-Turpentine-Secret-Handshake;
set bereq.http.Connection = "close";
}
sub vcl_hash {
if(false && req.http.X-Varnish-Cache-Url) {
set req.hash += req.http.X-Varnish-Cache-Url;
} else {
set req.hash += req.url;
}
set req.hash += req.url;
if (req.http.Host) {
set req.hash += req.http.Host;
} else {
set req.hash += server.ip;
}
set req.hash += req.http.Ssl-Offloaded;
if (req.http.X-Normalized-User-Agent) {
set req.hash += req.http.X-Normalized-User-Agent;
}
if (req.http.Accept-Encoding) {
set req.hash += req.http.Accept-Encoding;
}
if (req.http.X-Varnish-Store || req.http.X-Varnish-Currency) {
set req.hash += "s=";
set req.hash += req.http.X-Varnish-Store;
set req.hash += "&c=";
set req.hash += req.http.X-Varnish-Currency;
}
if (req.http.X-Varnish-Esi-Access == "private" &&
req.http.Cookie ~ "frontend=") {
set req.hash += regsub(req.http.Cookie, "^.*?frontend=([^;]*);*.*$", "\1");
}
if (req.http.X-Varnish-Esi-Access == "customer_group" &&
req.http.Cookie ~ "customer_group=") {
set req.hash += regsub(req.http.Cookie, "^.*?customer_group=([^;]*);*.*$", "\1");
}
return (hash);
}
sub vcl_fetch {
set req.grace = 15s;
set beresp.http.X-Varnish-Host = req.http.host;
set beresp.http.X-Varnish-URL = req.url;
if (req.url ~ "^(/shop/index\.php/radio_controlled_models/|/shop/index\.php/tools_and_accessories/|/shop/index\.php/toys_and_games/|/shop/index\.php/miscellaneous/|/shop/index\.php/default/|/shop/index\.php/rockets/|/shop/index\.php/trains/|/shop/index\.php/static/|/shop/media/|/shop/skin/|/shop/js/)(?:(?:index|litespeed)\.php/)?") {
remove beresp.http.Vary;
if (beresp.status != 200 && beresp.status != 404) {
set beresp.ttl = 15s;
return (pass);
} else {
if (beresp.http.Set-Cookie) {
set beresp.http.X-Varnish-Set-Cookie = beresp.http.Set-Cookie;
remove beresp.http.Set-Cookie;
}
remove beresp.http.Cache-Control;
remove beresp.http.Expires;
remove beresp.http.Pragma;
remove beresp.http.Cache;
remove beresp.http.Age;
if (beresp.http.X-Turpentine-Esi == "1") {
esi;
}
if (beresp.http.X-Turpentine-Cache == "0") {
set beresp.cacheable = false;
set beresp.ttl = 15s;
return (pass);
} else {
set beresp.cacheable = true;
if (req.http.X-Opt-Force-Static-Caching == "true" &&
bereq.url ~ ".*\.(?:css|js|jpe?g|png|gif|ico|swf)(?=\?|&|$)") {
set beresp.ttl = 28800s;
set beresp.http.Cache-Control = "max-age=28800";
} else if (req.http.X-Varnish-Esi-Method) {
if (req.http.X-Varnish-Esi-Access == "private") {
if (req.http.Cookie ~ "frontend=") {
set beresp.http.X-Varnish-Session = regsub(req.http.Cookie,
"^.*?frontend=([^;]*);*.*$", "\1");
}
if (req.http.X-Varnish-Esi-Method == "ajax") {
set beresp.ttl = 15s;
return (pass);
} else {
set beresp.ttl = 3600s;
}
} else {
if (req.http.X-Varnish-Esi-Method == "ajax") {
set beresp.http.Cache-Control =
"max-age=3600";
}
set beresp.ttl = 3600s;
}
} else {
set beresp.ttl = 3600s;
}
}
}
return (deliver);
}
}
sub vcl_deliver {
if (req.http.X-Varnish-Faked-Session) {
call generate_session_expires;
set resp.http.Set-Cookie = req.http.X-Varnish-Faked-Session "; expires="
resp.http.X-Varnish-Cookie-Expires "; path=/";
if (req.http.Host) {
set resp.http.Set-Cookie = resp.http.Set-Cookie
"; domain=" regsub(req.http.Host, ":\d+$", "");
}
set resp.http.Set-Cookie = resp.http.Set-Cookie "; HttpOnly";
remove resp.http.X-Varnish-Cookie-Expires;
}
if (req.http.X-Varnish-Esi-Method == "ajax" && req.http.X-Varnish-Esi-Access == "private") {
set resp.http.Cache-Control = "no-cache";
}
set resp.http.X-Opt-Debug-Headers = "false";
if (resp.http.X-Opt-Debug-Headers == "true" || client.ip ~ debug_acl ) {
set resp.http.X-Varnish-Hits = obj.hits;
set resp.http.X-Varnish-Esi-Method = req.http.X-Varnish-Esi-Method;
set resp.http.X-Varnish-Esi-Access = req.http.X-Varnish-Esi-Access;
set resp.http.X-Varnish-Currency = req.http.X-Varnish-Currency;
set resp.http.X-Varnish-Store = req.http.X-Varnish-Store;
} else {
remove resp.http.X-Varnish;
remove resp.http.Via;
remove resp.http.X-Powered-By;
remove resp.http.Server;
remove resp.http.X-Turpentine-Cache;
remove resp.http.X-Turpentine-Esi;
remove resp.http.X-Turpentine-Flush-Events;
remove resp.http.X-Turpentine-Block;
remove resp.http.X-Varnish-Session;
remove resp.http.X-Varnish-Host;
remove resp.http.X-Varnish-URL;
remove resp.http.X-Varnish-Set-Cookie;
}
remove resp.http.X-Opt-Debug-Headers;

when i change 
if(false && req.http.X-Varnish-Cache-Url)
to 
if (req.http.X-Varnish-Cache-Url)
in 172 line 
varnishd -C -f var/default.vcl 
execute without error

also before this issue i need make changes from this bug 

Failed to apply the VCL to 127.0.0.1:6082: Got unexpected response code from Varnish: 106 Message from VCC-compiler: Syntax error in condition, expected '(', '!' or variable name, found 'true' (input Line 155 Pos 5) if (true && req.url ~ "[?&](utm_source|utm_medium|utm_campaign|utm_content|utm_term|gclid|cx|ie|cof|siteurl)=") { ----####--------------------------------------------------------------------------------------------------------- Running VCC-compiler failed, exit 1 VCL compilation failed)

https://github.com/nexcess/magento-turpentine/issues/890

vim app/code/community/Nexcessnet/Turpentine/misc/version-2.vcl
#        if ({{enable_get_ignored}} && req.url ~ "[?&]({{get_param_ignored}})=") {
        if (req.url ~ "[?&]({{get_param_ignored}})=") {

so as i see bug 890 (https://github.com/nexcess/magento-turpentine/issues/890) not added to code and also there is new one which i post you.

**Comment by vova3379** [comment]
giive addition info about varnish version
[root@hobrc shop]# rpm -qa | grep varnish
varnish-2.1.5-5.el6.x86_64
varnish-libs-2.1.5-5.el6.x86_64

about 890 bug i remove 
if ({{enable_get_ignored}} && req.url ~ "[?&]({{get_param_ignored}})=") {
to 
if (req.url ~ "[?&]({{get_param_ignored}})=") {
as suggest by aricwatson commented on 29 Sep, strange that you do not add it to code untill now

**Comment by miguelbalparda** [comment]
I suggest you to install Varnish 3/4, we are about to stop supporting Varnish 2 and moving forward with new features only compatible with newer versions.
