### ISSUE TITLE
Backend navigation has issues when Varnish ESI Blocks is enabled

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#1048]
I downloaded and installed an extension (e.g. http://www.magentocommerce.com/magento-connect/manufacturer-brand-logo.html). This extension is adding its own section in backend navigation (e.g. Biztech). I cleared the cached, sessions, cookies, browser cache, restarted varnish.

<strong>Here is Cache Management page.</strong>

![image2](https://cloud.githubusercontent.com/assets/8360474/11766655/9902c6a2-a19a-11e5-99ef-32af6f082c13.jpg)

<strong>I can see Biztech sub-menu (Manage Manufacturer). If I click on the link I am redirected to Dashboard page.</strong>

![image1](https://cloud.githubusercontent.com/assets/8360474/11766649/78dcead8-a19a-11e5-9014-30e21913f144.jpg)

<strong>I will disable Varnish ESI Blocks in Cache Management Page.</strong>

![image3](https://cloud.githubusercontent.com/assets/8360474/11766746/7172f7e4-a19d-11e5-9079-88f329bd49fe.jpg)

<strong>Once Varnish ESI Cache Blocks is disabled I can access "Manage Manufacturer" section Biztech menu.</strong>

![image4](https://cloud.githubusercontent.com/assets/8360474/11766708/836b1d74-a19c-11e5-8f4e-6155e576acb9.jpg)

I tested other two extensions which add their own sections in backend navigation menu and their sub-categories cannot be accessed too. This is an issue related to caching policies. I thought the whole backend content is skipping Varnish cache by default, but it is not.

**Comment by ADDISON74** [comment]
And here is the link for Manage Manufacturers section:

https://www.mydomain.com/index.php/manufacturer/adminhtml_manufacturer/index/key/0d6d48d941f4e912d5c656d8faf48235/

Adding a part of this URL <strong>relative to Magento root path</strong> fixed the issue. If you add just adminhtml_manufacturer as url it won't work.

Correct URL Blacklist: manufacturer/adminhtml_manufacturer.

Please check how Turpentine policies are setup by default for backend to avoid adding Blacklist Url's. Many users could have the same issue with extensions which are adding their own links in backend navigation.

**Comment by miguelbalparda** [comment]
This seems to be a bad practice from the extension vendor. https://www.mydomain.com/index.php/manufacturer/adminhtml_manufacturer/index/key/0d6d48d941f4e912d5c656d8faf48235/ is not a valid admin url and it was higly discouraged in one of the latest patches Magento made public. For what is worth, Magento interprets this URL as a frontend URL and that is why Turpentine is acting as it was a non admin url.

**Comment by ADDISON74** [comment]
I agree and thank you for your explanation. I will get rid off such extension because the developer doesn't know making a professional job.
