### ISSUE TITLE
Add to cart twice doesn't work - Ajax

### ISSUE THREAD

**Issue by treestonemedia** [nexcess/magento-turpentine#1053]
Our Magento site uses Ajax instant cart from Mageworx http://www.mageworx.com/ajax-cart-magento-extension.html 
When on a category page, if we add the same item to cart twice,it only gets added once.
The second time we hit add to cart, it instantly returns a message that the product was added - but it didn't.

**Comment by aricwatson** [comment]
I would suggest adding the path used by the ajax script to the URL blacklist to see if the ajax calls are getting cached.

**Comment by ADDISON74** [comment]
Sometimes URLs called in Ajax requests can be found in Apache logs. Personally I found a lot of URLs there which caused me trouble. I added them into URL Blacklist as @aricwatson said and it worked as expected.

**Comment by treestonemedia** [comment]
That worked, Thanks!
