### ISSUE TITLE
Amazon Payments

### ISSUE THREAD

**Issue by treestonemedia** [nexcess/magento-turpentine#1054]
We have a Magento site with Amazon Payments https://github.com/amzn/amazon-payments-magento-plugin 
When a customer selects "pay with Amazon" he gets logged in to Amazon and then when he returns to Magento, the cart is emptied.

**Comment by aricwatson** [comment]
What version of Turpentine are you using? We recently fixed some checkout caching bugs that might be related.

Aside from that, does your site use a custom checkout path? It might be worth adding those URLs to the URL blacklist to avoid caching there. Or, if there's a 'return landing page' from amazon that the user is directed to, you could try adding that path to the blacklist URL.

**Comment by treestonemedia** [comment]
HI,

we're using 0.6.7
The checkout URL's are already in the blacklist.
I tried adding the URL that Amazon posts back to but that didn't help much

**Comment by miguelbalparda** [comment]
@treestonemedia when you return from Amazon to your site, what is the url you see? When you say the cart is emptied, does it work if you visit site.com/checkout/cart?

**Comment by treestonemedia** [comment]
@miguelbalparda when returning from Amazon the URL is site.com/amazon_payments/checkout/authorize/#access_token=At.......

Because the cart gets emptied by this request, Magento automatically redirects to site.com/checkout/cart which then generates an error message that the cart is empty.

**Comment by miguelbalparda** [comment]
I opened an issue https://github.com/amzn/amazon-payments-magento-plugin/issues/226 to see if the extension developers have some input on this matter.

**Comment by dbrent-amazon** [comment]
Hello. For debugging purposes, please disable Login with Amazon (Leave Pay with Amazon enabled). Add something to your cart and see if it empties. I've seen this multiple times with a standard Magento install and it may be unrelated to this project.

**Comment by treestonemedia** [comment]
@dbrent-amazon thanks for the quick response!
Disabling login with Amazon, worked like a charm! I was able to successfully checkout using Pay with Amazon.

**Comment by dbrent-amazon** [comment]
That's great... but also bad... in that you cannot use Login with Amazon. My team doesn't currently know the root cause of that issue. Perhaps the developers of the Magento plug-in do (Bear Group). You could log an issue on that project. https://github.com/amzn/amazon-payments-magento-plugin

**Comment by ngrices** [comment]
@treestonemedia can you check the exception log for when the error was occurring. My guess is that it is failing to create the customer record somehow during the authentication.

**Comment by miguelbalparda** [comment]
Thank you @ngrices and @dbrent-amazon for the help! I'll mark this issue as solved, feel free to keep the talk here anyway.

**Comment by treestonemedia** [comment]
@ngrices there is no exception being recorded

**Comment by ngrices** [comment]
@treestonemedia can you contact me directly @ ngrice@amazon.com

**Comment by ngrices** [comment]
Connected with @treestonemedia and he found another workaround.
Turns out that you can leave Login with Amazon enabled as long as you blacklist the path 'amazon_payments/checkout/authorize' from the varnish cache.

I will add to our FAQ's as well. 
Thanks

**Comment by miguelbalparda** [comment]
Amazing, thank you again @ngrices!
