### ISSUE TITLE
Redirect issue related to FORM_KEY and PARAM_NAME_URL_ENCODED

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#1058]
Removing items from side blocks like [Compare Products] or [Mini-Cart] is not working properly. In my opinion there are issues related to URLs having form_keys, encoded parameters or a combination of these two. Most of the URLs in Magento are created like this:

checkout/cart/add
/app/code/core/Mage/Checkout/Helper/Cart.php
```php
/**
 * Retrieve url for add product to cart
 *
 * @param Mage_Catalog_Model_Product $product
 * @param array $additional
 * @return string
 */
public function getAddUrl($product, $additional = array())
{
    $routeParams = array(
        Mage_Core_Controller_Front_Action::PARAM_NAME_URL_ENCODED => $this->_getHelperInstance('core')
            ->urlEncode($this->getCurrentUrl()),
        'product' => $product->getEntityId(),
        Mage_Core_Model_Url::FORM_KEY => $this->_getSingletonModel('core/session')->getFormKey()
    );

    if (!empty($additional)) {
        $routeParams = array_merge($routeParams, $additional);
    }

    if ($product->hasUrlDataObject()) {
        $routeParams['_store'] = $product->getUrlDataObject()->getStoreId();
        $routeParams['_store_to_url'] = true;
    }

    if ($this->_getRequest()->getRouteName() == 'checkout'
        && $this->_getRequest()->getControllerName() == 'cart') {
        $routeParams['in_cart'] = 1;
    }

    return $this->_getUrl('checkout/cart/add', $routeParams);
}
```
checkout/cart/delete
/app/code/core/Mage/Checkout/Block/Cart/Item/Renderer.php
```php
/**
 * Get item delete url
 *
 * @return string
 */
public function getDeleteUrl()
{
    if ($this->hasDeleteUrl()) {
        return $this->getData('delete_url');
    }

    return $this->getUrl(
        'checkout/cart/delete',
        array(
            'id'=>$this->getItem()->getId(),
            Mage_Core_Controller_Front_Action::PARAM_NAME_URL_ENCODED => $this->helper('core/url')->getEncodedUrl()
        )
    );
}
```

In the above example adding a product to cart has a combination of uenc and form_key in URL, but removing has only uenc. Using Varnish/Turpentine I discovered for removing actions products are removed properly, but I am redirected to other pages instead of staying on the same page. If I am visiting a category and removing an item from Mini-Cart I will be redirected to Cart Page. If I am removing a product from comparison list or clearing the whole list I am redirected to the last page I added a product to comparison. 

I tried adding uenc, form_key, catalog/product_compare/add,  catalog/product_compare/remove, catalog/product_compare/clear to URL Blacklist but I did't get any positive results. The only way to solve this was to change some templates or directly editing Magento core files for not adding encoded parameters and form_keys in removing URLs. I an not a fan of rewriting Magento core but at least this worked for me.

<strong>COMPARE</strong>

File: /app/code/local/Mage/Catalog/Helper/Product/Compare.php

```php
/**
* Retrieve remove item from compare list url
 *
 * @param   $item
 * @return  string
 */
public function getRemoveUrl($item)
{
    $params = array(
        'product' => $item->getId()/**,
        Mage_Core_Controller_Front_Action::PARAM_NAME_URL_ENCODED => $this->getEncodedUrl()**/
    );
    return $this->_getUrl('catalog/product_compare/remove', $params);
}

/**
 * Retrieve clear compare list url
 *
 * @return string
 */
public function getClearListUrl()
{
    $params = array(
        Mage_Core_Controller_Front_Action::PARAM_NAME_URL_ENCODED => $this->getEncodedUrl()
    );
    return $this->_getUrl('catalog/product_compare/clear'/**, $params)**/;
}
```

<strong>MINI-CART</strong>

File: /app/code/core/Mage/Checkout/Block/Cart/Item/Renderer.php

```php
**
 * Get item delete url
 *
 * @return string
 */
public function getDeleteUrl()
{
    if ($this->hasDeleteUrl()) {
        return $this->getData('delete_url');
    }

    return $this->getUrl(
        'checkout/cart/delete',
        array(
            'id'=>$this->getItem()->getId()/**,
            Mage_Core_Controller_Front_Action::PARAM_NAME_URL_ENCODED => $this->helper('core/url')->getEncodedUrl()**/
        )
    );
}
```

Here is what I found digging this Forum issue #119:

@aheadley: "This should actually be fixed as of 0.5.2 . Turpentine will now generally redirect users back to the page they were on instead of to /checkout/cart/ for most cases."

So Turpentine is redirecting the users but meanwhile we got form_keys and encoded params in URLs. Did you check how Turpentine redirect users in the latest version? Please do a check how an URL is processing before and after Varnish/Turpentine. I think there are some issues which must be corrected.

**Comment by ADDISON74** [comment]
I guess for such of issues we need Turpentine implementations for Mini-Cart, Compare and other side blocks same like this: https://github.com/deivisonarthur/Inovarti_FixAddToCartMage18 instead of editing and rewriting Magento core files ...

**Comment by ADDISON74** [comment]
Please check this out. Maybe you can integrate this code in Turpentine.

https://bitbucket.org/supportdesk_nl/turpertine-formkey-workaround

**Comment by aricwatson** [comment]
We're still investigating how best to fix the redirect issue.

> Please check this out. Maybe you can integrate this code in Turpentine.

Unfortunately, this essentially disables CSRF protection and our goal is for Turpentine to not decrease security in any way.

**Comment by ADDISON74** [comment]
Without doing this at least comparison actions like clear all or delete individual items won't work. I did not use that plugin, but I asked for help how to use it. There are a few people who claim it is working pretty well. In this moment I am using the modifications in Magento core files but looking for an elegant way to avoid these issues related to from key and encoded urls.

**Comment by aricwatson** [comment]
Closing this old issue - for reference, the "observer fix" in [settings](https://github.com/nexcess/magento-turpentine/wiki/Configuration#general-options) does provide this option (at the cost of losing CSRF protection). 

We're always interested in any ideas how to preserve CSRF protection *and* avoid having to pass the first request!

**Comment by akhiltanveer** [comment]
i have serious problem with my magento 1.9 store
this is my original question please help me fix this
https://magento.stackexchange.com/questions/188020/403-forbidden-error-on-few-links-magento-1-9-2

http://www.smartcityfood.in/      is my store
a normal link with form key is 

http://www.smartcityfood.in/seasons/customer/account/login/referer/aHR0cDovL3d3dy5zbWFydGNpdHlmb29kLmluL3NlYXNvbnMvP19fX1NJRD1V/

an abnormal link in some areas of my site is 

http://www.smartcityfood.in/seasons/customer/account/login/referer/aHR0cDovL3d3dy5zbWFydGNpdHlmb29kLmluL3NlYXNvbnMvc3RhcnRlcnMvZHJ5LWl0ZW1zLmh0bWw_X19fU0lEPVU,/

a malicious code is added to form key
 **_X19fU0lEPVU,/**
how can i fix this
