### ISSUE TITLE
No block node found with @Name

### ISSUE THREAD

**Issue by evanpetersen** [nexcess/magento-turpentine#1059]
Here's a link to the question on StackExchange: http://magento.stackexchange.com/questions/94616/no-block-node-found-with-name-wholesale-grid

After adding a block via local.xml and designating esiOptions, Turpentine can't seem to find the block.

**Comment by evanpetersen** [comment]
I should add that this is a multistore

**Comment by evanpetersen** [comment]
Turns out that System -> Design is not taken into consideration when processing layout xml for an esi request.  It IS taken into consideration when making the decision to encode a block for later ESI retrieval, however, which results in the "No block node found with @name" case.

I believe the label should be changed from question to bug.

**Comment by miguelbalparda** [comment]
I think https://github.com/nexcess/magento-turpentine/pull/972 it's not merged with master. Can you try devel and let us know if it worked?

**Comment by evanpetersen** [comment]
I looked at the diff and it seems like that would only serve to compound the problem.  I'll test it out tomorrow and report back.

As an aside, does your git workflow dictate that you merge devel into master?

**Comment by miguelbalparda** [comment]
Yes, we merge devel into master once the code is fully tested. We encourage developers to check the code in devel to discover potential issues or better solutions.

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
