### ISSUE TITLE
Failed to apply the VCL to 127.0.0.1:6082: Varnish data to write over length limit by 10225 characters

### ISSUE THREAD

**Issue by Xavier027** [nexcess/magento-turpentine#1063]
Hello,

I have the following error when I try to apply the varnish config on the magento cache management page:

``` 
Failed to apply the VCL to 127.0.0.1:6082: Varnish data to write over length limit by 10225 characters
Varnish esi_syntax param is not set correctly, please see these instructions to fix this warning.
``` 

I have read several topics, have edited my ect/sysconfig/varnish and added -p cli_buffer=16384 to my file:
``` 
DAEMON_OPTS="-a ${VARNISH_LISTEN_ADDRESS}:${VARNISH_LISTEN_PORT} \
             -f ${VARNISH_VCL_CONF} \
             -T ${VARNISH_ADMIN_LISTEN_ADDRESS}:${VARNISH_ADMIN_LISTEN_PORT} \
             -t ${VARNISH_TTL} \
             # -w ${VARNISH_MIN_THREADS},${VARNISH_MAX_THREADS},${VARNISH_THREAD_TIMEOUT} \
			 -p esi_syntax=0x2 \
			 -p cli_buffer=16384 \
			 # -p cli_buffer=16384 \
			 -p thread_pool_add_delay=2 \
			 -p thread_pools=4 \
			 -p thread_pool_min=200 \
			 -p thread_pool_max=4000 \
			 -w ${VARNISH_THREAD_TIMEOUT} \
             -u varnish -g varnish \
             -S ${VARNISH_SECRET_FILE} \
			 -s malloc,2G"
             #-s ${VARNISH_STORAGE}"
``` 
But I still get the error. Does somebody have any idea where the issue could be coming from?

Thanks in advance for your help !

**Comment by miguelbalparda** [comment]
Have you restarted varnish after the change? You can also start the service manually with the parameter you need to change. It also seems
You commented the same parameter you are trying to use with the exact same number.

**Comment by miguelbalparda** [comment]
I would say you try with a bigger value and see if the number in the error decreases.

**Comment by Xavier027** [comment]
I migualbalparda,

yes, I restart after each change varnish with:

``` 
service varnish restart
``` 
My Magento Store version is 1.9.0.1, I deactive the compilation and the cache before aplying the varnish configuration.

I have changed the value of varnish (I have increased the value of -p cli_buffer and removed comment of -p cli_buffer) with:
``` 
DAEMON_OPTS="-a ${VARNISH_LISTEN_ADDRESS}:${VARNISH_LISTEN_PORT} \
             -f ${VARNISH_VCL_CONF} \
             -T ${VARNISH_ADMIN_LISTEN_ADDRESS}:${VARNISH_ADMIN_LISTEN_PORT} \
             -t ${VARNISH_TTL} \
             # -w ${VARNISH_MIN_THREADS},${VARNISH_MAX_THREADS},${VARNISH_THREAD_TIMEOUT} \
			 -p esi_syntax=0x2 \
			 -p cli_buffer=25000 \
			 -p thread_pool_add_delay=2 \
			 -p thread_pools=4 \
			 -p thread_pool_min=200 \
			 -p thread_pool_max=4000 \
			 -w ${VARNISH_THREAD_TIMEOUT} \
             -u varnish -g varnish \
             -S ${VARNISH_SECRET_FILE} \
			 -s malloc,2G"
``` 
And the number in the error increases instead:

``` 
Failed to apply the VCL to 127.0.0.1:6082: Varnish data to write over length limit by 10226 characters
Varnish esi_syntax param is not set correctly, please see these instructions to fix this warning.
``` 
Any idea why it doesn't work?

**Comment by miguelbalparda** [comment]
It seems to be a Varnish issue rather than a turpentine problem. I'll suggest you to check your installation and also to try to start the service manually with a bigger number since it seems your changes are not being taken into account.

**Comment by Xavier027** [comment]
Hi Miguelbalparda,

I followed your advice and
- have doublechecked the version of Varnish, which is 3.0.7.
- tested Varnish with the following minimal configuration in /etc/varnish/default.vcl:

``` 
backend default {
  .host = "127.0.0.1";
  .port = "8080";
}

sub vcl_recv {
    return(lookup);
}

sub vcl_fetch {
    return (deliver);
}
``` 
I still have the same error. Varnish seems to be working fine for all static files. Can the issue be coming from writable rights ? I had several times this issue when i switched from apache to nginx.

**Comment by miguelbalparda** [comment]
I don't think this issue is related to permissions. I do think maybe you are editing the incorrect file/line or you are not starting the service with the correct options. See https://github.com/nexcess/magento-turpentine/issues/1026 for more info on how to start varnish manualy with -p cli_buffer=81920

**Comment by Xavier027** [comment]
Hi Miguelbalparda,

This is really strange... 
I think that my file /ect/sysconfig/varnish is beeing loaded when I start varnish because I specified manually in the file the port :80 (VARNISH_LISTEN_PORT=80) and I get the following error if I remove all parameter to DAEMON_OPTS (DAEMON_OPTS="").

``` 
Starting Varnish Cache: $DAEMON_OPTS empty.
``` 

It seems that the parameter in $DAEMON_OPTS are being ignored. I could confirm that the comments (#) in $DAEMON_OPTS cause an issue. 

I have restarted manually varnish with an high cli_buffer value and took a look at the parameters.
``` 
pkill varnishd
varnishd -f /etc/varnish/default.vcl -p cli_buffer=150000 -T :6082 -d
start 
param.show
``` 

The value seems to be correct with the manual start of varnish in debug mode:
``` 
cli_buffer                  150000 [bytes]
``` 

Therefore, I went to the backoffice of Magento and I tried to apply the varnish config but I got the following error:

``` 
Failed to apply the VCL to 127.0.0.1:6082: Got unexpected response code from Varnish: 106 Message from VCC-compiler: Module std already imported. ('input' Line 50 Pos 1) -- ('input' Line 50 Pos 10) import std; ##########- Previous import was here: ('input' Line 25 Pos 1) -- ('input' Line 25 Pos 10) import std; ##########- Running VCC-compiler failed, exit 1 VCL compilation failed 
``` 

``` 
Varnish esi_syntax param is not set correctly, please see these instructions to fix this warning.
``` 

Do you know where it's coming from?

**Comment by Xavier027** [comment]
Hi miguelbalparda,

I found out where the issue is coming from. I had created a file custom_include.vcl in app/code/community/Nexcessnet/Turpentine/misc. It seems that this file couldn't be overwritten by Turpentine.

Varnish is now correctly configured. Now, when I try to apply the varnish config in the cache management page, Magento is loading until I get an error (connection broken). I couldn't find the reason of the issue yet. Do you have an idea?

Thanks in advance !

**Comment by ADDISON74** [comment]
Turpentine is copying custom_include.vcl file content and paste it in default.vcl at a position. custom_include.vcl if is not created or just empty content it won't create any issue. In my case I don't have this file in the /misc folder. If I want it I can touch it or create it with a manually entered content. From my point of view just creating custom_include.vcl and getting working Varnish/Turpentine combination is a matter of luck, but actually this is not the solving of your issue.

This is not a Turpentine issue, just a mislead configuration. If systemd is responsible for managing the services use Google to find out how many issue it creates. In one of my posts I presented the right configuration in case you're using systemd. Just a clue, if systemd is used your editing configuration is not in /etc/default/varnish. What is the result of using this command: ps -ef | grep varnish? It tells you where is the configuration file and what parameters are using. Stay away for a while of using parameters thread_pools_*. Start with the default configuration not a custom one.

As an advice try making Varnish discussing with your webserver using the basic configuration without Magento or Turpentine. If this is working time to go forward. And please read Turpentine Wiki for configuration Varnish and Turpentine.

**Comment by Xavier027** [comment]
Hi Addison74,

Varnish is already working with a basic configuration:

**Comment by miguelbalparda** [comment]
@Xavier027 can I see the entire error you are having?

**Comment by Xavier027** [comment]
Hi Addison74, hi miguelbalparda,

**Addison74**
To tell the truth, I didn't really understand the part with systemd, sorry :-(. I'll try to inform myself fast on this subject.

Varnish is already working with a basic configuration. I'm already using it since months with my server to cache sucessfully my static files from websites without magento. Thing was the comment in DAEMON made varnish ignore the content past -t ${VARNISH_TTL} \ in my first post. Thus the configuration stayed basic and couldn't interpret the following parameters such as cli_buffer. it was a bug I wasn't aware until now, sorry about that. (well, I'm a n00b with basic UNIX knowledge and the guy who configured the varnish file before wasn't probably aware of if too)

This is now solved, I have removed the comments and after several crash because I tried to allocate too much memory with malloc, I have this configuration (I'm still reading lot of articles about malloc to decide if I add it with 256M or 512MB):

``` 
DAEMON_OPTS="-a ${VARNISH_LISTEN_ADDRESS}:${VARNISH_LISTEN_PORT} \
             -f ${VARNISH_VCL_CONF} \
             -T ${VARNISH_ADMIN_LISTEN_ADDRESS}:${VARNISH_ADMIN_LISTEN_PORT} \
             -t ${VARNISH_TTL} \
             -w ${VARNISH_MIN_THREADS},${VARNISH_MAX_THREADS},${VARNISH_THREAD_TIMEOUT} \
			 -p esi_syntax=0x2 \
			 -p cli_buffer=20000 \
			 -p thread_pool_add_delay=2 \
             -S ${VARNISH_SECRET_FILE}"
```

Please find below the details concerning your command:

``` 
[root@s16851519 ~]# ps -ef | grep varnish
root      1626     1  0 01:39 ?        00:00:01 /usr/sbin/varnishd -P /var/run/varnish.pid -a :80 -f /etc/varnish/default.vcl -T 127.0.0.1:6082 -t 3600 -w 100,3  000,120 -p esi_syntax=0x2 -p cli_buffer=20000 -p thread_pool_add_delay=2 -S /etc/varnish/secret
nobody    1627  1626  0 01:39 ?        00:01:16 /usr/sbin/varnishd -P /var/run/varnish.pid -a :80 -f /etc/varnish/default.vcl -T 127.0.0.1:6082 -t 3600 -w 100,3000,120 -p esi_syntax=0x2 -p cli_buffer=20000 -p thread_pool_add_delay=2 -S /etc/varnish/secret
root      7245  7223  0 12:16 pts/0    00:00:00 grep varnish
``` 

**miguelbalparda**
There isn't any error message. After I apply the varnish config file in the cache management page of Magento, Magento tries to load anew the cache management page (with probably the error or success message) but after 1-2 minutes, the page breaks down and I get the error "verbindung unterbrochen" (german, I guess something like "connection interrupted" in english) after 3 minutes. Looks a bit like a timeout, Varnish crashes and I have the restart the service to make Varnish work again.

I found out after reading several topics/pages that a file custom_include.vcl  should be created in /app/code/community/Nexcessnet/Turpentine/misc so I did some tests.

But if I create manually a file custom_include.vcl in /app/code/community/Nexcessnet/Turpentine/misc, I get the following error:
``` 
Failed to apply the VCL to 127.0.0.1:6082: Got unexpected response code from Varnish: 106 Message from VCC-compiler: Module std already imported. ('input' Line 50 Pos 1) -- ('input' Line 50 Pos 10) import std; ##########- Previous import was here: ('input' Line 25 Pos 1) -- ('input' Line 25 Pos 10) import std; ##########- Running VCC-compiler failed, exit 1 VCL compilation failed 
``` 
I sincerelly hope that the issue isn't related to my varnish configuration because if that's the case, I'm really ashamed to make you lose once again your time for something which isn' t Turpentine.

Many thanks for your support !

**Comment by ADDISON74** [comment]
- Did you set up a symlink from your magento /var folder to /etc/varnish/default.vcl? Does this file has the right permissions?
- Did you set up in Backend Turpentine for Varnish 3.0 instead of Auto?
- Is it your Varnish installed from official repository or other repository or source? 

Making Varnish/Turpentine working together is so simple without any issues. Personally I am using Varnish repository and 4 as version. Configuring Varnish/Webserver and Turpentine is taking no more than a few minutes. Set up a VM with Virtualbox which is free and install your Linux OS for testing.

**Comment by Xavier027** [comment]
Hi Addison74,

* Did you set up a symlink from your magento /var folder to /etc/varnish/default.vcl? Does this file has the right permissions?

No, I didn't because I have done the classic instation through magentoconnect. I think that the file has the right permissions because a file default.vlc is being created in var/. 
Do you have a way to find out if that's the case?

* Did you set up in Backend Turpentine for Varnish 3.0 instead of Auto?

Yes, I did. I have done a test with automatic too, I have the same issue.

* Is it your Varnish installed from official repository or other repository or source? 

Varnish has been installed from official repository.

I agree that Varnish/Turpentine can be working together without any issue, that it's simple, that it can be done in a few minutes and everything. Thing is it's done easily by experts and in most cases a lot more slowly by other persons.

**Comment by Xavier027** [comment]
I just have seen that the file var/default.vlc doesn't get actualized when I apply the varnish config in the cache management page:

``` 
-rwxr-xr-x  1 www-data psacln    8631 Jan  8 01:46 default.vcl
``` 

Could the issue be coming from here?

Thanks for the feedback !

**Comment by ADDISON74** [comment]
In /etc/varnish/default.vcl is the default configuration for starting Varnish with parameters. When you want using Turpentine VCL you have to follow these steps:

- check existence of Turpentine VCL configuration in Magento/var. just delete it, change a few parameters in Turpentine backend and save again. check file content
- backup /etc/varnish/default.vcl by moving it to same directory with other name
- create a symbolic link from Magento/var to /etc/varnish/default.vcl
- restart varnish service

If you services are listening on right ports you have to connect them correctly. It will be great if you present your steps for installation of Varnish/Turpentine for working with Magento and your webserver.

**Comment by ADDISON74** [comment]
... and for permissions:

```
root@server:~# ls -lah /etc/varnish/default.vcl
lrwxrwxrwx 1 root root 41 Dec  1 23:23 /etc/varnish/default.vcl -> /home/test_user/public_html/var/default.vcl
```

```
root@server:~# ls -lah /home/test_user/public_html/var/default.vcl
-rw-rw-rw- 1 www-data www-data 9.8K Jan  2 20:01 /home/test_user/public_html/var/default.vcl

```

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.

**Comment by aricwatson** [comment]
Just an update on this as I ran into the same issue in my own testing. There's a difference in how the `cli_buffer` is reported between Varnish 4.0.3 and Varnish 4.1

Varnish 4.1:

    varnishadm param.show | grep cli_buffer
    cli_buffer                 20000b [bytes]

Varnish 4.0.3:

    varnishadm param.show | grep cli_buffer
    cli_buffer                 16k [bytes]

This throws off Turpentine and it generates the 'over limit' error. The quick and dirty fix is to change a constant in `app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php' to this:

    const CLI_CMD_LENGTH_LIMIT = 16384;

That fixed the problem in my testing. We'll fix the issue better.
