### ISSUE TITLE
Connection Error try again later. 

### ISSUE THREAD

**Issue by fventurini** [nexcess/magento-turpentine#1064]
installing using magento connect manager I always obtain a 
Connection Error try again later.

may I have some permission problem or is there other out?

**Comment by miguelbalparda** [comment]
That is not something we control. You should ask Magento Connect or install the module in a different way.

**Comment by fventurini** [comment]
thanks miguel
to download tar.gz usable from connect manager, should I have to take a release (https://github.com/nexcess/magento-turpentine/releases)???

**Comment by miguelbalparda** [comment]
[Latest release.](https://github.com/nexcess/magento-turpentine/files/77154/latest.zip). The file is zipped, unzip it and then upload the tar.gz via Magento Connect.
