### ISSUE TITLE
Turpentine Removes All mod_expires Headers

### ISSUE THREAD

**Issue by sprankhub** [nexcess/magento-turpentine#1068]
Currently, Turpentine blindly removes all mod_expires headers via `unset beresp.http.Expires;` - see e.g. https://github.com/nexcess/magento-turpentine/blob/master/app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl#L318. Is that really sensible? I think it should be possible to define expires headers via htaccess AND using Varnish via Turpentine. Why is that not respected?

Thanks in advance!

**Comment by ADDISON74** [comment]
Personally I disabled mod_expires, mod_deflate. I let Varnish taking care of everything. mod_ssl is disable too. I am doing SSL Offloading with Pound in front of Varnish for keeping Apache working with basic modules loaded and increasing performance it is visible.

**Comment by sprankhub** [comment]
Afaik, mod_expires and Varnish solve different issues. Varnish makes it fast on the server side by not calculating everything again and again. But mod_expires makes the client side faster, because resources can be cached on the client side.

I do not see any contradiction in using both.

**Comment by aricwatson** [comment]
This behavior has always been a part of the default VCL template, and I can't comment as to why it was originally decided to remove the mod_expires headers. If it's a problem, I'd suggest trying to use the *custom_include.vcl* option to preserve the headers.  Or you could just comment those lines out of the template, but watch out for your changes getting overwritten when update Turpentine!

**Comment by sprankhub** [comment]
Okay, I do not see any reason in removing the mod_expires headers in the default VCL and if noone else does, maybe this part can be removed from the default VCL?

If you decide for leaving it there, could you post an example for a `custom_include.vcl` with which the headers are preserved?

Thanks!

**Comment by aricwatson** [comment]
I've fiddled around with it a little and I'm not seeing an easy way to accomplish this (yet) with a custom_include.vcl file - I'd suggest commenting out the unset line in the appropriate VCL template if preserving the Expires header is critically important. I suspect https://github.com/nexcess/magento-turpentine/pull/1096 will make doing this via custom includes easier, but I haven't had time yet to evaluate it.

**Comment by sprankhub** [comment]
Is this really solved? I still do not see any valid reason why all mod_expires headers should be removed...

**Comment by sprankhub** [comment]
@aricwatson could you have a look at this issue again, please? I do not think it is solved...

**Comment by pieterjanliekens** [comment]
Default should be something like this:

**Leverage browser caching**
Page load times can be significantly improved by asking visitors to save and reuse the files included in your website.

- Reduces page load times for repeat visitors
- Particularly effective on websites where users regularly re-visit the same areas of the website
- Benefit-cost ratio: high
- Access needed
- General guidelines for setting expiries:

```
Truly static content (global CSS styles, logos, etc.) - access plus 1 year
Everything else - access plus 1 week
```

Is there a way to accomplish this in varnish?

Source: Gmetrix guidelines for pagespeed 04-01-2019
