### ISSUE TITLE
Variables not properly replaced in the vcl

### ISSUE THREAD

**Issue by popoviciandrei** [nexcess/magento-turpentine#1069]
Hi,

I try to apply the version-3.vcl on my varnish server, but I get this error: 
"Failed to apply the VCL to 127.0.0.1:6082: Got unexpected response code from Varnish: 106 Message from VCC-compiler: Expected an action, 'if', '{' or '}' ('input' Line 43 Pos 1) std.collect(req.http.Cookie); ###########------------------ Running VCC-compiler failed, exit 1 VCL compilation failed"

Looking deeper in the code found out this method inside Nexcessnet_Turpentine_Model_Varnish_Configurator_Abstract: 
protected function _formatTemplate( $template, array $vars ) {
        $needles = array_map( create_function( '$k', 'return "{{".$k."}}";' ),
            array_keys( $vars ) );
        $replacements = array_values( $vars );
        // do replacements, then delete unused template vars
        return preg_replace( '~{{[^}]+}}~', '',
            str_replace( $needles, $replacements, $template ) );
    }

Looks like this method is not properly replacing all the tags with str_replace, and then preg_replace is deleteing the non replaced ones. So the final vcl ends up with empty conditions like if() { }.

Any idea why is that!?

**Comment by miguelbalparda** [comment]
Can you paste your generated VCL here?

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
