### ISSUE TITLE
Session shared for first guest visits / incognito window visits

### ISSUE THREAD

**Issue by milansimek** [nexcess/magento-turpentine#1073]
Hi,

Recently we have been experiencing a strange issue when using Turpentine: Somehow the cart is shared between guest visitors. 

For example, when I open an incognito screen on my mobile phone and on my laptop and add something to the cart on one of the devices, it's also added to the cart of the second device.

**The behavior seems to be as follows:**
* This issue only happens on new sessions.
* Once a customer is logged in, the sessions aren't shared anymore
* If a customer logs in and back out, the session is also not shared
* It seems that the session is only shared between new guest sessions

**System details:**
* Magento v1.9.0.1 with the latest security patch
* Varnish v3.0.5
* Turpentine v0.6.8

**Webserver config:**
* HTTPS Nginx > Varnish > Apache

Besides that we have disabled the front-end form key for adding products to the cart using the following module:

https://bitbucket.org/supportdesk_nl/turpertine-formkey-workaround

Found on: https://github.com/nexcess/magento-turpentine/issues/345

Any advice would be very helpful. I'm unsure where to look further to debug the issue.

Thanks in advance!

**Comment by ADDISON74** [comment]
What cookie names and values do you get in both browsers? Once you are in icognito mode you should get a crawler session.

**Comment by aricwatson** [comment]
> It seems that the session is only shared between new guest sessions

Check out the cookies as @ADDISON74 mentioned - it sounds like a cookie is getting set somehow for new sessions, so that guests are effectively all sharing the same cookie.

**Comment by milansimek** [comment]
Thanks for the replies! I appreciate it.

The issue has to do with our live site, so I will have to set up an identical test site first to debug. 

Once the test site is set up I will check the cookies and post back here.

**Comment by milansimek** [comment]
I managed to fix the issue by removing the crawler IP address, which was set to 127.0.0.1

I guess because the reverse proxy set the IP to the localhost IP, this was causing the issue.

I've also added the following fix to .htaccess:

SetEnvIf Ssl-Offloaded on HTTPS=on
SetEnvIf X-Forwarded-For "^(\d{1,3}+\.\d{1,3}+\.\d{1,3}+\.\d{1,3}+).*" XFFCLIENTIP=$1

Not sure if it helps, I found that solution here: 
https://github.com/nexcess/magento-turpentine/issues/1052

We have the crawler turned off anyway, because we don't have a lot of pages.

Thanks for the help!

**Comment by ADDISON74** [comment]
@milansimek: could you please give me more details how did you use that module "turpertine-formkey-workaround"? I got this file but I need the steps for using it. Thank you.
