### ISSUE TITLE
Caching options not visible when enabling Turpentine

### ISSUE THREAD

**Issue by kanduvisla** [nexcess/magento-turpentine#1079]
Does anyone else have the issue that the caching options are no longer visible when Turpentine is enabled?

![screen shot 2016-01-22 at 11 35 55](https://cloud.githubusercontent.com/assets/346681/12508476/69481760-c0fc-11e5-925a-a303622a3be0.png)

I'm working with EE 1.13.1.0

**Comment by kanduvisla** [comment]
The weird part is, when I comment out the rewrite in `config.xml` for the block `adminhtml/cache_grid`, the caching options show up (without the varnish options that is). But is soon as I re-enable the rewrite and even leave the `_prepareCollection()`-method empty in `Nexcessnet_Turpentine_Block_Adminhtml_Cache_Grid`, the options disappear ...

**Comment by kanduvisla** [comment]
Another update: each time I try to reload the cache page, my `system.log`-file gets appended with:

    2016-01-22T15:18:46+00:00 ERR (3): Warning: fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known  in /vagrant/public/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php on line 323
    2016-01-22T15:18:46+00:00 ERR (3): Warning: fsockopen(): unable to connect to varnish:6082 (php_network_getaddresses: getaddrinfo failed: Name or service not known)  in /vagrant/public/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php on line 323
    2016-01-22T15:18:46+00:00 WARN (4): TURPENTINE: Error in Varnish action result for server [varnish:6082]: Failed to connect to Varnish on [varnish:6082]: (0) php_network_getaddresses: getaddrinfo failed: Name or service not known

**Comment by miguelbalparda** [comment]
Those errore seems to indicate you are not being able to connect to your Varnish instance from Magento. Check your secret key, the ports and the address to see if those values are correct and let us know if it helped.

**Comment by kanduvisla** [comment]
Ok, I'm a bit closer now, it seemed that my server settings where wrong. I now changed them to 127.0.0.1:6082 and the error is gone. But a new one arose:

    2016-01-22T15:23:34+00:00 WARN (4): TURPENTINE: Failed to parse param.show output to check esi_syntax value

Any idea what might cause this error?

**Comment by miguelbalparda** [comment]
Which version of varnish are you using? Is it correctly defined in the admin or is is set to Auto?

**Comment by kanduvisla** [comment]
I'm using 3.0.7. In the admin it's manually set to 3.0.x

**Comment by kanduvisla** [comment]
Ah, I noticed I forgotten the `-p esi_syntax=0x2`-parameter to my `DAEMON_OPTS`. I added it now and the error in my log is gone. However, my cache grid screen is still empty ... :-(

**Comment by miguelbalparda** [comment]
Do you have any other extensions installed that might be conflicting with Turpentine or with the admin grids?

**Comment by kanduvisla** [comment]
Not any caching-extensions that I'm aware of ... I'll check ...

**Comment by miguelbalparda** [comment]
Also check for any extensions rewriting the grid, not necessarily caching extensions.

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.

**Comment by jeroenvermeulen** [comment]
I also bumped into this problem at one customer.
It has nothing to do with whether your Varnish instance is working or not.
Did not find a real solution yet.
Workaround: edit `app/code/community/Nexcessnet/Turpentine/etc/config.xml`
Change:

**Comment by jeroenvermeulen** [comment]
I also bumped into this problem at one customer, Magento CE 1.9.1.1
It has nothing to do with whether your Varnish instance is working or not.

**Real solution found!** Took me a lot of research.

It's simple when you know it:

Set `System > Configuration > ADVANCED > Advanced > Disable Modules Output > Nexcess Turpentine` to `Enable`

*[Facepalm]*

**Comment by treestonemedia** [comment]
@jeroenvermeulen you rock! we were having the same issue, turns out someone had once tried to install the extension and set `System > Configuration > ADVANCED > Advanced > Disable Modules Output > Nexcess Turpentine`
to `Disable`

**Comment by jeroenvermeulen** [comment]
@treestonemedia You're welcome!
