### ISSUE TITLE
Varnish 4.1 + Magento EE 1.13.0.2: slow add to cart

### ISSUE THREAD

**Issue by marcop83** [nexcess/magento-turpentine#1081]
I am testing Magento EE 1.13.0.2 (no modification has been made to any file) with Varnish 4.1. Everything works fine but the add to cart action from the product page takes 20-30 seconds. Can you guys help me?
Thanks!

**Comment by miguelbalparda** [comment]
We don't have enough information to diagnose this. What makes you think this is a Varnish/Turpentine issue? Have you applied the VCL from the admin and filled everything like IPs, ports and the secret key?

**Comment by marcop83** [comment]
Yes I have applied the VCL and Varnish was working with Magento as expected. The only issue was the add to cart action.
I have switched to Varnish 4.0.3 keeping the same Magento instance and everything works perfectly.

**Comment by miguelbalparda** [comment]
Interesting, we will check Varnish 4.1 to see why is affecting performance. Thank you for the heads up!

**Comment by yssource** [comment]
The issue happens to me also, CE 1.9.2.4.
It is very slow to add product to cart. #1156
