### ISSUE TITLE
How do I disable the extension?

### ISSUE THREAD

**Issue by mobweb** [nexcess/magento-turpentine#1082]
I have a single server with one Varnish instance and two Magento installations (PRODUCTION and STAGING). What is the recommended way of ensuring that Varnish is only used for PRODUCTION?

**Comment by miguelbalparda** [comment]
This is not related to Turpentine. You should ask this in a place like http://serverfault.com/ or similar. You might be able to create a directive inside the VCL to pipe all the requests for a URL but Varnish will still be there listening to port 80.

**Comment by mobweb** [comment]
Oops, sorry for the confusion, I thought there might be a way to do it via the extension.

**Comment by miguelbalparda** [comment]
You might be able to do this using some hacks, but I think the best approach is to pipe all the requests for a matching domain. I would ask in SF, they might have a different opinion.

**Comment by mobweb** [comment]
Thanks a lot! Excuse me if this is the wrong place, but considering both shops (e.g. staging.domain.com and production.domain.com) are fine with using the same Varnish and Turpentine configuration, is there any reason not to do that? I would just leave Turpentine running on both shops.

**Comment by miguelbalparda** [comment]
We recommend using separated instances of Varnish but it is possible to configure it to be used by both sites. See #122 and http://stackoverflow.com/questions/3334023/configure-multiple-sites-with-varnish for more info.
