### ISSUE TITLE
Latest devel has syntax problems!

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#1085]
I installed two days ago the latest devel version for testing. I cleared the current version I used before as usual. Even the new configuration file is created on disk, I cannot start Varnish service. Checking why the service is not starting I see a message from VCC-compiler related to mistakes inside the code:

```php
Jan 31 14:43:15 www.mydomain.com varnishd[17654]: Message from VCC-compiler:
Jan 31 14:43:15 www.mydomain.com varnishd[17654]: Expected '{' got 'set'
Jan 31 14:43:15 www.mydomain.com varnishd[17654]: (program line 147), at
Jan 31 14:43:15 www.mydomain.com varnishd[17654]: ('input' Line 303 Pos 1)
Jan 31 14:43:15 www.mydomain.com varnishd[17654]: set resp.http.Set-Cookie = resp.http.Set
Jan 31 14:43:15 www.mydomain.com varnishd[17654]: ###-------------------------------------
Jan 31 14:43:15 www.mydomain.com varnishd[17654]: Running VCC-compiler failed, exited with
Jan 31 14:43:15 www.mydomain.com varnishd[17654]: VCL compilation failed
```

Initially I thought it is a Varnish issue, but it was properly installed and working before. I went further installing a devel version I have, it is two or three changes behind from December. It is working as expected, no issues, Varnish service starts normal. 

Then I installed master version which is 17 days old, and it is working without issues.

Please correct devel branch version asap. Thank you.

**Comment by ADDISON74** [comment]
Here is the error message I get in Magento backend: 

```html
Failed to apply the VCL to 127.0.0.1:6082: Got unexpected response code from Varnish: 106 Message from VCC-compiler: Expected '{' got 'set' (program line 147), at ('input' Line 303 Pos 1) set resp.http.Set-Cookie = resp.http.Set-Cookie + ###---------------------------------------------- Running VCC-compiler failed, exited with 2 VCL compilation failed
```

There is a syntax issue inside Turpentine module which creates for wrong Varnish configuration.

**Comment by ADDISON74** [comment]
Here we go in order to fix this:

```php
sub vcl_deliver {
if (req.http.X-Varnish-Faked-Session) {
set resp.http.Set-Cookie = req.http.X-Varnish-Faked-Session +
"; expires=" + resp.http.X-Varnish-Cookie-Expires + "; path=/";
if (req.http.Host) {
if (req.http.User-Agent ~ "^(?:ApacheBench/.*|.*Googlebot.*|JoeDog/.*Siege.*|magespeedtest\.com|Nexcessnet_Turpentine/.*)$") {
set resp.http.Set-Cookie = resp.http.Set-Cookie +
"; domain=" + regsub(req.http.Host, ":\d+$", "");
} else {
if (req.http.Host ~ "" && "" ~ "..")  <-- here is missing a {
set resp.http.Set-Cookie = resp.http.Set-Cookie +
"; domain=";
} else {
set resp.http.Set-Cookie = resp.http.Set-Cookie +
"; domain=" + regsub(req.http.Host, ":\d+$", "");
}
}
}
```

See above line <strong>if (req.http.Host ~ "" && "" ~ "..")  <-- here is missing a {</strong>.

If I add a "{" to that if statement, Varnish starts without any issues. Please correct the following file and create a new devel package asap:

/app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl (line 393)

Thank you.

**Comment by ADDISON74** [comment]
Here is where it started, the missing of "{" : 

https://github.com/nexcess/magento-turpentine/commit/62b3fc19065dd8e8e1689cac3e6c743dfcb32da2

**Comment by aricwatson** [comment]
Apologies, it does appear I committed that with a syntax error! Fixing now.

**Comment by aricwatson** [comment]
Fixed in https://github.com/nexcess/magento-turpentine/pull/1087 - sorry about that! Good catch.
