### ISSUE TITLE
WARNING: Do not upgrade/install in production to Varnish 4.0 branch on CentOS 7!

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#1088]
There is a bug in Varnish 4.0 branch version on CentOS 7 x64 which creates trouble with ESI policies. They won't work whatever you will try to do. If you install this lethal combination your pages content like products or side blocks will disappear. You can bring them back by disabling [ESI Varnish Blocks] in Cache Management. But this won't solve anything, you will get your blocks being cached! 

I spent almost a week for finding a solution out of Varnish and I did not find one. So I decided this morning to give a try with Varnish 4.1. It was a pleasant surprise to see everything working as normal, except a few small things which can be fixed. I suggest to anyone involve in developing this extension to make it working with Varnish 4.1 too. 

<strong>IMPORTANT:</strong> Do not upgrade/install in production Varnish 4.0.3 on CentOS 7 x64. Debian/Ubuntu flavors are not affected by this and you can continue using your Varnish 4.0 branch from their repos without any issues (for the moment).

More details about my journey here: #1086

**Comment by farazhkhan** [comment]
@ADDISON74 @jeroenvermeulen 

Can you please make cautionary note here at https://github.com/nexcess/magento-turpentine/wiki/Installation for people who are going to install it for CentOS 7.x because like me all CentOS users are facing issues with CentOS 7+Varnish. Had I ever known this I would have not installed it on CentOS 7.x in first place.

**Comment by aricwatson** [comment]
@ADDISON74 @farazhkhan I have replicated this problem, specific to Centos 7 and Varnish 4.0.3. Earlier I tested Varnish 4.1.1 and did not experience this problem. There is an issue in 4.1.1 related to how the `cli_buffer` param is reported back to Turpentine, but we have a workaround [here](https://github.com/nexcess/magento-turpentine/issues/1063#issuecomment-197054368) if you'd like to try Varnish 4.1.1. I just tested upgrading to Varnish 4.1 using [these instructions](https://www.varnish-cache.org/installation/redhat) and that seems to have solved the problem.

**Comment by aricwatson** [comment]
Warning added there and to the *Compatibility* page on the wiki. Weird one - thanks for tracking it down!

**Comment by farazhkhan** [comment]
@aricwatson 
Thanks for instructions, 

1.
I have upgraded my Varnish version as per [these instructions](https://www.varnish-cache.org/installation/redhat) but now Varnish RPM has been built into 4.1.2 (not 4.1.1)... and after this installation when I go to back-end of Magento 
Varnish Options > Servers > Varnish Version there is no 4.1.x the only option available is 4.0.x and if I select 'Auto' and click on 'Save Config' it says

> Unsupported Varnish version

and does not work at all...

2.
With regards to cli_buffer I get following in 4.1.2
```
varnishadm param.show | grep cli_buffer
cli_buffer                 16k [bytes]
```

So is it fine, or does it still generates the 'over limit' error and I need to follow [these instructions](https://github.com/nexcess/magento-turpentine/issues/1063#issuecomment-197054368)?

**Comment by ADDISON74** [comment]
@aricwatson please update Turpentine for recognizing Varnish 4.1. in this moment I am testing Varnish 4.1 using Auto option. in this way that message with "unsupported varnish version" won't appear.

**Comment by farazhkhan** [comment]
@ADDISON74 @aricwatson 

1.
Not sure how it is working for you but with CentOS 7.2 having Nexcessnet_Turpentine 	0.6.8 (stable) when we select 'Auto' option under Varnish Options > Servers > Varnish Version it always says

> Unsupported Varnish version

2.
Also, Varnish 4.1.2 with CentOS 7.2 does not resolve issue of ESI Varnish Blocks, as to disable caching for cart or other block we always have to comment out them under `/app/design/frontend/base/default/layout/turpentine_esi.xml`

**Comment by ADDISON74** [comment]
@farazhkhan The only way for the moment is going back to Varnish 3.0.3 to 3.0.7. It is sad what is happening CentOS is a famous Linux flavor but those who are maintaining the packages did something wrong. I tried to install Varnish 3.0.7 from repository but it did not work on CentOS. So I downgrade to 6.7 and everything is going fine, except Age 0 issue. I was to much frustration continuing to dig something which consume too much efforts. In my case ESI policies worked on 4.1.1.

**Comment by farazhkhan** [comment]
@ADDISON74 @aricwatson 

Sorry but upgrading Varnish 4.1.2 with CentOS 7.x makes issues with add to cart which are heavily reported under issues tab, and I was also facing the [same issue](https://github.com/nexcess/magento-turpentine/issues/1157) and only option was to revert back to Varnish 4.0.3.

I hope these issues will be resolved in later version of Turpentine.

**Comment by miguelbalparda** [comment]
We will need more information, so far I haven't seen any data to back up what you just said. How did you came to that conclusion? I've seen the tickets you mentioned and while it seems to be true, we need more info to be sure this is Turpentine related and not some bad configs or a theme missconfiguration.

**Comment by franzludilabel** [comment]
I confirm that upgrading to Varnish 4.1.2 doesnt resolve the issue. ESI processing not enabled still  happening.
