### ISSUE TITLE
Varnish 4.1: JS's, GIF's and JPEG's files from cache with time load. Age 0 issue.

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#1089]
I am playing with this configuration: 

- CentOS 7 x64 (Release 7.2.1511)
- Varnish 4.1.1 (Revision 66bb824)
- Magento CE 1.9.2.2
- Turpentine latest devel branch

I don't understand why for all static files (cached already) there is still a time load? Why the Age header is 0?

Here is the Network section in Chrome first time visiting a category page. I flushed the cached and restarted Varnish service before:

![nocache](https://cloud.githubusercontent.com/assets/8360474/12747366/4a653a54-c9ac-11e5-9e4b-639adda743cb.jpg)

Here is the Network section in Chrome visiting again that category page by clicking on its link (not refreshing/reloading the page). See the page load time to 8 ms which means Varnish is working, but all static files are still having a time load. This time load is decreased from initial, but it is still there increasing the total page load time.

![cached](https://cloud.githubusercontent.com/assets/8360474/12747368/4ca54b38-c9ac-11e5-9e17-fb1fb8584b6f.jpg)

Here are the headers for a static file I picked up randomly (controls.js). As you may see the Age is still 0.

![file](https://cloud.githubusercontent.com/assets/8360474/12747412/8e7a4cc0-c9ac-11e5-98b4-f85a1936732d.jpg)

Do we have to make some changes inside VCL for Varnish 4.1 and Age 0 issue? Please note I was forced to switch to this Varnish version because ESI policies are not working in 4.0.3 anymore. Anyone who want to upgrade from Varnish 3 to Varnish 4 should avoid 4.0 going directly to 4.1.

**Comment by ADDISON74** [comment]
One more comment, all are having Age header set to 0, not only static files. This includes the page html itself.

**Comment by magenx** [comment]
how exactly did you get Varnish 4.1 ?

**Comment by ADDISON74** [comment]
From Varnish repository. Here are more information:

**Comment by ADDISON74** [comment]
In Magento Backend, Varnish Options -> General Options I set "Use VCL fix" to Disable. Once I did this I can take the benefits of Varnish/Turpentine on CentOS. For Debian/Ubuntu, both works great with "Use VCL fix" set to Enable by default.

I don't know what is happening behind Turpentine and I expect someone to investigate for CentOS geeks.

**Comment by ADDISON74** [comment]
Setting "Use VCL fix" to Disable was not solving this issue. I am trying to understand if this error comes from Apache 2.4. I just disabled Expire and Deflate Apache modules but no positive results. In Ubuntu I don't have this issue, but it is Apache 2.2, all the others are the same.

**Comment by aricwatson** [comment]
I suspect it's a Varnish 4.x issue - I just tested using Varnish 3 and got an appropriate age for asset files.

**Comment by ADDISON74** [comment]
What version of Apache did you use with Varnish 3? Was it Apache 2.2?

It could be Varnish 4.x. But it is related only to Red Hat OS flavors. That Varnish version from EPEL repository has this big problem. In Debian/Ubuntu I don't have any issue with Varnish 4.X.

**Comment by aricwatson** [comment]
> What version of Apache did you use with Varnish 3? Was it Apache 2.2?

Yes, Apache 2.2 and Varnish 3.0.3

**Comment by ADDISON74** [comment]
Your combination is working great. I suspect Apache 2.4 for doing some bad things. Can you replace Apache 2.2 with 2.4 in your configuration?

**Comment by aricwatson** [comment]
Not easily, since in this case I was testing with turpentine-master.devsupport.nexcess.net - when I get a chance I can test a different apache in a VM.

**Comment by ADDISON74** [comment]
For CentOS Varnish version was updated to 4.1.2. Unfortunately Age 0 issue still remains. Probably it is a build issue. In this moment I can say do not use Varnish on CentOS it won't work at least for 4.x and latest CentOS 7 version.

**Comment by aricwatson** [comment]
FWIW - in production we typically use CentOS, with Varnish 3.0.3 and Apache 2.2.

**Comment by aricwatson** [comment]
I just noticed something in your screenshot - the assets all have "(from cache)" in the size column. This indicates that the asset was actually loaded from the browser's cache and *not* from the network - which means this didn't come from Varnish. You can see in your first screenshot that there is a size given, indicating in that case the assets were loaded from the network and not the local browser cache.

**Comment by ADDISON74** [comment]
Pages source code is full of "". Page load time is 3 ms. Varnish is working but is not caching the files set in Turpentine with js, css, jpg, png extensions. I am not using a Varnish built from source, just the one from EPEL repository and mentioned on Varnish website. It is strange after two months nobody from maintainers did not realize there is an caching issue. I will report in Varnish forum. It is clear to me Varnish 4.x is not working as expected in Red Hat flavors.

**Comment by aricwatson** [comment]
So - it sounds like what happened is your first request passed through Varnish and downloaded the assets, which your browser cached.

On your second request, no requests were sent for those assets - because they were already cached by your browser. So, there was no opportunity for Varnish to server them, because they weren't requested.

**Comment by ADDISON74** [comment]
Yesterday I set up CentOS 6.7, Apache 2.2, Varnish 3.0.7. Comparing with CentOS 7.2, Apache 2.4, Varnish 4.x in CentOS 6.7 there is no page load time for all static files (see second image in my first post), this is good. 

Unfortunately I got the same issue Age:0 for files like js, gif, jpeg and Age: 608 for css. I disabled a lot of Apache modules like expire, deflate and headers. Now all static files get Age: 1374 and stay at this value without any changing. 

Since my configuration is working as expected in Debian/Ubuntu, including the same Turpentine version, I consider this is a Varnish issue for all Red Hat flavors.

**Comment by aricwatson** [comment]
I'm curious - try checking the 'disable cache' checkbox in your network tab in Chrome Dev tools and test again. I still think these assets are being cached locally by your browser and hence not interacting with Varnish at all.

**Comment by ADDISON74** [comment]
I will check your suggestion. Please note a have two VM's working in the same time. 

- One is using: Debian 6.7/Magento 1.9.2.4/Apache 2.2/Varnish 4.0/Turpenine Devel
- The other one is using CentOS 7.2/Magento 1.9.2.4/Apache 2.4/Varnish 4.0/Turpentine Devel

MySQL is 5.5 same version both, PHP is 5.5 same version both. All programs are updated. Magento it is the same in both VM's.

I cleared the cache and cookies in Chrome/Firefox before visiting each VM. Age 0 issue is only present in CentOS version. In my opinion it is not a browser issue, just an OS issue from its packages. It is crazy because I using Varnish from their repository, latest 4.0 version.

**Comment by ADDISON74** [comment]
It seems you were right. If the cache is enable Age 0 will be for all static files. If I disable cache from time to time I check the Age and the number rises up from 0. In this case browser is not interacting with Varnish at all. Is it bad? Is affecting the ranking?

**Comment by aricwatson** [comment]
>  Is it bad? Is affecting the ranking?

I don't see how it could be bad or affect rankings (I assume you mean in the search engines). Any elements that do not need to be requested by the browser will speed up page load times since the browser can quickly load the items from its own cache - which should be faster even than Varnish. The only real problem can be if locally cached items become out of date - but you will have that same problem even if Varnish/Turpentine were not involved. 

I'm not sure why in your CentOS testing it shows up as Age 0 - for me the age was always above zero (even when loaded from cache) - but it would have a 304 access code and a very fast time. It could even be a difference in how our browsers handle the same scenario.

**Comment by ADDISON74** [comment]
I accessed the website from Ubuntu 14 using latest Chrome. When the cache is disabled I get the Age from Varnish. When the cache is enabled I get the Age from Chrome, which is above 0. A refresh of the page with F5 changes the Age for all cached elements in browser with the age from Varnish. This is a correct behavior in my opinion. 

In Chrome for Windows, Age remains 0 for all static elements except the page which gets the Age from Varnish. When disabling the cache I get the Age from Varnish, when I enable the cache and refresh static element get Age 0. It is a browser version issue not Turpentine/Varnish. In this case I recommend a shorter period of time for static elements if someone plans to change them frequently, 12 - 24 hours.

**Comment by aricwatson** [comment]
OK, that makes sense I think. For the record, I was testing with Chrome on the mac, and never saw Age 0 in any scenario. The difference is in how the various browser's report this info for locally-cached assets.

**Comment by ADDISON74** [comment]
@aricwa

**Comment by aricwatson** [comment]
> Please all stay with 4.0 branch till they fix the Age 0 issue.

Agreed, can confirm no such issues in 4.0.3 with my testing.

Thanks!
