### ISSUE TITLE
turpentine not caching?

### ISSUE THREAD

**Issue by nomadph** [nexcess/magento-turpentine#109]
Is varnish-turpentine not caching product pages in Magento?

We tested a product page for varnish-turpentine in gtmetrix and this is the result:
http://gtmetrix.com/reports/www.trendsndeals.com/70jkcCPY

Please see under Timeline, the time to first byte is 5.37s (long time).

We checked by running varnishlog that it is configured correctly and that website is going through varnish.

comparatively, and curiously, all other pages in magento website loads fast (low time to first byte), such as the main page:
http://gtmetrix.com/reports/www.trendsndeals.com/HvyBs0pq

it seems the issue is only in the product pages. is varnish-turpentine not caching product pages?

please advice. thanks!

**Comment by dartsuresh** [comment]
I had the same error but didn`t get any solution please advise me.
Here is the varnish log
-   ReqURL         /turpentine/esi/getBlock/method/esi/access/private/ttl/864000/hmac/71c1dfbb36517a1c0708c14ef603b72b75b5c5602d2414c2ab4b817f8b351fb5/data/b9xeFjc1rxwDVQzy1CWU1CgWAuSiaiHO-SmymU9PFa6MEHBQ5KnxZ3zRcrcZZFM703APqmngwseP6P4seMtW-ihNFj4V6o6Voy5-0i843lMzDmZCLiO2Sl0Fhfp9lUlIv7xa7wCQ8bt005dj9XJs2a1NBcrnFUmJRtZBTzbWZacB3zuTLwMBaCSDU5s-c5.NdYu0wgFle66sfZPAFsOn17H8N9nwUx3dcx7YuNDo160wDbd8QYmc3zUp4GxpWKQcUuiBPI1cfF9JLaz1V7uUF7ToiZpLrCbUAp4ByB9.oqtGHEEMFuzQgfg79J5BFp77DQ21xDHyNHCH.0jJ4espGzb8zX4aghADuMT29Hi8QFh5jrUeAE4GwCv1.p6lFoRN4X.x2SrHMchy5h.yeFSGsJKhQ.f2H.FhS2jdACVFUu51BfcmV.lT4Z26RoUoKB4ACZ3PdrfcA8VtMGvjsxQ02w==/
-   ReqURL         /turpentine/esi/getBlock/method/esi/access/private/ttl/864000/hmac/71c1dfbb36517a1c0708c14ef603b72b75b5c5602d2414c2ab4b817f8b351fb5/data/b9xeFjc1rxwDVQzy1CWU1CgWAuSiaiHO-SmymU9PFa6MEHBQ5KnxZ3zRcrcZZFM703APqmngwseP6P4seMtW-ihNFj4V6o6Voy5-0i843lMzDmZCLiO2Sl0Fhfp9lUlIv7xa7wCQ8bt005dj9XJs2a1NBcrnFUmJRtZBTzbWZacB3zuTLwMBaCSDU5s-c5.NdYu0wgFle66sfZPAFsOn17H8N9nwUx3dcx7YuNDo160wDbd8QYmc3zUp4GxpWKQcUuiBPI1cfF9JLaz1V7uUF7ToiZpLrCbUAp4ByB9.oqtGHEEMFuzQgfg79J5BFp77DQ21xDHyNHCH.0jJ4espGzb8zX4aghADuMT29Hi8QFh5jrUeAE4GwCv1.p6lFoRN4X.x2SrHMchy5h.yeFSGsJKhQ.f2H.FhS2jdACVFUu51BfcmV.lT4Z26RoUoKB4ACZ3PdrfcA8VtMGvjsxQ02w==/
-   ReqURL         /turpentine/esi/getBlock/method/esi/access/private/ttl/864000/hmac/71c1dfbb36517a1c0708c14ef603b72b75b5c5602d2414c2ab4b817f8b351fb5/data/b9xeFjc1rxwDVQzy1CWU1CgWAuSiaiHO-SmymU9PFa6MEHBQ5KnxZ3zRcrcZZFM703APqmngwseP6P4seMtW-ihNFj4V6o6Voy5-0i843lMzDmZCLiO2Sl0Fhfp9lUlIv7xa7wCQ8bt005dj9XJs2a1NBcrnFUmJRtZBTzbWZacB3zuTLwMBaCSDU5s-c5.NdYu0wgFle66sfZPAFsOn17H8N9nwUx3dcx7YuNDo160wDbd8QYmc3zUp4GxpWKQcUuiBPI1cfF9JLaz1V7uUF7ToiZpLrCbUAp4ByB9.oqtGHEEMFuzQgfg79J5BFp77DQ21xDHyNHCH.0jJ4espGzb8zX4aghADuMT29Hi8QFh5jrUeAE4GwCv1.p6lFoRN4X.x2SrHMchy5h.yeFSGsJKhQ.f2H.FhS2jdACVFUu51BfcmV.lT4Z26RoUoKB4ACZ3PdrfcA8VtMGvjsxQ02w==/
-   RespHeader     X-Varnish-URL: /turpentine/esi/getBlock/method/esi/access/private/ttl/864000/hmac/71c1dfbb36517a1c0708c14ef603b72b75b5c5602d2414c2ab4b817f8b351fb5/data/b9xeFjc1rxwDVQzy1CWU1CgWAuSiaiHO-SmymU9PFa6MEHBQ5KnxZ3zRcrcZZFM703APqmngwseP6P4seMtW-ihNFj4V6o6Voy5-0i843lMzDmZCLiO2Sl0Fhfp9lUlIv7xa7wCQ8bt005dj9XJs2a1NBcrnFUmJRtZBTzbWZacB3zuTLwMBaCSDU5s-c5.NdYu0wgFle66sfZPAFsOn17H8N9nwUx3dcx7YuNDo160wDbd8QYmc3zUp4GxpWKQcUuiBPI1cfF9JLaz1V7uUF7ToiZpLrCbUAp4ByB9.oqtGHEEMFuzQgfg79J5BFp77DQ21xDHyNHCH.0jJ4espGzb8zX4aghADuMT29Hi8QFh5jrUeAE4GwCv1.p6lFoRN4X.x2SrHMchy5h.yeFSGsJKhQ.f2H.FhS2jdACVFUu51BfcmV.lT4Z26RoUoKB4ACZ3PdrfcA8VtMGvjsxQ02w==/
-   ReqURL         /turpentine/esi/getBlock/method/esi/access/private/ttl/864000/hmac/a3482b0355cb05e88762492303ce511ebdac8740e17c5052e4cb242fe88d03cb/data/1XLgu1E0hH-FMGDQcOBuXvNgIj0tORCo0jg79TYNa9kvrA8.3DAo4FK3bZ9lffYJG6aBb4Fu2CFBUF4Z1.sfsT00Rvyl8HJDBVJ3z1YEGcqWcDkOtgqZ2-Ql7P2r3Zp.QjdF8QvkBQwstv1AQ4HKHLoENYsKDDR4igQXsvK8kQIiI.2Ri9w4iRQ1zDNDUX6Xyq4JAgXAjSs1dFcw2qKgW19MM.9jFEpwWaRA-F7h9aHT24yNAwdJdlwEfsgjg8f.tSDaTzK97iel0iNOWU2E1EEPB-Grhhh8kjoo2bUqs9v3AJpZ98f21vHNzAkHG.r9hEhUzPhQCY55rIxxyeAb5GQeLdHcKTwgA-DHeRVkE4F1xLVbxOZR7g==/
-   ReqURL         /turpentine/esi/getBlock/method/esi/access/private/ttl/864000/hmac/a3482b0355cb05e88762492303ce511ebdac8740e17c5052e4cb242fe88d03cb/data/1XLgu1E0hH-FMGDQcOBuXvNgIj0tORCo0jg79TYNa9kvrA8.3DAo4FK3bZ9lffYJG6aBb4Fu2CFBUF4Z1.sfsT00Rvyl8HJDBVJ3z1YEGcqWcDkOtgqZ2-Ql7P2r3Zp.QjdF8QvkBQwstv1AQ4HKHLoENYsKDDR4igQXsvK8kQIiI.2Ri9w4iRQ1zDNDUX6Xyq4JAgXAjSs1dFcw2qKgW19MM.9jFEpwWaRA-F7h9aHT24yNAwdJdlwEfsgjg8f.tSDaTzK97iel0iNOWU2E1EEPB-Grhhh8kjoo2bUqs9v3AJpZ98f21vHNzAkHG.r9hEhUzPhQCY55rIxxyeAb5GQeLdHcKTwgA-DHeRVkE4F1xLVbxOZR7g==/
-   ReqURL         /turpentine/esi/getBlock/method/esi/access/private/ttl/864000/hmac/a3482b0355cb05e88762492303ce511ebdac8740e17c5052e4cb242fe88d03cb/data/1XLgu1E0hH-FMGDQcOBuXvNgIj0tORCo0jg79TYNa9kvrA8.3DAo4FK3bZ9lffYJG6aBb4Fu2CFBUF4Z1.sfsT00Rvyl8HJDBVJ3z1YEGcqWcDkOtgqZ2-Ql7P2r3Zp.QjdF8QvkBQwstv1AQ4HKHLoENYsKDDR4igQXsvK8kQIiI.2Ri9w4iRQ1zDNDUX6Xyq4JAgXAjSs1dFcw2qKgW19MM.9jFEpwWaRA-F7h9aHT24yNAwdJdlwEfsgjg8f.tSDaTzK97iel0iNOWU2E1EEPB-Grhhh8kjoo2bUqs9v3AJpZ98f21vHNzAkHG.r9hEhUzPhQCY55rIxxyeAb5GQeLdHcKTwgA-DHeRVkE4F1xLVbxOZR7g==/
-   RespHeader     X-Varnish-URL: /turpentine/esi/getBlock/method/esi/access/private/ttl/864000/hmac/a3482b0355cb05e88762492303ce511ebdac8740e17c5052e4cb242fe88d03cb/data/1XLgu1E0hH-FMGDQcOBuXvNgIj0tORCo0jg79TYNa9kvrA8.3DAo4FK3bZ9lffYJG6aBb4Fu2CFBUF4Z1.sfsT00Rvyl8HJDBVJ3z1YEGcqWcDkOtgqZ2-Ql7P2r3Zp.QjdF8QvkBQwstv1AQ4HKHLoENYsKDDR4igQXsvK8kQIiI.2Ri9w4iRQ1zDNDUX6Xyq4JAgXAjSs1dFcw2qKgW19MM.9jFEpwWaRA-F7h9aHT24yNAwdJdlwEfsgjg8f.tSDaTzK97iel0iNOWU2E1EEPB-Grhhh8kjoo2bUqs9v3AJpZ98f21vHNzAkHG.r9hEhUzPhQCY55rIxxyeAb5GQeLdHcKTwgA-DHeRVkE4F1xLVbxOZR7g==/
-   ReqURL         /turpentine/esi/getBlock/method/esi/access/private/ttl/864000/hmac/359dfe27affbc23a2ca4fbed1f915cd4cc4a10960239d5941043e8498612b1a5/data/QdbVcLIYIrmbk4qLp3JsqA5n.rAGyDTMPRFIGVThe4lByuGWb1LnLv8-lJIWuJbNbgUyov7olbKpgZ8iCbX6IuG6JZn-sBB6KAX1yu0P7PyOGbuJUQr64b76mKnhE2pzQo.3GaKOGdY694E7OvMtFIOareweHAtmlKyx5wlelsxMDgPCWMxBQfkXW0A9YC3qwLstbhNgXODG4jeciK7cFu7OeiVeT.csDT0ohof3ldbuf9sbb7n7qCUMSHRfaGm5VPuOj0SClSzblWMRzXK7nXPJXqWofmeNIcOkQGZCt28wET0jKp1GFeg7IqZJvAXlEoK4Cc2C4KBe6w817MDP3FBvQFo9.1df67mlh7JOxyxayMY3m2MkyA==/
-   ReqURL         /turpentine/esi/getBlock/method/esi/access/private/ttl/864000/hmac/359dfe27affbc23a2ca4fbed1f915cd4cc4a10960239d5941043e8498612b1a5/data/QdbVcLIYIrmbk4qLp3JsqA5n.rAGyDTMPRFIGVThe4lByuGWb1LnLv8-lJIWuJbNbgUyov7olbKpgZ8iCbX6IuG6JZn-sBB6KAX1yu0P7PyOGbuJUQr64b76mKnhE2pzQo.3GaKOGdY694E7OvMtFIOareweHAtmlKyx5wlelsxMDgPCWMxBQfkXW0A9YC3qwLstbhNgXODG4jeciK7cFu7OeiVeT.csDT0ohof3ldbuf9sbb7n7qCUMSHRfaGm5VPuOj0SClSzblWMRzXK7nXPJXqWofmeNIcOkQGZCt28wET0jKp1GFeg7IqZJvAXlEoK4Cc2C4KBe6w817MDP3FBvQFo9.1df67mlh7JOxyxayMY3m2MkyA==/
-   ReqURL         /turpentine/esi/getBlock/method/esi/access/private/ttl/864000/hmac/359dfe27affbc23a2ca4fbed1f915cd4cc4a10960239d5941043e8498612b1a5/data/QdbVcLIYIrmbk4qLp3JsqA5n.rAGyDTMPRFIGVThe4lByuGWb1LnLv8-lJIWuJbNbgUyov7olbKpgZ8iCbX6IuG6JZn-sBB6KAX1yu0P7PyOGbuJUQr64b76mKnhE2pzQo.3GaKOGdY694E7OvMtFIOareweHAtmlKyx5wlelsxMDgPCWMxBQfkXW0A9YC3qwLstbhNgXODG4jeciK7cFu7OeiVeT.csDT0ohof3ldbuf9sbb7n7qCUMSHRfaGm5VPuOj0SClSzblWMRzXK7nXPJXqWofmeNIcOkQGZCt28wET0jKp1GFeg7IqZJvAXlEoK4Cc2C4KBe6w817MDP3FBvQFo9.1df67mlh7JOxyxayMY3m2MkyA==/
-   RespHeader     X-Varnish-URL: /turpentine/esi/getBlock/method/esi/access/private/ttl/864000/hmac/359dfe27affbc23a2ca4fbed1f915cd4cc4a10960239d5941043e8498612b1a5/data/QdbVcLIYIrmbk4qLp3JsqA5n.rAGyDTMPRFIGVThe4lByuGWb1LnLv8-lJIWuJbNbgUyov7olbKpgZ8iCbX6IuG6JZn-sBB6KAX1yu0P7PyOGbuJUQr64b76mKnhE2pzQo.3GaKOGdY694E7OvMtFIOareweHAtmlKyx5wlelsxMDgPCWMxBQfkXW0A9YC3qwLstbhNgXODG4jeciK7cFu7OeiVeT.csDT0ohof3ldbuf9sbb7n7qCUMSHRfaGm5VPuOj0SClSzblWMRzXK7nXPJXqWofmeNIcOkQGZCt28wET0jKp1GFeg7IqZJvAXlEoK4Cc2C4KBe6w817MDP3FBvQFo9.1df67mlh7JOxyxayMY3m2MkyA==/
-   ReqURL         /turpentine/esi/getBlock/method/esi/access/public/ttl/3600/hmac/e1a7b0d771e3fc9d4a3426c0902598afeecb5034af1e2c9307d75d43485faed9/data/.UP5Dw2-hHnh26in2Q7YXVwhPsRf5h9t9o5cM-VxhhPK8xel.sM4SGBiXf6AjF-L6iECwvKc93fUca5psA6.Xbb.QTS78BEXUtFlzN9YPLna1v1gsdyiNa-Z2WqJvxisAoDrq6STIUdzOs2niQ8e1YDrr4z6avQfNmmfa98P1YkGstJEr8AtNT9NTlYQkcmJ-oEX2lUzpZC9sYDWChVPTQWYyjcoeWIXXV2Kv.kxN5T1jnVQ5sOHQa-KEgXg7PhqeMrSEXPjfPQzqdOeVeH7bA==/
-   ReqURL         /turpentine/esi/getBlock/method/esi/access/public/ttl/3600/hmac/e1a7b0d771e3fc9d4a3426c0902598afeecb5034af1e2c9307d75d43485faed9/data/.UP5Dw2-hHnh26in2Q7YXVwhPsRf5h9t9o5cM-VxhhPK8xel.sM4SGBiXf6AjF-L6iECwvKc93fUca5psA6.Xbb.QTS78BEXUtFlzN9YPLna1v1gsdyiNa-Z2WqJvxisAoDrq6STIUdzOs2niQ8e1YDrr4z6avQfNmmfa98P1YkGstJEr8AtNT9NTlYQkcmJ-oEX2lUzpZC9sYDWChVPTQWYyjcoeWIXXV2Kv.kxN5T1jnVQ5sOHQa-KEgXg7PhqeMrSEXPjfPQzqdOeVeH7bA==/
-   ReqURL         /turpentine/esi/getBlock/method/esi/access/public/ttl/3600/hmac/e1a7b0d771e3fc9d4a3426c0902598afeecb5034af1e2c9307d75d43485faed9/data/.UP5Dw2-hHnh26in2Q7YXVwhPsRf5h9t9o5cM-VxhhPK8xel.sM4SGBiXf6AjF-L6iECwvKc93fUca5psA6.Xbb.QTS78BEXUtFlzN9YPLna1v1gsdyiNa-Z2WqJvxisAoDrq6STIUdzOs2niQ8e1YDrr4z6avQfNmmfa98P1YkGstJEr8AtNT9NTlYQkcmJ-oEX2lUzpZC9sYDWChVPTQWYyjcoeWIXXV2Kv.kxN5T1jnVQ5sOHQa-KEgXg7PhqeMrSEXPjfPQzqdOeVeH7bA==/
-   RespHeader     X-Varnish-URL: /turpentine/esi/getBlock/method/esi/access/public/ttl/3600/hmac/e1a7b0d771e3fc9d4a3426c0902598afeecb5034af1e2c9307d75d43485faed9/data/.UP5Dw2-hHnh26in2Q7YXVwhPsRf5h9t9o5cM-VxhhPK8xel.sM4SGBiXf6AjF-L6iECwvKc93fUca5psA6.Xbb.QTS78BEXUtFlzN9YPLna1v1gsdyiNa-Z2WqJvxisAoDrq6STIUdzOs2niQ8e1YDrr4z6avQfNmmfa98P1YkGstJEr8AtNT9NTlYQkcmJ-oEX2lUzpZC9sYDWChVPTQWYyjcoeWIXXV2Kv.kxN5T1jnVQ5sOHQa-KEgXg7PhqeMrSEXPjfPQzqdOeVeH7bA==/
-   ReqURL         /turpentine/esi/getBlock/method/esi/access/private/ttl/864000/hmac/bf5e9801c7f0f464d859b38455efd8d2f1c1d90f619f5f0e32264aae8763f9c3/data/dtNUKfKnJD0cfTrMtp5AurOw7pfc7Cnj6s9DCI6mrDLzqykIwsc7WdsfaC.4bdtQOMfDPtyTPRqd-hMy1Js-OSgyMlsDYGyBqC5qZb4gGcWruP0OM16QovGLZR8MMeB9zzZBARW36xYSrj.bbCHH6gEnUo2uUsiesyLAm.Wrh9vzC9eZPv.pRdhZgtU40W0RyQ-LGvU7JVyLNC53Z6K6l5TeKLrytdfW8I7O9ZE6axLWi6ehW6F3Viq243SZ11TsJaf1zrZLcA-2u-Ag1aBlj31hnM..rOQ0hdno9ycEYJ1fWQ7hIVXdFn99E2dPEwphAFVdsUfuVNtSOe6TtDt0QA==/
-   ReqURL         /turpentine/esi/getBlock/method/esi/access/private/ttl/864000/hmac/bf5e9801c7f0f464d859b38455efd8d2f1c1d90f619f5f0e32264aae8763f9c3/data/dtNUKfKnJD0cfTrMtp5AurOw7pfc7Cnj6s9DCI6mrDLzqykIwsc7WdsfaC.4bdtQOMfDPtyTPRqd-hMy1Js-OSgyMlsDYGyBqC5qZb4gGcWruP0OM16QovGLZR8MMeB9zzZBARW36xYSrj.bbCHH6gEnUo2uUsiesyLAm.Wrh9vzC9eZPv.pRdhZgtU40W0RyQ-LGvU7JVyLNC53Z6K6l5TeKLrytdfW8I7O9ZE6axLWi6ehW6F3Viq243SZ11TsJaf1zrZLcA-2u-Ag1aBlj31hnM..rOQ0hdno9ycEYJ1fWQ7hIVXdFn99E2dPEwphAFVdsUfuVNtSOe6TtDt0QA==/
-   ReqURL         /turpentine/esi/getBlock/method/esi/access/private/ttl/864000/hmac/bf5e9801c7f0f464d859b38455efd8d2f1c1d90f619f5f0e32264aae8763f9c3/data/dtNUKfKnJD0cfTrMtp5AurOw7pfc7Cnj6s9DCI6mrDLzqykIwsc7WdsfaC.4bdtQOMfDPtyTPRqd-hMy1Js-OSgyMlsDYGyBqC5qZb4gGcWruP0OM16QovGLZR8MMeB9zzZBARW36xYSrj.bbCHH6gEnUo2uUsiesyLAm.Wrh9vzC9eZPv.pRdhZgtU40W0RyQ-LGvU7JVyLNC53Z6K6l5TeKLrytdfW8I7O9ZE6axLWi6ehW6F3Viq243SZ11TsJaf1zrZLcA-2u-Ag1aBlj31hnM..rOQ0hdno9ycEYJ1fWQ7hIVXdFn99E2dPEwphAFVdsUfuVNtSOe6TtDt0QA==/
-   RespHeader     X-Varnish-URL: /turpentine/esi/getBlock/method/esi/access/private/ttl/864000/hmac/bf5e9801c7f0f464d859b38455efd8d2f1c1d90f619f5f0e32264aae8763f9c3/data/dtNUKfKnJD0cfTrMtp5AurOw7pfc7Cnj6s9DCI6mrDLzqykIwsc7WdsfaC.4bdtQOMfDPtyTPRqd-hMy1Js-OSgyMlsDYGyBqC5qZb4gGcWruP0OM16QovGLZR8MMeB9zzZBARW36xYSrj.bbCHH6gEnUo2uUsiesyLAm.Wrh9vzC9eZPv.pRdhZgtU40W0RyQ-LGvU7JVyLNC53Z6K6l5TeKLrytdfW8I7O9ZE6axLWi6ehW6F3Viq243SZ11TsJaf1zrZLcA-2u-Ag1aBlj31hnM..rOQ0hdno9ycEYJ1fWQ7hIVXdFn99E2dPEwphAFVdsUfuVNtSOe6TtDt0QA==/

**Comment by aricwatson** [comment]
It looks like varnish is working, or at least ESI calls are being made. I'd suggest checking [this](https://github.com/nexcess/magento-turpentine/wiki/Debugging-Varnish#how-do-i-know-if-varnish-is-working) to help see if Turpentine is set up and working correctly.
