### ISSUE TITLE
xml typo

### ISSUE THREAD

**Issue by janw-oostendorp** [nexcess/magento-turpentine#1090]
https://github.com/nexcess/magento-turpentine/blob/master/app/code/community/Nexcessnet/Turpentine/etc/config.xml#L480

And these two are not completely valid:  
https://github.com/nexcess/magento-turpentine/blob/master/app/code/community/Nexcessnet/Turpentine/etc/config.xml#L56  
https://github.com/nexcess/magento-turpentine/blob/master/app/code/community/Nexcessnet/Turpentine/etc/config.xml#L58

**Comment by miguelbalparda** [comment]
I can see why the first link has an issue, but why do you think the other 2 are not completely valid?

**Comment by janw-oostendorp** [comment]
Phpstorm gives a notice. It suggests: `<backend_probe_url/>`  
I would agree it's not a real problem

**Comment by miguelbalparda** [comment]
It should be fixed by https://github.com/nexcess/magento-turpentine/commit/ba025294ebee5bfd4926e157206316b4b5295e72
Thank you for the heads up!
