### ISSUE TITLE
Product list slowly one by one

### ISSUE THREAD

**Issue by Schoeny1** [nexcess/magento-turpentine#1091]
My 1.9.0.1 website runs well in Varnish but once I apply the VCL in cache settings, the website loads slower.  More specifically the product list is what is slow- it loads each product one-by-one.  I run Turpentine on several websites with no issue and I am perplexed on this one.  Any ideas?

**Comment by miguelbalparda** [comment]
If you have Turpentine running in multiple sites I would recommend check your server setup first to rule out config differences between this and your other environments.

**Comment by miguelbalparda** [comment]
Turpentine is not a plug and play extension. You might need to change the cache settings for all your blocks, check the wiki for more info.

**Comment by Schoeny1** [comment]
The block I am trying to add to the turpentine VCL seems to be this:
Mage_Catalog_Block_Product_List

Any idea on this?  I tried this but it didn't seem to do anything:
<reference name="content">
        <block type="catalog/product_list" name="product_list" template="catalog/product/list.phtml">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <registry_keys>
                        <current_category/>
                    </registry_keys>
                </params>
            </action>

**Comment by miguelbalparda** [comment]
You should not be caching the list as private if it doesn't change on a per user basis. Usually list and product page are cached publicly to have the same version for everyone and if you set the cache to private, it will be cached for each user and Varnish won't be serving a cached version most of the time.

**Comment by Schoeny1** [comment]
Thanks for your help.  I actually found the reason in another post here:
https://github.com/nexcess/magento-turpentine/issues/75

The problem is that the product-list is being called in a CMS page in the content section.  It appears that if I move this to the design section instead then Turpentine will be able to cache it.

**Comment by miguelbalparda** [comment]
Good stuff, closing the issue. Regarding the cart issue, if you don't find the solution please open a new one.
