### ISSUE TITLE
Community Pole is not hiding if the module is disable in Backend

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#1093]
@aricwatson - You fixed the Community Pole a few months ago based on my reports. I discovered today if this module is disabled in Magento Backend (System -> Configuration -> Advanced) its side block won't disappear from Frontend. This is not a caching issue because I restarted several times Varnish service and side block is still there. I flushed Magento cache with no luck. The only way to hide this is keeping enable the module and close any polls. 

I guess this issue is coming because you extended its class in Turpentine module. I appreciate if you fix this too.

PS - I checked before reporting this issue in a Ubuntu server without no Varnish/Turpentine installed. If I disable Mage_Poll module, side block disappears from Magento Frontend. There is no need to clear the cache in order to get this.

**Comment by tschifftner** [comment]
+1

**Comment by arnoldmontiel** [comment]
+1

**Comment by aricwatson** [comment]
@ADDISON74 @tschifftner @arnoldmontiel I just created a PR with a fix for this. Please test https://github.com/nexcess/magento-turpentine/pull/1195 - thanks!

**Comment by ADDISON74** [comment]
I appreciate for your notification. I will test it these days and come back with a feedback.

**Comment by ADDISON74** [comment]
I

**Comment by ADDISON74** [comment]
1) I closed all poles - that XHR file still loads, but there is no Community Pole side block in frontend

2) I disabled Community Pole as module in backend - XHR file is not loading anymore and there is no Community Pole side block in frontend.

You did a great job. I tested it in two versions of Magento, you can integrate it in Devel branch. It solves the problem with that XHR file (prototype.js) which caused hundreds of miliseconds load even the Poll module was disabled. Now if someone won't use Poll module the page will load without that delay.

**Comment by aricwatson** [comment]
Good to hear, thanks for testing it out! I'll go ahead and merge this with devel.

**Comment by ADDISON74** [comment]
Do you know the code for inserting it in that if statement in order to check if there are any active polls or not? It is a scenario for XHR file loading time issue.

Your modification you provided already is: 
"If Community Poll module is not active do this ..."

My new scenario is: 
"If Community Pole module is not active OR if there are no active polls do this ..."

As it is now even you disable the polls first you will get that XHR file loaded having the module enable. So you have to do another task to disable the module too. With my statement there is no need to check the module first, you can only deactivate the polls and enable/create them when is needed. But for updating that "if statement" we need the code how Magento checks if there are any active polls.
