### ISSUE TITLE
ESI Processing Not Enabled appearing on certain pages

### ISSUE THREAD

**Issue by zirwin** [nexcess/magento-turpentine#110]
I'm getting the "ESI Processing Not Enabled" error several other people have, and haven't been able to make it work yet using the solutions provided to others.

First off, my setup is Magento 1.6.1.0, Turpentine 0.5.2, Varnish 3.0.3, PHP 5.3.3-7+squeeze15, and APC 3.1.13. The block it's occuring in is the item compare block in a sidebar, as well as the footer, and I've noticed that it usually on the first, initial load of a particular page, but subsequent loads give the error. Here's the response headers from one of those pages, with debugging enabled:

```
HTTP/1.1 200 OK
Server: Apache/2.2.16 (Debian)
X-Powered-By: PHP/5.3.3-7+squeeze15
X-Turpentine-Cache: 1
X-Turpentine-Esi: 1
Content-Type: text/html; charset=UTF-8
X-Varnish-Set-Cookie: frontend=49375bdb-488b-488b-8c27-1ca77d66a07c; expires=Fri, 22-Mar-2013 03:10:25 GMT; path=/store; domain=seiboncarbon.com; httponly
Date: Fri, 22 Mar 2013 02:10:32 GMT
X-Varnish: 974223485 974223465
Age: 7
Via: 1.1 varnish
Connection: keep-alive
Set-Cookie: frontend=1858821d-be6f-4e6f-8193-703a47e633b2; expires=Fri, 22-Mar-2013 03:10:32 UTC; path=/store; domain=seiboncarbon.com; httponly
X-Varnish-Hits: 1
```

A request of that page directly to the backend, using the 'X-Turpentine-Secret-Handshake: 1' header, gives this:

```
HTTP/1.1 200 OK
Date: Fri, 22 Mar 2013 02:17:38 GMT
Server: Apache/2.2.16 (Debian)
X-Powered-By: PHP/5.3.3-7+squeeze15
Set-Cookie: frontend=hoe9rdp73llj29hfhe1phd0v63; expires=Fri, 22-Mar-2013 03:17:39 GMT; path=/store; domain=seiboncarbon.com; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
X-Turpentine-Cache: 1
X-Turpentine-Esi: 1
Vary: Accept-Encoding
Content-Type: text/html; charset=UTF-8
```

The body from this request contains the ESI block error (in this case I'm using the footer) with the url. Requesting that ESI url from the backend server directly, with the handshake header, gives the correct HTML body (the contents of the footer block) with these headers:

```
HTTP/1.1 200 OK
Date: Fri, 22 Mar 2013 02:24:37 GMT
Server: Apache/2.2.16 (Debian)
X-Powered-By: PHP/5.3.3-7+squeeze15
Set-Cookie: frontend=vvr4u2hj6c8la8iujril8gcj70; expires=Fri, 22-Mar-2013 03:24:38 GMT; path=/store; domain=seiboncarbon.com; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
X-Turpentine-Cache: 1
X-Turpentine-Esi: 0
Vary: Accept-Encoding
Content-Type: text/html; charset=UTF-8
```

Hopefully some part of this stands out as the source of the error, but I haven't been able to track it down so far. Any help would be appreciated.

**Comment by pieterjanliekens** [comment]
Hello just wanted to point out that the if{ } else { } loop does not nest the statement.
This would result in always displaying the message.
