### ISSUE TITLE
Mage_Page_Block_Html_Head not loading when set in dummy context

### ISSUE THREAD

**Issue by kanduvisla** [nexcess/magento-turpentine#1102]
I've got an external module that resides in the footer, but als injects something in the head block. The module has this layout XML:

    <default>
        <reference name="footer">
           <block type="feedback/feedback" name="popuphtml1" as="popuphtml" template="feedback/popup_html.phtml">
              <action method="addItem"><type>skin_css</type><name>feedback/css/popup.css</name><params/></action>
              <action method="addItem"><type>skin_js</type><name>feedback/js/popup.js</name></action>
           </block>
        </reference>
    </default>

And the method `addItem()` in the `feedback/feedback`-block looks like this:

    public function addItem($type, $path)
    {
        $config = Mage::getStoreConfig('feedback/feedback/active');
        if($config == "1")
        {
            $head = $this->getLayout()->getBlock('head');
            return $head->addItem($type,$path);
        }
    }

This block was throwing a fatal error with Turpentine, because it needs the `head`-block to perform the `addItem()`-method on it:

> Fatal error: Call to a member function addItem() on a non-object in /vagrant/public/app/code/local/Bc/Feedback/Block/Feedback.php on line 24

So I try to resolve this with the `dummy_block`-node in my layout XML in my `<default>` context.

First attempt:

    <reference name="popuphtml1">
        <action method="setEsiOptions">
            <params>
                <dummy_blocks>
                    <head/>
                </dummy_blocks>
            </params>
        </action>
    </reference>

This gives the same error. Second attempt:

    <reference name="popuphtml">
        <action method="setEsiOptions">
            <params>
                <dummy_blocks>
                    <head/>
                </dummy_blocks>
            </params>
        </action>
    </reference>

Also, the same error. Third attempt:

    <reference name="footer">
        <action method="setEsiOptions">
            <params>
                <dummy_blocks>
                    <head/>
                </dummy_blocks>
            </params>
        </action>
    </reference>

This one brings me somewhat further. But instead of showing an error it creates a report with the following error:

> Invalid method Mage_Core_Block_Template::addItem(Array
(
    [0] => skin_css
    [1] => feedback/css/popup.css
)

Now, the strange part is, that when I edit the `addItem()`-function to get the class name of `$head`:

    Mage::log(get_class($head), null, 'bla.log');

I get various results. On the initial page load:

    2016-02-17T14:19:05+00:00 DEBUG (7): Mage_Page_Block_Html_Head
    2016-02-17T14:19:05+00:00 DEBUG (7): Mage_Page_Block_Html_Head
    2016-02-17T14:19:07+00:00 DEBUG (7): Mage_Core_Block_Template
    2016-02-17T14:19:08+00:00 DEBUG (7): Mage_Page_Block_Html_Head
    2016-02-17T14:19:08+00:00 DEBUG (7): Mage_Page_Block_Html_Head
    2016-02-17T14:19:08+00:00 DEBUG (7): Mage_Page_Block_Html_Head
    2016-02-17T14:19:08+00:00 DEBUG (7): Mage_Page_Block_Html_Head
    2016-02-17T14:19:09+00:00 DEBUG (7): Mage_Core_Block_Template
    2016-02-17T14:19:09+00:00 DEBUG (7): Mage_Core_Block_Template

On all subsequent page loads:

    2016-02-17T14:19:14+00:00 DEBUG (7): Mage_Core_Block_Template
    2016-02-17T14:19:15+00:00 DEBUG (7): Mage_Core_Block_Template
    2016-02-17T14:19:15+00:00 DEBUG (7): Mage_Core_Block_Template

In both cases I get the error report message from Magento.

Does anyone know what might be going on here? How can I make sure that my `feedback/feedback`-block has access the correct `head`-block so it can invoke it's `addItem()`-method on that block?

**Comment by aricwatson** [comment]
Likely, the first page load is bypassing Varnish to get a valid session. I believe you're seeing two different classes here because `Mage_Page_Block_Html_Head` extends `Mage_Core_Block_Template`. On the subsequent page loads, it's attempting to use ESI, which only works with `Mage_Core_Block_Template` - and I think this is probably where your problem lies - `Mage_Core_Block_Template` doesn't have a `addItem` method.
