### ISSUE TITLE
Frontend cookie is not set.

### ISSUE THREAD

**Issue by janw-oostendorp** [nexcess/magento-turpentine#1103]
We are having some problems with cookies. Namely the _frontend_ cookie is not set on cached pages. Which Magento needs for sessions. It is created after a non cached page is visited.

The header is simply missing.
There is no problem with adding to cart but a session is not created on first visit. Sounds like this [FAQ](https://github.com/nexcess/magento-turpentine/wiki/FAQ#im-seeing-an-empty-cart-after-clicking-add-to-cart) question.

We are on Turpentine 0.6.8
Varnish 3
Magento 1.9.2.3 (we had the same problem on 1.9.1.x)

It does not happen when varnish is completely disabled.
It does happen when the *Use VCL fix* *on* and *off*

The only tweak we have on the vcl is: to exclude the WP blog we have up.

    if (req.url ~ "^/blog/") {
      return (pass);
    }

Am I doing domething wrong? Am I missing something?  
Can anybody help me get started?
tnx.

**Comment by aricwatson** [comment]
If the VCL fix is enabled (which is the default) then the first time a user requests a page it should get passed straight through to Magento and get a *frontend* cookie. If you're not seeing this behavior on the first request (and you have the VCL fix enabled) then there must be something configured wrong.

**Comment by janw-oostendorp** [comment]
I tested it an extra time. The diff in the vlc and the first time headers are attached.
Can you see anything where the problem is?

If this is all fine, where would you recommend I look next? At the varnish implementation, php, apache?

![varnish-firstvisit-fixon](https://cloud.githubusercontent.com/assets/1026882/13143989/e70a80a6-d647-11e5-9372-7013f38a1ef3.png)
![vcl-diff](https://cloud.githubusercontent.com/assets/1026882/13143990/e720b4d4-d647-11e5-8d2f-dd08b1c09265.png)

**Comment by aricwatson** [comment]
It looks like you your response is setting a cookie: `frontend=crawler-session`

Do you have a crawler IP set in the back-end?

**Comment by janw-oostendorp** [comment]
yes, `127.0.0.1`

**Comment by janw-oostendorp** [comment]
Emptying that field seems to work.

**Comment by aricwatson** [comment]
Turpentine thought you were a crawler, so it always gave you the `frontend-crawler-session` cookie.
