### ISSUE TITLE
Multi-site setup all domains working just one domain shows ESI processing not enabled

### ISSUE THREAD

**Issue by pschoenmakers** [nexcess/magento-turpentine#1104]
We have a multi-site setup with three domains on one Magento installation.

For two domains Turpentine is working perfect. But one domain gives "ESI processing not enabled" messages. We have a nginx-varnish-nginx setup where all three domains have the exact same configuration. 

Even the stores have the same settings with the same modules enabled, same theme etc. etc. 

As soon as I activate the ESI Blocks in cache management I get this ESI processing not enabled error on just one domain. The other domains don't show this error. 

If I manually request the ESI block url's I do see the correct content. However on the site it says: 

I tried to have a look at the logs - but couldn't find anything that could points to the source of this problem. Does someone have any clues / ideas what could cause this issue?

**Comment by aricwatson** [comment]
> If I manually request the ESI block url's I do see the correct content. However on the site it says:

I think you were going to add more details?

**Comment by pschoenmakers** [comment]
However on the site it says: ESI processing not enabled

**Comment by diwakert** [comment]
I have a similar issue on wholesale site. Could you please find the full description of the issue here:
http://magento.stackexchange.com/questions/126021/esi-processing-not-enabled-error-only-on-product-detail-page-varnish-and-magento

**Comment by miguelbalparda** [comment]
Have you checked the answer in the SE question you posted?
