### ISSUE TITLE
User-specific caching issues

### ISSUE THREAD

**Issue by graemelambert** [nexcess/magento-turpentine#1110]
Content at /checkout/cart/ is staying cached no matter what I do to the cart contents.  I'm also seeing pages like /customer/account being cached regardless of whether the user is logged in or not.

I have Nginx proxying through to Varnish for handling HTTPS connections if that's any help?

**Comment by miguelbalparda** [comment]
That is probably because you are caching those blocks as public instead of private. You should check your theme structure and your cache policies to solve this issue.

**Comment by graemelambert** [comment]
Hi Miguel,

I haven't set anything like that, I've just installed the module and done a few system config tweaks.

I did get **Invalid method Mage_Cms_Block_Block::addLink** being thrown at one point so I commented this block of XML out of **app/design/frontend/base/default/layout/turpentine_esi.xml**:
`        <reference name="footer">
            <action method="setEsiOptions">
                <params>
                    
                    <access>public</access>
                </params>
            </action>
        </reference>
`
This is because it was changing the block type of footer_links before some other area of code got around to doing the above method call.

**Comment by miguelbalparda** [comment]
This is not a plug and play extension. You should configure the way blocks are cached, not all the themes are fully compatible out of the box. I suggest you checking the wiki to fully understand the differences between public and private blocks.
