### ISSUE TITLE
Varnish caching in HTTP Auth restricted area should be enabled

### ISSUE THREAD

**Issue by andreasemer** [nexcess/magento-turpentine#1112]
Currently the Varnish caching is disabled in a HTTP Auth restricted area, because of settings in the default file (for example app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl -> Line 124 -> the "req.http.Authorization" part) 

I don´t know if this part of the code makes any sense in a szenario? At least it should be a configurable option. 

What do you think about this? If you like a can create a PR for this? The question is, if we should remove the entry, or make this option configurable?

**Comment by miguelbalparda** [comment]
It should be pretty straightforward to wrap this with an if clause. I'm not sure about completely removing this but feel free to make a PR pointing to devel and we can check it out!

**Comment by andreasemer** [comment]
Ok, i have created https://github.com/nexcess/magento-turpentine/pull/1120 

In my opinion we don't need this option at all. Maybe @aricwatson can help us and can tell where and why this can be usefull.

**Comment by miguelbalparda** [comment]
@andreasemer I checked your PR and I think the best choice here is to make this configurable via the admin using a Yes/No select being Yes the default option instead of completely removing this. Not caching pages behind http Auth seems to be logical since it's mostly used for development and you don't want to flush Varnish every time you need to see a change. Do you think you can modify your PR with these new requirements?

**Comment by andreasemer** [comment]
>> Not caching pages behind http Auth seems to be logical since it's mostly used for development and you don't want to flush Varnish every time you need to see a change.

This first thing is, that usually a ci/stage env. which is populated to the internet and secured by a htaccess auth is imo the wrong place to develop, or? :-x

And if you really want to disabled the varnish cache, there is already a option under "System" -> "Cache Management"...

Imo the enabled option on the vcl will confuse a lot of new devs., cause this issue is hard to find. I would also avoid a new and unnecessary backend option...

**Comment by andreasemer** [comment]
Any news or feedback on this topic?

**Comment by miguelbalparda** [comment]
Yea. We believe this should be configurable via the admin using a Yes/No select being Yes the default option instead of completely removing the option. Any chance you can modify your PR to accomplish this?

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
