### ISSUE TITLE
No changes to default.vcl

### ISSUE THREAD

**Issue by kevin25** [nexcess/magento-turpentine#1113]
I am using varnishd (varnish-4.1.1 revision 66bb824)
I gave default.vcl full permissions. Btw, no changes from backend wrote to default.vcl. It's weird. Any idea?

Nginx is running under user nobody, and php-fpm is running under its owner. 

When i save configuration, i just got the message:
The configuration has been saved.

**Comment by miguelbalparda** [comment]
@kevin25 we closed #1041 for lack of feedback. It has been almost 2 months without feedback there. What happens if you remove the default.vcl file and then try to save it again?

**Comment by kevin25** [comment]
I just tried to remove it and save it again, nothing generated.

**Comment by miguelbalparda** [comment]
I don't think this is a Turpentine issue but a problem with your file system permissions/ownerships. Have you tried giving wider permissions to your var folder recursively?

**Comment by kevin25** [comment]
i did give full permissions to var/ folder as well.

**Comment by miguelbalparda** [comment]
I suggest you to try a PHP script using file_put_contents to see if that works independently from Turpentine. We use that [function](https://github.com/nexcess/magento-turpentine/blob/6ffc75169f63f3fda7d2f1196b341e0db498064d/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php#L99) to save the generated VCL.

**Comment by kevin25** [comment]
i tested file_put_contents funtion and it works.

**Comment by miguelbalparda** [comment]
I see. I suggest you to ask about this issue to your sysadmin to see why you can't save files to the filesystem.

**Comment by kevin25** [comment]
Im sysadmin. I tried to give full permissions, different owners but it hasn't worked out.

**Comment by miguelbalparda** [comment]
With proper permissions and ownership Turpentine should be able to write to the disk. I suggest you to double check those since there is nothing to indicate this is a Turpentine problem
