### ISSUE TITLE
Admin broken after SUPEE Patches

### ISSUE THREAD

**Issue by BarryCarlyon** [nexcess/magento-turpentine#1114]
```
~/public_html/var/report(master) $ cat 1356464192980 
a:5:{i:0;s:112:"Invalid method Nexcessnet_Turpentine_Model_Core_Session::validateFormKey(Array
(
    [0] => dAtSVmwp1shLX4HL
)
)";i:1;s:2225:"#0 /var/www/vhosts/fredaldous.co.uk/fredaldous.co.uk/public_html/app/code/core/Mage/Admin/Model/Observer.php(73): Varien_Object->__call('validateFormKey', Array)
#1 /var/www/vhosts/fredaldous.co.uk/fredaldous.co.uk/public_html/app/code/core/Mage/Admin/Model/Observer.php(73): Nexcessnet_Turpentine_Model_Core_Session->validateFormKey('dAtSVmwp1shLX4HL')
#2 /var/www/vhosts/fredaldous.co.uk/fredaldous.co.uk/public_html/app/code/core/Mage/Core/Model/App.php(1339): Mage_Admin_Model_Observer->actionPreDispatchAdmin(Varien_Event_Observer)
#3 /var/www/vhosts/fredaldous.co.uk/fredaldous.co.uk/public_html/app/code/core/Mage/Core/Model/App.php(1318): Mage_Core_Model_App->_callObserverMethod(Mage_Admin_Model_Observer, 'actionPreDispatchAdmin', Varien_Event_Observer)
#4 /var/www/vhosts/fredaldous.co.uk/fredaldous.co.uk/public_html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('controller_action_predispatch', Array)
#5 /var/www/vhosts/fredaldous.co.uk/fredaldous.co.uk/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(527): Mage->dispatchEvent('controller_action_predispatch', Array)
#6 /var/www/vhosts/fredaldous.co.uk/fredaldous.co.uk/public_html/app/code/core/Mage/Adminhtml/Controller/Action.php(160): Mage_Core_Controller_Varien_Action->preDispatch()
#7 /var/www/vhosts/fredaldous.co.uk/fredaldous.co.uk/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(407): Mage_Adminhtml_Controller_Action->preDispatch()
#8 /var/www/vhosts/fredaldous.co.uk/fredaldous.co.uk/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#9 /var/www/vhosts/fredaldous.co.uk/fredaldous.co.uk/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Mage_Core_Controller_Request_Http)
#10 /var/www/vhosts/fredaldous.co.uk/fredaldous.co.uk/public_html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#11 /var/www/vhosts/fredaldous.co.uk/fredaldous.co.uk/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#12 /var/www/vhosts/fredaldous.co.uk/fredaldous.co.uk/public_html/index.php(182): Mage->run('', 'store')
";s:3:"url";s:17:"/index.php/admin/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}
```

Such a delightful error.

Even though `Nexcessnet_Turpentine_Model_Core_Session` extends `Mage_Core_Model_Session` which has the `validateFormKey` function, `Varien_Object->__call()` can't call it.

Patch attached in a moment

**Comment by BarryCarlyon** [comment]
Added the renew form key function also

**Comment by miguelbalparda** [comment]
We have seen several cases with this error and most of them were not related with the upgrade but with older versions of Turpentine. Have you checked those?

**Comment by BarryCarlyon** [comment]
I haven't

I attributed it to the SUPEE, as I did SUPEE patches and upgraded turp's at the same time.

Not sure what version of turp's I was on before, I'll check when I'm in the office.

**Comment by aricwatson** [comment]
Closing for lack of feedback.

**Comment by s-hoffman** [comment]
@aricwatson, I suspect that this is not an code issue.
It would be a much, much larger bug if PHP did not implement the inheritance correctly.
(__call only picks up method invocations when there is no accessible method on the object).

Here SUPEE-7405 adds two public methods. (renewFormKey & validateFormKey).
The fact that __call was called, means that the those methods do not exist. (Or PHP has a MAJOR bug in inheritance).

A much more likely explanation is that the old session local file is still in place.
This fits the evidence; The local file was not patched by SUPEE-7405, thus the functions would not exist and __call is invoked. (Similar to the reported bugs when using the old versions of the extension),
(This could also be why the methods are re-implemented rather then calling parent::*).

It is completely possible to upgrade turpentine, and not remove the old file.
@BarryCarlyon, can you check if the local Session file exists / existed at the time of the errors.

---

You currently have taken a dependency on the implementation of Mage_Core_Model_Session, which was removed when switching to a rewrite from the local file.
I would recommend removing this code, and possibly adding some method to detect if the local file is still present in the file system. (Perhaps on saving the config?)

**Comment by BarryCarlyon** [comment]
I'm not in a position to test any more. The powers that be have decided to move away from Magento, so I don't have my build to run tests on

**Comment by s-hoffman** [comment]
@BarryCarlyon, maybe you / company still has old git repo that you can take a peek in? Did the file exist at the time, is a helpful question.
