### ISSUE TITLE
frontpage specific content doesn't show

### ISSUE THREAD

**Issue by dartsuresh** [nexcess/magento-turpentine#1118]
I have the same issue . As per our theme (SM Market) the slider has to come only in the home page which is not happening after Varnish implementation.
This is code below we have in our theme file to make the slider visible on home page.
`$routeName = Mage::app()->getRequest()->getRouteName();
$identifier = Mage::getSingleton('cms/page')->getIdentifier();

if($routeName == 'cms' && $identifier == 'home'):

We are using SM Market theme. Our theme also using slider under the header block. To manage this I tried a different header which works fine for the slider but it produces issue on the dynamic content (Cart etc).

Please advise me. Your quickest help is appreciated.

Our site = http://dev.tresbizz.com

I tried the solution [https://github.com/nexcess/magento-turpentine/issues/886](url).

**Comment by miguelbalparda** [comment]
Closing as duplicated, please use #886 in the future.
