### ISSUE TITLE
How to ban/flush cache domain/host wise

### ISSUE THREAD

**Issue by tushardatar** [nexcess/magento-turpentine#1119]
We have multiple domains on same server using same vcl file. 
when we try to clear cache for 1 store/domain then all stores/domains cache is getting flushed.

There is **X-Varnish-Host** parameter is set in headers which we can use to differentiate between each domain. 

Question :- 
How to use **X-Varnish-Host** this parameter to ban/flush cache for particular domain ? 
or is there any other way to do this. ?

**FYI**
In File :- app/code/local/Nexcessnet/Turpentine/Model/Varnish/Admin.php 
function :- flushUrl() 
we are trying to do something like :- 
$socket->ban($_SERVER['HTTP_HOST'],'obj.http.X-Varnish-URL', '~', '/*' ); OR 
$socket->ban( 'obj.http.X-Varnish-Host','==',$_SERVER['HTTP_HOST'],'obj.http.X-Varnish-URL', '~', '/*' );

but no luck  :( :(

Please help me out.

Thank you

**Comment by ravipalkonda** [comment]
Hi Tushar,

You can use below line to get this done.It should work for you.

$this->flushExpression('obj.http.X-Varnish-Host', '~', $_SERVER['HTTP_HOST'] );
please let me know if you need anything else.

Cheers,

**Comment by miguelbalparda** [comment]
@tushardatar did @ravipalkonda comment helped you?

**Comment by tushardatar** [comment]
Hi Ravi,

Yes .. It works like a charm for me !!!!!!!

Thanks 

@miguelbalparda - yes its working
