### ISSUE TITLE
Question about 1.9.3 turpentine install

### ISSUE THREAD

**Issue by Andrew415** [nexcess/magento-turpentine#1124]
Hi,

I just installed turpentine and I'm unsure if it is related to varnish or not. My setup is: varnish listens on public IP on port 80, nginx listens for requests on localhost port 80, and when pages like admin or login are called switches to nginx on port 443.

I have an issue with my payments pages 500, specifically:

checkout/cart

and

checkout/onepage/

2016/03/07 17:58:36 [error] 999#0: *471 FastCGI sent in stderr: "PHP message: PHP Fatal error:  require_once(): Failed opening required 'stripe/lib/Stripe.php' (include_path='/var/www/includes/src:.:/usr/share/php:/usr/share/pear') in /var/www/includes/src/Netgains_Stripe_Model_Stripe.php on line 5" while reading response header from upstream, client: snip, server: snip.com, request: "GET /checkout/onepage/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "www.snip.com", referrer: "http://www.snip.com/checkout/cart/"

however stripe/lib/Stripe.php does exist in the magento path and it was working prior to the varnish install, any ideas about this?

**Comment by aricwatson** [comment]
Usually the checkout pages aren't cached in Varnish. Try turning on the Varnish bypass (under *cache management*) and then test? If need be you can try adding those URLs to the blacklist.

**Comment by Andrew415** [comment]
Yes your right, we identified the issue as plugin related, closing.
