### ISSUE TITLE
an xhr file increases page load time in some categories. initiator prototype.js:1530

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#1125]
My configuration is Magento 1.9.2.4 + Sample Pack, Varnish 4.0, Turpentine latest dev. No changes, everything is by default. This issue appears in some categories (e.g. VIP). Inspect the category page in your browser. I am using Chrome, go to Network tab and by the end there is an xhr file. This file increases the page time load, between 84 to 110 ms and will remain always the same. This xhr file has a very long name including turpentine in path (see headers bellow). Initiator is prototype.js line 1530. I would like to find a solution for getting rid off this. Here are screenshots for a better understanding:

<strong>Page time load</strong>

![image1](https://cloud.githubusercontent.com/assets/8360474/13583665/57f1eed6-e4bb-11e5-9834-61f42f33d6a1.jpg)

<strong>Reference to prototype.js</strong>

![image2](https://cloud.githubusercontent.com/assets/8360474/13583662/5601d848-e4bb-11e5-8cb9-13aa3084d8c2.jpg)

<strong>Prototype.js line 1530</strong>

![image3](https://cloud.githubusercontent.com/assets/8360474/13583641/365ceca8-e4bb-11e5-849d-90254ab953cf.jpg)

<strong>XHR file Headers</strong>

![image4](https://cloud.githubusercontent.com/assets/8360474/13583637/31b32d16-e4bb-11e5-9751-5b679b4d3905.jpg)

**Comment by aricwatson** [comment]
That is the ajax call for the community poll block. It will slightly increase page load time since the ajax won't fire until after the DOM loads.  If this is causing problems on a live site you could rework the poll module, or just not use it.

**Comment by ADDISON74** [comment]
I am trying not using it for the moment. I followed these steps:

1) I closed all active Polls then I disabled the module from Advanced section in backend (Mage_Poll).
2) I flushed the whole cache and browser cache and reloaded again the page.

The issue is still there. Page time load is 100 ms average. I restarted varnish service to clear again the cache. No chance, that xhr file is still loading even there are no active polls and poll module disabled.

Could this happened because Turpentine is still extending the Poll class? See this issue #1093.

**Comment by ADDISON74** [comment]
It couldn't be the Community Poll. In Magento sample pack Poll Side Block it's active in other categories and is not creating any trouble. Only in VIP section and a few other subcategories randomly. Even I disable the Poll module nothing good is happening.

**Comment by aricwatson** [comment]
Closing this in favor of https://github.com/nexcess/magento-turpentine/issues/1093
