### ISSUE TITLE
changing admin path

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#1127]
By default to access your Magento backend you use /admin after your domain name. I changed the other days this path to something else for someone because too many attempts of break-in. Today he phoned me he cannot do tasks in Backend. For example deleting search terms. Once you submit Delete action nothing is happening. Immediately I knew it was a caching issue, bypassing Varnish everything worked as expected. All trouble came from changing the admin path.

<strong>Question</strong>: Is Turpentine using information from local.xml file located in /app/etc/ about admin path? Or do I need to add this path in URL Blacklist or changing Turpentine files?

Here is local.xml file content

```php
<admin>
        <routers>
            <adminhtml>
                <args>
                    <!-- <frontName><![CDATA[admin]]></frontName> -->
                    <frontName><![CDATA[789654123]]></frontName>
                </args>
            </adminhtml>
        </routers>
    </admin>
</config>
```

**Comment by magenx** [comment]
add to blacklist and use ssl

**Comment by aricwatson** [comment]
> Question: Is Turpentine using information from local.xml file located in /app/etc/ about admin path? Or do I need to add this path in URL Blacklist or changing Turpentine files?

Yes, it's inserted into the VCL template after being determined by [this code](https://github.com/nexcess/magento-turpentine/blob/6ffc75169f63f3fda7d2f1196b341e0db498064d/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php#L174). 

You probably just needed to re-apply your Turpentine-generated VCL after making the change.

**Comment by ADDISON74** [comment]
@magenx: I can blacklist the path. That website is using SSL already. Thank you.

@aricwatson: You are right. I was checking the content of the VCL file in Terminal for new admin path and it was not there. So I saved and applied again and now the new path is found in the file, no more issues in backend and no need to add the path to blacklist. Many thanks.

I will close this issue.

**Comment by sr972** [comment]
@ADDISON74 
did you just include 789654123 in a line?
I am wondering why my custom backend URL isn't working and i get 503 Gurus from time to time. As i have store view code enabled my backend URL is not just /index.php/789654123, it is /index.php/admin/789654123

Do i need to set (per line) admin, 789654123 and admin/789654123 ?

Would be nice if you could answer.

**Comment by ADDISON74** [comment]
Why to use 789....? This was my generic example for replacing admin name with something else. See how I commented the original line then added a new one with path for admin. But that is not may real path.

Be very careful doing this. You should already be logged into your admin account, change manually local.xml then save a new Turpentine file on disk. As @aricwatson said Turpentine replace admin path with the new one. Flush cache and restart Varnish. It should work just perfect. This issue was open because I did a mistake in steps and I did not let Varnish know about the new admin path. So I could not log into my account without editing default.vcl and changing admin to new path and restarting Varnish service.

**Comment by ADDISON74** [comment]
Guru meditation means Varnish is not talking with its backend (webserver). Your path is wrong because you did a mistake in local.xml for sure. admin should not be in your path, just 789....

Just read my initial post carefully and see how I changed that file. admin is replaced by 789.... and path  for accessing backend is www.mydomain.com/789... not www.mydomain.com/admin/789...

**Comment by sr972** [comment]
@ADDISON74 
Well, admin IS in path as soon as you enable store view codes in URL.
I know how to change the admin path, done it several times, but as soon as you put store view code into URLs via Magento settings (like you have store views e.g. 'de', 'en'), you'll see http://exampleshop.com/de/ or http://exampleshop.com/en/. 
In fact, the backend is just another store view. 

As long as you don't use store view codes in URLs, you're right, the BE url will be http://exampleshop.com/index.php/789654123/. As soon as the feature is enabled, it's http://exampleshop.com/index.php/admin/789654123/ (as 'admin' is the store view code, checkout table 'core_store').

That i've used your 789654123 was just for demo/asking. For sure i set my own BE url :)
