### ISSUE TITLE
header dissapears switching user agents

### ISSUE THREAD

**Issue by craigcarnell** [nexcess/magento-turpentine#1128]
If I use chrome developer tools and switch between Desktop, Mobile etc the header dissappears in Varnish

The rest of the page is present.

**Comment by aricwatson** [comment]
Do you mean it doesn't look like this?
![screen shot 2016-03-08 at 2 43 58 pm](https://cloud.githubusercontent.com/assets/7072513/13613967/47319462-e53c-11e5-9824-b9c61a18b060.png)

**Comment by craigcarnell** [comment]
@aricwatson Nope the menu is missing

**Comment by aricwatson** [comment]
I see - this is for a custom theme? Does it only show up in Desktop and not mobile, or once it disappears, is it gone for good? Any errors in the mage log or javascript console?

**Comment by aricwatson** [comment]
Closing for lack of feedback.

**Comment by mobweb** [comment]
I have the exact same issue as I have just discovered. Heres how I can reproduce it:

- Open home page in Chrome, everything is fine
- Reload the page, still everything is fine
- Open Chrome Dev Tools, enable the "Device Toolbar" and switch to a different device (for example "iPhone 6")
- Reload the page, now the header is missing

I checked the source code via the "Network" tab and I can confirm that it's indeed missing from the returned HTML source code, so I don't think it's a client-side or theme-related issue?

Should I open a separate ticket? I can also provide a link to a live website where this occurs, but I'd rather not share it publicly.

Thanks!

**Comment by aricwatson** [comment]
Hmm. And this is with the standard demo store? I can't replicate this either way on our demo site... Can you test on our demo site: http://turpentine-master.devsupport.nexcess.net/

We did find a tricky bug last week involving user agent normalization. Do you have this option set in your Turpentine settings?
