### ISSUE TITLE
Cache Storage Management is broken after Extension deactivation

### ISSUE THREAD

**Issue by knospe-** [nexcess/magento-turpentine#1133]
Hi,

I'm using Magento CE 1.9.2.2.

I have deactivated the Turpentine Module via Magento Backend (System > Configuration > Advanced > Disable Modules Output) and I have logout ob the Backend, Cleared Magento Cache and Logged Back in.
Now I do not see the Table of Caches under System>Cache Management in Magento BE.

Is this a known issue and does anyone have a clue how to fix it?

**Comment by miguelbalparda** [comment]
Have you tried setting the active tag to false inside app/etc/modules/Nexcessnet_Turpentine.xml?

**Comment by knospe-** [comment]
@miguelbalparda That solved it! Thank you :)
