### ISSUE TITLE
configuration file help

### ISSUE THREAD

**Issue by TruthF** [nexcess/magento-turpentine#1135]
- OS CentOS 7
- Magento CE 1.9.0.1
- Turpentine: RELEASE 0.6.8 (got it succesfully installed from here: https://www.magentocommerce.com/magento-connect/turpentine-varnish-cache.html
- Varnish: 4.0.3
- Nginx: 1.8.1

I was trying to follow this guide https://blog.nexcess.net/2012/05/21/installing-varnish-for-your-magento-store-on-centos-6/ but realized that it is too old written years ago back in 2012. So, I went to Turpentine github https://github.com/nexcess/magento-turpentine/wiki/Installation and followed the steps from there. Now, extension is successfully installed without any error and I can see it under admin panel now I need to configure it for which I looked into https://github.com/nexcess/magento-turpentine/wiki/Configuration section but it appears to me as they are just describing things instead of kind of steps needs to be done, so i am getting confused here.

If I check the blog again after git, and follow it from step 4 that also does not apply to me since I am using Nginx and also some variables in that blog are very old. Has someone gone through with this before and got a good idea for what action needs now to be taken place? should I simply change Nginx listening port to 8080 and Varnish to 80, if yes than where exactly? Following are my current files

/etc/varnish/default.vcl
```
# This is an example VCL file for Varnish.
#
# It does not do anything by default, delegating control to the
# builtin VCL. The builtin VCL is called when there is no explicit
# return statement.
#
# See the VCL chapters in the Users Guide at https://www.varnish-cache.org/docs/
# and http://varnish-cache.org/trac/wiki/VCLExamples for more examples.

# Marker to tell the VCL compiler that this VCL has been adapted to the
# new 4.0 format.
vcl 4.0;

# Default backend definition. Set this to point to your content server.
backend default {
    .host = "127.0.0.1";
    .port = "8080";
}

sub vcl_recv {
    # Happens before we check if we have this in cache already.
    #
    # Typically you clean up the request here, removing cookies you don't need,
    # rewriting the request, etc.
}

sub vcl_backend_response {
    # Happens after we have read the response headers from the backend.
    #
    # Here you clean the response headers, removing silly Set-Cookie headers
    # and other mistakes your backend does.
}

sub vcl_deliver {
    # Happens when we have all the pieces we need, and are about to send the
    # response to the client.
    #
    # You can do accounting or modifying the final object here.
}

```
Do I need to change .host IP to my site public IP and .port to 80 here? and some other settings?

/etc/varnish/varnish.params
```
# Varnish environment configuration description. This was derived from
# the old style sysconfig/defaults settings

# Set this to 1 to make systemd reload try to switch vcl without restart.
RELOAD_VCL=1

# Main configuration file. You probably want to change it.
VARNISH_VCL_CONF=/etc/varnish/default.vcl

# Default address and port to bind to. Blank address means all IPv4
# and IPv6 interfaces, otherwise specify a host name, an IPv4 dotted
# quad, or an IPv6 address in brackets.
# VARNISH_LISTEN_ADDRESS=192.168.1.5
VARNISH_LISTEN_PORT=6081

# Admin interface listen address and port
VARNISH_ADMIN_LISTEN_ADDRESS=127.0.0.1
VARNISH_ADMIN_LISTEN_PORT=6082

# Shared secret file for admin interface
VARNISH_SECRET_FILE=/etc/varnish/secret

# Backend storage specification, see Storage Types in the varnishd(5)
# man page for details.
VARNISH_STORAGE="malloc,1G"

# Default TTL used when the backend does not specify one
VARNISH_TTL=120

# User and group for the varnishd worker processes
VARNISH_USER=varnish
VARNISH_GROUP=varnish

# Other options, see the man page varnishd(1)
DAEMON_OPTS="-p thread_pool_min=5 -p thread_pool_max=500 -p thread_pool_timeout=300 -p cli_buffer=16384 -p feature=+esi_ignore_other_elements -p vcc_allow_inline_c=on"
```

Do I also need to uncomment and change the VARNISH_LISTEN_ADDRESS=192.168.1.5 and VARNISH_LISTEN_PORT=6081 to public IP address of my website and port to 80? and what about VARNISH_ADMIN_LISTEN_ADDRESS=127.0.0.1 and VARNISH_ADMIN_LISTEN_PORT=6082 also just to make you aware I did configure DAEMON_OPTS= options according to as described in section 2 of https://github.com/nexcess/magento-turpentine/wiki/Installation

/etc/nginx/conf.d/example.org.conf
```
server {
    listen 155.27.132.123:80;
    listen 155.27.132.123:443 ssl;
    server_name example.org *.example.org;
    root /home/www/vhosts/example.org/httpdocs;

    ssl_certificate      /etc/nginx/ssl/example.org.com.crt;
    ssl_certificate_key  /etc/nginx/ssl/example.org.com.key;
    ssl_protocols        TLSv1 TLSv1.1 TLSv1.2;

    location / {
        index index.html index.php;
        try_files $uri $uri/ @handler;
        expires 30d;
    }
```

Do I need to change the listen port to 8080 here? i tried to do that but it was keep showing the Nginx default page.

Admin > System > Cache Management 
![varnish_settings_1](https://cloud.githubusercontent.com/assets/17805716/13726503/f0b4ef7c-e8eb-11e5-9aa7-90c380e78253.PNG)

s this fine or do I need to make any change here?

Admin > System > Configuration > Varnish Options > Servers 
![varnish_settings_2](https://cloud.githubusercontent.com/assets/17805716/13726507/0b9aa1ba-e8ec-11e5-8d74-15cc4dfe316e.PNG)

Do I need to make any change here? i think I need to enter Varnish Authentication Key from /etc/varnish/secret file? Also, Config File Location & Custom VCL File Location are not there where path is defined. Will these be generated when I press Admin > System > Cache Management > Varnish Management > Apply Varnish Config. If that is the that VCL settings are being generated from here case than would I still require to edit /etc/varnish/default.vcl & /etc/varnish/varnish.params or these will be overwritten by Turpentine Magento admin section? also why the paths here in above image why the paths are defined as {{root_dir}}/var/default.vcl & {{root_dir}}/app/code/community/Nexcessnet/Turpentine/misc/custom_include.vcl 

Finally what to do with Admin > System > Configuration > Caching Options > Backend 

![varnish_settings_3](https://cloud.githubusercontent.com/assets/17805716/13726511/63b1ef5c-e8ec-11e5-8a53-a3cc7c9e0f4c.PNG)

Do I need to define my server public interface IP in Backend Host and port 80 in Backend Port

Finally, thanks for your time to read this and I hope that I will be able to overcome this varnish cache issue and this post will help many more.

**Comment by ADDISON74** [comment]
First you have to understand how the data flows into your server:

Varnish (SERVER_IP, port 80) -> Nginx (SERVER_IP or LOCALHOST, port 8080)

I do recommend using IP_EXT for Nginx in this case:

(Varnish)
Edit /etc/varnish/default.vcl
```php
backend default {
    .host = "SERVER_IP";
```

/etc/varnish/varnish.params nothing to change you configuration is fine including DAEMON_OPTS.

(Nginx)
- issue 1: Nginx should listen on Varnish backend default .host and .port. see above.
- issue 2: Nginx can deal with SSL but not behind Varnish. I do recommend using Pound in front of Varnish for both ports 80 and 443 and commenting listen line for ssl in Nginx. Pound it is a small service and easy to configure. You can use Nginx as well for ssl offloading and transferring decrypted data to Varnish 80 port.

(Magento Cache Management)
- select Block HTML output and Disable it
- select Varnish Pages and Varnish ESI Blocks and Enable them

(Turpentine first image)
- Varnish Version: set it to your Varnish version prior
- Server List: OK as it is
- Varnish Authentication Key: paste here /etc/varnish/secret content with this character at the end of the string \n (all is mentioned in Turpentine Wiki)

(Turpentine second image)
- Backend Host: Your Nginx listen IP
- Backend Port: Your Nginx listen port
- Leave Crawler IP Addresses empty

You need create a symbolic link from your Magento /var/default.vcl to /etc/varnish/default.vcl. Backup default.vcl before doing this (mv default.vcl default.vcl.org). <strong>Read the WIKI prior</strong>.

If you search with Google you can find numerous tutorials for setting up Varnish + Nginx. The most important thing is making them communicating each other, without Turpentine. Once they communicate add Turpentine extension and just configure it in Magento backend.

**Comment by ADDISON74** [comment]
When you configuration works let me know inspecting in browser Network section if you get time for css, js, jpeg files. I found issues related to Age header in CentOS 7 mainly from Varnish 4.X packages. Keep in mind using 3.0.7 for CentOS.

**Comment by TruthF** [comment]
@ADDISON74 Thanks for your help. I have now configured Varnish successfully which seems to be working fine. However, I have configuration like this. Please let me know if I am wrong anywhere

> My server public IP address is 99.25.55.148

**/etc/varnish/default.vcl**
```
#
# This is an example VCL file for Varnish.
#
# It does not do anything by default, delegating control to the
# builtin VCL. The builtin VCL is called when there is no explicit
# return statement.
#
# See the VCL chapters in the Users Guide at https://www.varnish-cache.org/docs/
# and http://varnish-cache.org/trac/wiki/VCLExamples for more examples.

# Marker to tell the VCL compiler that this VCL has been adapted to the
# new 4.0 format.
vcl 4.0;

# Default backend definition. Set this to point to your content server.
backend default {
    .host = "99.25.55.148";
    .port = "8080";
}

sub vcl_recv {
    # Happens before we check if we have this in cache already.
    #
    # Typically you clean up the request here, removing cookies you don't need,
    # rewriting the request, etc.
}

sub vcl_backend_response {
    # Happens after we have read the response headers from the backend.
    #
    # Here you clean the response headers, removing silly Set-Cookie headers
    # and other mistakes your backend does.
}

sub vcl_deliver {
    # Happens when we have all the pieces we need, and are about to send the
    # response to the client.
    #
    # You can do accounting or modifying the final object here.
}
```

At here I changed manually both .host & .port like this
```
backend default {
    .host = "99.25.55.148";
    .port = "8080";
}
```

**/etc/varnish/varnish.params**
```
# Varnish environment configuration description. This was derived from
# the old style sysconfig/defaults settings

# Set this to 1 to make systemd reload try to switch vcl without restart.
RELOAD_VCL=1

# Main configuration file. You probably want to change it.
VARNISH_VCL_CONF=/home/www/vhosts/example.org/httpdocs/var/default.vcl

# Default address and port to bind to. Blank address means all IPv4
# and IPv6 interfaces, otherwise specify a host name, an IPv4 dotted
# quad, or an IPv6 address in brackets.
VARNISH_LISTEN_ADDRESS=99.25.55.148
VARNISH_LISTEN_PORT=80

# Admin interface listen address and port
VARNISH_ADMIN_LISTEN_ADDRESS=127.0.0.1
VARNISH_ADMIN_LISTEN_PORT=6082

# Shared secret file for admin interface
VARNISH_SECRET_FILE=/etc/varnish/secret

# Backend storage specification, see Storage Types in the varnishd(5)
# man page for details.
VARNISH_STORAGE="malloc,12G"

# Default TTL used when the backend does not specify one
VARNISH_TTL=120

# User and group for the varnishd worker processes
VARNISH_USER=varnish
VARNISH_GROUP=varnish

# Other options, see the man page varnishd(1)
DAEMON_OPTS="-p thread_pool_min=5 -p thread_pool_max=500 -p thread_pool_timeout=300 -p cli_buffer=16384 -p feature=+esi_ignore_other_elements -p vcc_allow_inline_c=on"
```

At here, instead of creating sym links for VARNISH_VCL_CONF I used the complete path like this
`VARNISH_VCL_CONF=/home/www/vhosts/example.org/httpdocs/var/default.vcl`
and 
```
VARNISH_LISTEN_ADDRESS=99.25.55.148
VARNISH_LISTEN_PORT=80
```
and
`VARNISH_STORAGE="malloc,12G"`
Since I have lots of RAM on machine I used VARNISH_STORAGE="malloc,12G", is there there any issue with this? and do I need to use both disk and RAM to store cache if there is any better in it?

**/etc/nginx/conf.d/example.org.conf**
```
server {
    listen 99.25.55.148:8080;
    listen 99.25.55.148:443 ssl;
    server_name example.org www.example.org;
    access_log /home/www/vhosts/example.org/logs/access.log;
    error_log /home/www/vhosts/example.org/logs/error.log;
    root /home/www/vhosts/example.org/httpdocs;

    #ssl on;
    ssl_certificate      /etc/nginx/ssl/example.org.crt;
    ssl_certificate_key  /etc/nginx/ssl/example.org.key;
    ssl_protocols        TLSv1 TLSv1.1 TLSv1.2;

    location / {
        index index.html index.php;
        try_files $uri $uri/ @handler;
        expires 30d;
    }
}
```
Is this fine?

**Admin > System > Cache Management**
![cache_management](https://cloud.githubusercontent.com/assets/17805716/13907554/c8ebb444-ef12-11e5-92c6-a4da8d09e827.PNG)

Since I also followed this article https://rajeshganjeer.wordpress.com/2014/05/28/varnish-with-magento-terpentine/, I disabled all kind of cache for Magento including Block HTML output and only enabled Varnish Pages & Varnish ESI Blocks, is this fine or do I just need to just disable Blocks HTML output and enable all others?

**Admin > System > Configuration > Varnish Options > Servers**
![varnish_servers](https://cloud.githubusercontent.com/assets/17805716/13907595/89231518-ef13-11e5-8731-7b9ef76af8da.PNG)
Is this fine?

**Admin > System > Configuration > Caching Options > Backend**
![varnish_caching_options](https://cloud.githubusercontent.com/assets/17805716/13907641/aae88312-ef14-11e5-955b-6b7c558d1a3e.PNG)
Is this fine?

Finally, this is true that with CentOS 7 and Varnish 4.X(my one is 4.0.3) the Age header  is always 0. This is causing all ranking sites like Google to make our ranking down and keep suggesting

> Setting an expiry date or a maximum age in the HTTP headers for static resources instructs the browser to load previously downloaded resources from local disk rather than over the network.

I googled for this issue quite a long and defined following in **/var/www/vhosts/example.org/httpdocs/var/default.vcl**

```
sub vcl_backend_response {
    if (bereq.url ~ "\.(png|gif|jpg|swf|css|js|pdf)$") {
    unset beresp.http.set-cookie;
    set beresp.http.cache-control = "max-age = 2593000";
  }
}
```

but issue still persists :(... I don't want to downgrade my Varnish version as you said since I have hardly managed to configure all of them correctly. So, please help also help me here? there would must be some workaround. Like may be if I follow this https://github.com/nexcess/magento-turpentine/issues/1014 and define vcl_backend_response at the end of custom VCL file?

**Comment by ADDISON74** [comment]
Your configuration seems to be just fine. Use RAM for database than Varnish. 1G or 2G are just enough for 2000 products. For Age 0 I don't have any solution hope someone will hear us and help. CentOS 6.7 + Varnish 3.7 seems to work better than CentOS 7.2 + Varnish 4.1, my personal impression after testings. To avoid any issues I prefer Debian for being more solid and good repositories than CentOS. We are not using cPanel at all.

Seeing your SSL configuration for Nginx, your visitors are touching directly the webserver this is not good. Why don't you use Pound in front of Varnish for listing on both ports 80 and 443 and passes data to Varnish which communicates with Nginx without SSL? You can find in here a post of mine how to configure Pound. It will help you to switch from Varnish to Nginx just editing two lines if something is going wrong with Varnish.

**Comment by TruthF** [comment]
@ADDISON74 My products are around 100K and have plenty of RAM available so I think it would be fine to use VARNISH_STORAGE="malloc,12G"? But, I am having an strange issue that when I open browser and try to open my website or inner pages for the second time it comes from Varnish and pretty quick, at the same time if I go to another PC/network(or sometimes even different browsers on same PC) and try to load the same page it becomes slow. I am using all the default settings of Turpentine in my VCL config.

Could it be because I am storing everything in RAM and there might be a default behaviour of memory to just wipe out after every minute or second? or there could be another issue?

Please look at Admin > System > Configuration > Caching Options
![1](https://cloud.githubusercontent.com/assets/17805716/13931694/5793e10e-efc6-11e5-80de-0e2aad1b9237.PNG)
![2](https://cloud.githubusercontent.com/assets/17805716/13931699/5c6fcbd4-efc6-11e5-8dcb-fdf132a084b9.PNG)
![3](https://cloud.githubusercontent.com/assets/17805716/13931702/609a7876-efc6-11e5-9cbf-6dbe34259676.PNG)
![4](https://cloud.githubusercontent.com/assets/17805716/13931712/65386758-efc6-11e5-9995-66261e1d0b36.PNG)

**Comment by ADDISON74** [comment]
It is not an issue. First bite is always slow. It is based on sessions. No worries about.

By the way in set up process, did you create a symbolic link from /magento_folder/var/default.vcl to /etc/varnish? It is important, Varnish must know the configuration provided by Turpentine not the default one from above.

In Terminal do as follows:

1. mv /etc/varnish/default.vcl /etc/varnish/default.vcl.original.
2. ln -s /home/your_user/public_html/var/default.vcl /etc/varnish/default.vcl
3. service varnish restart

Related to memory it is not a problem, Varnish will occupy as it needs. You can allocate 3 G's and check in production the size of your free memory. I am dealing with one server which has 35.000 Simple Products and Varnish is working great with 2 to 4 G's. Varnish is a must have in all Magento stores. We are lucky Nexcess is offering in continuing this work for free.

**Comment by TruthF** [comment]
@ADDISON74 

1. I have under **/etc/varnish/varnish.params**

```
# Main configuration file. You probably want to change it.
VARNISH_VCL_CONF=/home/www/vhosts/example.org/httpdocs/var/default.vcl

```
Do you think symlink is still needed?

2. If you are saying that "First bite is always slow" than does it mean it will be slower for each different browser, and each session/connection? this is what is actually hapenning with me.

3. Almost all the stores I have seen which are providing page in like milliseconds does not encounter the same issue. When I browse those sites from various connections it all looks same with pretty much same speed.

**Comment by ADDISON74** [comment]
I prefer the symbolic link into /etc/varnish. I try as much as possible to avoid permission issues. For example default.vcl is owned by your vhost and same for group, but Varnish is running by varnish user and varnish group, symbolic link must be created with root privileges. I had a problem in the past with AWstats and Varnishlog and it took me a half an hour to understand why it is not working. It was permissions.

Don't worry about speed. It is more complex than that. Check in your browser for Age header files like css, js, png, jpeg  Age. Sorry in CentOS is not working. You will be surprised to see static files has appropriate ages in two running browser, this means the elements are coming from Varnish. The only thing which slows down is a new session and different esi policies.

**Comment by ADDISON74** [comment]
If you want doing SSL offloading with Pound use this tutorial I created: #1052.

**Comment by TruthF** [comment]
@ADDISON74 As you said

> The only thing which slows down is a new session and different esi policies.

Is it the normal behavior of how it should work, because this means that for the first time visitor he will never benefit from Turpentine/Varnish(due to new session) and for each page he has to browse twice(one with slow and than get it from cache) to see speed? How other stores are maintaining their speed even with first byte their pages always seems to come from cache.

Also, if you see here http://magento.stackexchange.com/questions/107278/magento-with-turpentine-per-session-connection-speed-issue what does it mean by

> this is wrong, Turpentine works very good for the first visit on cached page if no session cookie.

and is my setting wrong somewhere for this?

**Comment by aricwatson** [comment]
@TruthF this is normal behavior for Turpentine (passing the first request through to receive a valid session cookie. You can try bypassing this behavior by using the "observer fix" in the Turpentine configuration. This option removes some of the protections against CSRF attacks, so we generally recommend avoiding it. 

Once a valid session has been established, other pages will be loaded from the Varnish page cache (if they're in the cache already). Same for ESI blocks - although private ESI blocks may not yet be in the cache if it's a new request.

**Comment by farazhkhan** [comment]
@aricwatson 

> Once a valid session has been established, other pages will be loaded from the Varnish page cache (if they're in the cache already). Same for ESI blocks - although private ESI blocks may not yet be in the cache if it's a new request.

So, once the pages go to varnish it does not matter from which network/browser/PC the page is recalled again, it will always come up directly next time from Varnish? or even within the Varnish it will again look for session ID's for other client and if not found will once again create a new session?

**Comment by aricwatson** [comment]
> So, once the pages go to varnish it does not matter from which network/browser/PC the page is recalled again, it will always come up directly next time from Varnish? 

If it's the same session, then in general yes (subject to other caching policy choices). But if you use a new browser, it'll be starting with a new session and the first request will be passed to Magento.


> or even within the Varnish it will again look for session ID's for other client and if not found will once again create a new session?

The session ID is tied to the frontend cookie. So, if a request comes in without a `frontend` cookie - the request will be passed through to Magento. You can trigger this yourself if you want to test - go to a page on the site, reload once and check that you have a `frontend` cookie. You should see pages getting loaded from the cache if your reload. Delete the `frontend` cookie and hit reload - and you'll the request get passed to the backend. This is all assuming you're using the default "VCL fix"
