### ISSUE TITLE
Esi options for block inside block.

### ISSUE THREAD

**Issue by R0n1n-77** [nexcess/magento-turpentine#1138]
Hi,

I have a pretty challenging issue.
I have a two blocks which I have to set esi options for. I have no other option than cache both per-user, because both contain a user specific elements. The problem is that in a theme's local.xml they are loaded one inside another like this:

```
<block type="core/template" name="topline" as="topline" template="custom/topline.phtml">
                <action method="insert">
                    <block_name_to_insert>top.links</block_name_to_insert>
                    <sort_relative_to_other_childname/>
                    <sort_before_or_after/>
                    <alias>topLinks</alias>
                </action>
                <block type="page/switch" name="store_language" as="store_language" template="page/switch/languages.phtml"/>
                <block type="directory/currency" name="currency_top" template="page/switch/currency.phtml"/>
                <block type="customer/form_login" name="mini_login" template="customer/form/mini.login.phtml"/>
                <block type="core/template" name="socialogin" as="socialogin" template="customer/socialogin.phtml"></block>
                <block type="buyshopconfig/twitter" name="twitter_last_feed" as="twitter_last_feed" template="twitter/twitter_last_feed.phtml"/>
            </block>
```

I have no problem setting ESI options for "topline" like this:

```
        <reference name="topline">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                        <dummy_blocks>
                                <head/>
                        </dummy_blocks>
                    <flush_events>
                        <customer_login/>
                        <customer_logout/>
                    </flush_events>
                </params>
            </action>
        </reference>
```

Or for "top.links" like this:

```
<reference name="top.links">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                        <dummy_blocks>
                        </dummy_blocks>
                    <flush_events>
                        <catalog_product_compare_add_product/>
                        <catalog_product_compare_remove_product/>
                        <catalog_product_compare_item_collection_clear/>
                        <sales_quote_save_after/>
                        <checkout_cart_product_add_after/>
                        <checkout_cart_update_items_after/>
                        <checkout_cart_product_update_after/>
                    </flush_events>
                <!--    <method>ajax</method> -->
                </params>
            </action>
        </reference>
```

Caching works perfectly for each of them separately. The problem starts if define ESI for both of them, as described above.
Then Topline block is cached and served correctly on all pages, but top.links fails to render. It actually shows up, but isn't working. It is a drop-down with six more links inside it. So the block itself is showing on pages, but links inside are not, the drop-down isn't working at all.

My environment is:
Magento 1.9.2.2
Turpentine 0.6.8
Varnish 3

Will appreciate any ideas.

**Comment by aricwatson** [comment]
I'd suggest removing the special ESI policy for the inner block and setting a policy on the outer block that includes all the flush events, etc that you need for the inner block.

**Comment by R0n1n-77** [comment]
Hi,
@aricwatson , thanks for suggestion.
I already tried that. As I wrote previously ESI option work if I define the for one of the blocks either inner or outer.
The challenge here, that there's a user specific content in both blocks.
Outer has a login dependent div and inner has three blocks inside it(wishlist, conpare and login) rendered as a drop-down.
So I need both of them to be cached on a per user basis.
In addition, when I set ESI for the outer block, the inner fails to render whether it has ESI options set or not.

**Comment by akira28** [comment]
I have a similar issue, but in my case I want to completely disable cache for a block inside the header (a currency switcher) and leave the header as "private". Is this even possible? Or I have to disable cache for the whole header?

**Comment by R0n1n-77** [comment]
@akira28, I'm not sure if setting a full header to private would work, but I'd try to set it in a local.xml of you theme. In my case, I discovered, that whatever I define in turpentine_esi.xml doesn't work for my theme.

As for block inside header, try setting method to ajax inside theme's local.xml. Varnish doesn't cache ajax requests by default.

**Comment by R0n1n-77** [comment]
Has anyone had a time to take a look on it?

**Comment by aricwatson** [comment]
> I have a similar issue, but in my case I want to completely disable cache for a block inside the header (a currency switcher) and leave the header as "private". Is this even possible? Or I have to disable cache for the whole header?

You can set the whole header block to be cached privately - in fact that's the default behavior from the *turpentine_esi.xml* file.

@R0n1n-77 Sorry without direct access to the site it's hard to give recommendations. I'd suggest trying to change your layout so that one block doesn't contain the other and you can set ESI policies for both of them. Or is it possible to remove all ESI policies on both of those blocks that need to be private, and instead set a private ESI caching policy on a block that *contains* both of the problem blocks?

**Comment by R0n1n-77** [comment]
@aricwatson
 Concerning the layout change. This will most probably work, I agree with you, but one of my goals was to minimize the changes to the code.
Regarding your second suggestion. Both of the mentioned blocks are contained inside a "root" reference. I think I already tried setting it all to private at the beginning of my troubleshooting.
I'll give it another try and will post the results shortly.

**Comment by R0n1n-77** [comment]
@aricwatson  Setting ESI for the containing block, sadly, didn't work in this case neither.
The "topline" block(upper one) is loaded directly inside Mage_Page_Block_Html and caching it privately is like caching privately the whole page if I'm not mistaken.
Secondly, I noticed that the actual issue is not caching itself.
The "top.links" block(inner one) has a nested div inside it. How exactly it is loaded is above my knowledge.
Setting ESI for both the upper block breaks this nested div.
I'm currently waiting for someone from my dev team to take a look into it and will update is we'll get to any solution.
If providing my local.xml will help you to understand the issue better, just let me know.

**Comment by aricwatson** [comment]
I see - let us know what you dev team comes up with and we'll do what we can to help... Pretty hectic around here though with Imagine coming up!

**Comment by diglin** [comment]
Looks like I have the same issue as @R0n1n-77 regarding the topLinks items and Varnish and looks like we use the same template.

I fixed it in this way by changing the local.xml. It works better even if it's not perfect:

I replaced:
```
<block type="core/template" name="topline" as="topline" template="custom/topline.phtml">
                <action method="insert">
                    <block_name_to_insert>top.links</block_name_to_insert>
                    <sort_relative_to_other_childname/>
                    <sort_before_or_after/>
                    <alias>topLinks</alias>
                </action>
                ...
            </block>
```

with the following in the default handle:

```
            <block type="core/template" name="topline" as="topline" template="custom/topline.phtml">
                <block type="page/template_links" name="top.links" as="topLinks"/>
                ...
            </block>
```

and

```
        <reference name="topline">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <scope>page</scope>
                    <flush_events>
                        <sales_quote_save_after/>
                    </flush_events>
                </params>
            </action>
        </reference>
```
