### ISSUE TITLE
Modpagespeed and Varnish

### ISSUE THREAD

**Issue by evensis** [nexcess/magento-turpentine#1139]
Hi,

I'm just going through a setup with modpagespeed installed, and have noticed it is rather mucking up the layout of the webpage.

I've narrowed this down to the form key on the page causing all the problems with a duplicated page within itself (duplicates and renders itself to a 404 page, based on how many form keys are on the page, so if we have 4 form keys, then expect 4, 404 pages rendered within themselves on the page). So this narrows it down to ESI causing the issues.

I've tried modpagespeed on Pass Through mode, however it is still continuing to do it. Which is a mighty shame, as modpagespeed is excellent and has had a noticeable impact on page load times as the site is extremely DOM heavy.

The fix posted for mod page speed, unfortunately doesn't work in this instance. Strange thing in that the passthrough mode should stop it stripping comments, but for some reason it is not doing that and continuing to wipe out the page.

Switching modpagespeed off resolves all issues.

Does anyone have any suggestions with this problem, would rather have both working in tandem!?

Thanks in advance.

**Comment by miguelbalparda** [comment]
You should check https://developers.google.com/speed/pagespeed/module/downstream-caching 

If you disable mod_pagespeed you shouldn't have issues with varnish.

**Comment by data-digger** [comment]
Don't use Varnish in front of mod_pagespeed. mod_pagespeed has it's own User-Agent (and other) normalization which probably isn't the same as the one you use in Varnish. Plus mod_pagespeed might dynamically remove certain files it generated (for example it might remove .webp image in favor of some other format, but Varnish would keep serving HTML with non existent .webp resource).

Using mod_pagespeed in front of Varnish should work fine though.
