### ISSUE TITLE
Leverage browser caching with magento-turpentine installed

### ISSUE THREAD

**Issue by farazhkhan** [nexcess/magento-turpentine#1140]
Magento is running on 1.9.x, and web server is Nginx 1.8.1 having Varnish 4.0.3 installed on it using Turpentine plugin. Site speed is very fine when running from any browser due to Varnish cache but page speed showing in Google PageSpeed Insights, GTmetrix or Pingdom all are specifically suggesting to "Leverage browser caching". 

I made the changes in **/etc/nginx/conf.d/default.conf** & **/etc/nginx/conf.d/mysite.conf** and restarted all services

```
location ~*  \.(jpg|jpeg|png|gif|ico|css|js)$ {
expires 365d;
log_not_found off;
}
```

But still getting the exact same result on page speed sites, so since I am running Varnish on port 80 I googled around and changed settings in **/etc/varnish/default.vcl** & in **/var/www/vhosts/example.com/httpdocs/var/default.vcl** to include and restarted all services

```
sub vcl_backend_response {
    if (bereq.url ~ "\.(png|gif|jpg|swf|css|js)$") {
    unset beresp.http.set-cookie;
    set beresp.http.cache-control = "max-age = 2592000";
  }
}
```

But interestingly there is no change at Google PageSpeed Insights, GTmetrix or Pingdom sites and all of them are still explicitly suggesting heavily to 'Leverage browser caching'. I even tried with different network connection/location thinking that there may be some issues with these websites but still the same result.

**Comment by TruthF** [comment]
May be we can get some help with this article?
http://www.atomictag.com/2015/04/05/force-cache-and-leverage-browser-caching-for-non-cachable-contents/

**Comment by miguelbalparda** [comment]
Have you checked https://github.com/nexcess/magento-turpentine/issues/1089 ?

**Comment by farazhkhan** [comment]
@miguelbalparda I did check https://github.com/nexcess/magento-turpentine/issues/1089 but they concluded with following

> Since my configuration is working as expected in Debian/Ubuntu, including the same Turpentine version, I consider this is a Varnish issue for all Red Hat flavors.

But, I am sure there must be some workaround would be for CentOS 7 with Varnish 4.0.3... anyone please? How and where can I add these values as suggested in http://www.atomictag.com/2015/04/05/force-cache-and-leverage-browser-caching-for-non-cachable-contents/ ?

**Comment by miguelbalparda** [comment]
@farazhkhan CentOS is basically Red Hat without the cost of support. That issue might be affecting you as well.

**Comment by farazhkhan** [comment]
@miguelbalparda Yes, correct. That's I wanted to know for workaround instead of downgrade by Varnish version.

**Comment by ADDISON74** [comment]
Even you will downgrade to 3.0.7 it won't help you at all. I don't know what is going on with CentOS/Apache 2.4/Varnish 4.x, but the packages from the repositories create trouble. Age 0 is the main problem I am struggling in CentOS for the moment and form keys in Admin (but this issue is present in Debian/Ubuntu too).

Off Topic: People make a mistake avoiding Debian which in my opinion is a solid piece of software with nice repositories. Mainly because cPanel is not working with it. After 10 years of Linux i will go for servers with Debian than CentOS. And I don't like systemd which is part of Red Hat's and Debian/Ubuntu (I am old school).

**Comment by TruthF** [comment]
@ADDISON74 @farazhkhan let's wait for new release of Varnish or update from CentOS...
On another note, can you please tell me that 'Ago 0' means no Varnish cache at all? or is it just for HTTP headers client side cache which actually causes "Leverage browser caching"?

**Comment by ADDISON74** [comment]
Varnish is already updated to 4.1. I am not advanced in Varnish parameters to configure a build from source. It is clear to me there is something different inside the code between Debian/Ubuntu version and Red Hat's version.

I am still investigating Age 0 issue. @aricwatson gave my a clue to investigate if it is a header issue or a caching one.

**Comment by TruthF** [comment]
@ADDISON74 @aricwatson thanks for this and will wait for the feedback from your end once your testing is completed.

**Comment by farazhkhan** [comment]
@ADDISON74 did you get chance to work on @aricwatson clue and managed to resolve this? even after Varnish 4.1.2 on CentOS 7.2 we are getting `Leverage browser caching` suggestion from all page speed sites.

**Comment by ADDISON74** [comment]
Maintainers of Varnish packages for Red Hat flavors much be contacted and report these issues which are not appearing on Debian flavors. I don't know if this issue will be solved or wait for new version, but something bad is happening in the package.

**Comment by farazhkhan** [comment]
@ADDISON74 Thanks, in testing environment I am going to install Debian 8.4 and see what happens. Will share my experience with you guys.

**Comment by ADDISON74** [comment]
Personally I feel more conformable using Debian 7.10 + Apache 2.2 + PHP 5.5 + Percona 5.6 + Varnish 4.0. I played yesterday with Debian 8.4 and it has Apache 2.4. You can use Php 7.0 from Dotdeb with a small change in Magento and Percona 5.7. In terms of speed it is a massive improvement. If you have problems with systemd configuration for Varnish check inside Turpentine issues how I configured it for Debian.

**Comment by farazhkhan** [comment]
@ADDISON74 

> If you have problems with systemd configuration for Varnish check inside Turpentine issues how I configured it for Debian.

Can you send me the link for the issues you are referring to?

**Comment by ADDISON74** [comment]
You can use search for systemd inside this forum. Here is what I found searching:

https://github.com/nexcess/magento-turpentine/issues/1086

**Comment by farazhkhan** [comment]
@TruthF @ADDISON74 @miguelbalparda @aricwatson 

After 9 months of this issue our versions have now changed as follows: 

> Magento ver. 1.9.2.4
> Varnish ver. 4.0.4
> CentOS Linux release 7.2.1511 (Core)
> Nexcessnet_Turpentine 	0.7.1 (stable)

But this issue 'Leverage browser caching with magento-turpentine installed' still remains? do you guys have any luck or is it still one of the issue?

**Comment by miguelbalparda** [comment]
What happens if you point the test to the non varnish port? Something like yourdomain.com:8080

**Comment by farazhkhan** [comment]
@miguelbalparda Yes, we have a test site on exact same server http://example.org:8081 bypasssing Varnish and if we try that with Google PageSpeed Insights, GTmetrix or Pingdom it seems to be fine.

It only happens when we browse our main website which is using Varnish ver. 4.0.4 with Turpentine 0.7.1.
