### ISSUE TITLE
SUPEE / backoffice for non admin users / _isAllowed

### ISSUE THREAD

**Issue by viansolutions-com** [nexcess/magento-turpentine#1141]
Hi there,
Can you provide the code fix in your controllers for this issue?
http://magento.stackexchange.com/questions/73646/access-denied-errors-after-installing-supee-6285

The concrete acl resource, I mean
I've tried this

```
 	protected function _isAllowed()
 	{
	    return Mage::getSingleton('admin/session')->isAllowed('system/turpentine');
 	}
```

And this

```
 	protected function _isAllowed()
 	{
            return Mage::getSingleton('admin/session')->isAllowed('system/cache');
 	}
```

But flushing concrete URLs gives blank page

**Comment by miguelbalparda** [comment]
@viansolutions-com I don't understand what do you mean. Would you mind adding more details?

**Comment by viansolutions-com** [comment]
After applying SUPEE-6285 all admin controllers need to implement _isAllowed() method

If not, backoffice users with role different than administrator won't have access to any module, even if they have checked the permissions for modules in the role config, (as explained in the link http://magento.stackexchange.com/questions/73646/access-denied-errors-after-installing-supee-6285)

**Comment by miguelbalparda** [comment]
Did you actually had this issue with Turpentine?

**Comment by viansolutions-com** [comment]
Yes, Turpentine is one of the affected modules

I have checked the most recent version of your controllers here, to see if they have been updated, but it's not the case

**Comment by miguelbalparda** [comment]
Weird since the patch was released on 7 jul. 2015 and we didn't have any reports of this issue so far but yours. I'll check and get back to you if we find something.

**Comment by viansolutions-com** [comment]
The fast solution is just adding 

```
protected function _isAllowed()
{
    return true;
}
```

But I've come here, searching for the concrete acl fix

I understand it's rare to have a non administrator user having access to varnish features in backoffice. But it could happen

**Comment by miguelbalparda** [comment]
Have you seen [this](https://github.com/nexcess/magento-turpentine/blob/master/app/code/community/Nexcessnet/Turpentine/controllers/Varnish/ManagementController.php#L250)? If I understand correctly, this is what you were looking for.

**Comment by viansolutions-com** [comment]
Oh my... I was checking for it at the top of the class
My apologies

**Comment by miguelbalparda** [comment]
I suggest you checking your error and exception log, there you will probably find the cause of your BSOD.

**Comment by viansolutions-com** [comment]
Well... In fact, a fix is needed
The correct acl resource is this

`return Mage::getSingleton('admin/session')->isAllowed('system/cache');`

**Comment by miguelbalparda** [comment]
That will actually depend. We are checking if you have access to Turpentine and not to the system cache. This means you can only use actions within the Turpentine controller if you have access to Turpentine. Since this is a part of Turpentine, I think this is the correct permission to check because if we were checking for cache, anyone without access to Turpentine will still be able to use actions from Turpentine's controllers.
