### ISSUE TITLE
Cache warming page/user cache

### ISSUE THREAD

**Issue by sr972** [nexcess/magento-turpentine#1142]
Hi,

this is just a question regarding an old issue/question https://github.com/nexcess/magento-turpentine/issues/120

There was following scenario called:
Page A (Pa), Page B (Pb), Visitor A (Va) and Visitor B (Vb) in a clean, non-warmed up env.

In my case:
Pa was a "user" in Google Chrome, incognito mode, Pb was a "user" in Firefox, incognito mode.
In the backend in Turpentine -> Caching Options i activated "Normalize Encoding" and "Normalize User-Agent".

If Va visits Pa it's "slow", if Va visits Pa again it's "fast", if Va visits Pb its "medium" as user content is in Varnish but the page itself not. That's ok to me, as i understand.

If Vb visits Pa it's not that slow, because Pa itself is stored in Varnish but hole punching for Vb is needed. Thats ok for understandings too.

Now is the case were Vb should hit a fast page load on Pb, as Pb is in Varnish and Vb's blocks too. Ok for my understandings too. But this is not the case in my scenarios. So i'm done with my understandings.

I always experiencing a load of ~450ms for the "main" document URL in any case / combination until the 2nd (or even the 3rd) reload of the page, where it then goes down to a 15-45ms on the main document.

It looks like, that the page and/or user blocks are not cached the proper way or the ESI isn't handled the correct way.

Is there a way to get any kind of output what is cached by varnish? Like page content, user content and so on? Like turning on pathnames / blocknames in Magento backend?
As i turned on Normalize Encoding/User-Agent, Chrome and FF agents shouldn't be a problem too.

**Comment by aricwatson** [comment]
Varnish has a number of tools you can to to try to track down what's happening in these sorts of scenarios. [varnishhist](https://www.varnish-cache.org/docs/trunk/reference/varnishhist.html) will give you a nice graph showing cache hits/misses in realtime. [varnishstat](https://www.varnish-cache.org/docs/trunk/reference/varnishstat.html) will give you a *ton* of info about what's happening in Varnish. Finally, [varnishlog](https://www.varnish-cache.org/docs/3.0/reference/varnishlog.html) also gives you a lot of information about what's happening in each request. Each of these tools is complex and can be used in many ways.

Also, it can never hurt to be absolutely sure you know whether a request getting passed through Varnish, and when ESI blocks are being inserted, etc. - check out our [troubleshooting guide](https://github.com/nexcess/magento-turpentine/wiki/Debugging-Varnish#how-do-i-know-if-varnish-is-working)

**Comment by sr972** [comment]
The tools you suggested are ok, but didn't solve my "problems" at all. I need more debuging. If i find a good way, i'll answer myself or try to get a wiki page right into place.

**Comment by aricwatson** [comment]
Let us know what you find out or if you have more questions!
