### ISSUE TITLE
Removed all traces of Turpentine, still getting Mage registry key "_singleton/turpentine/observer_esi" already exists

### ISSUE THREAD

**Issue by pepijnblom** [nexcess/magento-turpentine#1147]
Hi, we've been having this problem with a client who had Turpentine installed by a previous developer but it was never used.

We cleared up any traces of the module, I've done greps for turpentine and observer_esi and parts of those words. I also scanned the database with phpMyAdmin for anything related to those words but still we are getting this error once in a while..

Any ideas where this could still be hidden?

**Comment by miguelbalparda** [comment]
Have you flushed your Magento cache and any other type of cache?

**Comment by pepijnblom** [comment]
Heah I've cleared redis cache, searched for cache dir in var/ and even in /tmp and deleted where necessary.. Also restarted HHVM..
