### ISSUE TITLE
Varnish user agent normalization issue

### ISSUE THREAD

**Issue by zvezdovs** [nexcess/magento-turpentine#1148]
Hi!
I'm currently running Magento 1.7 with Varnish Turpentine.

I have noticed a strange behavior on cached content - Varnish returns same content for mobile and tablet(iPad), although in Magento back-end I have set design exceptions for matched expressions (iPad should use default, mobiles use mobi) and it works like a charm until varnish default.vcl is applied.

After checking around I found out that Turpentine use device detection and normalizes user-agent as per following:

```
if (req.http.User-Agent ~ "iP(?:hone|ad|od)|BlackBerry|Palm|Googlebot-Mobile|Mobile|mobile|mobi|Windows Mobile|Safari Mobile|Android|Opera (?:Mini|Mobi)") {
set req.http.X-Normalized-User-Agent = "mobile";
```
Well, fair enough... clearly mobiles and tablets will return same cache hit as both are normalized as mobile ... lets separate iPad I though

```
if (req.http.User-Agent ~ "iP(?:hone|od)|BlackBerry|Palm|Googlebot-Mobile|Mobile|mobile|mobi|Windows Mobile|Safari Mobile|Android|Opera (?:Mini|Mobi)") {
set req.http.X-Normalized-User-Agent = "mobile";
else if (req.http.User-Agent ~ "iPad") {
set req.http.X-Normalized-User-Agent = "ipad";
```
A big surprise after this change was that varnish still returns same cached content.

I have tried to use different varnish device-detects but all unfortunately failed.

Have anybody has a smallest clue what could be the issue?

**Edit**
Worth mentioning that I did apply new config on running varnish instance. I also did restart varnish on server side and apply config on running instance aftwerwards - both ways issue was still there.

**Comment by aricwatson** [comment]
In case others are following this issue, we've been talking about the problem over on stackexchange - more details [there](http://magento.stackexchange.com/questions/108774/magento-varnish-user-agent-issue)

**Comment by data-digger** [comment]
The code you pasted has a missing closing brace "}" which leads me to believe that it's not an exact copy of generated VCL file or you indeed removed closing brace and Varnish simply refuses to apply VCL file due to syntax error.

Paste generated VCL file so we know what we're dealing with.

**Comment by aricwatson** [comment]
Closing for lack of feedback.
