### ISSUE TITLE
Error in Magento backend: Failed to save the VCL file: XCache: Cannot init

### ISSUE THREAD

**Issue by casekreative** [nexcess/magento-turpentine#1160]
Hi, we have installed succesfully Varnish and extension, but when trying to save vcl config, the following error occurs: 

> Failed to save the VCL file: XCache: Cannot init

The question is, were to solve this problem? 
Everything seems to be ok, we can download the file, default.vcl and apply, but when saving this error comes up. 
We did symlink the /etc/varnish/default.vcl to our magento /var/ directory. 

With kind regards, 

PW

Update: 
By saving and uploading the default.vcl file manually the error disappeared. 

> "VCL successfully applied to 127.0.0.1:6082" 

Then after: restarting varnish and enabling VARNISH cache, Caching is not working, no errors but not working... 

Website is http://kreativecases.com/stores

**Comment by aricwatson** [comment]
> Failed to save the VCL file: XCache: Cannot init

This sounds like an issue or conflict with XCache.

> Then after: restarting varnish and enabling VARNISH cache, Caching is not working, no errors but not working...

Are you sure when you restarted Varnish that it loaded the VCL file from Turpentine?

I checked the site and it does appear that Turpentine is running - the varnish bypass cookie is working as expected, for example.  I don't see any ESI going on, so you may need to adjust your caching policies in your theme's layout file.

**Comment by casekreative** [comment]
Hi, thanks for your support. Somehow, varnish stopt working after reboot. What to post here? We don't understand what is going on. 
What outputs do we have to post? 
Regards,

PW

**Comment by miguelbalparda** [comment]
You should ask your sysadmin about the Varnish issues you are having, I don't think your issue is related to Turpentine.

**Comment by casekreative** [comment]
http://www.clipular.com/c/6442120875868160.png?k=vN4sprWOj96OsBuPc_GQY-N5cOI
Nope, you're right.

**Comment by casekreative** [comment]
Ok, solved the issue, next it's working, saved, uploaded vcl, applied, cleared caches and restarted varnish and apache. Everything seems to fine. Are you referring to this: https://github.com/nexcess/magento-turpentine/wiki/ESI_Cache_Policy
?

**Comment by aricwatson** [comment]
I took a look at the site (http://kreativecases.com/stores/english/) and it looks like Turpentine and Varnish are set up (the bypass cookie works) - it doesn't appear that any ESI blocks are being set. Probably you'll at least want to set one up for your header block so that it can be cached privately.
