### ISSUE TITLE
Path `/` is never cached

### ISSUE THREAD

**Issue by witrin** [nexcess/magento-turpentine#1168]
Everything is working fine except the path `/` is never cached. I've tried to get help over [stackoverflow](http://stackoverflow.com/questions/36667901) without success; I also posted there the generated configuration for Varnish. When I add the path `/` to some regular expressions in the configuration file the caching works as expected in the frontend but it has side effects on the backend (see the comments on the linked post above).

**Comment by aricwatson** [comment]
FYI - I was able to replicate this on one of my test platforms, will hopefully have more on it soon.

**Comment by witrin** [comment]
@aricwatson Thanks\you very much! I'm looking forward to it! Unfortunately the first page is pretty important regarding this whole SEO crap... ^^

**Comment by witrin** [comment]
@aricwatson Any updates here? Or maybe some hints what this could cause?

**Comment by aricwatson** [comment]
@witrin Can you let us know a little about the environment/stack you're using?

**Comment by aricwatson** [comment]
@witrin I looked at this a bit more... In the SO post you said that this worked but now the backend isn't working correctly:

`(/|/media/|/skin/|/js/|/de/)(?:(?:index|litespeed)\.php/)`

I think the problem with that is that your addition makes *all* requests match... so if you're using that in the check for the admin area, then it'll cache the admin area, which certainly would cause problems.

What might work is if you make that change in the VCL here:

```
# check if the request is for part of magento
    if (req.url ~ "^(/media/|/skin/|/js/|/de/)(?:(?:index|litespeed)\.php/)?") {
```

Which is the initial check to see if something is a "part" of Magento - then do *not* make the change in this line:

```
        if (req.url ~ "^(/media/|/skin/|/js/|/de/)(?:(?:index|litespeed)\.php/)?administration") {
```

Which is where it pipes the request if it's a request of the magento backend.

**Comment by witrin** [comment]
@aricwatson I've tried it, but without changing the administration parts it wasn't working. You need to know that I've changed the admin URL. Which is an option of Magento and your extension obviously noticed that. But Magento always produces URL like `[...]/admin/administration` instead of `[...]/administration` exception for the login. so I replaced in all regular expression `/media` with `/|/media` and added to the administration URLs `(admin)?` before `administration`. Now it seems to work. But why does your extension doesn't generate the right configuration? Editing the generated file every time is not maintainable.

**Comment by miguelbalparda** [comment]
@witrin please remember this is an OSS project maintained by several developers around the globe. If you thin the module as a problem feel free to submit a PR with the additions you consider relevant.

**Comment by witrin** [comment]
@miguelbalparda Currently I'm involved in other OSS projects so I haven't the time to fix this bug. Anyway I've reported it, so you're welcome ;).
