### ISSUE TITLE
0 Items in Cart -- Add to Cart Caching Issues

### ISSUE THREAD

**Issue by kevincal** [nexcess/magento-turpentine#1170]
Been having an issue over last several months where intermittently people will be unable to add products to their cart.  It looks like it succeeds, but then "0 Items in Cart"

In investigating the source code I see:

```html

<form action="http://acme.com/.../form_key/qNl3BqQfseRMK3m6/" method="post" id="product_addtocart_form">

        <!--[ajaxpro_formkey_start]-->
<input name="form_key" type="hidden" value="XffVlyeVGcDJFObd">
<!--[ajaxpro_formkey_end]-->        
....
</form>
```

The form keys are different from the hidden field to the form.action.

So deep diving a little more into product->view.phtml

form.action relies on getSubmitURL() which renders the FORM_KEY this way:
```php
     array(Mage_Core_Model_Url::FORM_KEY => $this->_getSingletonModel('core/session')->getFormKey())
```

while inside view.phtml
```html
<?php echo $this->getBlockHtml('formkey') ?>
```
which calls:
frontend/base/default/template/core/formkey.phtml

```html
<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
```

So why would these two be fundamentally different? Is one being cached in Varnish or another layer?

I did see this when I was grepp'ing for "formkey"
```shell
app/code/community/Nexcessnet/Turpentine/Helper/Varnish.php
182:            'turpentine_varnish/miscellaneous/formkey_fixup_actions' );
```

What do you think?  Because it's a getBlockHtml then is it being cached? Can we exclude this?

**Comment by miguelbalparda** [comment]
Have you checked the documentation we have about AJAX and formKey issues and fixes? https://github.com/nexcess/magento-turpentine/wiki

**Comment by kevincal** [comment]
I replaced the following in the product's view.phtml
```php
<?php echo $this->getBlockHtml('formkey') ?>
```

with
```php
<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
```

To see if that gets rid of this issue completely -- Or would it be better to keep BlockHtml but add it to a whitelist somewhere regarding cache?

**Comment by miguelbalparda** [comment]
It should only be different if you set up a cache TTL policy for the formkey block. I suggest you to read the documentation and the open and closed issues to fully understand the module before trying to do any more changes in your code.

**Comment by aricwatson** [comment]
Closing for lack of feedback.
