### ISSUE TITLE
Managing errors in ESI

### ISSUE THREAD

**Issue by lucaslegoff** [nexcess/magento-turpentine#1174]
If, for whatever reason, I have an error happening on the backend when returning an ESI, by default, turpentine vcl does a deliver of the 500 error (in vcl_backend_response).
This produce a page with magento error page inside it (error page in the header for instance).

I couldn't find way to avoid this. I would like to return a complete error page instead of a punch hole page with error pages inside it.

I seems that Varnish treat ESI request independantly from the main request and there is no way to act on main request if an ESI failed.

Am I wrong ? 
Does anyone has a solution to this ?

I'm using Varnish 4 and turpentine 0.6.8

**Comment by aricwatson** [comment]
> I seems that Varnish treat ESI request independantly from the main request and there is no way to act on main request if an ESI failed.

Yes, the ESI request is a separate request and the results of that request are inserted into that spot on the main request.

There's probably a way to change this behavior in the VCL - i.e. if the response is a 500 do something differently. [This discussion](https://www.varnish-cache.org/forum/topic/980) is worth checking out.

**Comment by lucaslegoff** [comment]
Ok, thanks for the confirmation.
I will probably end up returning an empty string or just the word "error". But it is still not very clean for the end user.

To me, this is a major issue of using ESI. I might try a feature request on the varnish side.
