### ISSUE TITLE
Disable Cache for Specific Block

### ISSUE THREAD

**Issue by sprankhub** [nexcess/magento-turpentine#1176]
We use a countdown extension, which shows a days/hours/minutes/seconds countdown on the product page. Of course this block may not be cached at all, so that the time is always correct. I tried disabling the cache for this block via:

	
	<reference name="awcountdown.block">
		<action method="setEsiOptions">
			<params>
				<access>private</access>
				<ttl>0</ttl>
			</params>
		</action>
		<action method="setCacheLifetime">
			<s>null</s>
		</action>
	</reference>

But it is still cached and does not show the correct time. We move the block around directly before, but that should not matter I think:

	
	<reference name="product.info.extrahint">
		<action method="unsetChild">
			<name>product.info.extrahint.awcountdown.wrapper</name>
		</action>
	</reference>
	<reference name="product.info">
		<block type="page/html_wrapper" name="product.info.extrahint.awcountdown.wrapper">
			<action method="insert">
				<block>awcountdown.block</block>
			</action>
		</block>
	</reference>

Any idea why the block is still cached?

**Comment by miguelbalparda** [comment]
You might want to check http://fbrnc.net/blog/2015/06/cache-and-layout-xml-tricks, it seems using null in the XML is not the way to go.

**Comment by sprankhub** [comment]
Thanks! Will try that. But I am quite sure that it is not the default Magento caching which is the problem here. It is the Varnish cache which caches the block. And I guess the Varnish cache does not take this cache lifetime value into account, does it?

**Comment by miguelbalparda** [comment]
We use the TTL param inside the ESI call for cases like this usually, you can try the ESI decoder to see if the params are being added correctly.

**Comment by sprankhub** [comment]
I now changed it to the following, but the issue is still the same:

	
	<reference name="awcountdown.block">
		<action method="setEsiOptions">
			<params>
				<access>private</access>
				<ttl>0</ttl>
			</params>
		</action>
		
		
		<action method="setCacheLifetime"/>
	</reference>

I also asked the AheadWorks team for help, but if you have any more idea, I would be happy :)

Regarding the ESI decoder: What is the ESI URL?

**Comment by aricwatson** [comment]
@sprankhub If you turn on the Turpentine debug options in general configuration, you should see the ESI urls in html comments in the page source.

**Comment by sprankhub** [comment]
@aricwatson If I enable debugging, I do not even see a ESI URL for my block. I analysed it further and hope that you can help me with this information:

- I set the ESI options for the block `AW_Countdown_Block_Countdown`.
- This block uses the template `aw_countdown/blocks.phtml`.
- This template is a wrapper for the countdown and contains the call `echo $this->getCountdownHtml($countdown)`, which gets the actual countdown HTML.
- The `getCountdownHtml` method does the following:

        $timerHTML = $this->getLayout()->createBlock('awcountdown/timer')->toHtml();
        // processes $timerHTML and returns it

What we need to achieve is that the `awcountdown/timer` block is not cached. Because here, the actual days/hours/minutes/seconds are calculated. But this is an anonymous block. How can we achieve that?
I tried to set the ESI options in the constructor of `awcountdown/timer`, but this leads to a "ESI block not found" error message.

I would be VERY thankful for further help!

**Comment by aricwatson** [comment]
>  If I enable debugging, I do not even see a ESI URL for my block. 

If you look in the log file (and block debugging is turned on) you should see a bunch of messages as Turpentine considers each block and decides if it can/should insert an ESI block in its place. Are you getting any error messages there, or any other error messages?

I suspect even if you can get this working, you may not see as much performance as you'd like - because if that block will always bypass the cache, then the backend (Magento) will need to generate the html for that block each time it's needed, with all the overhead that entails. You may want to consider if this can be achieved via some sort of an Ajax call, or some other way that can be cached (i.e. cache the time that the counter counts down to - which presumably doesn't change too often, and use ajax to calculate/display this to the user based off that).

**Comment by sprankhub** [comment]
I did not look at the block debug stuff yet. I actually do not care about the performance that much in this case. This block can be re-generated on each page request. The most important thing is that the block is not cached at all.

How would I have to set the parameters in the case explained above, so that the block is not cached at all? The `awcountdown/countdown` block creates the `awcountdown/timer` block on the fly, so how would that work? My guess is that setting the ESI options on the `awcountdown/timer` block does not work, because it is an anonymous block and not in the initial layout XML.
But it should work to set the ESI options on the `awcountdown/countdown` block even though it generates another anonymous block on the fly, no?

Both options do not seem to work...

**Comment by sprankhub** [comment]
@aricwatson could you please have a look at my last answer? Sorry for bugging you again...

If there is any possibility of paid support or donations, please tell me...

**Comment by sprankhub** [comment]
No idea?

Is there any list of people who give (paid) support for Turpentine?

**Comment by aricwatson** [comment]
> But it should work to set the ESI options on the awcountdown/countdown block even though it generates another anonymous block on the fly, no?

Sorry for being slow, I've been traveling. If you're not seeing the HTML comments around the block indicating that it was inserted - then any ESI parameters you're setting are being ignored because the block is not being inserted ESI at all. So I think the first step is to try to get it to insert, then to tweak how it's cached (i.e. TTL 0).

Yesterday I put in a new PR that adds more information to the logs when Turpentine decides whether or not to do ESI for a particular block. Perhaps you can use that PR and turn on block logging and see what it tells you?

**Comment by sprankhub** [comment]
Thanks @aricwatson! For those following, the enhanced block logging can be found here https://github.com/nexcess/magento-turpentine/pull/1225/commits/959411d26124da9efd0be33db89c01b7861eac70.

I finally solved the issue. Turpentine relies on the possibility to set a custom template (`turpentine/ajax.phtml` or `turpentine/esi.phtml`). The block we wanted to be inserted via ESI (`AW_Countdown_Block_Countdown`) had a weird override of the method `getTemplate`:

    public function getTemplate()
    {
        if (null === $this->getData('template')) {
            $this->setData('template', $this->getDefaultTemplate());
        }
        return $this->getData('template');
    }

The `template` of a block is NOT stored in the data array of `Varien_Object`, but in a template attribute of `Mage_Core_Block_Template`. Hence, `$this->getData('template')` will return null and the default template will always be used. The only chance would be to set the template via `setData`, which (normally) does not make any sense. Now I overwrite the block and fix the method to respect the template:

    public function getTemplate()
    {
        // make sure to use getTemplate() and setTemplate()!
        // $this->getData('template') (as in the original implementation) will always return null
        // the template is NOT stored in the data array of Varien_Object - it is stored in the template attribute of
        // Mage_Core_Block_Template
        $template = parent::getTemplate();
        if (null === $template) {
            return $this->getDefaultTemplate();
        }
        return $template;
    }

I also wrote AheadWorks and asked them to fix their method.

And while we are at it, here is the layout XML needed, so that the countdown block is not cached at all:

	<catalog_product_view>
		<reference name="awcountdown.block">
			<action method="setEsiOptions">
				<params>
					<method>esi</method>
					<access>public</access>
					<scope>page</scope>
					<ttl>0</ttl>
					<only_cache_if>empty</only_cache_if>
					<registry_keys>
						
						<current_product/>
					</registry_keys>
				</params>
			</action>
			
			
			<action method="setCacheLifetime"/>
		</reference>
	</catalog_product_view>
