### ISSUE TITLE
"X-Varnish" header not found

### ISSUE THREAD

**Issue by icedoutbiz** [nexcess/magento-turpentine#1177]
Hello community,
I have configured the module as best as I can but there is not Cache Hit on the frontend. (X-Header is not found)
My provider sees caching results on the varnish server but the frontend still very slow.

http://www.urban-street-shop.com/

Any help is welcome.

Kind regards

**Comment by miguelbalparda** [comment]
Most of the headers are removed as you can see [here](https://github.com/nexcess/magento-turpentine/search?utf8=%E2%9C%93&q=X-Varnish).

**Comment by icedoutbiz** [comment]
Any idea how to reduce the waiting time? Or where to debug it?

 I did not have these long waiting time on a previos varnish module.

![image](https://cloud.githubusercontent.com/assets/19286652/15188628/f5c8f00a-17a6-11e6-96e1-64d30acacdbd.png)
