### ISSUE TITLE
about frontend cookies and session file, big question

### ISSUE THREAD

**Issue by 2007lf** [nexcess/magento-turpentine#1178]
There are some customers reflect product can't add to cart, and cannot log in, I did test, 
When I delete frontend cookies, then will be create new frontend cookies and session file, but now, I find question, frontend cookies always create, but sometimes session file cannot create, so, product can't add to cart, and cannot log in.

Hope you can read this, my English not good, I need help. Does anyone know how to solve this problem?

**Comment by miguelbalparda** [comment]
Have you checked the documentation and other issues for a problem like yours? It seems you might want to try the VCL fix.

**Comment by 2007lf** [comment]
I search long time used google, but nothing...

**Comment by 2007lf** [comment]
The problem solved.
The reason is that session file too many, but the linux file system has limit, looked the /var/log/message  has "EXT4-fs warning (device sda3): ext4_dx_add_entry: Directory index full!" warning.

so, It's not magento or varnish question. :)
