### ISSUE TITLE
Turpentine not working on Magento 1.9.2.1.

### ISSUE THREAD

**Issue by Insect2015** [nexcess/magento-turpentine#1187]
Hello Support,

When I have add the info from my provider like : 
Varnish version
Varnish server list
Varnish authentication key
Backend host
Backend port
Crawler ip’s: Remove localhost/127.0.0.1 from the crawler ip’s

what I do then cache management then I get an error like:
Download Varnish Config
Save Varnish Config
Apply Varnish Config

**ERROR**
`Warning: fsockopen(): unable to connect to varnish:6082 (Connection refused)  in /data/web/public/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php on line 323

#0 [internal function]: mageCoreErrorHandler(2, 'fsockopen(): un...', '/data/web/publi...', 323, Array)
#1 /data/web/public/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php(323): fsockopen('varnish', 6082, 111, 'Connection refu...', 5)
#2 /data/web/public/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php(267): Nexcessnet_Turpentine_Model_Varnish_Admin_Socket->_connect()
#3 /data/web/public/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php(34): Nexcessnet_Turpentine_Model_Varnish_Admin_Socket->getVersion()
#4 /data/web/public/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin.php(131): Nexcessnet_Turpentine_Model_Varnish_Configurator_Abstract::getFromSocket(Object(Nexcessnet_Turpentine_Model_Varnish_Admin_Socket))
#5 /data/web/public/app/code/community/Nexcessnet/Turpentine/controllers/Varnish/ManagementController.php(182): Nexcessnet_Turpentine_Model_Varnish_Admin->getConfigurator()
#6 /data/web/public/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Nexcessnet_Turpentine_Varnish_ManagementController->getConfigAction()
#7 /data/web/public/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('getConfig')
#8 /data/web/public/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#9 /data/web/public/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#10 /data/web/public/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#11 /data/web/public/index.php(83): Mage::run('dutch', 'store')
#12 {main}`

But when I trun on Varnish at the server I get the error from Chrome:
ERR_TOO_MANY_REDIRECTS

Thanks for the support!

**Comment by miguelbalparda** [comment]
This error "ERROR
`Warning: fsockopen(): unable to connect to varnish:6082 (Connection refused) in /data/web/public/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php on line 323" means Turpentine is not being able to communicate with Varnish. 

This can be because of a wrong port, host ip or secret key or even because everything is correct but the server you re using as the webserver is not being able to communicate with the Varnish server for another reason.

**Comment by Insect2015** [comment]
Hello @miguelbalparda  I have already fix it thanks for the reply on the ticket!

**Comment by miguelbalparda** [comment]
Nice! Can you add your resolution here for future comrades having this issue?

**Comment by Insect2015** [comment]
Hello @miguelbalparda 

I have remove the file server.rewrites j  web/nginx and make a file name public.rewrites

See also : https://support.hypernode.com/knowledgebase/redirect-all-http-traffic-to-https-in-nginx/
