### ISSUE TITLE
Store Auto Switcher 

### ISSUE THREAD

**Issue by Insect2015** [nexcess/magento-turpentine#1188]
Hello,

I using a store Auto Switcher extension but when I have trun on varnish it's not working also when I click on the flag it's no not switch to the correct store.

could someone show me how I can fix this? url shop: https://www.dumcobelgium.be/

**Comment by miguelbalparda** [comment]
We don't do support on sites and not all the extensions work out of the box with Turpentine. What have you tried so far to make it work? Have you checked the wiki and older issues?

**Comment by miguelbalparda** [comment]
@Insect2015 how did you fixed this?

**Comment by Insect2015** [comment]
Hello @miguelbalparda,

Whe ar now working on it I hoop it will be don for today and I will let you now!

**Comment by aricwatson** [comment]
Closing for lack of feedback.
