### ISSUE TITLE
10-15 sec intial load recurring randomly

### ISSUE THREAD

**Issue by m-overlund** [nexcess/magento-turpentine#1190]
Hi

I'm experiencing this issue, that sometimes it takes about 10-15 seconds (TTFB) before the page starts to load. If i set the varnish_bypass cookie, the issue doesn't seem to happen.

It happens when the local browser cache builds up. If i clean the browser cache it stops happening for a days time, but then starts occouring again.
That also means that if i change to a browser which i haven't visited the page with in a while, it won't happen before i've used the site for some time.

I've made a short screencast to show the issue:
http://screencast.com/t/nbRjBRu4Gi6h

the site is: https://www.haveglad.dk , and happens on all our Magento stores on this installation.

Our hosting company can't reproduce the issue - but it happens on several computers on several locations etc., after visiting the site for a longer period of time.

Any ideas what to check for?

**Comment by aricwatson** [comment]
Very strange. What version of Varnish?

>  If i set the varnish_bypass cookie, the issue doesn't seem to happen.

Then it sounds like some sort of occasionally occurring varnish issue - but then you'd expect that clearing your browser cache wouldn't help at all. You say it doesn't "seem" to happen - are you sure? You could wait until the slow down occurs again and restart Varnish on the server and see what happens.

You could also try reinstalling Varnish, or trying a different version of Varnish.

**Comment by m-overlund** [comment]
I use version 4.x.
I have been able to reproduce while varnish_bypass is enabled.

I've tried debugging with Aoe_profiler - and it seems to be related to:
CORE::create_object_of::Nexcessnet_Turpentine_Model_Core_Session > 
Mage_Core_Model_Session_Abstract_Varien::start/start

![profile-haveglad](https://cloud.githubusercontent.com/assets/504236/15849964/8db3c4a0-2c95-11e6-866c-4f6651afadf5.png)

**Comment by miguelbalparda** [comment]
@m-overlund if you experienced this while varnish_bypass was enabled I would recommend you to check your server setup instead of Turpentine. Usually when this happens there is something wrong with your setup and not with the module itself.

**Comment by m-overlund** [comment]
ahh okay - seemed like a module error to me.

I think we've solved the issue - it was a session storage (memcached) related error, which should be fixed now.

Thank you!
