### ISSUE TITLE
Turpentine Preventing Cookies From Generating

### ISSUE THREAD

**Issue by beckindesigns** [nexcess/magento-turpentine#1191]
Hello

I have the latest version of Turpentine installed on Magento 1.9.2.3.

We use Maxmind and Google location services to generate cookies. When someone lands on the homepage the first cookie is generated that contains their IP info and location. This part is working fine.

Then a dropdown appears asking them to confirm their location. Once confirmed, the dropdown disappears and a separate homepage banner is displayed based on their location. This is also when the second cookie is generated to prevent them from having to answer the question again in the near future. However, this cookie will not generate.

What can I do to allow (whitelist) this cookie generation from Magento?

**Comment by miguelbalparda** [comment]
How are you generating this cookie? IIRC the best way to do this with Turpentine is to generate the cookie in the frontend.

**Comment by beckindesigns** [comment]
It's being generated via a controller that was triggered by the user which then calls this function. The data variable contains their location information.

```
    /*
     * Create verified cookie
     */
    private function _setVerifiedCookie($data){
        //Generate New Cookie
        $cookieValue = base64_encode(serialize($data));
        $this->_getCookieModel()->set(self::VERIFIED_COOKIE, $cookieValue, 60*60*24*181);

        return;
    }
```

This is how it has always worked. I have no idea how to do it any other way b/c I am completely new to Varnish and Turpentine.

Any help with this would be awesome!

**Comment by beckindesigns** [comment]
I moved it from the model to the controller and it works fine now.
