### ISSUE TITLE
Finding Page Type within ESI Block (Edited Title)

### ISSUE THREAD

**Issue by novocast** [nexcess/magento-turpentine#1192]
Hi,

I'm attempting to always bypass the cache for an individual block and it still seems to be caching. Any advice would be appreciated. Here's what I have at present:

_module layout xml file_
```xml
<layout version="1.0.0">
    <default>
        <reference name="before_body_end">
            <block type="core/template" name="namespace_module_name" before="universalanalytics_sitewide" template="namespace/module_namename/tags.phtml">
            </block>
        </reference>
    </default>
</layout>
```

_local.xml_
```xml
<reference name="namespace_module_name">
    <action method="setEsiOptions">
        <params>
            <access>private</access>
            <ttl>0</ttl>
            <only_cache_if>empty</only_cache_if>
            <dummy_blocks>
        	<footer/>
            </dummy_blocks>
        </params>
    </action>
</reference>
```

Is there a combination to never cache, or always flush?

**Comment by novocast** [comment]
For some additional info. My debugging looks like this:
```json
2016-06-08T11:55:48+00:00 DEBUG (7): TURPENTINE: Matched router: default
2016-06-08T11:55:48+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: namespace_module_name
2016-06-08T11:55:48+00:00 DEBUG (7): TURPENTINE: Set Varnish cache flag header to: 0
2016-06-08T11:55:48+00:00 DEBUG (7): TURPENTINE: Set ESI flag header to: 0

```

**Comment by miguelbalparda** [comment]
You might want to check https://github.com/nexcess/magento-turpentine/issues/1176

**Comment by novocast** [comment]
Thanks, I'd checked that out earlier but no positive outcome was found.

I was doing a little bit more debugging after seeing those logs, and I think it is already skipping the cache, and the error may be due to the contents of my template. In some logic I am using: 
```php
Mage::app()->getFrontController()->getRequest()->getControllerName();
```
and
```php
Mage::app()->getFrontController()->getAction()->getFullActionName();
```

When I log the time it updates fine (and isn't cached), but these methods return the wrong information. Could it be that the way that the block is returned when injected, causes these values to be set incorrectly?

They return the correct information when Varnish is totally bypassed.

**Comment by novocast** [comment]
Like this issue: [#276](https://github.com/nexcess/magento-turpentine/issues/276)

**Comment by novocast** [comment]
As all the resources I've found state that the request object passed through is a Dummy I don't know if this is solvable.
Instead, I've reworked the module into javascript and grab data from the dom instead.

Not really a fix, but a workaround.

**Comment by aricwatson** [comment]
> I've reworked the module into javascript and grab data from the dom instead.

Maybe not ideal, but doing things like this client-side often works more smoothly with Varnish.
