### ISSUE TITLE
Unexpected response code from varnish: 500

### ISSUE THREAD

**Issue by slimshadyplace** [nexcess/magento-turpentine#1193]
Hi Github people,

When clicking on save settings at the back-end of Magento, it shows the following message:

```
ERROR DETERMINING VARNISH VERSION: GOT UNEXPECTED RESPONSE CODE FROM VARNISH: 500
FAILED TO APPLY THE VCL TO 127.0.0.1:6082: FAILED TO LOAD CONFIGURATOR
ERROR DETERMINING VARNISH VERSION: GOT UNEXPECTED RESPONSE CODE FROM VARNISH: 500
FAILED TO LOAD CONFIGURATOR
```

Error also shows when clicking apply, save or download on cache management page of Magento. All caches are enabled except Magento's own BLOCK_HTML.

My back-end settings are:
Backend Host 127.0.0.1
Backend Port 8080

Varnish Version 4.x	
Server List 127.0.0.1:6082
Varnish Authentication Key xxx (copied contents from the secret file to here)
Config File Location {{root_dir}}/var/default.vcl
Custom VCL File Location {{root_dir}}/app/code/community/Nexcessnet/Turpentine/misc/custom_include.vcl

_(checked folders, there's no custom_include.vcl or a default.vcl)_

on server side (CentOS) i changed httpd/apache listen port to 8080 and in varnish settings file VARNISH_LISTEN_PORT=80 and added the following to DEAMON_OPTS:
             -p feature=+esi_disable_xml_check \
             -p cli_buffer=16384"

All the other stuff is kept as default. Does anyone know whats causing this 500 error? Am I missing something here?

Thanks,
Sebastiaan

**Comment by miguelbalparda** [comment]
Have you tried selecting the Varnish version manually and adding a \n at the end of the secret key?

**Comment by miguelbalparda** [comment]
You can also try to start the service manually using -f /path/to/default.vcl

**Comment by slimshadyplace** [comment]
Adding \n at the end of the secret key helped but now it shows 'VARNISH _FEATURE_ PARAM IS NOT SET CORRECTLY'

**Comment by slimshadyplace** [comment]
After adding "-p feature=+esi_ignore_other_elements" to DEAMON_OPTS the last warning also disappeared. Thanks @miguelbalparda.
