### ISSUE TITLE
Caching for child blocks of cached parent block

### ISSUE THREAD

**Issue by beckindesigns** [nexcess/magento-turpentine#1196]
I have a block that is inside the header which is being cached that I want to set a ttl of 60 seconds for b/c it is a timer. However, it doesn't work.

This is what I have:
```
{{block type="core/template" name="countdown" template="countdown/countdown.phtml"}}

        <reference name="countdown">
            <action method="setEsiOptions">
                <params>
                    <access>public</access>
                    <disableEsiInjection>1</disableEsiInjection>
                    <ttl>60</ttl>
                </params>
            </action>
        </reference>
```

**Comment by aricwatson** [comment]
You have `<disableEsiInjection>1</disableEsiInjection>` set - which means no ESI tag is being generated for the block - so you TTL value isn't doing anything.
