### ISSUE TITLE
Good practices for private ESI blocks

### ISSUE THREAD

**Issue by viansolutions-com** [nexcess/magento-turpentine#1198]
After reading https://github.com/nexcess/magento-turpentine/wiki/ESI_Cache_Policy I have some doubts about certain parameters combinations. For **scope** parameter, doc here says:

> global : one version of the block is stored for the entire site

First question, as this parameter is not commonly used in default defined blocks... what's the default parameter value? "page" or "global"?

Next, combined with **private** access...
Does it mean 1 single copy of block html will be stored per site & user? Or it will be stored 1 per site & all users?

I am fighting with a GTM integration, and I am not sure if I am doing things properly
I am defining all private blocks for users (containing checkout data) this way

`<action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <scope>global</scope>
                    <flush_events>
                        <sales_quote_save_after/>
                    </flush_events>
                </params>
            </action>`

As I need to have lot of blocks like that, due to some tracking & layout design, I've tried setting scope to **global**, as it seems the right approach (this block should be accessed once per user in the whole site, unless there are some checkout changes), but I am afraid something is not ok, as server load is kindly higher than it was before the changes applied today

Any tips?

**Comment by aricwatson** [comment]
> What's the default parameter value? "page" or "global"?

It is global

> Next, combined with private access...
Does it mean 1 single copy of block html will be stored per site & user? Or it will be stored 1 per site & all users?

If you combine "global" with "private" - you should be seeing *one* cached block of html, *per user*. For example, on the demo site the header block is cached this way, each user has their own cached version of the header which is inserted on each page for them.

> but I am afraid something is not ok, as server load is kindly higher than it was before the changes applied today

Probably the first thing is to verify that these are blocks are getting inserted via ESI. Do you have any idea what your Varnish hit rate is? Perhaps there's something going wrong and the ESI blocks are getting cached, etc?

**Comment by viansolutions-com** [comment]
Thanks for the info
ESI blocks were working fine, problem with server load was another thing, but your response is valuable, to be sure we are doing things the right way with ESI blocks ;)
