### ISSUE TITLE
ESI data is not valid

### ISSUE THREAD

**Issue by npearson72** [nexcess/magento-turpentine#1199]
Not sure what's going on, but I recently started getting the problem where my header is missing and in place of it appears: "ESI data is not valid"

I've been developing locally within a VM and have not seen this issue before, but today I needed to reinstall OSX and so I had to rebuild my local dev environment. I cloned all my code from github and got things running as per usual only to notice that I'm getting this error. It's strange because just everything was working fine.

What's odd is that if I visit a page directly, it loads fine:

http://bit.ly/1XIGyHY

But when I refresh it (or when I navigate to other pages) I get the error:

http://bit.ly/1XIGbx7

I'm also seeing a lot of this kind of thing in my apache logs:

```
127.0.0.100 - - [09/Jun/2016:19:14:21 +0000] "GET /turpentine/esi/getBlock/method/ajax/access/private/ttl/0/hmac/b613679a0814d9ec772f95d778c35fc5ff1697c493715653c6c712144292c5ad/ HTTP/1.0" 500 537 "https://trs.dev/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
```

Any ideas?

**Comment by aricwatson** [comment]
If you have debug turned on, you should see either `ESI data HMAC mismatch` or `Invalid ESI data in URL` messages in the system log - that might help us pin down the issue. 

Your apache error sounds like you're getting 500 errors from the ESI logs - do you have a php error log or something you can investigate?

**Comment by npearson72** [comment]
I just figured out the problem. I didn't properly set my magento crypt key in my local.xml file.

Sorry for hassling you guys. I'm closing the ticket now.

**Comment by Gendos-ua** [comment]
For the history: in my case it was uppercase to lowercase redirect in the .htaccess
