### ISSUE TITLE
Cookies not setting if frontend cookie exists

### ISSUE THREAD

**Issue by beckindesigns** [nexcess/magento-turpentine#1200]
This is a huge problem.

I am noticing that if the frontend cookie exists then any cookie I try to set after that will not set and be cached.

Example, I have a cookie that gets set on the homepage only. However, if a customer first visits a separate page and then decides to visit the homepage the custom cookie does not get set. I noticed the same issue if they land on the homepage and the frontend cookie already exists for them then my custom cookie will not get set.

If I clear the frontend cookie then the custom cookie gets set. Can you please explain why this is happening and how to overcome it? This will cause us to have to abandon our varnish/turpentine installation if it cannot be resolved.

A little about how it is being set. A widget is being loaded on the homepage with the following class.
class `Our_Module_Block_Banner extends Our_Module_Block_Cache implements Mage_Widget_Block_Interface`

This class contains the following:
```
	protected function _construct()
	{
		parent::_construct();
		$this->addData(array(
			'cache_lifetime'    => false,
			'cache_tags'        => array('our_module'),
                        'cache_key'      => $this->getCacheKey().'_1',
		));
	}

    protected function _toHtml() {
        $html = '';

        if(!Mage::helper('our_module')->getIsEnabled()){
            $html.= '<div style="text-align: center;"><div id="placeholder1">';
            $html.= $this->getLayout()->createBlock('cms/block')->setBlockId('home_slide_1')->toHtml();
            $html.= '</div></div>';

            return $html;
        }

       //If cookie exists than do nothing but store it for comparison
        if(Mage::helper('our_module')->getMaxMindCookie()){
            $result = Mage::helper('our_module')->getMaxMindCookie();
        } else {
            //Set the cookie if it doesn't exist
            $result = Mage::getModel('our_module/cookie')->setMaxMindCookie();
        }
    .........
    }
```

Finally, the model which will set the cookie.
```
class Our_Module_Model_Cookie extends Mage_Core_Model_Abstract {
    .........
    /*
     * Init cookie model
     */
    private function _getCookieModel(){
        return Mage::getModel('core/cookie');
    }

    public function setMaxMindCookie(){
    .........
        if(!Mage::helper('our_module')->getIsEnabled()){
            return;
        }
        $cookieName = self::MAX_MIND_COOKIE;
        $cookieCheck = $this->_getCookieModel()->get($cookieName);

        if (!$cookieCheck) {
            $result = $this->_setMaxMindCookie();
       }
    .........
    }

    /*
     * Create MaxMind Cookie
     */
    private function _setMaxMindCookie(){
    .........
        //Getting the result
        if (!empty($record) && $record->mostSpecificSubdivision->name && $record->country->name) {
            $userIsoLocation = $record->country->isoCode;
            $userCountryLocation = $record->country->name;
            $userStateLocation = $record->mostSpecificSubdivision->name;
            $userCityLocation = $record->city->name;
            $userZipLocation = $record->postal->code;

            $userData = array('iso_location' => $userIsoLocation,
                'country_location' => $userCountryLocation,
                'state_location' => $userStateLocation,
                'city_location' => $userCityLocation,
                'zip_location' => $userZipLocation
            );

            //Generate New Cookie
            $cookieValue = base64_encode(serialize($userData));
            $this->_getCookieModel()->set(self::MAX_MIND_COOKIE, $cookieValue, 60*60*24*180);

        }
    .........
        return $cookieValue;
    }
}
```

**Comment by miguelbalparda** [comment]
I suggest you checking open and closed issues about cookies, there are several issues posted with similar issues and solutions.

**Comment by miguelbalparda** [comment]
Anything on this issue @beckindesigns?

**Comment by aricwatson** [comment]
I suspect your code isn't getting run when the page is served from the cache, since it's server-side. I'd suggest using javascript to the set cookie, or to do an Ajax query to a php script to generate the cookie.

> If I clear the frontend cookie then the custom cookie gets set. Can you please explain why this is happening and how to overcome it? This will cause us to have to abandon our varnish/turpentine installation if it cannot be resolved.

If there's no frontend cookie, the request will be passed to Magento for a good session - and your code will get run. Otherwise, it's hitting the cached frontpage and your cookie-setting code isn't getting run.

**Comment by beckindesigns** [comment]
Thanks @aricwatson. I'll give this a try and report back. I suspect this will work though.

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
