### ISSUE TITLE
Can't get ESI block rule work for "top.links" block

### ISSUE THREAD

**Issue by junijo** [nexcess/magento-turpentine#1201]
Hi all!

I am fairly new to Turpentine, Varnish and Magento in general. I am having trouble with a particular block. Here is my page.xml from my theme:

    <block type="page/html" name="jmtoolbar" as="jmtoolbar" template="page/html/jmtoolbar.phtml">  
      <block type="page/template_links" name="top.links" as="topLinks"/>
      <block type="page/switch" name="store_language" as="store_language" template="page/switch/languages.phtml"/>
      <block type="directory/currency" name="custom_currency_selector" template="currency/currency.phtml"/>
      <block type="checkout/cart_sidebar" name="mycart" template="checkout/cart/sidebar2.phtml" before="-">
					<action method="addItemRender"><type>simple</type><block>checkout/cart_item_renderer</block><template>checkout/cart/sidebar/default.phtml</template></action>
					<action method="addItemRender"><type>grouped</type><block>checkout/cart_item_renderer_grouped</block><template>checkout/cart/sidebar/default.phtml</template></action>
					<action method="addItemRender"><type>configurable</type><block>checkout/cart_item_renderer_configurable</block><template>checkout/cart/sidebar/default.phtml</template></action>
					<block type="core/text_list" name="cart_sidebar.extra_actions" as="extra_actions" translate="label" module="checkout">
						<label>Shopping Cart Sidebar Extra Actions</label>
					</block>
      </block>
    </block>

It works, if I define an ESI block definition for jmtoolbar like this:

    <reference name="jmtoolbar">
            <action method="setEsiOptions">
                <params>
                    <method>esi</method>
                    <access>private</access>
                    <ttl>60</ttl>
                    <scope>page</scope>
                    <flush_events>
                        <checkout_cart_save_after/>
                        <sales_quote_save_after/>
                        <sales_quote_delete_after/>
                        <catalog_product_compare_add_product/>
                        <catalog_product_compare_remove_product/>
                        <catalog_product_compare_item_collection_clear/>
                        <wishlist_item_save_after/>
                        <wishlist_item_delete_after/>
                        <checkout_cart_product_add_after/>
                        <checkout_cart_update_items_after/>
                        <checkout_cart_product_update_after/>
                    </flush_events>
                </params>
            </action>
    </reference>

However, this block is actually too much. I only need the `top.links` block in the ESI definition. But this seems to not work. If I replace the  `<reference name="jmtoolbar">`with `<reference name="topLinks">` the block is not ESI-cached. It also did not do anything if I use the original name and not the alias `<reference name="top.links">`

So I am wondering if I miss something obvious? Anyone knows what it happening here?

Despite my current troubles, I wanted to take this opportunity and thank the developers of Turpentine for such a fine piece of software! Keep on the good work!

**Comment by aricwatson** [comment]
Thanks, glad it's helpful!

> However, this block is actually too much. I only need the top.links block in the ESI definition.

You mean you'd rather have a smaller part of the HTML hole-punched via ESI? You may be better off leaving the whole block hole-punched, since it looks like it includes `mycart` which presumably will also need to be hole-punched? 

But anyways, have you tried turning on the debugging options and looking in the log for mentions of the `top.links` block?

**Comment by aricwatson** [comment]
Closing for lack of feedback.
