### ISSUE TITLE
Cookie Set not working

### ISSUE THREAD

**Issue by Gamewalker** [nexcess/magento-turpentine#1202]
Hello,

sorry if this is already explained and I dont get it, I searched the issues and couldnt find something that would help me.

I am setting my cookie with 
`<?php Mage::getModel('core/cookie')->set('popup-shown2', 'true', 60*60*24*365);?>`

and its not there. Found out why but no solution to get my cookie working. Can someone please give me a hint?

greetings

**Comment by miguelbalparda** [comment]
Where are you trying to do this? My suggestion is to try to do it with javascript (it seems you are doing this from a phtml)

**Comment by Gamewalker** [comment]
yes its inside a phtml file

**Comment by Gamewalker** [comment]
ok its working fine with the JS solution, thanks :)
