### ISSUE TITLE
Inline-C not allowed - CentOs 7.2 / Varnish 4.1.2

### ISSUE THREAD

**Issue by MageSuper** [nexcess/magento-turpentine#1204]
Hello,

I'm trying to get varnish working, but there's two issues i do face at the moment, Inline-C which is not enabled, and Age" header is less than 1.

So, i really need help to get it fixed.

Please be very clear, as this my first time with varnish.

I read a lot of articles but yet, i still facing the same issue.

Thanks

**Comment by ADDISON74** [comment]
You won't make it. Search for issues on CentOS in this forum. I reported so many and tried to resolve them. You should avoid Varnish 4 in my option on 6 or 7. Unfortunately by default you will get version 4. The only OS which is dealing great with Varnish is Debian 7 and 8.

**Comment by MageSuper** [comment]
So, what do you suggest? should i downgrade? if so can you pass me the instructions?

Looking forward to hearing from you.

Sincerely,

**Comment by ADDISON74** [comment]
I am not a fan of Red Hat flavors, I was using them only for cPanel's, so I am not familiar how to avoid a version from being installed with yum but I guess if you search with Google you can find some clues. 

First run a test environment before taking a decision. In my case I installed many times Varnish 4.x in both CentOS 6 and 7 before taking a conclusion, it really has a problem from default repository. Going back in CentOS 6 I could install Varnish 3 from an old package and there were no issues with ESI policies or Age 0. For instructions you have to dig deep using Google. 

If you don't use cPanel, switch to Debian 7 or 8. Very solid versions with good packages. Or a Debian flavor in Ubuntu 14.04 or 16.04.

**Comment by ADDISON74** [comment]
inline-C you will solve it, just such inside this forum. but for Age zero I did not find a solution.

**Comment by miguelbalparda** [comment]
This seems to be a duplicated of https://github.com/nexcess/magento-turpentine/issues/948
