### ISSUE TITLE
Create a Log of All Commands Turpentine Sends to Varnish

### ISSUE THREAD

**Issue by clwells** [nexcess/magento-turpentine#1206]
It's often hard to see the interaction between Turpentine and Varnish. It'd be nice to have a single Turpentine log (that's properly rotated) that shows all interaction between Turpentine and Varnish.  Ideally this would live in Magento's 'var' directory.

**Comment by aricwatson** [comment]
Forgot to mention that I created a PR for this issue: https://github.com/nexcess/magento-turpentine/pull/1216
