### ISSUE TITLE
Allow For a 100% Custom VCL

### ISSUE THREAD

**Issue by clwells** [nexcess/magento-turpentine#1209]
Other issues have asked for beginning/end custom VCL code but for more advanced setups we really need to allow folks to provide a complete VCL that Turpentine will use if it exists.  Something as simple as:

app/code/community/Nexcessnet/Turpentine/misc/version-3-custom.vcl

Where if that file exists we simply use it (substituting in all of the Turpentine variables) and if it doesn't then we default back to the "normal" VCL given the Varnish version.  Yes, folks will need to hand migrate changes in future Turpentine versions but it will at least give them flexibility for now to do more advanced things in the VCL directly without worry that a Turpentine refresh will kill their changes.

**Comment by aricwatson** [comment]
I think we add a configuration field where the user can specify their own custom VCL template by simply entering its path. Then it would be parsed/etc same as the default template - but would be outside the module files and not vulnerable to overwriting by updates.

**Comment by clwells** [comment]
+1

**Comment by aricwatson** [comment]
OK, https://github.com/nexcess/magento-turpentine/pull/1212 - adds a custom VCL template option.
