### ISSUE TITLE
Cache product pages with and w/o taxes

### ISSUE THREAD

**Issue by sr972** [nexcess/magento-turpentine#1217]
I try to figure out how i could cache product und category pages showing the prices with and without tax including. The storeview code is present in the URL (e.g. /de/, /en/) the other parts are always the same. And the storeview code isn't a sign for showing or not showing the tax.

Background: The site itself is german based. So all prices should be shown including tax by default. But if someone e.g. from Hong Kong or Australia is visiting the site, the prices should be shown w/o the tax. If the e.g. the product page gets invalidated due to updates or varnish cache clearing / restart and the first hit comes from Hong Kong then others from Germany will see the net price.

There is no special customer group for foreign user. I already tried https://github.com/nexcess/magento-turpentine/issues/226 as "product.clone_prices" and so on are defaults in Magento and the used theme including it bunch of extensions doesn't seem to override it or rename it.

Any ideas?

**Comment by aricwatson** [comment]
> There is no special customer group for foreign user. 

This would be one thing to try - one group for German users, one for all others. Then you'll essentially have 2 sets of pages in the varnish cache, one for each customer group.

Another way would be via custom VCL - assign a custom cookie depending on the user's country, and then add that cookie's value to the hash in `vcl_hash`.

**Comment by sr972** [comment]
This is a great idea that i haven't mentioned yet. I'll give it a try in the next days and give a feedback. Thanks in advance!

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
