### ISSUE TITLE
VCL fix performance issues

### ISSUE THREAD

**Issue by npearson72** [nexcess/magento-turpentine#1218]
I just did a fresh install and test.. and am finding that with the VCL fix enabled, performance drops substantially.

http://bit.ly/29cqVnH

Is anyone else experiencing this?

**Comment by magenx** [comment]
VCL fix must be disabled, and also cookie regex configured just to be sure no sessions will be lost and no empty cart errors

**Comment by npearson72** [comment]
cookie regex? Where is that?

**Comment by magenx** [comment]
look in varnish settings next to `Normalization Options`

**Comment by npearson72** [comment]
This is what I have there:

http://bit.ly/29czqPN

What should be there?

**Comment by miguelbalparda** [comment]
If the user has no valid session then the first request is piped to obtain a -Magento session. That might explain this issue.

**Comment by npearson72** [comment]
That would explain why the first request is slow… but what about consequent
requests? I’m doing a load test and all the way through with VCL enabled my
performance is miserable. When I disable it, my performance is amazing.

I’m just not sure how to understand this other than a bug.

**Comment by miguelbalparda** [comment]
How are you testing this?

**Comment by npearson72** [comment]
Currently I’m using blazemeter.com, but the same issue is apparent when I
use siege.

**Comment by miguelbalparda** [comment]
Can you try setting a cookie? Something like `--header="Cookie: frontend=niu8v9qubdm1q0a17t7qb7dn82"`

**Comment by npearson72** [comment]
Where do I set this?

**Comment by miguelbalparda** [comment]
The one I wrote is for siege, idk how you set that in blazemeter.com

**Comment by npearson72** [comment]
Yes, that worked. What is that doing and how do I set that in my configs so
that it’s always passed in?

**Comment by miguelbalparda** [comment]
It's a testing method flaw, not a Turpentine one. This only simulates a valid Magento cookie.

**Comment by npearson72** [comment]
Well, not all agents are actual users. I’m concerned about Google crawling
my site. When I use PageSpeed Insights to test my scores, they always
complain about slow response times with the VCL fix.

**Comment by miguelbalparda** [comment]
Weird, https://github.com/nexcess/magento-turpentine/blob/6ffc75169f63f3fda7d2f1196b341e0db498064d/app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl#L173 but I still think the testing method is the culprit here and that is not what users actually see.

**Comment by aricwatson** [comment]
>  I’m concerned about Google crawling my site. 

By default, the google bot's user agent should be added to the crawler user agents - can you verify this is the case and that it's working? If you browse the site with the google crawler user agent set, do you get cached pages?

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
