### ISSUE TITLE
ESI Processing not enabled

### ISSUE THREAD

**Issue by mdlonline** [nexcess/magento-turpentine#1219]
We have setup a few Magento sites with Turpentine and Varnish without any hassle. However with this site we are getting the notice "ESI Processing not enabled" instead of the footer block. Suggested solutions like clearing cache, reloading configuration, do not work. Is there another cause for this error to appear?

**Comment by gewaechshaus** [comment]
How does the runtime configuration of the varnish daemon look like? Are you running the -p option?

**Comment by mdlonline** [comment]
These are the daemon opts:

DAEMON_OPTS="-a :6081 \
             -p vcc_allow_inline_c=on \
             -p thread_pool_add_delay=2 \
             -p thread_pools=2 \
             -p thread_pool_min=25 \
             -p thread_pool_max=2000 \
             -p timeout_linger=50 \
             -p first_byte_timeout=300 \
             -p cli_buffer=65536 \
             -p syslog_cli_traffic=off \
             -p workspace_backend=64k \
             -p feature=+esi_disable_xml_check,+esi_ignore_other_elements \
             -T 127.0.0.1:6082 \
             -u varnish -g varnish \
             -f /etc/varnish/default.vcl \
             -S /etc/varnish/secret \
             -s malloc,659m"

**Comment by magenx** [comment]
check for php errors or change block content to simple `echo`

**Comment by mdlonline** [comment]
Solved, removed block from ESI and it mysteriously solved the problem. Thanks
