### ISSUE TITLE
Completely seperate Multiple Magento Sites on 1 server using 1 Varnish install

### ISSUE THREAD

**Issue by BenBish** [nexcess/magento-turpentine#122]
Hi I am looking to have multiple, completely separate, Magento sites running on one server using nginx. They are using different domain names.

I setup the first site fine and then got the caching working perfectly using your plugin. 

The second site is up and running with Turpentine installed in the same way but neither sites esi blocks now work. I am using the exact same Turpentine settings including the secret (I can add to the cart and when viewing the cart I can see the products, when I continue browsing the cart, recent products etc are blank).

So my question is, should this type of setup work or should I stop my config setting witch hunt now?

Thanks for a simply awesome plugin.

**Comment by pieterjanliekens** [comment]
For those thinkering with multiple backend configurations this method seem to solve it for me:

```
backend example1{
.host = "127.0.0.1";
.port = "81";
}

backend example2{
.host = "127.0.0.1";
.port = "82";
}

sub vcl_recv { if (std.port(server.ip) == 7081) {
set req.backend_hint = example1;
}
elsif (std.port(server.ip) == 7082) {
set req.backend_hint = example2;
}

if (req.http.host ~ "^(www\.)?example1\.com$") {
        set req.backend_hint = example1;
        return (pass);
}

if (req.http.host ~ "^(www\.)?example2\.com$") {
        set req.backend_hint = example2;
        return (pass);
}


```
You can tinker with pass / lookup in the return field.
