### ISSUE TITLE
IDEV Onestepcheckout login form

### ISSUE THREAD

**Issue by mdlonline** [nexcess/magento-turpentine#1220]
When having Varnish 4 enabled, and added the following urls to the blacklist:

cron.php
onestepcheckout
checkout
customer
onepage

The checkout is not getting cached so that works fine. However, the Ajax login form in the checkout does not work properly. It seems to strip the cookies, leaving me with an empty cart and still logged out. As this is a commonly used extension, does someone have a remedy for this?

**Comment by miguelbalparda** [comment]
Turpentine is not compatible with all the extensions out of the box. Have you contacted the extension developers to see if they can help you?

**Comment by gewaechshaus** [comment]
In every case or particular loose of the cart items?

**Comment by mdlonline** [comment]
I have contacted the Idev developers.
It's happening every time. If i disable varnish everything works fine. 
The same effect as if you would remove your frontend cookie manually.

**Comment by miguelbalparda** [comment]
What's the URL of the AJAX call?

**Comment by mdlonline** [comment]
this is the url:
onestepcheckout/ajax/login/

**Comment by gewaechshaus** [comment]
Related to https://github.com/nexcess/magento-turpentine/issues/1203

**Comment by aricwatson** [comment]
This may be a longshot but a similar problem seems to have been due to using redis - please [review](https://github.com/nexcess/magento-turpentine/issues/1156#issuecomment-228380072)

**Comment by miguelbalparda** [comment]
Closing for lack of feedback

**Comment by ToonSpinISAAC** [comment]
Hi @miguelbalparda, @iamlolz, @aricwatson and others,

I am having this issue as well, and have found the cause; in the version of Turpentine I am using, namely 0.7.1, [this](https://github.com/nexcess/magento-turpentine/blob/release-0.7.2/app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl#L130) is a `pass` statement instead of a `pipe` statement.

I'm going to upgrade now to see if that helps.

**Comment by iamlolz** [comment]
@ToonSpinISAAC  unfortunately I tried both `pipe` and `pass` and neither worked with the onestepcheckout extension I was using. I'm glad it worked for you, it was a major headache for me at the time.

**Comment by Nuranto** [comment]
I solved this kind of issue by replacing pass to pipe [here too](https://github.com/nexcess/magento-turpentine/blob/release-0.7.2/app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl#L211)

**Comment by iamlolz** [comment]
@Nuranto I long ago removed varnish/turpentine but your comment makes me consider giving it another go.
