### ISSUE TITLE
Some out-of-stock issues

### ISSUE THREAD

**Issue by gewaechshaus** [nexcess/magento-turpentine#1221]
Hey guys,

one thing we didn't noticed till one of our clients informed us about:
If one of the shop products get out of stock during the day, it is still available cause varnish delivers the cached version of the page. This can cause some serious issues...

I think we need some logic to handle this...?

**Comment by aricwatson** [comment]
Turpentine should automatically clear product pages from the cache when this happens - see [here](https://github.com/nexcess/magento-turpentine/blob/1236f2971511e52eea1c57e4192748b16d4986a0/app/code/community/Nexcessnet/Turpentine/Model/Observer/Ban.php#L112) - can you try debugging this? Maybe add a log item when it gets called to ensure that it's getting called appopriately?

**Comment by gewaechshaus** [comment]
Yes... To be honest I didn't took a closer look, otherwise I had to stumple upon this nice piece of work... Sorry for stealing your time, I will put some Mage::log into the method and keep you updated.

**Comment by gewaechshaus** [comment]
Everything is working fine... I think this issue is related to stock updates by another software which doesn't trigger the event cataloginventory_stock_item_save_after... **Can be closed!**

**Comment by aricwatson** [comment]
Good to hear!!
