### ISSUE TITLE
No response headers. Does it work at all?

### ISSUE THREAD

**Issue by vitazzz** [nexcess/magento-turpentine#1223]
I've installed and configured Turpentine. From backend it seems like everything works fine: I got all the "success" messages, the default.vcl file is created and symlinked, no error messages, nothing special in log etc. However when I enabled debug info I did not receive Varnish headers in browser. Also the page loading speed did not change at all and when I used command "varnishhist" I saw "1:1 n = 0". So it seems like something IS NOT right with it.

**Comment by aricwatson** [comment]
Yes, it sounds like there's a problem somewhere! There's a lot of things to check - perhaps first check the [debugging](https://github.com/nexcess/magento-turpentine/wiki/Debugging-Varnish) page on the wiki to make sure things are set up right.

**Comment by miguelbalparda** [comment]
Just in case, do you mean any of [these](https://github.com/nexcess/magento-turpentine/blob/master/app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl#L416) headers?

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
