### ISSUE TITLE
Not flushing header

### ISSUE THREAD

**Issue by tr33m4n** [nexcess/magento-turpentine#1227]
Hi there,

I have modified the header flush events in turpentine_esi.xml to the following:

```XML
<reference name="header">
        <action method="setEsiOptions">
            <params>
                <access>private</access>
                    <flush_events>
                        <wishlist_item_save_after/>
                        <wishlist_item_delete_after/>
                        <sales_quote_save_after/>
                        <customer_login/>
                        <customer_logout/>
                    </flush_events>
                </params>
            </action>
        </reference>
```

However the header is not being flushed on customer login/logout. I have also disabled caching in the header by using:

```XML
<reference name="header">
            <action method="unsetData"><key>cache_lifetime</key></action>
            <action method="unsetData"><key>cache_tags</key></action>
        
        </reference>
```

Any ideas?

Thanks

**Comment by aricwatson** [comment]
Hi - I have a PR (https://github.com/nexcess/magento-turpentine/pull/1216) which adds an option that will log all commands (including BANs) sent to varnish. Can you try that to see if customer login/logout is triggering the proper command to be sent?

> I have also disabled caching in the header by using:

Those settings will only affect Magento's built-in block caching, and won't directly affect Turpentine. I'd advise trying to get the flush event working before disabling caching on that block to improve performance.
