### ISSUE TITLE
Override IP for domain cache warmer

### ISSUE THREAD

**Issue by craigcarnell** [nexcess/magento-turpentine#1230]
Using the warm-cache.sh script you can get it to warm your domain:

e.g. www.somedomain.com

But say you have a load balancer at www.somedomain.com for 2 seperate servers on 2 different IPs

Your cache warming script will either 1st or 2nd server.

Ideally, you would be able to specify in the cache warming script the IP to use for www.somedomain.com, so you can run the cron script on both servers

**Comment by aricwatson** [comment]
We generally set up Varnish on each web node of a clustered environment, and then run the warmer script via cron script on each node. 

> Ideally, you would be able to specify in the cache warming script the IP to use for www.somedomain.com, so you can run the cron script on both servers

Worth considering! However, I think this would need to be done by editing the hosts file on the system running the script, so this might better done outside of Turpentine.
