### ISSUE TITLE
Does turpentine supports Varnish version 4.1.x?

### ISSUE THREAD

**Issue by diwakert** [nexcess/magento-turpentine#1231]
Not a issue exactly and apologies if answer to this question exists already. I am getting `Unrecognized Varnish version: 4.1 ` errors in admin panel?

**Comment by aricwatson** [comment]
Try manually setting the Varnish version to 4 in the Magento backend.

There have been reports of issues with 4.1 so test thoroughly!

**Comment by ADDISON74** [comment]
I recommend you staying with version 3.0.7 or 4.0.3. I did a lot of tests in CentOS, Debian and Ubuntu and version 4.1 is creating a lot of trouble. I waited about 8 months to see some issues solved by Varnish maintenance team but no luck for the moment.

**Comment by diwakert** [comment]
I was unaware of this non-compatibility and just downloaded the latest version of varnish. So far I've seen  one error on Magento that I am not able to delete products in the cart. It just stucks to a blank page and the product is still in cart with no traces of any errors in turpentine or magento logs.
Initially I had to change /etc/default/varnish settings to configure `cli_buffer` and `vcc_allow_inline_c`. After which I am getting no more backend complaints when saving VCL from cache management.

Any way, going to use version 4.0.3 as it is tried and tested.

Thank you all for your replies!
