### ISSUE TITLE
session problem

### ISSUE THREAD

**Issue by openmomo** [nexcess/magento-turpentine#1236]
Hi, I have noticed an incorrect behaviour in my site after adding a frontal server with pound + varnish to my nginx server.
First time you visite the site it works well and you can buy and browse all the content with no issues. But, if you had a previous session (re-visit the web next day or after few hours) you cant add anything to cart. You must clear browser cache or use private mode for letting it you buy anything. Clearing Magento cache, restarting Varnish or Pound does not help. Looks like a session "desync" between browser and site. Could be turpentine and varnish the ones to blame? I didnt notice this issue before intalling it.

We use a tracking system for remarketing and abandoned carts. This is how an OK or KO "add to cart" click looks like for Pound:

 GET /checkout/cart/add/uenc/aHR0cHM6Ly9zaW5ndWxhcnUuY29tL2pveWFzL2FuaWxsb3M,/product/24602/form_key/c7MZ4lqzEPDcU2dR/ HTTP/1.1 - HTTP/1.1 302 Moved Temporarily

Magento 1.9.1.0
Turpentine 0.7.0
CentOS7
Varnish 3
PHP 5.6.15

Thanks.

**Comment by miguelbalparda** [comment]
It's possible Varnish and/or Turpentine are the ones to blame, but chances are any other software (pound/nginx/Magento) is the culprit here. What have you tried to debug this issue so far?

**Comment by openmomo** [comment]
Just disabled config applied by turpentine VLC and now site is working fine with varnish with default config in bypass mode.

Take a look at this screenshot. If varnish config is applied, delivery address becomes totally random. I have created a test order with a new customer and there appeared data from another customer who registered on january 2016.

I also have blacklisted /checkout/onepage/

![checkout](https://cloud.githubusercontent.com/assets/20593042/17066123/e0294268-5045-11e6-9761-ee018868700d.jpg)

**Comment by gewaechshaus** [comment]
1. - Did you check all of your session related settings? 
http://php.net/manual/en/session.configuration.php
2. - Do you store sessions as files?
3. - Is your garbage collection working?
4. - Do you use pound for ssl termination?

**Comment by miguelbalparda** [comment]
@openmomo probably the cause of your issue is that the ESI policy for the block is set to public instead of private. This is not a plug and play extension, you need to explicitly set the way your blocks are cached.

**Comment by openmomo** [comment]
Thanks for your comments.

@gewaechshaus .
1- its OK
2- Yes
3- Yes
4- Yes
5- Yes, it works normally. I have left it in production like that.
6- No.
7- Not sure how to verify, but at least 1 block is being cached.

@miguelbalparda 

Im almost sure that is not a session problem at all. Varnish is caching some block at the one step checkout process. I thought it was a session issue because in my four previous installations of the module, blacklisting "/checkout/onepage/" seemed to work. Dont know why in this case blacklisting is not enough.

I have created custom ESI policies before for things like ajax minicart or megamenu, so this time looks like I need to hunt down the problematic block. If  get it to work ill post which one page module is in use and the related block.

**Comment by openmomo** [comment]
Now seems to work fine.

Changed to private few blocks with name ".progress" like "checkout.progress" or "billing.progress" in checkout.xml layout which load within checkout-progress-wrapper.

No clue why blacklisting /checkout/onepage does not work for this site, but at least seems solved.

OPC extension is from IWD.

Thanks again.

**Comment by pieterjanliekens** [comment]
Indeed. Agree that blacklisting these pages should resolve the issue.
Care to elaborate what code you added to which files?
