### ISSUE TITLE
Varnish bypass to magento

### ISSUE THREAD

**Issue by vinitchopra12** [nexcess/magento-turpentine#1239]
I have installed varnish 4.0 and applied the settings (default.vcl) generated by the module. But still every hits goes to Magento instance. 

Below is my setup
Load Balancer >> Varnish with Nginx >> Internal ELB >> Magento Instance (EC2) with Apache.

Please advise how can I fix this problem.

**Comment by miguelbalparda** [comment]
What have you tried so far to debug this? What makes you think this is related to varnish or turpentine?

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
