### ISSUE TITLE
Not displaying header on cart & checkout page.

### ISSUE THREAD

**Issue by vinitchopra12** [nexcess/magento-turpentine#1240]
I have an issue after varnish installed that the header of the website is gone esp. in cart and checkout page. Also order is not place, it shows 500 error in saveorder action after payment gateway select.

Please advise me asap.

Thanks

**Comment by miguelbalparda** [comment]
What have you tried so far to debug this? There are a few similar issues in the repo, have you checked those?

**Comment by vinitchopra12** [comment]
Somehow I have fixed the Checkout issue (500 Error) but the cart sidebar is still no fixed.  Its completed messed. I have added below code in my local.xml file

<reference name="cart_sidebar">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <flush_events>
                        <sales_quote_save_after/>
                    </flush_events>
                </params>
            </action>
        </reference>
