### ISSUE TITLE
Cache Hit and Miss

### ISSUE THREAD

**Issue by Tipnik** [nexcess/magento-turpentine#1241]
Hello
I've been trying to configure Magento + Turpentine with Varnish on Cloudways hosting and now I am out of ideas.
Everything seems to be configured right, but there are several problems.
1. First page is never cached
2. Product pages are cached, sometimes. Usually it's MISS HIT MISS HIT
I get only these headers
X-Cache HIT
X-Cache-Hits 1
3. I've tried different cookie domains and paths, still can't decide to use www.domain.com or domain.com. At least now I don't get double frontend cookies.
4. I used Auto-redirect to Base URL to point to www.domain.com because fonts were breaking on landing page.
5. Sometimes user isn't able to login, after submitting login form, site looks refreshed, nothing more.

Versions
Magento 1.9.2
Varnish 4.0.2
Turpentine 0.7.0 (updated from 0.6.7)
Cloudways is using Nginx, Apache, Memcached, Redis.

Logs from Magento or Turpentine show nothing rather interesting.

Do you have any ideas why this might be happening? I'll be happy to provide more informations if needed.

**Comment by aricwatson** [comment]
> 1. First page is never cached

This is the default behavior if you're using the "VCL fix" option. The first request will be passed through to Magento to get a valid session.

> Product pages are cached, sometimes. Usually it's MISS HIT MISS HIT

Have you tried some of the debugging suggestions [in the wiki](https://github.com/nexcess/magento-turpentine/wiki/Debugging-Varnish) - for example, are you seeing the HTML comments around ESI blocks in the page source? 

Are you using any other caching extensions?

**Comment by Tipnik** [comment]
Thanks for replying.
I know that the first request is sent to magento, but that's a different case.

Only cache types enabled are Varnish Pages and Varnish ESI Blocks. There shouldn't be any other caching extensions. I'm using Ultimo theme.

After enabling debug info I can see for example 
`
`
but headers stay the same
```
Age	0
Connection	keep-alive
Content-Encoding	gzip
Content-Type	text/html; charset=UTF-8
Date	Wed, 27 Jul 2016 06:48:39 GMT
Server	nginx
Transfer-Encoding	chunked
X-Cache	MISS
X-Frame-Options	SAMEORIGIN
X-Robots-Tag	noindex, nofollow
```

Here's also some requests from varnishlog
http://ctrlv.it/id/7130/544920025

**Comment by aricwatson** [comment]
In the varnishlog I see two requests for the same page - the second coming back with a cache miss. I'm wondering, does the third come back with a cache hit? 

You might want to try [this PR](https://github.com/nexcess/magento-turpentine/pull/1232) - it will add logging in varnishlog of each of the hash_data calls that are used to be build up the hash used to store/lookup the page in Varnish.  That'll help see if it's issue with matching the "hash buckets" with the requests.

**Comment by Tipnik** [comment]
I changed the file according to pr, but I didn't see any change.
http://ctrlv.it/id/7151/1294280444
I've tried logging in different place, clearing the cache, purging varnish (option in cPanel), restarting varnish, praying, save or apply vcl config ( what I can't really do because of "Varnish data to write over length limit", but support told me that's how it's suppose to be on cloudways).
Could I do something wrong? Or some other file is used?
And yes, usually third request is a hit.

**Comment by aricwatson** [comment]
> what I can't really do because of "Varnish data to write over length limit", but support told me that's how it's suppose to be on cloudways

Did they say why? This is usually resolved by changing the Varnish startup options. Otherwise, how are you sure that your config changes are being reflected in the VCL running on Varnish? The other option is to save the generated VCL somewhere, and tell Varnish to load it. The varnishlog you pasted indicates the changed VCL didn't get loaded...

> And yes, usually third request is a hit.

Interesting - if you continue reloading does it continue to be a hit?
