### ISSUE TITLE
ESI processing not enabled in footer

### ISSUE THREAD

**Issue by craigcarnell** [nexcess/magento-turpentine#1242]
Hi,

I routinely get this ESI processing not enabled in my footer. There never appear to be any logs.

I have added the Magento newsletter form to the footer.

**Comment by miguelbalparda** [comment]
Today we had a similar issue and we ended up fixing it by using the last answer [here](http://serverfault.com/a/535516/299841). Also check [this](http://magento.stackexchange.com/questions/126021/esi-processing-not-enabled-error-only-on-product-detail-page-varnish-and-magento/126029#126029) for some more context. Let me know if this worked!

**Comment by miguelbalparda** [comment]
The solution seems to be to add esi_disable_xml_check, "Don't check of body looks like XML", "Allow ESI processing on any kind of object"
and
esi_ignore_other_elements, "Ignore non-esi XML-elements","Allows syntax errors in the XML"
First link in my previous answer is for Varnish 3 and the other one is for Varnish 4

**Comment by craigcarnell** [comment]
@miguelbalparda Thank you 👍
