### ISSUE TITLE
Turpentine - Varnish Cache 

### ISSUE THREAD

**Issue by meenakus** [nexcess/magento-turpentine#1247]
Error determining Varnish version: Failed to connect to Varnish on [127.0.0.1:6082]: (111) Connection refused
Failed to apply the VCL to 127.0.0.1:6082: Failed to load configurator
Error determining Varnish version: Failed to connect to Varnish on [127.0.0.1:6082]: (111) Connection refused
Failed to load configurator

**Comment by miguelbalparda** [comment]
There are quite a few issues with the same title as this one, please use the search in the repo and read the documentation.
