### ISSUE TITLE
issue varnish cache installation 

### ISSUE THREAD

**Issue by meenakus** [nexcess/magento-turpentine#1251]
hi 
  i am installing  Turpentine - Varnish Cache in magento store 
  i don't have Varnish Authentication Key  and other setting i have done 
 but this error will be generate  when save the setting 

Error determining Varnish version: Failed to connect to Varnish on [127.0.0.1:6082]: (111) Connection refused
Failed to apply the VCL to 127.0.0.1:6082: Failed to load configurator
Error determining Varnish version: Failed to connect to Varnish on [127.0.0.1:6082]: (111) Connection refused
Failed to load configurator.

and also this 
/etc/sysconfig/varnish
/etc/varnish/default.vcl
etc/varnish/secret 
auto file is not generate our magento store after setting of varnish cache

**Comment by miguelbalparda** [comment]
@meenakus please stop opening issues. This is the 5th you open today with the exact same issue after I told you to check the documentation. Every problem you are having is explained in the documentation or other issues, please use the search bar, you can paste the exact message you are receiving and find the solution to your issue.

**Comment by meenakus** [comment]
i have check
