### ISSUE TITLE
install Turpentine - Varnish Cache 

### ISSUE THREAD

**Issue by meenakus** [nexcess/magento-turpentine#1255]
i want to install Turpentine - Varnish Cache extension but this issue  will be generate 
Error determining Varnish version: Varnish admin socket timeout
Failed to apply the VCL to 108.167.133.35:2082: Failed to load configurator
Error determining Varnish version: Varnish admin socket timeout
Failed to load configurator.
also i don't have Varnish Authentication Key how can get Varnish Authentication Key .
please slove my issue

**Comment by miguelbalparda** [comment]
This is a duplicated, please read the documentation and open and closed issues.

**Comment by meenakus** [comment]
but i have no any solution how can slove this issue

**Comment by miguelbalparda** [comment]
Reading the documentation, everything you are asking is explained there and in old issues with people with the same problem you are having.

**Comment by meenakus** [comment]
i have read all but documentation i can't get Varnish Authentication Key

**Comment by meenakus** [comment]
i have read all  documentation  but i can't get Varnish Authentication Key

**Comment by aricwatson** [comment]
The authentication secret is located in a file specified in the startup arguments or Varnish - [see here](https://www.varnish-cache.org/docs/3.0/reference/varnishadm.html). Usually it's located under `/etc`.
