### ISSUE TITLE
Header disappears when Turpentine is enabled

### ISSUE THREAD

**Issue by keebs** [nexcess/magento-turpentine#1257]
I'm new to configuring Varnish, so please be kind.

I'm running nginx 1.8.1 + varnish 3.0.7 + Magento 1.9.2.4 + turpentine 0.7.0
I installed turpentine, refreshed all my caches, and hit the homepage and the entire header disappears.

If I comment out the "<reference name="header">" section in the turpentine_esi.xml, and refresh the caches, the header returns. I suspect this problem is related to my hit ratio in varnishstat being less than 1%. Turpentine is definately installed fully. I can apply the varnish config from the admin successfully. as far as i can tell everything is configured correctly. I have no errors in system.log, exception.log, or turpentine.log. I'm guessing it has something to do with the way the template was written? Can anyone give me some direction on where to start looking? TY

**Comment by miguelbalparda** [comment]
There are quite a few issues like this one, can you search for those to see if any matches your problem? This is not a plug and play extension and it's not compatible out of the box with all themes.

**Comment by keebs** [comment]
I've been searching posts for 6 hours already. None of the existing posts seem to match my scenario. I've tried disabling all non-core extensions without any change...

**Comment by miguelbalparda** [comment]
Just to be sure, have you checked the closed issues? If yes, we might need some more info to debug this one.

**Comment by keebs** [comment]
The problem is with an extension > Tm_LiveSearch. If I disable the extension, the missing areas come back. I've tried disabling the esi injection on the <reference name="head"> which allows me to re-enable the extension, but the ajax search within the <reference name="top.search"> within the <reference name="head"> no longer works. Any ideas where to go from here? TY
