### ISSUE TITLE
after clearing cache and reindex also data in shipment search box is present 

### ISSUE THREAD

**Issue by ravichandrarv** [nexcess/magento-turpentine#1260]
<img width="874" alt="error" src="https://cloud.githubusercontent.com/assets/15813454/17624224/62885b14-60c1-11e6-9a08-731a0af09f58.png">

as you can see in image if you enter lots of data in search box it takes then it will hang after clearing cache and reindex also its not clear..........now how to clear about this.........??

**Comment by miguelbalparda** [comment]
@ravichandrarv can you add some more info? It seems you are using Magento 2 and this module only works in 1.x

**Comment by ravichandrarv** [comment]
yes let me explain you.

yes im using magento 2 and the issue is , in pic you can see that there is an search box in that box i pasted some content.
as you can see in pic now the problem is im unable to clear that data in search box and i cleared cache and reindex also done but data is still there..

**Comment by miguelbalparda** [comment]
Ok so this doesn't belong here. Maybe you are trying to contact Nexcess?

**Comment by ravichandrarv** [comment]
no was search in google about this issue because, i never faced this kind of issue and saw one post which is similar to this so posted my question also
