### ISSUE TITLE
Add to cart not working on first load

### ISSUE THREAD

**Issue by thepaleone** [nexcess/magento-turpentine#1267]
We're running in to the problem where you can't add a product to your cart until you've loaded the cart page at least once. I've read a bunch of different posts/threads/etc.. and can't seem to figure this out.  Some pertinent information:
- Magento v 1.9.1.0
- Turpentine v 0.7.0 (upgraded from 0.6.8)
- _VLC Tweak_ is enabled (although we tried without it to test, no difference)
- We've tried the fix from #1213 without luck.
- When we bring up the product page the first time, the formkey is **always** the same. As soon as we make it to the cart page once it changes to a new value for the rest of the session.

If there are any ideas or any information I can provide just let me know.

**Comment by miguelbalparda** [comment]
This is probably related to the way you are caching your product page and will depend heavily on your theme structure. You will need to explicitly set a hole punch for the form_key block and not have it cached with the rest of the page or even with the block containing the form_key block.

**Comment by thepaleone** [comment]
Thanks for the response Miguel. Is there a tool or guide that helps track down where to add a hole punch for something like this? I'm fairly new to working with Magento and I don't have much of a grasp yet on the theme system.

**Comment by miguelbalparda** [comment]
Wiki [here](https://github.com/nexcess/magento-turpentine/wiki).
