### ISSUE TITLE
Compatibility with Firecheckout

### ISSUE THREAD

**Issue by jorgb90** [nexcess/magento-turpentine#1268]
To make Varnish/Turpentine compatible with [Firecheckout](http://templates-master.com/magento-one-page-checkout.html) I have added the following in turpentine_esi.xml. It seems to work except that I still get a form_key error when I want to checkout.. Any idea how I can fix that? I can't add the path /firecheckout/ to the url blacklist unfortunately :(

`    <firecheckout_index_index>
        <turpentine_cache_flag value="0"/>
    </firecheckout_index_index>

```
<firecheckout_empty_layout>
    <turpentine_cache_flag value="0"/>
</firecheckout_empty_layout>

<firecheckout_col1-set>
    <turpentine_cache_flag value="0"/>
</firecheckout_col1-set>

<firecheckout_col2-set>
    <turpentine_cache_flag value="0"/>
</firecheckout_col2-set>

<firecheckout_col3-set>
    <turpentine_cache_flag value="0"/>
</firecheckout_col3-set>

<firecheckout_index_updatecheckout>
    <turpentine_cache_flag value="0"/>
</firecheckout_index_updatecheckout>

<firecheckout_index_saveorder>
    <turpentine_cache_flag value="0"/>
</firecheckout_index_saveorder>

<firecheckout_index_failure>
    <turpentine_cache_flag value="0"/>
</firecheckout_index_failure>

<firecheckout_replace_checkout_links>
    <turpentine_cache_flag value="0"/>
</firecheckout_replace_checkout_links>

<firecheckout_onecolumn_saveOrder>
    <turpentine_cache_flag value="0"/>
</firecheckout_onecolumn_saveOrder>`
```

Thanks!

**Comment by miguelbalparda** [comment]
Have you tried doing the same for the form_key checkout block? It's probably different than the form_key block in the product page. Also, interested to know why you can't add firecheckout to the blacklist.

**Comment by jorgb90** [comment]
How to find that block? It seems the extension includes it as a piece of javascript.

`<script type="text/javascript">
//<![CDATA[
        var checkout = new FireCheckout('firecheckout-form', {
        success         : 'https://www.yourmacstore.nl/checkout/onepage/success/',
        save            : 'https://www.yourmacstore.nl/firecheckout/index/saveOrder/form_key/hcCnGsf61Yl7LKSv/',
        billing_address : 'https://www.yourmacstore.nl/firecheckout/index/saveBilling/',
        shipping_address: 'https://www.yourmacstore.nl/firecheckout/index/saveShipping/',
        shipping_method : 'https://www.yourmacstore.nl/firecheckout/index/saveShippingMethod/',
        payment_method  : 'https://www.yourmacstore.nl/firecheckout/index/savePayment/',
        coupon          : 'https://www.yourmacstore.nl/firecheckout/index/saveCoupon/',
        giftcard        : 'https://www.yourmacstore.nl/firecheckout/index/saveGiftcard/',
        paymentdata     : 'https://www.yourmacstore.nl/firecheckout/index/savePaymentData/',
        presave         : 'https://www.yourmacstore.nl/firecheckout/index/preSaveOrder/',
        shopping_cart   : 'https://www.yourmacstore.nl/firecheckout/index/saveCart/',
        failure         : 'https://www.yourmacstore.nl/checkout/cart/'
    }`

I can't add it to the blacklist cause Cloudways doesn't allow me to change the VCL config. Hopefully they will add this feature soon!

**Comment by miguelbalparda** [comment]
You will have to ask Firecheckout about that, every extension/theme is different in their structure. I find it strange you can't change the VCL @wajidstack can you help here?

**Comment by jorgb90** [comment]
Ok thanks! Created a ticket on their website. When I have got the answer I will share it here.

**Comment by trideeindhoven** [comment]
Hi Jorgb90, i am struggling with exactly the same. Could you please share with me how you found the ESI block names (e.g. firecheckout_empty_layout). That would be great!

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
