### ISSUE TITLE
Varnish configuration in Magento website

### ISSUE THREAD

**Issue by anuragenvision** [nexcess/magento-turpentine#1269]
Hi Team,

I have install the Vanish extension successfully but not able to configure correctly.
After saving the setting in admin i am getting below error.
Error determining Varnish version: Failed to connect to Varnish on [127.0.0.1:6082]: (111) Connection refused
Failed to apply the VCL to 127.0.0.1:6082: Failed to load configurator
Error determining Varnish version: Failed to connect to Varnish on [127.0.0.1:6082]: (111) Connection refused
Failed to load configurator

Can you please look into this and help me out i am stuck.

Thanks in Advance!
![configuration-backend](https://cloud.githubusercontent.com/assets/21334211/18085484/f777b250-6ec8-11e6-998c-e618229cc30d.png)
![configuration -vanish2](https://cloud.githubusercontent.com/assets/21334211/18085485/f77fdffc-6ec8-11e6-9278-a01bc3c3d8d7.png)

**Comment by miguelbalparda** [comment]
Your valuefor the field Varnish Authentication Key is wrong, you should put the content of the file and not the path to it.

**Comment by anuragenvision** [comment]
Thanks for your quick response.

Where we can find the authentication key content ?

**Comment by miguelbalparda** [comment]
Inside the file you used as the value.

**Comment by anuragenvision** [comment]
I got this path from google search. I don't know where i can find this...

**Comment by miguelbalparda** [comment]
Via ssh inside your server, or ask your hosting provider for this.

**Comment by anuragenvision** [comment]
Okay sure let me ask to hosting provider, so this will resolve my problem right? or anything else we need to configure..

**Comment by anuragenvision** [comment]
Hosting provider said there is no file under this directory: /etc/varnish/secret/

**Comment by miguelbalparda** [comment]
The location will depend on your server/plan, you should ask them for Varnish secret key. Just to be sure, have you installed Varnish?

**Comment by anuragenvision** [comment]
Got the secret key and filled still getting error..
    Error determining Varnish version: Failed to connect to Varnish on [127.0.0.1:8080]: (111) Connection refused
    Failed to apply the VCL to 127.0.0.1:8080: Failed to load configurator
    Error determining Varnish version: Failed to connect to Varnish on [127.0.0.1:8080]: (111) Connection refused
    Failed to load configurator

Please help me out

**Comment by miguelbalparda** [comment]
Please take a look at the documentation in the [Wiki](https://github.com/nexcess/magento-turpentine/wiki), there are a number of causes for this error and some of them are using an incorrect host, port, the secret key without a \n at the end, etc.

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
