### ISSUE TITLE
Plain JS in ajax calls on safari browsers event

### ISSUE THREAD

**Issue by bjoern-flagbit** [nexcess/magento-turpentine#1270]
Hello guys,

in our fork from your great module, we changed that file:
https://github.com/nexcess/magento-turpentine/blob/master/app/design/frontend/base/default/template/turpentine/ajax.phtml#L53

from that
`if (typeof Ajax === 'object' && typeof Ajax.Updater === 'function' &&  (typeof Event === 'function' || typeof Event === 'object') ) {`

to this
`if (typeof Ajax === 'object' && typeof Ajax.Updater === 'function' 
                 && (typeof Event === 'function' || (typeof Event === 'object' && typeof Event.observe === 'function'))
             ) {`

we realized problems with the following browsers

> Mointain Lion 10.8.5 - Safari 6.2
> Mavericks - Safari 7.1
> Yosemite - Safari 8
> El Captian - Safari 9.1

the problem was that the js was not executed and posted plain to the browser.

Maybe you can update that in your module. 

thx and greetings from flagbit

**Comment by miguelbalparda** [comment]
Hey @bjoern-flagbit did you see the issues you mentioned before or after doing the changes you mentioned? If your fork fixes this, can you submit a pull request to the devel branch with your changes?

**Comment by bjoern-flagbit** [comment]
We see the problems before we did that change. After that it was working like expected.
And yes we can submit a pull request to devel branch no prob.

**Comment by miguelbalparda** [comment]
Thank you!!
