### ISSUE TITLE
Generating varnish config issue

### ISSUE THREAD

**Issue by vchackos** [nexcess/magento-turpentine#1272]
Hi,

I am implementing a server with a separate varnish server, and when ever I generate the cache rules, I am getting this error.  The turpentine generates the file two times and append to the var/default.vcl 

Has anyone had this issue before ? 

<img width="975" alt="screen shot 2016-09-01 at 12 18 47 am" src="https://cloud.githubusercontent.com/assets/12655296/18142104/b6a44b14-6fd9-11e6-9a95-a16b52c7b1ec.png">

Thanks!

**Comment by miguelbalparda** [comment]
What have you tried so far to debug this issue?

**Comment by miguelbalparda** [comment]
What happens if you remove the file and then reapply the rules? Is it generated only once?

**Comment by vchackos** [comment]
1. reinstalled turpentine
2. Redid varnish from 3.0 to 4.0 to 4.1 
3. Removed the var/default.vcl and regenerated thee code 
4. tried to dump the config to a different file, say default2.vcl 

all same. So I have to manually delete the extra entries and copy the file to the varnish server ( a different VM ) 

Thanks!

**Comment by miguelbalparda** [comment]
This doesn't seem to be related to varnish or Turpentine but to the way PHP is opening/writing to the file. We haven't seen anything line this before, so I suspect this has something to do with your server and not with the extension/Varnish.

**Comment by vchackos** [comment]
Thanks for that - I will contact the guy who set up the apache ( i really dont know why apache is being used :) )
