### ISSUE TITLE
Using nginx as SSL terminator

### ISSUE THREAD

**Issue by vchackos** [nexcess/magento-turpentine#1275]
Hey,

I have moved forward with the help of the community and the site works fine without SSL. 

When I install SSL, I am having an issue. 

HAPROXY  <-> Nginx <-> Varnish <-> Apache 

Haproxy forwards all requests to Nginx and Nginx takes it to Varnish. 

If I I take away Varnish, the site works fine.  If I put Varnish there, CSS is not loading, throwing a 502 error like the following. 

> 2016/09/07 04:55:15 [error] 15120#15120: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.169.2, server: test.xxxxx.com, request: "GET / HTTP/1.1", upstream: "http://172.19.169.42:80/", host:

<img width="582" alt="screen shot 2016-09-07 at 2 30 58 am" src="https://cloud.githubusercontent.com/assets/12655296/18290936/28135146-74a3-11e6-93ad-a5fc88a9568c.png">

If some one can throw a light on what could be wrong , it will be very helpful.

**Comment by vchackos** [comment]
Just to add, if I remove the tupentine rules and put the basic ones, it works fine. 

So it seem to be an issue with the haproxy sending some unwanted headers ?

**Comment by magenx** [comment]
why you need HAproxy? any needs in your environment?

**Comment by ADDISON74** [comment]
By default Varnish cannot deal with SSL. You have to put another service in front of Varnish to listen on both ports 80 and 443. If 443 to deal with all SSL stuff. In this way you will not use your webserver from now on doing SSL stuff.

Qualified for doing this job are HAProxy, Nginx and Pound. I am working with all three in different projects, personally I like HAProxy then Pound. With a good configuration HAProxy and Nginx could get for you an A+ in SSL Labs tests, Pound can get only A maximum if you installed normally from CentOS/Debian/Ubuntu repository then compile it from official 2.7 archive with configuration parameter dhparams=2048. Finally you have to replace both pound, poundctl files in /usr/sbin with the compiled ones (make a backup before). 

If you look for my Git name ADDISON 74 into Turpentine repository you will find a complete resource to get Pound working as SSL Offloader in front of Varnish in this configuration:

POUND (SERVER_IP, Ports: 80, 443) -> VARNISH (LOCALHOST, Port: 8090) -> APACHE (SERVER_IP, Port 8080). 

As you want to do in not OK HAProxy and Nginx  can do the same job load balancer and SSL Offloader. You can make that chain working as you want but it is resource consuming: HAProxy (load balancer) -> Nginx (SSL Offloader) -> Varnish (Cache server) -> Apache (Webserver). Pound can do HAProxy and Nginx jobs for only 400 KB of memory.
