### ISSUE TITLE
Customer/Account Page not working. for Multistore

### ISSUE THREAD

**Issue by magesh7j** [nexcess/magento-turpentine#1276]
I am using Multistore in same domain. like www.example.com/nl/nl www.example.com/in/en

Actually. There is No Problem in logging in in/en store. we can access the www.example.com/in/en/customer/account.

IN NL/NL store. Can i logging in successfully, but, i cant access the www.example.com/nl/nl/customer/account.. Talking more time to load, after loading getting sever misconfiguration error. please help me

**Comment by miguelbalparda** [comment]
@magesh7j have you checked the documentation?
