### ISSUE TITLE
Varnish data to write over length limit by 1821 characters Ubuntu 16.04 Varnish 4

### ISSUE THREAD

**Issue by andrey-borgoyakov** [nexcess/magento-turpentine#1277]
Hi all.
Failed to apply the VCL to 127.0.0.1:6082: Varnish data to write over length limit by 1821 characters
I had this problem in next env:
Ubuntu 16.04.1 x64 Server (DigitalOcean Droplet) (PHP 7, mysql 5.7, apache2.48)
varnish-4.1.1 revision 66bb824
Magento 1.9.2.4
Nexcessnet_Turpentine   0.7.0 (stable) 

I was read next:
https://github.com/nexcess/magento-turpentine/issues/114
https://github.com/nexcess/magento-turpentine/issues/136
https://github.com/nexcess/magento-turpentine/issues/267

but nothing helped me. I always get this error with constant characters value 1821.

My config
DAEMON_OPTS="-p cli_buffer=16384 \
             -a :80 \
             -T localhost:6082 \
             -f /etc/varnish/default.vcl \
             -u varnish -g varnish \
             -p esi_syntax=0x2 \
             -s file,/var/lib/varnish/varnish_storage.bin,1G \"

Help me please to determine what the problem?

**Comment by miguelbalparda** [comment]
So there are plenty of issues like this, you probably only saw the open ones. Check https://github.com/nexcess/magento-turpentine/issues/1063 and also [the search](https://github.com/nexcess/magento-turpentine/search?q=over+length+limit+by&type=Issues&utf8=%E2%9C%93) and let me know if you till have this issue.
