### ISSUE TITLE
Turpentine extension generates a buggy VCL config file

### ISSUE THREAD

**Issue by guvysaggu** [nexcess/magento-turpentine#1278]
We are facing an issue with Turpentine extn. Our serverside Varnish setup is correct but Turpentine extension generates a buggy VCL config file.

Our website is www.fashionplanet24.com

If you need anything, feel free to ask. I will appreciate your kind support.

**Comment by miguelbalparda** [comment]
What do you mean by buggy? Can you specify the issues you are having?

**Comment by guvysaggu** [comment]
We excluded our staging site URLs but it is still caching those URLs.

![varnish-cacheissue](https://cloud.githubusercontent.com/assets/2586343/18465252/7115375a-79b3-11e6-9280-aa8472a5a5cd.png)

Our staging URL: http://staging11.fashionplanet24.com/

sub vcl_recv {
       if (req.http.host !~ "(www\.)(fashionplanet24|domain2)\.(com|de)") {
               return (pipe);
       }
}

**Comment by guvysaggu** [comment]
Our varnish cache is not working properly.

**Comment by miguelbalparda** [comment]
@guvysaggu I'm not really sure what you mean. From your comments, I will suggest you to read the documentation first and then try to make this work in your site. The VCL you pasted here is not the one Turpentine generates.

**Comment by guvysaggu** [comment]
Thank you @miguelbalparda I go through the documentations as suggested.
