### ISSUE TITLE
[question] Cache by device

### ISSUE THREAD

**Issue by jlestel** [nexcess/magento-turpentine#1281]
Hello, 

I want to separate caches by device (desktop, mobile and tablets). 
Is it possible ? How can I implement this ?

Thx

**Comment by andreasemer** [comment]
This question has nothing to do with the Magento extension, but https://github.com/varnishcache/varnish-devicedetect or https://www.varnish-cache.org/docs/3.0/tutorial/devicedetection.html

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
