### ISSUE TITLE
Varnish - Error 403 External ESI requests are not allowed

### ISSUE THREAD

**Issue by mrk-i** [nexcess/magento-turpentine#1285]
Varnish 4.1.3
Turpentine Last version
I have 'ajax', 'Ajax' and 'add/uenc' in the URL blacklist.

Adding products to cart from category pages works fine when I visit page for the first time but it doesn't work anymore after I revisit or reload that page and I am getting:

HTTP/1.1 403 External ESI requests are not allowed

I guess that the reason behind the error is because the ajax call was cached in Varnish? But then why does it happen when I have these patterns in URL blacklist and what exactly does ' External ESI requests are not allowed' mean?

First time visit url (backend response):

http://96.126.119.231/checkout/cart/add/uenc/aHR0cDovLzk2LjEyNi4xMTkuMjMxOjgwODAvZ2l2ZS13ZWxsL3JlY2lwaWVudHMvZ2lmdHMtZm9yLW1vbQ,,/product/6230/form_key/EUUwvZjA9ohZF7Y4/

Reload or revisit (varnish respond):
http://96.126.119.231/checkout/cart/add/uenc/aHR0cDovLzk2LjEyNi4xMTkuMjMxOjgwODAvZ2l2ZS13ZWxsL3JlY2lwaWVudHMvZ2lmdHMtZm9yLW1vbQ,,/product/6230/form_key/%3Cesi:include%20src='http://96.126.119.231/turpentine/esi/getFormKey/ttl/259200/method/esi/scope/global/access/private/'%20/%3E/

Couldn't find any solution for this problem? Any suggestion? Thanks!

**Comment by mrk-i** [comment]
One more thing that I just noticed, I have the very same ajax request on product pages as well, all works fine from there. The difference is that on category pages ajax is sending a GET request when ajax from  product pages sends a post POST request. 

When I look into VCL, this is where the thing happens:

if (req.http.X-Varnish-Esi-Method == "esi" && req.esi_level == 0 &&
!(false || client.ip ~ debug_acl)) {
return (synth(403, "External ESI requests are not allowed"));
}

X-Varnish-Esi-Method is set to 'esi' for the ajax GET request on the other hand it's not set for the POST request...would it mean that switching ajax to GET would fix this issue? Post request shouldn't be cached from the logical point of view. Both pages are served from cache.

**Comment by mrk-i** [comment]
Adding:
`checkout\/cart\/add\/uenc`
to blacklisted urls didn't help :(

**Comment by jeroenvermeulen** [comment]
I may experience this bug too, still investigating.

**Comment by miguelbalparda** [comment]
@mrk-i are you still experiencing this issue? If not, how did you solved it?
