### ISSUE TITLE
Erreur page cache

### ISSUE THREAD

**Issue by magegirl** [nexcess/magento-turpentine#1286]
Bonjour,
J'ai le module Nexcess_Turpentine. Et depuis hier j'ai ajouté le module BL_CustomGrid sauf que j'ai cette erreur quand je vais en bo dans la gestion du cache : 
 Fatal error: Call to a member function setSaveParametersInSession() on boolean in /app/code/core/Mage/Adminhtml/Block/Widget/Grid/Container.php on line 66

Et dans exception.log j'ai : 
exception 'Mage_Core_Exception' with message 'Type de bloc non valide : BL_CustomGrid_Block_Rewrite_Nexcessnet_Turpentine_Block_Adminhtml_Cache_Grid' in app/Mage.php:595
Stack trace:
#0 app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Type de bloc no...')
#1 app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('adminhtml/cache...', Array)
#2 app/code/core/Mage/Adminhtml/Block/Widget/Grid/Container.php(66): Mage_Core_Model_Layout->createBlock('adminhtml/cache...', 'cache.grid')
#3 app/code/core/Mage/Core/Block/Abstract.php(293): Mage_Adminhtml_Block_Widget_Grid_Container->_prepareLayout()
#4 app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))
#5 app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('adminhtml/cache', 'cache')
#6 app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('adminhtml/cache', 'cache')
#7 app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#8 app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#9 app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#10 app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#11 app/code/core/Mage/Adminhtml/Controller/Action.php(275): Mage_Core_Controller_Varien_Action->loadLayout(NULL, true, true)
#12 app/code/core/Mage/Adminhtml/controllers/CacheController.php(46): Mage_Adminhtml_Controller_Action->loadLayout()
#13 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_CacheController->indexAction()
#14 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#15 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#16 app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#17 app/Mage.php(684): Mage_Core_Model_App->run(Array)
#18 index.php(67): Mage::run('', 'store')
#19 {main}

Je suis obligé de vider le cache en console mais le bug revient dès la 2ème consultation.
j'ai essayé de désactivé turpentine et je n'ai pas l'erreur.
Une collègue m'a dit qu'il doit y avoir un bloc mal définit mais je ne trouve pas comme corriger ce problème.

**Comment by miguelbalparda** [comment]
Are you sure this is related to Turpentine? I used Google Translate for this since I don't speak french, but since this is something happening in the admin, Turpentine will pipe all the requests. Also there are cases where the extension is using an incorrect approach to override admin paths and that can cause this type of issues.

**Comment by magegirl** [comment]
Yes maybe ! this module (bl_customgrid) "override" by event. Maybe it's for that

**Comment by miguelbalparda** [comment]
If the module is using observers it shouldn't be a problem, so maybe there is something else. Also, if you see the module has any frontend router try to whitelist it to see if it helps.

**Comment by magegirl** [comment]
I see i can disable this override with this module !
i didn't have this error anymore
