### ISSUE TITLE
Turpentine - Varnish 301 redirect 

### ISSUE THREAD

**Issue by vikassoni22** [nexcess/magento-turpentine#1287]
Hi, I am trying to configure varnish caching for my magento website and have configured turpentine successfully. I have been using Smartware-Porto theme and an extension named PeerForest to render my header. I am applying ESI cache policy on my header block and turpentine injects it successfully, but while rendering it gives 301 redirect to header. I have been trying to modify .xml files, but nothing seems to work. When I use 'ajax' method for caching, drop down in my header menu doesn't work. 

Please help me solve this issue. I am attaching screenshots and turpentine log to give you an idea of what I have done do far. 

details - 
magento - 1.7.0.2
varnishd (varnish-4.1.3 revision 5e3b6d2)
turpentine - 0.7.0

Thanks in advance. 
![img2](https://cloud.githubusercontent.com/assets/7268887/18902693/29ff5cf4-8572-11e6-9d40-34a752c97883.png)
![img1](https://cloud.githubusercontent.com/assets/7268887/18902694/2a28d37c-8572-11e6-819e-59fe2a82eda4.png)

**Comment by miguelbalparda** [comment]
Sorry for the late reply, is this fixed?

**Comment by svikas92** [comment]
hi,
this issue is resolved, forward '/' issue.
Thanks!

**Comment by miguelbalparda** [comment]
Can you post your solution here please?
