### ISSUE TITLE
Add to cart issues - empty 

### ISSUE THREAD

**Issue by Gincc** [nexcess/magento-turpentine#1290]
I am currently using varnish 3.0.7 with Magento CE 1.9 - we are seeing erratic behaviors with the add to cart/checkout. When a user adds to cart, it is empty until after they visit another page. However, when the same user visits the home page again, their cart is empty. Lastly, when a user goes to checkout, the items in their checkout are incorrect. Other tested issue - customer login doesn't work properly/signup stuck.

Attempted the 2 items mentioned here: 
https://github.com/nexcess/magento-turpentine/pull/846

Tried turning CSRF off and VCL Fix off and also tried VCL Fix on. Can you elaborate on what you mean by "pipe the first page visit for new sessions" - @miguelbalparda ?

**Comment by miguelbalparda** [comment]
There are quite a few closed issues about this. Please try to search this and check the open and closed issues and also keep in mind this is not a plug and play extension, you will need to read the documentation first and then try to apply the needed changes to your theme's structure to make it work with Varnish/Turpentine.
