### ISSUE TITLE
getCurrentUrl always refers to previously visited URL

### ISSUE THREAD

**Issue by ashokmsc4** [nexcess/magento-turpentine#1291]
The store language switcher always redirect to previously visited page. Its not redirect to current page. I have checked the previous fixes, but no luck.

**Comment by ashokmsc4** [comment]
I have fixed this issue via below 
https://github.com/nexcess/magento-turpentine/issues/381
Index: community/Nexcessnet/Turpentine/Model/Observer/Esi.php
===================================================================
--- community/Nexcessnet/Turpentine/Model/Observer/Esi.php  (revision 2040)
+++ community/Nexcessnet/Turpentine/Model/Observer/Esi.php  (working copy)
@@ -286,6 +286,7 @@
         $scopeParam = $esiHelper->getEsiScopeParam();
         $methodParam = $esiHelper->getEsiMethodParam();
         $esiData = new Varien_Object();
+        $esiData->setCurrentUrl( Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . $_SERVER['REQUEST_URI'] );
         $esiData->setStoreId( Mage::app()->getStore()->getId() );
         $esiData->setDesignPackage( Mage::getDesign()->getPackageName() );
         $esiData->setDesignTheme( Mage::getDesign()->getTheme( 'layout' ) );
Index: community/Nexcessnet/Turpentine/controllers/EsiController.php
===================================================================
--- community/Nexcessnet/Turpentine/controllers/EsiController.php   (revision 2040)
+++ community/Nexcessnet/Turpentine/controllers/EsiController.php   (working copy)
@@ -89,7 +89,7 @@
                 Mage::app()->setCurrentStore(
                     Mage::app()->getStore( $esiData->getStoreId() ) );
                 $appShim = Mage::getModel( 'turpentine/shim_mage_core_app' );
-                if( $referer = $this->_getRefererUrl() ) {
+                if( $referer = $esiData->getCurrentUrl() ) {
                     $referer = htmlspecialchars_decode( $referer );
                     $dummyRequest = Mage::helper( 'turpentine/esi' )
                         ->getDummyRequest( $referer )

**Comment by daniel043** [comment]
Needs a trim for the trailing slash at the end of the base URL (mydomain.com/), otherwise returns www.mydomain.com//category.html. Used

`$esiData->setCurrentUrl( rtrim(Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB),'/') . $_SERVER['REQUEST_URI'] );`

instead in ESI.php
