### ISSUE TITLE
Blocks are ignored in ESI reload when appended

### ISSUE THREAD

**Issue by sebastianwahn** [nexcess/magento-turpentine#1294]
Magento has a function to append blocks within layouts:

```
 <PRODUCT_TYPE_configurable translate="label" module="catalog"> 
        <block type="catalog/product_view" name="product.info.addtocart2" as="addtocart2"
               template="catalog/product/view/addtocart.phtml"/>

         <reference name="product.info.options.configurable">
             <action method="append">
                 <block>product.info.addtocart2</block>
             </action>
         </reference>

...
```

unfortunately, if a block is appended to a parent block which has ESI tags, the appended block is not loaded within the `getChildHtml` function anymore when the ESI magic happens. Although the block is appended properly when the page is initially loaded.

If i use the following code instead:

```
    <PRODUCT_TYPE_configurable translate="label" module="catalog"> 
        <reference name="product.info.options.configurable">
            <block type="catalog/product_view"
                   name="product.info.addtocart2"
                   template="catalog/product/view/addtocart.phtml" >
            </block>
        </reference>
    </PRODUCT_TYPE_configurable>
```

it will work fine.

Both layout updates are doing the same and are working properly. But just the second one will work with ESI.

I assume this is some missbehaviour of the turpentine plugin.

**Comment by miguelbalparda** [comment]
Can you check https://github.com/nexcess/magento-turpentine/pull/1301 and see if it fixes your issue?

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
