### ISSUE TITLE
Ultimo template mini cart in magento 1.9.3.0 not showing

### ISSUE THREAD

**Issue by hellraiser2005** [nexcess/magento-turpentine#1299]
I have updated my magento to 1.9.3.0 and module Turpentine to 0.7.0.
I now have an issue that the Ultimo template mini cart is not shown in http but the orginal base cart_sidebar.
When i goto https it works and also when i disable the esi cache in admin.

Part of my local.xml

`
        <reference name="header">

```
        <!-- Welcome message as block (added after Magento 1.7.0.2) -->
        <block type="page/html_welcome" name="welcome" as="welcome"/>

        <!-- Add mini cart to the header -->            
        <block type="checkout/cart_sidebar" name="cart_sidebar" template="checkout/cart/mini.phtml" before="-">
            <action method="addItemRender">
                <type>simple</type>
                <block>checkout/cart_item_renderer</block>
                <template>checkout/cart/sidebar/default.phtml</template>
            </action>
            <action method="addItemRender">
                <type>grouped</type>
                <block>checkout/cart_item_renderer_grouped</block>
                <template>checkout/cart/sidebar/default.phtml</template>
            </action>
            <action method="addItemRender">
                <type>configurable</type>
                <block>checkout/cart_item_renderer_configurable</block>
                <template>checkout/cart/sidebar/default.phtml</template>
            </action>
            <block type="core/text_list" name="cart_sidebar.extra_actions" as="extra_actions" translate="label" module="checkout">
                <label>Shopping Cart Sidebar Extra Actions</label>
            </block>
            <block type="cms/block" name="block_mini_cart_above_products">
                <action method="setBlockId">
                    <block_id>block_mini_cart_above_products</block_id>
                </action>
            </block>
        </block>`
```

If there is more info needed please let me know. Thanks in advance.

**Comment by miguelbalparda** [comment]
There are quite a few Ultimo issues reported and solved, have you checked the Wiki and the open and closed issues in this repo?

**Comment by hellraiser2005** [comment]
I couldn't find any solution until i reverted the function "_getEsiBlock" back to what it was before upgrade. It looks that the new function is not good with the xml overrides in the ultimo tpl layout?

`protected function _getEsiBlock( $esiData ) {
        $block = null;
        Varien_Profiler::start( 'turpentine::controller::esi::_getEsiBlock' );
        foreach( $esiData->getSimpleRegistry() as $key => $value ) {
            Mage::register( $key, $value, true );
        }
        foreach( $esiData->getComplexRegistry() as $key => $data ) {
            $value = Mage::getModel( $data['model'] );
            if( !is_object( $value ) ) {
                Mage::helper( 'turpentine/debug' )->logWarn(
                    'Failed to register key/model: %s as %s(%s)',
                    $key, $data['model'], $data['id'] );
                continue;
            } else {
                $value->load( $data['id'] );
                Mage::register( $key, $value, true );
            }
        }
        $layout = Mage::getSingleton( 'core/layout' );
        Mage::getSingleton( 'core/design_package' )
            ->setPackageName( $esiData->getDesignPackage() )
            ->setTheme( $esiData->getDesignTheme() );
        $layoutUpdate = $layout->getUpdate();
        $layoutUpdate->load( $this->_swapCustomerHandles(
            $esiData->getLayoutHandles() ) );
        foreach( $esiData->getDummyBlocks() as $blockName ) {
            $layout->createBlock( 'Mage_Core_Block_Template', $blockName );
        }
        $layout->generateXml();
        $blockNode = current( $layout->getNode()->xpath( sprintf(
            '//block[@name=\'%s\']',
            $esiData->getNameInLayout() ) ) );
        if( $blockNode instanceof Varien_Simplexml_Element ) {
            $nodesToGenerate = Mage::helper( 'turpentine/data' )
                ->setLayout( $layout )
                ->getChildBlockNames( $blockNode );
            Mage::getModel( 'turpentine/shim_mage_core_layout' )
                ->shim_generateFullBlock( $blockNode );
            foreach( $nodesToGenerate as $nodeName ) {
                foreach( $layout->getNode()->xpath( sprintf(
                        '//reference[@name=\'%s\']', $nodeName ) ) as $node ) {
                    $layout->generateBlocks( $node );
                }
            }
            $block = $layout->getBlock( $esiData->getNameInLayout() );
        } else {
            Mage::helper( 'turpentine/debug' )->logWarn(
                'No block node found with @name="%s"',
                $esiData->getNameInLayout() );
        }
        Varien_Profiler::stop( 'turpentine::controller::esi::_getEsiBlock' );
        return $block;
    }`

**Comment by miguelbalparda** [comment]
Can you try https://github.com/nexcess/magento-turpentine/pull/1301 and let me know if it fixes your issue?

**Comment by hellraiser2005** [comment]
Did not fix the problem, I think this part of the code is the fix, did not test it.

Mage::getSingleton( 'core/design_package' )
            ->setPackageName( $esiData->getDesignPackage() )
            ->setTheme( $esiData->getDesignTheme() );

Because I reverted back the complete function.

**Comment by bartlubbersen** [comment]
During the module update I stumbled on the same problem also with an ultimate template. It has something to do with the block name, because it was identical to the sidebar block Turpentine is loading the wrong block. If i changed the name of the block from cart_sidebar to cart_sidebar_mini the problem was solved. Another way to solve it by editing the module was to remove this code from the _getEsiBlock function:

```
        //find addional blocks that aren't defined in the <block/> but via <reference name="%s">
        $referenceNodes = $layout->getNode()->xpath(sprintf(
            '//reference[@name=\'%s\']',
            $esiData->getNameInLayout() ));
        if ($referenceNodes) {
            foreach ($referenceNodes as $referenceNode) {
                if ($referenceNode instanceof Mage_Core_Model_Layout_Element) {
                    $referencesToGenerate = $turpentineHelper
                        ->getChildBlockNames($referenceNode);
                    $nodesToGenerate =
                        array_merge($nodesToGenerate, $referencesToGenerate);
                }
            }
        }
```

The problem is solved for me, but just wanted to update the issue since it helped me.

**Comment by hellraiser2005** [comment]
Upgraded to 0.7.1 still same problem

**Comment by miguelbalparda** [comment]
Can you check the version in devel plus @bartlubbersen reply?

**Comment by hellraiser2005** [comment]
Changed to the develop branch tested it, still same problem.
Removed the code that @bartlubbersen  suggested, then its is working correctlty. Dont have other issues.
