### ISSUE TITLE
checkout_onepage_progress_* are cached

### ISSUE THREAD

**Issue by sebastianwahn** [nexcess/magento-turpentine#1302]
On the onepage checkout, the frontend is doing AJAX requests to the backend about the progress. These calls shouldn't be cached, although they are.

When the `public function progressAction()` (which handles the AJAX) is processed the code which will set the `Mage::register('turpentine_nocache_flag', true, true);` is not hit at all. (You can test this by putting breakpoints on all occourences of the above code).

This leads to the problem that when your function `public function setCacheFlagHeader($eventObject) { ... }` is processed, the `Mage::register('turpentine_nocache_flag')` will return null. This will lead to the problem, that the header is set to `X-Turpentine-Cache: 1`.

You have a function implemented which should set the `Mage::register('turpentine_nocache_flag')`: `public function checkCacheFlag($eventObject)`. Although, when the `public function progressAction()` is processed the event ("controller_action_layout_generate_blocks_after")  you listening on in this function is not dispatched.

**Comment by miguelbalparda** [comment]
Have you tried adding checkout to the whitelist?

**Comment by sebastianwahn** [comment]
@miguelbalparda If i add them to the whitelist it works. 
Since, there is code which should handle this case (but doesn't work) i recommend either remove the buggy code or fix it.
