### ISSUE TITLE
Simple fix

### ISSUE THREAD

**Issue by Nuranto** [nexcess/magento-turpentine#1303]
Paypal redirect page is being cached.
Tested on :
Magento ver. 1.11.0.0 (native magento Paypal extension)
Turpentine 0.6.9

**Comment by miguelbalparda** [comment]
Can you add some more info please? Have you tried adding this to the whitelist?

**Comment by Nuranto** [comment]
We just did, I'll tell you if it works, but I'm pretty sure it will. A simple fix could be to add "paypal" in the blacklist default value.

The case : 
Our order ...248, GT=21,60€ PM=paypal  => has been not paid on paypal by the customer => Got validated by paypal on magento
Our order ...249, GT=23,80€ PM=paypal  => has been paid on paypal by the customer but partially (amount 21,60€) => Not validated on magento

URL used, which I suspect to be cached when it shouldnt : GET /paypal/standard/redirect/

**Comment by miguelbalparda** [comment]
Did adding this to the whitelist helped?

**Comment by Nuranto** [comment]
Yes it did

**Comment by miguelbalparda** [comment]
Cool, I'll close this issue then.

**Comment by Nuranto** [comment]
Well, since paypal is a native magento module, I think it would be nice to manage it without having to add an exception manually after installing the extension / enabling paypal. It would prevent many orders & payments issues.
But, well, your call :p
