### ISSUE TITLE
Number of uses of search terms is not getting updated

### ISSUE THREAD

**Issue by jishvi** [nexcess/magento-turpentine#1305]
Hi,
    Since search page is getting cached, the number of uses of search terms is not getting updated. We have a search suggester which depends on the number of uses of search terms. I need to cache the search page and at the same time, I need to update the number of uses of search terms. Is that possible? Is there an event which is triggered when we search? So that I can flush the cache.

**Comment by miguelbalparda** [comment]
Have you tried whitelisting the url? This should help in this case.

**Comment by jishvi** [comment]
How can I whitelist a URL? I don't want to add search URL in the blacklist. Because I need the search page to be cached.

**Comment by miguelbalparda** [comment]
I meant the search suggester. How does it work? https://github.com/nexcess/magento-turpentine/wiki/Configuration#url-based-caching

**Comment by jishvi** [comment]
Yeah. I get it. But that won't help because, when I search the same word twice, the second request is being served from cache. So the '_number of uses_' of that search word is not updated. 
![magento1](https://cloud.githubusercontent.com/assets/10036266/19979770/a6bf9dc8-a221-11e6-8c11-aa523e23ce41.png). 
The search suggester only shows words having _number of uses_ more than 5. So when I  search a new word it is set to 1 and not getting updated if I search the same word again.

**Comment by miguelbalparda** [comment]
Ok I understand now. I'm not sure how the +1 for the term in the search is done but if you find that you should be able to hole punch just that bit of the code and have the counter working.

**Comment by jishvi** [comment]
Thanks for the quick response. They are setting it in Result controller of the core module catalogsearch. Here is the piece of code.
 `  if ($query->getId()) {
                    $query->setPopularity($query->getPopularity()+1);
                }
                else {
                    $query->setPopularity(1);
                }
`
Any idea how to hole punch this?

**Comment by miguelbalparda** [comment]
Maybe not directly in the controller but you can replicate the feature within a block and hole punch that in an XML.

**Comment by jishvi** [comment]
Okay. Or I can send  a POST or GET request to manually update the count. Anyway, I'll look into it. Thanks for the help.

**Comment by miguelbalparda** [comment]
Perfect if you make it work please post the code here.
