### ISSUE TITLE
Looking for Hole Puncher expert

### ISSUE THREAD

**Issue by livneb** [nexcess/magento-turpentine#1306]
Hi,
We have 4 sites. all of them using varnish and turpentine.
magento 1.9.
i'm looking for an expert to go through the ESI settings in the layout xml files in order improve the performance. do some fine tuning to the whole process.

Thanks in advanced.

**Comment by miguelbalparda** [comment]
We don't offer a paid configuration service,I suggest you using sites like https://commercehero.io to see if you can find anyone available to help you.
