### ISSUE TITLE
Activating Varnish breaks "Layout Update XML" for CMS page

### ISSUE THREAD

**Issue by mobweb** [nexcess/magento-turpentine#1307]
I am doing the following "Layout Update XML" via the backend on a CMS page (not in a layout XML file):

```
<!-- Top menu -->
<reference name="top.menu">
    <!-- Remove the default sidebar navigation (categories) -->
    <remove name="catalog.topnav" />

    <!-- Insert our custom sidebar navigation block -->
    <block type="cms/block" name="subnavigation_mobile">
         <action method="setBlockId"><block_id>subnavigation_mobile</block_id></action>
     </block> 
</reference>
```

For some reason, when I have enabled Varnish, the layout update is ignored.

When I activate the Varnish bypass cookie, the layout updates are applied and visible in the frontend.

I have confirmed that other layout (very similar to this one) work, so it's not like Varnish is ignoring all manual layout updates entered in the CMS page configuration.

Any idea why this could be happening? Why is Varnish causing Magento to ignore the layout update?

**Comment by miguelbalparda** [comment]
Probably because the parent/container block has different cache policies. Can you try doing the same in a XML file instead of doing it in the backend?

**Comment by mobweb** [comment]
Ah, thanks. The parent container is actually the header, so I guess that must be it.

**Comment by mobweb** [comment]
Closing this, thanks.
