### ISSUE TITLE
Lot of entries in log_visitor

### ISSUE THREAD

**Issue by ronn0** [nexcess/magento-turpentine#1308]
Good day,

After installing this module with a nginx-proxy:
```location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_pass http://127.0.0.1:6081;

        # Cache configuration
        proxy_cache_valid 3s;
        proxy_no_cache $cookie_PHPSESSID;
        proxy_cache_bypass $cookie_PHPSESSID;
        proxy_cache_key "$scheme$host$request_uri";
        add_header X-Cache $upstream_cache_status;
    }
```

Varnish is running on prot 6081 and that one is forwarded to lighttpd on port 8080. 

Every new pageview is a new entry in my log_visitor table wich is around 1 million rows the last 14 days (auto cleaning). They all have the http_user_agent 

> Nexcessnet_Turpentine/0.7.0 Magento/1.9.3.0 Varien_Http_Client 

They all have the IP 127.0.0.1 

Is there something wrong in my configuration? I'd like to log the products viewed the way it should be for our recommendations.

**Comment by miguelbalparda** [comment]
This is probably because of the way you have configured nginx and Varnish, I don't think this is related to the extension itself.
