### ISSUE TITLE
SID appearing in URLs when going to secure/unsecure links

### ISSUE THREAD

**Issue by paulpartington** [nexcess/magento-turpentine#131]
Hello,

We are using Turpentine and we are having a small issue with some URLs. When they are entered with Mage::getUrl(), __SID=U and __SID=S are being appended to the URL if it's changing from http to https. If I disable Turpentine it doesn't happen.

We are running on:
nginx
php5-fpm
varnish 3
Magento CE 1.7.0.2

Edit:

This appears to only be happening to links in the header block. If I change ESI to 

```
<reference name="header">
       <turpentine_cache_flag value="0"/>
</reference>
```

it works but obviously we lose the benefit of caching.

Apologies if this has been answered elsewhere and if you need any more information I'll provide what I can do!

Cheers

**Comment by lonesoft** [comment]
Although this is an old question, I leave my note here as I had the same problem and found the solution.
The problem with a cache (I am using the AWS CloudFront) is that it does not forward the headers.
It seems like magento relies on that Header to decide if the browser has or not cookies capabilities.
Once I enabled the "Host" Header, the SID disappeared.
