### ISSUE TITLE
Error installation varnish

### ISSUE THREAD

**Issue by magegirl** [nexcess/magento-turpentine#1318]
Hello,
I know that this is not entirely in turpentine but i want install this plugin.
I try to install varnish in my server : 
1/ sudo curl https://repo.varnish-cache.org/ubuntu/GPG-key.txt | sudo apt-key add -
2/ echo "deb http://repo.varnish-cache.org/ubuntu/ trusty varnish-4.0" | sudo tee -a /etc/apt/sources.list
3/ sudo apt update
4/ sudo apt install varnish

I have this error and i do not find anything on google : 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libvarnishapi1
Suggested packages:
  varnish-doc
The following NEW packages will be installed:
  libvarnishapi1 varnish
0 upgraded, 2 newly installed, 0 to remove and 22 not upgraded.
Need to get 0 B/552 kB of archives.
After this operation, 1,733 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Selecting previously unselected package libvarnishapi1.
(Reading database ... 57570 files and directories currently installed.)
Preparing to unpack .../libvarnishapi1_4.0.3-5~trusty_amd64.deb ...
Unpacking libvarnishapi1 (4.0.3-5~trusty) ...
Selecting previously unselected package varnish.
Preparing to unpack .../varnish_4.0.3-5~trusty_amd64.deb ...
Unpacking varnish (4.0.3-5~trusty) ...
Processing triggers for systemd (215-17+deb8u5) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up libvarnishapi1 (4.0.3-5~trusty) ...
Setting up varnish (4.0.3-5~trusty) ...
dpkg-statoverride: error: group 'varnishlog' does not exist
dpkg: error processing package varnish (--configure):
 subprocess installed post-installation script returned error exit status 2
Processing triggers for libc-bin (2.19-18+deb8u6) ...
Processing triggers for systemd (215-17+deb8u5) ...
Errors were encountered while processing:
 varnish
E: Sub-process /usr/bin/dpkg returned an error code (1)

Thanks for your help

**Comment by miguelbalparda** [comment]
You will have to ask your hosting provider this one, it can be a number of things that exceeds our support scope.
