### ISSUE TITLE
Turpentine 0.7.1 on magento 1.6.2.0

### ISSUE THREAD

**Issue by ccorbineau** [nexcess/magento-turpentine#1321]
Hi,

We use turpentine 0.6.0 on magento 1.6.2.0, great works !

On magentoconnect, i can see your confirm release  0.6.1 is compatible with 1.6+ whereas it's not the case since release 0.6.3  (Compatibility: 1.7, 1.8, 1.8.1, 1.9)

Coud you confirm me if release 0.7.1 is compatible/working with magento 1.6.2.0 ? 

Thanks

**Comment by miguelbalparda** [comment]
That is a pretty old version we don't currently support. With that said, I suggestoyou to try the latest versions to see if they work with your store. Since lots of changes were introduced in 1.8 I'm not entirely sure it will work.

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
