### ISSUE TITLE
Issue on desactivate Turpentine (ver. 1.9.1.1)

### ISSUE THREAD

**Issue by tirys** [nexcess/magento-turpentine#1323]
Hello,

When I try to desactivate the Turpentine on Magento 1.9.1.1, the cache manager page stop works, the list of caches not load at the page. Can you help me?

Thanks

**Comment by miguelbalparda** [comment]
You will need to completely remove all the files instead of deactivating it manually.

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
