### ISSUE TITLE
Unable to hole punch an inner block

### ISSUE THREAD

**Issue by jishvi** [nexcess/magento-turpentine#1325]
Hi, 
    I have a custom block inside the block called 'product_list'. I need to exclude that block from caching. But this is not possible since the inner block gets the product object from the outer block. Since I could not find any solution to that, I decided to hole punch the outer block. Now no matter which category page I'm in it shows the list of entire products in the catalog. 
Here is my ESI policy.
```
 <catalog_category_default>
        <reference name="product_list">
             <action method="setEsiOptions">
                <params>
                    <access>customer_group</access>
                     <flush_events>
                          <adminhtml_customer_save_after/>
                          <admin_system_config_changed_section_customerrewards/>
                    </flush_events>
                </params>
            </action>
        </reference>
    </catalog_category_default>
     <catalog_category_layered>
        <reference name="product_list">
             <action method="setEsiOptions">
                <params>
                    <access>customer_group</access>
                     <flush_events>
                          <adminhtml_customer_save_after/>
                          <admin_system_config_changed_section_customerrewards/>
                    </flush_events>
                </params>
            </action>
        </reference>
    </catalog_category_layered>

```

Is there any registry_keys or dummy blocks I can inclde in ESI policy so that the category won't be cached?
I have tried to include registry key  'current_category' in ESI. But that did not work.

**Comment by miguelbalparda** [comment]
Can you try [this](https://github.com/nexcess/magento-turpentine/pull/1263) and see if you still experience your issue?

**Comment by jishvi** [comment]
@miguelbalparda I do not think it has anything to do with my issue. 
This is a code snippet from my _catalog.xml_
`<block type="catalog/product_list" name="product_list" template="catalog/product/list.phtml">
<block type="catalog/product_list" name="product_list_fbp" as="fbp" template="catalog/product/fbp.phtml"/>`
I need to exclude the block  _product_list_fbp_ from caching. But this block takes a product parameter from the block _product_list_ .

This is how I'm passing that product object
`$this->getChild("fbp")->setData("product", $product_obj)`

But in the _product_list_fbp_ block that object is null since the block _product_list_ is being served from cache. So is it possible to hole punch an inner block leaving its outer blocked to be cached?

**Comment by miguelbalparda** [comment]
I'm not entirely sure I understand your issue. Why are you using catalog_category_default and catalog_category_layered and caching it with customer_group?

**Comment by jishvi** [comment]
Magento uses catalog_category_default when _is anchor_ is off and catalog_category_layered when _is anchor_ is on ([http://magento.stackexchange.com/a/47998/44804](url)) .  I use customer_group because the custom block is group specific. But changing it to private did not work either.

**Comment by jishvi** [comment]
Okay. I'll try it and let you know.

**Comment by jishvi** [comment]
Unfortunately, that didn't work. I am getting this error message saying "Fatal error: Call to a member function getCategoryIds() on null".  I'm calling this function on a product object in the block _product_list_fbp_ . That product object is passed to _product_list_fbp_ from the outer block _product_list_ by using the setData() function. But after I included the block _product_list_fbp_ to hole punch I'm not getting the product object in _product_list_fbp_. 
Here is my ESI policy.
```
<catalog_category_default>
        <reference name="product_list_fbp">
             <action method="setEsiOptions">
                <params>
                    <access>private</access>
                     <flush_events>
                          <checkout_onepage_controller_success_action/>
                          <adminhtml_customer_save_after/>
                          <admin_system_config_changed_section_customerrewards/>
                          <catalog_product_save_after/>
                    </flush_events>
                   <registry_keys>
                        <current_category/>
                    </registry_keys>
                </params>
            </action>
        </reference>
    </catalog_category_default>
```

**Comment by miguelbalparda** [comment]
Check [this](https://github.com/nexcess/magento-turpentine/wiki/ESI_Cache_Policy), specifically the documentation for "What are the parameters for defining a cache policy?"

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
