### ISSUE TITLE
ERROR DETERMINING VARNISH VERSION: GOT UNEXPECTED RESPONSE CODE FROM VARNISH: 500

### ISSUE THREAD

**Issue by ravinew41** [nexcess/magento-turpentine#1326]
When clicking on save settings at the back-end of Magento, it shows the following message:

ERROR DETERMINING VARNISH VERSION: GOT UNEXPECTED RESPONSE CODE FROM VARNISH: 500
FAILED TO APPLY THE VCL TO 127.0.0.1:6082: FAILED TO LOAD CONFIGURATOR
ERROR DETERMINING VARNISH VERSION: GOT UNEXPECTED RESPONSE CODE FROM VARNISH: 500
FAILED TO LOAD CONFIGURATOR

**Comment by miguelbalparda** [comment]
Which version of the module are you using? There are some reports with fixes for this issue [here](https://github.com/nexcess/magento-turpentine/search?q=GOT+UNEXPECTED+RESPONSE+CODE+FROM+VARNISH%3A+500&type=Issues&utf8=%E2%9C%93), have you tried the proposed solutions?
