### ISSUE TITLE
Need Support ton configure a specific TTL for 404 pages

### ISSUE THREAD

**Issue by sandrinecrozat** [nexcess/magento-turpentine#1328]
Hi,
I would like to configure a specific TTL for 404 pages.
I can't find such option in the Turpentine module configuration
Do you know how I do this ?
Thanks

**Comment by miguelbalparda** [comment]
Have you tried setting a TTL for the 404 block and cache the other blocks from that page separately?

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
