### ISSUE TITLE
magento backend cookie "admin" not set / when and why cookies are set

### ISSUE THREAD

**Issue by digitalwert-developer** [nexcess/magento-turpentine#1330]
Hi there,

I'm having an issue getting varnish/turpentine to correctly set cookies.

If I open the magento backend login mask (using a _custom backend adminhtml frontName_), the http response contains a header called _"X-Varnish-Set-Cookie"_. It contains the correct backend cookie.

However, since the cookie is not contained in the _"Set-Cookie"_ header but a custom x-header, login attempts to the magento backend fail because the _formKey isn't valid_.

---

I also spotted this behaviour in the store frontend. Every page-request contains the _"X-Varnish-Set-Cookie"_ header in it's response.

When navigating directly to "/customer/account/login", _no cookie is set_. But taking a detour to "/customer/account/index" (which redirects to "/customer/account/login"), the former will create a cookie by responding with a standard _"Set-Cookie"_ header.

Is this the desired/correct behaviour or is something completely going wrong?
Is Varnish responsible for sending the "Set-Cookie" header or doe's the turpentine extension decide when to send it?

---

The following are some of my configuration values for the magento turpentine extension (in case any of them are relevant):

_general / web_
Cookie Path: (empty)
Cookie Domain: .domain.tld
Base URL: https://subdomain.domain.tld

_turpentine_
Use VCL fix: true
Fix HTTPS redirect: false

_fyi:_ My magento instance is running on a separate server.

**Comment by miguelbalparda** [comment]
@digitalwert-developer this behavior is explained in the documentation and in several issues, basically the first hit is piped to get a valid Magento session and continue business as usual after that.

**Comment by digitalwert-developer** [comment]
Hi @miguelbalparda, thanks for your quick reply.

We finally found a solution for our problem: If the turpentine magento cache "Varnish Pages" is disabled, the magento backend cookie will not be sent to the http client.
Disabling this cache is a valid options, especially for development environments or just for debugging.

see https://github.com/nexcess/magento-turpentine/blob/master/app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl#L127

This would always return a "pass" in varnish which results in varnish always removing the "Set-Cookie" header in "vcl_backend_response".

For requests to the magento backend, using a "pipe" return could fix this problem.

best regards

**Comment by miguelbalparda** [comment]
There is a thread [here](https://github.com/nexcess/magento-turpentine/issues/1129) talking about pipe vs pass, feel free to chime in. I'll close this issue for now.
