### ISSUE TITLE
Can't ESI hole punch "addToParentGroup"

### ISSUE THREAD

**Issue by wolfautoparts** [nexcess/magento-turpentine#1337]
Trying to add ESI hole punch within a tab on the product view page. Adding the hole punch breaks the block. Code I am using:
`    <catalog_product_view>
        <reference name="product.info">
            <block type="core/template" name="the_new_tab" as="the_new_tab" template="catalog/product/view/newtab.phtml">
                <action method="addToParentGroup">
                    <group>detailed_info</group>
                </action>
                <action method="setTitle" translate="value">
                    <value>Does it fit my car?</value>
                </action>
				<action method="setEsiOptions">
					<params>
						<method>esi</method>
						<access>private</access>
						<ttl>0</ttl>
					</params>
				</action>
            </block>
        </reference>
    </catalog_product_view>`

I am kind of lost at this point, Is this a bug or am I missing something?

Error I get:
`Fatal error: Uncaught Error: Call to a member function addToChildGroup() on null in xxx/public_html/app/code/core/Mage/Core/Block/Abstract.php:819 Stack trace: #0 xxx/public_html/app/code/core/Mage/Core/Model/Layout.php(348): Mage_Core_Block_Abstract->addToParentGroup('detailed_info') #1 xxx/public_html/app/code/core/Mage/Core/Model/Layout.php(214): Mage_Core_Model_Layout->_generateAction(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element)) #2 xxx/public_html/app/code/community/Nexcessnet/Turpentine/Model/Shim/Mage/Core/Layout.php(35): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element)) #3 xxx/public_html/app/code/community/Nexcessnet/Turpentine/controllers/EsiController.php(224): Nexcessnet_Turpentine_Model_Shim_Mage_Core_Layout->shim_generateFullBlock(Obje in xxx/public_html/app/code/core/Mage/Core/Block/Abstract.php on line 819`

**Comment by miguelbalparda** [comment]
What have you tried so far to debug this? What makes you think this might be a bug?

**Comment by wolfautoparts** [comment]
This issue is happening on a clean install of magento 1.9.3.1. This is the only modification I have made to this store so far. Also ESI is working correctly on other blocks.

**Comment by miguelbalparda** [comment]
I haven't seen  `<action method="addToParentGroup"> <group>detailed_info</group> </action>` before, can you try removing that and report back?

**Comment by wolfautoparts** [comment]
I am leaning towards this is a bug. 
<action method="addToParentGroup"> <group>detailed_info</group> </action> is used to set this block as a child of "detailed_info".

I did some more troubleshooting and removed my custom block and tried to hole punch the magento RWD "Additional Info" block / tab located on the product view page. I am getting the same error.

I modified app/design/frontend/rwd/default/layout/catalog.xml code as follows (Just added the ESI Action):

`                <block type="catalog/product_view_attributes" name="product.attributes" as="additional" template="catalog/product/view/attributes.phtml">
                    <action method="addToParentGroup"><group>detailed_info</group></action>
                    <action method="setTitle" translate="value"><value>Additional Information</value></action>
					<action method="setEsiOptions">
						<params>
							<method>esi</method>
							<access>private</access>
							<ttl>0</ttl>
						</params>
					</action>`

**Comment by miguelbalparda** [comment]
Check [this](https://github.com/nexcess/magento-turpentine/wiki/ESI_Cache_Policy), specifically the documentation for "What are the parameters for defining a cache policy?"

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
