### ISSUE TITLE
shopping cart not updating auto 

### ISSUE THREAD

**Issue by Greaceaffi** [nexcess/magento-turpentine#1338]
shopping cart not updating auto  while i clear caches. and if i open site with htttps: url there showing correct cart items  i don't know whats happening .
i am using for caches extension any one call help me hoe can i solve this issue. thanks in advance

**Comment by miguelbalparda** [comment]
Can you re phrase this please? I don't understand your issue. FWIW, https has nothing to do with Turpentine.

**Comment by Greaceaffi** [comment]
@miguelbalparda when i add to cart  product into ajax mini cart .  mini cart  showing "1 item in cart" but when i go at home pgee there mini cart showing "cart is empty"  but if i clear cache from admin panel  than mini cart showing "1 item in cart" its happening cache issue

**Comment by miguelbalparda** [comment]
Most of the time this is caused by an incorrect theme architecture. I suggest you to read the [Wiki](https://github.com/nexcess/magento-turpentine/wiki) and also issues with similar problems like the one you are experiencing.

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
