### ISSUE TITLE
Syntax error in VCL file with turpentine 0.7.1, varnish 4.0.4 and Magento 1.9.2.4

### ISSUE THREAD

**Issue by fbenedini** [nexcess/magento-turpentine#1339]
When I try to apply Varnish Config in the Magento Cache Admin, I get a Syntax Error. After downloading the VCL file I found that Turpentine ha s generated these strange lines in the VCL file:

**hash_data(regsub(req.http.Cookie, "^.*?frontend=([^;]*);*.*$", "\1"));
}**
**<<<<<<< HEAD**
**std.log("vcl_hash end return lookup");**
**=======
if (req.http.X-Varnish-Esi-Access == "customer_group" &&
req.http.Cookie ~ "customer_group=") {
hash_data(regsub(req.http.Cookie, "^.*?customer_group=([^;]*);*.*$", "\1"));
}**
**>>>>>>> master**
**return (lookup);**

Deleting these lines and manually deploying the file to Varnish everything works. Why is Turpentine generating these strange lines?
Thank you

**Comment by miguelbalparda** [comment]
Where did you get the files? Can you re download the module from this repo and try again? You will need to remove the module manually first and then reinstall it.

**Comment by fbenedini** [comment]
I installed varnish 4.0.4-3.el7  from epel repository via YUM on CENTOS 7.
I'm going to try your repo and let you know asap.
thank you.



2017-01-03 12:12 GMT+01:00 Miguel Balparda <notifications@github.com>:

**Comment by miguelbalparda** [comment]
I was asking about Turpentine, not Varnish. Where did you get the files? I already fixed this issue in the past but it might still be present, that is why I'm asking.

**Comment by fbenedini** [comment]
From magento connect 


Ottieni Outlook per Android






On Tue, Jan 3, 2017 at 1:24 PM +0100, "Miguel Balparda" <notifications@github.com> wrote:












I was asking about Turpentine, not Varnish. Where did you get the files? I already fixed this issue in the past but it might still be present, that is why I'm asking.

**Comment by miguelbalparda** [comment]
Can confirm the version there still has this issue, working on it now.

**Comment by fbenedini** [comment]
Great! thank you. I proceed with downloading from your repo in the
meanwhile.
bye


2017-01-03 14:11 GMT+01:00 Miguel Balparda <notifications@github.com>:

**Comment by miguelbalparda** [comment]
This should be fixed now, sorry about that.
