### ISSUE TITLE
"/turpentine/esi/getBlock/method"

### ISSUE THREAD

**Issue by viansolutions-com** [nexcess/magento-turpentine#1342]
If I paste a getBlock url in browser the html loads fine, but when it is injected in page it throws "ESI processing not enabled"

Any ideas of what's happening here?

**Comment by miguelbalparda** [comment]
Most of the times this means a php error somewhere or an error in the code somewhere else and not something related to Varnish or Turpentine.

**Comment by viansolutions-com** [comment]
After some tracing, I've seen this requests are throwing the classical "Error 403 External ESI requests are not allowed"

**Comment by miguelbalparda** [comment]
Can you elaborate?

**Comment by viansolutions-com** [comment]
Sure, sorry for the lack of info

This is a new production server, where we are going to migrate an existing project. I thought this errors came because the difference between IPs (we access the new server editing /etc/hosts local file)

After this error we've made the IP mapping in /etc/hosts files for new production servers too, but any ESI request are still throwing that error: "Error 403 External ESI requests are not allowed"

However, if we change method to "ajax" then they load fine...

Any ideas?

**Comment by miguelbalparda** [comment]
[Here](https://github.com/nexcess/magento-turpentine/blob/4929b8a5cbd4e62f254a42dae881eda28b0a7dec/app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl#L171) you can see where the 403 is being generated, are you pasting the URLs right in the browser with debugging off?

**Comment by viansolutions-com** [comment]
Yes, I am pasting url in the browser... but this way the html is loaded fine. Is that piece of code the only place in .vcl where 403 is throwed?

I think our problem is this conditional ( client.ip ~ debug_acl ), I am reporting this to hosting support

**Comment by miguelbalparda** [comment]
In our template yes, but you should check that in your VCL. If debugging is not enabled, the 403 is going to be throwed. I suggest you to check and try to understand the VCL before contacting your hosting support, in this case in particular if you enable debugging and add your IP to the authorized ones it should work  I'll close this ticket for now, feel free to reopen it anytime with more info.
