### ISSUE TITLE
“ADD TO CART” button not workinG www.blendurtrend.com

### ISSUE THREAD

**Issue by pranayambokar99** [nexcess/magento-turpentine#1343]
0
down vote
favorite
i dont know why but the “ADD TO CART” button not working on my website. when ever i click on the add cart button it doesnt do anything. i dont know why but the “ADD TO CART” button not working on my website. when ever i click on the add cart button it doesnt do anything. i dont know why but the “ADD TO CART” button not working on my website. when ever i click on the add cart button it doesnt do anything. i dont know why but the “ADD TO CART” button not working on my website. when ever i click on the add cart button it doesnt do anything.

**Comment by miguelbalparda** [comment]
Closing as invalid.

**Comment by miguelbalparda** [comment]
@pranayambokar99 please try to rephrase this and avoid the copypasting if possible.
