### ISSUE TITLE
Many Buttons not working on my website

### ISSUE THREAD

**Issue by pranayambokar99** [nexcess/magento-turpentine#1346]
www.BlendUrTrend.com , The AddToCart, Drop down for option ( Configurable products, and billing information, etc, this buttons are not working, i tried many solutions, still not solution found.

**Comment by miguelbalparda** [comment]
@pranayambokar99 we'll need to know what have you tried so far, your software version, Turpentine version, theme, etc to be able to help you find the cause of your issue. Most of the times these symptoms show an incompatible theme, not all the themes are compatible with Turpentine out of the box. Have you checked the Wiki, specifically the documentation about ESI?

**Comment by pranayambokar99** [comment]
I have not used turpentine, The theme used is Swify (modulegarden). This error suddenly started occuring, website was working properly from past 12 months.

**Comment by miguelbalparda** [comment]
What do you mean you haven't used Turpentine? Maybe I got this wrong, why do you think your problem is related to this module?

**Comment by pranayambokar99** [comment]
Magento Version 1.9.2.4 , I am not a programmer, i dont know how to use it.

**Comment by miguelbalparda** [comment]
@pranayambokar99 I strongly suggest you to hire a programmer to deal with this. Turpentine is not a plug and plat module and doesn't work out of the box with all themes.

**Comment by pranayambokar99** [comment]
Thank you, i got it fixed, just had to reinstall some plugins.
