### ISSUE TITLE
Unsupported Varnish version 4.1

### ISSUE THREAD

**Issue by magenx** [nexcess/magento-turpentine#1347]
installed varnish
varnishd (varnish-4.1.4 revision 4529ff7)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2015 Varnish Software A

latest turpentine

and i see only 2.1.x - 3.0.x - 4.0.x - Auto

there is no support for Varnish 4.1??

**Comment by miguelbalparda** [comment]
Have you tried selecting auto or 4.0.x? As a minor version, 4.0.x should work.

**Comment by whizkid79** [comment]
are you sure you have the latest turpentine (0.7.1) @magenx ?

**Comment by whizkid79** [comment]
I just found out, there are some unreleased fixes for varnish 4.1 in devel. see also #1231 and #1332

**Comment by magenx** [comment]
i will work with 3.0

**Comment by magenx** [comment]
i just dont understand why i need to select 4.0 for varnish 4.1

**Comment by miguelbalparda** [comment]
It's already fixed in devel, check it out [here](https://github.com/nexcess/magento-turpentine/blob/devel/app/code/community/Nexcessnet/Turpentine/Model/Config/Select/Version.php).

**Comment by whizkid79** [comment]
@miguelbalparda is is working with 4.1 at all? i have several issues, looks like esi caching settings are ignored (at least partially).  on the search page i get:
 ESI processing not enabled 
<Breadcrump>
 ESI processing not enabled

**Comment by miguelbalparda** [comment]
It is working with 4.1, yes. That error usually means an error somewhere else, most of the times a PHP error from my experience.
What have you tried so far to debug this? Have you tried the devel version we mentioned in this issue? Also, have you checked the closed issues for a solution to your specific problem?

**Comment by whizkid79** [comment]
Thanks for the hints. I had some other issues triggered by wrong server time and a typo in a xml file.
My procedure was:
- delete all reports and logs in magento (to have a clean start)
- reload the broken page
- look for errors and exceptions and fix them
- repeat until no exceptions show up any more.

Now the search is working. The header block not knowing the right category was missing another registry key. I now have a working version which looks like this:
`<?xml version="1.0" encoding="UTF-8"?>
<layout version="0.1.0">
    <default>
        <reference name="header">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <scope>page</scope>
                    <registry_keys>
                        <current_category/>
                        <current_entity_key/>
                    </registry_keys>
                    <flush_events>
                        <wishlist_item_save_after/>
                        <wishlist_item_delete_after/>
                        <sales_quote_save_after/>
                        <controller_action_layout_render_before_catalogsearch_result_index/>
                        <persistent_session_expired/>
                    </flush_events>
                </params>
            </action>
        </reference>
    </default>
    <catalogsearch_result_index>
        <reference name="header">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <scope>page</scope>
                    <registry_keys>
                        <current_category/>
                        <current_entity_key/>
                    </registry_keys>
                    <flush_events>
                        <wishlist_item_save_after/>
                        <wishlist_item_delete_after/>
                        <sales_quote_save_after/>
                        <controller_action_layout_render_before_catalogsearch_result_index/>
                        <persistent_session_expired/>
                    </flush_events>
                </params>
            </action>
        </reference>
    </catalogsearch_result_index>
</layout>`

Please note the added `<current_entity_key/>` in the registry_keys listing.
