### ISSUE TITLE
Header ".. Items in Cart"

### ISSUE THREAD

**Issue by philicous** [nexcess/magento-turpentine#1374]
Hi,
i have an issue with my ".. items in cart" block in my header. Varnish is always caching this block. I almost tried for 10 hours to fix it, but it didn't worked for me.
I'm using Magento 1.9.3 with turpentine 0.7.10 and varnish 3.
in my header.phtml i have:`<div class="cart-top"><?php echo $this->getChildHtml('venusMinicart'); ?></div>`
in my minicart.phtml i have `
<span id="cart-total" >
					<?php echo $cart_total; ?></span>`

I also tried to add ESI:

> <reference name="header">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
					<ttl>0</ttl>
                    <flush_events>
                        <wishlist_item_save_after/>
                        <wishlist_item_delete_after/>
                        <sales_quote_save_after/>
                        <controller_action_layout_render_before_catalogsearch_result_index />
                        <persistent_session_expired/>
			<checkout_cart_product_add_after/>
			<checkout_cart_update_items_after/>
			<checkout_cart_product_update_after/>
                    </flush_events>
                </params>
            </action>
        </reference>

and I also tried to log the Blocks:

> 2017-02-28T18:31:54+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: header
2017-02-28T18:31:54+00:00 INFO (6): TURPENTINE: -- block testing: shouldResponseUseEsi = 
2017-02-28T18:31:54+00:00 INFO (6): TURPENTINE: -- block testing: instanceof Mage_Core_Block_Template = 1
2017-02-28T18:31:54+00:00 INFO (6): TURPENTINE: -- block testing: Esi Options = Array
(
    [access] => private
    [ttl] => 0
    [flush_events] => Array
        (
            [wishlist_item_save_after] => 
            [wishlist_item_delete_after] => 
            [sales_quote_save_after] => 
            [controller_action_layout_render_before_catalogsearch_result_index] => 
            [persistent_session_expired] => 
            [checkout_cart_product_add_after] => 
            [checkout_cart_update_items_after] => 
            [checkout_cart_product_update_after] => 
        )

)

But nothing of this helped me. Could someone help me? I'm already so frustrated...

**Comment by miguelbalparda** [comment]
Have you checked the [wiki](https://github.com/nexcess/magento-turpentine/wiki/ESI_Cache_Policy)? Not all the themes are compatible out of the box with Varnish and usually the fix is to move the conflicing block outside their current div or add an ESI policy for the container block. I've also seen using ajax as the injection method helps, it's all explained in the wiki.

**Comment by philicous** [comment]
I already checked the wiki. If tried to put the ESI in my turpentine_esi.xml and if I debug the blocks to the log i see that it works.

> Code
 2017-02-28T18:32:05+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: venus.minicart
2017-02-28T18:32:05+00:00 INFO (6): TURPENTINE: -- block testing: shouldResponseUseEsi = 
2017-02-28T18:32:05+00:00 INFO (6): TURPENTINE: -- block testing: instanceof Mage_Core_Block_Template = 1
2017-02-28T18:32:05+00:00 INFO (6): TURPENTINE: -- block testing: Esi Options = Array
(
    [access] => private
    [flush_events] => Array
        (
            [sales_quote_save_after] => 
            [checkout_cart_product_add_after] => 
            [checkout_cart_update_items_after] => 
            [checkout_cart_product_update_after] => 
        )

)

and I also tried it with the complete header

> Code
2017-02-28T18:32:05+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: header
2017-02-28T18:32:05+00:00 INFO (6): TURPENTINE: -- block testing: shouldResponseUseEsi = 
2017-02-28T18:32:05+00:00 INFO (6): TURPENTINE: -- block testing: instanceof Mage_Core_Block_Template = 1
2017-02-28T18:32:05+00:00 INFO (6): TURPENTINE: -- block testing: Esi Options = Array
(
    [access] => private
    [ttl] => 0
    [flush_events] => Array
        (
            [wishlist_item_save_after] => 
            [wishlist_item_delete_after] => 
            [sales_quote_save_after] => 
            [controller_action_layout_render_before_catalogsearch_result_index] => 
            [persistent_session_expired] => 
            [checkout_cart_product_add_after] => 
            [checkout_cart_update_items_after] => 
            [checkout_cart_product_update_after] => 
        )

)

**Comment by philicous** [comment]
I've now found out that this function: 

> Code 
public function shouldResponseUseEsi() {	
        return Mage::helper('turpentine/varnish')->shouldResponseUseVarnish() &&
        $this->getEsiEnabled();
}

is always returning "FALSE" and on my webshop i'm getting following error: "ESI includes are not enabled"

Does anyone know what to do to enable ESI includes?

**Comment by rbrown** [comment]
In `System/Cache Management` the `Varnish Pages` and `Varnish ESI Blocks` ?

**Comment by philicous** [comment]
Thanks, that was right. The "... items in cart" block is now working. But it takes very long to load the products on a category page. it takes appr. 2 sec to load just 1 product.

**Comment by philicous** [comment]
Or it seems that the whole page isn't caching anymore

**Comment by miguelbalparda** [comment]
@philicous this might be related to your theme architecture. You might need to add ESi policies for everything not being cached.

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
