### ISSUE TITLE
gzip or mod_deflate?

### ISSUE THREAD

**Issue by zlep** [nexcess/magento-turpentine#1375]
Hi, is it possible to use gzip or mod_deflate with Turpentine (Varnish)? Because the first time a user visits my site, it has to load 2,5 MB. GTmetrix is telling me this could be reduced by 50% by enabling gzip/mod_deflate. I tried to enable it in my htaccess but it seems not to work because of Varnish I guess!?!

This is my htaccess:

`<IfModule mod_deflate.c>
 AddOutputFilterByType DEFLATE text/plain
 AddOutputFilterByType DEFLATE text/html
 AddOutputFilterByType DEFLATE text/xml
 AddOutputFilterByType DEFLATE text/css
 AddOutputFilterByType DEFLATE text/javascript
 AddOutputFilterByType DEFLATE application/xml
 AddOutputFilterByType DEFLATE application/xhtml+xml
 AddOutputFilterByType DEFLATE application/rss+xml
 AddOutputFilterByType DEFLATE application/atom_xml
 AddOutputFilterByType DEFLATE application/javascript
 AddOutputFilterByType DEFLATE application/x-javascript
 AddOutputFilterByType DEFLATE application/x-shockwave-flash
</IfModule>`

Not an issue of Turpentine obviously. I hope it's still ok to ask you guys :) 
Thank you very much in advance.

**Comment by miguelbalparda** [comment]
[Here](https://www.varnish-cache.org/docs/3.0/phk/gzip.html) you can find a guide about this. 
Turpentine's VCL should already handle this, so my best guess is that you need to contact your hosting provider and ask them about this too.
