### ISSUE TITLE
Custom debugging

### ISSUE THREAD

**Issue by eriksenonline** [nexcess/magento-turpentine#1378]
Hi
I have no other place to ask as Nexcess only provide support for this extension to their hosting customers. I have an issue with Turpentine, ssl and my magento store and need an expert to help us. The issue is session related and we beleve it is some of our custom code messing up.  

I understand if you delete this post, but as this is kind of an emergency I had to try. Hope I do not bother the administrators with this.

**Comment by miguelbalparda** [comment]
I'm not sure here you got the "Nexcess only provide support for this extension to their hosting customers" but that is not the case. Can you add some more info to this issue to see if anyone can help?
