### ISSUE TITLE
Magento instance creating multiple session ids on first page load

### ISSUE THREAD

**Issue by manucorra** [nexcess/magento-turpentine#1387]
We are using Nexcessnet_Turpentine 0.5.4 in our Magento ver. 1.13.1.0. We have 2 stores and sharing the cart. We are getting empty cart issue when we are adding product in one store and navigating to next store. The issue is not coming when the varnish is disabled. While debugging we came to know that multiple session ids are generating when we load the site for first time in a new browser. When we checked the session id in getSessionId in this file - app/code/core/Mage/Core/Model/Session/Abstract/Varien.php, we found 13 times session ids are logged. These were 3 different ids. When the varnish is in disabled stage, only 4 times session ids are logged and all were same.

Please check this issue and let us know how to fix this.

Thanks,
Manu

**Comment by miguelbalparda** [comment]
Have you tried upgrading Turpentine to the latest version?

**Comment by manucorra** [comment]
Yes, we upgraded the Turpentine module to latest version - 0.7.10. Still the multiple session ids were generating.

**Comment by miguelbalparda** [comment]
Have you checked the wiki and the open and closed issues with your same problem? We are using 0.7.2 right now also.

**Comment by manucorra** [comment]
Yes, we have checked the below threads regarding the issue, but the changes did not fix our issue.
https://github.com/nexcess/magento-turpentine/issues/459
https://github.com/nexcess/magento-turpentine/pull/516
https://github.com/nexcess/magento-turpentine/issues/470
We will try this version - 0.7.2 in our server. Can you please send us the varnish configuration file for this version.

**Comment by miguelbalparda** [comment]
Do you mean the generated VCL?

**Comment by manucorra** [comment]
Yes, default.vcl file

**Comment by miguelbalparda** [comment]
Turpentine generates the VCL on the fly with the settings you enter in the admin.

**Comment by manucorra** [comment]
Thanks Miguel.. the issue seems to be fixed in our dev server.. now the cart in second store showing products.. thanks a lot
