### ISSUE TITLE
set session data  holepunch with ESI not working

### ISSUE THREAD

**Issue by daniel043** [nexcess/magento-turpentine#1389]
Hi,

I am trying to set/get the last category urls of customers in a session (for individual back buttons and other things). It is working but when I activate Varnish/Turpentine, the session is not updated anymore. 

I am calling a child phtml block (ESI params set to TTL 0 and private). The code contains among other things: 

`<?php
$currentUrl = $this->helper('core/url')->getCurrentUrl();
$session = Mage::getSingleton("core/session",  array("name"=>"frontend"));
$session->setData("last_category_url", $currentUrl);
?>`

Is it due to Varnish/Turpentine and how it is caching pages or am I missing something here? Everything else is working fine though, e.g. form keys.

**Comment by miguelbalparda** [comment]
My best guess is that the block  is not being correctly cached. That being said, usually a frontend approach using Js usually helps but I'm not sure that is possible for your particular case.

**Comment by daniel043** [comment]
Thank you for the feedback. I will check some more caching parameters on monday then. So far I tried:

 ```
 <params>
                    <access>private</access>
                    <flush_events>
                        <catalog_controller_product_view/>
                    </flush_events>
</params>
```

for product pages. For category pages:
```
  <registry_keys>
                    <current_category/>
  </registry_keys>
```
Also tried for both:

```
 <params>
...
 <ttl>0</ttl>
 </params>
```

It is quite bugging me.

**Comment by daniel043** [comment]
Solved by using the getCurrentUrl Fix from [here](https://github.com/nexcess/magento-turpentine/issues/1291).

Saving the current URL in a session was not working because getting the current URL for this was faulty.
