### ISSUE TITLE
VCL fix vs Observer method: major issues

### ISSUE THREAD

**Issue by dvershinin** [nexcess/magento-turpentine#1391]
With VCL fix Enabled, the ```generate_session``` subroutine becomes unused in Varnish and first cookie-less request goes with pipe mode. 

Effect: no full page cache for new visitor's first page request. 
**Turpentine can't be called a real FPC solution for Magento. Not great!**

[Installation doc](https://github.com/nexcess/magento-turpentine/wiki/Installation) says this for disabled state of VCL fix:

> If Disable is selected, an observer will be used. Please note that the observer method will disable CSRF protection.

Effect: full page cache achieved with lack of security. 

The [Technical notes](https://github.com/nexcess/magento-turpentine/blob/master/TECHNICAL_NOTES.md) only mention how it's all awesome and great about form keys solution. 

In the earlier "beginning" section the technical notes also state how it's all wrong to:

> just let the first request from a client pass through Varnish to the backend and send the response back unmodified which lets the client get the session cookie

and 

> This is how Turpentine originally worked, along with many of the other Varnish extensions available for Magento.

Now my first question is :) We're essentially back in time with form keys VCL fix? First page request has to be piped in order to retain security?

Can we get some technical details please on the effect of "VCL Fix: Disabled" i.e. how does it break security and update Technical notes with it.

**Comment by miguelbalparda** [comment]
This has been discussed plenty of times in this repo, have you checked the open and closed issues?
I believe the documentation is pretty clear, but feel free to open a PR for us to consider if you think this can be done differently. 
As of you saying this is not a FPC extension, I will have to disagree with you. The VCL fox is the best way we found to handle sessions in Magento without compromising the site performance. I'm pretty sure you can take a miss in the first visit for the gains Turpentine will give you in the subsequent visits.

**Comment by dvershinin** [comment]
I have seen the discussions however I believe it should be clearly stated in plugin options that the VCL fix will cause first page visit to be miss. The subsequent visit performance gain is of little consolation as I believe non-Varnish FPC solutions will not suffer from the same first-visit cache miss.

I understand the way it is now but let's admit it - the first page request is most important and it should be documented what "comes" with the VCL fix performance wise.

**Comment by miguelbalparda** [comment]
Again, feel free to submit a PR if you think it's not clear enough. If you were able to find this as quickly as you did, I would say it's pretty clear. 
As a programmer I can't go with the SEO idea that the first page is the most important thing in the entire universe and nothing else matters. I also don't think it's fair to compare non varnish solutions with varnish solutions since the usage of resources and the results clearly show how different these options are. 
This is not a plug and play extension and there is some work required to make everything fly, but after hat the benefits are quite clear in terms of performance.

**Comment by dvershinin** [comment]
@jmifarma tried a few PHP based caches including Lesti FPC, Amasty FPC and Potatocommerce.

The latter, [Potatocommerce FPC](
https://www.getpagespeed.com/recommends/potatocommerce-full-page-cache-cache-crawle), was tried out of frustration after Lesti and Amasty failed to deliver. Surprisingly, it provided consistent, fast time to first byte, well within 250ms which was satisfactory and much better than slow first time visits.

If you need something freeware, I'd look towards [Lesti FPC](https://github.com/GordonLesti/Lesti_Fpc).

All in all, I would never understand the notion of using Varnish "because it's Varnish", while tremendously hurting conversions (which is of course the case if first page visit is uncached). I like Varnish otherwise (where it is perfectly applicable, like Magento 2, or Wordpress blogs), but not with Magento 1. 

I understand that this uncached first page visit is somewhat by design of M1, but this had to be stated clearly by Turpentine on the project's homepage. To many folks, this would make things more clear on how Turpentine is useless.

**Comment by mabigo** [comment]
There is a built-in (and smart written) crawler for warming up the cache in turpentine. So @dvershinin 's statement ins't accurate. 
Crawler usage however depends on catalog size, and may not be applicable for high-traffic stores
