### ISSUE TITLE
Varnish never init cookie first time

### ISSUE THREAD

**Issue by GuilleretFlorian** [nexcess/magento-turpentine#1396]
On my website : www.maisondunreve.com cooki session isn't generate until i add a product in my cart.

And if i check the vcl generate i saw this : 

`/* -- REMOVED
sub generate_session {
if (req.url ~ ".*[&?]SID=([^&]+).*") {
set req.http.X-Varnish-Faked-Session = regsub(
req.url, ".*[&?]SID=([^&]+).*", "frontend=\1");
} else {
C{
char uuid_buf [50];
generate_uuid(uuid_buf);
static const struct gethdr_s VGC_HDR_REQ_VARNISH_FAKED_SESSION =
{ HDR_REQ, "\030X-Varnish-Faked-Session:"};
VRT_SetHdr(ctx,
&VGC_HDR_REQ_VARNISH_FAKED_SESSION,
uuid_buf,
vrt_magic_string_end
);
}C
}
if (req.http.Cookie) {
std.collect(req.http.Cookie);
set req.http.Cookie = req.http.X-Varnish-Faked-Session +
"; " + req.http.Cookie;
} else {
set req.http.Cookie = req.http.X-Varnish-Faked-Session;
}
}
sub generate_session_expires {
C{
time_t now = time(NULL);
struct tm now_tm = *gmtime(&now);
now_tm.tm_sec += 86400;
mktime(&now_tm);
char date_buf [50];
strftime(date_buf, sizeof(date_buf)-1, "%a, %d-%b-%Y %H:%M:%S %Z", &now_tm);
static const struct gethdr_s VGC_HDR_RESP_COOKIE_EXPIRES =
{ HDR_RESP, "\031X-Varnish-Cookie-Expires:"};
VRT_SetHdr(ctx,
&VGC_HDR_RESP_COOKIE_EXPIRES,
date_buf,
vrt_magic_string_end
);
}C
}
-- */
`

Is it normal that this code is in comment ?

**Comment by GuilleretFlorian** [comment]
In fact i saw that everyone got a wrong cookie : frontend=crawler-session

**Comment by GuilleretFlorian** [comment]
quick fix : change ip crawler in varnish option to prevent all user to get crawler-session cookie

**Comment by miguelbalparda** [comment]
Yep, that is a known issue. Regarding the cookie not being generated, check the Wiki for VCL fix. There are quite a few issues explaining that behavior.
