### ISSUE TITLE
Pagination issue: previous link in pager contains ?p=1 if turpentine is enabled

### ISSUE THREAD

**Issue by rickbakker** [nexcess/magento-turpentine#1397]
Hi guys,

Today i discovered a problem with Turpentine and the pagination or pager on the category pages of Magento. I tested this on a staging environment where i disabled Turpentine by removing the xml-file from /app/etc/modules. When i do so the pager on the category pages is exactly how i want it to be: When you are on page 2 the previous link/url should not contain ?p=1 but just the link to the category page. Now, when i enable turpentine again, the previous link contains ?p=1 all of the sudden, while on page 2. The strange thing is, that when you hover over '1' the link does not contain ?p=1. So the URL on '1' is set correctly, but the 'previous' link URL contains ?p=1.

Anybody have a solution to this problem or do i have to code it manually in the Turpentine extension?

**Comment by miguelbalparda** [comment]
I'm not aware of anyone else having this issue and I find it pretty weird. Any chance this is not caused by Turpentine but maybe to another module you installed lately?

**Comment by rickbakker** [comment]
We have an Amasty plugin that does certain things with the pagination, i guess. But the weird thing is, when i completely disable Turpentine, the issue is gone. When i enable turpentine again, the problem is back. So something is changing when you enable Turpentine. What could it be?

**Comment by miguelbalparda** [comment]
Try to enable Turpetine and disable all the caches but the last 2 from Turpentine in the admin panel and see if that helps.

**Comment by rickbakker** [comment]
It didn't change one bit. It's a staging environment btw, i have all caches disabled all the time. Could it be that certain variables change so that the Amasty extension does not work like it's working without turpentine enabled? I'm just guessing here.

**Comment by miguelbalparda** [comment]
Yes, that might be the case. Also remember that disabling Turpentine and not disabling Varnish won't make any difference. When you say you removed the file, did you stopped Varnish and reconfigured your environment to query apache directly?

**Comment by rickbakker** [comment]
Well this staging environment isn't using Varnish. Only the live site is using that. It's only the extension that is installed.

I discovered this issue on the live environment. I noticed that this problem wasnt present on the staging environment, which i thought was weird, so i thought maybe it has something to do with Turpentine. So i enabled the extension on the staging env and that also brought the same issue to this env. That is why i thought it might be related. Now i'm trying to find out what it can be that changes when enabling Turpentine so i can fix this issue.

Could you maybe point me in the right direction?

**Comment by miguelbalparda** [comment]
Check the XMLs, that is where the magic is happening. Basically what the extension is doing is defining policies for the blocks via XML, I'd say that is a good place to start. Also, read the Wiki since the documentation covers a lot of issues and topics.

**Comment by miguelbalparda** [comment]
Closing for lack of feedback, feel free to comment to reopen.

**Comment by rickbakker** [comment]
Sorry, haven't had the time to work on this issue.

Loading the block as follows does not fix this issue:

                        <block type="page/html_pager" name="product_list_toolbar_pager">
                            <action method="setEsiOptions">
                                <params>
                                    <method>esi</method>
                                    <access>public</access>
                                    <scope>page</scope>
                                    <ttl>0</ttl>
                                    <only_cache_if>empty</only_cache_if>
                                    <registry_keys>
                                        <current_category/>
                                    </registry_keys>
                                </params>
                            </action>
                            <action method="setCacheLifetime"/>
                        </block>

Even if i'm not caching anything (caching disabled in Magento) but have Turpentine enabled, the previous link on page 2 has ?p=1 in it. If i disabled Turpentine the problem goes away.

Is it possible that Turpentine overrides the default pager_html template? It could be that we put a custom  pager_html in our template (that fixes this ?p=1 issue) and that Turpentine overrides that one?

**Comment by rickbakker** [comment]
It's $this->getPreviousPageUrl() that contains ?p=1 all of the sudden when Turpentine is activated.

I have made a kinda hacky fix for this in our template:

                $prevurlpager = $this->getPreviousPageUrl();

                if ($_GET['p'] == "2")
                {
                    $prevurlpager = str_replace("?p=1", "", $prevurlpager);
                }

This works for now. But why does this variable $this->getPreviousPageUrl() only contain ?p=1 when Turpentine is activated ? I can't seem to get that.
