### ISSUE TITLE
Attempting to apply VCL generates error 106 Illegal character in VCL name

### ISSUE THREAD

**Issue by josh-palan** [nexcess/magento-turpentine#1399]
Whenever I attempt to apply the VCL to varnish through either saving a configuration change, or via hitting Apply Varnish Config in Cache Management, I get an error `Failed to apply the VCL to 127.0.0.1:6082: Got unexpected response code from Varnish: 106 Illegal character in VCL name ('1')`

If I continue to hit save or apply, the character changes to a random number each time, until it eventually applies successfully.

**Comment by miguelbalparda** [comment]
That is weird, never heard this before. Can you add some more info about your setup?

**Comment by josh-palan** [comment]
Sure! What info are you looking for?

**Comment by miguelbalparda** [comment]
Your server stack and your software might be a good place to start.

**Comment by miguelbalparda** [comment]
I just found this, might be helpful https://github.com/varnishcache/varnish-cache/issues/2125

**Comment by josh-palan** [comment]
That certainly looks like my issue. It appears to be with Varnish and not Turpentine. This can probably be closed.

**Comment by josh-palan** [comment]
OK just to clarify, this appears to be an issue with version 5.x of Varnish, as the VCL name is required to be valid C. Quoting the linked issue above:

> More precisely, vcl must have names that are valid in C, so they can't
start with a number.

In app\code\community\Nexcessnet\Turpentine\Model\Varnish\Admin.php on line 107, 
```
$vclName = Mage::helper('turpentine/data')
                    ->secureHash(microtime());
```

By changing this to

```
$vclName = 'vcl_' . Mage::helper('turpentine/data')
                    ->secureHash(microtime());
```

I am able to avoid all issues. So this is something that will only really need to be done in the future when working towards varnish v5.x+

**Comment by miguelbalparda** [comment]
Can you please submit this as a PR to the devel branch?

**Comment by josh-palan** [comment]
https://github.com/nexcess/magento-turpentine/pull/1400

**Comment by miguelbalparda** [comment]
Sweet thank you!!
