### ISSUE TITLE
Version4 Configurator overrides a method description

### ISSUE THREAD

**Issue by vladfr** [nexcess/magento-turpentine#1404]
Latest release on Varnish 4.x:

Failed to save the VCL file: Declaration of Nexcessnet_Turpentine_Model_Varnish_Configurator_Version4::_vcl_director_backend() should be compatible with Nexcessnet_Turpentine_Model_Varnish_Configurator_Abstract::_vcl_director_backend($host, $port, $probeUrl = '', $options = Array)

**Comment by miguelbalparda** [comment]
That is weird, those files haven't been changed in a while. Anything in particular you can tell me about your setup?

**Comment by miguelbalparda** [comment]
Sorry I just found the issue and it seems you are right. I'll start working on this now.

**Comment by miguelbalparda** [comment]
A quick fix is to add $descriptor in https://github.com/nexcess/magento-turpentine/blob/master/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php but I still have to debug this some more to see if this breaks something else.

**Comment by vladfr** [comment]
Yup, just a method signature. It's probably used a few times but nothing
major.

I use varnish 4 and adding the new param to the signature in Abstract did
the trick.

**Comment by sprankhub** [comment]
I can confirm this issue. I think #1361 should fix this as well.

**Comment by miguelbalparda** [comment]
This should be fixed in the last release. Thanks!

**Comment by chepchepcirkus** [comment]
Version 0.7.3
Bug Still present
