### ISSUE TITLE
do-not-cache headers are missing

### ISSUE THREAD

**Issue by jeroenvermeulen** [nexcess/magento-turpentine#1409]
When Magento calls `session_start()`, PHP adds these HTTP headers:
```
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
```
This makes the browser refresh the page when you click the browser's **Back** button.
This is necessary to refresh the mini-cart after adding a product to your cart.

When using Turpentine, all these *do-not-cache* headers are not present.
**Problem:** The mini cart is not updated when you press the browser's back button after adding a product to your cart.

**Comment by miguelbalparda** [comment]
This should be fixed by #1410
