### ISSUE TITLE
Affiliate cookie issue

### ISSUE THREAD

**Issue by Nuranto** [nexcess/magento-turpentine#1428]
Hi,

We have an affiliate extension. It is quite simple : the affiliate code is passed via a GET parameter = ?aff=code
Then, the aff code is grabbed by JS (by searching into location global variable), and store in a specific cookie.
Finally, the cookie is grabbed when saving an order, and stored in order table.

So, there should'nt be any problem with varnish, right ? Well it did not for a while... But we just found out that between two server restart (without any change in the code), the cookie seem to have been cached, indeed between those two restarts all orders came with a same affiliate code....

It's back to normal now, but we want to prevent this from happening again.. Do you have any ideas ?

**Comment by miguelbalparda** [comment]
How are you getting the param in the JS file? Can you show me that piece of code?

**Comment by Nuranto** [comment]
`<script>
    function findGetParameter(parameterName) {
        var result = null,
            tmp = [];
        location.search
        .substr(1)
            .split("&")
            .forEach(function (item) {
            tmp = item.split("=");
            if (tmp[0] === parameterName) result = decodeURIComponent(tmp[1]);
        });
        return result;
    }
    var affQueryParam = '<?php echo Mage::getStoreConfig('affiliation/general/query_param') ?>';
    var aff = findGetParameter(affQueryParam);
    var cookieLifeTime = <?php echo intval(Mage::getStoreConfig('affiliation/general/cookie_lifetime')) ?>;
    if(aff) {
        var expDate = new Date();
        expDate.setTime(expDate.getTime() + cookieLifeTime*1000);
        document.cookie='mageaff='+aff+'; expires='+expDate.toUTCString()+'; path=/';
    }
</script>`

**Comment by miguelbalparda** [comment]
Ok cool, thanks! I can see you are using JS to retrieve the URL from the value, so that should not be cached since it is a frontend action. What you can see as cached is everything you are doing with PHP since Varnish can cache and serve those pages directly instead of asking PHP to retrieve it.
Does that make sense for you?

**Comment by Nuranto** [comment]
I know, that's why I did it that way.
And that's why the only thing that could have cause the issue, is the unwanted caching of the cookie itself by varnish, right ?
(On server side, i just use `Mage::getSingleton('core/cookie')->get('mageaff');` which only calls $_COOKIE.)

**Comment by miguelbalparda** [comment]
I'm not that sure, I don't have enough info to say that. What do you mean by "Finally, the cookie is grabbed when saving an order, and stored in order table."? When this is happening? In the success pace or in a PHP controller?

**Comment by Nuranto** [comment]
Via an observer on sales_order_save_before event.

**Comment by miguelbalparda** [comment]
Okey, I don't have enough evidence to say what is the cause of the problem, but logging the affiliate extension in a separated log and try to see how to reproduce this issue might be the best approach. 
I find it quite strange this started and stopped without any change.

**Comment by Nuranto** [comment]
So do I :) I hoped it could match some known problems with turpentine... Thanks for your time
