### ISSUE TITLE
turnpentine 0.7.2 varnish hits miss after customer login

### ISSUE THREAD

**Issue by rameshramachandran84** [nexcess/magento-turpentine#1434]
Hi ,

We are facing an issue related to varnish cache miss after customer login action happens . We are having multi website configuration and we noticed that varnish cache miss is happening each time login action performs . 
For reference i am attaching default.vcl out put 

Please review and let us know .
[default.vcl.txt](https://github.com/nexcess/magento-turpentine/files/1159919/default.vcl.txt)

**Comment by miguelbalparda** [comment]
Hi, what have you tried so far to debug this?
I don't quite understand what you mean, can you add some more details?

**Comment by rameshramachandran84** [comment]
We are having performance issue related cache on our website and we noticed that varnish getting purged intermittently . So part of debugging we enabled the varnish NCSA logs on the webservers . 
We could see that varnish cache hits happening fine for certain time until customer login via frontend . As soon login is successful we are seeing subsequent pages getting cache miss from varnish NCSA logs .

So i have attached the vcl file currently being used on the webserver . Kindly let us know your comments .

**Comment by miguelbalparda** [comment]
I still don't understand most of this issue. When you say Varnish is being purged intermittently do you mean you see some MISS or something else? Also, this is not a plug and play extension, your theme might be interfering with the caching if it is not configured properly. Just in case, are you using SSL for the checkout and customer pages?

**Comment by rameshramachandran84** [comment]
yes you are correct ,we are seeing MISS and also we are using SSL for login,cusotmer  and checkout pages  . At theme level we checked if there any interfering with varnish cache , but we could not find any . 

Thanks

**Comment by miguelbalparda** [comment]
How are you handling Varnish and SSL?

**Comment by rameshramachandran84** [comment]
varnish is running on Port :80 and it hands over request to Nginx running on port 8080 . 

Where as SSL is configured directly on Nginx on  port 443 .

**Comment by miguelbalparda** [comment]
Then why do you expect Varnish to handle secure requests?

**Comment by rameshramachandran84** [comment]
Sorry for the confusion , We are only using varnish in the HTTP request . The cache miss is observed only on HTTP requests . 

Our observation is may be cache MISS is happening while customer login in to website . We were able to replicate this scenario multiple times .

**Comment by miguelbalparda** [comment]
A login operation will always be a miss if it is under a secure URL. Also, most of the times, these kinds of requests even in unsecure sites will be piped because of the action itself (a login should ALWAYS hit the db to compare the entered login details)

**Comment by rameshramachandran84** [comment]
yes , we feel that is correct , but when user logins we noticed that homepage cache gets MISS .Where home page was showing cache HITS before customer logins to website .

**Comment by miguelbalparda** [comment]
Well the might make sense, the page being server is different for logged in users and not logged in users. What happens if you login, you get the first miss and then reload? In that case and if everything is configured correctly, you should a HIT

**Comment by rameshramachandran84** [comment]
yes , intially when customer logs , we reload home page and we noticed its a MISS , then we relaod the home page again and we got cache HIT . So is this expected ?

**Comment by miguelbalparda** [comment]
Yes, technically the first time you visit a page logged in it creates a different bucket and the second time you visit it, you consume that.

**Comment by rameshramachandran84** [comment]
Sorry i am not clear ,can you please provide more information .

Thanks

**Comment by rameshramachandran84** [comment]
Hi @miguelbalparda : So as per your comment above are you referring that this is an expected behaviour .

**Comment by miguelbalparda** [comment]
Yes, that seems to be the case. I'll close this one for now, feel free to add more info to reopen it or just create a separated issue.

**Comment by rameshramachandran84** [comment]
Thanks for the confirmation
