### ISSUE TITLE
Error while load balancing backend configuration saving

### ISSUE THREAD

**Issue by chepchepcirkus** [nexcess/magento-turpentine#1437]
Hello,
Version 0.7.10
The following method **Nexcessnet_Turpentine_Model_Varnish_Configurator_Version4::_vcl_director** 
will execute **_vcl_director_backend** function with arguments in the wrong order.

`$backends .= $this->_vcl_director_backend($host, $port, $prefix . $number, $probeUrl, $backendOptions);`

should be

`$backends .= $this->_vcl_director_backend($host, $port, $probeUrl, $backendOptions, $prefix . $number);`

Function definition :
`protected function _vcl_director_backend($host, $port, $probeUrl = '', $options = array(), $descriptor = 1)`
An error occured while _vcl_director_backend function try to print the variable $descriptor, because $descriptor is not string but an array.

**Comment by miguelbalparda** [comment]
This should be fixed in the latest release, can yo check it?

**Comment by chepchepcirkus** [comment]
Hello,
Release 0.7.3
https://github.com/nexcess/magento-turpentine/blob/master/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Version4.php
line 147 problem is not fix

**Comment by chepchepcirkus** [comment]
Sorry the function definition has been fixed, that's all right
