### ISSUE TITLE
Magento 1.9.3.4 wth default theme

### ISSUE THREAD

**Issue by mikeshield13** [nexcess/magento-turpentine#1443]
Hi,

First thanks for this extension, it's great and it would be very useful If we could set up properly. We installed the latest Magento (1.9.3.4) with sample data, then followed the instructions in the wiki. But there some unclear parts in it.

Varnish: 5.1, Turpentine: 0.7.10 (it's weird, because the latest relase is 0.7.3 at the relase page)

1. I don't need https, so only http. Which software should listen on the port 80? Varnish or Apache?
I've set it up in the following order: Varnish: 80, Apache: 8080. Is it correct?

2. We didn't change anything with theme xmls, we use the default template, but it doesn't work. Varnish cache the cart for pages. Is there a tutorial how can I set it up correctly?

3. As I see the baclklist doesn't work: I added checkout/ to it, and didn't solve anything.

Thanks. :)

**Comment by miguelbalparda** [comment]
Where did you get this module from? The latest release can be downloaded from this repo directly.
1. Correct.
2. https://github.com/nexcess/magento-turpentine/wiki/ESI_Cache_Policy
3. Not really sure what were you expecting, care to add more info?

**Comment by mikeshield13** [comment]
I've installed it via Magento Connect.

1. Thanks.
2. I thought the default ESI policy file works well with the default theme, am I wrong?

**Comment by miguelbalparda** [comment]
I haven't updated them in a while, so I wouldn't take that for granted. This is not a plug and play extension, some changes will be needed for it to work with any theme.

**Comment by miguelbalparda** [comment]
To get the latest version, go to https://www.magentocommerce.com/magento-connect/turpentine-varnish-cache.html and then to the M1 Extension Versions tab. I can see 0.7.3 there

**Comment by mikeshield13** [comment]
![kepernyokep errol 2017-07-28 14-11-47](https://user-images.githubusercontent.com/30526578/28716671-c209d5f4-739e-11e7-801e-62e02962dd40.png)

**Comment by miguelbalparda** [comment]
Ah, it seems they think 0.7.10 > 0.7.3. I'll try to contact Magento to have this sorted. Thanks!

**Comment by mikeshield13** [comment]
You're welcome. How can I create a package from the downloaded repo? I tried "make all", but I get the following error:

> grep -v 'Build Status' README.md | markdown_py -o html5 -f "build/magento-connect-desc-.html"
> /bin/bash: markdown_py: command not found
> Makefile:5: recipe for target 'connect-desc' failed
> make: *** [connect-desc] Error 127

**Comment by miguelbalparda** [comment]
You will have to install all the dependencies to create a package. It might be easier to install this manually instead of using Magento Connect.

**Comment by mikeshield13** [comment]
How can I install it manually?

**Comment by miguelbalparda** [comment]
I strongly suggest you to hire a dev for any development work. If you, for any reason can't do that, [here](https://stackoverflow.com/questions/4874761/installing-magento-plugins-without-using-magento-connect) is a guide.
