### ISSUE TITLE
Disable cache for a block inside a block

### ISSUE THREAD

**Issue by mikeshield13** [nexcess/magento-turpentine#1446]
Hi
I have a block (ownBlock) in header block. How can I completely disable the cache for ownBlock, but only for on the main page?

**Comment by miguelbalparda** [comment]
You can create an ESI policy for the block and set the TTL to 0. What have you tried so far to debug this?

**Comment by mikeshield13** [comment]
I tried the following ESI policy in my local.xml:

```
<default>
...
<reference name="ownBlock">            
    <action method="setEsiOptions">       
        <params>                          
            <access>private</access>      
            <ttl>0</ttl>                  
        </params>                         
    </action>                             
</reference> 
</default>
```

2. try: I tried to use page scope, because it has different content on almost every page. So maybe a different cache for every page would be a better solution, like this:

```
<default>
...
<reference name="ownBlock">            
    <action method="setEsiOptions">       
        <params>                          
            <access>private</access>      
            <scope>page</scope>
        </params>                         
    </action>                             
</reference> 
</default>
```

None of them work.

**Comment by miguelbalparda** [comment]
Is your block being contained by another block with a different ESI policy?

**Comment by mikeshield13** [comment]
Yes, because it is in the header block.

**Comment by mikeshield13** [comment]
I moved it out from header, and created a separate block, it solved the problem. :)
