### ISSUE TITLE
Warning: Declaration with v0.7.3 and varnish v4.1.5

### ISSUE THREAD

**Issue by mage1111** [nexcess/magento-turpentine#1458]
Hello
I am using varnish 4.1.5 and turpentine last version. But still received this error when saved the Turpentine > Caching Options

2017-10-22T12:23:41+00:00 ERR (3): Warning: Declaration of Nexcessnet_Turpentine_Model_Varnish_Configurator_Version4::_vcl_director_backend($host, $port, $descriptor, $probeUrl = '', $options = Array) should be compatible with Nexcessnet_Turpentine_Model_Varnish_Configurator_Abstract::_vcl_director_backend($host, $port, $descriptor = '', $probeUrl = '', $options = Array)  in /var/www/webroot/ROOT/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Version4.php on line

**Comment by michbsd** [comment]
Seeing the same with 0.7.2 
have also tried downgrading to varnish 4.0.3

**Comment by michbsd** [comment]
Here's the stack trace:

Strict Notice: Declaration of Nexcessnet_Turpentine_Model_Varnish_Configurator_Version4::_vcl_director_backend() should be compatible with that of Nexcessnet_Turpentine_Model_Varnish_Configurator_Abstract::_vcl_director_backend()  in /data/www/magento/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Version4.php on line 194

#0 /data/www/magento/lib/Varien/Autoload.php(93): mageCoreErrorHandler(2048, 'Declaration of ...', '/data/www/magen...', 194, Array)
#1 /data/www/magento/lib/Varien/Autoload.php(93): Varien_Autoload::autoload()
#2 [internal function]: Varien_Autoload->autoload('Nexcessnet_Turp...')
#3 [internal function]: spl_autoload_call('Nexcessnet_Turp...')
#4 /data/www/magento/app/code/core/Mage/Core/Model/Config.php(1204): class_exists('Nexcessnet_Turp...')
#5 /data/www/magento/app/Mage.php(432): Mage_Core_Model_Config->getModelInstance('turpentine/varn...', Array)
#6 /data/www/magento/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php(46): Mage::getModel('turpentine/varn...', Array)
#7 /data/www/magento/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin.php(131): Nexcessnet_Turpentine_Model_Varnish_Configurator_Abstract::getFromSocket(Object(Nexcessnet_Turpentine_Model_Varnish_Admin_Socket))
#8 /data/www/magento/app/code/community/Nexcessnet/Turpentine/controllers/Varnish/ManagementController.php(182): Nexcessnet_Turpentine_Model_Varnish_Admin->getConfigurator()
#9 /data/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Nexcessnet_Turpentine_Varnish_ManagementController->getConfigAction()
#10 /data/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('getConfig')
#11 /data/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(177): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 /data/www/magento/app/code/core/Mage/Core/Model/App.php(304): Mage_Core_Controller_Varien_Front->dispatch()
#13 /data/www/magento/app/Mage.php(596): Mage_Core_Model_App->run(Array)
#14 /data/www/magento/index.php(129): Mage::run('xxxx', 'store')
#15 {main}

**Comment by mage1111** [comment]
Hello 
I fixed problem like this:
Nexcessnet\Turpentine\Model\Varnish\Configurator\Version4.php
Line 168 changed 
Old: protected function _vcl_director_backend($host, $port, $descriptor, $probeUrl = '', $options = array()) {
New: protected function _vcl_director_backend($host, $port, $descriptor, $probeUrl, $options) {

Nexcessnet\Turpentine\Model\Varnish\Configurator\Abstract.php
Line 714
Old: protected function _vcl_director_backend($host, $port, $descriptor = '', $probeUrl = '', $options = array()) {
New: protected function _vcl_director_backend($host, $port, $descriptor, $probeUrl, $options) {

Have nice day
