### ISSUE TITLE
Magento Connect / turpentine no longer listed

### ISSUE THREAD

**Issue by michbsd** [nexcess/magento-turpentine#1465]
It seems turpentine is no longer listed/available via Magento Connect ?? 

http://www.magentocommerce.com/magento-connect/turpentine-varnish-cache.html is just redirecting to the front page .. 

Is it normal?

**Comment by michbsd** [comment]
Any news ?

**Comment by ADDISON74** [comment]
Magento Connect was closed since September 2017. Just Google some news about it. It is not Turpentine Team Fault.
