### ISSUE TITLE
Invalid method Mage_Cms_Block_Block::addLink(Array ...

### ISSUE THREAD

**Issue by ulicodex** [nexcess/magento-turpentine#1477]
With Varnish version 3.0.7, Turpentine 0.7.3 and Magento 1.9.1.0 we get the following error, referring to our hoster the configuration is ok.

There has been an error processing your request
Invalid method Mage_Cms_Block_Block::addLink(Array
(
    [0] => Sitemap
    [1] => https://www.#####.com/catalog/seo_sitemap/category/
    [2] => Sitemap
)
)
Trace:
                #0 [internal function]: Varien_Object->__call('addLink', Array)
#1 [internal function]: Mage_Cms_Block_Block->addLink('Sitemap', 'https://www.####…‘, 'Sitemap')
#2 /var/www/share/#####.com/magento/htdocs/app/code/core/Mage/Core/Model/Layout.php(348): call_user_func_array(Array, Array)
#3 /var/www/share/#####.com/magento/modules/vendor/layoutconditions/app/code/local/Aoe/LayoutConditions/Model/Layout.php(63): Mage_Core_Model_Layout->_generateAction(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#4 /var/www/share/#####.com/magento/htdocs/app/code/core/Mage/Core/Model/Layout.php(214): Aoe_LayoutConditions_Model_Layout->_generateAction(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/share/#####.com/magento/modules/vendor/layoutconditions/app/code/local/Aoe/LayoutConditions/Model/Layout.php(26): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#6 /var/www/share/#####.com/magento/modules/local/Turpentine/app/code/community/Nexcessnet/Turpentine/controllers/EsiController.php(254): Aoe_LayoutConditions_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#7 /var/www/share/#####.com/magento/modules/local/Turpentine/app/code/community/Nexcessnet/Turpentine/controllers/EsiController.php(101): Nexcessnet_Turpentine_EsiController->_getEsiBlock(Object(Varien_Object))
#8 /var/www/share/#####.com/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Nexcessnet_Turpentine_EsiController->getBlockAction()
#9 /var/www/share/#####.com/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('getBlock')
#10 /var/www/share/#####.com/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/share/#####.com/magento/htdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/share/#####.com/magento/htdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/share/#####.com/magento/htdocs/index.php(87): Mage::run('', 'store')
#14 {main}

Any idea?

Kindest regards
Uli

**Comment by mabigo** [comment]
Try to open same page directly from apache. (port 8080 or whatever)  I bet it has nothing to do with turpentine.

**Comment by ulicodex** [comment]
Thanks for the quick response. What would you expect to see when I connect directly to apache? I'm getting "Secure connection failed".

**Comment by mabigo** [comment]
Normally you get the same page as if no Varnish were in front of it.  But it depends on your configuration. Maybe your Server uses SSL Offloading with ngnix. Check ports in turpentine config

**Comment by ulicodex** [comment]
**Solved:**
Thanks for your help. **One of our blocks had the same name as a magento block**. This caused turpentine/varnish to error on that block.

**Comment by Webmasterei** [comment]
Same thing here. For me it was  a rename from 
`footer_links` to `footer_links_1`
