### ISSUE TITLE
Ban issues with Magento BLOCK_HTML cache enabled

### ISSUE THREAD

**Issue by raulvian** [nexcess/magento-turpentine#1483]
This is Magento 1.9 with Varnish 4.0
We are experiencing slowness with checkout/* web requests, and (strangely) they seem to be solved by disabling **Magento BLOCK_HTML** cache... with that cache enabled slowness raises gradually, as var/cache content grows

Tracing the issue, the only explanation seems to be ESI blocks purge when some Magento checkout events are fired, such as sales_quote_save_after, etc...

Any ideas?

**UPDATE**
However, this makes ESI block functionality stop working... so it's not a valid workaround

**Comment by Nuranto** [comment]
Hello @raulsinapsis 
I have similar issues. How did you fixed this ?
