### ISSUE TITLE
vcl.inline Syntax Error: Missing '"'

### ISSUE THREAD

**Issue by webtekindo** [nexcess/magento-turpentine#1488]
Magento 1.13.1
Varnish 4.1.9 

After install of Turpentine, and Apply Varnish Config or save Varnish Options, we get an error:

Failed to apply the VCL to 127.0.0.1:6082: Got unexpected response code from Varnish: 100 Unknown request. Type 'help' for more info. Syntax Error: Missing '"'

In the turpentine.log:

`2018-04-15T06:52:54+00:00 DEBUG (7): TURPENTINE: Error on Varnish command: "vcl.inline" "vcl_70c1309a9792486fd9ea49a3aed7c01cc8dee093e7416a09289770e714fb32b7" "vcl 4.0;\nC{\n#include <stdlib.h>.........
`

We already add "-p vcc_allow_inline_c=on" and we test manually to add vcl.inline with minimal VCL and it works, but it seems there's some error in the vcl turpentine syntax.

If we use the generated var/default.vcl directly in DAEMON_OPTS it also works, so the problem is vcl.inline and turpentine VCL syntax

How can we solve that?

**Comment by thiagolima-bm** [comment]
same problem here

**Comment by miguelbalparda** [comment]
This is fixed in a subsequent version. Closing for now, feel free to reopen.
