### ISSUE TITLE
Varnish v4.1.10+ ban request not working Error Unable to detect varnish version

### ISSUE THREAD

**Issue by ngongoll** [nexcess/magento-turpentine#1490]
all ban request will end with error Unable to detect varnish version when subversion of varnish 4.1 has 2 digits.

you can fix it by change the line 91 in
app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php
to

const REGEXP_VARNISH_VERSION = '/^varnish\-(?P<vmajor>\d)\.(?P<vminor>\d)\.(?P<vsub>\d{1,2}) revision (?P<vhash>[0-9a-f]+)$/';

**Comment by notimplementedyet** [comment]
i wouldn't change it that way. 
who tells you there will be no two digit minor version or three digit version sub?

if limiting the numbers i would go for something like this:
const REGEXP_VARNISH_VERSION = '/^varnish-(?P\d{1,2}).(?P\d{1,3}).(?P\d{1,4}) revision (?P[0-9a-f]+)$/';

but my prefered regex would just be just not limiting the numbers:
const REGEXP_VARNISH_VERSION = '/^varnish-(?P\d+).(?P\d+).(?P\d+) revision (?P[0-9a-f]+)$/';

**Comment by sprankhub** [comment]
Are you sure this works @ngongoll? Later, after the `preg_match`, the `vmajor` and `vminor` group is referenced, which you deleted:

https://github.com/nexcess/magento-turpentine/blob/e948e9f609eeb36514817d7d1938e003335820af/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php#L373-L374

Besides of that, would you mind creating a pull request?

**Comment by notimplementedyet** [comment]
@sprankhub yes it works but it's an suboptimal fix ;-)

**Comment by notimplementedyet** [comment]
created a pull request https://github.com/nexcess/magento-turpentine/pull/1491

**Comment by Flyingmana** [comment]
(comment out of the off:) Could please someone do a follow up PullRequest refactoring this to not use a regex anymore? PHP has perfectly find functions to compare versions, which are easier to read and change then a regex.

**Comment by dunkla** [comment]
Any updates on this?

**Comment by dunkla** [comment]
at the cost of repeating myself: any updates on this?

**Comment by miguelbalparda** [comment]
This should be fixed in devel by #1491, care to check?

**Comment by dunkla** [comment]
Looks good to me.
