### ISSUE TITLE
Varnish 6 supported?

### ISSUE THREAD

**Issue by darnux** [nexcess/magento-turpentine#1492]
I could not find any hint in the documentation so I am creating this issue.
Varnish 6 introduces UDS ( https://varnish-cache.org/docs/6.0/whats-new/changes-6.0.html ) so I am wondering if this plugin also supports Varnish 6. 
In fact their should not be much difference to 4.1.x

At a first glance it looks like the plugin is working.
I had to change the following setting to get it working: 

* Remove "cli_buffer" from start options.

This option was deprecated since Varnish 5.2 and was removed with Varnish 6.0.

> https://varnish-cache.org/docs/5.2/reference/varnishd.html#ref-param-cli-buffer
> 
> DEPRECATED: This parameter is ignored. Memory for the CLI command buffer is now dynamically allocated.
>

**Comment by Nuranto** [comment]
Hi @darnux 

Have you more intel ? Still no trouble with this extension and Varnish6 ?
Did you see significant performance gain versus Varnish4 ?

**Comment by sprankhub** [comment]
I would be interested in that as well. Could you share your experiences @darnux? Thanks!

**Comment by miguelbalparda** [comment]
Varnish 6 is not supported for now, will scope and see if it's doable.

**Comment by jacquesbh** [comment]
Hi @miguelbalparda :)

On Debian Buster, Varnish 6 is mandatory.
Is that possible to update the module considering this new information?

Thank you so much :)

**Comment by mpolinowski** [comment]
Hi,
I couldn't find any documentation on this anywhere. So I gave it a try and so far it seems to work:

https://mpolinowski.github.io/magento-2-and-varnish-6

**Comment by fballiano** [comment]
why was this closed?
