### ISSUE TITLE
ESI processing not enabled - how debug?

### ISSUE THREAD

**Issue by jeremydevos** [nexcess/magento-turpentine#1493]
Hello,

I have a Magento Enterprise 1.14.3.1 and I have "ESI processing not enabled" errors that are displayed.
I can not find any error in the Magento logs and in the turpentine.log everything seems OK.
A varnishlog does not give any additional information.

How to debug this problem?

Can you explain : ?

// change the block's template to the stripped down ESI templateT
             switch ($ esiOptions [$ methodParam]) {
                 case 'ajax':
                     $ blockObject-> setTemplate ('turpentine / ajax.phtml');
                     break;
                 'esi' box:
                 default:
                     $ blockObject-> setTemplate ('turpentine / esi.phtml');
                     // flag request for ESI processing
                     Mage :: register ('turpentine_esi_flag', true, true);
             }

Why is esi.phtml called?

Thank you
Jérémy

**Comment by michael-bouvy** [comment]
Had this issue several times.

Is the handshake token properly transmitted by Varnish to your backend?

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
