### ISSUE TITLE
Incompatibility with aheadworks AJAX Cart Pro

### ISSUE THREAD

**Issue by arosenhagen** [nexcess/magento-turpentine#150]
We experience problems with aheadworks AJAX Cart Pro Extension (http://ecommerce.aheadworks.com/magento-extensions/ajax-cart-pro.html). Items added to the cart are not "saved" correctly (reloading the page shows blank cart_sidebar). The product gets added to the magento cart properly.

**Comment by bgui** [comment]
@arosenhagen did you find a fix for this?
