### ISSUE TITLE
Missing/flashing header, Javascript for Cart Prototype error? not able to add items to cart

### ISSUE THREAD

**Issue by pieterjanliekens** [nexcess/magento-turpentine#1529]
I've got my site up and running.
https://www.two-store.be

- Disabling ESI blocks results in other clients seeing the cart contents.
- Enabling using method ESI, gives me no header...
- Enabling and using AJAX method it gives me a flashing header and following error:

```
ONE.Widget  Uncaught TypeError: ONE.Widget is not a constructor
    at eval (eval at <anonymous> (prototype.js?v=1520107635:612), <anonymous>:2:5)
    at prototype.js?v=1520107635:612
    at prototype.js?v=1520107635:865
    at prototype.js?v=1520107635:825
    at Array.forEach (<anonymous>)
    at Array.each (prototype.js?v=1520107635:824)
    at Array.collect (prototype.js?v=1520107635:864)
    at String.evalScripts (prototype.js?v=1520107635:612)
    at Function.<anonymous> (prototype.js?v=1520107635:391)
    at prototype.js?v=1520107635:416
```
Resulting in a broken add to cart button...

This is my header part in Turpentine.xml
```
        <reference name="header">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <flush_events>
                        <wishlist_item_save_after/>
                        <wishlist_item_delete_after/>
                        <checkout_cart_product_add_after/>
                        <checkout_cart_update_items_after/>
                        <checkout_cart_product_update_after/>
                        <sales_quote_save_after/>
                        <controller_action_layout_render_before_catalogsearch_result_index />
                        <persistent_session_expired/>
                    </flush_events>
  		   <method>esi</method>
                </params>
            </action>
        </reference>
```

**Comment by pieterjanliekens** [comment]
[system.log](https://github.com/nexcess/magento-turpentine/files/2777078/system.log)
I've added the system log and 3 XML files that might be interfering. If interested I will also upload the used VCL.


[onethemes_ajaxcart.xml.txt](https://github.com/nexcess/magento-turpentine/files/2777083/onethemes_ajaxcart.xml.txt)
[checkout.xml.txt](https://github.com/nexcess/magento-turpentine/files/2777084/checkout.xml.txt)
[turpentine_esi.xml.txt](https://github.com/nexcess/magento-turpentine/files/2777085/turpentine_esi.xml.txt)
[default.vcl.txt](https://github.com/nexcess/magento-turpentine/files/2777086/default.vcl.txt)

**Comment by pieterjanliekens** [comment]
Using Aoe Templatehints I was able to look at the result and 
catalog.topnav.menu
Class:
OneThemes_Bewear_Block_Mainmenu_Menu
Module:
OneThemes_Bewear
Template:
frontend/bewear/bewearst2/template/onethemes/mainmenu/top.phtml
Cache-lifetime:
forever
Cache-key:
566a7035e0cbdad8640bdf77f34c2e32b2a2939e
Cache-key-info:
CATALOG_NAVIGATION, 5, bewear, bewearst2, 0, onethemes/mainmenu/top.phtml, catalog.topnav.menu, 1/2/5, 1/2/5, c5fb3d752e97e58cb684552209aba6e7
Tags:
catalog_category,store_group,block_html
Methods:
OneThemes_Bewear_Block_Mainmenu_Menu:
Mage_Catalog_Block_Navigation:
getCurrenCategoryKey()
getStoreCategories()
getCurrentChildCategories()
isCategoryActive($category)
getCategoryUrl($category)
drawItem($category, $level, $last)
getCurrentCategory()
getCurrentCategoryPath()
drawOpenCategoryItem($category)
renderCategoriesMenuHtml($level, $outermostItemClass, $childrenWrapClass)
Mage_Core_Block_Template:
(skipping)
Mage_Core_Block_Abstract:
(skipping)
Block nesting:
top.menu (alias: topMenu)
header
root

**Comment by miguelbalparda** [comment]
This has been reported multiple times, have you checked the closed issues? It's very environment and theme specific and most likely not caused by Turpentine.

**Comment by pieterjanliekens** [comment]
I think it's because the block doesn't extend a mage_core_block. Is that possible? Ohh.. And yes. I've read through them all to be honest. But still can't find my way around the issue.

**Comment by miguelbalparda** [comment]
That has been the case sometimes, have you tried changing the block in question to extend from that class?

**Comment by pieterjanliekens** [comment]
No I haven't. What would be the preferred block to be extended for the top cart?

**Comment by miguelbalparda** [comment]
From the [wiki](https://github.com/nexcess/magento-turpentine/wiki/ESI_Cache_Policy#what-is-an-esi-cache-policy)

> Only blocks that inherit from the Mage_Core_Block_Template class may have caching policies.

**Comment by miguelbalparda** [comment]
Will close this one after 2 weeks of inactivity. Feel free to reopen if you have anything else to add. Thanks!
