### ISSUE TITLE
Is there a support for Varnish 5.2.1 ?

### ISSUE THREAD

**Issue by kansoft** [nexcess/magento-turpentine#1533]
Is there a support for Varnish 5.2.1 ?

I have that version of varnish installed on server and when save settings in varnish module in magento i get that error (version of Varnish set to Auto):
**Unsupported Varnish version**

When I change version of Varnish in settings to 4.1.x i get that error:
**Failed to apply the VCL to 127.0.0.1:6082: Varnish socket write error: 8192 != 11325**

Is there a chance to get that works?

**Comment by miguelbalparda** [comment]
It's not being actively worked atm but feel free to submit a PR. It looks like the VCL for 4.0 should work for 5.0
