### ISSUE TITLE
No headers or logs

### ISSUE THREAD

**Issue by Doyley3731** [nexcess/magento-turpentine#1534]
Hello all

I've been pulling my hair out trying to get Varnish working.  I've got it to a state where Varnish is now working on the server and Turpentine is configured so I can click "Apply Varnish Config" and it works correctly.  The site is not giving me the varnish headers though so I'm pretty sure it's not working.
There is nothing in turpentine.log even though logging is enabled.
This is nothing in the varnish log either.
I'm at a loss now as what to check next.  Is there anything I can do to check where I am going wrong?

Thanks

**Comment by miguelbalparda** [comment]
There's a number of reasons why your setup might not be working and most of them are not related to Turpentine. What have you tried so far? How is your server setup? Have you checked open and closed issues and the wiki first?

**Comment by miguelbalparda** [comment]
From [here](https://github.com/nexcess/magento-turpentine/blob/master/app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl#L447), most of the Varnish headers are removed if not in debug mode. Ty @ChrisOrlando for pointing this out.

**Comment by miguelbalparda** [comment]
Closing for lack of response, feel free to reopen if anything changes.
