### ISSUE TITLE
When this extension available for magento 2?

### ISSUE THREAD

**Issue by ask694** [nexcess/magento-turpentine#1537]
We are like to use this for magento 2. Help us by making this available for Magento 2

**Comment by magenx** [comment]
magento 2 already have varnish built in,
just generate default.vcl config

do you have magento 2 installed? check admin options...
https://devdocs.magento.com/guides/v2.3/config-guide/varnish/config-varnish-magento.html

**Comment by ChrisOrlando** [comment]
There are no plans at this time to develop a version of this extension for Magento 2. Magento 2 has native Varnish support as @magenx mentioned.
