### ISSUE TITLE
some users can't login, but some can

### ISSUE THREAD

**Issue by nomadph** [nexcess/magento-turpentine#169]
Hi,

When I enable varnish-turpentine, some users complain that they suddenly can't login to their existing account on our magento store, while others have no problem logging in at all.

I've tried flushing magento cache, and flush cache storage, but same problem persist.

The users that can't login say that when they enter their login email and password and clicks the submit button, the login page just reloads itself (no error or anything).

When we turn off varnish-turpentine, all is well and no customers complain about not being able to login. Please advice on where to look or if we're missing something.

**Comment by harveychow** [comment]
This might have to do with my solution here: https://github.com/nexcess/magento-turpentine/issues/222

**Comment by erichileman** [comment]
We noticed this problem as well.  What we found was customers/admins were logging in using to specific pages.  Having them clear cache/cookies and using proper account login urls fixed the problems for those users.
