### ISSUE TITLE
Failed to apply the VCL

### ISSUE THREAD

**Issue by ajardin** [nexcess/magento-turpentine#170]
Hello everyone,

I just updated this module with the 0.5.3 release. And I encounter the following error when I try to apply the configuration to my Varnish instance.

```
Failed to apply the VCL to xx.x.xx.xx:xxxx: Got unexpected response code from Varnish: 106 Message from VCC-compiler: Expected string variable or constant (input Line 184 Pos 17) set req.hash += ("s=" + req.http.X-Varnish-Store); ----------------#--------------------------------- Running VCC-compiler failed, exit 1 VCL compilation failed
```

We currently use Magento Enterprise 1.11.2.0 with Varnish 2.1 and we never had this problem with the version 0.5.2. Before this update, everything worked perfectly.

At first glance, it would be a simple problem when concatenating some parameters. 

In **version-2.vcl** at line **240**:

```
set req.hash += "s=" req.http.X-Varnish-Store "&c=" req.http.X-Varnish-Currency;
```

Thanks.

**Comment by spanakorizo** [comment]
hi, almost same problem : centos7 varnish4 (turpentine v4fork)
Failed to apply the VCL to 127.0.0.1:6082: Got unexpected response code from Varnish: 106 Message from VCC-compiler: Inline-C not allowed ('input' Line 2 Pos 1) C{ ## Running VCC-compiler failed, exited with 2 VCL compilation failed
fixed allready -p cli_buffer=16384 and now after press :apply varnish config in admin i get this error
cannot install varnish3 on centos7 so ?
