### ISSUE TITLE
Varnish admin socket timeout

### ISSUE THREAD

**Issue by jimjamdev** [nexcess/magento-turpentine#179]
Hey, I'm looking for some help with this extension.

I've already read the other posts, but can't work it out.

Here's my /etc/default/varnish (I've removed all the comments)

``` bash
START=yes
NFILES=131072
MEMLOCK=82000
DAEMON_OPTS="-a 10.0.0.253:80 \
             -T localhost:9831 \
             -f /etc/varnish/default.vcl \
             -S /etc/varnish/secret \
             -s malloc,512m"
```

And here's my /etc/varnish/default.vcl

``` vcl
backend default {
  .host = "10.0.0.253";
  .port = "8090";
}


backend admin {
  .host = "10.0.0.253";
  .port = "8091";
  .first_byte_timeout = 18000s;
  .between_bytes_timeout = 18000s;
}


acl purge {
  "localhost";
  "127.0.0.1";
}
```

```
Caching Options > Backend:

Host: localhost
Port: 9831
```

```
Varnish Options > Servers

Version: 3.0x
Server List: 10.0.0.253:8090
Auth Key: xxxxxxxx-c1ba-483c-bb35-xxxxxxxxxxxa\n
Config file location: {{root_dir}}/var/default.vcl
```

I'm banging my head against the desk here trying to get it to work, but just keep getting the error: `Failed to apply the VCL to 10.0.0.253:8090: Varnish admin socket timeout`

What am I doing wrong?

**Comment by magentoguru** [comment]
Hello,
NGINX: 80/443
VARNISH: 8081
Apache: 8080

Here is the configuration:

    NGINX:

upstream varnish {
server 127.0.0.1:8081;
}

limit_req_zone $binary_remote_addr zone=one:10m rate=1r/s;

server {

listen 10.1.1.*7:80 default;

server_name my.com www.my.com;

location / { 
    proxy_read_timeout 300; 
    proxy_pass http://varnish;  
    proxy_set_header Host $http_host;  
    proxy_set_header X-Forwarded-Host $http_host;  
    proxy_set_header X-Real-IP $remote_addr;  
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  
    proxy_set_header HTTPS "";  
    proxy_hide_header X-Varnish;  
    proxy_hide_header Via; 
    add_header "X-UA-Compatible" "IE=Edge,chrome=1";
}  

}

server {

listen 443 ssl;

server_name my.com www.my.com;

ssl                  on;  
gzip                 on;
gzip_min_length 1000;

gzip_proxied    expired no-cache no-store private auth;
gzip_types      text/plain application/xml text/css application/x-javascript;
keepalive_timeout   70;
ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
#ssl_ciphers         AES128-SHA:AES256-SHA:RC4-SHA:DES-CBC3-SHA:RC4-MD5;
ssl_certificate     /etc/ssl/private/my.nginx.crt;
ssl_certificate_key /etc/ssl/private/my.nginx.crt;
ssl_session_cache   shared:SSL:10m;
ssl_session_timeout 10m;  



location / {  
    proxy_read_timeout 300;  
    proxy_pass http://varnish;  
    proxy_set_header Host $http_host;  
    proxy_set_header X-Forwarded-Host $http_host;  
    proxy_set_header X-Real-IP $remote_addr;  
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  
    proxy_set_header HTTPS "on";  
    proxy_hide_header X-Varnish;  
    proxy_hide_header Via;  
}  

    Varnish:

/etc/default/varnish
DAEMON_OPTS="-a :8081 \
-T localhost:6082 \
-f /etc/varnish/default.vcl \
-S /etc/varnish/secret \
-t 120 \
-s malloc,256m"

/etc/varnish/default.vcl

backend default {
.host = "127.0.0.1";
.port = "8080";
}

    Apache:

etc/apache2/ports.conf

Listen 127.0.0.1:8080

/etc/apache2/sites-enabled/000-default.conf:


ServerAdmin info@my.com
ServerAlias my.com
DocumentRoot /var/www/my/
SetEnvIf HTTPS on HTTPS=on

<IfModule mod_php5.c>
    php_value display_errors on
</IfModule>
Options -Indexes
    <Directory /var/www/my>
        AllowOverride All
    </Directory>

I still don't get my pages cached. Please help!

Thanks
