### ISSUE TITLE
menu and some blocks on my website are disappeared & website not showing a speed increase.

### ISSUE THREAD

**Issue by ogletech** [nexcess/magento-turpentine#203]
Dear Sir,
I did install Turpentine and varnish.
After having all required configurations
Turpentine communicating easily with varnish and creating .vcl
But website not showing a speed increase.
Note: I am installing turpentine on http://www.europafashions.co.uk
Best Regards,

**Comment by dartanandan** [comment]
<registry_keys>
    <current_category/>
<registry_keys>

Hi aheadley can you explain the above code, actually the <register_key></register_key> end tag is not closed

**Comment by dartanandan** [comment]
<registry_keys>
    <current_category/>
<registry_keys>

Hi can you explain the above code because <registry_keys></registry_keys> end tag is not closed.

**Comment by diwakert** [comment]
In case someone stumbles here. I have just fixed Smartwave_Megamenu that comes with Smartwave Porto Magento theme is by introducing the same _toHtml method as described above. In my case the patch was:

```
protected function _toHtml() {
        if( Mage::getStoreConfig('megamenu/general/enabled') &&
                $this->getNameInLayout() == 'catalog.topnav' ) {
            $this->setTemplate('smartwave/megamenu/html/topmenu.phtml');
        }
        return parent::_toHtml();
    } 
```

**Comment by jisaacFL** [comment]
diwakert can you advise where I should place your suggested code.That is the theme I am using and issue I am facing.

**Comment by diwakert** [comment]
@jisaacFL,  it's Smartwave/Megamenu/Block/Navigation.php

Also I had an issue where Topmenu.php and Toggle.php had different config checks in place. Toggle.php had getStoreConfig(megamenu/general/enable) and Toggle.php had getStoreConfig(megamenu/general/enabled).

Check if your package has this correct.

**Comment by mmkolev** [comment]
@diwakert I have the same problem with Megamenu and Porto theme. Can you help me, please.

**Comment by kimlongyakura** [comment]
@diwakert @mmkolev I am having same problem.  I can't find _toHhtml function in Navigation.php so I added the code at bottom of the page,  Now my page turns completly white.  IF I disable ESI Block cache, everything work fine, but I leave it on, the navigation bar will be all floating all over the page.

**Comment by yuukooagency** [comment]
In case anyone is still blocked with Porto theme Megamenu not displaying, you can add this in local.xml under :
`<reference name="top.menu">`

```            
<reference name="catalog.topnav">
   <action method="setTemplate" ifconfig="megamenu/general/enable" condition="1"> 
     <template>smartwave/megamenu/html/topmenu.phtml</template>
   </action>
</reference>
```
