### ISSUE TITLE
Prices per customer

### ISSUE THREAD

**Issue by rvr31** [nexcess/magento-turpentine#226]
Hello,

Im having a little issue here with varnish.
We have a shop with customers who have special prices for product.
This is a special customer group.

The problem now is that they see the normal product prices cause of varnish.

Is there some sort of cookie i can set for them upon login that makes sure they dont get cached pages and their page's wont be cached? 
I know how to set a cookie on login, i just dont know if there is something for this problem?

Thanks alot!
Cheers!

**Comment by nbijl** [comment]
Does the xml work for both the category and the product pages?
