### ISSUE TITLE
Useful Info: Block /turpentine/ in robots.txt

### ISSUE THREAD

**Issue by vitalized** [nexcess/magento-turpentine#235]
I've just launched a website. I've  been checking for potential indexing issues with Google and found that Google is indexing ESI blocks.  I thought someone on here may find it useful to know that you should block /turpentine/ in the robots.txt file.

User-agent: *
Disallow: /turpentine/

If you're worried Google may have already crawled and indexed ESI block on your website you can check the index by doing a search for:

site:YourWebsite.com/turpentine/

If you find Google has indexed them then use the Google Webmaster Tools to remove the  /turpentine/ directory

There are many other directories & Magento you'll probably want to block as well. Here's a copy of my robots.txt if you're interested:

User-agent: *
Disallow: /404/
Disallow: /app/
Disallow: /manage/
Disallow: /cgi-bin/
Disallow: /downloader/
Disallow: /includes/
Disallow: /js/
Disallow: /lib/
Disallow: /magento/
Disallow: /pkginfo/
Disallow: /report/
Disallow: /skin/
Disallow: /stats/
Disallow: /var/
Disallow: /catalog/product_compare/
Disallow: /catalog/category/view/
Disallow: /catalog/product/view/
Disallow: /catalog/product/gallery/
Disallow: /catalogsearch/
Disallow: /checkout/
Disallow: /control/
Disallow: /contacts/
Disallow: /customer/
Disallow: /customize/
Disallow: /newsletter/
Disallow: /poll/
Disallow: /review/
Disallow: /sendfriend/
Disallow: /tag/
Disallow: /wishlist/
Disallow: /index.php
Disallow: /cron.php
Disallow: /cron.sh
Disallow: /error_log
Disallow: /install.php
Disallow: /LICENSE.html
Disallow: /LICENSE.txt
Disallow: /LICENSE_AFL.txt
Disallow: /STATUS.txt
Disallow: /get.php
Disallow: /.js$
Disallow: /?___from_store=
Disallow: *___from_store=
Disallow: /?mode=
Disallow: /?limit=
Disallow: /?dir=
Disallow: /.css$
Disallow: /.php$
Disallow: /?p=*&
Disallow: /?SID=
Disallow: /?cat=
Disallow: /.php$
Disallow: /rss*
Disallow: /delivery-returns/
Disallow: /shopper_home/
Disallow: /sitemap/
Disallow: /privacy-policy-cookie-restriction-mode/
Disallow: /home/
Disallow: /sale_items/
Disallow: /ajax/
Disallow: /turpentine/
Sitemap: http://YourWebsite.co.uk/sitemap.xml

**Comment by aricwatson** [comment]
Added to wiki.
