### ISSUE TITLE
strange experience with very large URL parameters

### ISSUE THREAD

**Issue by donnie-darko** [nexcess/magento-turpentine#238]
Hi,
In MailChimp campaign newsletters the URL parameters are very long, like this one:
`?utm_source=THIS+TEST+NEWSLETTER&utm_campaign=256b7777e7a-newsletter201313&utm_medium=email&utm_term=0_80b5c23cde-256b711e7a-%5BLIST_EMAIL_ID%5D&gooal=eyJjaWQiOiIyNTZiNzExZTdhIiwidGFnIjoibmV3c2xldHRlcjIwMTMwNiIsInVpZCI6IjQ1MTRlYjQxNDg5NGExODczNmMzMDQ2YWQifQ%3D%3D%7CY3Npa29zLmFrb3NAcHJldHR5bGl0dGxlL777&mc_cid=256b711777&mc_eid=%5BUNIQID%5D`
I recently updated turpentine in my live system to 0.5.4 so I haven't got enough time to test it fully so I run into these errors in the landing page with the above URL parameters today morning after the newsletter was sent to every subscriber:
`Invalid URI supplied
/srv/www/www.example.com/magento/lib/Zend/Uri.php(143): Zend_Uri_Http->__construct('http', '//www.example`
So I stop varnish and bring nginx to front (port 80) to disable turpentine.
Then I tried this URL parameters on my development environment and in the first few times I can reproduce the error. I have found out that the gooal parameter cause the problem. URLs without the very long gooal parameter works, with gooal parameters doesn't. But after a few attempts the URLs with gooal parameters suddenly start working and I don't know why.
Can somebody confirm this weird issue?

**Comment by luigifab** [comment]
For us, I have `if (!empty($uri)) $uri = str_replace('|', '%7C', $uri);` to fix the same problem:

https://github.com/nexcess/magento-turpentine/blob/c670a492a18cf495d87699e0dbd712ad03fd84ad/app/code/community/Nexcessnet/Turpentine/Model/Dummy/Request.php#L40-L46
