### ISSUE TITLE
Crawler doesn't warmup the cache

### ISSUE THREAD

**Issue by tiennd79** [nexcess/magento-turpentine#255]
Hi,
I have setup the extension and it works great with ESI.  My website has two stores and using the browsers to access, it works just great, each stores are cached and all sub-sequent accesses are very fast.
After turning on the crawler and setup cronjob to run every 1 hour, in log file I see crawler accesses the url and there is no error reported. But when I copied and pasted those url to browser and use inspector to see header, the page speed is slow and Varnish cache hit is 0. 
Do you know why the cache was not warmup?

Thank you

**Comment by drk1** [comment]
Hi, I've exactly the same problem. Everything seems working fine without error, but when I try to reach the urls with my browser after the cache warmer exec, there is no effect (needs to reload to see fast loading).

@tiennd79 : did you found a solution?
