### ISSUE TITLE
ESI block not processed

### ISSUE THREAD

**Issue by kevinhaynes** [nexcess/magento-turpentine#261]
How do I determine where to add custom ESI blocks? I have tried to add them to the turpentine_esi.xml file as well as the local.xml file in the same directory as the turpentine_esi.xml file, to no avail.

If this is the correct location, do I need to do anything to get Varnish to read the changes? Does Varnish provide any logging to help with determining if it's reading the changes or not?

Thanks

**Comment by anderow** [comment]
the one in /app/etc/local.xml
