### ISSUE TITLE
Varnish not allowing to fetch controller name, action name

### ISSUE THREAD

**Issue by satyendra1989** [nexcess/magento-turpentine#276]
I have varnish installed on magento 1.7
I am trying to fetch router name, controller name, and action name with the below code.

``` php
$routeName = Mage::app()->getFrontController()->getRequest()->getRouteName();
$controllerName = Mage::app()->getFrontController()->getRequest()->getControllerName();
$actionName = Mage::app()->getFrontController()->getRequest()->getActionName();
```

Above code gets proper value if we disable varnish. 
However if varnish is enabled
The above variables are returned empty.
I have written the above code in the footer section.
So I tried adding footer to esi block so that it does not gets cached.
I did this by making the below changes in turpentine_esi.xml

```
reference name="footer"
            action method="setEsiOptions"
                params
                    access private access
                params
            action
        reference
    default
```

I have removed the tags a browser will not render it.
i even tried setting cache flag to 0 for footer still it does not return proper values on every page type.
Can you please specify why varnish is not returning values for above variables.
How can I fetch current page type if turpentine varnish is active.
is this because of varnish caching mechanism or this is a bug with varnish.
Please mention how can get solution for above problem.

**Comment by powerhousefitness** [comment]
Can anyone provide the solution to this problem as i also said controller name.
