### ISSUE TITLE
Failed to apply the VCL to 127.0.0.1:6082: Failed to connect to Varnish on [127.0.0.1:6082]: (111) Connection refused

### ISSUE THREAD

**Issue by Vladimir-kp** [nexcess/magento-turpentine#278]
I installed the Turpentine - Varnish Cache extension on Magento and did configuration.
Attached the configuration Image files.
![configuration1](https://f.cloud.github.com/assets/5136861/892679/6478b7d4-fa8a-11e2-9164-9f348c556bd7.jpg)
![configuration2](https://f.cloud.github.com/assets/5136861/892680/65014784-fa8a-11e2-9af1-1ee46c3cdadd.jpg)

**Comment by qinsan1986** [comment]
you should install php_openssl
