### ISSUE TITLE
How to refresh turpentine cache by command line.

### ISSUE THREAD

**Issue by LifeSoCool** [nexcess/magento-turpentine#289]
Hi,
I just want to run a cron job to refresh all magento cache and varnish cache.

here's my php code for magento:

``` php
$allTypes = Mage::app()->useCache();
        foreach($allTypes as $type => $blah) {
          Mage::app()->getCacheInstance()->cleanType($type);
        }
```

Does this include turpentine cache? if not, how can I refresh turpentine cache by command line?

Cheers,

**Comment by milansimek** [comment]
In case someone is still wondering about this, the following code works:

```php
//clean regular cache
Mage::app()->cleanCache();
//clean Turpentine cache
Mage::getModel('turpentine/observer_ban')->banAllCache(true);
```
