### ISSUE TITLE
RESOLVED: Cannot send headers; headers already sent

### ISSUE THREAD

**Issue by AnthraX1** [nexcess/magento-turpentine#296]
Hi all,
Im using EM onestepcheckout that comes with the template of my site. When I go to checkout page, it will be redirected to the error page.

Cannot send headers; headers already sent in /home/html/app/code/local/EM/Onestepcheckout/controllers/IndexController.php, line 6

Content of line 6:
echo $this->getLayout()->getBlock('checkout.onepage.review.info')->toHtml();

Trace:
#0 /home/html/lib/Zend/Controller/Response/Abstract.php(115): Zend_Controller_Response_Abstract->canSendHeaders(true)
#1 /home/html/app/code/community/Nexcessnet/Turpentine/Model/Observer/Varnish.php(35): Zend_Controller_Response_Abstract->setHeader('X-Turpentine-Ca...', '1')
#2 /home/html/app/code/core/Mage/Core/Model/App.php(1338): Nexcessnet_Turpentine_Model_Observer_Varnish->setCacheFlagHeader(Object(Varien_Event_Observer))
#3 /home/html/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Nexcessnet_Turpentine_Model_Observer_Varnish), 'setCacheFlagHea...', Object(Varien_Event_Observer))
#4 /home/html/app/Mage.php(447): Mage_Core_Model_App->dispatchEvent('http_response_s...', Array)
#5 /home/html/app/code/core/Mage/Core/Controller/Response/Http.php(82): Mage::dispatchEvent('http_response_s...', Array)
#6 /home/html/app/code/core/Mage/Core/Controller/Varien/Front.php(188): Mage_Core_Controller_Response_Http->sendResponse()
#7 /home/html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#8 /home/html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#9 /home/html/index.php(87): Mage::run('', 'store')
#10 {main}

Please help!! This is urgent...

**Comment by mahmoudissmail** [comment]
Hi all,
I have some issue any Solution?
