### ISSUE TITLE
Cache headers

### ISSUE THREAD

**Issue by valguss** [nexcess/magento-turpentine#327]
Currently a site using turpentine will score poorly using yslow http://developer.yahoo.com/yslow/ because all the expires, cache-control etc headers get stripped out of every request using the sub remove_cache_headers. I think I can see the logic of doing this for pages, however it would be great to exclude static content from this.
I suspect that the default vcl generated will need to be updated to filter out static content like images, js and css, or what would be even better would be if we could choose in the admin system what to filter out from this strip.

**Comment by joolswills** [comment]
I have noticed this too - why was this ticket closed btw ? If expires header is set for static content (via nginx etc), then it should be respected. We may not want varnish to cache the static content (which will then add its own cache-control header) as nginx can serve it up quickly anyway.
