### ISSUE TITLE
TAX Switcher

### ISSUE THREAD

**Issue by ghost** [nexcess/magento-turpentine#349]
In the header of my site, I have an "include VAT switcher" (on/off).

it simply sets a session to set the VAT.

```
 Mage::getSingleton('core/session')->setVat( $_GET['vat'] );
```

once i enable turpentine, this no longer works and i cannot switch between the options (always including VAT).

whats the way around this?

I also have an "EU cookie law" notice that now won't go away when i click close

**Comment by NudeWeb** [comment]
What extension are you using for switching tax pls?
