### ISSUE TITLE
Nginx SSL support

### ISSUE THREAD

**Issue by rmsint** [nexcess/magento-turpentine#35]
Hi,

Have you also looked at Nginx to provide the SSL support? Anyhow, doing research on this subject I also found Nginx as option that I would like to share. Underneath the config I have for CentOS 6. Many thanks for this great extension!!

The following article provides an example http://www.fabrizio-branca.de/nginx-varnish-apache-magento-typo3.html

In forums post I found that Nginx configured as proxy/SSL wrapper can use less resources (CPU and memory) than Pound.

The X-Forwarded-for header configured in the nginx (or Pound) proxy-pass can be used to update your logging mechanism to record the correct information. For example, If you're using Apache combined logging, replace the letter h (remote host) with:
\"%{X-Forwarded-for}i\"

Cheers,

Roel

/etc/nginx/nginx.conf:

```
# /etc/nginx/nginx.conf

# For more information on configuration, see:
#   * Official English Documentation: http://nginx.org/en/docs/
#   * Official Russian Documentation: http://nginx.org/ru/docs/

user              nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log;
#error_log  /var/log/nginx/error.log  notice;
#error_log  /var/log/nginx/error.log  info;

pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    # Load config files from the /etc/nginx/conf.d directory
    # The default server is in conf.d/default.conf
    #include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/conf.d/ssl_offload.conf;

}
```

/etc/nginx/conf.d/ssl_offload.conf:

```
# /etc/nginx/conf.d/ssl_offload.conf

upstream varnish {
    server 127.0.0.1:80;
    server 127.0.0.1:8080 backup;
}

server {
    listen       443;
    server_name  site1.com;

    ssl                  on;
    ssl_certificate      /etc/ssl/certs/site1_com.crt;
    ssl_certificate_key  /etc/ssl/certs/site1_com.key;

    include conf.d/default_ssl_options.conf.inc;
    include conf.d/magento_proxy_pass.conf.inc;
}

server {
    listen      443;
    server_name site2.com;

    ssl                 on;
    ssl_certificate     /etc/ssl/certs/site2_com.crt;
    ssl_certificate_key /etc/ssl/certs/site2_com.key;

    include conf.d/default_ssl_options.conf.inc;
    include conf.d/magento_proxy_pass.conf.inc;
}
```

/etc/nginx/conf.d/default_ssl_options.conf.inc:

```
# /etc/nginx/conf.d/default_ssl_options.conf.inc

ssl_session_timeout  10m;

ssl_protocols  SSLv2 SSLv3 TLSv1;
ssl_ciphers  ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP;
ssl_prefer_server_ciphers   on;
```

/etc/nginx/conf.d/magento_proxy_pass.conf.inc:

```
# /etc/nginx/conf.d/magento_proxy_pass.conf.inc

location / {
    proxy_pass http://varnish;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Ssl-Offloaded "1";
    #proxy_hide_header X-Varnish;
    #proxy_hide_header Via;
}
```

**Comment by paulpartington** [comment]
Thank you very much for the information.

I was having some trouble with redirect loops. I found I had to add:

`proxy_set_header X-Forwarded-Proto $scheme;`

to the SSL location.

I then had to check for the value to set a fastcgi_param:

    set $site_ssl "off";
    if ($http_x_forwarded_proto = "https") {
        set $site_ssl "on";
    }
    fastcgi_param HTTPS $site_ssl

Taken from https://www.sonassi.com/knowledge-base/magento-kb/magento-https-redirect-loop/

**Comment by srmobile** [comment]
I realize I may be a little late to the party, this is very informative, but the one item you left out was the actual varnish configuration and turpentine.  What port should turpentine / varnish be set to listen on? 

I've been able to get this to work with apache: pound port 443 ------> Varnish port 6081 ------> Apache port 8080

What I cant understand is how to configure either varnish or nginx?
nginx port 443 -----> Varnish port 6081 ----> nginx port ???
