### ISSUE TITLE
Mini cart count and contents cached

### ISSUE THREAD

**Issue by aidin3000** [nexcess/magento-turpentine#355]
I'm not sure if this has been posted before, as i have searched and have not found an answer..so please forgive me.

I have a mini cart that displays Qty Count and $ Amounts of contents in the shopping cart. Values update fine on shopping cart page, but let's say you go back to home page it will still show Shopping Bag $0.00.

I could not find an answer on how to keep just that uncached and updated as items are added to cart.

Thanks for your help.

**Comment by epiblue** [comment]
@Dung123 have you manage to solve it? I'm getting the same...

**Comment by Dung123** [comment]
no i switch to http://www.extendware.com/magento-extensions/performance/magento-full-page-cache.html <http://www.extendware.com/magento-extensions/performance/magento-full-page-cache.html>
