### ISSUE TITLE
Product pricing, group pricing

### ISSUE THREAD

**Issue by j0ney3** [nexcess/magento-turpentine#359]
First off, @aheadley, thank you immensely for this extension.

Ok, now on to my issue, for reference: https://github.com/nexcess/magento-turpentine/issues/202

I've been trying everything I can think of to get pricing to go through ESI, but I just can not get it working.  

The "block" that should be product.price actually comes through as ANONYMOUS_*, I tried the hack below in price.phtml just to see if I could get it to come through as "product.price", which it did.
```php
    $esiOptions = array('access' => 'private', 'registry_keys' => array('product'=>''));
    $this->setEsiOptions($esiOptions);
    $this->setNameInLayout('product.price');
```

However, it said it was injecting, but of course fails later on in Esi.php when it looks for the $blockNode (because it's not in the xml layout anywhere...)

I then tried adding the following, both to default and catalog_product_view, but it errors out with: 
```
"[Wed Nov 06 15:06:36 2013] [error] [client 96.30.37.70] PHP Fatal error:  Call to a member function getStockItem() on a non-object in /home/dev/public_html/app/code/core/Mage/CatalogInventory/Block/Qtyincrements.php on line 72"
```
```xml
<reference name="product.info">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <registry_keys>
                        <product/>
                    </registry_keys>
                </params>
            </action>
</reference>
```
Does anyone have a successful fix for group pricing, or product.info injection?  Please let me know and thanks in advance

**Comment by miguelbalparda** [comment]
@j0ney3 please check #838, it might be helpful here.

**Comment by miguelbalparda** [comment]
Closing for lack of response.

**Comment by mabigo** [comment]
to make the above work you may consider adding model definition to registry_keys node.
`                    <registry_keys>

                    	<product>

                    		<model>catalog/product</model>

                    	</product>

		                <current_product/>

		            </registry_keys>`
