### ISSUE TITLE
Language selector?

### ISSUE THREAD

**Issue by cscd98** [nexcess/magento-turpentine#36]
Hi,

I noticed in your readme that multi-store (language selector) is not supported. Any idea when this might be fixed?

Also, how/why would we not get the real ip in log files? We are using nginx and we are using the ip forwarded by our varnish configuration file

**Comment by mobweb** [comment]
Has this ever been resolved? Currently struggling to set up a shop that uses the same base domain for multiple languages (e.g. example.com can be both English and French), and I'm wondering if the error is on my end or if it's not possible with Turpentine.
