### ISSUE TITLE
BUG with magento Cookie Restriction (EU cookie Law) and analytics

### ISSUE THREAD

**Issue by karpa** [nexcess/magento-turpentine#375]
Hi i think there is a bug with ESI and EU cookies setting and analytics.
To reproduce the error you must enable "system->settings->web->cookie restriction mode"
With this setting magento adds a warning on the header saying that the website is using cookies and user must press "Allow" is he accepts the policy.
The bugs are two.
1) If user press "allow" the page is reloading but the message is still there (since its cached by varnish.). The work around for this was to add "ttl=0" for "global_messages" block. 
2) it seems that magento have a server-side cookie check if user pressed "allow" and if user accepts cookies it injects the analytics code. see app/design/frontend/base/default/template/googleanalytics/ga.phtml line 27 (v1.7.0.2). But since the page is cached the code is not visible until cache refresh. Workaround for me was to copy the ga.phtml file to my theme and remove the "if (!Mage::helper('core/cookie')->isUserNotAllowSaveCookie()):" statement.

I believe you should add an event for "user allowed cookies" and refresh the "global_notices" and "google_analytics" ESI block.

PS. i didn't tried because my site is live now but i believe that the bug 1) is also affecting the "Javascript seems to be disabled in your browser" notice (also in "global_notices" block and with server-side check). Since i set ttl=0 to global_notices it works fine on my site.
Thanks

**Comment by kanduvisla** [comment]
I added the following to my local.xml:

        <reference name="global_cookie_notice">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <ttl>0</ttl>
                </params>
            </action>
        </reference>
        <reference name="global_notices">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <ttl>0</ttl>
                </params>
            </action>
        </reference>

And although it's working is expected on my local development environment, it doesn't seem to work on my production environment.

**Comment by craigcarnell** [comment]
@aheadley Any updates on this?

**Comment by aricwatson** [comment]
I've tested the following and it seems to work fine with 1.9.1
```
        <reference name="global_cookie_notice">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                </params>
            </action>
        </reference>
```

**Comment by craigcarnell** [comment]
@aricwatson Thanks works for me

**Comment by Nuranto** [comment]
Just enable cookie notice.
Not working here (1.9.4.0).  When I click allow, I keep getting the cookie notice untill I flush varnish cache.
I don't understand your solution. It should be private indeed, but there should be some flush mecanism when the user do accept cookie, right ?
