### ISSUE TITLE
Welcome message not working properly with varnish active

### ISSUE THREAD

**Issue by keeebs** [nexcess/magento-turpentine#376]
When a customer is logged in, the welcome message is the same whether varnish is active or not. When a customer is not logged in, the message is different.

Without Varnish active, the message is correct:
Welcome, John Smith! (Not John Smith?)

With Varnish Active, the message displayed is simply:
Hello. Sign In.

The message is being called by:
<?php echo $this->getWelcome() ?>

Any help is appreciated. TY

**Comment by data-digger** [comment]
`Mage_Page_Block_Html_Welcome` overrides `_toHtml()` and prevents usage of any template file -  which prevents ESI block injection. `welcome` block won't work out of the box, you need to either override it or encapsulate it in some other block.

(At least in Magento 1.9.x, I'm not sure how it works in other versions of Magento.
