### ISSUE TITLE
Turpentine not saving default.vcl

### ISSUE THREAD

**Issue by jewelstreet** [nexcess/magento-turpentine#377]
Hi, I'm trying to get Turpentine up and running, but cannot get it to save the default.vcl so cannot proceed at the moment. The relevant info is:-

- Magento 1.6.2
- version 0.5.5 installed via Magento Connect
- "Apply VCL On Config Change" is set to "Enable"
- "Config File Location" is set the default of "{{root_dir}}/var/default.vcl"
- the var folder is writable by the apache process
 
Clicking 'Save Config' returns the message 'The configuration has been saved.' and I would have expected a default.vcl in the var folder except that it's not there. 

Am I missing something obvious, and any suggestions on what to try next?

Thanks.

**Comment by theycallmepepper** [comment]
I just ran into this issue again on my dev environment and it was cleared by resetting the permissions on the folder in which the VCL is saved.

**Comment by miguelbalparda** [comment]
This seems to be a server issue not related to the extension code. Closing as invalid.
