### ISSUE TITLE
Add to cart navigate to empty shopping cart page

### ISSUE THREAD

**Issue by sujithtv** [nexcess/magento-turpentine#383]
I am getting an issue like if i click add to cart from product list page/product detail page it is navigated to empty shopping cart page. The issue is not consistent.
If i clear the varnish cache i can perform the add to cart option but even after 3-4 hours if i tried the add to cart for the same product it will not add product to cart and will navigate to empty shopping cart page.

Just want to confirm i am using Magento EE 1.13.0.2 which using "form_key" parameters on URL's.
Can you please let me know is there any work around on these issues?

**Comment by ravinama** [comment]
Cannot add the item to shopping cart error come when i have added item on product page.
I have set all Session Cookie Management but not resolve this issue so please give me better idea for this error.

**Comment by miguelbalparda** [comment]
@ravinama what have you tried so far?
