### ISSUE TITLE
Support more than one backend + load-balancing

### ISSUE THREAD

**Issue by aheadley** [nexcess/magento-turpentine#41]
For clusters, the current single-backend-only really only works for some specific cluster configs, need to add support for using multiple backends and using Varnish's load-balancing. Should also implement the health-check stuff as well.

**Comment by dogsbody** [comment]
Shocked at how hard this was to implement.  Thank you @jdub for the config above.  I couldn't have done it without this!

**Comment by jdub** [comment]
@miguelbalparda Which commit fixed this?

**Comment by miguelbalparda** [comment]
@jdub no commit for this, only your comment. It will remain here for others to use it. Since this is a special case I won't add the changes to our VCL default file.

**Comment by jdub** [comment]
@miguelbalparda In that case, it's probably worth re-opening the bug, as it's an important feature that @aheadley recognised was missing from very early on. My suggested configuration block is only a partial, manual fix (e.g. it doesn't balance admin requests, etc).
