### ISSUE TITLE
Global messages (success & error) appears on next page

### ISSUE THREAD

**Issue by franciskim** [nexcess/magento-turpentine#419]
Hi everyone - this is a fairly common issue with AJAX global messages I believe due to the way Magento processes the success and error messages. 

I have an AJAX add to cart that works fairly well - Turpentine knows to refresh the cart quantity afterwards too. However the success message 'You have added foobar to your cart' does not appear until you hit the next page. 

Does anyone know a fix/workaround for this seemingly common issue?

**Comment by Krapulat** [comment]
Hello @franciskim,

can you explain how did you solve it?

Thanks!

**Comment by franciskim** [comment]
@Krapulat I don't remember clearly - it was a while ago but I think there was a setting in the AJAX cart module that changed how the messages worked.

**Comment by anhuy1989** [comment]
I fixed this issue by adding the code below to 1column.phtml and enable AJAX flash message of Magento Turpentine.

`<?php echo $this->getChildHtml('messages') ?>
<?php $this->getMessagesBlock()->getMessageCollection()->clear(); ?>
`
