### ISSUE TITLE
Cache only for logged in users?

### ISSUE THREAD

**Issue by J0s3f** [nexcess/magento-turpentine#421]
Hello,
is there a way o have varnish cache different pages for logged in users?
So a private shop where anonymous users just allowed to view contact information and the legal stuff, but for every page are redirected to the login form.
Logged in users see a regular shop.
As it is now, Varnish shows the pages for logged in users to everyone.

**Comment by miguelbalparda** [comment]
Maybe #758 can help here!

**Comment by aricwatson** [comment]
Closing for lack of response.
