### ISSUE TITLE
HTTPS not working with  	Varnish Pages enabled!

### ISSUE THREAD

**Issue by J0s3f** [nexcess/magento-turpentine#425]
Hi, when I enable the Varnish Pages cache, all https sites get redirected to the startpage without https!
Here is the answer to the request to get https://www.mysite.com/customer/account/login/

		Accept-Ranges:bytes
		Age:0
		Cache-Control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
		Connection:keep-alive
		Content-Encoding:gzip
		Content-Length:25
		Content-Type:text/html
		Date:Tue, 28 Jan 2014 20:03:08 GMT
		Expires:Thu, 19 Nov 1981 08:52:00 GMT
		Location:http://www.mysite.com/
		Pragma:no-cache
		Set-Cookie:frontend=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; domain=www.mysite.com; httponly
		Via:1.1 varnish
		X-Powered-By:PHP/5.4.4-14+deb7u7
		X-Varnish:1710488714
		X-Varnish-Hits:0

Especially the Set-Cookie:frontend=deleted; looks fishy!

**Comment by kenorb** [comment]
It's Varnish configuration issue, it unset your cookie. See similar thing for [Drupal](http://drupal.stackexchange.com/q/46137/1908).
