### ISSUE TITLE
PayPal Express - 10002 security header is not valid error

### ISSUE THREAD

**Issue by franciskim** [nexcess/magento-turpentine#426]
<pre>10002 security header is not valid</pre> is the error I get while trying to purchase an item via PayPal Express. All API details are correct - I've reset it multiple times. Has anyone experienced something similar? Not entirely sure if it's related to Varnish - SSL is configured and running well. Here's some logs:
<pre>
==> payment_paypal_express.log <==
2014-01-31T05:22:42+00:00 DEBUG (7): Array
(
    [url] => https://api-3t.paypal.com/nvp
    [GetExpressCheckoutDetails] => Array
        (
            [TOKEN] => 
            [METHOD] => GetExpressCheckoutDetails
            [VERSION] => 72.0
            [USER] => ****
            [PWD] => ****
            [SIGNATURE] => ****
            [BUTTONSOURCE] => Varien_Cart_EC_AU
        )

    [response] => Array
        (
            [TIMESTAMP] => 2014-01-31T05:22:42Z
            [CORRELATIONID] => 5bcdb0da70494
            [ACK] => Failure
            [VERSION] => 72.0
            [BUILD] => 9285531
            [L_ERRORCODE0] => 10002
            [L_SHORTMESSAGE0] => Security error
            [L_LONGMESSAGE0] => Security header is not valid
            [L_SEVERITYCODE0] => Error
        )

    [__pid] => 1219
)

</pre>

**Comment by sanghvi1989** [comment]
@franciskim : can you please let me know the solution for above paypal pro issue ? if you found it .

thank you

**Comment by mpathy** [comment]
According to the hotline its no technical error but a problem with the account used to do the order.
Maybe negative balance, maybe fraud suspicion or other stuff.
Because of the delicate matter of the topic, they decided to let the message quite cryptic, but throw an error, because they dont want to do the transaction.
Thats what the hotline told me.
