### ISSUE TITLE
Too many hits on /catalog/category/view - increasing hit rate

### ISSUE THREAD

**Issue by franciskim** [nexcess/magento-turpentine#434]
I've got NewRelic installed so I've been tracking a few key transactions. I'm seeing way too many hits on /catalog/category/view - pretty much the same number as /turpentine/esi/getBlock which leads me to think my VCL settings are probably inadequate.

Anyone have experience with tweaking Varnish settings for optimal hit rate? Care to share?

I'm currently looking at the TTLs settings under Turpentine. I believe this will have a lot to do with it.

**Comment by aricwatson** [comment]
Closing for lack of feedback.
