### ISSUE TITLE
Turpentine Exclude one domain from varnish for multiple sites on same server

### ISSUE THREAD

**Issue by shaily-a** [nexcess/magento-turpentine#435]
Hello,
I have multiple sites running on the same server. When i enable the option for normalizing the host name, the other site is also taken to the one on which we have our varnish configured.
Also hostname.com doesn't redirects to www.hostname.com.

If I disable the normalize host name both the sites are running, but their are two frontend cookies set in the same host name due to which when I open the site from the hostname.com on checkout the cart becomes empty.

I have a mobile site which shows a different theme, even when I have enabled the normalize user agent the desktop theme comes up.

Am not able to understand where am going wrong. Please help.

**Comment by miguelbalparda** [comment]
It seems #832 has a fix for this issue. would you mind giving it a try? It is on the devel branch until further testing.

**Comment by aricwatson** [comment]
Closing this issue - appears fixed by the VCL tweak.
