### ISSUE TITLE
Session cookie generation

### ISSUE THREAD

**Issue by mgwelance** [nexcess/magento-turpentine#441]
Hey there....
since my Varnish-Hoster doesn't allow C to be executed in the VCL i can't use the normal turpentine session-generator...  i had to strip that part but now the average user gets the "crawler session" frontend-cookie which leads to an ever growing compare-list (that is privately cached via ajax)... users only get a real personal frontend cookie when they put something into the cart or log in ... 

How can i give them such a personalized frontend-session from the start?

Do i have to have an uncached ESI included Block for this?

Any help is appreciated! (there's probably more hosters out there that don't allow the C code in the VCL for security reasons...)

update:
what i mean is the "X-Varnish-Session	crawler-session" header that identifies the privately cached blocks....

**Comment by aricwatson** [comment]
Closing this, as of 0.6.3 session generation no longer occurs in the VCL.
