### ISSUE TITLE
Mage::app()->getStore()->getLocaleCode() appears unreliable.

### ISSUE THREAD

**Issue by evensisftw** [nexcess/magento-turpentine#448]
Hi there,

Interesting issue that has popped up, we use the subject header code in order to get hold of the store locale for our size guides.

On my git branch for our new clustered servers (which has turpentine installed along with various other minor changes), Mage::app()->getStore()->getLocaleCode() seems unreliable. Sometimes works sometimes doesn't, for the moment i'm using Mage::getStoreConfig('general/locale/code', $storeId) instead which is a perfectly good alternative.

This is unique to this git branch, and I haven't done anything that touches any core code, so my immediate assumption is something is caching something it shouldn't!

I would investigate it a bit further, but the deadline for these cluster servers is looming so I don't have the time to track through xdebug unfortunately.

Has anyone had any experience with this issue?

Thanks,

Adam

**Comment by Schrank** [comment]
Because this issue ranks high, when one googles for  `Mage::app()->getStore()->getLocaleCode()` and this is one of the recommendations on stackoverflow:

This doesn't work at all, at least for me. Obviously there are cases where the language is returned, but the alternative is `null`, which is not helpful.

So go with 

    Mage::getStoreConfig('general/locale/code', $storeId)

**Comment by miguelbalparda** [comment]
Thank you for the feedback @Schrank!

**Comment by digitalpianism** [comment]
Small addition to @Schrank just in case it changes in the future:

`Mage::getStoreConfig(Mage_Core_Model_Locale::XML_PATH_DEFAULT_LOCALE,$storeId);`

**Comment by Schrank** [comment]
I love this community. Another project, the same problem, thanks @Schrank and @digitalpianism for your feedback and help 😂  👍
