### ISSUE TITLE
checkout_onepage_progress showing previous users shipping address

### ISSUE THREAD

**Issue by craigcarnell** [nexcess/magento-turpentine#455]
Not sure if this is related to turpentine or not, but I am testing checkout (no HTTPS) and some of my users who are testing it are seeing a previous users shipping address in the checkout progress block?

We are using an external module to remove the postage step, but I have disabled it for now (only in it's admin setting):

Clearandfizzy_Reducedcheckout

**Comment by sprankhub** [comment]
I just had exactly the same issue on Magento 1.9.2.4 with Turpentine 0.7.2. Although adding `checkout` to the blacklist works, I think this should work out of the box. Would it make sense to populate the following URLs to the blacklist by default?

    cron\.php
    customer
    checkout
    paypal/ipn
    paypal/standard/success
    paypal/express/return
    paypal/express/review
