### ISSUE TITLE
Shopper theme with Turpentine

### ISSUE THREAD

**Issue by batmike** [nexcess/magento-turpentine#463]
I am using the Shopper theme on our site and based on the layout.xml, I was able to get the header links (which include a login/logout link) to generate on a per-client basis. However, the header is normally generated on a site-wide basis, which works great except the dropdown shopping cart and basket item count are included in the header reference. What I'm having trouble with is getting the header included on a site wide caching basis (the header is very slow in rendering) but to have the cart section included on a per-client/ per-page basis as it otherwise will show the cart contents of whoever cached the page the first time.

The changes I made in turpentine_esi.xml (lines 39-79) that enabled it to work without caching the cart and login button on a site level (but also without caching the header menu) are:

```xml
        <reference name="header">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
		    <scope>page</scope>
                    <flush_events>
                        <wishlist_item_save_after/>
                        <wishlist_item_delete_after/>
                        <sales_quote_save_after/>
                    </flush_events>
                </params>
            </action>
        </reference>
        <reference name="top.links">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <flush_events>
                        <wishlist_item_save_after/>
                        <wishlist_item_delete_after/>
                        <sales_quote_save_after/>
                    </flush_events>
                </params>
            </action>
        </reference>
        <block name="queldorei.topnav" type="shoppersettings/navigation">
            <action method="setEsiOptions">
                <params>
                    <access>public</access>
		    <scope>page</scope>
                </params>
            </action>
        </block>
        <block name="slideshow" type="shopperslideshow/slideshow">
            <action method="setEsiOptions">
                <params>
                    <access>public</access>
		    <scope>page</scope>
                </params>
            </action>
        </block>
```

Also, here is the relevant section in our local.xml but I can't figure out what I should set to cache the header globally but not the cart_top section.

```xml
		<reference name="header">
            <block type="cms/block" name="theme_logo" as="theme_logo">
                <action method="setBlockId"><block_id>shopper_logo</block_id></action>
            </block>
            <block type="directory/currency" name="currency_top" as="currencyTop"
			       template="directory/currency-top.phtml"/>
			<block type="checkout/cart_sidebar" name="cart_top" as="cartTop" template="checkout/cart/cart-top.phtml">
                <action method="addItemRender"><type>simple</type><block>checkout/cart_item_renderer</block><template>checkout/cart/sidebar/default.phtml</template></action>
                <action method="addItemRender"><type>grouped</type><block>checkout/cart_item_renderer_grouped</block><template>checkout/cart/sidebar/default.phtml</template></action>
                <action method="addItemRender"><type>configurable</type><block>checkout/cart_item_renderer_configurable</block><template>checkout/cart/sidebar/default.phtml</template></action>
                <block type="core/text_list" name="cart_sidebar.extra_actions" as="extra_actions" translate="label" module="checkout">
                    <label>Shopping Cart Sidebar Extra Actions</label>
                </block>
            </block>


            <block type="shoppersettings/navigation" name="queldorei.topnav" as="topShopperMenu"
			       template="queldorei/navigation/top.phtml"/>
            <block type="shopperslideshow/slideshow" name="slideshow" as="slideshow"
			       template="queldorei/slideshow.phtml"/>
		</reference>
```

Any help would be very appreciated!

Thanks!

**Comment by delarosajv** [comment]
@FabienTei have you solved the issue with amasty improved navigation slowing the store?

i'm monitoring server with newrelic says that amshopby pages are the super slowest and i'm thinking to look for an alternative if i do not found a solution. They are pushing my server's to the limit :(

**Comment by FabienTei** [comment]
Hi @delarosajv , 

I gave up on trying to configure varnish with Amasty's extension, because I was runing out of time and my customer wanted it fully functionnal quickly.

I ended up choosing Amasty's full Page cache to solve the performance issues.

If your store has many products / attributes, there are many possibilities and of course many results pages to display. A full page cache is then mandatory to get a nice user experience.

You can keep Amasty's improved navigation module but 1st : you need to update it to the latest version, as then continuously improve it.
Then, you have to configure a full page cache correctly, either with Varnish or with Amasty's (or anyother's) full page cache module.

If you're not familiar with full page cache, you should read how it works, and then you'll be able to understand some key concepts, like whole punching, excluding parameters, ....

Good luck
