### ISSUE TITLE
How to define a caching policy for magento customer groups?

### ISSUE THREAD

**Issue by plumrocket** [nexcess/magento-turpentine#465]
We have several magento catalog price rules assigned to a specific customer group. So the product price CANNOT be cached witn ```<access>public</access>```. In this case it should be ```"private"```. 

However creating an ESI rule for "product list" page with ```"access = private"``` doesnt make sense as it will never load from varnish cache *for new visitors for the first time* (with varnish hit-rate near zero). 
Localizing prices on product list page in a separate block (and making only these blocks ```"private"```) is also not an easy task, but still it will require varnish to make 20 requests to magento to get prices of 20 products on page. 

Therefore we thought if there is a way to define a caching policy for magento customer groups. Basically create new access = ```<access>group</access>```.

**This is what we thought could be done:**
1. Define "access = group" for a product list page (category page in magento)
2. From varnish VCL file somehow retrieve magento ```SESSION "customer group id"```
3. If "access = group", generate cache based on session group id (not session_id as in private access policy)

------------------------------------------------------------------------
**Here is what we are using:**
+ Magento CE 1.8.1
+ Varnish-3.0.3 
+ Turpentine - Varnish Cache-0.6.0 Magento Extension (with Nexcessnet_Turpentine Varnish v3 VCL Template)
+ Redis for storing sessions and backend cache

------------------------------------------------------------------------

**Some links we found that may help:**
https://github.com/brandonwamboldt/libvmod-redis
https://www.iweb-hosting.co.uk/blog/moving-varnish-caching-logic-into-php-with-the-curl-vmod.html

------------------------------------------------------------------------

Any ideas appreciated! Would love to hear from Turpentine developers such as @aheadley

**Comment by pejoo** [comment]
For anyone still looking for this, I submitted a pull request that adds this feature: https://github.com/nexcess/magento-turpentine/pull/758

You can replicate the adjustments in your module until it gets added to the plugin itself.

**Comment by jg-development** [comment]
Thanks ... I did it with a similar approach, but this is imho a little better

**Comment by miguelbalparda** [comment]
If anyone here is using #758 feel free to share your experience, it is our next merge candidate!
