### ISSUE TITLE
Pagespeed / Turpentine

### ISSUE THREAD

**Issue by TableDeMassageElectrique** [nexcess/magento-turpentine#479]
I have a problem when I use pagespeed with turpentine.
You can see the problem : http://table-de-massage-electrique.fr/fauteuil-specialise.html

```<button type="button" title="Ajouter au panier" class="button btn-cart" onclick="setLocation('http://table-de-massage-electrique.fr/checkout/cart/add/uenc/aHR0cDovL3RhYmxlLWRlLW1hc3NhZ2UtZWxlY3RyaXF1ZS5mcjo4MDgwL3RhYmxlLW9zdGVvcGF0aGllLmh0bWw,/product/1/form_key/1lWjTPu3ZnpZePTf/')"><span><span>Ajouter au panier</span></span></button>```
become
```<button type="button" title="Ajouter au panier" class="button btn-cart" onclick="setLocation('http://table-de-massage-electrique.fr/checkout/cart/add/uenc/aHR0cDovL3RhYmxlLWRlLW1hc3NhZ2UtZWxlY3RyaXF1ZS5mcjo4MDgwL3RhYmxlLW9zdGVvcGF0aGllLmh0bWw,/product/1/form_key/<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">```

**Comment by siment** [comment]
I would like to add to @jeroenvermeulen excellent suggestion and modify it somewhat. This regexp will allow you to use custom ports in your request url:

```
sub vcl_recv {
    #### Fix ESI URLs broken by Mod_PageSpeed
    if ( req.url ~ "https?: " ) {
        set req.http.Host = regsub( req.url, "^.*https?: ([\w\.\-]+(\s?\:[0-9]+)?).*$", "\1" );
        set req.url = regsub( req.url, "^.*https?: ([\w\.\-]+(\s?\:[0-9]*)?)", "" );
        set req.url = regsuball( req.url, " ", "/" );
    }
}
``` 

Otherwise this request URL:

    http://www.example.com:6081/some/uri

Would become:

    :6081/some/uri
