### ISSUE TITLE
Missing header

### ISSUE THREAD

**Issue by 3hertz** [nexcess/magento-turpentine#480]
Hi!
In source code I see instead of header next comments:
~~~~html
<!-- ESI START DUMMY COMMENT [] -->
<!-- ESI URL DUMMY COMMENT -->
<!-- ESI END DUMMY COMMENT [] -->
~~~~
Can you help me?

Please ask if you need info to understand a problem.

**Comment by aricwatson** [comment]
FYI - this should be fixed by PR https://github.com/nexcess/magento-turpentine/pull/626, which was merged in 0.6.2. Let us know if you're still seeing it after updating to 0.6.2!
