### ISSUE TITLE
Controlling caching of block

### ISSUE THREAD

**Issue by AnthonyLavin** [nexcess/magento-turpentine#486]
Hi, I have a contact-us page with a block containing the contact-us form. I want just this block to not be cached. Here is my contacts.xml:

    <contacts_index_index translate="label">
        <label>Contact Us Form</label>
        <reference name="head">
            <action method="setTitle" translate="title" module="contacts"><title>Contact Us</title></action>
        </reference>
        <reference name="root">
            <action method="setTemplate"><template>page/1column.phtml</template></action>
            <action method="setHeaderTitle" translate="title" module="contacts"><title>Contact Us</title></action>
        </reference>
        <reference name="content">
            <block type="core/template" name="contactForm" template="contacts/form.phtml">
				<action method="setEsiOptions">
					<params>
						<access>public</access>
						<scope>page</scope>
						<ttl>0</ttl>
					</params>
				</action>
			</block>
        </reference>
    </contacts_index_index>

I have tried every combination of settings in the EsiOptions I could find but I cannot get the block to stop caching. For testing purposes I have added a timer to my contact form template and no matter what I try it gets cached.

I have managed to stop caching a block that is in the default handle but I'm having no luck with this form.

Thank you
Anthony

**Comment by sprankhub** [comment]
Mind that wholepunching the contactForm block ist not enough. The form action is only `post` in this case and not the whole shop URL plus `contacts/index/post`. Hence, you need to exclude the whole contacts page.
