### ISSUE TITLE
Is it really necessary to overwrite Mage_Core_Model_Session in local?

### ISSUE THREAD

**Issue by eth8505** [nexcess/magento-turpentine#491]
I find it rather dirty to deliver a community extension with a fully overwritten file in the local code pool:

https://github.com/nexcess/magento-turpentine/blob/master/app/code/local/Mage/Core/Model/Session.php

Is this really necessary?

**Comment by aricwatson** [comment]
The PR from @eth8505 has been merged into master as of 0.6.3. Thanks!
