### ISSUE TITLE
Wishlist problems

### ISSUE THREAD

**Issue by R0n1n-77** [nexcess/magento-turpentine#497]
Hi,
I'm having some issues with caching Wishlist pages.
1.
 If add some products to wishlist, then browse to a wishlist page in my account and then click "Add to cart" on some product, I get:
Error 403 External ESI requests are not allowed
I found that it can be worked around by excluding the wishlist/* in Turpentine, but then it bytes me from the other side.
2.
On the same Wishlist page, if I make any change to products in wishlist(like quantity, comment, etc), then submit the changes and browse to any other page, I'm getting logged out. This one can't be worked around by blacklisting the URL.
Might it be connected to my vcl.conf options? I have a backend servers configured as follows:
```
probe magento {
.request = "GET /magento-check.php HTTP/1.1"
"Host: merkur.agenda.si"
"Connection: close";
.timeout = 2s;
.interval = 15s;
.window = 8;
.threshold = 3;
}
backend appsrv1 {
.host = "192.168.121.131";
.port = "80";
.first_byte_timeout = 300s;
.between_bytes_timeout = 300s;
.probe = magento;
}
backend appsrv2 {
.host = "192.168.121.132";
.port = "80";
.first_byte_timeout = 300s;
.between_bytes_timeout = 300s;
.probe = magento;
}
director magento round-robin {
{ .backend = appsrv1; }
{ .backend = appsrv2; }
}
sub vcl_recv {
set req.backend = magento;
}
backend default {
.host = "192.168.121.131";
.port = "80";
.first_byte_timeout = 300s;
.between_bytes_timeout = 300s;
}
backend admin {
.host = "192.168.121.131";
.port = "80";
.first_byte_timeout = 21600s;
.between_bytes_timeout = 21600s;
}
acl crawler_acl {
"127.0.0.1";
}
acl debug_acl {
}
```
But if I run varnishadm --> backend.list, I get:
```
backend.list
200        
Backend name                   Refs   Admin      Probe
appsrv1(192.168.121.131,,80)   4      probe      Healthy 8/8
appsrv2(192.168.121.132,,80)   4      probe      Healthy 8/8
default(192.168.121.131,,80)   4      probe      Healthy (no probe)
admin(192.168.121.131,,80)     4      probe      Healthy (no probe)
```
Should I do something to override default and admin backends with appsrv1 and appsrv2?
Thanks in advance for your help.

**Comment by chrisvanderpoel** [comment]
Hello,
Just confirming this is still an issue with 1.14.2.2 and 0.6.7.
