### ISSUE TITLE
Varnish 4.0 Support

### ISSUE THREAD

**Issue by aheadley** [nexcess/magento-turpentine#498]
Varnish 4.0 has been released, need to add support for it.

https://www.varnish-cache.org/docs/trunk/whats-new/upgrading.html

**Comment by zewolf** [comment]
Yes I already check it, the parameter is correct...

Cyril

2014-12-31 17:09 GMT+01:00 Jan-Simon Winkelmann <notifications@github.com>:

**Comment by anderow** [comment]
I have a very similar issue with Varnish 4 and turpentine. I have changed the cli_buffer in varnish.params file but when I use varnishadm it shows as being 8k.
So when I change it in varnishadm to the correct value, it appears ok at the time but it doesnt actually change the value , it still remains at 8k?

Really strange....

**Comment by prysie** [comment]
There is a bug with the regex pattern matching in the file /app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php, to fix change this :

if ( $this->getVersion()==='4.0' ) {
                // Varnish4 supports "16k" style notation
                $regexp = '~^cli_buffer\s+Value is:\s+(\d+)([k|m|g]{1})?\s+\[bytes\]~';
 }

To include the b for bytes :

if ( $this->getVersion()==='4.0' ) {
                // Varnish4 supports "16k" style notation
                $regexp = '~^cli_buffer\s+Value is:\s+(\d+)([k|m|g|b]{1})?\s+\[bytes\]~';
 }

No need to add it to the pow factor array it as it is already in bytes.

Currently it does not match on the returned message from Varnish that may look like :

200|cli_buffer
        Value is: 17000b [bytes]
        Default is: 8k
        Minimum is: 4k

It can not match on the b so it falls back to using the default const value:

const CLI_CMD_LENGTH_LIMIT  = 8192;

Which is usually too small for the vcl generated.

This will fix this issue, on to the next.

**Comment by Krapulat** [comment]
@aricwatson @miguelbalparda are you planning to include varnish 4 support?

**Comment by aricwatson** [comment]
Yes, we certainly are! I've already done some testing of the Varnish4 PR and it's looking pretty good although I did see some issues.

**Comment by aricwatson** [comment]
FYI the *devel-varnish4* branch is currently up to date with *devel* if you'd like to test varnish4 and more recent turpentine features. So far everything is working pretty well in my testing.

**Comment by craigcarnell** [comment]
@aricwatson I'm just testing this now and found a small error when saving your varnish settings:

```
Fatal error: Call to undefined method Nexcessnet_Turpentine_Helper_Debug::logWarning() in /Users/ccarnell/Sites/dirtdevil-de/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin.php on line 172
```

**Comment by craigcarnell** [comment]
I also get this error when restarting Varnish (Varnish 4.0.3 on OS X Yosemite)
```
Message from C-compiler:
./vcl.Mwgjwpmq.c:1022:1: error: implicit declaration of function 'gettimeofday' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
gettimeofday(&detail_time,NULL);
^
./vcl.Mwgjwpmq.c:1024:50: error: format specifies type 'unsigned long' but the argument has type '__darwin_suseconds_t' (aka 'int') [-Werror,-Wformat]
sprintf(start, "t=%lu%06lu", detail_time.tv_sec, detail_time.tv_usec);
                     ~~~~~                       ^~~~~~~~~~~~~~~~~~~
                     %06d
/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^
[4 lines truncated]
Running C-compiler failed, exited with 1

VCL compilation failed
```

**Comment by aricwatson** [comment]
Fixed! Thanks!

**Comment by kirmorozov** [comment]
I had trouble with compiling c include, varnish did not recognize source annotation.
Also there was trouble with missing file in modman when install through composer.
(about a week ago)

**Comment by miguelbalparda** [comment]
About the composer stuff, it should be fixed by now. Sorry about that @kirmorozov

**Comment by aricwatson** [comment]
@kirmorozov can you give us steps to reproduce?

**Comment by Krapulat** [comment]
I'm testing varnish 4. With "Use VCL fix" enabled it generates this in vcl file:
```
if (!false || req.http.Authorization ||
req.method !~ "^(GET|HEAD|OPTIONS)$" ||
req.http.Cookie ~ "varnish_bypass=1") {
return (pipe);
}
```

I think it could be:
```
if (!true || req.http.Authorization ||
req.method !~ "^(GET|HEAD|OPTIONS)$" ||
req.http.Cookie ~ "varnish_bypass=1") {
return (pipe);
}
```

**Comment by Krapulat** [comment]
Also, it doesn't work with SSL sites.

This resolved the issue: https://github.com/eth8505/magento-turpentine/commit/575f499382217f0013eaf097fd79ceddec0b4381

**Comment by aricwatson** [comment]
Thanks @Krapulat we'll investigate.

**Comment by aricwatson** [comment]
Thanks @Krapulat - I couldn't replicate your error in the vcl file, I'm getting the file generated with this when I have 'use vcl fix' enabled:
```
if (!true || req.http.Authorization ||
req.method !~ "^(GET|HEAD|OPTIONS)$" ||
req.http.Cookie ~ "varnish_bypass=1") {
return (pipe);
}
```
Which is correct.

As for the ssl fix, I think once we get varnish 4 support merged in, we'll then merge in the https/http fix.

**Comment by aricwatson** [comment]
We've merged varnish4 support into devel - https://github.com/nexcess/magento-turpentine/pull/883

**Comment by allardhoeve** [comment]
Are there plans to release this anytime soon?

**Comment by miguelbalparda** [comment]
This is already released on devel. You can checkout the branch and test the code. We use the devel branch as a release candidate before pushing the code to master.

**Comment by allardhoeve** [comment]
I understand. My customers would be loath to install from github/devel though. Turpentine is currently the plugin we ask our customers to install at my [work](https://byte.nl), so. It would be nice to be able to offer Varnish 4.

Any idea on when you'll make a new release?

**Comment by miguelbalparda** [comment]
No, there is no release date for this. We consider that the best way to test this new features is to leave it in devel and have different users test the code. If after a couple of weeks no issues arises we push the new code to master. What I can give you is Magento Connect compatible file with the content of devel branch for you and your customers to install it manually via Connect. Let me know what do you think.

**Comment by allardhoeve** [comment]
If they could install it through Magento Connect, that would certainly help with the adoption rate :smile:

**Comment by miguelbalparda** [comment]
Here it is, a Magento Connect file for devel branch. https://mega.nz/#!AR5n0QAb!yFmpGOfl9bzvGfaSHJcFXAtvSFzFhrAHe61EdccusMY

**Comment by allardhoeve** [comment]
Thanks! But that link tries to convince me to install mega.nz software,
which of course I won't :smile:

**Comment by miguelbalparda** [comment]
You should be able to use the button that says 'Download through your browser' without installing additional software.

**Comment by allardhoeve** [comment]
Thanks, clicked the spam by accident :disappointed:

**Comment by allardhoeve** [comment]
I put it here for future reference:

https://gist.github.com/allardhoeve/095ef50e6a0f2d62ebb8
