### ISSUE TITLE
Custom Logging File

### ISSUE THREAD

**Issue by davidalexander** [nexcess/magento-turpentine#510]
It would be very useful for debugging if Turpentine could log files to a custom log file rather than the standard `var/log/system.log`. Filtering though `var/log/system.log` for Turpentine specific logs can be quite time consuming.

The core `Mage::log` supports a third parameter `$file` which could be used for this.

```php
// app/Mage.php ln.785
public static function log($message, $level = null, $file = '', $forceLog = false)
```

**Comment by miguelbalparda** [comment]
Thank you for the contribution guys!
