### ISSUE TITLE
Mega Menu is not rendering

### ISSUE THREAD

**Issue by bbfdesign** [nexcess/magento-turpentine#515]
Hi there,

I try to use Turpentine with my Theme - but the Mega Menu is not rendering. I can't see any issuses on the errorlog oder exceptions. When I look to the Page on Port 8080 the Menu has gone - without Varnish/ Turpentine it's still there.

I'm using a premium theme and there is a Bootstrap based Mega Menu. The Fix (I tried to modified it) for the WP Mega Menu doesn't work for me.

I need help, to fix that issue.

Thank you

**Comment by goodwebdesignco** [comment]
Sorry for the delay!! Its too much.

But for future reference.

Well.. There are two methods Ajax and ESI.
Put the megamenu inside the top.link or top.menu depends on your theme.

and try testing with the checking the system logs.. you should see the ESI entry there.
If you see there then you made it :)
If not then refer your theme and found the reference for your megamenu.

**Comment by vipuldadhich** [comment]
Sorry for the delay!! Its too much.

But for future reference.

Well.. There are two methods Ajax and ESI.
Put the megamenu inside the top.link or top.menu depends on your theme.

and try testing with the checking the system logs.. you should see the ESI entry there.
If you see there then you made it :)
If not then refer your theme and found the reference for your megamenu.
