### ISSUE TITLE
ESI processing not enabled (header/footer)

### ISSUE THREAD

**Issue by jessetaverne** [nexcess/magento-turpentine#518]
Hi there,

My issue is that "ESI processing not enabled" is shown instead of header/footer blocks when i turn on Varnish ESI Blocks cache in Magento.

I'm running :
- Magento 1.8.1
- Varnish 2.1.5
- Turpentine 0.6.0

I found quite a few hits on google which i thought could help me solve the issue but none seem to apply to my problem so I'm coming here for help instead.

I've added "-p cli_buffer=10000" and "esi_syntax=0x2", reapplied the config file and flushed the cache by a hard varnish restart.

The src url in esi:include doesn't yield html for the header (just empty html/body here), while it does for the footer.

One thing that might be a problem is that my Varnish server is seperate from my Magento server.

Does anybody have a clue? Might upgrading to varnish 3 be a solution?

Regards, Jesse

**Comment by Shelest** [comment]
For me, issue was resolved by Flush Cache from the admin panel.
