### ISSUE TITLE
System->Cache Management - Specify which cached page/category to clear

### ISSUE THREAD

**Issue by craigcarnell** [nexcess/magento-turpentine#525]
More of a feature request.. The ability to clear a particular page or category page from System->Cache Management.

E.g. A box to enter a URL e.g. http://www.yoururl.com/your-category to clear that particular category instead of having to use the CLI or clearing all varnish pages using the admin.

**Comment by miguelbalparda** [comment]
Thank you for your contribution @craigcarnell!
