### ISSUE TITLE
Proper Way to Remove Turpentine

### ISSUE THREAD

**Issue by danielc1234** [nexcess/magento-turpentine#532]
Hi all, I needed to remove the turpentine extension but when I do I get an error on the site. I just simply removed all the files from the app folder and it crashed. I had even cleared cache, etc.
Is there a proper way to completely remove this extension?

**Comment by caevv** [comment]
Yeh, this happen here as well.

**Comment by promocris16** [comment]
me website ot s this
www.magazincompas.ro
please setting me this error 
you have acces cpanel ?
