### ISSUE TITLE
Strip whitespace option - leaves @source directive in generated VCL

### ISSUE THREAD

**Issue by cscd98** [nexcess/magento-turpentine#535]
If you change the strip whitespace option in the admin to "Only when applying to Varnish" and then you save the generated VCL, it will leave in the source directive, which causes a VCL compile error.

```
error: invalid preprocessing directive #@
     # @source app/code/community/Nexcessnet/Turpentine/misc/uuid.c
```

**Comment by prysie** [comment]
I fixed this one by editing the file :

apps/magento/htdocs/app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl and changed it from this :

## Custom C Code

C{
    # @source app/code/community/Nexcessnet/Turpentine/misc/uuid.c
    {{custom_c_code}}
}C

## Imports

To this :

## Custom C Code

# @source app/code/community/Nexcessnet/Turpentine/misc/uuid.c
C{    
    {{custom_c_code}}
}C

Moving the comment outside of the C block ensures the C compiler does not try to import it.

This seemed to be an error with the version-3.vcl file also, although I never have used version 3.
