### ISSUE TITLE
Turpentine Generated UUID may not be random enough

### ISSUE THREAD

**Issue by scottrebel** [nexcess/magento-turpentine#562]
Hi,

We seem to be experiencing an issue where the UUID generated for the frontend cookie is colliding with a value that already exists in the session table. On average we have just over 200,000 active sessions in the db. I am receiving reports that every once in a while a user gets a "Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '28117ecd772947298eb31a9c0948b37b' for key 'PRIMARY'' ... " message on the home page. Oddly enough these are not logged in the system.log or exception.log, but rather displayed on the page. Refreshing the page and the error is no longer displayed. 

Given the randomness of the error, I have not been able to reproduce the issue reliably. 

Any assistance trouble shooting the issue, or suggestions for improving the randomness of the UUID is greatly welcome.

Thanks,

**Comment by aricwatson** [comment]
The current *devel* branch contains fixes to prevent unnecessary creation of sessions, which in turn should greatly reduce the chance of a session collision like this. You may also consider tweaking the uuid.c file which is where the keys are generated. Be aware that increasing the length over 32 characters may cause problems with Kount fraud detection modules.

Given the age of this issue I'm going to close, but feel free to reply if you need more help.

**Comment by peterjaap** [comment]
I just ran into this problem as well. As per @aricwatson his suggestion, I've tweaked the uuid.c file. I've doubled the length of the UUID string by changing the numeric values in the sprintf function;

```
    sprintf(buf, "frontend=%016lx%08lx%08lx%08lx%08lx%016lx",
        a,
        b & 0xffff,
        (b & ((long)0x0fff0000) >> 16) | 0x4000,
        (c & 0x0fff) | 0x8000,
        (c & (long)0xffff0000) >> 16,
        d
    );
```

Let's see....

**Comment by Nuranto** [comment]
Still having this issue...
Turpentine 0.7.1
Varnish 4
Magento 1.9.3.1
(Multi node infra)
