### ISSUE TITLE
When I use ESI blocks, the product list query changes

### ISSUE THREAD

**Issue by jonaypelluz** [nexcess/magento-turpentine#575]
When I add this to the product_list block:

    <action method="setEsiOptions">
        <params>
            <access>public</access>
            <scope>page</scope>
             <registry_keys>
                  <current_category />
                  <query_request />
             </registry_keys>
        </params>
    </action>

It works for a simple category list, but if I filter the list using "Layered navigation 2.0 extension" and with my custom attributes the query for the product ain't right, and I don't know how I have to pass that data to turpentine, in the example it is not clear and I can't find examples to know how to pass custom data to Turpentine.  I suppose the idea is to use registry_keys but I can't find a way to do it.

**Comment by aricwatson** [comment]
Not all 3rd party extensions are going to work well with Turpentine/Varnish, but we'll try to help as much as possible.

It appears that the "Layered navigation 2.0" extension uses ajax, so you might try adding the ajax call URLs to the URL blacklist in the Varnish configuration section to make sure those ajax calls don't get cached.

This is an older issue, so I'll close it - but feel free to reply if this is still an active problem and we'll help out more.
