### ISSUE TITLE
"ESI processing not enabled" when "Varnish ESI Blocks" cache is enabled.

### ISSUE THREAD

**Issue by strocknar** [nexcess/magento-turpentine#578]
As stated, if I have the Varnish ESI Blocks cache enabled then I get the "ESI processing not enabled" error. However, if I disable this cache then everything works as normal. No other caches are enabled (aside from "Varnish Pages").

I have refreshed the cache both within the admin console and by restarting Varnish/deleting magento/var/* from disk.

I'm not really sure where to look to start troubleshooting. Any help would be greatly appreciated.

**Comment by aricwatson** [comment]
Closing for lack of feedback.
