### ISSUE TITLE
getEsiOptions is empty even due it is set in turpentine_esi.xml

### ISSUE THREAD

**Issue by michel3vb** [nexcess/magento-turpentine#583]
Hi,

I have a very strange problem with one ESI block on our website. We use several ESI blocks without any problem but this one won't load. On a product page i want to load the "add to cart" button via ajax. For some products this button must disabled when i user is not logged in or is not complety configured.

I have the following code:

*app/design/frontend/base/default/layout/turpentine_esi.xml*
``` xml
<reference name="product.info.add.to.cart.box">
    <action method="setEsiOptions">
        <params>
            <access>private</access>
            <method>ajax</method>
        </params>
    </action>
</reference>
```
*app/design/frontend/company/default/layout/catalog.xml*
```xml
<catalog_product_view translate="label">
		.....
        <reference name="content">
            <block type="catalog/product_view" name="product.info" template="catalog/product/view.phtml">
			   .....
                <block type="catalog/product_view" name="product.info.add.to.cart.box" as="product_info_add_to_cart_box" template="catalog/product/view/addtocartbox.phtml" />
				.....
```
In *app/design/frontend/company/default/template/catalog/product/view.phtml* i have added:
```php
<?php echo $this->getChildHtml('product_info_add_to_cart_box'); ?>
```
And in *app/design/frontend/company/default/template/catalog/product/view/addtocartbox.phmlt* something to display the "add to cart" button

The problem is that product.info.add.to.cart.box is not recognized as an ESI block. In the logs i see  `Checking ESI block candidate: product.info.add.to.cart.box`. This block is also a instance of Mage_Core_Block_Template. It goes wrong when ESI tries to do `$blockObject->getEsiOptions()`. This returns nothing! The block would be added like a normal block and not via an Ajax request.

I have also tried to set the ESI options manually. In *app/code/community/Nexcesset/Turpentine/Model/Observer/Esi.php* i have added the following if statement in the injectEsi function:
```php
if($blockObject->getNameInLayout() == "product.info.add.to.cart.box")
{
    $blockObject->setEsiOptions(array( "method" => "ajax", "access" => "private"));
}
```
After submitting this code the block is loaded via Ajax. But i get an endless loop because each Ajax block loads a new block.

Does anyone know what going wrong? Why is getEsiOptions empty in this particular case?

**Comment by dhpowrhost** [comment]
Did you ever solve this. I am having the exact same issue

**Comment by michel3vb** [comment]
No sorry i have never solved this problem....

**Comment by raulvian** [comment]
I have experienced similar issues

I have solved them by adding the setEsiOptions code directly in the concrete layout files, where desired block is defined
