### ISSUE TITLE
customizing vcl to ignore additional tracking variables in query string

### ISSUE THREAD

**Issue by matt453** [nexcess/magento-turpentine#589]
I believe I am having an issue where additional unique identifiers are being added to query string from email tracking generated links and this is causing a lot of cache misses.

I want turpentine to ignore these unique query strings and pull the cached version 

additional possible fields are: 
trk_msg
trk_contact
trk_module

how do I customize the vcl to account for this.  when I edit the default.vcl directly it doesn't seem to take.  also is this code chunk the place where I should be doing this editing:

if (req.url ~ "[?&](utm_source|utm_medium|utm_campaign|gclid|cx|ie|cof|siteurl)=") {
set req.url = regsuball(req.url, "(?:(\?)?|&)(?:utm_source|utm_medium|utm_campaign|gclid|cx|ie|cof|siteurl)=[^&]+", "\1");
set req.url = regsuball(req.url, "(?:(\?)&|\?$)", "\1");
}

**Comment by aricwatson** [comment]
As of 0.6.2 you can now enter parameters that Varnish will ignore when caching:
https://github.com/nexcess/magento-turpentine/wiki/Configuration#parameter-based-caching
