### ISSUE TITLE
update docs to make an important notice on Crawler IP Addresses setting under Caching Options

### ISSUE THREAD

**Issue by arosenhagen** [nexcess/magento-turpentine#596]
Since it is very likely that one have some sort of proxy-setup when using turpentine, I advise to do an important notice on _Crawler IP Addresses_ setting under _Caching Options_ as per #91 
We use nginx:80/:443 --> varnish:6081 --> nginx:8080 to do proper ssl-offloading and it is VERY likely that requests hit varnish/turpentine with 127.0.0.1. Therefore customers might share the crawler session and see carts from other customers! In my eyes this setting should be left empty overall.

**Comment by miguelbalparda** [comment]
We added this to the documentation and also a comment in the field. Thank you for your contribution guys!
