### ISSUE TITLE
Only One Footer Cached if There are two Different Footers

### ISSUE THREAD

**Issue by frognrainbow** [nexcess/magento-turpentine#603]
My theme having two differently designed footers, Footer A (normal) for other pages, Footer B (minimized) for Login related pages (Register Account, Forgot Password, etc.).

When both footer A and B are set as ESI public, only the first displayed footer (Ex. only Footer A) cached and overwrite the place Footer B should be (or, Footer B in the place of Footer A).

Footer A is the default Magento footer layout, and the following is the Footer B layout.
<block type="page/html_footer" name="footer.mini" as="footerMini" template="page/html/footer-mini.phtml"></block>

In template, Footer B is only specified in a custom created page template named 1column-simple.phtml and called Footer B alias manually.
*Footer A is not specified in this template 1column-simple.phtml . In HTML, both footer A and B having the same id & class "footer".

If I change the ESI to both private, this issue resolves.
But other settings, like Footer A private and Footer B public, doesn't resolve.
*My theme also having 2 different headers (specified almost the same as Footer B), but these headers are working flawlessly without any additional settings.

Does anyone know how to cache both footers publicly and displayed as the specified?
Will the block specified type="page/html_footer" be the cause of it?

Sorry for my primitive question if it is, maybe I missed something important basics.
But hope someone had the same issue resolved, or point out my mistakes.

**Comment by craigcarnell** [comment]
I've seen this issue too

**Comment by aricwatson** [comment]
@craigcarnell did you see this with a custom theme?
