### ISSUE TITLE
Lot of issues: Add to Compare, Add to Cart, Recently Viewed

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#608]
Turpentine is a great extension, one of the best in my opinion for speeding up the website, but is has a lot of issues related to frontend blocks I need a fix:

My configuration (updated):
VMware 10 (4 Core 4 Ghz, 16 Gb RAM DDR3, SSD)
Debian 7,6
Nginx 1.6.1 (basic configuration) + PHP-FPM + MySQL
Varnish 3.0.5 (default configuration)
Magento 1.9.0.1 (out of box)
Turpentine 0.6.0 installed via Downloader

Intro: Using default.vcl provided by Varnish page load time is around 350 - 400 ms, using default.vcl provided by Turpentine page load time decreases extraordinary to only 6 - 10 ms. But I have a lot of issues related to Magento messages and Magento side-boxes.

1) Clear Cart is not updating My Cart block in the header. It remains with 1 product. I click inside the block then X button, nothing happening. If you navigate to a category this block updates to 0 items, but visiting a product it still has the product inside. I add another product to cart. Now in cart page I see the right product, I can update or clear, but in block it still the product I cleared before.

2) My Cart side block (right panel). It shows the product I deleted, now updates.

3) Recently Added Item(s) side block (right panel). It shows the product I deleted, even I add 2 - 3 products to cart.

4) Compare Products side block (right panel). When you add a product for compare it is not showing inside this block. I used my default.vcl from Varnish default to get this working. I have a product to compare, now I can use Compare, All Clear button. Let's add a new product to Compare. Nothing happening, no Magento message at the top. If you click on Compare, product you just added is listed! Deleting individual compare products is not working. If you click All Clear you will be redirect to Home page or Cart page (for some situations). When I visit other product page, a group of Magento messages appears, informing I added 1 - 2 product to compare, I remove one from compare, I cleared out the compare list.

5) Recently Compared Products side block (right panel) shows wrong products.

6) Popular Tags is not adding new tags

7) Community Poll is not working. You choose and option then Vote, page is reloaded and nothing.

8) Recently Viewed Products is not updated according to products visited.

What shall I do? I want to use this extension but I can. Having a lot of side blocks with wrong content and behavior I cannot leave it just like that. I appreciate if you provide me a fix for this.

**Comment by onimsha** [comment]
@ADDISON74 : Can you share with me how you fixed the Recently Viewed Products block? Currently i have no idea about disable caching for that block.

Thanks!

**Comment by ADDISON74** [comment]
Just reinstall everything from scratch and it is working fine. This extension is a must-have for any Magento shopping cart, but it has to updated to 1.9.1. It's been more than 6 months from 1.9 release and I wonder if this extension is really updated. I guess the project is dead.

**Comment by crasx** [comment]
There are plenty of projects that go without updates for years. They may have bugs but still work. You have opened so many bugs in this project that are obviously related to misconfiguration. In fact you have opened this same bug 3 times already. I suggest you learn more about how to correctly configure varnish and stop opening duplicate bugs and stop talking crap about a free extension while doing nothing to make it better. Doing so only wastes the developer's time.

**Comment by ADDISON74** [comment]
@crasx - don't be rude. If you are a developer inside this project I can accept your comments, but only if your are developer. You made some accusations without having some respect to my person or work. I am computer science engineer with tons of degrees. For 6 years I worked as beta tester for two important shopping carts in the world. Now I am learning Magento World. Why are you so sure it is a misconfiguration? Do you think you are talking to a newbie? If your picture is real you are half of my age, don't have a lack of respect. Please do a search for my issues again to see them as confirmed bugs and corrected by Turpentine's developers.

**Comment by aricwatson** [comment]
Closing this issue in favor of the specific issues already open for each problem.
