### ISSUE TITLE
IP Address Logging

### ISSUE THREAD

**Issue by theycallmepepper** [nexcess/magento-turpentine#609]
I know its noted in the description that currently all guest IPs will be logged the same.  I was wondering if we could discuss the workaround options more. 

Also, I found an article regarding correcting an issue with logging IP addresses behind a load balancer (Rackspace (formerly mosso) is specifically noted but this may apply to other scenarios).

Apparently this can be added to the global section of a module to help pull the correct information in for magento to gather.

```
<remote_addr_headers>
<!-- list headers that contain real client IP if webserver is behind a reverse proxy -->
          <header1>HTTP_X_FORWARDED_FOR</header1>
          <header2>HTTP_X_REAL_IP</header2>
          <header3>REMOTE_ADDR</header3>
</remote_addr_headers>
```
http://www.magentocommerce.com/boards%20/viewthread/37749/ is the article.

I understand these may be two separate and potentially unrelated problems and will hopefully have some time to set up a dev environment where I can investigate this soon.

Can anyone weigh in?

**Comment by aricwatson** [comment]
In case this helps you or others - we (Nexcess) use the apache module mod_extract_forwarded to grab the real IP from the *X-Forwarded-For* header. After installing the module the following config changes are made:
```
echo "MEFaccept 127.0.0.1" >> /etc/httpd/conf.d/mod_extract_forwarded.conf
echo "MEFaccept xx.xx.xx.xx" >> /etc/httpd/conf.d/mod_extract_forwarded.conf
```
