### ISSUE TITLE
Community Pole not working with Turpentine

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#612]
Testing platform:
- Magento 1.9.0.1 + Sample Data - no changes, out of the box
- Varnish 3.0.5 + Turpentine 0.6.0 - default VCL

I found an issue related to Community Poll module. I vote and nothing is happening. I switched back Nginx on port 80 and I have no issues. After I voted page is reloaded showing votes then Community Poll block disappears as usual. 

I flushed Magento cache, Storage cache, my browser cache and I checked with SSH if sessions and cache still on disk. All cleaned as wanted. Still no cache to vote and see the votes.

For the moment I will disable the module in backend. I really recommend Turpentine because it makes website flying for sure. From 26 requests per second and 1700 ms (c100 n1000 in AB) I boosted to 1200 requests pe second and only 30 ms per request. There is no need using Full Page Cache with such of performance.

Please I need a fix as soon as possible. If other blocks are not working as requested please provide a solution to disable Turpentine for them. Thank you!

**Comment by aricwatson** [comment]
Community poll issues should be fixed as of Turpentine 0.6.2
