### ISSUE TITLE
Error when Appling Varnish Config - varnish 4.0

### ISSUE THREAD

**Issue by marcosdemasi** [nexcess/magento-turpentine#615]
Hi,

   After following all the installation instructions (and double check on it) I am quite convinced that it is not working properly.
    When I go to System->Cache Management and click on "Apply Varnish Config" button, I saw the following error message:

Failed to apply the VCL to 127.0.0.1:6082: Got unexpected response code from Varnish: 106 Message from VCC-compiler: Module std already imported. ('input' Line 31 Pos 1) -- ('input' Line 31 Pos 10) import std; ##########- Previous import was here: ('input' Line 27 Pos 1) -- ('input' Line 27 Pos 10) import std; ##########- Running VCC-compiler failed, exit 1 VCL compilation failed

```
By checking the file MAGENTODIR/var/varnish/varnish.vcl I believe that all fields were filled correctly. 

Could someone help me to identify the root cause for this problem?
```

Thanks,
Demasi

**Comment by federicosoich** [comment]
Hi Jan, i'm using your project in my ubuntu localhost.
With Xampp, Magento 1.9.0.1 and varnish 4.0.3.
I have a error Varnish socket write error: 8192 != 9612 when i try to save configuration.
I tried configuring   const CLI_CMD_LENGTH_LIMIT  = 8192; in
/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php
and also other numbers, but with not success.
Any idea ?
Thanks
Federico
![varnish error](https://cloud.githubusercontent.com/assets/2135553/6847171/2de42052-d3a3-11e4-9d54-80daf5ae10ba.png)

**Comment by eth8505** [comment]
@federicosoich I have since quit the magento world and hence are no longer working on the varnish4 support. The error message however looks like you need to modify your cli_buffer varnish setting in varnish itself.

**Comment by federicosoich** [comment]
@eth8505 Thanks for your reply. I´ll try this.
