### ISSUE TITLE
How to add an exception for track affiliates?

### ISSUE THREAD

**Issue by hadikalantari** [nexcess/magento-turpentine#620]
our affiliate system use "?acc=" parameter in url to track referrer, I add this code to vcl file to prevent caching any url that contains "acc" parameter:
if(req.url ~ "\?.*acc=") {
			return (pass);
		}

it works and pages with this parameter, will not be cached. 
now, the problem is this pages have no cookie and not able to create cookies, so our affiliate system not work.

thank you.

**Comment by aricwatson** [comment]
https://github.com/nexcess/magento-turpentine/issues/440 may be useful.

**Comment by aricwatson** [comment]
Closing for lack of feedback.
