### ISSUE TITLE
Default Cpanel/Apache Configuration Page

### ISSUE THREAD

**Issue by sabonmichal** [nexcess/magento-turpentine#636]
Hi,

I am using cpanel on aws lamp stack and the turpentine settings apply correctly but when I go to my homepage it shows the default cpanel/apache system config. page. How can I get it to show my website? 

I noticed that if I change 127.0.0.1 in turpentine settings and varnish config files to the private IP of the aws instance, the homepage loads but the user login doesn't work. The same site is working fine with user login on a lemp stack so I thought it must have something to do with apache or cpanel config.

Thank you in advance for your help :)

**Comment by aricwatson** [comment]
>The same site is working fine with user login on a lemp stack so I thought it must have something to do with apache or cpanel config.

It certainly sounds like a config issue unrelated to Turpentine. You might try asking the question somewhere like serverfault - we can't really help with this here.
