### ISSUE TITLE
OnePageCheckout

### ISSUE THREAD

**Issue by Krapulat** [nexcess/magento-turpentine#639]
Hi,

Magento Turpentine have problems with One Page Checkout module ( https://www.iwdextensions.com/magento-one-step-checkout-module.html ). I get 403 error in nginx when the module do an ajax update ( "POST /onepagecheckout/index/updateCheckout/"), and then it returns to  "/checkout/cart/".

I've solved this adding to varnish:

if (req.url ~ "onepagecheckout")
{
     return(pipe);
}

Is there a more elegant solution?

**Comment by theycallmepepper** [comment]
You could add ```onepagecheckout``` to the url blacklist in the magento admin panel.
