### ISSUE TITLE
Step 5 Of Checkout Showing Previous User's Cart Contents

### ISSUE THREAD

**Issue by sabonmichal** [nexcess/magento-turpentine#643]
At step 5 of checkout/onepage, items in last user's cart are displayed. These items are not displayed when user clicks on view cart. This issue might be related to issue #455.

**Comment by miguelbalparda** [comment]
@sabonmichal do you hav more info about this? Magento version, Turpentine version, VCL, etc. We did somemajor changes the last few months, I suggest you to try the new versions to see if this now works as expected. I'l close the issue for now,feel free to reopen it anytime with some more info.
