### ISSUE TITLE
vcl code to remove double slashes breaks query string parameters with urls

### ISSUE THREAD

**Issue by joolswills** [nexcess/magento-turpentine#645]
the file app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl contains

```
    # remove double slashes from the URL, for higher cache hit rate
    # set req.url = regsuball(req.url, "(.*)//+(.*)", "\1/\2");
```

this breaks any querystrings that have a url passed to them - in our case, we have wordpress in a subfolder from our magento site (varnish doesn't cache it, but it sits behind varnish), that has a thumbnailing script that gets passed a full url. this varnish code strips a slash from a parameter breaking it.

I'm unsure how removing a slash from the url increases cache hits - is that in relation to something specific to turpentine/magento ? I assume the reg exp could be made to match specifically the beginning of the url to avoid breaking query string parameters anyway (with a ^).

I'm happy to provide a patch, but I wanted to understand the purpose of this first. thanks.

**Comment by aricwatson** [comment]
Looks good to me! Just added this regex tweak to *devel* - thanks @joolswills

**Comment by joolswills** [comment]
Cheers.
