### ISSUE TITLE
PHPSESSID generated on redirect

### ISSUE THREAD

**Issue by nicofff** [nexcess/magento-turpentine#649]
A PHPSESSID cookie is being generated when the "Use SID on Frontend" is enabled and the user is redirected from an unsecure admin url to a secure one.
I was able to reproduce this in two different stores, one with Magento 1.8 and other with Magento 1.9.

Steps to reproduce:
1. Have a site that uses https for it's secure_base_url
2. Have "Use SID on Frontend" enabled in System->Config->Web->Session Validation Settings
3. Browse to http://yoursite.com/admin

You should get redirected to the https version of the admin console, and you should have that cookie set.

I've tracked the issue to this call: https://github.com/nexcess/magento-turpentine/blob/master/app/code/community/Nexcessnet/Turpentine/Model/Observer/Esi.php#L82
in the redirect Observer. 

I'm seeing some caching issues on one of the stores, don't know if related to this. I'll update if I find out something else

**Comment by miguelbalparda** [comment]
@nicofff did you find a fix for this?

**Comment by nicofff** [comment]
I think we disabled the use SID option. But I'm not sure

**Comment by aricwatson** [comment]
Closing for lack of feedback.
