### ISSUE TITLE
Failed to apply the VCL to 127.0.0.1:6082: Failed to read response code from Varnish

### ISSUE THREAD

**Issue by harry882** [nexcess/magento-turpentine#654]
Hi,

I am getting the error on saving configuration : :

Failed to apply the VCL to 127.0.0.1:6082: Failed to read response code from Varnish

**Comment by kingdiablo** [comment]
I also have this same error.

**Comment by somokanta** [comment]
Can anyone explain me why this error comes while all configuration is perfect as per instruction ??
I am getting same error while saving and applying varnish config.

**Comment by miguelbalparda** [comment]
@somokanta we could use some more info about your problem like Turpentine version, Varnish version, Magento version, etc.

**Comment by somokanta** [comment]
Thanks for quick response. 

I have installed 
magento version : 1.9.2.2 
Turpentine version: 0.6.3 ( also tried 0.6.8 latest version)
Varnish version: 3.0.7 (also tried 4.0.2 latest one)

Any help will be much appreciated.

**Comment by miguelbalparda** [comment]
Have you selected the correct version in the Turpentine admin section?

**Comment by somokanta** [comment]
Yes I have tried both  Auto and by selecting 3.x, still same issue .

**Comment by somokanta** [comment]
So in socket.php file in _read() function when i have logged $code value it is returning 0 (zero). can you explain me what could be the root cause of it?

**Comment by miguelbalparda** [comment]
Is there anything in the Varnish logs? I don't think this is a Turpentine issue but a Varnish problem.

**Comment by somokanta** [comment]
Nope nothing, the issue comes when you apply varnish config from Magento backend.

**Comment by robsonschneider** [comment]
Are there some news about this topic? I think it is with no solution yet. Right?

**Comment by miguelbalparda** [comment]
@robsonschneider there are multiple causes and solutions for this issue documented in this repo, have you checked the closed issues?

**Comment by miguelbalparda** [comment]
Most of the time this is caused by an error in the admin configuration , specifically in the Turpentine section, causing Magento  not being able to communicate with Varnish. Search the repo for "Failed to apply the VCL" for open and closed issues to learn more.
