### ISSUE TITLE
Dummy Comments in HTML source

### ISSUE THREAD

**Issue by Krapulat** [nexcess/magento-turpentine#657]
Hi,

I'm getting comments like these in my HTML source:

What do they mean? Is anything wrong ?

Thanks

**Comment by BarryCarlyon** [comment]
I removed them to do ill effects myself

**Comment by aricwatson** [comment]
The "DUMMY CONTENT" tags were added as a workaround a specific Varnish problem originally discussed here https://github.com/nexcess/magento-turpentine/issues/110. As such, if you decide to remove them you may experience intermittent issues with ESI.
