### ISSUE TITLE
Varnish esi_syntax param is not set correctly AND Failed to apply the VCL to 127.0.0.1:6082: Varnish data to write over length limit by XX characters

### ISSUE THREAD

**Issue by mastubbs** [nexcess/magento-turpentine#658]
Hello!

Im setting up Turpentine for the first time and i must confess from the outset that i have not used varnish before so there is a lot for me to learn here.

I have installed and configured as per the documentation however when i try to apply varnish config from cache management i get two errors: 

1) "Failed to apply the VCL to 127.0.0.1:6082: Varnish data to write over length limit by 896 characters"

2) Varnish esi_syntax param is not set correctly.

I have searched extensively and tried the fixes suggested in other posts regarding problem 1 (which i can see has caught a few people out). I have certainly set cli_buffer=16384 but that doesn't seem to have done the trick.

Regarding problem 2, i haven't been able to find much about that on GitHub or in Google (which is always a worrying sign!)

If you can think of any problems that might be causing these two errors i would be most grateful. Of course, it could be two separate issues or they could be connected.

Very many thanks in advance for any help or advice you might have.

PS I am using the latest version of Turpentine and Magento, Varnish and Cent OS 6.5.

**Comment by Knase** [comment]
This is fixed problems:
DAEMON_OPTS=" 
             -p cli_buffer=16384 \
             -a :80 \
             -T localhost:6082 \
             -f /etc/varnish/default.vcl \
             -S /etc/varnish/secret \
             -s malloc,256m"
