### ISSUE TITLE
 "topseller" Block and some ESI Blocks disappear

### ISSUE THREAD

**Issue by content3** [nexcess/magento-turpentine#666]
Actual we try to implement your Turpentine Extension in one of our customers Magento Installation.
Unfortunately the Varnish Connection fails in some points. e.g. "topseller" Block and some ESI Blocks disappear.

May you can help us fix the problem or give us a hint?

Thanks in Advance and best regards!

**Comment by aricwatson** [comment]
Appreciated, but we cannot provide direct help to non-Nexcess clients :) 

Hopefully you found a developer to help you!
