### ISSUE TITLE
Invalid URI supplied 

### ISSUE THREAD

**Issue by kevin25** [nexcess/magento-turpentine#667]
I use Channel Advisor, but when i upgraded varnish to 3.0.6, it doesn't work. 

tracking.searchmarketing.com/click.asp?AID=120156480000028375&CAPCID={CREATIVE}&cadevice={device}

The error message:

Trace:
#0 /chroot/home/domain/domain.com/html/lib/Zend/Uri.php(143): Zend_Uri_Http->__construct('http', '//www.domain...')
#1 /chroot/home/domain/domain.com/html/lib/Zend/Controller/Request/Http.php(113): Zend_Uri::factory('http://www.domain...')
#2 /chroot/home/domain/domain.com/html/.modman/magento-turpentine/app/code/community/Nexcessnet/Turpentine/Model/Dummy/Request.php(44): Zend_Controller_Request_Http->__construct('http://www.domain...')
#3 /chroot/home/domain/domain.com/html/.modman/magento-turpentine/app/code/community/Nexcessnet/Turpentine/Helper/Esi.php(184): Nexcessnet_Turpentine_Model_Dummy_Request->__construct('http://www.domain...')
#4 /chroot/home/domain/domain.com/html/.modman/magento-turpentine/app/code/community/Nexcessnet/Turpentine/controllers/EsiController.php(95): Nexcessnet_Turpentine_Helper_Esi->getDummyRequest('http://www.domain...')
#5 /chroot/home/domain/domain.com/html/app/code/core/Mage/Core/Controller/Varien/Action.php(419): Nexcessnet_Turpentine_EsiController->getBlockAction()
#6 /chroot/home/domain/domain.com/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('getBlock')
#7 /chroot/home/domain/domain.com/html/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /chroot/home/domain/domain.com/html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#9 /chroot/home/domain/domain.com/html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#10 /chroot/home/domain/domain.com/html/index.php(88): Mage::run('default', 'store')
#11 {main}

I found out that the error came from {CREATIVE} and {device}. How can I make turpentine accept {}?

**Comment by miguelbalparda** [comment]
@kevin25 this is not an issue in the extension, this is regular varnish behaviour. I suggest you to put this same answer in StackExchange where someone will be able to better assist you.

**Comment by websiteduck** [comment]
This is also on StackOverflow with no answers: http://stackoverflow.com/questions/26750642/invalid-uri-supplied-magento-turpentine

If this is regular varnish behavior, shouldn't it work with turpentine?  

Is there a setting in varnish to make it not use curly braces?  or a setting in turpentine to replace them with something else that works with Zend_Uri?

**Comment by miguelbalparda** [comment]
Have you tried to encode the url with urlencode and/or escaping the {} with '' or ""?
