### ISSUE TITLE
Block is caching when Customer Logged in, but not when non logged in user opens the page

### ISSUE THREAD

**Issue by jaypatel16** [nexcess/magento-turpentine#669]
Hello,
 I am facing very strange issue. I am calling one block using ESI Ajax method and with private access. 
If I open any product page from guest then block is coming form Ajax. If I open same page from logged in user after that then also block is coming fine.
But if I open the product first with any user logged in the block is getting cached. and same data appear for non logged in user also.

My ESI Policy
```xml
In Default
 
<reference name="product.info.addtocart.oneclick">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <flush_events>
                        <catalog_controller_product_view/>
                    </flush_events>
                </params>
            </action>
        </reference>

for <catalog_product_view>

<reference name="product.info.addtocart.oneclick">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <method>ajax</method>
                </params>
            </action>
        </reference>

```
Log

2014-11-08T12:16:06+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: product.info.addtocart.oneclick
2014-11-08T12:16:06+00:00 INFO (6): TURPENTINE: Block check passed, injecting block: product.info.addtocart.oneclick

Please suggest me. what is wrong with my policy

**Comment by aricwatson** [comment]
Apologies for the late reply. 

I suspect setting two different policies for the same block is causing problems. I'd suggest sticking with one. 

Since this issue is so old, I'm going to close it - but if you're still having problems feel free to reply and we'll continue to try to help you.
