### ISSUE TITLE
 Fatal error: Call to a member function setTitle() on a non-object in Mage_Customer_Block_Form_Register.php on line 48

### ISSUE THREAD

**Issue by heliob** [nexcess/magento-turpentine#671]
I am got the  
Fatal error: Call to a member function setTitle() on a non-object in Mage_Customer_Block_Form_Register.php on line 48

just when I apply varnish config with Varnish Pages/TURPENTINE_FAKE_PAGE_TAG is enable

**Comment by epiblue** [comment]
@heliob 

Did you manage to solve this? I'm having a similar isssue: ( #720 )

Thanks,

**Comment by heliob** [comment]
i dind't
i just turn off checkbox block_html cache option, its works for me

2015-01-07 9:18 GMT-02:00 Artur <notifications@github.com>:

**Comment by theycallmepepper** [comment]
To clarify, you disabled the default magento ```BLOCK_HTML``` cache?    There are some other issues open that relate to this, I'll try to tag them when I get a moment.

**Comment by aricwatson** [comment]
Closing for lack of feedback.
