### ISSUE TITLE
Force To Desktop

### ISSUE THREAD

**Issue by kevin25** [nexcess/magento-turpentine#672]
Hello, 
I used turpentine with custom vcl to redirect mobile agents to mobile site:
sub vcl_recv {
if (req.http.user-agent ~ "iP(hone|od)|android|(?i)^samsung|(?i)android|(?i)android 3") {
error 750 "Moved Temporarily";
}
}

sub vcl_error {
if (obj.status == 750) {
set obj.http.Location = "http://m.website.com" + req.url;
set obj.status = 301;
return(deliver);
}
}
By the way, on mobile site we have the  url: 
http://www.website.com/?mredirect=yes
Is there any way to force mobile agents to desktop version? It means have url will work.

Thanks!

**Comment by aricwatson** [comment]
I apologize for the delay getting to this issue as we work through our backlog. 

I'm not sure I totally understand the issue, however you may need to look at the URL parameter options to achieve what you're looking for.

Please feel free to reply and I'll re-open the issue to continue discussion.
