### ISSUE TITLE
ESI processing not enabled

### ISSUE THREAD

**Issue by danielrona** [nexcess/magento-turpentine#68]
Hello,

I'm running Magento CE 1.7.0.2 with Varnish 2.1.3 and the latest turpentine from Magento Connect on a debian 2.6.32 kernel

As soon as I turn on the ESI Blocks in Cache Management I get the well known ESI processing not enabled error.

The following headers are returned with debug enabled.

> Age    45
> Connection keep-alive
> Content-Encoding   gzip
> Content-Length 6571
> Content-Type   text/html; charset=UTF-8
> Date   Thu, 21 Feb 2013 08:23:55 GMT
> Server Apache
> Via    1.1 varnish
> X-Turpentine-Cache 1
> X-Turpentine-Esi   1
> X-Varnish  1837777343 1837777340
> X-Varnish-Hits 1

The HTML Sourcecode in the Browser looks as follows.

``` php
<esi:remove>ESI processing not enabled</esi:remove>
<!--esi <esi:include src="link_to_esi_url" /> -->
```

The Link to the ESI Url is working and does actually return content with the following headers

> Age    0
> Connection keep-alive
> Content-Length 9826
> Content-Type   text/html; charset=UTF-8
> Date   Thu, 21 Feb 2013 08:30:04 GMT
> Server Apache
> Via    1.1 varnish
> X-Turpentine-Cache 0
> X-Turpentine-Esi   0
> X-Varnish  1837777363
> X-Varnish-Hits 0

I've purged all caches, tried to disable all types except Varnish ones, I still get that error there no other addons enabled that should conflict with turpentine.

Maybe you have any idea what I'm missing.

**Comment by keyur-iksula** [comment]
Any one have better solution ?? as i have installed latest version varnish 3.0.5 still its not working.

**Comment by miguelbalparda** [comment]
@keyur-iksula please see the devel branch, you are a couple of versions behind.

**Comment by keyur-iksula** [comment]
Thanks Miguel, i have upgraded to latest version as per your suggestion and then written hole punching code in turpentine_esi.xml, looks working fine for me.
