### ISSUE TITLE
I don't need a gun. This extension is perfect for killing me!

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#690]
Magento 1.9.0.1 -> Default installation, sample package
Varnish 3.0.6 (latest)
Apache 2.2.29 (latest)
PHP 5.5.19

Everything is configured and working till a point, a random one in time. 

1) I want to add a product in cart, but cart page shows empty cart . I visit my website over 2 - 3 hours, it is working. Then again not working.

2) I visit the vebsite with icognito mode in Chrome. I want to add a product I get the page about Cookies. Ok, I am running other computer with other IP address. Even I am not in icognito mode, I get the cookie page when I use the website. This means one thing, I get the session from the other computer, the one in icognito mode. I am clearing Magento cache directly inside folders, media/catalog/product/cache, media/css, media/js, var/cache, var/sessions, var/reports, browser cache, reload Varnish. It is working for a while then again same issue. This is for sure the same problem with cookie.

3) I wanted to access my admin backend in Magento. I couldn't. I deleted everything related to Magento Cache in Terminal. After using username and password page reloads with empty inputs. I should go and edit /app/etc/modules/Nexcess_... file to set module to false in order to get access again to admin area.

I have to mention everything is set up according to your tutorials (secret key, symbolic link to varnish folder, ports, parameters) It is working but it fails over a while. I am not a basic user in Linux just an advanced one. This extension is unstable, it provide good results, but also bad results. With such of issues I will make my visitors nervous for sure. If you really want to continue providing this extension please do an effort and correct everything which is not working. Varnish is one of the best tools for web caching, maybe the best one, it speed up a website, it is great when attacks are done, but without a good configuration file it is nothing. Sorry to say it one more, this extension is not a final product, just something made for fun and testing. This is not normal. 

Thank you for your understanding. I have to go back to my Lesti FPC with 90 req/sec instead of using Varnish on my dedicated server with 3900 req/sec. Hope you do something asap, just make it working. If not more and more will be frustrated like me.

**Comment by ADDISON74** [comment]
Bump

**Comment by aricwatson** [comment]
See related: https://github.com/nexcess/magento-turpentine/issues/697

**Comment by mabigo** [comment]
i know where is the problem. actually i found a solution for all issues with "random" empty cart problems. (there are a lot of them starting with #84). For now i'm too lazy and have no idea how to make a pull-request here on gh. By the way last review on magentoconnect gives a big hint to where the problem came from.

**Comment by miguelbalparda** [comment]
Thank you for the heads up @mabigo! If you don't have time to make the PR please let me know what should we look after to improve the extension in this issue. Thank you!

**Comment by miguelbalparda** [comment]
It seems #832 has a fix for this issue. would you mind giving it a try? It is on the devel branch until further testing.
