### ISSUE TITLE
ESI Processing Not Enabled - Only randomly

### ISSUE THREAD

**Issue by theycallmepepper** [nexcess/magento-turpentine#691]
Varnish 3-Magento 1.8-Apache2- Turpentine 0.6

Just switched to a new more customized theme.  I set up the esi profiles for the blocks in local.xml as some new ones had been added or names changed from the defaults.  Once I took care of that, things seemed to be working perfectly fine, but every once and a while you'll see some blocks missing with the "ESI Processing Not Enabled".

I've already set the extra parameters in the daemon options.  What else should I be looking for? Anything specific to check logs for? (Especially since I can't easily reproduce it)

Thanks ahead of time!

**Comment by aricwatson** [comment]
This issue https://github.com/nexcess/magento-turpentine/issues/64 might be helpful. Otherwise, without a way to reliably replicate the issue it's difficult to help you debug.
