### ISSUE TITLE
MCE 1.9.0.1, RWD theme, list more than ~15 products

### ISSUE THREAD

**Issue by gewaechshaus** [nexcess/magento-turpentine#692]
Hello,

if i list more than 12 items in grid or list while varnish esi blocks are enabled, the products list stops rendering while getting the add to cart url including the formkey  (in most cases after 15-25 products).
If i disable esi blocks for debugging it works, so it has to be anywhere in the near of this ;)

Can anybody reproduce this? U can test this quickly with the limit dropdown in products grid...

**Comment by aricwatson** [comment]
If this is still a problem, could you test with the current *devel* branch to see if there's any improvement?

**Comment by aricwatson** [comment]
Closing this issue because of age, but if this problem is still occurring using *devel* or 0.6.3 or higher, we'll definitely open it back up and investigate further.
