### ISSUE TITLE
Community Pole is cached!

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#697]
I am using Community Pole because over years I got a lot of good information using it. I am testing Turpentine because Varnish in my case can deal with 4000 requests/second with no fails. For small DDoS this really helps you using the webserver and finding solutions instead of switching off the line. 

I have an big issue with this side block module. According to Turpentine docs Community Pole is not cached, but as I found in all my tests it is! I see the side block, I vote, nothing happens. Still there. Unfortunately I did not find a tutorial for blacklist URL's (maybe that's the main reason a lot of issues reported here are related to 3rd party extensions, if someone will do a tutorial for this I guarantee no more issues with extensions). 

Here are my intuitive steps I did:

1) I checked the frontend source code for that Poll form . URL is http://192.168.159.123/poll/vote/add/poll_id/1/. 

2) In Admin -> System -> Configuration -> Caching Options, I set in URL Blacklist on a new line part of the URL /poll/vote/add/poll_id.

3) I cleared the whole cache, refreshed all cache types, cleared browser cache. I can vote, I see the results, but if I go back to a previous page, poll is still there. Or if I am using the Layering Navigation, when I clearing the options, I see the poll back. Default Magento behavior is once you vote you see the results then it disappears from that session. Even you skip from cache, the pole is back, or maybe I have to do more steps. 

I would like if someone could help me with this issue. Also, it will be great having a tutorial for Blacklist URL's, just an example for a known extension.

Thank you.

**Comment by ADDISON74** [comment]
Wow, 5 months ago ...

**Comment by aricwatson** [comment]
I think I've tracked this down. Unfortunately, the poll block works differently from "normal" Magento blocks, in that it uses it's own *setPollTemplate()* method to set two different templates - one for the poll form and one for the poll results. Then, during it's custom *toHtml()* it chooses which to show depending on whether the user's session data shows that they just voted.

So... Turpentine attempt to set the ESI or Ajax template does nothing, since the Mage_Poll_Block_ActivePoll doesn't use *setTemplate()* 

This is why you don't see the *ESI START*, etc comments in the page source, and why you can't use ajax for this block, etc.

I'm working on a fix for this issue.

**Comment by aricwatson** [comment]
Ok, the *devel* branch now includes a fix for this bug. Please test!

**Comment by ADDISON74** [comment]
@aricwatson : Thank you. I just installed dev branch inside a test machine and I confirm this issue is solved. Now Community Poll is working as expected. I can go back to previous page and seeing results instead of poll questions. If I go visiting other pages, even these pages are cached the poll won't appear again or showing results. You did a great job, for almost one year this was a mystery to me and other people. 

I appreciate if you can post the solution with some comments to this issue because it was not a normal one. This issue was inside Turpentine from the very beginning and if there are other blocks same like Community Pole everyone can use this approach.

**Comment by aricwatson** [comment]
My comment https://github.com/nexcess/magento-turpentine/issues/697#issuecomment-105633772 basically lays it out - Turpentine calls *setTemplate()* on ESI blocks to replace the regular templates with the special ESI or Ajax templates. But the poll doesn't actually use *setTemplate()* - so when Turpentine called it, it essentially had no effect on the site. As a result, the poll remained cached. My fix rewrites that poll block to remedy this. 

I wouldn't be surprised at all if similar issues are behind problems with other blocks not caching as expected.

**Comment by ADDISON74** [comment]
@aricwatson: Could you please let me know what files did you edit for fixing this issue? I have problem with secure/unsecured. When I have SSL enabled, voting redirect me from http to a https URL. It is a Magento issue in my opinion I have to fix. Thank you.

**Comment by aricwatson** [comment]
I didn't edit any core files directly, I did put in a rewrite for `Nexcessnet_Turpentine_Block_Poll_ActivePoll` [here](https://github.com/nexcess/magento-turpentine/blob/master/app/code/community/Nexcessnet/Turpentine/Block/Poll/ActivePoll.php) to reimplement the *setTemplate()* method.

**Comment by ADDISON74** [comment]
I will look into these files finding out where is unsecured passed to secure protocol. By the way I reported this in Magento Bug Tracker too.

**Comment by ADDISON74** [comment]
Getting secure protocol after voting is a Magento issue. It comes from this file, line 182:
app/code/core/Mage/Poll/Block/ActivePoll.php

<code>
return array(
    'poll' => $poll,
    'poll_answers' => $pollAnswers,
    $$pollId, '_secure' => true))
);
</code>

Setting _secure to false voting is no considered "a secure" action anymore. I don't understand what Magento engineers had in mind setting this parameter, because when HTTPS in enabled in frontend after voting protocol remain the same, https. If frontend is http mainly but with https for some parts like customer account, voting is passing secure and this create trouble. It is just a visual issue seen in URL bar, not affecting functionality.
