### ISSUE TITLE
Trauma with Varnish 4.0.1_ Turpentine and Magento 1.9

### ISSUE THREAD

**Issue by anderow** [nexcess/magento-turpentine#699]
So I am new to Varnish.
I am running centos 7 on a dedi cloud server which I wanted to install varnish on to improve the speed of my magento store (I run Lesti FPC already) .

I am having serious problems getting it working together.!
I have done all the fixes on here

When I change certain config items in the admin panel, or tell it to write to vcl file I get this

 106 Message from VCC-compiler: Inline-C not allowed ('input' Line 2 Pos 1) C{ ## Running VCC-compiler failed, exit 1 VCL 

When I add this to varnish startup  
d `-p vcc_allow_inline_c=on` to Varnish's startup command.

My site whitepages, and I need to remove the line from Varnish.params and restart varnish to see any of my webpages again!

I have done all the fixes on this excellent article here

https://github.com/nexcess/magento-turpentine/pull/541/files

Slowly errors reduced but I am left with this.
Turpentine states on Magento Connect that it is compatible with 1.9.... however from reading up I have heard mention on here that there is issues but I cannot find out what they are!!!

Could anyone please help me before I jump off a tall building :) It is really getting annoying now.
Alternatively if there is any varnish/magento experts I am more than happy to pay for your help to resolve this. If indeed it can be resolved.

What are my options if Turpentine in fact , cannot run with 1.9 CE? I really dont want lose varnish but this is very bad for my store!!!

Thanks

**Comment by aricwatson** [comment]
I know this tickets quite old, but in my initial testing of https://github.com/nexcess/magento-turpentine/pull/541 with Varnish 4 and CE 1.9.1 I haven't seen many problems yet. I'd suggest disabling Lesti FPC as other caching extensions often cause problems.

**Comment by aricwatson** [comment]
Closing for lack of feedback.
