### ISSUE TITLE
Cutom menu not working with Varnish ESI Blocks!

### ISSUE THREAD

**Issue by sIiiS** [nexcess/magento-turpentine#707]
I used this module with nginx and varnish
nginx port is 8080 and varnish is 80
when I enable "Varnish ESI Blocks" cache then my custom menu do not appear in 80 but load in 8080 and when I disable "Varnish ESI Blocks" cache then in both work without problem, how can I solve this problem ?

**Comment by imitaz** [comment]
i have an issue menu load correct on first hit but when i open any other page menu load from base thme not my smartwave mega menu
