### ISSUE TITLE
Why Dummy tags in page source code?

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#708]
Why in page source code there are a lot of Dummy tags?

    
    
    

This is happening in Magento 1.8, Varnish 3.0.6, Turpentine 0.6.1, all installed without modifications. Debug Log and Block Logging in Turpentine, both disabled.

I would like to get rid off these tags. How can I do it?

**Comment by crasx** [comment]
I was able to resolve this by adding 3 spaces before the comment. It looks like something is taking a substring from position 3 on so adding the spaces keeps the full comment markup

**Comment by ADDISON74** [comment]
This needs a revise from maintenance team. Unfortunately this extension seems to be dead.

**Comment by crasx** [comment]
I just implemented it last week and it worked great
