### ISSUE TITLE
Mystery related to Community Poll. It is cached!

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#710]
Even there is a rule into turpentine_esi.xml file for not caching Community Poll, it will be cached! Just vote and you will see again the page for voting. If you visit any page after you voted you will see the results. These two pages will remain in cache from now on. If you come back to them you will see the same content for Poll block (active vote and results).

This is the block reference in turpentine_esi.xml file:

        <reference name="right.poll">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <flush_events>
                        <poll_vote_add/>
                    </flush_events>
                </params>
            </action>
        </reference>

I checked as following:

- block name -> it is correct, 'right.poll'
- dispatchEvent -> 'poll_vote_add'

As rule it is correctly created, but astonishing if you enable block debugging there are no ESI_START [right.poll], ESI URL and ESI END surrounding this block. This means one thing, even the rule is correct it won't work, being cached.

Well all versions of Magento starting with 1.7.0.2 have this problem. I am not a novice with Turpentine, I discovered this issue in August and I reported it. In my opinion there is something with this issue I can learn and also a challenge for every advanced user of Turpentine.

If you think you know Turpentine try solving this. I assure you will find a good puzzle into it. Give it a try.

**Comment by ADDISON74** [comment]
Bump

**Comment by aricwatson** [comment]
Same as https://github.com/nexcess/magento-turpentine/issues/697 - closing this duplicate issue.
