### ISSUE TITLE
Turpentine is not working with Apache Benchmark tool

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#711]
Varnish 3, Apache 2.2, Php 5.4, MySQL Server 5.5
Magento 1.7.0.2
Turpentine 0.6.1

1) All components are working and configured properly. Magento page load in total is around 0.06 seconds.

2) I open an ssh session to my server and launch htop application to check resources like memory load and cpu usage. 

3) Keeping F5 pressed it doesn't affect the server performance. This basic flood will kill Apache for a while if Varnish is not working. All resources are not changing.

Now let's use AB tool to stress the server: ab -n1000 -c100 http://localmage.test/. Astonishing ab tool is almost killing my server boosting resources loading. Varnish should deal easy with this but it doesn't. I get 23 request per second instead of minimum 1000.

As I mention before in browser Varnish is just perfect. I did ab test from other workstation in my LAN. 

Any thoughts?

**Comment by ADDISON74** [comment]
I managed to solve this issue. 

1) Edit in Magento root .htaccess, line 123 uncomment RewriteBase /

2) In Magento Admin go to System -> Configuration. In General section click on Web link, click on Search Engines Optimization and change Use Web Server Rewrites to Yes.

3) Clear all caches in System -> Cache management.

If you touch again the home page, it loads very fast. An AB test gives around 4000 requests/second in my case. I risen up the test to ab -n10000 -c1000 http://localmage.test/ and it provided 2500 requests/second, without any failures.

Conclusion, if you don't get rid off index.php in your URLs, AB test will touch you Apache Server and will provide the true results of your webserver. If you get rid off index.php, AB will get cache from Varnish.

This should be mentioned in Turpentine wiki. Also, if you want to continue using Magento without "Web Server Rewrites" enabled, Turpetine needs to deal with this situation. For this inside VCL file should be added this scenario too.

**Comment by aricwatson** [comment]
I've tested this a bit and could not replicate the issue. My ab tests come back very quick  - as long as I make sure the cache is warm! 

For example, with the -n1000 -c100 I get the following (on an uncached URL):
```
Percentage of the requests served within a certain time (ms)
  50%     13
  66%     14
  75%     14
  80%     14
  90%  11793
  95%  11796
  98%  11799
  99%  11800
 100%  11800 (longest request)
```
If I'm reading that right, 10% of the requests took a *long* time, but the rest were fast. That makes sense, since concurrency was set to 100. Those 100 requests were hitting an uncached page. The next 900 were all getting served from the Varnish cache, so are quite fast.

I get similar results whether or not I use web server rewrites.

**Comment by ADDISON74** [comment]
Here are the results doing the same test from the same server and other server not in the same network:

root@server1:~# ab -n 1000 -c 100 http://localhost/
This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests


Server Software:
Server Hostname:        localhost
Server Port:            80

Document Path:          /
Document Length:        0 bytes

Concurrency Level:      100
Time taken for tests:   12.076 seconds
Complete requests:      1000
Failed requests:        0
Write errors:           0
Non-2xx responses:      1000
Total transferred:      446000 bytes
HTML transferred:       0 bytes
Requests per second:    82.81 [#/sec] (mean)
Time per request:       1207.555 [ms] (mean)
Time per request:       12.076 [ms] (mean, across all concurrent requests)
Transfer rate:          36.07 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    1   1.8      0       8
Processing:    38 1009 1212.2    762    5816
Waiting:       38 1009 1212.2    762    5816
Total:         42 1010 1212.0    762    5816

Percentage of the requests served within a certain time (ms)
  50%    762
  66%    819
  75%    900
  80%   1059
  90%   1569
  95%   4608
  98%   5427
  99%   5536
 100%   5816 (longest request)

**Comment by ADDISON74** [comment]
ab test on the same machine but with IP in URL:

root@server1:~# ab -n 1000 -c 100 http://IP_ADDREESS/
This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking XX.XX.XX.XX (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests


Server Software:
Server Hostname:        XX.XX.XX.XX
Server Port:            80

Document Path:          /
Document Length:        28951 bytes

Concurrency Level:      100
Time taken for tests:   0.644 seconds
Complete requests:      1000
Failed requests:        0
Write errors:           0
Total transferred:      29106000 bytes
HTML transferred:       28951000 bytes
Requests per second:    1553.05 [#/sec] (mean)
Time per request:       64.389 [ms] (mean)
Time per request:       0.644 [ms] (mean, across all concurrent requests)
Transfer rate:          44143.71 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        2   24  15.6     24      68
Processing:     2   40  15.6     40      74
Waiting:        1   22  14.7     21      64
Total:         10   63  12.5     65     119

Percentage of the requests served within a certain time (ms)
  50%     65
  66%     66
  75%     68
  80%     73
  90%     77
  95%     78
  98%     88
  99%     99
 100%    119 (longest request)

**Comment by ADDISON74** [comment]
TEST 3: ab test from other machine not in the same network:

root@server1:~# ab -n1000 -c100  http://IP_ADDREESS/
This is ApacheBench, Version 2.3 <$Revision: 1604373 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking XX.XX.XX.XX (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests


Server Software:
Server Hostname:        XX.XX.XX.XX
Server Port:            80

Document Path:          /
Document Length:        28951 bytes

Concurrency Level:      100
Time taken for tests:   13.118 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      29106000 bytes
HTML transferred:       28951000 bytes
Requests per second:    76.23 [#/sec] (mean)
Time per request:       1311.835 [ms] (mean)
Time per request:       13.118 [ms] (mean, across all concurrent requests)
Transfer rate:          2166.72 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        4   62 173.1     15    1089
Processing:   113 1191 385.7   1234    4496
Waiting:       12 1063 380.7   1119    3861
Total:        119 1253 424.4   1261    4517

Percentage of the requests served within a certain time (ms)
  50%   1261
  66%   1353
  75%   1402
  80%   1428
  90%   1657
  95%   2025
  98%   2250
  99%   2889
 100%   4517 (longest request)

**Comment by ADDISON74** [comment]
Varnish is listening on port 80. Why the results are different? As you can see a massive number of requests can be achieved only using localhost in URL, test on the same machine. 

If using IP address (no matter if ab test is done on the same machine and on Internet) it provides the same results, almost 80 requests/second. This is not a Varnish result for sure. It is like touching Apache directly. But it is not touching Apache, using htop memory is not increasing in this test staying on the same level (memory will blow if Varnish won't be in front of Apache for such of test).

Going further, I lauch the ab test on the same machine, using IP address in URL, then in my browser I am trying to load the front page. It is taking about 7 seconds to reload the page. This is not a Varnish results for sure.

**Comment by aricwatson** [comment]
Hmm... Speaking from experience, it's worth double-checking that Varnish/Turpentine are all set up and working when testing from the browser regularly. The easiest way to do this is to turn on Turpentine debug and look at the headers when you load the page.

Have you tried the tests with other pages?

**Comment by ADDISON74** [comment]
Yes I did what you suggested. It is pretty strange. When I am doing the AB test on the same server I get a huge number of requests/second. But when I am doing the AB test from a VMware located at my home, then server is providing the same number of requests. It is like testing directly into the Apache webserver. 

Varnish configuration is fully operation. Turpentine is working as expected. Hits, headers all OK. From my home, the whole server is running just perfect. AB test is not eating the memory, keeping it at the same level. 

Also it is not normal with a number of 1000 requests and 100 concurrency level running in browser not loading the same page. It is loading after the test is finished. But as I said, resources of the server are untouched.

**Comment by ADDISON74** [comment]
I have to talk to my ISP. My only conclusion is even I have a dedicated server is it possible there is a router with some firewall rules in front of all networks, or they have a firewall for this dedicated server. Same configuration into my VM test environment provided me huge number of requests. But not for the dedicated server.

**Comment by aricwatson** [comment]
I'm going to close this issue, but will reopen if you're still seeing weird problems that we can help with.

In addition, I'd point out that our standard tool for this sort of testing is [siege](https://github.com/JoeDog/siege) - you may want to try that tool.
