### ISSUE TITLE
Ugly issue - Online Customers section in Admin is compromised

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#714]
Go to Backend and from [Customers] menu choose [Online Customers]. Watch URL column, it is compromised as information. 24 records all with turpentine in url for the same ip. After a while and some refreshes it will remain only one URL, also with turpentine text in URL. Here is an example from my test localhost:

http://192.168.159.131/turpentine/esi/getBlock/method/esi/access/public/ttl/3600/hmac/c2b8547cb6feec581e62213af326e05c9ad9c057716ea153892b5ce5664a84d2/data/ahlJpOZh6So05ByE.Xp2gC98.HR.9i7FudWMsOQbmfqEGZscaOmtlZuMhmY17YS9fpF7qcIyd9NiK6XFfp587nqAwVnJXt

As this URL is you cannot understand anything a visitor is doing inside the website.

**Comment by gewaechshaus** [comment]
About 22k entries on a production environment. x-forwarded-for seems to be broken as most customers got ip 127.0.0.1 :)

**Comment by theycallmepepper** [comment]
I believe this is documented in the FAQ.

**Comment by gewaechshaus** [comment]
Thanks, i'll dive into it ;)

**Comment by theycallmepepper** [comment]
Keep us all updated with what you find, this one is on my list as well!

**Comment by gewaechshaus** [comment]
Found nothing... :(

**Comment by theycallmepepper** [comment]
Referenced under known issues on the main github page.

**Comment by gewaechshaus** [comment]
Thx again. Need to look into a solution for nginx, will post it here...

**Comment by ADDISON74** [comment]
It is not an extension, it is Magento default, CE 1.7, 1.8 and 1.9. I am concentrating to find all issues in Magento stock, without adding extensions. Once we solve all issues to Magento default we can go further with tutorials for making extensions working.

**Comment by ADDISON74** [comment]
In my opinion an investigation should start related to this Online Customer module and how Turpentine affects the URL this module is processing. It is clear to me Turpentine is passing the URLs and this module just show them, like an array.

**Comment by evensis** [comment]
Try adding your admin path into the Turpentine blacklist (and the /customer_online route) and see how you get on, Turpentine does cache some odd things, and my blacklist is full of things it caches but shouldn't do. I'm actually on a project to upgrade Magento CE from 1.6.2.0 to 1.9.1.0, so by sounds of it Turpentine is going to be tricky!

**Comment by ADDISON74** [comment]
Unbelievable! Nobody did not find a solution for this issue, which creates a lot of problems in performance. I am sorry to say, is Nexcess team deep sleeping? This issues is really a bad one!!!!

**Comment by gewaechshaus** [comment]
Disable logging as I wrote above.

It's easy to critize, but it ain't easy to find good solutions! This is a free extension, think about that...

**Comment by ADDISON74** [comment]
I already disable the logging. Thank you.

Please note my post was not criticism. I would like to see Nexcess team back like at the very beginning whey they offered this extension to the community.

How can I achieve extending the native logging method to exclude ESI?

**Comment by gewaechshaus** [comment]
Take a look at Mage_Log_Model_Visitor and extend it local for a first test...

**Comment by aricwatson** [comment]
We'll investigate some more, but I suspect that this online customer report will not be reliable on systems running Turpentine. Ideally, some users will hit the site and have their requests be handled 100% by Varnish - in which case Magento would not know of them, and they would not appear in the online customer report.

I suspect however there may be other problems going on here and will test some more. I understand this could aggravate performance problems on high traffic sites that do no implement some sort of log-cleaning by adding unnecessarily to the logs being generated, so in my mind that's the primary concern.

I don't think it's accurate to say the report is *compromised* (as in a security concern) because of this.

**Comment by ADDISON74** [comment]
I agree aricwatson. It is not only online customers is more than that. When Varnish is hit you won't get correct traffic statistics. Awstats provides statistics based on webservers log. I disabled all logs for the moment, but I am blind without statistics. All links now come from one IP address (my webserver IP address), cutting the first part I can evaluate what pages are the most visited. I did not check with Google Analytics, but I need a solution when using Turpentine for getting correct traffic statistics. Do you know one?

**Comment by aricwatson** [comment]
You have [a couple options](https://github.com/nexcess/magento-turpentine#known-issues) to fix the IP issue, at least if you're using Apache.

Google analytics should work fine, since the google analytics javascript code runs in the front end. 

Also, it's possible to set up Varnish to generate logs in the same format as apache, which tools like awstats should be able to process - check out the [varnishncsa command](https://www.varnish-cache.org/docs/trunk/reference/varnishncsa.html)

**Comment by ADDISON74** [comment]
This is really helpful. I just forgot in the past I used mod_rpaf ...

**Comment by ADDISON74** [comment]
Well I used mod_rpaf then mod_cloudflare (this is new). I managed fixing Hosts section in Awstats, now it shows correctly visitor's IP address.

Still have trouble with 

1) Pages-URL section, it shows tons of /turpentine/esi/getBlock ...
2) Connect to site from -> Links from an external page. All are having my server IP address.

Any clues?

**Comment by aricwatson** [comment]
> 1) Pages-URL section, it shows tons of /turpentine/esi/getBlock ...

I think this is proper behavior, since each ESI request is made separately though apache

> 2) Connect to site from -> Links from an external page. All are having my server IP address.

It should be possible to set it up so this works, but with cloudflare involved also it gets complicated. You may need to ask your hosting company to help.

> Any clues? Is it a good idea to insert my server IP into Crawler IP Addresses: 127.0.0.1, SERVER_IP?

No I don't think this will help.

**Comment by ADDISON74** [comment]
Guys, what do you think about this new Magento Extension?

http://magemail.co/blog/better-visitor-log-for-magento.html

**Comment by miguelbalparda** [comment]
Sorry about that. Never used it, you can find the developer on Twitter @kalenjordan

**Comment by kalenjordan** [comment]
@ADDISON74 hey, Kalen here.  The extension is pretty basic - it adds some ajax logging and support for mixpanel logging.  I haven't gotten much feedback from anyone using it in the wild yet, so let me know if anything comes up for you.

**Comment by ADDISON74** [comment]
I will try using it and see what happens.

**Comment by kalenjordan** [comment]
@ADDISON74 sounds good.  By the way, I would probably say it's more appropriate for a developer or someone who's fairly technical to use.  I'm not sure if you're a developer or not.  But also since it's a free extension I probably won't be able to provide a ton of support for it either.

**Comment by miguelbalparda** [comment]
Thank you @kalenjordan!

**Comment by ADDISON74** [comment]
I am not a Magento developer, just a networking engineer who has advanced knowledge about operating systems, web technology, security ... and using Magento. I found this extension which pretends to fix some issue related to proxy servers, mainly using Varnish. Well, I can check if it could be interesting. I am not planning to offer any support, just wanted to find out if anyone knows about it for providing a feedback. It could be a fix to the reported issue.

By the way I guess it was a misunderstanding to my post about this extension.

**Comment by aricwatson** [comment]
Closing for now, let us know if you have any other questions!

**Comment by ADDISON74** [comment]
I removed Online Customers menu link from backend. I also disabled logs using Yireo extension. I will follow your advice to take Varnish logs into AWstats.

**Comment by ADDISON74** [comment]
Can we do something to Apache not letting log all the links with /turpentine/esi/ ... and /media/catalog/product/cache? The access log after 1 day is becoming so huge. Like excluding some paths from recording in access log.
