### ISSUE TITLE
Installed The module. Geting : Varnish admin socket timeout

### ISSUE THREAD

**Issue by touaquarious** [nexcess/magento-turpentine#717]
Hello everyone
I have installed the module.
Earlier I was using 69.16.242.55:6082  in  Server List and was getting the following error
---"Failed to apply the VCL to 69.16.242.55:6082: Failed to connect to Varnish on [69.16.242.55:6082]: (111) Connection refused"

But changing the server list  to 69.16.242.55:80,  I think it connects but now getting a different error
---"    Failed to apply the VCL to 69.16.242.55:80: Varnish admin socket timeout"

Do not know where I am going wrong.

**Comment by magenx** [comment]
yes, you need to go back and start from reading the varnish installation and configuration manual...
