### ISSUE TITLE
Turpentine module customer login and cart issue

### ISSUE THREAD

**Issue by jessyloran** [nexcess/magento-turpentine#718]
everything works fine but some customer facing the problem in login
what would be the problem and how should i trace this issue ?

**Comment by magenx** [comment]
what is the problem?  maybe you have double cookie?

**Comment by gewaechshaus** [comment]
Read the end of this issue carefully and follow the instructions of https://github.com/licarna
https://github.com/nexcess/magento-turpentine/issues/169
