### ISSUE TITLE
ESI not refreshing cache

### ISSUE THREAD

**Issue by caevv** [nexcess/magento-turpentine#722]
I have installed an Search Sphinx Extension by Mirasvit. 

When I disabled ESI on Magento Cache, the extension Search Bar display. If I enable it, the extension is gone, and the built in Search Bar appear instead.

I have tried to:
1) service varnish restart
2) ban.url .
3) rm -fr var/cache
4) Make a local.xml with:
```
    <default>
		<reference name="search.block">
			<action method="setEsiOptions">
				<params>
					<method>esi</method>
					<access>private</access>
				</params>
			</action>
		</reference>
    </default>
```
It doesn't work at all.

**Comment by magenx** [comment]
you have it in head or header? is this the only block name - search.block ? try to disable header in turpentine_esi.xml

**Comment by caevv** [comment]
It's on Header. If I disable header on turpentine_esi.xml it works, the new Search Bar appears.

**Comment by caevv** [comment]
Yes, it is the only block name:
```
        <block type="searchautocomplete/layout" name="search.block">
            <action method="addSearchAutocomplete" ifconfig="searchautocomplete/general/enabled" />
        </block>
```

**Comment by magenx** [comment]
you dont have to define this block, only dynamic blocks inside header template.

**Comment by caevv** [comment]
But how to make it work then?
Em 08/01/2015 13:43, "magenx" <notifications@github.com> escreveu:

**Comment by evensis** [comment]
Does this block depend on any objects or Mage::registry entries? If so you need to specify this in ESI policy, otherwise it will simply throw 503's.

Header's a bit of an odd one at the best of time and I've spent a fair bit of time having to get around issues in it.
