### ISSUE TITLE
Recently Viewed Products it is cached too!

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#723]
Well I discovered as follows:

- Community Poll right side block it is cached. You vote, page reloads, no vote results. First page you visit you will see the poll results. If you come back to page vote and page results you will see poll active and poll results.

- Compare Products and Recently Compared Products right side blocks both cached. Also info message in page content after you removed a product from Compare list is cached too.

Now here comes another one:

- Recently Viewed Products. I cleared all cookies and cached file of my browser and all Magento sessions before reloading the page. I load a category and Recently Viewed Products still shows 3 products. 

All these issues have ESI cache rules set up in turpentine_esi.html. It is clear with have a problem with them and they should be removed from page, before creating rumors through your online visitors. I will try to move these block to other places in order to check their behavior.

All Magento versions starting with 1.7.0.2 to 1.9.1 are affected.

**Comment by BarryCarlyon** [comment]
You ESI configuration in the Turpentine layout file is wrong, or you are using the default layout file.

The default turpentine_esi.xml points to the *likely* place of these blocks in your theme.

I tackled this exact same problem last week.

I created my own turpentine_esi.xml which applies the right block paths/references and now have a working Recently Viewed Products.

**Comment by ADDISON74** [comment]
I deleted turpentine_esi.xml file from base folder and them placed it into my theme. Inside right block all block are default as names, including "Recently Viewed Products", ... But even the configuration is well written in turpentine_esi.xml, there are still issues. Check the poll block too and see what is happened.

Could you provide more information? Could you paste your custom file here?

Thank you.
