### ISSUE TITLE
No X-Varnish header 

### ISSUE THREAD

**Issue by brentwpeterson** [nexcess/magento-turpentine#726]
I am using this service: http://www.isvarnishworking.com/

Nope!
We didn't find the "X-Varnish" header in the response from the server so likely Varnish is, in fact, not working.

I have Varnish installed and the turpentine module installed.

Please let me know how I can help to debug this.

**Comment by aheadley** [comment]
@brentwpeterson By default, Turpentine removes the `X-Varnish` header for PCI compliance reasons so it won't show that it's working on that site. If you enable the debugging option it should show up again if you want to confirm.
