### ISSUE TITLE
Ban category page cache on stock status change

### ISSUE THREAD

**Issue by 0859170** [nexcess/magento-turpentine#729]
If a product becomes back in, or out of, stock it would be really nice if the category pages of that product would be banned so the product is visible again.

Now only the product page itself is banned, but the product is not visible on the category page when it comes back in stock.

**Comment by gkopec** [comment]
I have a similar problem, when I changed the product price it has been updated only on the product page, but category page shows old price. Is there a way to clean the category cache automatically after product saving?

**Comment by Stasevi4** [comment]
I have a similar problem with category , my fix was /app/code/community/Nexcessnet/Turpentine/Helper/Ban.php
```
$categories = $product->getCategoryIds();
	foreach ($categories as $categoryId) {
    		$category = Mage::getModel('catalog/category')->load($categoryId);
		$urlPatterns[] = $category->getUrlKey();
	} 
```
add this code in function  
```
public function getProductBanRegex( $product ) { 
```
also same problem in search,  fix ban all search result:
```
$urlPatterns[] = 'catalogsearch';
```

**Comment by miguelbalparda** [comment]
Some more info on #812
