### ISSUE TITLE
Varnish age stays at zero when examining headers, Varnish 3 

### ISSUE THREAD

**Issue by anderow** [nexcess/magento-turpentine#730]
ok, so I got Varnish 3 running with latest Turpentine. It is still causing me headaches though. 
Here is the header from isvarnishworking.com (its a dev site and debug is enabled so xvarnish shows)

[root@li311-198 conf]# curl -I http://www.site.co
HTTP/1.1 200 OK
Server: Apache/2.2.15 (CentOS)
X-Powered-By: PHP/5.3.3
Set-Cookie: frontend=jdujmc45k7tqnakqbhcji6e730; expires=Fri, 16-Jan-2015 00:52:32 GMT; path=/; domain=www.site.co; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
X-Frame-Options: SAMEORIGIN
X-Robots-Tag: noindex, nofollow
Content-Type: text/html; charset=UTF-8
Content-Length: 45868
Accept-Ranges: bytes
Date: Thu, 15 Jan 2015 23:52:33 GMT
X-Varnish: 1249242180
Age: 0
Via: 1.1 varnish
Connection: keep-alive

Here is varnishstat readout
![picture2](https://cloud.githubusercontent.com/assets/10123094/5769386/a3c07874-9d12-11e4-965e-2e5f377ef99c.png)

Has anyone got any ideas what could be the issue? It seems that cache control is being set as no cache, I have checked httpd.conf but there is nothing in there setting it. would appreciate any input thanks

**Comment by jg-development** [comment]
Hardly to see it from here. How is your Apache/Varnish Configuration?
Varnish Port 80?
Apache Port 8080?
