### ISSUE TITLE
Varnish work, config is save, but no cache page

### ISSUE THREAD

**Issue by TechOS-PL** [nexcess/magento-turpentine#733]
Hi,

i have a big problem, i install varnish 3.0.6 , all config looks ok, becouse when i press Accept Varnish Config in magento cache management all be fine, config is accept, I don't get any error message, but my page is no cache, in magento system.log i see only Checking ESI block candidate, and Cleared ESI cache for client (....) on event .... , nothing more

How to find where is the error ?

**Comment by anderow** [comment]
what does curl -I http://yourdomain.com   give?

type  varnishstat   - post a screenshot of the page (view your site a few times). I am guessing your site appears to work?

**Comment by aricwatson** [comment]
No further details provided.
