### ISSUE TITLE
Registry Keys not working

### ISSUE THREAD

**Issue by pushonque** [nexcess/magento-turpentine#734]
Hi

I am having problems getting registry keys for current product to work.

Edit: My local xml isn't displaying. I have attached an image.
![xml](https://cloud.githubusercontent.com/assets/6839170/5835270/599db112-a15e-11e4-97ab-3ed26d13473d.PNG)

This is how my block looks

class PushON_CurrencySelector_Block_Product extends Mage_Core_Block_Template{

	public function getProduct(){
		$_product = Mage::registry('current_product');
		return $_product;
	}

}

And this is my template file

<?php
	$_product = $this->getProduct() 
 ?>
 <?php echo $_product->getName() ?>

I get this fatal error

Fatal error: Call to a member function getName()

This all works with Varnish disabled. Please help me out. What am I doing wrong?

Thanks in advance.

**Comment by aricwatson** [comment]
Hi - apologies for the late response.

If you haven't already resolved this - I wonder if you are seeing anything in the debug logs? It might be worth adding some debugging messages to `Model/Observer/Esi.php` to make sure your registry keys are getting set up.

**Comment by aricwatson** [comment]
Closing for lack of feedback.
