### ISSUE TITLE
Access = Private not working

### ISSUE THREAD

**Issue by Nuranto** [nexcess/magento-turpentine#736]
Hello,

I'm trying to add ESI options to an extension's block that displays a JS script, different for each visitor.
I've already done this for some other extensions, but for this one it is not working for some reason...

The log is saying :  "Block check passed, injecting block: tracking_footer", which means the ESI options have been found, right ? But when I test on two session, the same code (with customer data..) appears on both side.

I also added a 'page' scope, because the script is changing on each page (product/category/cart/HP/...).
I don't know where to look to debug this, but it seems like a bug, right ?

Thanks,

V.E.

**Comment by Nuranto** [comment]
Well... I disabled the cache, and re-enabled it and it is now working. (I did purge the cache, but is seems it is not enough to purge all cache)

Now I have another trouble, maybe someone can help : 
This script changes when the customer log in. With varnish On, it does not change after login.
Here is my ESI options for this block : 

protected function _construct()
    {
$this->setEsiOptions(array(
            'access' => 'private',
            'scope' => 'page',
            'flush_events' => array(
                'sales_quote_save_after',
                'checkout_onepage_controller_success_action',
                'customer_register_success',
                'customer_login',
                'customer_logout',
            ),
            'registry_keys' => array(
                'current_product',
                'current_category',
                'wc_tt_current_customer'
            )
        ));
        if($customer = Mage::helper('customer')->getCustomer()) {
            if(!Mage::registry('wc_tt_current_customer')) {
                Mage::register('wc_tt_current_customer', $customer);
            }
        }

The wc_tt_current_customer thing is a try to make this work. But it does not work...

**Comment by adeshsuryan** [comment]
Hi  ,
      We'r trying  to  exclude the top.link block which   contains  cart, login, wishlist  etc. links in header .But Access = Private is not  working  at  block  level . Check the below code of layout  file (turpentine_esi.xml). 

Block Name : top.links
<reference name="top.links">
                    	<turpentine_cache_flag value="0"/>
			<action method="setEsiOptions">
				<params>
					<access>private</access>
					<ttl>0</ttl>
				</params>
			</action>                    
		</reference>


Block Name : header
        <reference name="header">
		 <turpentine_cache_flag value="0"/>
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
					<ttl>0</ttl>
                    <flush_events>
                        <wishlist_item_save_after/>
                        <wishlist_item_delete_after/>
                        <sales_quote_save_after/>
                    </flush_events>
                </params>
            </action>
        </reference>

**Comment by adeshsuryan** [comment]
Block Name : header
