### ISSUE TITLE
Varnish/Turpentine JavaScript issue...

### ISSUE THREAD

**Issue by epiblue** [nexcess/magento-turpentine#737]
Hey Guys,

I've added the ESI policy for my minicart and started getting some strage issues.

I've added these two policies in my ```local.xml``` (inside ```<default></default>``` tags)
```
		<reference name="minicart_content">
			<action method="setEsiOptions">
			    <params>
			        <access>private</access>
			        <method>ajax</method>
			    </params>
			</action>
		</reference>
		<reference name="minicart_head">
			<action method="setEsiOptions">
			    <params>
			        <access>private</access>
			        <method>ajax</method>
			    </params>
			</action>
		</reference>
```

The cart is working just fine, but for some reason the JavaScript stoped working, when clicked on the minicart in the header the minicart product container should show up and after enabling the ESI policy it doesn't.

I've added a simple JS to test and it's not working:
```
$j(document).ready(function(){
	$j('.header-minicart a').click(function(){
		$j('#header-cart').addClass('show-cart');
		alert('click 1');
	});
});

$j(document).ready(function(){
    $j('.header-minicart a.close').click(function() {
	    $j('#header-cart').removeClass('show-cart');
	    alert('click 2');
  });
});
```

here's the site: www.golulo.es

Can anybody point me in the right direction? I don't understand why it's not working? 

Also, the CSS (it can be fixed manualy, but it's strage) stoped working for that Block:

Screen without cache:
![image](https://cloud.githubusercontent.com/assets/6641569/5898753/e115236c-a552-11e4-9246-f343146cd338.png)

With Cache:
![image](https://cloud.githubusercontent.com/assets/6641569/5898766/01332360-a553-11e4-9cce-5cb029d39efb.png)

Cleared cache, restarted varnish... 

Thanks,

**Comment by gewaechshaus** [comment]
Hey,

you're manipulating the DOM cause you're including the minicart as an esi block via ajax. In conclusion, some pieces of code needs a smarter logic...

Assuming you are using a rwd fork

app/skin/frontend/what/ever/js/app.js

    skipLinks.on('click', function (e) {
         ...
     }

doesn't have to be convoluted, change it into

    $j('.skip-links').on('click', '.skip-link', function (e) {
           ...
      }

http://api.jquery.com/on/

**Comment by aricwatson** [comment]
Javascript issue, object loads after DOM so you need to use *.on* as explained by gewaechshaus.

**Comment by jcmokitup** [comment]
Hi @epiblue 

Finally, can you resolve the issue with javascript and mini-cart?

Please, help me if is possible for you :/

Thanks a lot,
