### ISSUE TITLE
Turpentine not banning CMS Pages on Enterprise

### ISSUE THREAD

**Issue by ashsmith** [nexcess/magento-turpentine#738]
Turpentine will ban a CMS page, when you go: CMS > Pages > Manage Content and select a page, and save it. However, when you edit a revision and publish it, the page is never banned.

Tested by having varnishlog open and I never see a ban request for the edited revision.

Happy to submit a PR with the change. My solution was to listen for the `enterprise_cms_revision_save_commit_after` event.

**Comment by aricwatson** [comment]
Thanks! Just committed your PR to *devel* so it'll be in the next update.
