### ISSUE TITLE
Magento cache flushes, but varnish still beeing cached.

### ISSUE THREAD

**Issue by epiblue** [nexcess/magento-turpentine#743]
Hey,

I've spotted, that when I flush my magento cache the varnish cache is not beeing flushed...

If I do it manually, everything works.

Anybody can point me where to look for a solution? My vcl config or?

Also, is there a posibility to warm varnish when flushed, to cache all the pages onces the updates were made?

How does the Varnish Warm script work? becaue I can't seem to see it working, because everytime I flush my varnish cache via SSH, I need to revisit manually the pages to cache them. In configuration I have the Varnish Warm enabled.

Thank you

**Comment by epiblue** [comment]
Is this extension even supported or any kind of support is provided? I tryed asking here quite a few questions and during the past month didn't receive any feedback nor help. Any signs of life, please? :)

**Comment by sander010587** [comment]
Hello Epiblue,

Is your backend configured correctly? Is varnish using the correct VCL? Check if your logs show any unusual input after flushing caches.

With regard to cache warming you will need some kind of cache warming applicaton like Siege. Please have a look at that, which enables you to cache the pages in your sitemap for instance.

Kind regards, Sander.

**Comment by miguelbalparda** [comment]
@epiblue varnish should be flushed while flushing cache from the admin. How are you flushing your cache? What do you mean by manually flushing varnish?

**Comment by miguelbalparda** [comment]
Closing for lack of response.
