### ISSUE TITLE
Failed to apply the VCL and Failed to save the VCL

### ISSUE THREAD

**Issue by vroberttaken** [nexcess/magento-turpentine#744]
Hi am using Ubuntu and Apache + Varnish for Magento. After installing Magento and Varnish(https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-varnish-with-apache-on-ubuntu-12-04--3) I also add the Turpentine Extension for Magento. I enabled it and want to save it but I get that following error:

Failed to apply the VCL to 127.0.0.1:8080: Varnish admin socket timeout

Failed to save the VCL file: Undefined index: block

The Backend Host and port is correct but I don't have any idea want could be the problem.

thanks

**Comment by jg-development** [comment]
This tutorial has the apache on port 8080 and the varnish on 6082.
Try it again with the port 6082.
