### ISSUE TITLE
Maintenance mode

### ISSUE THREAD

**Issue by 0859170** [nexcess/magento-turpentine#745]
When I put my store in maintenance mode I get really ugly pages with our 503 page on it a couple of times.

I would like the cached pages to serve as normally, but maybe disable the add to cart buttons. Non-cached pages can serve the 503 page.
Is this possible?

I know index.php throws the error message, but is there a way to check if it is a ESI request, or a full page?

**Comment by magenx** [comment]
```
acl dev_allow {
        "123.123.123.123";
}

sub vcl_recv {
if (client.ip !~ dev_allow) {
        error 503;
        }
}
```
