### ISSUE TITLE
Breadcrumbs not showing + page "getTitle" error

### ISSUE THREAD

**Issue by alemontalti** [nexcess/magento-turpentine#748]
Hello, 

I read all the issues about breadcrumbs but I can't find out how to fix the problem, I only understand that using Turpentine in Magento 1.7.0.2 (and maybe in other versions), it comes some troubles with variable `$crumb` and its check in breadcrumbs.pthml.

Here's my local.xml file:

    <reference name="header">
        <block type="page/html_breadcrumbs" name="breadcrumbs" as="breadcrumbs" />
        ...
    </reference>

    ...

    <reference name="breadcrumbs">
    	<action method="setEsiOptions">
        	<params>
            	<access>private</access>
            	<ttl>0</ttl>
        	</params>
    	</action>
    </reference>

But it doesn't work. 

Furthermore, I have a custom behavior for breadcrumbs if variable `$crumb` is not setted up in Magento: I get the page title as a breadcrumb. Here the code:

    <?php 
	if($crumbs && is_array($crumbs)):
    ?>

        [ standard breadcrumbs behavior ]

    <?php else:?>

    <div class="breadcrumbs">
	    <ul>
		    <li><?php echo $this->getLayout()->getBlock('head')->getTitle(); ?></li>
	    </ul>
    </div>

<?php endif; ?>

It doesn't work anymore since I turned on Varnish and Turpentine, I get a 500 error such as: 

```2015/02/05 18:10:20 [error] 9602#0: *545445 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function getTitle() on a non-object in /var/www/vhosts/********.com/httpdocs/app/design/frontend/arena/default/template/page/html/breadcrumbs.phtml on line 76" while reading response header from upstream, client: 88.80.187.121, server: www.********.com, request: "GET /fr_fr/turpentine/esi/getBlock/method/esi/access/private/ttl/3600/hmac/9a7f53ca125daa688d155cfe02432ce9fba2edfee3f99da2cd6e81a6b39e5458/data/cXXfkvnu5-YmEguhMeWNc3UFODEdRj.mGDlLLUMw54jIZBrsjyS5ViwFd4cvUmLpM-jIFB7H0aW5.uKItvHj14YOoW-Uw2IgVcEqObuJJBcH1gtnSlFyZ.3sXoCsKGdRcGOjvmM6f6-XaS-kJHnx9WNwmPlZSJj0OJze2ngPq.yB.pZ3pYlhtP3by4aJUgKF1FjqO0Okd9nO2Zc5Oou.NlQIkwRLD-Yj6RRKRn6oxDv3kxToYMuMfFCCmZ3IPnVDE5-PENUYGTKudIM6CjL263fZoVZ81bd04nnER0E8SVSvkISYvpNNRAP809zuEl-ZHt6Pmc97cao6hMKPh9x4omD2VKDyqBYdES.e012QGKWXleViFCSi9TjFsialgmkHSyxykh9CPpVp0sDK8pZr8A==/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "www.********.com", referrer: "http://www.********.com/fr_fr/eshop/"```

Anobody can help me? It would be really appreciated!

**Comment by theycallmepepper** [comment]
[ESI_Cache Policies](https://github.com/nexcess/magento-turpentine/wiki/ESI_Cache_Policy)
```
<dummy_blocks>
<head/>
</dummy_blocks>
```
Take a look at this and try setting the dummy blocks parameters for the breadcrumb block since it depends on the head block to render properly.
