### ISSUE TITLE
Can we flush the varnish cache storewise in multi-store/site setups ?

### ISSUE THREAD

**Issue by ravipalkonda** [nexcess/magento-turpentine#749]
Can we flush the varnish cache storewise in multi-store/site setups ?
It was working in Phoenix Varnishcache extension.
This extension is working excellently for single store setup, but not able to find solution fo multistore setups.
Can someone please help 

Thanks in advance...

**Comment by miguelbalparda** [comment]
@ravipalkonda we don't support this now. There is a new feature that might help you, see #527
