### ISSUE TITLE
Where should define ESI cache for a block in the CMS

### ISSUE THREAD

**Issue by donnie-darko** [nexcess/magento-turpentine#75]
The newsletter subscribe box in my custom template home page "come" from a CMS page where I set it. How can I cache it properly? If I use the default `turpentine_esi.xml` the newsletter block doesn't appear, if I use the custom.vcl. If I use the original default.vcl , the newsletter subscribe box appear.

**Comment by ngongoll** [comment]
I tried your solution but doesn't work for me.
Varnish 3.0.7 with latest turpentine master.

CMS Page Layout: 
` <reference name="right">
 <block type="czfilm/Productmostviewed" name="home.beliebteste" alias="beliebteste" template="catalog/product/mostviewed.phtml" >

            <action method="setEsiOptions">
                <params>
                    <access>public</access>
                    <method>ajax</method>
                    <ttl>3600</ttl>
                </params>
            </action>
</block>
</referenz>`

From log File i get this error:

2016-02-02T10:09:36+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: home.beliebteste
2016-02-02T10:09:36+00:00 INFO (6): TURPENTINE: Block check passed, injecting block: home.beliebteste
2016-02-02T10:09:42+00:00 WARN (4): TURPENTINE: No block node found with @name="home.beliebteste"

in frontend ESI block not found
