### ISSUE TITLE
Varnish first byte takes longer after every 2 - 3 days.

### ISSUE THREAD

**Issue by ankee143** [nexcess/magento-turpentine#750]
Hi ,

We have turpentine on our Magento site mruga.com and we realized that every so often the site takes longer to load. 

ex. http://gtmetrix.com/reports/www.mruga.com/6O68lbM7   after 2 - 3 days of varnish restart
ex. http://gtmetrix.com/reports/www.mruga.com/CtGAJFNB  soon after varnish is restarted from server root

As it can be seen in above ex. that the first byte load time is 935ms compared to 3.33s when varnish is restarted.

Can you please help with a solution to this ?

Thanks,

**Comment by nstojadinovicwst** [comment]
Change Varnish storage engine to malloc

**Comment by ankee143** [comment]
Sorry but i am not sure how to do that.

Can you please help and guide me through to change the Varnish storage engine to malloc.

**Comment by Stasevi4** [comment]
If you run Debian/Ubuntu config file located /etc/default/varnish
change line 
```
VARNISH_STORAGE="file,${VARNISH_STORAGE_FILE},${VARNISH_STORAGE_SIZE}"
```
to
```
VARNISH_STORAGE="malloc,${VARNISH_STORAGE_SIZE}"
```
make sure you have free memory

**Comment by ankee143** [comment]
Hi,

Thanks for your help, will make the changes accordingly.

Regards,

**Comment by aricwatson** [comment]
Did this resolve the problem?
