### ISSUE TITLE
Turpentine not purging or not sure , but our site takes longer to respond after every 2-3 days

### ISSUE THREAD

**Issue by ankee143** [nexcess/magento-turpentine#752]
Hi,

It seems that turpentine is not purging the old cache or not sure what the issue is . but our site takes longer to respond after every 2-3 days . If we restart varnish on server it comes back to normal again but after 2 - 3 days its the same again.

Could you please advice if we need to set something ?

Regards,

**Comment by aricwatson** [comment]
Hi - FYI - I'm going close this while leaving your other issue open (https://github.com/nexcess/magento-turpentine/issues/750)
