### ISSUE TITLE
Is it possible to use varnish in front and multiple web backends?

### ISSUE THREAD

**Issue by eriksenonline** [nexcess/magento-turpentine#754]
I am not sure where to ask this question so I post it here. I know varnish can be used as a load balancer for multiple web backends. If it is so it would be a cleaner setup compared to HAproxy. No need for extra software to complicate stuff. I will only have two backend webservers so I do not need a lot if intelligence when it comes to the balancer.

Is it possible to configure this in Turpentine? In config or in the extra custom vlc file?

**Comment by magenx** [comment]
have you tried to look in to this problem? depends on your traffic and workload, you can try to use local nginx server to loadbalance as well, you will have more flexible configuration then.

**Comment by eriksenonline** [comment]
The alternative would be varnish -> HAProxy -> Nginx
But if I was able to use varnish as load balancer I would have less systems to manage. My application is very cpu intensive so I need more backends. One varnish will work fine. 

I know this is possible in varnish config but I wonder if there is a way for Turpentine to generate that config? Or if there must be some tweaking with custom VLC here?

**Comment by eriksenonline** [comment]
I vould realy like to do this
https://www.varnish-cache.org/trac/wiki/LoadBalancing

**Comment by aricwatson** [comment]
There is a PR (https://github.com/nexcess/magento-turpentine/pull/632) to implement this which we are reviewing - but feel free to check it out in the meantime and report back!

**Comment by aricwatson** [comment]
We've merged https://github.com/nexcess/magento-turpentine/pull/865 into devel, which allows load balancing via Turpentine. If you have further issues or ideas, feel free to reply and we'll reopen the issue.
