### ISSUE TITLE
Magento + Turpentine Varnish in Amazon ELB

### ISSUE THREAD

**Issue by maaxxicarvalho** [nexcess/magento-turpentine#755]
Hi,

I'm trying to setup Turpentine to run in a Amazon ELB environment.

We have two servers with two identical configurations (nginx, varnish and etc).

Is there a recommended setup for this type of environment?

Thanks!

**Comment by magenx** [comment]
there is nothing special.

**Comment by maaxxicarvalho** [comment]
@magenx sorry but? that answer doesn't help.

I have two servers running Magento behind a Amazon ELB. At the moment, Varnish is installed on both servers but , the problem is when applying settings, sometimes I'm facing admin panel from server 1 and sometimes I'm facing from server 2, so this doesn't work.

I tried to install Varnish on the ELB server, since this, in my opinion, is the right whay. But ELB is a service and cannot have software installed like in a ELB instance.

So I'm thinking that I'll have to remove ELB and "promote" Varnish to stay in front of my Magento servers, so Varnish became to be the load balancer.

But, this is the best approach? Anyone have this issue?

Thanks very much!

**Comment by nstojadinovicwst** [comment]
You need make sure varnish secret is the same on all servers. After that just set in varnish configuration all admin ip:ports and on apply it will apply on all servers.

**Comment by aricwatson** [comment]
Closed for lack of feedback.
