### ISSUE TITLE
Get Version error after server upgrade 

### ISSUE THREAD

**Issue by brentwpeterson** [nexcess/magento-turpentine#757]
I am getting the following error after upgrading to PHP5.4

Fatal error: Call to a member function getVersion() on a non-object in app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php on line 34

**Comment by jg-development** [comment]
As far as I can see this can happen through the method getSocket
```php
    /**
     * Get a Varnish management socket
     *
     * @param  string $host           [description]
     * @param  string|int $port           [description]
     * @param  string $secretKey=null [description]
     * @param  string $version=null   [description]
     * @return Nexcessnet_Turpentine_Model_Varnish_Admin_Socket
     */
    public function getSocket( $host, $port, $secretKey=null, $version=null ) {
        $socket = Mage::getModel( 'turpentine/varnish_admin_socket',
            array( 'host' => $host, 'port' => $port ) );
        if( $secretKey ) {
            $socket->setAuthSecret( $secretKey );
        }
        if( $version ) {
            $socket->setVersion( $version );
        }
        return $socket;
    }
```
If this function returns null the call "$version = $socket->getVersion();" results in an error.
But it seems this only happens if the cache is activated without a proper config in the backend.
Did you have all settings correct before you activaed the extension?

**Comment by miguelbalparda** [comment]
@brentwpeterson did you find a workaround for this issue? Have you tried what @jg-development suggested?

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.

**Comment by ProxiBlue** [comment]
Old ticket, although closed, some feedback, in case someone else gets this issue.
Issue produced after removing all server entries from server list in admin, and hitting save of that config.

Simply clear cache (using cli tool, such as n98-magerun). This clears any latent (cached) configs, and error goes away.
