### ISSUE TITLE
Defined Registry Key always returns Null

### ISSUE THREAD

**Issue by danhanly** [nexcess/magento-turpentine#760]
I'm creating a menu, and in order for its active state to be honoured, I'm trying to turn the cache off the block entirely and ensure that certain registries and events are accessible. It may be a little overkill.

I've defined my menu block as below:

```xml
<block type="danhanly/my_menu" name="my_menu" as="my_menu">
    <action method="setEsiOptions">
        <params>
            <access>private</access>
            <scope>page</scope>
            <ttl>0</ttl>
            <flush_events>
                <controller_action_predispatch />
            </flush_events>
            <registry_keys>
                <current_category />
            </registry_keys>
        </params>
    </action>
</block>
```

If I visit a category page, the `current_category` registry returns null.
Locally, where Varnish is inactive, the following line returns an instance of the correct category:

```php
Mage::registry('current_category');
```

On our staging server, where varnish is active, the same line returns null.

**Comment by aricwatson** [comment]
Have you tried using this?
```
<method>ajax</method>
```

**Comment by aricwatson** [comment]
Closed for lack of feedback.

**Comment by processkiller** [comment]
Hi,
I have the same problem, but with current_product registry in catalog_product_view. Could you help me please?
