### ISSUE TITLE
It work not with all extension

### ISSUE THREAD

**Issue by mediadiv** [nexcess/magento-turpentine#761]
Hi, we got a problem with the slider at our shop. After the activate varnish the show the slider to all the pages. They should only visible at the start page. See at our site http://shop.arnoldproducts.eu.
Then we got a product finder at http://shop.arnoldproducts.eu/en/forestry.html. They don´t work after the activated the varnish. Can you give me a info, how we can fix that?

Thanks for your help

Timo

**Comment by aricwatson** [comment]
Closed for lack of feedback.
