### ISSUE TITLE
Limit to amount of pages cached?

### ISSUE THREAD

**Issue by Schoeny1** [nexcess/magento-turpentine#763]
Hello,

I am running the cache warmer script daily, but it seems that not all pages are getting cached.  These pages are in the sitemap.xml which the warmer crawls, but checking on some of the pages the next day shows they are not cached.  My TTL for Turpentine is 7 days.

I have 16454 URLs in the sitemap.  Is there a limit to how many pages stay cached?

**Comment by Schoeny1** [comment]
I am wondering now if this is happening due to the amount of space allocated to varnish.  I am using the default settings which allocate 1GB of Varnish Storage Size.  Should there be any varnish tweaking for larger sites to keep more URLs cached?

**Comment by magenx** [comment]
sounds like your cache is kept for user individually, check headers information from access log and varnish log when warmer is running

**Comment by Schoeny1** [comment]
I ended up increasing the size to 2GB and it works great!
