### ISSUE TITLE
Refreshing the cache

### ISSUE THREAD

**Issue by darylscott** [nexcess/magento-turpentine#764]
Can you please confirm if our varnish cache can be refreshed automatically?
We have an issue with pricing because tax/vat exempt orders show the same for all customers, until we refresh the cache again.

**Comment by magenx** [comment]
you need to find the block name that holds your prices/tax details, and define this block in turpentine_esi.xml file in your layout folder, or apply esi settings directly in any layout xml file where is this block already defined.
