### ISSUE TITLE
Turpertine not working with silly slideshow

### ISSUE THREAD

**Issue by sz00gun** [nexcess/magento-turpentine#765]
I use Magento 1.9 + Turpentine with Varnish 3.0.6 also default vcl settings from Turpentine.

I have a silly Magento MT Slideshow which generates slideshows with error 400 - Bad request only with Turpentine on.

The problem with generated pictures with timthumb.php

http://website.com/js/magenthemes/mtslideshow/timthumb/timthumb.php?src=http://1.szogun.eu/media/mtslideshow/cache/1/9df78eabhfgh6fgghj27136e95/a/l/picture_1.jpg&h=464&w=744

Please have a look how the error look like: http://s30.postimg.org/9bxc3nbkv/turper_vcl.png

Any fast solution for it?

**Comment by aricwatson** [comment]
Have you tried  adding the timthumb URLs in the turpentine back-end to keep varnish from caching them? 
https://github.com/nexcess/magento-turpentine/wiki/Configuration#url-based-caching

Or, in https://github.com/nexcess/magento-turpentine/issues/452 someone mentioned that updating timthumbs seems to have fixed their problems. Might be worth trying.
