### ISSUE TITLE
Helping to Set

### ISSUE THREAD

**Issue by iurimedeiros** [nexcess/magento-turpentine#766]
Hello I'm having trouble setting up, could you help me please?

**Comment by magenx** [comment]
what exactly you need to setup?

**Comment by iurimedeiros** [comment]
I really do not configure my server is shared, if possible could you set for me? If so I am willing to collaborate with some money in return.
![sem titulo-2](https://cloud.githubusercontent.com/assets/11665895/6856117/7be5d442-d3dc-11e4-8bca-48a6b2aa3ecd.jpg)

**Comment by iurimedeiros** [comment]
![sem titulo-2](https://cloud.githubusercontent.com/assets/11665895/6856204/1790008e-d3dd-11e4-9090-c27ab4a46777.jpg)

**Comment by magenx** [comment]
if you have shared account, im afraid this is not possible, you need to contact your hosting provider/system administrator.
