### ISSUE TITLE
can't start varnish by service varnish start ; only can start varnish by /etc/init.d/varnish start

### ISSUE THREAD

**Issue by europafashions** [nexcess/magento-turpentine#768]
Dear Sir,

After installing varnish it is not starting properly.
As you can see in attached varnish.jpg

![varnish](https://cloud.githubusercontent.com/assets/4511283/6886674/42be5b64-d65f-11e4-8f7e-af75430f7617.jpg)

can't start varnish by
service varnish start

only can start varnish by
/etc/init.d/varnish start

Note: but after restarting VPS varnish not auto restarting.

OS: centos 6
website url: http://www.wholesaleshopping.co.uk

Please guide

**Comment by aricwatson** [comment]
This appears to be an unrelated varnish/linux issue. Try checking with your web host.
