### ISSUE TITLE
Varnish caches per session. How to avoid that?

### ISSUE THREAD

**Issue by datashock** [nexcess/magento-turpentine#770]
Developer said he configured everything correctly, made punchholes, blocks, but:

Looks like Varnish is caching somehow per session. I noticed that when using Chrome incognito mode. I go to www.discount4pets.nl from Chrome Incognito mode:
- homepage loads very slow
- then when i start opening categories, and come back to them they are showing instantly. As more I use site it more becomes cached and works great
- then i close Incognito and open it again, like a fresh browser, and it AGAIN works slow like the first time

What is he doing wrong? Is there something that should be configured?

Rgds,
Oliver

**Comment by aricwatson** [comment]
This would be an issue to bring up with your developer -  perhaps they should look into the ESI policies they've configured - specifically the *access* parameter:
https://github.com/nexcess/magento-turpentine/wiki/ESI_Cache_Policy
