### ISSUE TITLE
Infinite redirect using Aheadworks Mobile 2 Template

### ISSUE THREAD

**Issue by dpdenton** [nexcess/magento-turpentine#773]
I've installed the latest Aheadworks mobile 2 template (2.0.3) on our dev site which has Varnish running but turpentine is not installed on the mage installation, and everything works fine.

After moving the mobile template to the live site which has Turpentine 0.6.1 running on Magento 1.7.0.2 and Varnish 3 there seems to be some kind of infinite redirect occurring which means the page fails to load on mobile devices.

On the rare occasion it has loaded I've seen a bunch of header blocks being loaded, all nested in each other which suggests it's reloading that block each time within the same block and never getting to the end of the page..

I've enabled 'Normalize User-Agent' and played around with the configurations but can't get anything to work.

The site is at www.modedesigns.co.uk/shop

If someone could point me in the direction of what's going on?

**Comment by aricwatson** [comment]
Are you using the default turpentine_esi.xml file, or have you added any customizations (there or in another xml layout file)?

Just for debugging, you could try commenting out any policies for the header block to see if that solves the problem.

**Comment by aricwatson** [comment]
Closing for lack of feedback.

**Comment by odi-um** [comment]
Hi @dpdenton, 

Just in case somebody faced same issue. It's an issue with AW_Mobile2_Model_Observer::_checkHomePage method. Nexcess solution want be able to change this in any way. Imo best to do is move this logic into controller rewrite of cms_index_index. It will be cleaner and not so performance heavy.
