### ISSUE TITLE
Category url key change does not ban the url (Magento EE 1.13.1)

### ISSUE THREAD

**Issue by SirTarox** [nexcess/magento-turpentine#775]
Dear Nexcess.net Turpentine team,

our company is currently using your Turpentine module for Magento in several projects.

Using the Magento Enterprise 1.13.1 edition we encountered the following error:
When a category url key is changed, the category is accessible through both urls; the old one and the new one. Due to varnish the old url still contains obsolete content and is not banned.

Are you aware of this problem and does a bugfix for this already exist; and if not, could you please fix that problem?

I would appreciate a short feedback from your side.

Yours sincerely,
SirTarox

**Comment by miguelbalparda** [comment]
@SirTarox this is regular Magento behaviour creating redirects.
