### ISSUE TITLE
Breadcrumbs not being updated based on referer

### ISSUE THREAD

**Issue by phpdave11** [nexcess/magento-turpentine#776]
I just set up this extension on my Magneto 1.9.1 store, and everything works great, except that the breadcrumbs don't change anymore.  Without this extension enabled, the breadcrumbs used to show you how you got to page.

For example, if you got to the product from the home page, the breadcrumbs should say:
Home > ABC Product

If you got to the product from a category, the breadcrumbs should say something like this:
Home > Some Category > Some Subcategory > ABC Product

If you visit the product from another subcategory, the breadcrumbs should be updated:
Home > Another Category > A Different Subcategory > ABC Product

I've tried adding the following setEsiOptions parameters in my local XML file, but I couldn't get it to work:

    <reference name="breadcrumbs">
        <action method="setEsiOptions">
            <params>
                <access>private</access>
            </params>
        </action>
    </reference>
After I added that XML and applied the Varnish config and flushed the cache, the breadcrumbs disappeared completely.

Is there any way I can use this extension while still having dynamically updated breadcrumbs?

**Comment by aricwatson** [comment]
Have you turned on debugging and block logging to ensure that the breadcrumb block is using ESI?

It might be worth try ajax as well for that block.

**Comment by aricwatson** [comment]
Closing for lack of feedback.
