### ISSUE TITLE
I want to bypass a block 

### ISSUE THREAD

**Issue by mvaisberg** [nexcess/magento-turpentine#777]
Hi,

I install varnish-turpentine succesfully. 
Now i want that a block for example 
```xml
<block type="catalog/product_view_media" name="product.info.media" as="media" template="catalog/product/view/media.phtml">
    <block type="core/text_list" name="product.info.media.after" as="after" />
 </block>
```
in ``` <catalog_product_view> ``` not to be cached

I try with ESI block in turpentine_esi.xml i add:

```xml
<catalog_product_view> 
       <reference name="product.info.media">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <flush_events>
                        <sales_quote_save_after/>
                    </flush_events>
                    <ttl>1</ttl>
                </params>
            </action>
        </reference>
</catalog_product_view>
```
but that only hide the block. What am i doing wrong?

I need help with this.

Thank very much

**Comment by mvaisberg** [comment]
anyone who can help me with this? I can not solve

thankss

**Comment by phpdave11** [comment]
mvaisberg, are you using Magento 1.9.1.0?  I've noticed that this extension hasn't been updated since Magneto 1.9.1.0 was released, which may explain why it only hides the block.  I'm having similar problems with breadcrumbs being hidden when I try to set the ESI options.

**Comment by mvaisberg** [comment]
yes i am using Magento 1.9.1.0. You know how to solve it to work in this version?

**Comment by mvaisberg** [comment]
@phpdave11  Did you find the solution to this problem?

**Comment by ichalov** [comment]
Is there a specific reason you want to make this block private? You would have the same issue in 1.8.1 too. You can overcome it by requesting 'current_product' registry key like this:
```xml
    <catalog_product_view>
        <reference name="product.info.media">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <flush_events>
                        <sales_quote_save_after/>
                    </flush_events>
                    <ttl>1</ttl>
                    <registry_keys>
                        <current_product/>
                    </registry_keys>
                </params>
            </action>
        </reference>
    </catalog_product_view>
```

and adding this method:
```php
    public function getProduct()
    {
        return Mage::registry('current_product');
    }
```
in Mage_Catalog_Block_Product_View_Media ( app/code/core/Mage/Catalog/Block/Product/View/Media.php ).

**Comment by mvaisberg** [comment]
Great!! thanks very much! that works perfectly!!
