### ISSUE TITLE
Is this extension dead already?

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#778]
There are a lot of open issues. Some of them really basic, no 1.9 support yet. I would like to ask those who maintain this if the project is dead already. An honest statement will pay the whole frustration accumulated into this project for more than 1 year.

**Comment by mvaisberg** [comment]
+1

**Comment by aricwatson** [comment]
We still maintain and use turpentine on a large number of our clients. It is certainly not dead! We have been extremely busy preparing for and attending Imagine 2015, but we're back now and hope to begin pushing turpentine forward again in the coming months.

**Comment by ADDISON74** [comment]
Thank you for your post. I hope to see the things moving. There are a lot of open issues and we need help. Please take a look to the answers, in the last more than year the Nexcess team missed this extension support. We need a solution for using it with Magento 1.9, also having a solution for Varnish 4. I guess this is a win-win situation, having feedback you can maintain this extension in a great shape. 

If you get time I am struggling with Community Poll, not because I would like to use it, just because the way I solve this issue will help me solving others. Community Poll it is cached and ESI policy it is not working. This issue is present from Magento 1.5 to 1.9.

**Comment by evensis** [comment]
In all fairness, this is what your reps said at MagentoLive in July last year, and @aheadley repeated some time after, so i'm taking it with a pinch of salt. However, if true, excellent - there's certainly a fair few issues with the module that need addressing.

**Comment by ADDISON74** [comment]
This is a public statement on April the 5th from @aheadley:

"I'm no longer working for Nexcess so it's not up to me. I'm not sure who is taking over the project unfortunately."

What I can say more? 8 months without a new release or replies for support. Too bad, this could be the end of a nice extension for Magento. So long Turpentine!

**Comment by aricwatson** [comment]
I understand the frustration, and we have been working on cleaning up issues and moving the extension forward. We use this extension on *lots* of Magento sites and will continue to support/improve it.

**Comment by ADDISON74** [comment]
@aricwatson : Thank you for your message. This is really encouraging.
