### ISSUE TITLE
ESI processing not enabled on Manadev Layered Navigation with Mana_Ajax enabled

### ISSUE THREAD

**Issue by Hrafnahnef** [nexcess/magento-turpentine#781]
We are running turpentine on two different sites, CE 1.7.0.2 (nginx, php 5.3) and CE 1.9.1 (nginx, php 5.4) and are having an issue with a 3rd party module (Manadev Layered Navigation). Both sites are running Varnish 3.0.7

The problem arises when `Mana_Ajax` is enabled and the category filters causes a ajax reload of the actual site content instead of a document reload. One of the ESI blocks fails to load and puts the following in the HTML source:

    
    
    <esi:remove>ESI processing not enabled</esi:remove>
    
    

The Ajax request gets these response headers

    Via:1.1 varnish
    X-Powered-By:PHP/5.3.10-1ubuntu3.17
    X-Turpentine-Cache:1
    X-Turpentine-Esi:1
    X-Varnish:2013362417
    X-Varnish-Currency:
    X-Varnish-Esi-Access:
    X-Varnish-Esi-Method:
    X-Varnish-Hits:0
    X-Varnish-Host:example.com
    X-Varnish-Set-Cookie:frontend=foobar; expires=Thu, 30-Apr-2015 07:53:16 GMT; path=/; domain=example.com; httponly
    X-Varnish-Store:
    X-Varnish-URL:/ajax/layered-navigation/catalog/category/view/id/28/requested-url/foobar?color=17_15

When we curl the  `http:/example.com/turpentine/esi/getBlock/method/esi/access/private/ttl/3600/hmac/.../data/.../` url we get the dreaded magento white page of death (200 OK but without any content) and nothing at all in our logs. We have manually tried to add our own exception_handler, error_handler and shutdown_function which does Mage::log(error_get_last(), 3, 'our.log');

The HTTP response headers we get for our direct request are

    Server:nginx/1.6.2
    Via:1.1 varnish
    X-Powered-By:PHP/5.3.10-1ubuntu3.17
    X-Turpentine-Block:messages
    X-Turpentine-Cache:1
    X-Turpentine-Esi:0
    X-Turpentine-Flush-Events:customer_login,customer_logout,core_session_abstract_add_message
    X-Varnish:2013359056 2013359046
    X-Varnish-Currency:
    X-Varnish-Esi-Access:private
    X-Varnish-Esi-Method:esi
    X-Varnish-Hits:9
    X-Varnish-Host:example.com
    X-Varnish-Session:foobar
    X-Varnish-Set-Cookie:frontend=foobar; expires=Thu, 30-Apr-2015 06:56:44 GMT; path=/; domain=example.com; httponly
    X-Varnish-Store:
    X-Varnish-URL:/turpentine/esi/getBlock/method/esi/access/private/ttl/3600/hmac/.../data/.../

And the *only* thing that shows up in our log are 

    2015-04-30T07:06:39+00:00 ERR (3): Array
    (
        [type] => 8
        [message] => Undefined index: block
        [file] => /www/app/code/community/Nexcessnet/Turpentine/Model/Shim/Mage/Core/Config.php
        [line] => 36
    )

We have tried with the setting `Fix Product List Toolbar` both enabled and disabled with no success. We have now ran into a dead end and don't know how to further debug this issue and pinpoint a solution (other than disabling the ajax reload which is not really a solution).

**Comment by ichalov** [comment]
It's difficult to tell what's happening without looking at the code. Overall, I believe it will get solved only by fixing something in magento core or extension code and not by changing anything about turpentine. 

1. What would happen if you remove <reference name="messages"> block from app/design/frontend/base/default/layout/turpentine_esi.xml ? (I guess it may start showing someone else's message to all other visitors of the same URL, so it's risky to implement on the live site).
2. It may help to check if Mana_Ajax or any other extension overrides 'messages' block layout attributes (by searching for <reference name="messages"> text in the whole app/ directory). Another possible case is that PHP class of this block may be overridden as well, but that's more tricky to find.

**Comment by Hrafnahnef** [comment]
There is no other <reference name="messages">, unfortunately. There isn't much code in Mana_Ajax and nothing of it overrides anything. Of course, it is possible that part is done in another Mana_* module (there are ~20) which relies on Mana_Ajax.

Removing the <reference name="messages"> block from turpentine_esi.xml **does** fix the ajax reload. However, as predicted, actual messages such as "added to cart/wishlist/compare list" ends up in the cache for all visitors. That is, if the cache was empty. Otherwise, no message is shown at all because the page was fetched from the cache.

**Comment by ichalov** [comment]
Does it show the same cached message on all pages or just that one where it was initially received? In the first case it may be because messages are cached as AJAX response and not as part of magento page. It would help to learn what AJAX URL is used to fetch messages from server and put the prefix of this URL into 'URL blacklist' setting of turpentine config. That would make a great workaround solution, but it's still hard to understand how it got broken in the first place.

**Comment by ichalov** [comment]
I just noticed there's 'Enable AJAX Flash Messages' setting in Varnish Options section of turpentine config. It may be useful to switch it and look how it affects messages block.

**Comment by aricwatson** [comment]
Closed for lack of feedback.

**Comment by viansolutions-com** [comment]
I have faced this problem with some of our customers
Problem (in a default configuration) is ESI processing requires the header X-Turpentine-Secret-Handshake set to 1 in an Ajax request to work 

You can fix this issue for Messages block just adding that header in the Mana ajax request process

**Comment by werfu** [comment]
@viansolutions-com would you mind detailing how you fixed the issue? I'm facing the exact same problem.

**Comment by viansolutions-com** [comment]
I pointed the solution, as it was clear the header was required for Turpentine to enable ESI in Ajax requests, but in our case it was not a problem with Mana (we don't use catalog messages in Layered Navigation), our case was jQuery code written by us, so adding the header was easy

In your case, you'll need to find the piece of code which handles the Ajax request inside the multiple Mana modules. Not easy... Maybe you'd contact Mana team for support

**Comment by aricwatson** [comment]
Thanks @rossmc - as a general note for these sorts of Ajax issues, if you open your developer tools (Chrome or Firefox) and choose 'network' and then interact with the extension (probably best to do this with the Varnish bypass turned on), you should see the URLs of the requests being triggered by the Ajax code (i.e. *ajax/layered-navigation/catalog/category/view* in this case) - blacklisting those will prevent Varnish from caching anything from those URLs.

**Comment by lrkwz** [comment]
@viansolutions-com worked for me either. I'm integrating a theme which uses ajaxsupercart used in ol'ver 1.7
