### ISSUE TITLE
getting cms esi blocks to work

### ISSUE THREAD

**Issue by st-bobb** [nexcess/magento-turpentine#782]
I see that cms blocks get anonymous names like 'ANONYMOUS_52'. How would I reference them in my xml. I tried adding via Layout Update XML as suggested in 
https://github.com/nexcess/magento-turpentine/issues/75

I essentially need an uncached cms block for every request as I am getting issues with form keys. USers without a session are not getting good form keys right now.
Any thoughts much appreciated

local.xml:
```
  <reference name="cmsaddtocart">
	        <action method="setEsiOptions">
		    <params>
		        <ttl>0</ttl>
		        <access>private</access>
		        <method>ajax</method>
		    </params>
	        </action>
	    </reference>
```
Layout updates xml for the specific CMS page:
```
    <reference name="content">
    <block type="st_component/Cmsaddtocart" name="cmsaddtocart" template="st/component/cms_addtocart.phtml"/>
    </reference>
```

**Comment by aricwatson** [comment]
Hi -

Turpentine can't apply options on anonymous blocks, so your options are either using a parent block, or changing the layout.xml (see https://github.com/nexcess/magento-turpentine/issues/75)
