### ISSUE TITLE
Caching header module works incorrectly

### ISSUE THREAD

**Issue by webgear** [nexcess/magento-turpentine#785]
Hello,

We've tried to install & configure the Varnish module for a recently upgraded Magento 1.9.1.0 website. It works great so far, speed went through the roof, caching seems to work well on most pages, but there is a small issue that we cannot overcome.

In the header, there's a search autocomplete function, different than the Magento default one. The block is top.search (aliased as topSearch), and its called inside the header.phtml like so: $this->getChildHtml('topSearch'); (tried adding false as a 2nd param, but nothing changed). The problem is that, when Varnish is enabled, the default Magento search field appears. The site is this: http://www.wintermag.ro/ (you can see a custom search in the header, with a small dropdown and a custom suggestion list). The module used for the search itself is part of the Mirasvit Sphinx Search Ultimate (https://mirasvit.com/magento-extensions/sphinx-search-ultimate.html) extension.

We've tried adding this block:

       <reference name="top.search">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <flush_events>
                        <core_session_abstract_add_message/>
                    </flush_events>
                    <only_cache_if>no_text</only_cache_if>
                </params>
            </action>
        </reference>

inside the default handle in turpentine_esi.xml but it seems to be ignored completely. Also tried to change the reference to point to the aliased name (topSearch), but again it seems to be ignored. The header reference looks like this (in the same turpentine_esi.xml file - its the turpentine default config):

        <reference name="header">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <flush_events>
                        <wishlist_item_save_after/>
                        <wishlist_item_delete_after/>
                        <sales_quote_save_after/>
                    </flush_events>
                </params>
            </action>
        </reference>

Also, the logo has some issues, in the sense that it doesnt have a link on it on secondary pages, it's as if Varnish thinks the user is always on the homepage. For pages that have the cache disabled altogher (eg: checkout), the links and search modules work correctly. This is the code for the logo itself:

        <div id="logo">
         <?php if ($this->getIsHomePage()):?>
            <img src="[...]logo.png" />
        <?php else:?>
        <a href="/" title="<?php echo $this->getLogoAlt() ?>" ><img src="[...]logo.png" /></a>
        <?php endif?>

(paths have been truncated since theyre not important, the resources show up correctly, only the conditions arent met.

What could the problem be? Thank you in advance.

**Comment by ichalov** [comment]
I'm not sure it will help, but can you try to make header block completely uncacheable by using this kind of setting:
```xml
        <reference name="header">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <ttl>-1</ttl>
                </params>
            </action>
        </reference>
```
It works on my test installation (but increases response time 3 to 100 ms, because it renders header block for every page request). It would be good to see if it helps on real sites.

**Comment by webgear** [comment]
Hello, thank you for the prompt answer, however the proposed solution does not do anything in regards to the problem. The search form is still cached, tried to add the ttl -1 setting to both the header and the top search block, all it does is indeed speed down the page just a tad, but not fixing the issue.

It's curious though that the extension output doesnt appear at all, and instead the default magento search block is rendered. I'm completely out of ideas, please let me know if you can think of any other issue that could be causing this behavior.

Thanks again.

**Comment by ichalov** [comment]
I thought it should solve problems with logo at least. Can you try to make header ttl=-1 and remove anything related to the search box from turpentine_esi.xml? Search block is nested inside header, I believe it doesn't need ESI options of its own if header is never cached.

**Comment by webgear** [comment]
I fixed the issue by completely commenting out the header reference in the turpentine_esi.xml file. Apparrently there was a problem with the public/private access, or maybe something else entirely. This increased the TTFB time by 0.01 sec (it was 0.10 now its 0.11), which is acceptable, so right now it's not a problem anymore, but it would be interesting to find the root cause, in case someone else stumbles upon the same problem in the future.

I also want to mention that the modules XML files were correctly being loaded (in the right order), and even adding a <depends><Mage_CatalogSearch /></depends> in the module's file did not do anything extra.

**Comment by treestonemedia** [comment]
@webgear  
> completely commenting out the header reference in the turpentine_esi.xml file
doesn't sound like it fixes the problem, it avoids it from happening.
Has anyone else bumped in to this issue?
