### ISSUE TITLE
Blocks caching across stores - Magento EE 1.14.2.0/CE 1.9.2.0 incomptability

### ISSUE THREAD

**Issue by craigcarnell** [nexcess/magento-turpentine#789]
Hi,

On our multi-store setup, our footer templates are being cached even tho they are setup with different themes and different URLs.

For example, If I visit site A I get site A footer. But then I visit site B, I get site A's footer.

The template is footer.phtml, the block that is output is cms_footer_links. The content of cms_footer_links is different in the admin for both stores.

This is apparent in Magento EE 1.14.2.0. This does not happen in Magento EE 1.14.1.0

**Comment by craigcarnell** [comment]
I have found the change in Magento EE 1.14.2.0. This breaks the caching of these blocks. The solution right now is to remove this new code, either through a rewrite or copying to app/code/local/Mage. Does anyone have a workaround?

class Mage_Cms_Block_Block - code added:

```
protected function _construct()
 {
   /*
    * setting cache to save the cms block
    */
    $this->setCacheTags(array(Mage_Cms_Model_Block::CACHE_TAG));
    $this->setCacheLifetime(false);
}
```

Mage_Cms_Block_Widget_Block - code was added:
```
protected function _construct()
{
parent::_construct();
/*
* setting cache to save the cms block
 */
 $this->setCacheTags(array(Mage_Cms_Model_Block::CACHE_TAG));
$this->setCacheLifetime(false);
}
```

class Mage_Page_Block_Html_Topmenu - code added:
```
/*
 * setting cache to save the topmenu block
*/
$this->setCacheTags(array(Mage_Catalog_Model_Category::CACHE_TAG));
$this->setCacheLifetime(false);
```

class Mage_Page_Block_Html_Topmenu - code removed:
```
$this->addData(array(
'cache_lifetime' => false,
));
```

**Comment by evensis** [comment]
Sounds suspiciously like a bug we had while upgrading to 1.14.2.0, request SUPEE-5874 from Varien. Don't think its necessarily an issue with varnish but a bug within the cache tagging within Enterprise.

**Comment by craigcarnell** [comment]
@evensis @aricwatson 

This now also appears to be a bug in Magento CE 1.9.2.0 (see below). With this new code that Magento uses, it's now impossible for cms blocks loaded via layout.xml to change based on the store switcher in magento. The German block that I create in the 'german store view' is cached across to the 'english store view' etc.

```
class Mage_Cms_Block_Block - code added:

/**
     * Initialize cache
     *
     * @return null
     */
    protected function _construct()
    {
        /*
        * setting cache to save the cms block
        */
        $this->setCacheTags(array(Mage_Cms_Model_Block::CACHE_TAG));
        $this->setCacheLifetime(false);
    }
```

**Comment by craigcarnell** [comment]
This appears to be a Magento bug as opposed to a Turpentine bug

**Comment by miguelbalparda** [comment]
I think this has been reported here and even has a workaround http://magento.stackexchange.com/questions/73685/magento-1-9-2-0-static-block-display-issues.

**Comment by craigcarnell** [comment]
@miguelbalparda Thanks, closing this
