### ISSUE TITLE
Original request parameters in ESI Block

### ISSUE THREAD

**Issue by t3ddftw** [nexcess/magento-turpentine#792]
Hello,

I have an ESI block that depends on URL parameters to spit out dynamic data. The page is an alphabetical listing of all of our products but the content of the page can be different if the user's session hasn't met a particular condition, hence why we're using ESI there instead of a full page cache. The problem is that it doesn't seem that the original request parameters are available to the ESI block. Are they preserved anywhere?

Thanks!

**Comment by aricwatson** [comment]
Unfortunately no, the ESI request doesn't have access to the original request's parameters. You'll need to figure out some other way to pass that information.

**Comment by t3ddftw** [comment]
Thanks for the confirmation @aricwatson. I have worked around this by implementing the solution I needed client-side in J/S.
