### ISSUE TITLE
Varnish on Server pilot: bad gateway

### ISSUE THREAD

**Issue by manisharora** [nexcess/magento-turpentine#793]
when i "Apply vcl" i get bad gateway error ? do need to change turpentine settings for this? because server pilot has some strange config

See here:
https://serverpilot.io/community/articles/how-to-install-and-configure-varnish.html

They are keeping varnish between nginx and apache
Browser --> Nginx --> Varnish --> Apache --> PHP-FPM

**Comment by aricwatson** [comment]
It sounds like perhaps Turpentine can't communicate with Varnish. The host and port options under "server list" may be the issue. Can you verify by  telnetting to the host and port set in the config?
https://github.com/nexcess/magento-turpentine/wiki/Configuration#servers
