### ISSUE TITLE
Shopping Cart is Empty

### ISSUE THREAD

**Issue by theseanstewart** [nexcess/magento-turpentine#795]
Periodically we get reports of people adding items to their cart and seeing a "Shopping Cart Is Empty" message. These reports didn't start until we upgraded to 1.9.1 after successfully using Turpentine on 1.7.1 for over a year, and our conversion rate has dropped by about 55%.

I'm not really sure where to start in diagnosing this issue, as it's seemingly random. It seems as if the user's session is expiring in Magento, but their cookie is still cached. Any ideas?

**Comment by aricwatson** [comment]
How is your storage session configured?

**Comment by theseanstewart** [comment]
We just recently switched to Redis using the built in extension.

*Sean Stewart*
Eko Internet Marketing
sean@ekoim.com
817.754.0182

**Comment by aricwatson** [comment]
This is almost certainly related to https://github.com/nexcess/magento-turpentine/issues/345

I know it's not a huge help, but if the user goes to another page first, then goes to the product page - then hits 'add to cart' this won't happen. In my testing, it only occurs when the user goes *directly* to the product page on a new session. I'm not sure if there's a way to use that information to minimize the hit you're taking on the conversion rate in the meantime :(

I'm going to close this issue, but rest assured we're working on this.
