### ISSUE TITLE
Varnish detached from Magento

### ISSUE THREAD

**Issue by mattnthat** [nexcess/magento-turpentine#797]
Im looking at a scenario where we need a disconnect between Varnish and Magento.

If I was to copy an existing generated turpentine VCL file and manually install this into Varnish is there any additional configuration needed to make this work?

Accepting that updates to things like blacklists would need to be manually edited in VCL is there any additional work needed in Magento Admin apart from enable the 2 caching blocks (Varnish Pages, Varnish ESI Blocks)?

**Comment by aricwatson** [comment]
No, I don't believe you'll need to do more than just ensure that your custom VCL was loaded correctly by Varnish. You'll also need to ensure that Turpentine can still connect to the Varnish management interface.

**Comment by mattnthat** [comment]
Cheers for feedback!

What about if it was completely detached? No management interface? - Purging wouldnt work?

Any other major functions?

**Comment by aricwatson** [comment]
Yeah, banning/purging wouldn't work, including things like automatically purging various caches when a product is saved, clearing the cache from the Magento 'cache management' admin panel, etc.

I don't believe any other major functions would be affected.

**Comment by aricwatson** [comment]
Please feel free to let us know if  you have any other questions.

**Comment by mattnthat** [comment]
Hi There,

No thats perfect. Im going to be looking to promote use of Turpentine as our preferred solution for accelerating Magento with Varnish.

Checkout: www.section.io when you have a moment, love any feedback from yourself or the community.
You can get me at matt at section.io

Talk soon

**Comment by aricwatson** [comment]
Interesting, will definitely check it out!
