### ISSUE TITLE
Magento Shopping Cart Items Visible to all

### ISSUE THREAD

**Issue by imadkhalid** [nexcess/magento-turpentine#798]
I have configured varnish with turpentine on my magento store and varnish is caching the whole page. Even the cart and checkout page is being cached. My mini cart at the top is also being Cached and visible to everyone. 

I have also defined the ESI policies inside my local.xml file.

I am missing something which I am not able to figure out please help.

**Comment by imadkhalid** [comment]
My VCL Configuration File

C{
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <pthread.h>
static pthread_mutex_t lrand_mutex = PTHREAD_MUTEX_INITIALIZER;
void generate_uuid(char* buf) {
pthread_mutex_lock(&lrand_mutex);
long a = lrand48();
long b = lrand48();
long c = lrand48();
long d = lrand48();
pthread_mutex_unlock(&lrand_mutex);
sprintf(buf, "frontend=%08lx%04lx%04lx%04lx%04lx%08lx",
a,
b & 0xffff,
(b & ((long)0x0fff0000) >> 16) | 0x4000,
(c & 0x0fff) | 0x8000,
(c & (long)0xffff0000) >> 16,
d
);
return;
}
}C
import std;
backend default {
.host = "127.0.0.1";
.port = "8080";
.first_byte_timeout = 300s;
.between_bytes_timeout = 300s;
}
backend admin {
.host = "127.0.0.1";
.port = "8080";
.first_byte_timeout = 21600s;
.between_bytes_timeout = 21600s;
}
acl crawler_acl {
"127.0.0.1";
}
acl debug_acl {
}
sub generate_session {
if (req.url ~ ".*[&?]SID=([^&]+).*") {
set req.http.X-Varnish-Faked-Session = regsub(
req.url, ".*[&?]SID=([^&]+).*", "frontend=\1");
} else {
C{
char uuid_buf [50];
generate_uuid(uuid_buf);
VRT_SetHdr(sp, HDR_REQ,
"\030X-Varnish-Faked-Session:",
uuid_buf,
vrt_magic_string_end
);
}C
}
if (req.http.Cookie) {
std.collect(req.http.Cookie);
set req.http.Cookie = req.http.X-Varnish-Faked-Session +
"; " + req.http.Cookie;
} else {
set req.http.Cookie = req.http.X-Varnish-Faked-Session;
}
}
sub generate_session_expires {
C{
time_t now = time(NULL);
struct tm now_tm = *gmtime(&now);
now_tm.tm_sec += 3600;
mktime(&now_tm);
char date_buf [50];
strftime(date_buf, sizeof(date_buf)-1, "%a, %d-%b-%Y %H:%M:%S %Z", &now_tm);
VRT_SetHdr(sp, HDR_RESP,
"\031X-Varnish-Cookie-Expires:",
date_buf,
vrt_magic_string_end
);
}C
}
sub vcl_recv {
if (req.restarts == 0) {
if (req.http.X-Forwarded-For) {
set req.http.X-Forwarded-For =
req.http.X-Forwarded-For + ", " + client.ip;
} else {
set req.http.X-Forwarded-For = client.ip;
}
}
if (!true || req.http.Authorization ||
req.request !~ "^(GET|HEAD)$" ||
req.http.Cookie ~ "varnish_bypass=1") {
return (pipe);
}
set req.url = regsuball(req.url, "(.*)//+(.*)", "\1/\2");
if (req.http.Accept-Encoding) {
if (req.http.Accept-Encoding ~ "gzip") {
set req.http.Accept-Encoding = "gzip";
} else if (req.http.Accept-Encoding ~ "deflate") {
set req.http.Accept-Encoding = "deflate";
} else {
unset req.http.Accept-Encoding;
}
}
if (req.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?") {
set req.http.X-Turpentine-Secret-Handshake = "1";
if (req.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?admin") {
set req.backend = admin;
return (pipe);
}
if (req.http.Cookie ~ "\bcurrency=") {
set req.http.X-Varnish-Currency = regsub(
req.http.Cookie, ".*\bcurrency=([^;]*).*", "\1");
}
if (req.http.Cookie ~ "\bstore=") {
set req.http.X-Varnish-Store = regsub(
req.http.Cookie, ".*\bstore=([^;]*).*", "\1");
}
if (req.url ~ "/turpentine/esi/get(?:Block|FormKey)/") {
set req.http.X-Varnish-Esi-Method = regsub(
req.url, ".*/method/(\w+)/.*", "\1");
set req.http.X-Varnish-Esi-Access = regsub(
req.url, ".*/access/(\w+)/.*", "\1");
if (req.http.X-Varnish-Esi-Method == "esi" && req.esi_level == 0 &&
!(false || client.ip ~ debug_acl)) {
error 403 "External ESI requests are not allowed";
}
}
if (req.http.Cookie !~ "frontend=") {
if (client.ip ~ crawler_acl ||
req.http.User-Agent ~ "^(?:ApacheBench/.*|.*Googlebot.*|JoeDog/.*Siege.*|magespeedtest\.com|Nexcessnet_Turpentine/.*)$") {
set req.http.Cookie = "frontend=crawler-session";
} else {
call generate_session;
}
}
if (true &&
req.url ~ ".*\.(?:css|js|jpe?g|png|gif|ico|swf)(?=\?|&|$)") {
unset req.http.Cookie;
unset req.http.X-Varnish-Faked-Session;
return (lookup);
}
if (req.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?(?:admin|api|cron\.php)" ||
req.url ~ "\?.*__from_store=") {
return (pipe);
}
if (true &&
req.url ~ "(?:[?&](?:__SID|XDEBUG_PROFILE)(?=[&=]|$))") {
return (pass);
}
if (req.url ~ "[?&](utm_source|utm_medium|utm_campaign|gclid|cx|ie|cof|siteurl)=") {
set req.url = regsuball(req.url, "(?:(\?)?|&)(?:utm_source|utm_medium|utm_campaign|gclid|cx|ie|cof|siteurl)=[^&]+", "\1");
set req.url = regsuball(req.url, "(?:(\?)&|\?$)", "\1");
}
return (lookup);
}
}
sub vcl_pipe {
unset bereq.http.X-Turpentine-Secret-Handshake;
set bereq.http.Connection = "close";
}
sub vcl_hash {
hash_data(req.url);
if (req.http.Host) {
hash_data(req.http.Host);
} else {
hash_data(server.ip);
}
hash_data(req.http.Ssl-Offloaded);
if (req.http.X-Normalized-User-Agent) {
hash_data(req.http.X-Normalized-User-Agent);
}
if (req.http.Accept-Encoding) {
hash_data(req.http.Accept-Encoding);
}
if (req.http.X-Varnish-Store || req.http.X-Varnish-Currency) {
hash_data("s=" + req.http.X-Varnish-Store + "&c=" + req.http.X-Varnish-Currency);
}
if (req.http.X-Varnish-Esi-Access == "private" &&
req.http.Cookie ~ "frontend=") {
hash_data(regsub(req.http.Cookie, "^.*?frontend=([^;]*);*.*$", "\1"));
hash_data(client.ip);
hash_data(req.http.Via);
hash_data(req.http.X-Forwarded-For);
hash_data(req.http.User-Agent);
}
return (hash);
}
sub vcl_hit {
}
sub vcl_fetch {
set req.grace = 15s;
set beresp.http.X-Varnish-Host = req.http.host;
set beresp.http.X-Varnish-URL = req.url;
if (req.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?") {
unset beresp.http.Vary;
set beresp.do_gzip = true;
if (beresp.status != 200 && beresp.status != 404) {
set beresp.ttl = 15s;
return (hit_for_pass);
} else {
if (beresp.http.Set-Cookie) {
set beresp.http.X-Varnish-Set-Cookie = beresp.http.Set-Cookie;
unset beresp.http.Set-Cookie;
}
unset beresp.http.Cache-Control;
unset beresp.http.Expires;
unset beresp.http.Pragma;
unset beresp.http.Cache;
unset beresp.http.Age;
if (beresp.http.X-Turpentine-Esi == "1") {
set beresp.do_esi = true;
}
if (beresp.http.X-Turpentine-Cache == "0") {
set beresp.ttl = 15s;
return (hit_for_pass);
} else {
if (true &&
bereq.url ~ ".*\.(?:css|js|jpe?g|png|gif|ico|swf)(?=\?|&|$)") {
set beresp.ttl = 28800s;
set beresp.http.Cache-Control = "max-age=28800";
} elseif (req.http.X-Varnish-Esi-Method) {
if (req.http.X-Varnish-Esi-Access == "private" &&
req.http.Cookie ~ "frontend=") {
set beresp.http.X-Varnish-Session = regsub(req.http.Cookie,
"^.*?frontend=([^;]*);*.*$", "\1");
}
if (req.http.X-Varnish-Esi-Method == "ajax" &&
req.http.X-Varnish-Esi-Access == "public") {
set beresp.http.Cache-Control = "max-age=" + regsub(
req.url, ".*/ttl/(\d+)/.*", "\1");
}
set beresp.ttl = std.duration(
regsub(
req.url, ".*/ttl/(\d+)/.*", "\1s"),
300s);
if (beresp.ttl == 0s) {
set beresp.ttl = 15s;
return (hit_for_pass);
}
} else {
set beresp.ttl = 3600s;
}
}
}
return (deliver);
}
}
sub vcl_deliver {
if (req.http.X-Varnish-Faked-Session) {
call generate_session_expires;
set resp.http.Set-Cookie = req.http.X-Varnish-Faked-Session +
"; expires=" + resp.http.X-Varnish-Cookie-Expires + "; path=/";
if (req.http.Host) {
set resp.http.Set-Cookie = resp.http.Set-Cookie +
"; domain=" + regsub(req.http.Host, ":\d+$", "");
}
set resp.http.Set-Cookie = resp.http.Set-Cookie + "; httponly";
unset resp.http.X-Varnish-Cookie-Expires;
}
if (req.http.X-Varnish-Esi-Method == "ajax" && req.http.X-Varnish-Esi-Access == "private") {
set resp.http.Cache-Control = "no-cache";
}
if (false || client.ip ~ debug_acl) {
set resp.http.X-Varnish-Hits = obj.hits;
set resp.http.X-Varnish-Esi-Method = req.http.X-Varnish-Esi-Method;
set resp.http.X-Varnish-Esi-Access = req.http.X-Varnish-Esi-Access;
set resp.http.X-Varnish-Currency = req.http.X-Varnish-Currency;
set resp.http.X-Varnish-Store = req.http.X-Varnish-Store;
} else {
#unset resp.http.X-Varnish;
#unset resp.http.Via;
#unset resp.http.X-Powered-By;
#unset resp.http.Server;
#unset resp.http.X-Turpentine-Cache;
#unset resp.http.X-Turpentine-Esi;
#unset resp.http.X-Turpentine-Flush-Events;
#unset resp.http.X-Turpentine-Block;
#unset resp.http.X-Varnish-Session;
#unset resp.http.X-Varnish-Host;
#unset resp.http.X-Varnish-URL;
#unset resp.http.X-Varnish-Set-Cookie;
}
}

**Comment by imadkhalid** [comment]
Policies defined in turpentine_esi.xml file for cart 

    <reference name="cart_sidebar">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <flush_events>
                        <sales_quote_save_after/>
                    </flush_events>
                </params>
               <ttl>0<ttl/>
            </action>
        </reference>
       <reference name="mini-cart">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <flush_events>
                        <sales_quote_save_after/>
                    </flush_events>
                </params>
             <ttl>0<ttl/>
            </action>
        </reference>

**Comment by aricwatson** [comment]
Try turning on the varnish debug and block logging. Then flush the varnish caches and reload the page. Do you see your blocks ('cart_sidebar' and 'mini-cart') in the log? If you look at the page source, you should also the ESI urls that varnish is using for each of those blocks.

**Comment by imadkhalid** [comment]
In  varnish log through this command.

varnishlog -b | grep 'TxURL'

When I click cached page from one system/PC I found this url in varnish log 

12 TxURL        b /turpentine/esi/getBlock/method/esi/access/private/ttl/3600/hmac/fdd2cc183f810c80722ce5b01dc6f9e5ca41e69086a68feef907ee5a1019be4c/data/SCd6HJ50rvAn6tVpiHt1iyog6uyok.rKZCGp64iIi.aQ8Ml3bS2RDPGRU7-RYRqQSvdhz6-zeD5d9ZhkzbY8akLR6zip40v7-mKDrT3h8Vd8ADWrDJcZ5Pm

When I clicked the same URL from different PC I found this url in varnish log again and I think this is the block which is about cart
I can see the product I added from both systems.

12 TxURL        b /turpentine/esi/getBlock/method/esi/access/private/ttl/3600/hmac/fdd2cc183f810c80722ce5b01dc6f9e5ca41e69086a68feef907ee5a1019be4c/data/SCd6HJ50rvAn6tVpiHt1iyog6uyok.rKZCGp64iIi.aQ8Ml3bS2RDPGRU7-RYRqQSvdhz6-zeD5d9ZhkzbY8akLR6zip40v7-mKDrT3h8Vd8ADWrDJcZ5Pm

**Comment by aricwatson** [comment]
OK, so it's trying to get blocks via ESI. One other thing worth checking - I notice your VCL has been customized quite a bit, have you tried loading the default one to see if things start working with that?

- Aric

**Comment by imadkhalid** [comment]
This VCL is the turpentine generated VCL. I copied that from magento/var/ directory and loaded in /etc/varnish/default.vcl

Am I right in saying that we do have to use this turpentine generated vcl?

**Comment by aricwatson** [comment]
Yes you should be sure it's using the turpentine generated VCL. You can try hitting the *Apply Varnish Config* button on the cache management screen in the back-end to make sure it loads the VCL, and then clear the caches to rule out that the wrong VCL is running somehow or something like that.

The other place to check would be your system.log and possibly the exception log.

Another thing to check is that you have full page caching turned off (if you're running EE) - other caching plugins can also cause problems.

**Comment by imadkhalid** [comment]
My turpentine_esi.xml is located in /app/design/frontend/base/default/layout

Where as my theme directory is /app/design/frontend/sns_twen/default/layout.

My page.xml has mini-cart block where as my checkout.xml has cart_sidebar block...My local.xml has no block related to cart. Should the policies defined in turpentine is enough or i have to define those in all other files as well.?

**Comment by imadkhalid** [comment]
Only varnish caches are enabled and all the other caches are disabled.

One more thing when the varnish caching started initially my header was disappearing. I resolved this issue by commenting out the <reference name=""header"> tag from turpentine_esi.xml file and my header appeared.

**Comment by imadkhalid** [comment]
I even compared both VCL files and they were same hence I used the same exact Turpentine Generated VCL File.

**Comment by aricwatson** [comment]
>One more thing when the varnish caching started initially my header was disappearing. I resolved this issue by commenting out the tag from turpentine_esi.xml file and my header appeared.

This is why your cart is being cached publicly now. When you commented out the header ESI config, it will now be cached as part of the whole page, which is publicly cached. You should now set up an ESI caching policy just for your shopping cart block:

```
<reference name="cart_sidebar">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <flush_events>
                        <sales_quote_save_after/>
                    </flush_events>
                </params>
            </action>
</reference>
```

and change the reference name parameter to the name of the block in your theme.

**Comment by aricwatson** [comment]
Closing for lack of feedback.
