### ISSUE TITLE
Varnish + Linksture Coupon Extension

### ISSUE THREAD

**Issue by loginid** [nexcess/magento-turpentine#799]
Hi there!

After quite a little fiddling around, I've finally been able to install magento-turpentine.
Thanks for a great contribution :)
I think I'm already getting some faster page loads, so really happy about that. 

I am having a problem with one extension though, it is this one : 
http://www.magentocommerce.com/magento-connect/linksture-discount-coupon-code-link.html

To use the extension I can just give my customers a link such as : 
http://www.yourstore.com/applycoupon/?code=couponcode&return_url=http://www.domainname.com

Then when they click the link it applies the coupon for them automatically and takes them to the return_url that I've specified.

Problems I'm facing : 

1. The return_url doesn't seem to work - it just takes me to (using the example above): 
http://www.yourstore.com/www.domainname.com  -  which returns a 404

2. When it applies the coupon (which it does successfully - which is great!) It loads the return_url and then states: "Coupon automatically applied" with a green tick sign (see image) 
![little-green-tick](https://cloud.githubusercontent.com/assets/12857044/8125466/365cfa42-1129-11e5-8406-aa5f7c1ac5e4.JPG) but now it doesn't. It just shows: 
![no-little-green-tick](https://cloud.githubusercontent.com/assets/12857044/8125513/7b30a542-1129-11e5-9382-c5e16b52e39a.JPG)

Could you please help me to identify how I can put coupon functionality outside of the cache?

Thank you!!

PS - thanks for all the hard work on the turpentine extension again, it's really rad.

**Comment by aricwatson** [comment]
Glad it's proving useful!

It sounds like you can fix the coupon functionality by adding *applycoupon* to the URL blacklist:
https://github.com/nexcess/magento-turpentine/wiki/Configuration#url-based-caching

Then you might want to try adding the *return_url* to the GET parameters that will prevent caching:
https://github.com/nexcess/magento-turpentine/wiki/Configuration#parameter-based-caching

**Comment by loginid** [comment]
Hi there! Thanks for getting back to me.

I've done as you suggested:

![turpentine-config-capture](https://cloud.githubusercontent.com/assets/12857044/8151035/08791c46-1345-11e5-9e4b-c0aaad1e2204.JPG)

Then I have saved the new vcl file
Uploaded it to my etc/varnish 
Restarted varnish.

After restarting I checked that varnish was running properly (netstat method).
Then checked the varnish headers on a page request, but the x-varnish header no longer appeared.
So I reverted back to the original config.

Any reason why you think that might be happening?

Thanks!!

**Comment by aricwatson** [comment]
> After restarting I checked that varnish was running properly (netstat method) - and it was.
> Then checked the varnish headers on a page request, but the x-varnish header no longer appeared.

Just so it's clear - what URLs was Varnish not working on? The changes you set up should make it not work on the *applycoupon* URL, for example. 

> So I reverted back to the original config and it's working again (in the original config without the changes).

But the coupon is back, correct?

**Comment by loginid** [comment]
Hi aricwatson.. thanks for getting back to me. Sorry about the delay.
Just wanted to let you know that I'm using a workaround for this behaviour so it seems to be working just fine now.
