### ISSUE TITLE
Set disclaimer cookie

### ISSUE THREAD

**Issue by gallart** [nexcess/magento-turpentine#800]
Hello Turpentine,

In France, with "Hamon law", we need to tell customers about cookie privacy, collection, etc.

That's the reason why my Magento code needs to check for cookie existence and create it, if needed. Therefore, Turpentine cookie policy does not allow me to do so.

Here is the code (app/design/frontend/mytemplate/default/template/page/html/cookie.phtml)

```
<?php

$visu=Mage::getSingleton('core/cookie')->get('popup_loi');

// Si le cookie n'existe pas
if (!$visu){

// Création du cookie et affichage du message
Mage::dispatchEvent('create_cookie_loi');
?>
<div id="cookieLoi" style="">

<span>En poursuivant votre navigation sur ce site, vous acceptez l'utilisation de cookies, ces derniers permettent le bon fonctionnement de nos services. </span>
<a href="/cookie.pdf" target="_blank">En savoir plus</a>
<a id="cookieChoice" href="#" onclick="jQuery('#cookieLoi').css('display','none');return false;" style="margin-left: 10px;">Fermer</a>
</div>
<?php } ?>
```

How should I configure Turpentine to let this cookie being transmitted to browser?

Thanks,

**Comment by t3ddftw** [comment]
I had a similar issue that I couldn't solve properly within the confines of Varnish. My fix was to handle the cookie/splash page client side with jQuery cookie.

**Comment by aricwatson** [comment]
I suspect that your coupon block is part of an ESI request and doesn't have access to the cookies. I'd suggest use the ajax method for that block - which is essentially the same as t3ddftw's method.

**Comment by magenx** [comment]
use jQuery or javascript to read/set cookie...

**Comment by miguelbalparda** [comment]
Using JS is the best approach for your issue. Check https://github.com/Creare/EUCookieLawBanner, it seems to be exactly what you need. This can also be achieved with the native prototype functions to create/read cookies instead of using PHP.
