### ISSUE TITLE
Magento 1.9.1 - [Recently Viewed Products] side block is being cached!

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#801]
Testing version installed from scratch, no other extensions. Magento CE 1.9.1 out of box, Varnish 3, Turpentine.

[Recently Viewed Products] side block is being cached! I tried to set up ESI policies for it but it is not working at all.

Please take a look to see what is going wrong. If you need a testing version just let me know. Thank you.

**Comment by aricwatson** [comment]
I believe this is due to a misconfiguration, I could not replicate using fresh install of 1.9.1 and Turpentine. Closing until further information provided.

**Comment by aricwatson** [comment]
Can replicate on 1.9.1

**Comment by aricwatson** [comment]
Just commited a fix for this to the *devel* branch if you'd like to test...

**Comment by ADDISON74** [comment]
I appreciate for your technical support. For sure I will test it. I will come back to you with more information related to the other issues I opened. All are based on 1.9.1 RWD default theme.

**Comment by ADDISON74** [comment]
I just installed the dev version and I can confirm now the block product.viewed is working as expected. I can see ESI START and ESI END tags inside the source code. Still testing these days.

BTW was it easy to fix?

**Comment by aricwatson** [comment]
It was a little hard to track down. There was an ESI policy set up for it by default, however there was a layout xml loading order issue that meant it was getting overridden

**Comment by ADDISON74** [comment]
I would like to ask you if it is a correct behavior of this block as follows:

You already visited 3 products. Now go to a new category you will see those 3 products listed inside "Recently Viewed Products". Go visiting a product from this category. Now use GO BACK one page from browser. You will get the parent category for the visited product. Inside "Recently Viewed Products" there are the same 3 products even you visited another one. 

1) If you visit other pages and come back to this category you will get the same 3 products.
2) If you Refresh the page you will get now 4 products, which is correct. 

Could this be considered an issue and it needs a fix?

**Comment by ADDISON74** [comment]
I come to you with an issue related to what I mentioned in my previous post. Using the links in Magento frontend it is showing correctly the page content. Let's say you visited a product page then you select parent category of the product clicking on parent category link. You will see in Recently Viewed Products side block the product you just visited. But when you use Back or Forward buttons in browser the page content won't refresh, Recently Viewed Products is unchanged. 

On tablets for example many users are using back button. This is not good, because the page content will not be refreshed using it. Do you have any idea how can I change the things in Magento or Turpentine in order to prevent Back/Forward buttons issue I told you about? It is a matter of adding some headers?

Thank you!

**Comment by ADDISON74** [comment]
Bump!

**Comment by aricwatson** [comment]
We've merged the fix for the recently compared and recently viewed blocks. I haven't looked yet, but I suspect that the recently added block issue you mentioned is related, so once I get a chance to investigate it'll hopefully be a quick fix!

**Comment by ADDISON74** [comment]
No problem. I still keeping an eye on testing. If you fix [Clear All] behavior these two issues are closed forever.
