### ISSUE TITLE
Magento 1.9.1 - [Popular Tags] side block is being cached!

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#802]
Testing version installed from scratch, no other extensions. Magento CE 1.9.1 out of box, Varnish 3, Turpentine.

[Popular Tags] side block is being cached! I tried to set up ESI policy for it but it is not working.

Please take a look to see what is going wrong. If you need a testing version just let me know. Thank you.

**Comment by aricwatson** [comment]
There is no specific cache policy set for this block, so it will use the default page ttl set under *Configuration -> Turpentine -> Caching Options* (3600 seconds by default). If you need a specific policy for this, you should be able to set up a custom policy in your themes local.xml policy.

**Comment by ADDISON74** [comment]
I will help you asap with more information.
