### ISSUE TITLE
Magento 1.9.1 - [Recently Added Products] side block is being cached!

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#804]
Testing version installed from scratch, no other extensions. Magento CE 1.9.1 out of box, Varnish 3, Turpentine.

[Recently Added Products] side block is being cached! I tried to set up ESI policies for it but it is not working at all.

Please take a look to see what is going wrong. If you need a testing version just let me know. Thank you.

**Comment by magenx** [comment]
you need to understand the logic behind this, how [Recently Added Products] actually works.

**Comment by aricwatson** [comment]
That's exactly what I was going to suggest - turn on debugging and block logging and first make sure the ESI requests for those blocks are being made.

**Comment by ADDISON74** [comment]
I am struggling with this issue same like Compare. I tried some rules but it didn't work. I guess this is a bug too like the one you know related to Compare side block.

**Comment by aricwatson** [comment]
I think it probably is related, will look closer.

**Comment by ADDISON74** [comment]
For sure it is related. Activating "Template Hints" I found information about this side block, maybe it helps:

[My Cart]
Mage_Checkout_Block_Cart_Sidebar
frontend/base/default/template/checkout/cart/sidebar.phtml

[Recently Added Item(s)]
Mage_Checkout_Block_Item_Renderer
frontend/base/default/template/checkout/cart/sidebar.phtml

**Comment by aricwatson** [comment]
Hi @ADDISON74 - any chance you can give me exact steps to replicate what you're seeing?

**Comment by ADDISON74** [comment]
Please allow me to reproduce again this issue. As I remember Magento version was 1.9 with the default template from 1.7. 

RWD theme is not showing this side block by default. But I will create two testing environments, both based on CE 1.9.2.0, using RWD and the one from 1.7 (see images above). When I added products to cart, in header I could see the cart block updating correctly, but the side block was cached.

**Comment by ADDISON74** [comment]
I will close this issue for opening other one with more details and extended.
