### ISSUE TITLE
Magento 1.9.1 - [My Cart] side block is being cached!

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#805]
Testing version installed from scratch, no other extensions. Magento CE 1.9.1 out of box, Varnish 3, Turpentine.

[My Cart] side block is being cached! I tried to set up ESI policies for it but it is not working at all.

Please take a look to see what is going wrong. If you need a testing version just let me know. Thank you.

PS - If Magento 1.9 changed how the side blocks work (Upsells, Recommended, ...) please let us know.

**Comment by aricwatson** [comment]
I believe this is due to a misconfiguration, I could not replicate using fresh install of 1.9.1 and Turpentine. Closing until further information provided.

**Comment by ADDISON74** [comment]
I will help you asap with more information.
