### ISSUE TITLE
Footer Links RWD design

### ISSUE THREAD

**Issue by ceceghini** [nexcess/magento-turpentine#807]
I installed turpentine extension in my magento istance with rwd template and multistore that share some catalog.

Everything works except the block relative to the links in the footer.

This links is rendered two times: es:

<ul><li>link1</li><li>link2</li><li>link1</li><li>link2</li></ul>

This is the part of page.xml of my rwd design:

<block type="page/template_links" name="footer_links" as="footer_links" template="page/template/links.phtml">
                    <action method="setTitle"><title>Servizio clienti</title></action>
</block>

<reference name="footer_links2">
            		<action method="addLink" translate="label title" module="catalog"><label>Trova Prezzi</label><url>http://www.trovaprezzi.it</url><title>Trova Prezzi</title></action>
            		<action method="addLink" translate="label title" module="catalog"><label>ShoppyDoo</label><url>http://www.shoppydoo.it</url><title>ShoppyDoo</title></action>
            		<action method="addLink" translate="label title" module="catalog"><label>Verdestampa</label><url>http://www.verdestampa.it</url><title>Verdestampa</title></action>
            		<action method="addLink" translate="label title" module="catalog"><label>ShopMania</label><url>http://www.shopmania.it</url><title>ShopMania</title></action>
            	</reference>

**Comment by aricwatson** [comment]
Have you tried turning on block logging and debugging and checking system.log to see what's reported for that block?

**Comment by ceceghini** [comment]
I have tried. 

The problem is that the block is not duplicated in whole (<div><ul>...</ul></div>)

Are duplicated only tags <li>. It looks like part of the XML that adds the link (<AddLink>) is processed twice

**Comment by miguelbalparda** [comment]
@ceceghini I'm unable to reproduce the issue with a fresh Magento 1.9.1.0 with sample data and RWD. Is  Blocks HTML output  enabled in System - Cache managment?
