### ISSUE TITLE
Prepending HTTPS address onto HTTP root

### ISSUE THREAD

**Issue by danhanly** [nexcess/magento-turpentine#808]
I've enabled HTTPS across my full site. Now, I'm getting malformed URLs with each ESI block that gets loaded. Check the below URL:

http://mysite.co.uk/https:/mysite.co.uk/turpentine/esi/getBlock/method/esi/access/private/ttl/86400/hmac/0bba22107283b1c40305e7ebe49a3cb82516079fd84e7ee866a65409aa871f18/data/9U7M6H1qFKpNp0Cc8Sp1V-mxKKsA0yK7Gr34ctdQa3zReD

Obviously, the correct address would be: 

https://mysite.co.uk/turpentine/esi/getBlock/method/esi/access/private/ttl/86400/hmac/0bba22107283b1c40305e7ebe49a3cb82516079fd84e7ee866a65409aa871f18/data/9U7M6H1qFKpNp0Cc8Sp1V-mxKKsA0yK7Gr34ctdQa3zReD

What's causing this?

**Comment by aricwatson** [comment]
Hi Dan -

You're no doubt aware - but just in case I wanted to make sure you know that Varnish doesn't terminate SSL, so you need to use something like pound or nginx to handle SSL and allow an all https site. The [wiki page](https://github.com/nexcess/magento-turpentine/wiki/SSL_Support) has more info.

There's a few different settings that need to be changed, and I suspect you've missed one. For more info,  check out the wiki, this issue (https://github.com/nexcess/magento-turpentine/issues/675) - this PR may also be useful (https://github.com/nexcess/magento-turpentine/pull/524) - I haven't yet had a chance to test and merge it.

**Comment by danhanly** [comment]
@aricwatson

Cheers for your help. It seems that upgrading our version of Varnish may solve the issue.
The following, which describes our exact circumstances, has been resolved in 3.0.5

https://www.varnish-cache.org/trac/ticket/1333

**Comment by miguelbalparda** [comment]
@danhanly you might want to check #834 and https://github.com/ichalov/magento-turpentine/commit/ef3738f806c2d9ffea6621dd63213f7859c286d3

**Comment by miguelbalparda** [comment]
Closing for lack of response.
