### ISSUE TITLE
Cache Hits & Misses

### ISSUE THREAD

**Issue by loginid** [nexcess/magento-turpentine#810]
Hi all,

Again - thanks for all the hard work with this contrib.

I've just got a question around what we should be seeing as standard hits and misses for a standard install?
I'm running magento 1.9.0.1 and deployed the standard VCL generated by turpentine.. but I'm seeing a larger number of cache misses than hits (as reported by munin).

Is there any kind of standard of cache hits / misses that I should be seeing? Do you think I should be seeing more hits then misses? 

Thanks for the help!!

**Comment by aricwatson** [comment]
This will vary quite a bit depending on how you've set up your ESI policies, as well as if you get a lot of traffic on portions of the site that are bypassing varnish - but I think it should be quite a bit higher. The [normalization options](https://github.com/nexcess/magento-turpentine/wiki/Configuration#normalization-options) might be worth testing as well.

**Comment by loginid** [comment]
thanks for your reply aricwatson, I'm just using the standard ESI policy which comes out of the box with turpentine. Here's how my varnishstat looks ( 2 days running) : 

       61924         0.00         0.38 client_conn - Client connections accepted
       70602         0.00         0.43 client_req - Client requests received
       89873         0.00         0.55 cache_hit - Cache hits
         684         0.00         0.00 cache_hitpass - Cache hits for pass
      368237         0.00         2.25 cache_miss - Cache misses
       12399         0.00         0.08 backend_conn - Backend conn. success
      357556         0.00         2.18 backend_reuse - Backend conn. reuses
        9596         0.00         0.06 backend_toolate - Backend conn. was closed
      367340         0.00         2.24 backend_recycle - Backend conn. recycles


Hits look a little low to me - what do you think?
My site is just a standard magento site really without too much configuration. 
So users are mainly going to front page and product pages, then off to cart, etc. But mainly front & prod. So I would really expect a higher hit rate?

For normalisation I have : 
 Normalize Encoding  = TRUE
 Normalize User-Agent = FALSE
  Normalize Host = FALSE (but I've got a multistore site, so probably don't want to touch this).

**Comment by ichalov** [comment]
Loginid, What is the 'Default TTL' setting? Do you use any cache warm up scripts? I use long TTL (24 hours) and a tight warm up script that visits all category and product pages every hour. It can produce the varnish cache hit rate over 99% in some days (but, frankly, most of these hits are made by warm up script itself).

**Comment by aricwatson** [comment]
We see hit rates of 90% or higher on some clients - and some as low as 30%. So, it really depends on a ton of factors - but it is possible to get very high hitrates. It takes a a lot of debugging and testing to figure out what will work well for you. 

One other question - have you added a lot of blacklisted urls in the configuration, so that a large amount of your traffic might be bypassing varnish that way?

**Comment by aricwatson** [comment]
Closing, hopefully the question is answered :)
