### ISSUE TITLE
Product name change only updated on product page, not category pages

### ISSUE THREAD

**Issue by phpdave11** [nexcess/magento-turpentine#812]
When making an update to a product, for example changing the product name, the product page itself gets banned and after the first page visit, the page is cached again.  That works fine.

However, other pages still have the old product name.  For example, category pages still have the old product name, as well as the "related products" section on other product pages.

Should this plugin be banning other pages if they reference a product that has changed?  I'm planning on modifying the Nexcessnet_Turpentine_Model_Observer_Ban::banProductPageCache() function so that related pages are also banned.

**Comment by aricwatson** [comment]
> Should this plugin be banning other pages if they reference a product that has changed?

It was decided not to implement this, because of potential performance problems. See https://github.com/nexcess/magento-turpentine/issues/78 for more information.

Something to watch for if you do modify it.

**Comment by miguelbalparda** [comment]
@phpdave11 check #527, from there you can manually flush any page.

**Comment by miguelbalparda** [comment]
Closing for lack of response.
