### ISSUE TITLE
Apply Varnish Config Throws 404

### ISSUE THREAD

**Issue by nflint** [nexcess/magento-turpentine#821]
Tested on clean Mage install. 1.9.1.1
Tested Turpentine version .0.6.1 and works fine. 
 Commercebug generated this error: `The controller name [varnish_management] matches the following file, but this file does not exist."
"/home/xxxxxx/domains/dev.xxxxxx.com/app/code/core/Mage/Adminhtml/controllers/Varnish/ManagementController.php`

Latest version is completely unusable.

**Comment by miguelbalparda** [comment]
@nflint I think I found the case of the issue. I pushed my fix to devel and I'm waiting the build to finish to merge with master, it seems the issue was introduced by #817.

**Comment by nflint** [comment]
@miguelbalparda Thanks. I suspected that might be the issue but did not have time to verify. I will pull the master after the merge and let you know if I notice any more issues.

**Comment by miguelbalparda** [comment]
It is merged @nflint, I'll close the issue now.
