### ISSUE TITLE
Captcha...

### ISSUE THREAD

**Issue by gewaechshaus** [nexcess/magento-turpentine#822]
Hey there,

is there anybody out there running the native captcha and turpentine in full effect?

Best regards,
Jan

**Comment by aricwatson** [comment]
Checking it out... what issues have you had?

**Comment by aricwatson** [comment]
@gewaechshaus I was unable to replicate this issue - I turned on the native captcha for the admin and it worked fine. Can you give us any other details?

**Comment by gewaechshaus** [comment]
Hi @aricwatson,

i'll have to look what was bugging exactly... Give some hours.

**Comment by gewaechshaus** [comment]
@aricwatson - sorry for the delay... I had a look over the captcha related thing. We had problems declaring the ESI to work for the captcha block. As a result it's cached generaly. (we're running the review form as a tab in catalog_product_view).

Our modul related configuration (doesn't work)

     <catalog_product_view>
        <reference name="head">
            <action method="addJs"><file>mage/captcha.js</file></action>
        </reference>
        <reference name="product.review.form"> 
           <block type="core/text_list" name="form.captcha">
                <block type="captcha/captcha" name="captcha">
                    <action method="setFormId"><formId>review_form</formId></action>
                    <action method="setImgWidth"><width>350</width></action>
                    <action method="setImgHeight"><width>50</width></action>
                </block>
                <action method="setEsiOptions">
                  <params>
                      <access>private</access>
                      <ttl>0</ttl>
                  </params>
                </action> 
            </block>
             
        </reference> 
    </catalog_product_view>


A turpentine_esi.xml test (doesn't work)

  
         
         
        <reference name="form.captcha">
            <action method="setEsiOptions">
               <params>
                    <access>private</access>
                    <ttl>0</ttl>
                </params>
            </action>    
        </reference>

I will also take a quick look into the related core controllers to locate what's going on related to sessions.

**Comment by aricwatson** [comment]
@gewaechshaus are you using an extension? I don't believe there's a captcha on the review form in vanilla magento...

If you turn on the debug logs are you seeing anything?

**Comment by gewaechshaus** [comment]
@aricwatson - yes, exactly. We're extending the review form in a custom, self-written extension with the native captcha. I will have to check the logs.

**Comment by aricwatson** [comment]
@gewaechshaus any luck getting it to work? Anything in the logs?

**Comment by gewaechshaus** [comment]
@aricwatson - still working at another lot :) It's working static(no ESI), that's ok (as long as nobody from the wrong side gets it), but i'll investigate it till the next days.

**Comment by aricwatson** [comment]
Closing for now, but if you need more help we'll re-open!
