### ISSUE TITLE
Initial Page Load

### ISSUE THREAD

**Issue by adamrandazzo** [nexcess/magento-turpentine#827]
Hi Guys - I am having an issue that I haven't quite seen in the open issues (it also seems to be almost the opposite of #806 where there were too many sessions being created.

I am using Magento 1.9.1, Varnish 3.X, and the latest  release of turpentine, as of last week. My stack is a little unusual as I am doing the following: 

`Load Balancer w/SSL offload (Rackspace Cloud bases) -> Varnish -> nginx -> php-fpm`

My issue is that when a person first lands on the site (doesn't matter if its the homepage, or something else), if they try to use the "Add to Cart" button, it doesn't work. It loads the subsequent page and there is no resulting alert message that it was added to cart. Additionally, the item is never actually added to the cart. 

Now, assuming that a person lands on the site, and visits a second page and then adds the item to their cart, it works PERFECTLY. I have made all of the modifications to the startup parameters for 1.91 found in the FAQ. This also isn't my first project using this plugin. I have had success with Turpentine on an older version of Magento / Varnish / Turpentine. I have never had any real problems with it before, and have never seen this issue. I believe that it has to be some sort of session/cookie issue and have tried checking/setting cookies and reloading the page in the Mage index.php file, but that didn't workout either.

Can anyone reproduce it? I have a capture of my headers from the first page load, where the Add to Cart fails. I have checked 

Here is a capture of my response from the server with the cookies
![screen shot 2015-06-25 at 11 18 14 pm](https://cloud.githubusercontent.com/assets/8340768/8370111/936c1322-1b91-11e5-8f01-4215ab0d93e3.png)

I really appreciate your work on the project, and the community using it.

**Comment by aricwatson** [comment]
This sounds like it's almost certainly related to https://github.com/nexcess/magento-turpentine/issues/345 which we're still working on. There is a working fix you can implement but it will disable varnish on the first page load for al new visitors: https://github.com/nexcess/magento-turpentine/issues/345#issuecomment-106096817

**Comment by adamrandazzo** [comment]
Thank you! Sorry I missed that original issue. I made the changes to my vcl template as recommended in #345, and its all working correctly now. The penalty is relatively minor in comparison to having to use a different plugin. Thanks again!
