### ISSUE TITLE
Customers unable to login randomly,  empty cart after login, add to cart problem, duplicated frontend cookie

### ISSUE THREAD

**Issue by mabigo** [nexcess/magento-turpentine#831]
For many months our team tried to find the reason why some customers became empty cart after login attempt. This error could not be reproduced, and therefore hard to debug. Until one day we found that a second "frontend" cookie appears when user tries to access the shop with non-www uri (our base url is configured with www). No big deal (i thought), but as soon as this user tries to login magento fails on creating session and the guest session getting destroyed together with it's cart items! The first fix i could think of was creating a redirect in vcl recv subroutine from non-www to www, but what if some user will configure non-www as base_url? this could lead to redirect loop or something. Then i remembered of trying to install jenkins on our dev server, after i done this we had to access it with apache port because varnish always cached everything according to turpentine vcl rules, just like for any other host on same server, so then i decided to fix both problems by customizing vcl and adding a regex with all hosts from base url's configured in magento.

    
    public function getAllowedHostsRegex() {
    	$hosts = array();
    	foreach( Mage::app()->getStores() as $store ) {
    		$hosts[] = parse_url( $store->getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB , false ), PHP_URL_HOST );
    	}
    	 
    	$hosts = array_values(array_unique( $hosts ));
    	 
    	$pattern = '('.implode('|', $hosts).')';
    	return $pattern;
    }
    

This solution would give varnish the idea of what it has to cache and what not. By default varnish created a frontend cookie for each host regardless of what was behind of it. Adding a "pass" for all non magento url's will let magento decide what to do (in our case redirect to www and let varnish create the frontend cookie)

    
        # if host is not allowed in magento pass to backend
        if (req.url !~ "{{allowed_hosts_regex}}") {
        	return (pass);
        }
    
refs #84, #345, #435, #477, #690, #774

**Comment by mabigo** [comment]
PR #832

**Comment by Petce** [comment]
This sounds like the symptoms for issue #829. Please give it a read.

**Comment by mabigo** [comment]
@Petce yes is have read it, we talked yesterday in magento irc channel and i recommended you to drop your custom vcl changes and would now recommend to apply this commit changes and see if it helps.

**Comment by ichalov** [comment]
Magento itself has this setting: System / Configuration / General / Web / Session Cookie Management / Cookie Domain . You may try to put your domain name with www in it and somehow ensure non-www URLs are redirected to www (I believe turpentine installation does it if 'Normalized Host Target' setting is set to www domain, but I'm not sure). I had exactly the same problem as you, and I was able to solve it by changing configuration parameters, no VCL changes were required.

**Comment by mabigo** [comment]
@ichalov changing configuration in magento will not help because varnish is always in front of it, before magento even tries to create a session cookie it is already done by generate_session subroutine in varnish.

about normalized host according to turpentine wiki:
> 
> **Normalize Host**: Enabling this setting makes Varnish rewrite the Host header of a request to a 
> specific domain. This can be helpful to prevent duplicate entries in the cache (for 
> http://example.com/somepage and http://www.example.com/somepage for example) by making 
> the backend see all requests as coming to a specific domain. Note that this setting is likely to 
> break many/most multi-store setups so it's use should be carefully considered.
>

i have a lot of multi-store setups i dont want to break. 

As i wrote in PR:
> I am sure some people could implement this even better. But i just wanted to give an idea of how
>  to understand, reproduce and fix this bug.

**Comment by mabigo** [comment]
@ichalov 
looking deeper into code of turpentine's configurator you may see how normalized host will break any multi-store.

    
    /**
     * Get the hostname for host normalization from Magento's base URL
     *
     * @return string
     */
    protected function _getNormalizeHostTarget() {
        $configHost = trim( Mage::getStoreConfig(
            'turpentine_vcl/normalization/host_target' ) );
        if( $configHost ) {
            return $configHost;
        } else {
            $baseUrl = parse_url( Mage::getBaseUrl() );
            if( isset( $baseUrl['port'] ) ) {
                return sprintf( '%s:%d', $baseUrl['host'], $baseUrl['port'] );
            } else {
                return $baseUrl['host'];
            }
        }
    }
    

in vcl template we can see another confirmation
    
set req.http.Host = "{{normalize_host_target}}";
    

conclusion: normalize host is just not multi-store capable

**Comment by ichalov** [comment]
@mabigo , Sorry, I didn't realize this topic is supposed to match pull request and hence doesn't need an answer. Yes, I understand multi-store support would require VCL changes.

**Comment by mabigo** [comment]
@ichalov actually your answer is really helpful. Because fixing normalize_host to be multi-store capable may be a better idea then adding another method and change vcl template. 
{{normalize_host}} is already in the perfect place inside vcl_recv.

However it was not only about code design problem. But because of this **HUGE BADASS BUG** causing some store customers to giveup on trying to order anything, because the cart is getting empty and login is not possible at all. Who knows where this error has it roots, but it is caused by the second frontend cookie.

**Comment by miguelbalparda** [comment]
Thank you for the help @mabigo! I will merge this with devel and ask the issues OP to test it from there and once we have some more info and if everything works I will merge it with master.

**Comment by Petce** [comment]
@mabigo @miguelbalparda, How does Varnish and Turpentine go about creating a new session for a first time visitor (i.e. someone with no cookies at all).

I can see that the Turpentine VCL creates a frontend cookie for the user but how does that become a session in Magento? At some stage Magento will see that cookie and say "This is not in my session data!" And then that users session will become invalidated.

**Comment by Petce** [comment]
While this fix by @mabigo allows the auto-genereated VCL to handle multi-domain magento installations, it is not a fix to the very serious issue that is #345.
