### ISSUE TITLE
customer_logout event not flushing ESI Block cache

### ISSUE THREAD

**Issue by matrixbegins** [nexcess/magento-turpentine#833]
I saw that in ```turpentine_esi.xml``` the ESI caching policy is written like 
```
 <reference name="header">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <flush_events>
                        <wishlist_item_save_after/>
                        <wishlist_item_delete_after/>
                        <sales_quote_save_after/>
                    </flush_events>
                </params>
            </action>
        </reference>
```
However, the menu is also part of header. So every  ```login/logout/quotesave``` It'll keep generating the menu. Which is a performance hit. So in order to prevent that I used ```top.links``` instead of header.
```
<reference name="my_top_links">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <flush_events>
                        <wishlist_item_save_after/>
                        <wishlist_item_delete_after/>
                        <sales_quote_save_after/>
                        <customer_login/>
                        <customer_logout/>
                    </flush_events>
                </params>
            </action>
        </reference>
```
However I found its working for all events except ```  <customer_logout/>```. top links cache doesn't get flushed on customer logout event. 
Is this configuration correct ? Or there is another way around it ?

**Comment by matrixbegins** [comment]
Sometimes we are just facing issues of invalid form_key, e.g. delete from cart.

**Comment by miguelbalparda** [comment]
Have you tried refreshing your cache? Specifically the Configuration cache. Are you sure your reference name is the correct one and matches your theme reference name?

**Comment by matrixbegins** [comment]
@miguelbalparda Yes I tried clearing cache few dozen times. FPC as well as Magento cache. And yes reference is correct too. It was fine on staging. 
I see now two primary issues:

 * two ```frontend``` cookies in browser one has domain ```.mywebsite.net``` one has ```.www.mywebsite.net``` 

* Moreover ```X-Varnish-Set-Cookie``` has right info, see headers below

``` 
Set-Cookie: frontend=4e52b84bc6864686859e355c0ca45bc8; expires=Thu, 02-Jul-2015 10:37:51 UTC; path=/; domain=www.mywebsite.net; httponly 

X-Varnish-Set-Cookie: frontend=59ebfd27d8e148e180585a8d66c3e246; expires=Sat, 11-Jul-2015 06:36:52 GMT; Max-Age=846000; path
=/; domain=.mywebsite.net; httponly
```

See domain, and cookie life time. The cookie life time in ```X-Varnish-Set-Cookie``` is correct. This lifetime is configured in Sysconfig. If I bypass varnish I get correct cookie domain and lifetime.

**Comment by miguelbalparda** [comment]
In devel branch there are new fixes and one includes the issue you are mentioning about the cookie. If you have some time take a look there, it might be the fix you need.

**Comment by miguelbalparda** [comment]
See #832 for more references.

**Comment by miguelbalparda** [comment]
BTW, we experienced a lot f issues with FPC activated along with Turpentine, I would suggest you to disable it and test some more.

**Comment by matrixbegins** [comment]
@miguelbalparda So you mean try alternative to turpentine ? Honestly I find old school approaches better. Just have a placeholder and fill hole with ajax request. Saves a lot of trouble.

**Comment by miguelbalparda** [comment]
@matrixbegins no, what I said was to disable FPC and test Turpentine alone.

**Comment by miguelbalparda** [comment]
Closing for lack of response.
