### ISSUE TITLE
Redis session cache

### ISSUE THREAD

**Issue by donnie-darko** [nexcess/magento-turpentine#84]
Hi,
I would like to use Cm_Cache_Backend_Redis and Cm_RedisSession extensions with a system that have Turpentine installed, too.
On my dev server the Cm_Cache_Backend_Redis and turpentine work nice together. But after I enable Cm_RedisSession it seem that turpentine can't instert any session into redis server. Can you confirm this? Is there any workaround?

**Comment by miguelbalparda** [comment]
It seems #832 has a fix for this issue. would you mind giving it a try? It is on the devel branch until further testing.
