### ISSUE TITLE
Price Block per customer

### ISSUE THREAD

**Issue by stamm-media** [nexcess/magento-turpentine#841]
We have a varnish-issue of product-listing with different prices and taxes.
We have a shop with customers, who have special prices and taxes of products on depends of the delivery country.

We want to solve our issue like jOney3 
https://github.com/nexcess/magento-turpentine/issues/226

What we have do right now:

1.) setup the price into block.
```
<block type="catalog/product_list" name="custom_price" template="catalog/product/list/custom-price.phtml">
```
2.) defined the esi-block in my catalog.xml
```
<catalog_category_default translate="label">

<reference name="custom_price">
	<action method="setEsiOptions">
		<params>
			<method>ajax</method>
			<access>private</access>
		</params>
	</action>
</reference>
```

3.) Call the block "custom_price" in catalog/product/list.phtml

4.) We modified our ESI Block and defined the registry_keys
```
<reference name="custom_price">
	<action method="setEsiOptions">
		<params>
			<method>ajax</method>
			<access>private</access>
			<registry_keys>
				<current_product>
			</registry_keys>
		</params>
	</action>
</reference>
```
We are getting always an error, cause the block "custom_price" doesn\'t have or find the object of product.
Our question is, how we can pass the product ID into the block custom_price?
Or if someone has another solution, how we can change the price?

Thanks alot!
Cheers!

**Comment by sofib** [comment]
Have you found a solution so far?

**Comment by stamm-media** [comment]
Yes, i used jQuery for loading price and tax

**Comment by tushardatar** [comment]
@stamm-media - Have you find any way to get product id into the block custom_price? or can you share what you have used to get dynamic price ? 



Thanks

**Comment by stamm-media** [comment]
we used jQuery for loading dynamic price
