### ISSUE TITLE
Generating Form Key for Review on Product Page

### ISSUE THREAD

**Issue by syoumans** [nexcess/magento-turpentine#842]
This is more of a support question than a bug I think: Running EE 1.14.2 with Varnish/Turpentine, we've added the review form to our product page directly. Varnish seems to cache it globally "out of the box" and the form doesn't change based on the logged-in/logged-out state of the user. 

When we punch a hole for the form, the form ID isn't on the form action URL, and the form_key input field is missing altogether. Here's our layout XML change:
```xml
<block type="review/form" name="product.review.form" as="review_form">
    <action method="setEsiOptions">
        <params>
            <access>private</access>
        </params>
    </action>
</block>
```
Here's the form as it should appear:
```html
<form action="http://www.somedomain.com/review/product/post/id/6364/" method="post" id="review-form">
    <input name="form_key" type="hidden" value="aaaaaformkeyaaaaaa" />
   ...
</form>
```
And here's the form as it appears after hole-punching:
```html
And here's the form as it should appear:
```html
<form action="http://www.somedomain.com/review/product/post/" method="post" id="review-form">
     <!-- notice no form key input field -->
     ...
</form>
```
Without the form_key and form ID, the form doesn't submit correctly. Is there a straightforward way to have the review form key generated in this instance?

**Comment by miguelbalparda** [comment]
@syoumans can you try the latest version from devel instead of the one in the master branch?

**Comment by syoumans** [comment]
@miguelbalparda , thanks for your quick reply and great suggestion. I've downloaded and installed the devel branch (0.6.3). With the above setEsiOptions command, the review form on our product page continues to miss a post ID in the action attribute and the form_key input field.

**Comment by miguelbalparda** [comment]
Have you tried using public instead of private? I think this should not be private since this can be shared across users. Also, are you sure you applied the vcl correctly? Try applying it from the admin, under System - Cache management.

**Comment by syoumans** [comment]
Yes, we've tried both. We have our Magento review setting set to "only let logged in users leave reviews." The problem we were originally trying to solve was to have the review form display correctly depending on whether or not the current user is logged in or logged out. With the ESI option set to public (or not specified at all), the first cached view of the review block is what everyone sees: If the user isn't logged in, then everyone sees the "Only registered users can write reviews. Please, log in or register" text; if the user is logged in, then everyone can see the review form even if they are logged out.

**Comment by syoumans** [comment]
As for VCL, I haven't touched that config in ages–we've been running live with Varnish/Turpentine for months now. I can look at it, though if it seems relevant.

**Comment by miguelbalparda** [comment]
Any luck on this @syoumans?

**Comment by syoumans** [comment]
@miguelbalparda , thank you so much for checking back in. We haven't taken the time to look into this and have decided to live with the problem for now. We're also open to the possibility that the next update to Turpentine may correct whatever issue we're encountering ;-)

**Comment by yannschepens** [comment]
A workaround is to declare product review form this way : 
```
             <block type="review/form" name="product.review.form" as="review_form">
                   <action method="setEsiOptions">
                        <params>
                            <access>private</access>
                            <scope>page</scope>
                            <registry_keys>
                                <current_product/>
                            </registry_keys>
                        </params>
                    </action>
                    <block name="formkey" type="core/template" template="core/formkey.phtml" />
					<block type="page/html_wrapper" name="product.review.form.fields.before" as="form_fields_before" translate="label">
						<label>Review Form Fields Before</label>
						<action method="setMayBeInvisible"><value>1</value></action>
					</block>
				</block>
```

Be careful, you must add the formkey block (the one used without turpentine is the default one, so you need to add a block).

But you will have another problem, the form action url will miss the product ID. I have not this problem yet.

**Comment by yannschepens** [comment]
Workaround : continuation and end

With the 
```
                            <registry_keys>
                                <current_product/>
                            </registry_keys>
```

You can get the product into Mage::registry('current_product').

So you can override rewrite/form block to use it into getAction.

I tested it, and it works.

Have a good day everybody.

**Comment by aricwatson** [comment]
@syoumans have you tried @yannschepens fix to see if it helps in your particular situation?

**Comment by syoumans** [comment]
@aricwatson , no, not yet. I put a story in our backlog to try, but it hasn't been prioritized yet. Much appreciation to @yannschepens for following through on the suggestion.

**Comment by aricwatson** [comment]
Closing for now, but let us know if you're still having problems and we'll certainly reopen!

**Comment by syoumans** [comment]
Totally understand. Will do. Thanks so much for your support here, and looking forward to future updates.
