### ISSUE TITLE
Caching Product List with access = customer_group

### ISSUE THREAD

**Issue by andreaseba89** [nexcess/magento-turpentine#852]
I followed the instruction to added customer_group access option to cache (#758)  and i think it's working because i see a new cookie called "customer_group" when i log in. Now i would implement a esi cache policy for the product list page for customer group; so i put this code into "turpentine_esi.xml":

```xml
<catalog_category_layered>
        <reference name="product_list">
            <action method="setEsiOptions">
                <params>
                    <access>customer_group</access>
                </params>
            </action>
        </reference>
    </catalog_category_layered>

<catalog_category_default>
        <reference name="product_list">
            <action method="setEsiOptions">
                <params>
                    <access>customer_group</access>
                </params>
            </action>
        </reference>
    </catalog_category_default>
```

The problem is that now in each category I always see all the products in the whole catalog. Is there something wrong in my code?

Thanks

**Comment by aricwatson** [comment]
Hi -

Can you give us steps to replicate this, ideally using a default theme?

**Comment by aricwatson** [comment]
Closing for lack of feedback.

**Comment by IhorVansach** [comment]
try this settings
            <action method="setEsiOptions">
                <params>
                    <access>customer_group</access>
                    <scope>page</scope>
                    <registry_keys>
                        <category/>
                        <current_category/>
                        <current_layer/>
                    </registry_keys>
                </params>
            </action>
