### ISSUE TITLE
Very slow product grid load times on 1st hit (CE 1.9.1 RWD)

### ISSUE THREAD

**Issue by vbuck** [nexcess/magento-turpentine#853]
With an essentially stock RWD CE 1.9.1.0 theme I'm seeing that on the first page load the product grid items load incrementally and **very** slowly, about 1 grid item appears per half second. Subsequent page loads incur a cache hit and so are instantaneous.

I can't figure out why. This happens with and without debugging options enabled.

Here's the complete output of `varnishlog -o` on such a request:
http://rickbuczynski.com/varnishlog-discstore-staging_20150713.txt

The above was taken after flushing all cache storage. Has anyone encountered this before? Are there ESI policies configured by default that would cause this?

**Comment by aricwatson** [comment]
What version of turpentine are you using?

**Comment by miguelbalparda** [comment]
Rick, which version are you using? The most updated version is on the devel branch now. Please also  check #846, there you will find some issues we found in the past and 3 different approaches to use.

**Comment by vbuck** [comment]
Using v0.6.1, I see I'm a couple revisions behind. I'll check out the `devel` to see if there's a difference, and review #846, then respond with updates. Thanks.

**Comment by gewaechshaus** [comment]
This issue is related to form_key rendering and str_replace as far as I remember.

**Comment by vbuck** [comment]
Thanks for the reference. I'll be testing these recommendations tomorrow night and should have a reply thereafter.

**Comment by aricwatson** [comment]
@vbuck Any luck?

**Comment by vbuck** [comment]
Yes, updating to 0.6.3 seems to have solved the problem. Thanks to everyone for the help!
