### ISSUE TITLE
Custom landing/holding page for certain IP range

### ISSUE THREAD

**Issue by craigcarnell** [nexcess/magento-turpentine#854]
Hi,

For whatever reason (e.g. to launch a new store) it would be useful to show a custom landing page to all IP addresses except those that match mine as a developer.

I am not sure how to go about this when you have varnish in front of your server however. Any ideas?

The server may also sit behind a LB where the user ip will be set differently

http://www.rackspace.com/knowledge_center/article/why-does-every-visitor-to-my-cloud-sites-website-have-the-same-ip-address

**Comment by craigcarnell** [comment]
I am actually working on a PR for this

**Comment by aricwatson** [comment]
Thanks, sounds useful! 

> For whatever reason (e.g. to launch a new store) it would be useful to show a custom landing page to all IP addresses except those that match mine as a developer.

So for all IPs that aren't yours, you'd like them to all get redirected to a the same custom page? This should be doable in the VCL I'd think.

**Comment by craigcarnell** [comment]
https://github.com/nexcess/magento-turpentine/pull/857

**Comment by BarryCarlyon** [comment]
Just passing thru you closed your PR when you deleted the branch. And when you recreated the branch it didn't reopen the PR.

**Comment by craigcarnell** [comment]
It is now https://github.com/nexcess/magento-turpentine/pull/885

**Comment by BarryCarlyon** [comment]
Ah coolio I didn't see the follow up PR :-P
