### ISSUE TITLE
form_key is the same for all requests

### ISSUE THREAD

**Issue by thepaleone** [nexcess/magento-turpentine#855]
Hi, I'm testing Magento + Varnish + Turnentine for potential deployment but I'm running into a problem where the form_key is always the same regardless of the client making a request. I'm sure there's something simple I've missed but I can't seem to find anything searching for it. A few things that I know I've done:

1. Varnish is started with the -p esi_syntax=0x2 switch (verified using varnishadm)
2. Varnish caching is enabled within Magento.
3. All other Magento caching options are enabled (I also tried it with disabling all but Varnish)
4. Cache was flushed after every change.
5. ESI debugging does not put any comments around the form_key lines. Other comments are inserted for different blocks.
6. I am using the demo data / store and have not modified any layout or theme files.

Usually I can Google fairly well to find what I'm looking for but I'm having a real hard time coming up with anything. This is a Magento 1.9.1.0 with Varnish 3.0.7 and it should be the latest version of Turpentine (it was installed about 4 days ago).

Thanks in advance for any help.

**Comment by miguelbalparda** [comment]
Please download the latest version from the devel branch and also check https://github.com/nexcess/magento-turpentine/pull/846 where we added some fixes for known issues.

**Comment by thepaleone** [comment]
I downloaded the the devel branch and copied all of the files under /app/.... to the correct locations (overwriting existing files), then went in to flush the Magento Cache and the Magento Storage for good measure, re-applied the Varnish config and ti's still using the same form_key for different clients.

I did not see the exact setting mentioned in the bug: System - Configuration - Turpentine - Varnish Options - General Options - Use VCL fix - No., but I did try toggling the one labled "Enable AJAX Flash Messages" but neither setting worked. Is there something else I missed?

**Comment by miguelbalparda** [comment]
The PR I showed you is under testing and not merged to devel, that is why you are not seeing the option. You can try the official Magento fox anyway and disable completely the CSRF. If you want to try the new features you should checkout the branch I created.

**Comment by miguelbalparda** [comment]
@thepaleone now everything is merged into devel. Any feedback on this issue?

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
