### ISSUE TITLE
Testing with cache on behind http authorization

### ISSUE THREAD

**Issue by mabigo** [nexcess/magento-turpentine#858]
Because of pipe on http Authorization it seems currently impossible to test with cache on, on environments behind http Authorization. 
    
    if (!{{enable_caching}} || req.http.Authorization ||
        req.request !~ "^(GET|HEAD|OPTIONS)$" ||
        req.http.Cookie ~ "varnish_bypass={{secret_handshake}}") {
        return (pipe);
    }
    
after some research i found this 
https://mig5.net/content/excluding-ips-http-auth-when-apache-behind-varnish

i theory we could switch off http auth for developer ip's entered in magento system configuration. Would be useful for development, staging, pre-live environments etc.

    
if (client.ip ~ debug_acl) {
    unset req.http.Authorization;
    set req.http.SkipAuth = "turpentine";
}
    

and let developer use this magic in host configuration
    
    AuthType Basic
    AuthName "Restricted Site"
    AuthBasicProvider file
    AuthUserFile /path/to/htpasswd
    Require valid-user
    Order allow,deny
    SetEnvIf ^SkipAuth* "turpentine" allow
    Allow from env=allow
    

is there anything similar or even better in devel branch?

**Comment by miguelbalparda** [comment]
I think the use case you posted is covered here http://razbakov.com/magento/2015/07/14/htaccess-magento-varnish.html

**Comment by aricwatson** [comment]
Additionally, check out this issue - seems related: https://github.com/nexcess/magento-turpentine/issues/786

**Comment by mabigo** [comment]
thanks @miguelbalparda
this solution is good enough, because someone will need to change .htaccess anyway. I suggest to add similar howto to projects wiki.
