### ISSUE TITLE
Duplicate Frontend Cookies when using www vs non-www

### ISSUE THREAD

**Issue by Petce** [nexcess/magento-turpentine#866]
If a Magento store is configured to `Auto-redirect to Base URL` and has a Base URL of `http://www.example.com` and a visitor attempts to visit the site on `http://example.com`, the user will be, as expected, redirected back to the Base URL (while not tested I expect this issue occurs both ways).

This will cause the Turpentine VCL file to issue a `Frontend` cookie to the user with the `.example.com` domain. However, when the user then performs an action that results in a communication with the backend, like adding a product to their cart or attempting to log in, Magento will issue the user with a new `Frontend` cookie with the `.www.example.com` domain.

This results into a session conflict which Magento is unable to resolve and causes a lock state on the users session. In this state, the user will be unable to perform any task that requires communication with the backend until their cookies for the given Magento Store expires from natural circumstances.

**Comment by miguelbalparda** [comment]
Your example doesn't match the title. In theory you should never face a situation like the ones you are describing. All your links should be either www or non www but not both at the time. It should be pretty easy to follow this good practice with some .htaccess code. See https://support.google.com/webmasters/answer/44231?hl=en

**Comment by Petce** [comment]
It happens if a user goes to a url direct. I discovered this problem because it was occuring for me and my customers. Checking Varnishncsa and the Apache logs are easy and the error does occur.

**Comment by mabigo** [comment]
@Petcec @miguelbalparda  guys its  all about #832 
my suggested solution was to pass the request in case if host is not configured as base url and let backend decide if redirection is needed. It solves the problem and lets other non-magento apache hosts work bypassing varnish.

**Comment by miguelbalparda** [comment]
#832 is merged into devel. Anyway I was referring to this solution http://magento.stackexchange.com/questions/6311/redirect-non-www-prefix-to-www-prefix-still-not-working-after-disabling-auto where you do a 301 and there is no possibility to face this issue.

**Comment by miguelbalparda** [comment]
@Petce any more feedback about this issue?

**Comment by mabigo** [comment]
in general there are several workarounds available. Like @miguelbalparda wrote people can disable auto-redirect to base url or put another webserver in front of varnish (may lead to poor performance. imho). However to avoid this problem for any possible setup it make sense to pass requests for non-baseurl visitors. Also it is not a bad idea to put additional condition into vcl generation class to check configuration value of "Auto-redirect to Base URL"

**Comment by miguelbalparda** [comment]
I don't understand why would you want to allow non-base url visitors. You certainly know the domain the users will request and with a 301 redirect from www to non-www or vice-versa(or http <-> https) this should never happen. Maybe I'm missing something but with the correct configuration and folowing the best practices the case explained in this issue should never happen.

**Comment by mabigo** [comment]
@miguelbalparda best practices are questionable :) Most magento certified hosting provider i know use following setup Magento <- Apache <- Varnish. In this case the comment from @Petce is always true

> The .htaccess can not be used to resolve this problem because Varnish sits in front of the Apache server. 
> This means that the cookie is most likely created on a cache hit.

**Comment by miguelbalparda** [comment]
I don't think this best practice in particular can be questioned. If you end up with 2 different urls you will have 2 different set of cookies, one for each domain. This is correct from any point of view since  WWW and non-www are actually different domains for any indexer or browser, that is why you should find a way to have only one. Now in the devel branch the cookie generation has been removed, so I think the cookie is generated by Magento and not by Varnish. Also the cookies you are talking about are always generated by Magento which means you are past way the Varnish and the .htaccess, so you should be in your unique URL with or without www after the redirect, no matter where the user comes from.

**Comment by Petce** [comment]
The problem is that Varnish intercepts the non-base URL request. And with the VCL that turpentine produces right now, it will always create a cookie at the non-base URL domain. Magento does not clean up `frontend` cookies on different domains so when it sees this, it will consider it invalid, create a new cookie but leave the old one there. This is the cause of a session lock. As @mabigo wrote, the proper solution would be to make the VCL genereation code take into consideration the base URL settiongs.

**Comment by miguelbalparda** [comment]
@Petce are you using the devel branch?

**Comment by miguelbalparda** [comment]
Closed for lack of feedback.
