### ISSUE TITLE
Drop support for Varnish 2?

### ISSUE THREAD

**Issue by craigcarnell** [nexcess/magento-turpentine#867]
3 and 4 have been out for quite some time

**Comment by aricwatson** [comment]
We're agreeing. When we add Varnish 4 support, we'll update the documentation to say that we're no longer testing with Varnish 2, and if any issues come involving Varnish 2 we'll tell them to first try updating to 3 or 4.

**Comment by craigcarnell** [comment]
@aricwatson Any idea when the PR for Varnish 4.0 will be merged into devel? :)

**Comment by aricwatson** [comment]
There's a varnish4 version of devel that's pretty close, which is what I've been testing with - feel free to check it out.
https://github.com/nexcess/magento-turpentine/tree/devel-varnish4

**Comment by miguelbalparda** [comment]
+1 to @aricwatson comment. We will add a notice once Varnish 4 is out.
