### ISSUE TITLE
on Add to cart price shows zero , but on checkout it shows fine. Checkout url is excluded from cache using varnish

### ISSUE THREAD

**Issue by wingsryder** [nexcess/magento-turpentine#868]
On Add to cart price shows zero , but on checkout it shows fine. Checkout url is excluded from cache using varnish.  Also in top header cart it stay zero. Wondering it is not refreshing the prices.

**Comment by miguelbalparda** [comment]
Which version are you using?

**Comment by wingsryder** [comment]
1.9.1

**Comment by miguelbalparda** [comment]
That is the version I'm using to test most of the issues here and didn't notice this in the past. Is there any other module that might be causing this issue.

**Comment by wingsryder** [comment]
There is no other module for cache installed. Also with varnish SSL doesnt show green bar on checkout. It shows yellow triangle. On chrome. that other issue facing. Wondering if that nginx settings issue or varnish module.

**Comment by miguelbalparda** [comment]
Varnish does not support SSL out of the box, I suggest you to check nginx first and then if that does not help we can take a look.

**Comment by wingsryder** [comment]
Do you have proffered Nginx settings  for support proper SSL. Also any idea about zero price? I believe the block is not getting refreshed.

**Comment by miguelbalparda** [comment]
About the block issue, Magento try disabling all the caches but the Turpentine ones in System - Cache. @aricwatson do we have any preferred settings for nginx?

**Comment by wingsryder** [comment]
Did you mean to disable all caches? and leave the Turpentine enabled ?

**Comment by miguelbalparda** [comment]
Yes, something like this
![cache](https://cloud.githubusercontent.com/assets/3997682/8908886/e0114e1e-3454-11e5-8a02-de239d9f225f.png)

**Comment by miguelbalparda** [comment]
Also see https://github.com/nexcess/magento-turpentine/issues/725 for your SSL issues, it might be related.

**Comment by mohit234786** [comment]
Hi,

Even i'm running into the same issue. The cart sidebar is cached even after using default hole punching by turpentine_esi.xml and adding the same into the local.xml. Tried almost everything there on internet and github but the issue does not fix at all.

Magento : 1.9.0.1
Varnish : 3.0.x
Turpentine : 0.6.3

@aheadley Require help from github to fix this as soon as possible.

**Comment by wingsryder** [comment]
i have disabled all cache expect varnish , still not working.

**Comment by miguelbalparda** [comment]
@wingsryder have you found the case of this issue?

**Comment by wingsryder** [comment]
Its still not working for me.

**Comment by wingsryder** [comment]
See this is happening. While using Varnish. Anybody getting same and fixed? Only first item remain zero price. Also it doesnt added in mini cart total price........but once we to main checkout (excluded from varnish) that show correct price.

![1xzbq4u](https://cloud.githubusercontent.com/assets/1322917/9423053/61191700-48d0-11e5-918b-73d276781563.png)

**Comment by aricwatson** [comment]
@wingsryder If you're still having problems - what ESI policy are you currently using for the cart sidebar? You may need to set up some registry keys or flush_events for that block.

**Comment by aricwatson** [comment]
Closing for lack of feedback.
