### ISSUE TITLE
Magento 1.9.2.0 with Varnish 3.0.7 empty cart issue

### ISSUE THREAD

**Issue by tufanayd** [nexcess/magento-turpentine#871]
Hi,

I am using Magento 1.9.2.0 with Varnish Cache 3.0.7 wit Turpentine 0.6.3 and when I add a product to the cart, it is showing Empty Cart page.

Is there a fix or solution for this?

I need it urgently. Thanks in advance.

**Comment by miguelbalparda** [comment]
Please check https://github.com/nexcess/magento-turpentine/pull/846 where you will find 3 different ways to configure Turpentine and avoid this issue.

**Comment by tufanayd** [comment]
I apply the fix and able to add the product to the cart, but when I go back to the homepage or catalog pages, the the cart again becomes empty.

If I go to My Account page, the cart shows the added product.

Also when I try to apply the varnish config it is giving me error of 

Failed to apply the VCL to 127.0.0.1:6082: Got unexpected response code from Varnish: 107 qcznjavfnadfiledhhdotcizxkgecauv Authentication required.

Then I try to apply the vcl manually from by copying from var/ to etc/varnish/ and try to restart the varnish, the varnish doesn't start, it fails.

**Comment by miguelbalparda** [comment]
Did you added the secret key in the admin? You might want to add a \n to the end of it.

**Comment by tufanayd** [comment]
I added the \n to the secret key now below is the new errors:

Failed to apply the VCL to 127.0.0.1:6082: Varnish data to write over length limit by 576 characters
Varnish esi_syntax param is not set correctly, please see these instructions to fix this warning.

I added the esi syntax -p esi_syntax=0x2 to /etc/sysconfig/varnish and it gave me this error:
/etc/sysconfig/varnish: line 107: -p: command not found

**Comment by tufanayd** [comment]
Ok, I have added the necessary -p to the /etc/sysconfig/varnish

Now new error arises which is:

Failed to apply the VCL to 127.0.0.1:6082: Got unexpected response code from Varnish: 106 Message from VCC-compiler: Undefined sub generate_session_expires, first reference: ('input' Line 259 Pos 6) call generate_session_expires; -----########################- Running VCC-compiler failed, exit 1 VCL compilation failed

**Comment by miguelbalparda** [comment]
Which method are you using as a fix for the issue in the cart?

**Comment by tufanayd** [comment]
Now everything is working fine however the fix is breaking the Ultimo theme My cart icon, it is replacing with the default cart I guess.

You can check it from http://www.glitzsilver.com/ (this is my test site for Magento and Varnish)
This is the original theme page http://ultimo.infortis-themes.com/demo/default/ where you can see the cart icon (on the top right)

**Comment by miguelbalparda** [comment]
We can't assure you full out of the box compatibility with every theme in the market. I suggest you to ask the vendor of the theme about this.

**Comment by tufanayd** [comment]
Thank you for your help and guidance.

**Comment by miguelbalparda** [comment]
Check http://magento.stackexchange.com/questions/69215/ee-1-14-2-ce-1-9-2-block-caching-update-has-non-unique-cache-keys-duplicate @tufanayd
