### ISSUE TITLE
Need to pass two cookies

### ISSUE THREAD

**Issue by frankc420** [nexcess/magento-turpentine#872]
We are using Magento 1.7 and the latest build of Turpentine that was available on Magento Connect.  

We use a recommendation engine from a company called Besugre.  We can insert blocks on multiple pages throughout the site and these blocks get their information from the cookies that get passed by the server.  The cookie is dynamic and updated by the server after each page load.  

Since cookies are stripped by default, the blocks are displaying the first cached list of products to all users.  The two cookie names are:

besugre_recommendation
besugre_recommendation_c

How can I allow these to pass so that we can get dynamic listings to our users?

**Comment by miguelbalparda** [comment]
@frankc420 please take a look at https://github.com/nexcess/magento-turpentine/issues/816 where we faced the same issue.

**Comment by frankc420** [comment]
I'm not seeing a resolution to his issue.  Since these are cookies and not URL variables I'm not understanding how it would apply in this case.  Am I missing something?

**Comment by miguelbalparda** [comment]
The title of the issue is "Adding an extra cookie (like currency or store)" #816. Also see PR #838 where a cookie is added for customer groups.

**Comment by miguelbalparda** [comment]
Any news about this @frankc420 ?

**Comment by miguelbalparda** [comment]
Closed for lack of feedback.
