### ISSUE TITLE
Release 0.6.3 on Magento connect is missing templates

### ISSUE THREAD

**Issue by nicka101** [nexcess/magento-turpentine#873]
Templates within the packaged extension are gone, and the extension will not function properly without them. I have resolved the issue for my sites by manually replacing the missing templates with the ones from release 0.6.1

**Comment by miguelbalparda** [comment]
Which templates are missing?

**Comment by miguelbalparda** [comment]
I would suggest you to download the missing templates from the master branch in this repo BTW.

**Comment by miguelbalparda** [comment]
I'm seeing the VCL templates present in the package.

**Comment by Schoeny1** [comment]
I too had issues installing the latest version of the plugin through Magento connect.  For some reason there were missing files.  I ended up installing the previous version and it works great.

**Comment by miguelbalparda** [comment]
See https://github.com/nexcess/magento-turpentine/pull/874, I already corrected the Magento Connect version with the templates. Thank you for noticing this @Schoeny1 and @nicka101
