### ISSUE TITLE
302 Redirect when using Googlebot Agent

### ISSUE THREAD

**Issue by delarosajv** [nexcess/magento-turpentine#881]
Hello,

i have to remove .Googlebot. from Crawler user agents cause varnish is given 302 redirect to main domain when Googlebot user agent loads the page.

I have two themes for the same url using device detection via javascript. Prior using this device selecion method, all worked fine.

please someone have a solution for this? i lost huge seo traffic because of this and it will be nice to get this working.

thank you

**Comment by miguelbalparda** [comment]
I don't think this is an actual issue. Is there any code to replicate this?

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.

**Comment by TableDeMassageElectrique** [comment]
I have the same problem. I don't understand why. It was operating normally before. The problem began only in early September.

I test using Google tools:
https://www.google.com/webmasters/tools/googlebot-fetch

HTTP response : 
HTTP/1.1 302 Found
Content-Type: text/html
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: frontend=crawler-session; expires=Wed, 16-Sep-2015 09:47:57 GMT; path=/; domain=table-de-massage-electrique.fr; httponly
Set-Cookie: frontend=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; domain=table-de-massage-electrique.fr; httponly
Location: http://table-de-massage-electrique.fr/
X-Page-Speed: Powered By ngx_pagespeed
X-Cache: MISS
Transfer-Encoding: chunked
Date: Wed, 16 Sep 2015 08:47:57 GMT
Age: 0
Connection: keep-alive

**Comment by TableDeMassageElectrique** [comment]
We can see the start of the problem in Google Merchant Center : 
![merchant-center](https://cloud.githubusercontent.com/assets/6951942/9900720/ede749f4-5c62-11e5-8b01-642bfd18f3ab.PNG)

**Comment by delarosajv** [comment]
Hello I'm still with the problem.

I have to exclude googlebot from bot list in turpentine admin. This is a
bad solution cause google always get a slow, noncached version of the page.

I hope someone can help us to find the solution to this.

2015-09-16 11:07 GMT+02:00 TableDeMassageElectrique <
notifications@github.com>:

> We can see the start of the problem in Google Merchant Center :
> [image: merchant-center]
> <https://cloud.githubusercontent.com/assets/6951942/9900720/ede749f4-5c62-11e5-8b01-642bfd18f3ab.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nexcess/magento-turpentine/issues/881#issuecomment-140678650>
> .
>



-- 
Javier de la Rosa Prieto
email: delarosajv@gmail.com

**Comment by james-siddall** [comment]
I'm having the same issue only it is with user agent validation turned on.

For some reason when the session gets validated, it happens about 4 times per request and in some of the attempts the user agent is different. Trying this as Googlebot I see 2 user agents, 1 is the one I'm using and 2 is what it is being validated against but I have no idea where it is coming from.

1.Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
2. Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)

**Comment by delarosajv** [comment]
@james-siddall have you found a solution for this?

i'm still excluding Googlebot from user agent list to ser er cached version on first page load.

Recently i have updated to version .68 but i have not tested if this is fixed here

**Comment by delarosajv** [comment]
i think i found the solution to this:
Have you tried to disable this magento option?
Redirect to CMS-page if Cookies are Disabled

**Comment by aricwatson** [comment]
Closing for lack of feedback.

**Comment by mobweb** [comment]
I've had the same issue for one shop which unfortunately lead to a lot of previously indexed pages getting unlisted in the Google index.

This was the response that the Google Crawler received from the server:

```
HTTP/1.1 302 Found
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: frontend=crawler-session; expires=Thu, 08-Mar-2018 10:26:40 GMT; path=/; domain=example.com; httponly
Set-Cookie: frontend=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; domain=example.com; httponly
Location: http://example.com/
Connection: keep-alive
Content-Type: text/html
Content-Length: 0
Accept-Ranges: bytes
Date: Wed, 07 Mar 2018 10:26:40 GMT
Age: 0
```

This redirected the crawler to the frontpage, stopping it from indexing any page that is not the frontpage! :(

The issue was this line:

`Set-Cookie: frontend=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; domain=example.com; httponly
`

This seems to be used when Magento fails to validate the session. In my case, I had to set "Validate HTTP_USER_AGENT" to "No" in the backend. For some reason, the Google Crawler failed the HTTP_USER_AGENT validation of Magento, leading to a redirect to the frontpage.

**Comment by craigcarnell** [comment]
@miguelbalparda Can confirm this issue.

http://www.redirect-checker.org/index.php

Checking our site as a user, no 302 re-direct
Checking our site using GOOGLEBOT, 302 re-direct.

The only option we have found is to set Validate HTTP_USER_AGENT" to "No" which is a security related feature of Magento we would rather not switch off.

Any suggestions?
