### ISSUE TITLE
Magento 1.9.2.1 - frontpage specific content doesn't show

### ISSUE THREAD

**Issue by m-overlund** [nexcess/magento-turpentine#886]
After upgrading to Magento 1.9.2.1 my cms home specific content doesn't show, when varnish is enabled.
When using the varnish bypass cookie the content shows just fine.

I use route and identifier to check for the homepage:

    $routeName = Mage::app()->getRequest()->getRouteName();
    $identifier = Mage::getSingleton('cms/page')->getIdentifier();
    
    if($routeName == 'cms' && $identifier == 'home'): 

Check www.fyr-selv.dk with and without varnish_bypass cookie for an example.

![with_varnish](https://cloud.githubusercontent.com/assets/504236/9327171/39be53ac-459f-11e5-87fa-0cdd3cceff81.png)
![without_varnish](https://cloud.githubusercontent.com/assets/504236/9327170/39bc34e6-459f-11e5-8d45-70d99393e0fe.png)

**Comment by aricwatson** [comment]
Odd... Is the homepage-specific content contained within a block that has an ESI policy? If you turn on the debug logging, is there anything showing up in the logs?

**Comment by m-overlund** [comment]
Thanks for getting back - Finally got time to test a bit again:

Yeah, it's in the header block, with ESI set to private (because it also contains the cart).
The cart in header updates as it should.

Can't really find anything in the logs.


```
2015-08-24T06:36:08+00:00 DEBUG (7): TURPENTINE: Matched router: default
2015-08-24T06:36:08+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: header
2015-08-24T06:36:08+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: store_language
2015-08-24T06:36:08+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: top.links
2015-08-24T06:36:08+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: wishlist_link
2015-08-24T06:36:08+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: top.search
2015-08-24T06:36:08+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: ANONYMOUS_12
2015-08-24T06:36:08+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: top.container
2015-08-24T06:36:08+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: bml.center.logo
2015-08-24T06:36:08+00:00 DEBUG (7): TURPENTINE: Set Varnish cache flag header to: 1
2015-08-24T06:36:08+00:00 DEBUG (7): TURPENTINE: Set ESI flag header to: 0
2015-08-24T06:36:08+00:00 DEBUG (7): TURPENTINE: Generated form_key: 8hthLVorjPkmWQq0
2015-08-24T06:36:08+00:00 DEBUG (7): TURPENTINE: Set Varnish cache flag header to: 1
2015-08-24T06:36:08+00:00 DEBUG (7): TURPENTINE: Set ESI flag header to: 0
2015-08-24T06:36:14+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: root
2015-08-24T06:36:14+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: content
2015-08-24T06:36:14+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: messages
2015-08-24T06:36:14+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: form.additional.info
2015-08-24T06:36:14+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: captcha
2015-08-24T06:36:14+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: ANONYMOUS_29
```

Headers:
```
Age:1039
Connection:keep-alive
Content-Encoding:gzip
Content-Type:text/html; charset=UTF-8
Date:Mon, 24 Aug 2015 06:35:28 GMT
Server:nginx
Transfer-Encoding:chunked
Via:1.1 varnish
X-Content-Type-Options:nosniff
X-Frame-Options:sameorigin
X-Frame-Options:SAMEORIGIN
X-Turpentine-Cache:1
X-Turpentine-Esi:1
X-Varnish:1572897879 1572897797
X-Varnish-Currency:
X-Varnish-Esi-Access:
X-Varnish-Esi-Method:
X-Varnish-Hits:22
X-Varnish-Host:www.fyr-selv.dk
X-Varnish-Set-Cookie:frontend=0d612455a00140018e001e464c0099a4; expires=Tue, 25-Aug-2015 06:18:08 GMT; Max-Age=86400; path=/; domain=fyr-selv.dk; httponly
X-Varnish-Store:
X-Varnish-URL:/
```

**Comment by m-overlund** [comment]
Additional info: We're running multistore, and the issue is the same on the other websites, using different templates etc.

**Comment by m-overlund** [comment]
The issue is that the identifier is empty when using varnish:

    Mage::getSingleton('cms/page')->getIdentifier();

**Comment by miguelbalparda** [comment]
@m-overlund have you tried using $this->getIsHomePage()? It can be also Mage::getBlockSingleton('page/html_header')->getIsHomePage(). See http://stackoverflow.com/questions/12403675/detect-home-page-in-magento-phtml-that-will-work-with-block-html-cache-enabled for some more info.

**Comment by m-overlund** [comment]
Can't get the mentioned solutions working with turpentine enabled. 
As mentioned it works just fine without turpentine enabled too - shouldn't be an error in Magento per se.

This issue is very strange.
Been looking through the base code of CMS page handling, and the getRequest seems to be the way to identify - thats the way Magento does it too.

    print_r(Mage::app()->getRequest()->getControllerName());

Will output:

Without varnish:
Frontpage: index
CMS page: cms

Varnish enabled:
Frontpage, : cms
CMS page: index

Works opposite as expected with varnish enabled.

Temporary solution could be to check for ControllerName not to be frontpage and it would work as expected.

But could be nice to fix the actual issue :-)


I'm getting way out of my area of expertise, but my best guess would be that Magento changed some of the identifier/router code, which makes turpentine alter the identifier to always be null.


The only bits i can grep on anything like this is from Model/Dummy/Request.php, Line: 767
Maybe it could be helpful?

```
    protected function _cmsRouterMatch() {
        $router = Mage::app()->getFrontController()->getRouter( 'cms' );

        $identifier = trim($this->getPathInfo(), '/');

        $condition = new Varien_Object(array(
            'identifier' => $identifier,
            'continue'   => true
        ));
        Mage::dispatchEvent('cms_controller_router_match_before', array(
            'router'    => $router,
            'condition' => $condition
        ));
        $identifier = $condition->getIdentifier();

        if ($condition->getRedirectUrl()) {
            Mage::app()->getFrontController()->getResponse()
                ->setRedirect($condition->getRedirectUrl())
                ->sendResponse();
            $this->setDispatched(true);
            return true;
        }

        if (!$condition->getContinue()) {
            return false;
        }

        $page   = Mage::getModel('cms/page');
        $pageId = $page->checkIdentifier($identifier, Mage::app()->getStore()->getId());
        if (!$pageId) {
            return false;
        }

        $this->setModuleName('cms')
            ->setControllerName('page')
            ->setActionName('view')
            ->setParam('page_id', $pageId);
        $this->setAlias(
            Mage_Core_Model_Url_Rewrite::REWRITE_REQUEST_PATH_ALIAS,
            $identifier
        );

        return true;
    }
```

**Comment by m-overlund** [comment]
This also returns 1 on every page except the frontpage:

    Mage::getBlockSingleton('page/html_header')->getIsHomePage();

Will try a clinical test when i have time...

**Comment by m-overlund** [comment]
Tested on blank rwd theme on same installation, with same results.
Need to test on clean Magento installation, to rule out any other modules etc.

**Comment by miguelbalparda** [comment]
Any news on this @m-overlund?

**Comment by m-overlund** [comment]
Not really. Still need time to do a clean test, to get any further...



And still the same after updating to latest turpentine version.





—

**Comment by m-overlund** [comment]
Hmm...

Works in Firefox now, on my computer at least. (using inverted logic for the isHomepage check though)

But both Google Chrome and IE11 doesn't work as expected.
The `"Billigt brændsel på nettet"` heading doesn't get outputted in the HTML of www.fyr-selv.dk neither on frontpage nor on other pages.
Emptying cache and cookies doesn't change a thing.

**Comment by aricwatson** [comment]
@m-overlund that's odd, I can't think of a reason why it would work in Firefox but not other browsers... And this on a clean Magento install with the sample data? Can you give steps to replicate in that scenario?

**Comment by m-overlund** [comment]
https://github.com/nexcess/magento-turpentine/issues/965#issuecomment-144739007
Fixed my issues by disabling block cache (and others).

**Comment by dartsuresh** [comment]
I have the same issue . I have the slider only visible in home page. with the below condition
`$routeName = Mage::app()->getRequest()->getRouteName();
$identifier = Mage::getSingleton('cms/page')->getIdentifier();

if($routeName == 'cms' && $identifier == 'home'): 

We used SM Market theme. In my theme they used slider under header. So i try to use different header with <cms_index_index> now it shows the slider but cart not working based on client in home page.

Please advise me.
