### ISSUE TITLE
Esi policy with local.xml

### ISSUE THREAD

**Issue by tufanayd** [nexcess/magento-turpentine#887]
Hi,

I am using Magento ver. 1.9.2.1 with Varnish 3 and Turpentine (latest from Git). I have Ultimo Theme installed and without esi policy into local.xml the top cart (mini.cart) looks fine  like below:

![without_esi](https://cloud.githubusercontent.com/assets/5356911/9356152/5e726bfa-4687-11e5-9460-892bb88043f9.jpg)

However if I apply esi to local.xml like below:

			
			<block type="checkout/cart_sidebar" name="cart_sidebar" template="checkout/cart/mini.phtml" before="-">
				<action method="setEsiOptions">
					<params>
						<method>esi</method>
						<access>private</access>
						<flush_events>
							<sales_quote_save_after/>
						</flush_events>
					</params>
				</action>
				<action method="addItemRender"><type>simple</type><block>checkout/cart_item_renderer</block><template>checkout/cart/sidebar/default.phtml</template></action>
				<action method="addItemRender"><type>grouped</type><block>checkout/cart_item_renderer_grouped</block><template>checkout/cart/sidebar/default.phtml</template></action>
				<action method="addItemRender"><type>configurable</type><block>checkout/cart_item_renderer_configurable</block><template>checkout/cart/sidebar/default.phtml</template></action>
				<block type="core/text_list" name="cart_sidebar.extra_actions" as="extra_actions" translate="label" module="checkout">
					<action method="setEsiOptions">
						<params>
							<method>esi</method>
							<access>private</access>
							<flush_events>
								<sales_quote_save_after/>
							</flush_events>
						</params>
					</action>
					<label>Shopping Cart Sidebar Extra Actions</label>
				</block>
				<block type="cms/block" name="block_mini_cart_above_products">
					<action method="setBlockId"><block_id>block_mini_cart_above_products</block_id></action>
				</block>
			</block>

The cart becomes like this:

![with_esi](https://cloud.githubusercontent.com/assets/5356911/9356095/0de5667e-4687-11e5-97da-3d27bc43f193.jpg)

Where am I doing wrong?

Thanks

**Comment by aricwatson** [comment]
We've seen similar issues on a couple client sites lately and are investigating to see what changes might be required in Turpentine. The solution we've found for now is to comment out the ESI policy for the cart_sidebar block in the turpentine_esi.xml file, so that there's no specific policy set for that block. In the cases we've seen, since it's a part of the header block it works out. 

Please try this and let us know if it fixes the problem!

**Comment by tufanayd** [comment]
Hi,

Thank you for your solution which is working for the time being.

However I am using AJAX add to compare from Excellense and I have disabled the turpentine_esi.xml for the compare block and in my local.xml I added the below for the compare block:
			
			<block type="catalog/product_compare_sidebar" name="compare.mini" as="compareMini" template="catalog/product/compare/mini.phtml">
				<action method="setEsiOptions">
					<params>
					<method>esi</method>
						<access>private</access>
						<flush_events>
							<catalog_product_compare_add_product/>
							<catalog_product_compare_remove_product/>
							<catalog_product_compare_item_collection_clear/>
						</flush_events>
					</params>
				</action>
			</block>

When I choose the method esi it gives me the message "ESI processing not enabled" after the product added to the compare list thorugh AJAX, but when I choose method AJAX, it is working fine. Could there be a problem wit the method esi for ajax add to compare?

**Comment by tufanayd** [comment]
Hi,

Thank you for your solution which is working for the time being.

However I am using AJAX add to compare from Excellense and I have disabled the turpentine_esi.xml for the compare block and in my local.xml I added the below for the compare block:

			
			<block type="catalog/product_compare_sidebar" name="compare.mini" as="compareMini" template="catalog/product/compare/mini.phtml">
				<action method="setEsiOptions">
					<params>
					<method>esi</method>
						<access>private</access>
						<flush_events>
							<catalog_product_compare_add_product/>
							<catalog_product_compare_remove_product/>
							<catalog_product_compare_item_collection_clear/>
						</flush_events>
					</params>
				</action>
			</block>

When I choose the method esi it gives me the message "ESI processing not enabled" after the product added to the compare list thorugh AJAX, but when I choose method AJAX, it is working fine. 

Could there be a problem wit the method esi for ajax add to compare?

**Comment by ADDISON74** [comment]
Compare side blocks has some issues with redirecting. I did the same thing a cuple of days ago with no positive results. I guess AJAX is creating trouble with comparison. See #895.

Check this issue. Open the comparison windows and delete one of the products. Is it working?

**Comment by tufanayd** [comment]
I am using <method>AJAX</method> and it is working fine for me with the AJAX Add to Compare extension. When I add or delete or empty compare list everything is working fine.

**Comment by ADDISON74** [comment]
@tufanayd please do the following steps:

1. Go to category A and add one product for comparison
2. Go to category B and delete this product or clear all from comparison

You have to be redirected to Category A instead of being on Category B page.

Of course, Adding and Deleting individual products, and Clear All work as actions, but Turpentine has a problem with redirected. This is a bug already investigated.

**Comment by tufanayd** [comment]
@ADDISON74 thanks for your comments but hence I am using AJAX add to compare, whishlist and cart I have no redirection and therefore Turpentine works well.

Another issue is when I add a product to cart(using ajax add to cart extension) a small label shows up on top of the product photo in the category list and product page, but becuase of the cache if you refresh the page the label doesn't show. how can I write an esi policy for this to make the label not cached ?

**Comment by aricwatson** [comment]
Hmm, what are the current ESI policies for the block containing the label?

**Comment by aricwatson** [comment]
Closing for lack of feedback.

**Comment by Feggel** [comment]
I have the same problem as tufanayd described.
My mini cart is being cached, using same Ultimo 1.15 theme.

I tried the fix offered by aricwatson, but that doesn't work for me.
Any suggesties of what I also could try to fix this?

**Comment by aricwatson** [comment]
When you say your cart is being cached, does that mean that it's not being cached privately - i.e. other visitors will see someone else's cart? What are the ESI policies you've set for this block?

**Comment by Feggel** [comment]
As tufanayd said, the cart breaks when you activate Turpentine.
I've set the following ESI policy:

`
<reference name="cart_sidebar">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <flush_events>
                        <sales_quote_save_after/>
                    </flush_events>
                </params>
            </action>
      </reference>
`

The problem isn't that other visitors see someone else's cart. It breaks in styling.
The dropdown doens't work anymore. As you can see in the first post by tufanayd, screenshot 1 and 2

The fix described by you for this, doesn't work for me.

**Comment by Feggel** [comment]
For better understanding here are some screenshots.

Wrong with Varnish enabeld:
![wrong-cart-varnish-enabled](https://cloud.githubusercontent.com/assets/7804094/14018601/f8e854e0-f1ce-11e5-8099-4263a68f60bf.JPG)

Correct with Varnish disabled:
![correct-cart-with-varnish-enabled](https://cloud.githubusercontent.com/assets/7804094/14018626/0aa26f72-f1cf-11e5-92cf-efe672ae10ee.png)


But I do believe I've setup the correct ESI policy as described above.

**Comment by R0n1n-77** [comment]
I had a similar issue with a Buyshop template.
Setting the esi in a following manner worked:
```
<reference name="topcart">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <flush_events>
                        <sales_quote_save_after/>
                        <checkout_cart_product_add_after/>
                        <checkout_cart_update_items_after/>
                        <checkout_cart_product_update_after/>
                    </flush_events>
                <!--    <method>ajax</method> -->
                </params>
            </action>
        </reference>
```
Important: in my case, it worked only if set in a local.xml of a theme and inside the reference(header in my case) that the "topcart" block is defined in. So I generally added a policy, as reference inside reference.

**Comment by aricwatson** [comment]
@tufanayd  FYI - we had an issue with a client using the Ultimo theme. We were able to resolve it by adding ` <disableEsiInjection>1</disableEsiInjection>` to the `cart_sidebar` block, allowing it to just be cached with the read of the header (which is cached privately).
