### ISSUE TITLE
Current VCL GZIPs Images Too

### ISSUE THREAD

**Issue by theycallmepepper** [nexcess/magento-turpentine#892]
Issue seems to stem from ``` set beresp.do_gzip = true; ```  in the VCL template.

I have proper gzip rules laid out in the htaccess file.  If I comment out the line I mentioned above and run ```curl -I -H "Accept-Encoding: gzip,deflate" http://URLGOESHERE ```  after adjusting/reapplying the VCL then it stops running gzip on images but continues to run it on everything else as it should.

I checked against http://sip400-demo.nexcess.net/ to make sure it was gzipping images there too and it was.

**Comment by miguelbalparda** [comment]
I don't see why this is an issue, can you elaborate this with some more details?

**Comment by theycallmepepper** [comment]
Images are already processed so running GZIP on them should be an unnecessary use of resources and from what I understand it interferes with 3rd party CDN type services that manipulate images on your site between their origin and the browser.

**Comment by miguelbalparda** [comment]
I don't see this as an issue, not everyone has gzip enabled in the .htaccess. The default VCL is a template which will never satisfy every case and/or scenario. It seems the issue can only happening in a subset of scenarios. We can add some info to the documentation but it is definitely not a problem everyone will face.

**Comment by theycallmepepper** [comment]
Understood.  Before closing this out, do you foresee any issues from commenting that line out as long as you have proper gzip rules set up in the .htaccess ?

**Comment by miguelbalparda** [comment]
I don't think there should be any issues commenting the mentioned line, but it's up to every user to make the change.
