### ISSUE TITLE
Flash Messages not displayed - Magento 1.9.1.1, Turpentine 0.6.4 (branch devel), Varnish 3.x

### ISSUE THREAD

**Issue by ceckoslab** [nexcess/magento-turpentine#893]
System:
 * Magento 1.9.1.1
 * Turpentine 0.6.4 (branch devel - 8ac83545023706ad2ef34ca054430bcefe3f3e96)
 * Varnish 3.x

Turpentine settings:
 * Enable AJAX Flash Messages - Enable

With this System and Turpentine settings I don't see any flash Messages. For example when I add a product to cart I don't see flash message.

After some debugging I found that Turpentine is preparing the Messages ESI block but I couldn't find any ESI related comments when I was with Enable Debug Info - Enabled. I expected to see something like this in the page output:

```
<!-- ESI START [global_messages] -->
<!-- ESI URL: ............
........
<!-- ESI END [global_messages] -->
```

I ended up at this code snippet in Nexcessnet_Turpentine_Block_Core_Messages:

```
    protected function _toHtml() {
        if( $this->_fixMessages() ) {
            if( $this->_shouldUseInjection() ) {
                $html = $this->renderView();
            } else {
                $this->_loadMessages();
                $this->_loadSavedMessages();
                $html = $this->_real_toHtml();
            }
        } else {
            $html = $this->_real_toHtml();
        }
        $this->_directCall = false;

        if (count($this->getMessages()) == 0) {
            return '';
        }
        return $html;
    }
```

I managed to see the ESI directives and to see the flash messages after commenting:
```
//if (count($this->getMessages()) == 0) {
//      return '';
//}
```

In my case I was first entering in:
```
if( $this->_shouldUseInjection() ) {
       $html = $this->renderView();
}
```
The $html variable contained the HTML which contained the ESI directives as well but couple of lines below the $html value was set to ''.

Seems that there is some logical mistake in _toHtml() but so far I am not able to understand the real purpose of this fix - https://github.com/nexcess/magento-turpentine/commit/8f6acc5a2e2921a5d24e54afc8ad793cb685105a

Can somebody check and clarify that he / she has the same problem, so we can find out what is the best solution?

**Comment by miguelbalparda** [comment]
Fixed by https://github.com/nexcess/magento-turpentine/pull/894/commits
