### ISSUE TITLE
Compare Products side block is compromised!

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#895]
Sorry for re-posting again, but I found one more issue related to this annoying behavior:

1) CLEAR ALL button
When you use this button it should clear the comparison list and refresh the page.  It won't do this. After Magento cleans the list, you will be redirected to the last past you added a product to the comparison list. Please add a product to comparison list, visit a new category and click on Clear All button. The page loads not with the current category content but the page content you added the product for comparison (category or product page).

2) Deleting individual products in the list (X buttons)
Same issue here too. When you delete a product from list your page content after refreshing will be the last one you added a product for comparison instead of current one.

Is this an AJAX related issue like in Community Poll?

As it is now, comparison is totally compromised. It can be used hoping the visitor won't clear products from list or the whole list. When a visitors clears the list he will become confused for sure trying to understand what happened. Please investigate and provide a solution asap. Initially I was disabling Clear All button by hiding it with CSS. Now all delete individual buttons have issues too, cannot hide them all.

Thank you.

**Comment by miguelbalparda** [comment]
We could really use some more informative titles for the issues you post, no one having the same issue will be able to find this with the current titles. Anyway we will check this and get back to you.

**Comment by ADDISON74** [comment]
aricwatson investigated this issue a couple of weeks ago. but only for Clear All button. the initial issue report is closed. today I found an new issue related to #2 from above. it is only a matter of history/redirect after page reloads.

thank you.

**Comment by aricwatson** [comment]
Yes, I believe there is a larger issue related to referer problems which I hope to track down at some point. There are a number of issues where the user is redirected differently when when using Varnish than otherwise.

We're still tracking that down, I think for now we can close this particular issue.

**Comment by ADDISON74** [comment]
More on this:

Case 1:
1) Go visit Category A, add Product 1
2) Go visit Category B, add Product 2
3) Go visit Category C, add Product 3 and STAY in this category. 

Now delete individual products or Clear All, everything is working just perfect.

Case 2:
1) Go visit Category A, add Product 1
2) Go visit Category B, add Product 2
3) Go visit Category C, add Product 3
4) Go visit Cateogry D

Now delete individual products or Clear All. You will be always redirected to the last page you added a product for comparison.

**Comment by ADDISON74** [comment]
@aricwatson Please reopen this issue too. it should be marked as a bug. 

Any positive thoughts after investigating it?

**Comment by aricwatson** [comment]
We're still looking into the issues surrounding redirects like this. It's an issue we're aware of and working on, and I think this particular issue is just one manifestation of the larger one. I'll reopen it to help us remember to check this particular scenario when we find a solution. Thanks for the very specific steps to replicate - always helpful!

**Comment by ADDISON74** [comment]
Great. I appreciate for your dedicated work. I am not rushing you at all. This comparison issue is very annoying. I pretty sure you will find out what is going wrong. Turpentine extension made a lot of steps in good in the last months.

**Comment by ADDISON74** [comment]
@thampe came with this possible solution: I had a similar issue. The problem is that magento encodes the redirect url inside the remove url which is cached by your varnish server. You can fix it if you build the compare url manually without the encoded url parameter:

// default
$this->helper('catalog/product_compare')->getRemoveUrl($_item);
// manually
$this->getUrl('catalog/product_compare/remove', array('product' => $_item->getId()));

app/design/{theme}/{package}/template/catalog/product/compare/sidebar.phtml
app/design/{theme}/{package}/template/catalog/product/compare/list.phtml

Or override the helper Mage_Catalog_Helper_Product_Compare

**Comment by ADDISON74** [comment]
I checked the files. In Magento 1.9.2.1 here are the content to modify:

list.phml

from
<code>
 <td class="a-right"><a href="#" class="btn-remove" onclick="removeItem('<?php echo $this->helper('catalog/product_compare')->getRemoveUrl($_item) ?>');" title="<?php echo $this->quoteEscape($this->__('Remove This Item')) ?>"><?php echo $this->__('Remove This Item') ?></a></td>
</code>

to
 <td class="a-right"><a href="#" class="btn-remove" onclick="removeItem('<?php echo $this->getUrl('catalog/product_compare/remove', array('product' => $_item->getId())); ?>');" title="<?php echo $this->quoteEscape($this->__('Remove This Item')) ?>"><?php echo $this->__('Remove This Item') ?></a></td>
</code>

**Comment by ADDISON74** [comment]
Is it necessary to change list.phtml file? Just changing only in sidebar.phtml it seems to fix the issue for removing individual products. There is no redirecting at all.

**Comment by thampe** [comment]
Hi @ADDISON74,

your modifications are correct. The way I suggested you to fix the issue, should not be implemented by the Turpentine Module itself, because it requires template changes, which will be in most cases overridden by a custom theme.

 There are two other options to fix the redirect problem in general:

* Override alle Blocks/Helpers (e.g. the Mage_Catalog_Helper_Product_Compare) which generate an url with an encoded url parameter (`uenc`) and remove it. But I am *not a big fan* of rewrites. 
* Create an observer which removes the `uenc` parameter before the controller action is executed. Possible Event: `controler_action_predispatch`. I have not tested these solution.

Both solutions can break some of magentos core functionality.

**Comment by ADDISON74** [comment]
@thampe : Did you find a solution for [Clear All] button which is affected in the same way?

**Comment by thampe** [comment]
```php
$this->getUrl('catalog/product_compare/clear');
```

this should do the trick ;)

**Comment by ADDISON74** [comment]
Thank you. Your suggestion worked.

I hope Turpentine developers will take in consideration this option and find a way not editing our templates. It is a matter of redirecting at all.

**Comment by ADDISON74** [comment]
any feedback or update from Turpentine developers related to this issue?

**Comment by ADDISON74** [comment]
I will close this issue for opening other one with more details and extended.

**Comment by ADDISON74** [comment]
Just to let you know what I found from #119:

@aheadley : "This should actually be fixed as of 0.5.2 . Turpentine will now generally redirect users back to the page they were on instead of to /checkout/cart/ for most cases."

Is still the way today in Turpentine? This is not good at all.
