### ISSUE TITLE
Best practice for separated admin instance

### ISSUE THREAD

**Issue by mikeschaekermann** [nexcess/magento-turpentine#896]
In hopes that this question has not been covered in the wiki or issues before (could not find anything), I would like to ask if there is a best practice to use Turpentine+Varnish with a server setup where there is 1 single web server for the admin back-end and a separate array of front-end servers.

My naive approach would have been to create a VCL file on the back-end instance and then copy this configuration file over to the front-end instances. Would this require approach require any modifications to the VCL file, created on the backend?

Also, should one turn off the automatic creation of a VCL file on config save then?

**Comment by miguelbalparda** [comment]
I don't quite understand where you are going. Is your issue about applying a VCL to a different Varnish server? If this is the case you can configure your servers IP in the admin. Also Varnish is used only in the frontend, all the requests to the admin are piped.

**Comment by mikeschaekermann** [comment]
Thanks for your quick reply. I am very new to both Varnish and Turpentine. Right now, after installing the module and Varnish on all our application servers, when I save the Turpentine back-end configuration, a VCL file will be put into the back-end instances local file system. My main question is if the module somehow supports distribution of the same VCL file to all instances, back-end and front-end, e.g. using database file storage of the VCL file or whether I have to do that manually.

**Comment by miguelbalparda** [comment]
Actually it is not that complex. The file is being saved but then it is also applied to the server you configured in the admin. So having the file in only one server doesn't actually matter since if you configured your Varnish IP in the Turpentine admin it will be applied. The only thing you need to be sure is that you actually can reach the varnish server from the backend server and that it will stand in front of your frontend server.

**Comment by mikeschaekermann** [comment]
Ah, I see, so the recommended way would not be to have one Varnish server running locally on every Magento application server, but rather to have a single central Varnish server as a reverse proxy for all front-end servers. Is that correct?

**Comment by miguelbalparda** [comment]
Yes. You can have one or multiple varnish servers in front of your frontend server and nothing in front of your backend server since you don't want to see cached info when dealing with products or orders.

**Comment by mikeschaekermann** [comment]
One last question though. If you have a load balancer in front of your application server array (in our case an AWS Elastic Load Balancer), how would that work with Varnish between the load balancer and the front-end servers? Wouldn't Varnish then compromise the load balancing functionality? I know that this is rather a Varnish-specific question and not something having to do specifically with Turpentine, but I would appreciate your quick advice if you still have the time for it.

**Comment by miguelbalparda** [comment]
You might want to check https://www.varnish-cache.org/trac/wiki/LoadBalancing

**Comment by mikeschaekermann** [comment]
Thanks, Miguel. That's exactly what I needed.
