### ISSUE TITLE
VCL can nto be apllied because Varnish Version Detection is not reliable

### ISSUE THREAD

**Issue by thampe** [nexcess/magento-turpentine#908]
Hi, 

I have updated to the latest stable version 0.6.5. And now the VCL-File can no longer be applied:

```Failed to apply the VCL to 127.0.0.1:6082: Got unexpected response code from Varnish: 106 Message from VCC-compiler: Expected ';' got '"; "' (program line 174), at ('input' Line 66 Pos 56) set req.http.Cookie = req.http.X-Varnish-Faked-Session "; " req.http.Cookie; -------------------------------------------------------####----------------- Running VCC-compiler failed, exit 1 VCL compilation failed```

Since the last Version ```Nexcessnet_Turpentine_Model_Varnish_Admin_Socket::_determineVersion($bannerText)``` trys to detrmine the version number even if the version number is correctly set via the backend configuration. The Implementation is not very *reliable*, at least on our server configration. Version 2.1 after detection, 3.0 wolud be correct:

Description:    Debian GNU/Linux 7.8 (wheezy)
Release:        7.8
Codename:       wheezy
Varnish: 3.0.2-2+deb7u1 

$bannerText contains:

```
-----------------------------
Varnish Cache CLI 1.0
-----------------------------
Linux,3.2.0-4-amd64,x86_64,-smalloc,-smalloc,-hcritbit

Type 'help' for command list.
Type 'quit' to close CLI session.
```

Suggestion: Determine the version only if the version needs to be determined and check the implementation ;).

**Comment by miguelbalparda** [comment]
Fixed on #915
