### ISSUE TITLE
ESI url is probably too long

### ISSUE THREAD

**Issue by BarryCarlyon** [nexcess/magento-turpentine#910]
I am seeing a *lot* of 

```TURPENTINE: ESI url is probably too long (MORETHAN2047 > 2047 characters)```

And I'm not sure what to make of it.

I'm also seeing a handful of bad session/form keys now and again possibly linked.

I'm digging but any thoughts Hive Mind?

**Comment by BarryCarlyon** [comment]
After some digging.

I have a registry key that contains a largish JSON encoded string, and it was tipping the hash hmac compression over the 2047 char limit.

Said registry key was in the ESI config to be passed to said ESI include

**Comment by aricwatson** [comment]
Glad you tracked it down! I'm going to close this issue, but let us know if you have any other questions.
