### ISSUE TITLE
Autodetect varnish 3.0 to 3.0.3 detects version 2.1

### ISSUE THREAD

**Issue by timmuller** [nexcess/magento-turpentine#918]
Currently, the varnish version is detected based on the varnish version in the banner, which varnish should print on connect.
https://github.com/nexcess/magento-turpentine/blob/master/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php#L353

Turpentine suggests in the comment of the code "Varnish before 3.0 does not spit out a version number".
Unfortunally, this feature is introduced of varnish version 3.0.4, and not of version 3.0.
This results in a VCL generate for varnish 2.1, which causes a VCL syntax error in version 3.0:

```
 * Stopping HTTP accelerator varnishd                                                                           [ OK ] 
 * Starting HTTP accelerator varnishd                                                                           [fail] 
Message from VCC-compiler:
Expected ';' got '"; "'
(program line 174), at
('input' Line 66 Pos 56)
set req.http.Cookie = req.http.X-Varnish-Faked-Session "; " req.http.Cookie;
-------------------------------------------------------####-----------------

Running VCC-compiler failed, exit 1

VCL compilation failed
```

Feature Introduced: https://github.com/varnish/Varnish-Cache/blob/varnish-3.0.4/bin/varnishd/mgt_cli.c#L83
Before: https://github.com/varnish/Varnish-Cache/blob/varnish-3.0.3/bin/varnishd/mgt_cli.c#L83

Ubuntu Precise and Debian are stil releasing varnish versions below 3.0.4:
Ubuntu Precise: 3.0.2-1ubuntu0.1
Debian: 3.0.2-2+deb7u1

Banner example 3.0 to 3.0.3
```
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
200 206     
-----------------------------
Varnish Cache CLI 1.0
-----------------------------
Linux,3.19.0-25-generic,x86_64,-smalloc,-smalloc,-hcritbit

Type 'help' for command list.
Type 'quit' to close CLI session.

```

```
> dpkg - l varnish
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                    Version                 Description
+++-=======================-=======================-==============================================================
ii  varnish                 3.0.2-1ubuntu0.1        state of the art, high-performance web accelerator
```

**Comment by miguelbalparda** [comment]
This should be fixed by #915, let me know if that works for you @timmuller

**Comment by allardhoeve** [comment]
Well. These are two seperate bugs.

1. Turpentine does not correctly identify Varnish on Debian Wheezy or Ubuntu 12.04 (LTS), which is stuck at Varnish 3.0.2.
2. Turpentine does not actually honor the dropdown if you manually select a version, because it always autodetects.

That autodetection works mostly, which hides bug number 2. That is what #914 fixes.

So, yes, you can work around #918 using the fix in #914, but is does not actually fix anything about this :smile:

**Comment by allardhoeve** [comment]
As a second strategy for autodetection, you could (if Varnish is set to 127.0.0.1) try to get the version directly from the `varnishd` binary:

```
# /usr/sbin/varnishd -V
varnishd (varnish-3.0.2 revision cbf1284)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2011 Varnish Software AS
```

**Comment by miguelbalparda** [comment]
Varnish is not always set to 127.0.0.1. For now the implementation will remain the same since #915 actually fixes your issue if the auto detection fails and the newest Varnish versions support the auto detection.

**Comment by allardhoeve** [comment]
Can you release a version that contains #915? Our customers will probably not install a version of Turpentine that is not available through Magento Connect :disappointed:

**Comment by miguelbalparda** [comment]
We will in a short time, we need to do some more testing in devel first. Anyway you can download it from here as a zip and cp the files.
