### ISSUE TITLE
source app/code/community/Nexcessnet/Turpentine/misc/uuid.c

### ISSUE THREAD

**Issue by craigcarnell** [nexcess/magento-turpentine#921]
This still get's left in the output when saving VCL (v4)

    # @source app/code/community/Nexcessnet/Turpentine/misc/uuid.c

**Comment by miguelbalparda** [comment]
It seems to have a # in front of it, that should not be a problem. Am I missing something here?

**Comment by craigcarnell** [comment]
@miguelbalparda On mine, it fails compilation

**Comment by miguelbalparda** [comment]
Can you try with a double # and see if that fixes the issue? If positive I will do the change in the VCL.

**Comment by miguelbalparda** [comment]
Did you tried the change @craigcarnell?

**Comment by craigcarnell** [comment]
Fixed in https://github.com/nexcess/magento-turpentine/pull/959
