### ISSUE TITLE
Grace Period - what is the best value?

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#926]
According to this article: https://www.lullabot.com/articles/configuring-varnish-for-highavailability-with-multiple-web-servers, a value of 6 hours can help your visitors in case Apache/Mysql services are down. Well, I stopped Apache and it was a pleasant surprise having Varnish set up. I can continue visiting my website.

1. I am working with latest dev version. Grace period is set up in seconds, by default is 15. What negative effects I can get if I will increase the value to a few hours?

2. Is it a good idea to cache the whole website for unexpected situation like a DDoS attack? How can I achieve that? There is a file named "warm-cache.sh" inside utils folder. Just copying it in Magento root and executing it will cache the whole website based on sitemap file?

3. I would like to ask you how Turpentine is warming the cache (there is an option in configuration area). What is exactly the result of this option.

Thank you.

**Comment by aricwatson** [comment]
1) I think the primary risk is overloading your memory by caching potentially stale content that might not even be used. If this is a live site, I'd suggest bumping up the grace period gradually and monitoring memory usage. [This link](http://serverfault.com/questions/54276/how-to-check-if-chosen-varnish-cache-size-is-ideal) might help.

2) This would depend on how much impact/load refreshing the cache creates for your site - vs the likelihood of it being needed. The warm-cache script reads URLs from the sitemap and visits them to warm the cache. By default the whole site is cached with Turpentine - *except* for blacklisted urls.

3) If you're referring to the crawler, it builds up a list of URLs to crawl, and then uses Magnto's cron system to crawl those URLs when a flush occurs. It's a pretty basic system, and there may be other extensions that are more useful for this task.

**Comment by ADDISON74** [comment]
Thank you for explanation.

**Comment by aricwatson** [comment]
No problem, let us know if you have any others!
