### ISSUE TITLE
Site crashes when applying Varnish config

### ISSUE THREAD

**Issue by xtremevision** [nexcess/magento-turpentine#927]
Hi,

I installed your latest module, and upgraded Varnish to v3.0.7 on Centos 6.6. I noticed that when I click on Apply Varnish Config, the site crashes. Restarting varnish service fixes the problem.

Any ideas what it could be? I am using the same setup on other sites and I am not having this issue. Applying varnish config works fine and the site does not crash.

Cheers,
Michael.

**Comment by miguelbalparda** [comment]
Have you seen any errors in the log files?

**Comment by xtremevision** [comment]
To be honest, no. Here's a screenshot of the messages log file, after I 
increased the cli_buffer to 65536 from 32768, and hit apply config.



... and this is the browser


On 9/7/2015 4:15 PM, Miguel Balparda wrote:
>
> Have you seen any errors in the log files?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nexcess/magento-turpentine/issues/927#issuecomment-138295184>.
>

-- 
Xtreme Vision Systems SRL
Str. Agatha Birsescu 11, Bl. V11 Sc. A, Et. 1, Ap. 7
Bucuresti, Sector 3
Tel: 021 335 0201
Reg Com: J40/23/03.01.2012
CUI: RO29505826

**Comment by xtremevision** [comment]
PS: Varnish is listening on port 80 on the public ips, nginx on port 80 
on 127.0.0.1 and php-fpm on 127.0.0.1:9000, if it helps...

On 9/7/2015 4:15 PM, Miguel Balparda wrote:
>
> Have you seen any errors in the log files?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nexcess/magento-turpentine/issues/927#issuecomment-138295184>.
>

-- 
Xtreme Vision Systems SRL
Str. Agatha Birsescu 11, Bl. V11 Sc. A, Et. 1, Ap. 7
Bucuresti, Sector 3
Tel: 021 335 0201
Reg Com: J40/23/03.01.2012
CUI: RO29505826

**Comment by miguelbalparda** [comment]
I can't see any images here. Nothing on Varnish logs?

**Comment by xtremevision** [comment]
Here's a copy/paste from the messages log:

Sep  7 16:23:12 localhost varnishd[18455]: CLI telnet 127.0.0.1 45105 
127.0.0.1 6082 Rd "auth" "*************"
Sep  7 16:23:12 localhost varnishd[18455]: CLI telnet 127.0.0.1 45105 
127.0.0.1 6082 Wr 200 -----------------------------#012Varnish Cache CLI 
1.0#012-----------------------------#012Linux,2.6.32-573.1.1.el6.x86_64,x86_64,-sfile,-smalloc,-hcritbit#012varnish-3.0.7 
revision f544cd8#012#012Type 'help' for command list.#012Type 'quit' to 
close CLI session.
Sep  7 16:23:12 localhost varnishd[18455]: CLI telnet 127.0.0.1 45105 
127.0.0.1 6082 Rd "param.show" "esi_syntax"
Sep  7 16:23:12 localhost varnishd[18455]: CLI telnet 127.0.0.1 45105 
127.0.0.1 6082 Wr 200 esi_syntax                  2 
[bitmap]#012                            Default is 
0#012                            Bitmap controlling ESI parsing 
code:#012                              0x00000001 - Don't check if it 
looks like XML#012                              0x00000002 - Ignore 
non-esi elements#012                              0x00000004 - Emit 
parsing debug records#012 0x00000008 - Force-split parser input#012 
(debugging)#012                            Use 0x notation and do the 
bitor in your head :-)
Sep  7 16:23:12 localhost varnishd[18455]: CLI telnet 127.0.0.1 45105 
127.0.0.1 6082 Rd "param.show" "cli_buffer"
Sep  7 16:23:12 localhost varnishd[18455]: CLI telnet 127.0.0.1 45105 
127.0.0.1 6082 Wr 200 cli_buffer                  65536 
[bytes]#012                            Default is 
8192#012                            Size of buffer for CLI 
input.#012                            You may need to increase this if 
you have big VCL#012                            files and use the 
vcl.inline CLI command.#012                            NB: Must be 
specified with -p to have effect.
Sep  7 16:23:12 localhost varnishd[18455]: CLI telnet 127.0.0.1 45105 
127.0.0.1 6082 Rd "vcl.inline" "***************" "C{\n#include 
<stdlib.h>\n#include <stdio.h>\n#include <time.h>\n#include 
<pthread.h>\nstatic pthread_mutex_t lrand_mutex = 
PTHREAD_MUTEX_INITIALIZER;\nvoid generate_uuid(char* buf) 
{\npthread_mutex_lock(&lrand_mutex);\nlong a = lrand48();\nlong b = 
lrand48();\nlong c = lrand48();\nlong d = 
lrand48();\npthread_mutex_unlock(&lrand_mutex);\nsprintf(buf, 
\"frontend=%08lx%04lx%04lx%04lx%04lx%08lx\",\na,\nb & 0xffff,\n(b & 
((long)0x0fff0000) >> 16) | 0x4000,\n(c & 0x0fff) | 0x8000,\n(c & 
(long)0xffff0000) >> 16,\nd\n);\nreturn;\n}\n}C\nimport std;\ndirector 
default round-robin {\n{\n.backend = {\n.host = \"127.0.0.1\";\n.port = 
\"8080\";\n.first_byte_timeout = 300s;\n.between_bytes_timeout = 
300s;\n}\n}\n}\ndirector admin round-robin {\n{\n.backend = {\n.host = 
\"127.0.0.1\";\n.port = \"8080\";\n.first_byte_timeout = 
21600s;\n.between_bytes_timeout = 21600s;\n}\n}\n}\nacl crawler_acl 
{\n\"127.0.0.1\";\n}\nacl debug_acl {\n}\n/* -- REMOVED\nsub 
generate_session {\nif (req.url ~ \".*[&?]SID=([^&]+).*\") {\nset 
req.http.X-Varnish-Faked-Session = regsub(\nreq.url, 
\".*[&?]SID=([^&]+).*\", \"frontend=\\1\");\n} else {\nC{\nchar uuid_buf 
[50];\ngenerate_uuid(uuid_buf);\nVRT_SetHdr(sp, 
HDR_REQ,\n\"\\030X-Varnish-Faked-Session:\",\nuuid_buf,\nvrt_magic_string_end\n);\n}C\n}\nif 
(req.http.Cookie) {\nstd.collect(req.http.Cookie);\nset req.http.Cookie 
= req.http.X-Varnish-Faked-Session +\n\"; \" + req.http.Cookie;\n} else 
{\nset req.http.Cookie = req.http.X-Varnish-Faked-Session;\n}\n}\nsub 
generate_session_expires {\nC{\ntime_t now = time(NULL);\nstruct tm 
now_tm = *gmtime(&now);\nnow_tm.tm_sec += 3600;\nmktime(&now_tm);\nchar 
date_buf [50];\nstrftime(date_buf, sizeof(date_buf)-1, \"%a, %d-%b-%Y 
%H:%M:%S %Z\", &now_tm);\nVRT_SetHdr(sp, 
HDR_RESP,\n\"\\031X-Varnish-Cookie-Expires:\",\ndate_buf,\nvrt_magic_string_end\n);\n}C\n}\n-- 
*/\nsub vcl_recv {\nif (req.restarts ==
Sep  7 16:23:12 localhost varnishd[18455]: CLI telnet 127.0.0.1 45105 
127.0.0.1 6082 Wr 200 VCL compiled.
Sep  7 16:23:13 localhost varnishd[18455]: CLI telnet 127.0.0.1 45105 
127.0.0.1 6082 Rd "vcl.use" "*******************"
Sep  7 16:23:13 localhost varnishd[18455]: CLI telnet 127.0.0.1 45105 
127.0.0.1 6082 Wr 200

... to me it looks like it fails to apply the vcl, it cuts off 
prematurely, unless I am totally wrong and the log message is truncted...
The browser shows this:


  Not Found

The requested URL 
/index.php/admin/cache/index/key/d92a569be1db391bb76f5e313e8b2be8/ was 
not found on this server.

------------------------------------------------------------------------
Apache/2.2.15 (CentOS) Server at www.bibliotecaeuropeana.ro Port 80




On 07/09/2015 19:34, Miguel Balparda wrote:
>
> I can't see any images here. Nothing on Varnish logs?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nexcess/magento-turpentine/issues/927#issuecomment-138336221>.
>

-- 
Michael Mussulis
CEO
*Xtreme Vision Systems SRL*
Str. Agatha Birsescu 11, Bl. V11,
Sc. A, Et. 1, Ap. 7, Sector 3
Bucuresti
Romania 031481
Tel: +40 (0)21 335 0205
CUI: RO29505826
Reg.Com.: J40/23/2012

**Comment by xtremevision** [comment]
Besides var/log/messages, are there any other logs I should check?

On 07/09/2015 19:34, Miguel Balparda wrote:
>
> I can't see any images here. Nothing on Varnish logs?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nexcess/magento-turpentine/issues/927#issuecomment-138336221>.
>

-- 
Michael Mussulis
CEO
*Xtreme Vision Systems SRL*
Str. Agatha Birsescu 11, Bl. V11,
Sc. A, Et. 1, Ap. 7, Sector 3
Bucuresti
Romania 031481
Tel: +40 (0)21 335 0205
CUI: RO29505826
Reg.Com.: J40/23/2012

**Comment by miguelbalparda** [comment]
Probably the Magento logs and turn on php error reporting to see why this is happening.

**Comment by miguelbalparda** [comment]
Do you have compilation enabled?

**Comment by xtremevision** [comment]
No. I will check the Magento and php-fpm logs tomorrow but I don't 
recall seeing anything relating to this...

On 08/09/2015 21:16, Miguel Balparda wrote:
>
> Do you have compilation enabled?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nexcess/magento-turpentine/issues/927#issuecomment-138654840>.
>

-- 
Michael Mussulis
CEO
*Xtreme Vision Systems SRL*
Str. Agatha Birsescu 11, Bl. V11,
Sc. A, Et. 1, Ap. 7, Sector 3
Bucuresti
Romania 031481
Tel: +40 (0)21 335 0205
CUI: RO29505826
Reg.Com.: J40/23/2012

**Comment by miguelbalparda** [comment]
Any news on this @xtremevision?

**Comment by xtremevision** [comment]
Sorry, was just too busy with projects. Holiday season and had lots of 
employees away... will try to look at it in the next couple days... 
Thanks, Mike.

On 9/15/2015 6:19 PM, Miguel Balparda wrote:
>
> Any news on this @xtremevision <https://github.com/xtremevision>?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nexcess/magento-turpentine/issues/927#issuecomment-140426525>.
>

-- 
Xtreme Vision Systems SRL
Str. Agatha Birsescu 11, Bl. V11 Sc. A, Et. 1, Ap. 7
Bucuresti, Sector 3
Tel: 021 335 0201
Reg Com: J40/23/03.01.2012
CUI: RO29505826

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.

**Comment by xtremevision** [comment]
Hi,

I installed the module on another server, another Magento install, and 
experience the same identical crash when applying the config.

Thanks,
Mike.

On 11/3/2015 1:18 PM, Miguel Balparda wrote:
>
> Closing for lack of feedback.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nexcess/magento-turpentine/issues/927#issuecomment-153320663>.
>

-- 
Xtreme Vision Systems SRL
Str. Agatha Birsescu 11, Bl. V11 Sc. A, Et. 1, Ap. 7
Bucuresti, Sector 3
Tel: 021 335 0201
Reg Com: J40/23/03.01.2012
CUI: RO29505826

**Comment by aricwatson** [comment]
Was this other server also running Varnish 3.0.7?

Can you let us know what parameters you're starting Varnish with (before trying to apply the Turpentine-generated VCL)?

**Comment by xtremevision** [comment]
Hi, on the first site I reported I had to upgrade to Varnish 4.x and 
your latest module to make it work. Now I don't have problem anymore. I 
will check the other site.

On 23/11/2015 21:10, Aric Watson wrote:
>
> Was this other server also running Varnish 3.0.7?
>
> Can you let us know what parameters you're starting Varnish with 
> (before trying to apply the Turpentine-generated VCL)?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nexcess/magento-turpentine/issues/927#issuecomment-159031064>.
>

-- 
Xtreme Vision Systems SRL
Str. Agatha Birsescu 11, Bl. V11 Sc. A, Et. 1, Ap. 7
Bucuresti, Sector 3
Tel: 021 335 0201 / 0721 052 013
Reg Com: J40/23/03.01.2012
CUI: RO29505826

**Comment by xtremevision** [comment]
I just tried the 2nd server and it crashed varnish big time. I had to go 
in via ssh and restart the service to get the site back up. See below 
requested info.

root@server [~]# rpm -qa | grep varn
varnish-libs-3.0.7-1.el6.x86_64
varnish-3.0.7-1.el6.x86_64

and the config is:

root@server [/etc/sysconfig]# cat varnish
# Configuration file for varnish
#
# /etc/init.d/varnish expects the variable $DAEMON_OPTS to be set from this
# shell script fragment.
#

# Maximum number of open files (for ulimit -n)
NFILES=131072

# Locked shared memory (for ulimit -l)
# Default log size is 82MB + header
MEMLOCK=82000

# Maximum number of threads (for ulimit -u)
NPROCS="unlimited"

# Maximum size of corefile (for ulimit -c). Default in Fedora is 0
# DAEMON_COREFILE_LIMIT="unlimited"

# Set this to 1 to make init script reload try to switch vcl without 
restart.
# To make this work, you need to set the following variables
# explicit: VARNISH_VCL_CONF, VARNISH_ADMIN_LISTEN_ADDRESS,
# VARNISH_ADMIN_LISTEN_PORT, VARNISH_SECRET_FILE, or in short,
# use Alternative 3, Advanced configuration, below
RELOAD_VCL=1

# This file contains 4 alternatives, please use only one.

## Alternative 1, Minimal configuration, no VCL
#
# Listen on port 6081, administration on localhost:6082, and forward to
# content server on localhost:8080.  Use a fixed-size cache file.
#
#DAEMON_OPTS="-a :6081 \
#             -T localhost:6082 \
#             -b localhost:8080 \
#             -u varnish -g varnish \
#             -s file,/var/lib/varnish/varnish_storage.bin,1G"


## Alternative 2, Configuration with VCL
#
# Listen on port 6081, administration on localhost:6082, and forward to
# one content server selected by the vcl file, based on the request.  Use a
# fixed-size cache file.
#
#DAEMON_OPTS="-a :6081 \
#             -T localhost:6082 \
#             -f /etc/varnish/default.vcl \
#             -u varnish -g varnish \
#             -S /etc/varnish/secret \
#             -s file,/var/lib/varnish/varnish_storage.bin,1G"


## Alternative 3, Advanced configuration
#
# See varnishd(1) for more information.
#
# # Main configuration file. You probably want to change it :)
VARNISH_VCL_CONF=/etc/varnish/default.vcl
#
# # Default address and port to bind to
# # Blank address means all IPv4 and IPv6 interfaces, otherwise specify
# # a host name, an IPv4 dotted quad, or an IPv6 address in brackets.
# VARNISH_LISTEN_ADDRESS=
VARNISH_LISTEN_PORT=80
#
# # Telnet admin interface listen address and port
VARNISH_ADMIN_LISTEN_ADDRESS=127.0.0.1
VARNISH_ADMIN_LISTEN_PORT=6082
#
# # Shared secret file for admin interface
VARNISH_SECRET_FILE=/etc/varnish/secret
#
# # The minimum number of worker threads to start
VARNISH_MIN_THREADS=50
#
# # The Maximum number of worker threads to start
VARNISH_MAX_THREADS=1000
#
# # Idle timeout for worker threads
VARNISH_THREAD_TIMEOUT=120
#
# # Cache file location
VARNISH_STORAGE_FILE=/var/lib/varnish/varnish_storage.bin
#
# # Cache file size: in bytes, optionally using k / M / G / T suffix,
# # or in percentage of available disk space using the % suffix.
VARNISH_STORAGE_SIZE=1G
#
# # Backend storage specification
VARNISH_STORAGE="file,${VARNISH_STORAGE_FILE},${VARNISH_STORAGE_SIZE}"
#
# # Default TTL used when the backend does not specify one
VARNISH_TTL=120
#
# # DAEMON_OPTS is used by the init script.  If you add or remove 
options, make
# # sure you update this section, too.
DAEMON_OPTS="-a ${VARNISH_LISTEN_ADDRESS}:${VARNISH_LISTEN_PORT} \
              -f ${VARNISH_VCL_CONF} \
              -T 
${VARNISH_ADMIN_LISTEN_ADDRESS}:${VARNISH_ADMIN_LISTEN_PORT} \
              -t ${VARNISH_TTL} \
              -w 
${VARNISH_MIN_THREADS},${VARNISH_MAX_THREADS},${VARNISH_THREAD_TIMEOUT} \
              -u varnish -g varnish \
              -S ${VARNISH_SECRET_FILE} \
              -s ${VARNISH_STORAGE} \
              -p cli_buffer=65536 \
              -p esi_syntax=0x2"
#


## Alternative 4, Do It Yourself. See varnishd(1) for more information.
#
# DAEMON_OPTS=""


On 23/11/2015 21:10, Aric Watson wrote:
>
> Was this other server also running Varnish 3.0.7?
>
> Can you let us know what parameters you're starting Varnish with 
> (before trying to apply the Turpentine-generated VCL)?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nexcess/magento-turpentine/issues/927#issuecomment-159031064>.
>

-- 
Xtreme Vision Systems SRL
Str. Agatha Birsescu 11, Bl. V11 Sc. A, Et. 1, Ap. 7
Bucuresti, Sector 3
Tel: 021 335 0201 / 0721 052 013
Reg Com: J40/23/03.01.2012
CUI: RO29505826

**Comment by matheuzzy** [comment]
Hi,

I receive this run-time error in varnish child proc:
If I disable cache ESI blocks, everyting it's OK

/var/log/messages:

Dec  5 19:24:51 test varnishd[12390]: Child (12851) died signal=6
Dec  5 19:24:51 test varnishd[12390]: Child (12851) Panic message:#012Assert error in VEP_Init(), cache/cache_esi_parse.c line 1039:#012  Condition((vep) != 0) not true.#012thread = (cache-worker)#012version = varnish-4.0.3 revision b8c4a34#012ident = Linux,2.6.32-042stab108.5,i686,-sfile,-smalloc,-hcritbit,epoll#012
Backtrace:#012  0x8082bae: /usr/sbin/varnishd() 
[0x8082bae]#012  0x8082f01: /usr/sbin/varnishd() 
[0x8082f01]#012  0x8064d69: /usr/sbin/varnishd(VEP_Init+0xe6) 
[0x8064d69]#012  0x806199b: /usr/sbin/varnishd(vfp_esi_gzip_pull+0x138) 
[0x806199b]#012  0x806c8a8: /usr/sbin/varnishd() 
[0x806c8a8]#012  0x806c939: /usr/sbin/varnishd() 
[0x806c939]#012  0x806cc7a: /usr/sbin/varnishd(VFP_Fetch_Body+0xf7) 
[0x806cc7a]#012  0x806a1a3: /usr/sbin/varnishd() 
[0x806a1a3]#012  0x806b907: /usr/sbin/varnishd() 
[0x806b907]#012  0x80860ab: /usr/sbin/varnishd(Pool_Work_Thread+0x457) 
[0x80860ab]#012  busyobj = 0x64c11018 {#012    ws = 0x64c11098 { OVERFLOW#012      id = ""o",#012      {s,f,r,e} = {0x64c128ec,+10028,(nil),+10028},#012    },#012  refcnt = 2#012  retries = 0#012  failed = 0#012  state = 1#012    is_do_esi#012    is_is_gzip#012    bodystatus = 3 (length),#012    },#012    http[bereq] = {#012      ws = 0x64c11098["o]#012        "GET",#012        "/",#012        "HTTP/1.1",#012   

I guess the issue it's about ESI processing + wrong backend headers about gzip content.
VEP_Init() here https://github.com/varnish/Varnish-Cache/blob/4.0/bin/varnishd/cache/cache_esi_parse.c#L1033

**Comment by matheuzzy** [comment]
The solution was to increase workspace_backend. I think is a general solution for Panic message Assert error in child proc. Please consider adding this to your FAQ

DAEMON_OPTS="-p workspace_backend=64k \
https://www.varnish-cache.org/trac/ticket/1739
https://www.varnish-software.com/book/4.0/chapters/Tuning.html#system-parameters

In my case this erros occurred when gzip was disabled, so the content was bigger and the default 16k was not enough.

**Comment by aricwatson** [comment]
Added to the FAQ - thanks for the info!

**Comment by xtremevision** [comment]
Hi,

I am still having this issue. I increased the workspace as suggested to 
64K and 128K and still have the same problem. These are the last lines 
from the message.log file, when trying to apply the config:

Apr  4 02:03:51 dinobebe varnishd[25247]: CLI telnet 127.0.0.1 46422 
127.0.0.1 6082 Wr 200 VCL compiled.
Apr  4 02:03:52 dinobebe varnishd[25247]: CLI telnet 127.0.0.1 46422 
127.0.0.1 6082 Rd "vcl.use" 
"9bd342698cc808a282fa512c7076463e243dd5ac7816d2b7ff6cb12e3c938f19"
Apr  4 02:03:52 dinobebe varnishd[25247]: CLI telnet 127.0.0.1 46422 
127.0.0.1 6082 Wr 200 VCL 
'9bd342698cc808a282fa512c7076463e243dd5ac7816d2b7ff6cb12e3c938f19' now 
active

and then Varnish crashes. Nothing works after that, until reload varnish 
service. Any ideas?

Cheers,
Michael.

On 09/12/2015 00:00, Aric Watson wrote:
>
> Closed #927 <https://github.com/nexcess/magento-turpentine/issues/927>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nexcess/magento-turpentine/issues/927#event-486201785>.
>

-- 
Xtreme Vision Systems SRL
Str. Agatha Birsescu 11, Bl. V11 Sc. A, Et. 1, Ap. 7
Bucuresti, Sector 3
Tel: 021 335 0201 / 0721 052 013
Reg Com: J40/23/03.01.2012
CUI: RO29505826

**Comment by matheuzzy** [comment]
Hello @xtremevision  !

My advice is to copy and paste the generated VCL from magento turpentine path to /etc/varnish/default.vcl and then reload varnish. This way you will see if the VCL is broken or the apply via CLI Telnet is truncated.

It's nice to apply VCL from backend on demand.. but what will happen after a server reboot or Varnish restart? you need to re-apply the VCL from the backend. So, I think it's better to modify VCL path in varnish config options OR to modify turpentine to generate the VCL in the /etc/varnish/default.vcl

**Comment by xtremevision** [comment]
Ok, I am officially declaring myself stupid or blind or whatever you 
want. Time to get new glasses. The problem was user error, i.e. me, 
having configured under caching options->backend port: 80 instead of 
8080..!!! I am a total idiot. Probably due to the many configs I played 
with, that setting simply slipped through my fingers.

Thank you all for all your help, and apologies for chasing a red herring!

Mike.

On 06/04/2016 18:27, Valentin Matei wrote:
>
> Hello @xtremevision <https://github.com/xtremevision> !
>
> My advice is to copy and paste the generated VCL from magento 
> turpentine path to /etc/varnish/default.vcl and then reload varnish. 
> This way you will see if the VCL is broken or the apply via CLI Telnet 
> is truncated.
>
> It's nice to apply VCL from backend on demand.. but what will happen 
> after a server reboot or Varnish restart? you need to re-apply the VCL 
> from the backend. So, I think it's better to modify VCL path in 
> varnish config options OR to modify turpentine to generate the VCL in 
> the /etc/varnish/default.vcl
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nexcess/magento-turpentine/issues/927#issuecomment-206427667>
>

-- 
Xtreme Vision Systems SRL
Str. Agatha Birsescu 11, Bl. V11 Sc. A, Et. 1, Ap. 7
Bucuresti, Sector 3
Tel: 021 335 0201 / 0721 052 013
Reg Com: J40/23/03.01.2012
CUI: RO29505826
