### ISSUE TITLE
Cannot apply VCL.

### ISSUE THREAD

**Issue by Dimtar** [nexcess/magento-turpentine#928]
Getting this error every time, also tried installing Varnish on a fresh box and trying that.

Failed to apply the VCL to 192.168.3.4:6082: Got unexpected response code from Varnish: 106 Message from VCC-compiler: directors are now in directors VMOD. ('input' Line 27 Pos 1) director default round-robin { ########---------------------- Running VCC-compiler failed, exited with 2 VCL compilation failed

Running 14.04, here is a snippet from /etc/default/varnish
`## Alternative 2, Configuration with VCL`
`#`
`# Listen on port 6081, administration on localhost:6082, and forward to`
`# one content server selected by the vcl file, based on the request.`
`# Use a 256MB memory based cache.`
`#`
`DAEMON_OPTS="-a :6081 \`
`             -T 192.168.3.4:6082 \`
`-p vcc_allow_inline_c=on \`
`-p cli_buffer=16384 \`
`             -f /etc/varnish/default.vcl \`
`             -S /etc/varnish/secret \`
`             -s malloc,256m"`

**Comment by thampe** [comment]
See #908 and #915

**Comment by miguelbalparda** [comment]
Probably a duplicated, let us know if #915 fixes your issue.
