### ISSUE TITLE
Invalidation of product availability

### ISSUE THREAD

**Issue by mikeschaekermann** [nexcess/magento-turpentine#929]
Hello, first of all, thank you for your awesome open-source contribution to the Magento realm.
We have started configuring our Magento+Turpentine+Varnish setup and I sucessfully created a hole-punch for a top-level block containing some tracking identification code which should never be cached at all. The block is defined and hole-punched as follows:

In some_module_layout.xml:

```
<?xml version="1.0"?>
<layouts>
    <default>
        <reference name="head">
            <block type="core/template" name="some_top_level_block" template="some_module/global_block.phtml" />
        </reference>
    </default>
    ...
</layout>
```

In local.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<layout>
    ...
    <default>
        <reference name="some_top_level_block">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <ttl>0</ttl>
                </params>
            </action>
        </reference>
    </default>
    ...
</layout>
```

As I said, the hole-punching for this block works perfectly fine. Another place where we intend to turn off caching is a block on the product page where we show the stock quantity of the item, selected, and an estimated delivery time. This block will always change if the item quantity of the parent product or of any of the other product variants changes. Therefore, we thought, the easiest way to hole-punch it would be to turn off caching for this block entirely. This is how it is defined and how we tried to hole-punch it:

In company_base.xml:

```
<?xml version="1.0"?>
<layout version="0.1.0">
    <PRODUCT_TYPE_simple>
        <reference name="product.info.addtocart">
            <block type="core/template" name="product.info.availability" as="product.info.availability" template="company_base/catalog/product/view/availability.phtml" />
        </reference>
    </PRODUCT_TYPE_simple>
    <PRODUCT_TYPE_configurable>
        <reference name="product.info.addtocart">
            <block type="core/template" name="product.info.availability" as="product.info.availability" template="company_base/catalog/product/view/availability.phtml" />
        </reference>
    </PRODUCT_TYPE_configurable>
    ...
</layout>
```

In app/design/frontend/package/theme/template/catalog/product/view/addtocart.phtml:

```
...
<?php echo $this->getChildHtml('product.info.availability'); ?>
<?php $this->unsetChild('product.info.availability');?>
...
```

In local.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<layout>
    ...
    <default>
        <reference name="product.info.availability">
            <action method="setEsiOptions">
                <params>
                    <access>public</access>
                    <ttl>0</ttl>
                </params>
            </action>
        </reference>
    </default>
    ...
</layout>
```

However, the hole-punching for this block does not seem to work properly. For example, we tried to output a random integer in the block HTML, and the first rendering after a cache flush contained a random number whereas all subsequent responses had cached this number.

My 2 questions would be:

1) Do we need to do any hole punching for blocks on the product page that need to update when the stock quantity of a product or its parent/siblings changes or is this handled automatically by the extension already?

2) If we need to do the hole-punching manually, what are we doing wrong with the above code? Did we miss anything obvious or is it truely complicated to achieve the desired behavior?

Thanks again for your great extension and contribution to the Magento community. We greatly appreciate your help!

Mike

**Comment by mikeschaekermann** [comment]
Okay, I was able to solve this issue by changing the ESI directive for hole-punching the product availability block from

```
<?xml version="1.0" encoding="UTF-8"?>
<layout>
    ...
    <default>
        <reference name="product.info.availability">
            <action method="setEsiOptions">
                <params>
                    <access>public</access>
                    <ttl>0</ttl>
                </params>
            </action>
        </reference>
    </default>
    ...
</layout>
```

to

```
<?xml version="1.0" encoding="UTF-8"?>
<layout>
    ...
    <PRODUCT_TYPE_configurable>
        <reference name="product.info.availability">
            <action method="setEsiOptions">
                <params>
                    <access>public</access>
                    <ttl>0</ttl>
                    <registry_keys>
                        <current_product/>
                    </registry_keys>
                </params>
            </action>
        </reference>
    </PRODUCT_TYPE_configurable>
    ...
</layout>
```

To cut a long story short, I changed the `<default>...</default>` to `<PRODUCT_TYPE_configurable>...</PRODUCT_TYPE_configurable>` and added the `current_product` registry key, needed by the block.

That solved the issue for me. Hope this might help other beginners, running into similar issues.

**Comment by miguelbalparda** [comment]
Thank you @mikeschaekermann!
