### ISSUE TITLE
Fatal Error when enabling Turpentine in Magento 1.9.1.1

### ISSUE THREAD

**Issue by thebrawnyman** [nexcess/magento-turpentine#931]
We installed Turpentine v0.6.5 thru Magento connect on our Magento 1.9.1.1 site. Installation appeared to complete successfully (though the extension does not show up in the 'Manage Existing Extensions' section of Magento Connect). The entire site now white screens, and I'm getting the following error in the logs

PHP Fatal error:  Call to a member function start() on a non-object in /var/www/html/includes/src/__default.php on line 14219

The line in question appears to be instantiating 'core/session'.

Disabling the extension by setting active = false in its /app/etc/modules/ xml file resolves the issue for now.

**Comment by miguelbalparda** [comment]
Disable the compilation in Magento, clear cache and try again.

**Comment by thebrawnyman** [comment]
Thanks, that resolves the issue for me.
