### ISSUE TITLE
SSL support with Varnish and turpentine

### ISSUE THREAD

**Issue by lijucorra** [nexcess/magento-turpentine#933]
We are using turpentine 0.6.0 and Varnish 3.0 on  our Magento server. We are currently looking for SSL support on Varnish cache.
Can we achieve this using turpentine 0.6.0 and Varnish 3.0?

Please advise.

**Comment by miguelbalparda** [comment]
What have you tried so far? Have you read the documentation? In theory it should be possible but there are better versions like Varnish 4 and a new Turpentine version with support for Varnish 4.

**Comment by lijucorra** [comment]
I have tried the method explained in URL https://github.com/nexcess/magento-turpentine/wiki/SSL_Support

We are using Nginx on 443 port and I have tried directing the 443 HTTPS web traffic to Varnish listening on 80 port. The issue that I am facing is Varnish is delivering HTTP pages for HTTPS request and we are getting mixed content issue on HTTPS page.

>>there are better versions like Varnish 4 and a new Turpentine version with support for Varnish 4.

Is this new turpentine version supports Varnish 3 with SSL support. Or do we specifically  use Varnish 4

**Comment by miguelbalparda** [comment]
Both varnish versions are supported in Turpentine, have you found a solution?

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.

**Comment by ADDISON74** [comment]
@lijucorra: use Pound instead of Nginx. You have all you need in that wiki page. I installed and it working as expected. do not forget to disable ssl module for apache in case you are using this webserver and the module is loaded. SSL offloading support is provided too.
