### ISSUE TITLE
Is Varnish 4 supported?

### ISSUE THREAD

**Issue by specialtactics** [nexcess/magento-turpentine#936]
Hi

In the documentation, it says to use Varnish under 4, and elsewhere it also says version 2.1+ and 3 are supported. Yet elsewhere again in the documentation (actually also on the same page as one of the above - https://github.com/nexcess/magento-turpentine/wiki/Installation ) there are configuration instructions for Varnish 4.

Can you please clarify whether Varnish 4 is supported or not?
I would be using 4.0.3 from CentOS 7 EPEL repository.

Thanks

**Comment by miguelbalparda** [comment]
We actually support Varnish 4, feel free to comment your experience or open an issue if you find any problem.
