### ISSUE TITLE
The famous <ul id="admin_messages">MESSAGE HERE</ul>

### ISSUE THREAD

**Issue by elfeffe** [nexcess/magento-turpentine#940]
I have Magento 1.9.1 and Turpentine 0.6.5, with Ultimo Theme.

And I have the same issue as some people had #112 #153. But that issues are from 2013, I don't believe they are not fixed yet.

When I post a review I get 

``` html
<ul id="admin_messages">MESSAGE HERE</ul>
```

Is there any way to fix this?
I don't have that error if I disable Turpentine.

My turpentine_esi.xml looks like

``` xml
 <reference name="global_messages">
            <action method="setEsiOptions">
                <params>
                <method>esi</method>
                    <access>private</access>
                    <flush_events>
                        <core_session_abstract_add_message/>
                    </flush_events>
                </params>
            </action>
        </reference>
    <reference name="messages">
            <action method="setEsiOptions">
                <params>
                <method>esi</method>
                <access>private</access>
                    <flush_events>
                        <core_session_abstract_add_message/>
                    </flush_events>
                </params>
            </action>
        </reference>
```

Any help will be really appretiated, I'm getting crazy with this.

**Comment by miguelbalparda** [comment]
I think the fix for this issue is in the devel branch. How did you get Turpentine? Can you please download the devel branch and see if the error persists?

**Comment by elfeffe** [comment]
Nope, I will explain. Ihave installed it using git, I have switched to devel branch now and.

1) with this
```xml
        <reference name="global_messages">
            <action method="setEsiOptions">
                <params>
                    <method>ajax</method>
                    <access>private</access>
                    <flush_events>
                        <core_session_abstract_add_message/>
                    </flush_events>
                    <only_cache_if>empty</only_cache_if>
                </params>
            </action>
        </reference>
        <reference name="messages">
            <action method="setEsiOptions">
                <params>
                    <method>ajax</method>
                    <access>private</access>
                    <flush_events>
                        <core_session_abstract_add_message/>
                    </flush_events>
                    <only_cache_if>empty</only_cache_if>
                </params>
            </action>
        </reference>
```
And this
![1232f17b3b6d83f0d53875a8713cec70](https://cloud.githubusercontent.com/assets/4717507/9816658/b4a2d13a-589e-11e5-98bc-87e21f66657a.png)

The block refreshes with ajax and creates this code
```html
<div class="col-main">
                        <!-- AJAX START [global_messages] -->
<div id="turpentine-esi-block-adcb2807a97f6084b951516cc1890a79b7339481fbdcdf10f65fafb6767fce9a"><ul id="admin_messages">Tu opinión ha sido aceptada y enviada para su revisión.</ul></div><!-- AJAX END [global_messages] -->
                        <div id="newsletterajax"></div>


<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice([]);
</script>
<div id="messages_product_view"><!-- AJAX START [messages] -->
<div id="turpentine-esi-block-59d82f41339ead2a8c2f6d7c21156b41f23f11c47d56b0013c11ff11bd74dd61"></div><!-- AJAX END [messages] -->
</div>
```
The HTML is wrong the generated message is
```html
<ul id="admin_messages">Tu opinión ha sido aceptada y enviada para su revisión.</ul>
```
2) If I leave the ESI xml using Ajax method, but I switch "Enable AJAX Flash Messages" to Disable
![4405d13864b684fafba7c1d50ad471e6](https://cloud.githubusercontent.com/assets/4717507/9816677/ccb973be-589e-11e5-922e-0723e0bd04d9.png)

The generated html is
```html
<ul class="messages"><li class="success-msg"><ul><li><span>Tu opinión ha sido aceptada y enviada para su revisión.</span></li></ul></li></ul>
```
Its ok, but the content is cached and there is no way to refresh it, everytime I visit the product, I get the message

3) If I switch method to ESI instead of AJAX, and I leave "Enable AJAX Flash Messages" as DISABLED, generated html is correct
```html
<ul class="messages"><li class="success-msg"><ul><li><span>Tu opinión ha sido aceptada y enviada para su revisión.</span></li></ul></li></ul>
```
But, again, I see the message everytime. It never refreshes
I tried changing to

```xml
    <reference name="global_messages">
            <action method="setEsiOptions">
                <params>
                    <method>esi</method>
                    <access>private</access>
                    <flush_events>
                        <core_session_abstract_add_message/>
                    </flush_events>
                    <only_cache_if>no_text</only_cache_if>
                </params>
            </action>
        </reference>
        <reference name="messages">
            <action method="setEsiOptions">
                <params>
                    <method>esi</method>
                    <access>private</access>
                    <flush_events>
                        <core_session_abstract_add_message/>
                    </flush_events>
                    <only_cache_if>no_text</only_cache_if>
                </params>
            </action>
        </reference>
```
Note the change in "only_cache_if" section
But nothing, it never refreshes.
I also tried applying
```xml
<ttl>0</ttl>
```
But the cache never refreshes

It only refreshes cache if you set method to AJAX and Enable AJAX Flash Messages, but it returns incorrect HTMl as in master branch.

**Comment by elfeffe** [comment]
One more
When I enable "Enable AJAX Flash Messages"
It makes 2 AJAX request, I think this is wrong too

http://turp.mystore.com/turpentine/esi/getBlock/method/ajax/access/private/ttl/0/hmac/136908b62efd256395b258e47b8f2318d50e93667f06c16cf77ec140cdb604e9/data/OruN-OAv5qzlHicSQy6ePG7mXTcckjJ0bGyvvwyaHMoTl4S..EEwWXPZN8c9WXkyS8QDD-NEPzFc6HlUF4X93m9ysn1ee127EV5onMJnIkMZXiBW58tfIIybuWJ1TNHAptCjKRM.pZUtrYAR6fISqwZKM7aRMNpPpgScuwsaG7f3VE1A8RG9JGJEpHLorfBtSDNPD-CJ.WPY0FX.4FbFocOLdxzxzSZuYGdGpuUFT8sb3SRpkrJiAgYz-itTnKhEB5FRsb2nmxZnvXxuqRc8bTJ1LLtSdo2TfwORgRWMZ5Qv0XR0AEJQw7ya60Lep.K0XOQNnZFFLx.BKBqvk8eXgFK9vLLUcCHNjZljwZbEFdatEAi3.kLwn92pwt1KFqTJ/

and

http://turp.mystore.com/turpentine/esi/getBlock/method/ajax/access/private/ttl/0/hmac/521e143667c0fa6a536386043060c38da947d3e8db1251470b5d5317db028ede/data/YGwxWb0J0Zi3siC8PKWLBo9HboyjNqqnW.JBg96le2lGVe0EkwizPth8wjDon-f04r.wTcrlqCcdL5IycAkkl9wLzElEEWdSfmPBp1EK5Pz3EiEXsYHwuTng64TSIBMo9W.Op55gJqy4WVutlMG1-Uaq4DLTyRawmaAEAs1KCyWySATAXGN85z.K15zd5N9aCzO9dSEQsrkdsd9rbV71x7mHimhW-mVQe3A2DIDklI5SpRHb86LAEtq0CoDnkLcIiHUf2M50Pigi8unltrqQzmb9Jk.AKk4cPfoVUXehxjMEseZ5wBp3sObPezSQy2Eztu9gzWBA2SGiouzUVxGHBp.PfDU5tzG3a9fqKGqJg5PJ9DdD2HbbKw==/

I think only one is needed

**Comment by elfeffe** [comment]
I discovered that when you load messages block using ESI instead of AJAX, the Turpentine Nexcessnet_Turpentine_Block_Core_Messages class is not running.
It runs only if AJAX is enabled.
And AJAX works good, but just return wrong HTML
```html
 <ul id="admin_messages">MESSAGE HERE</ul>
```

**Comment by elfeffe** [comment]
@miguelbalparda sorry Miguel, just to know. Is there any fix or any plan to fix it?
The extension can't be used with this bug, am I the only one with this problem?

**Comment by miguelbalparda** [comment]
We work hard to fix all the issues. It seems to be you are the only one experiencing this issue for now, so I wouldn’t say the extension can't be used.

**Comment by elfeffe** [comment]
Ok, I only want to know if it's only me the one with the problem.

**Comment by elvin-vaimo** [comment]
Nope, you aren't the only one. getting same.

**Comment by aricwatson** [comment]
Try adding another flush event to clear the cache when new products are added:

```
<reference name="global_messages">
            <action method="setEsiOptions">
                <params>
                    <method>esi</method>
                    <access>private</access>
                    <flush_events>
                        <core_session_abstract_add_message/>
                        <controller_action_predispatch_checkout_cart_add />
                    </flush_events>
                    <only_cache_if>no_text</only_cache_if>
                </params>
            </action>
        </reference>
        <reference name="messages">
            <action method="setEsiOptions">
                <params>
                    <method>esi</method>
                    <access>private</access>
                    <flush_events>
                        <core_session_abstract_add_message/>
                        <controller_action_predispatch_checkout_cart_add />
                    </flush_events>
                    <only_cache_if>no_text</only_cache_if>
                </params>
            </action>
        </reference>
```

Additionally, do you know steps to replicate this on default install/theme?

**Comment by elvin-vaimo** [comment]
Actually this is core bug

```diff
--- app/code/core/Mage/Core/Block/Messages-o.php	2015-10-13 20:35:25.000000000 +0000
+++ app/code/core/Mage/Core/Block/Messages.php	2015-10-13 20:40:49.000000000 +0000
@@ -213,7 +213,7 @@
         $html = '<' . $this->_messagesFirstLevelTagName . ' id="admin_messages">';
         foreach ($this->getMessages($type) as $message) {
             $html.= '<' . $this->_messagesSecondLevelTagName . ' class="'.$message->getType().'-msg">'
-                . ($this->_escapeMessageFlag) ? $this->escapeHtml($message->getText()) : $message->getText()
+                . ($this->_escapeMessageFlag ? $this->escapeHtml($message->getText()) : $message->getText())
                 . '</' . $this->_messagesSecondLevelTagName . '>';
         }
         $html .= '</' . $this->_messagesFirstLevelTagName . '>';
```

**Comment by Desmaster** [comment]
Having the same issues..
The messages get added, but they're cached. And nothing seems to flush the block.

The following I tried:

```xml     
<reference name="global_messages">
    <action method="setEsiOptions">
        <params>
            <access>private</access>
            <ttl>1</ttl>
            <method>esi</method>
            <scope>page</scope>
            <flush_events>
                <controller_action_predispatch/>
            </flush_events>
        </params>
    </action>
</reference>

<reference name="messages">
    <action method="setEsiOptions">
        <params>
            <access>private</access>
            <ttl>1</ttl>
            <method>esi</method>
            <scope>page</scope>
            <flush_events>
                <controller_action_predispatch/>
            </flush_events>
        </params>
    </action>
</reference>

- Flush events
- Setting TTL to 1 
- The core bug fix

**Comment by ADDISON74** [comment]
I got this issue on orders and returns page. The error message related to the form fill in was without magento css style. I checked the source code and the ul tag you encountered id admin message is there. If varnish disabled the error message is styled. Checking the source code other ul tag is now inserted.

**Comment by Desmaster** [comment]
I got my messages working! This is what I did.

From the docs I quote: 
> Only blocks that inherit from the `Mage_Core_Block_Template` class may have caching policies.

Since neither the block `Mage_Core_Block_Messages` or `Nexcessnet_Turpentine_Block_Core_Messages` inherit from `Mage_Core_Block_Template`, **no** caching policies exist/work for the blocks. 

But, we want to define caching policies though. We want it to be dynamic, so we need some wrapper around it. The solution:

**In my local.xml**
```xml
<default>
    <reference name="root">
        <action method="unsetChild">
            <name>global_messages</name>
        </action>
        <action method="unsetChild">
            <name>messages</name>
        </action>
        <block type="core/template" name="message_wrapper" as="message_wrapper" template="custom/message-wrapper.phtml">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <scope>page</scope>
                    <ttl>0</ttl>
                </params>
            </action>
            <block type="core/messages" name="global_messages" as="global_messages"/>
            <block type="core/messages" name="messages" as="messages"/>
        </block>
    </reference>
</default>
```

**And in my custom/message-wrapper.phtml**
```phtml
<div class="messages-wrapper">
    <?php
        echo $this->getChildHtml('global_messages');
        echo $this->getChildHtml('messages');
    ?>
</div>
```

**Comment by ADDISON74** [comment]
@Desmaster your solution is not working for me. I placed local.xml in my theme layout folder, then custom/message-wrapper.phtml in template. I flushed the cache, restarted varnish, none worked.

Could you please give more details about file locations and changes?

**Comment by Desmaster** [comment]
Make sure you output the defined block in the root templates(`page/1column.phtml` etc) like this: `echo $this->getChildHtml()` and het rid of the messages output that's in the root templates already.

**Comment by ADDISON74** [comment]
@Desmaster. I followed all your steps and I could not fix it. 

1) I created inside /app/design/frontend/default/mytheme/layout/local.xml with your suggested content.

2) I created inside /app/design/frontend/default/mytheme/template/custom/message-wrapper.phtml with your suggested content.

3) I edited /app/design/frontend/default/mytheme/template/page/1 column.phtml as follows:

```php
<div class="col-xs-12">
    <div class="main">
    <?php echo $this->getChildHtml('breadcrumbs') ?>
        <div class="col-main">
            <div class="padding-s">
            <?php echo $this->getChildHtml('global_messages') ?>
            <?php echo $this->getChildHtml('content') ?>
            </div>
        </div>
    </div>
</div>
```

In line 51 <?php echo $this->getChildHtml('global_messages') ?> I replaced <strong>global_messages</strong> with <strong>message_wrapper</strong>. I flushed the cache and restarted Varnish but there is no positive result, same behavior. To find out if this is the right template file I commented the whole line 51 and the message is not appearing, so this was the right template for editing.

I am getting this issue in "Orders and Returns" page here is a screenshot:

![admin_message](https://cloud.githubusercontent.com/assets/8360474/12719793/f0c98498-c8ff-11e5-90f9-071b5e334c6e.jpg)

**Comment by ADDISON74** [comment]
@elvin-vaimo was right. I've made that change in Magento core files and here is the result:

![admin_message2](https://cloud.githubusercontent.com/assets/8360474/12725058/78cbb33e-c919-11e5-843c-bb8cfa0394c1.jpg)

Even it is an error message its class it is "admin_messages" instead of "messages". See how the containers are bonded together. Do a test with login form. You will get this html tag for an error:

```html
<ul class="messages">
    <li class="error-msg">
        <ul><li><span>Invalid login or password.</span></li></ul>
    </li>
</ul>
```

I would like to know as @elvin-vaimo " why Turpentine uses "admin_messages" container and when Turpentine is off then this is not being used".

**Comment by elfeffe** [comment]
@miguelbalparda Sorry to bother you Miguel, but you can see I'm not the onlyone with this problem

**Comment by npearson72** [comment]
+1

Also having this issue

**Comment by aricwatson** [comment]
I'd like to take a look at this. Can anyone give me steps to replicate on a default store? I'd like to rule out that it's theme-specific.

**Comment by ADDISON74** [comment]
Check my posts.

**Comment by geminpak** [comment]
@ADDISON74 Hello, was wondering what changes you made to Magento's core files in order to correctly display the error messages? I am currently looking at Messages.php in the core files.

**Comment by ADDISON74** [comment]
Check this one: https://github.com/nexcess/magento-turpentine/issues/940#issuecomment-150329176

For the moment it is like a bandage. It is not a proper solution, a more elegant one should come from Turpentine module.

**Comment by yoosefi** [comment]
We had the same problem and found that messages were being stashed in `core/session` instead of `customer/session`. Putting them in `customer/session` resolved the issue for us.

Hope that helps anyone.

**Comment by treestonemedia** [comment]
+1
Also having this issue

**Comment by norgeindian** [comment]
We face the same issue when a customer subscribes for the newsletter in our footer.

The message is not displayed like a usual magento success message, but as an admin_message.
During our debugging we ended up at  `Nexcessnet_Turpentine_Block_Core_Messages::_real_toHtml()`
This function is called in `Nexcessnet_Turpentine_Block_Core_Messages::_toHtml()` and decides, if the function getHtml or getGroupedHtml shall be called, depending on the name in layout. 

 And here is the thing, we do not really understand. Disabling turpentine one can see, that usually `Mage_Core_Block_Messages::_toHtml()` always calls `getGroupedHtml().`

Does anyone have an idea, why this decision is implemented the way it is?

**Comment by elvinristi** [comment]
@norgeindian , see https://github.com/nexcess/magento-turpentine/issues/940#issuecomment-150329176 to fix the core bug there on M1.

**Comment by norgeindian** [comment]
@elvinristi , thanks for the hint, but did not work for me. Faced the same issue.
And the question remains, why turpentine calls this function, if the usual way would be getGroupedHtml()

**Comment by miguelbalparda** [comment]
Am not really sure why this was coded like this, what would be a better way to do it?

**Comment by norgeindian** [comment]
@aheadley , as far as I can see it was you who wrote most of the code in these functions. Could you explain the reasons for that?
In my local tests everything works fine, when _real_toHtml just calls getGroupedHtml in every case, but maybe there are issues I don't see right now.

**Comment by miguelbalparda** [comment]
There is a proposed fix for this in https://github.com/nexcess/magento-turpentine/pull/1508, care to check and report back?

**Comment by norgeindian** [comment]
If you could include this fix, this would be great and in my eyes we could then close this issue.
