### ISSUE TITLE
___SID=U issue reloaded

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#941]
Important: Please do not close this issue again. I am offering all details and proof this issue exists!

Here is the link for the website. It is a test environment we have in project: http://94.176.2.184/

All are installed from scratch:
1) Magento 1.9.2.1
2) Magento sample 1.9.1.0
3) Apache 2.22, PHP 5.5, MySQL 5.6, Varnish 3.0.7
4) Turpentine - dev branch
5) No changes in settings or adding any extensions
6) The store has 3 languages available, it is a Magento default. 

I will not restart any service for you in the next hours. Right now the issue is present, I checked it with different browsers from different locations (different OS's - Windows and Linux). Same behavior. 

Please check as following:

1) Some categories got in their link the string ___SID=U (at the end), others not.

2) Some links in footer are affected too. See how the string ___SID=U is going in a wrong place in Company column, they are not at the end. This causes when you click on the to get the home page.

This is for category. See the address bar, status bar:

![category](https://cloud.githubusercontent.com/assets/8360474/9815948/8791e524-58a2-11e5-9707-d761182494f5.jpg)

This is for a link in footer (Company column). See where the string ___SID=U is placed (it should be at the end, but it is in the middle of the URL):

![about_us](https://cloud.githubusercontent.com/assets/8360474/9815963/a054192e-58a2-11e5-86a4-ebc533757319.jpg)

This if for a link same in the footer (Quick Link column). This time the string ___SID=U is placed at the end of the URL:

![sitemap](https://cloud.githubusercontent.com/assets/8360474/9815990/d01aa704-58a2-11e5-931a-c3a7bef5ab80.jpg)

**Comment by miguelbalparda** [comment]
This issue is a duplicated, please keep all the info in a single issue. Use #909 for future reference.
