### ISSUE TITLE
Turpentine removes header block

### ISSUE THREAD

**Issue by dhpowrhost** [nexcess/magento-turpentine#946]
I am new to varnish and turpentine, but i have set up a test site: http://tapetforum.powr.host/ to get to know it. I use the generated vcl on my varnish box, but it seems varnish removes the header block. How can i make it not remove the header block? I am using Magento 1.9.2.1 and turpentine 0.6.5 and Varnish 3

The Footer works fine. I have enabled debugging so you can see the tags in source..

**Comment by miguelbalparda** [comment]
What have you tried so far? I think there are some related issues, have you checked the open and closed issues?

**Comment by dhpowrhost** [comment]
I have tried upgrading to varnish4. The same issue occurs. It is strange that it is only header that does not work since footer works even if it is private. I have tried adding dummy blocks </head> but that does not work either.

**Comment by dhpowrhost** [comment]
I have checked open issues, but they seems to be related to earlier versions, or am i wrong?

**Comment by aricwatson** [comment]
The header does appear to be showing up when I go to http://tapetforum.powr.host/

Did you find a fix?

**Comment by dhpowrhost** [comment]
aricwatson> Actually i just edited turpentine_esi.xml so that the header is cached. Then i editet the local.xml for the template so that cart_sidebar was not cached. But when i do that the cart_sidebar block is not loaded. Look at the source: the cart_sidebar esi block is empty as header was empty. I dont understand it. Why is the block empty?

**Comment by aricwatson** [comment]
I see - what ESI settings did you use for the cart_sidebar block? What are you seeing in the logs?

**Comment by dhpowrhost** [comment]
The settings are:
<action method="setEsiOptions"> <params> <access>private</access> <flush_events>
<wishlist_item_save_after/> <wishlist_item_delete_after/>
<sales_quote_save_after/> </flush_events> </params> </action>


And the logs says esi block cart_sidebar injected

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=7.2.9&pv=5.1.1] On ons., sep. 16, 2015 at 4:59 PM, Aric Watson < notifications@github.com [notifications@github.com] > wrote:
I see - what ESI settings did you use for the cart_sidebar block? What are you
seeing in the logs?

—
Reply to this email directly or view it on GitHub
[https://github.com/nexcess/magento-turpentine/issues/946#issuecomment-140767042] .[https://github.com/notifications/beacon/ALLE3a1XmDI81JXvc1J6uFHs4uvdq6Wyks5oyXrTgaJpZM4F9dp6.gif]

**Comment by dhpowrhost** [comment]
Would it make a difference to use

<registry_keys>
<current_category/>
<registry_keys>

Also cart_sidebar is still active in turpentine_esi.xml


On ons., sep. 16, 2015 at 4:59 PM, Aric Watson < notifications@github.com [notifications@github.com] > wrote:
I see - what ESI settings did you use for the cart_sidebar block? What are you
seeing in the logs?

—
Reply to this email directly or view it on GitHub
[https://github.com/nexcess/magento-turpentine/issues/946#issuecomment-140767042] .[https://github.com/notifications/beacon/ALLE3a1XmDI81JXvc1J6uFHs4uvdq6Wyks5oyXrTgaJpZM4F9dp6.gif]

**Comment by ADDISON74** [comment]
Sidebar block for cart is an open issue already. I did the same thing as you did above but it won't work. 

@aricwatson for Recently Viewed and Recently Compared you extended some classes. I guess this cart bar needs the same thing.

**Comment by aricwatson** [comment]
@dhpowrhost I just took a look at your site and it appears the header and cart blocks are working. It appears that you're setting ESI policies only for the header. Is it working correctly now?

**Comment by dhpowrhost** [comment]
aricwatson. I just tried to apply the default theme to se how that worked, and as you can see it works better..

**Comment by aricwatson** [comment]
Closing for lack of feedback, let us know if you're still having problems.

**Comment by dhpowrhost** [comment]
I am still having this issue. I dont understand.. It seems i am getting a 500 response on the esi header block..

http://tapetforum.powr.host
