### ISSUE TITLE
Caching Options config crashes.

### ISSUE THREAD

**Issue by studio2f** [nexcess/magento-turpentine#947]
Previously I was running Turpentine 0.6.4 without issue. I just upgraded to 0.6.6 on a Magento 1.9.2.1 store. When navigating to System > Configuration > TURPENTINE Caching Options the page crashes and returns:

*Fatal error: Class 'Mage_Extendedvarnish_Helper_Data' not found in /home/mysite/public_html/app/Mage.php on line 547*

Of course caches have been cleared and indexes re-indexed post upgrade. Varnish (& turpentine) appear to be running fine. I am able to change System > Configuration > TURPENTINE Varnish Options without any problems.  Anyone have an idea what's wrong? Thanks in advance.

**Comment by miguelbalparda** [comment]
Mage_Extendedvarnish_Helper_Data seems to be pointing to a module called Extendedvarnish. Any chance you have something like that installed? From your Magento root folder you can run find . | xargs grep 'Extendedvarnish' -sl and see if you can find anything to start debugging this issue.

**Comment by studio2f** [comment]
That did it. I found the problem and fixed it. Thanks so much @miguelbalparda
