### ISSUE TITLE
Cart not empty after logout

### ISSUE THREAD

**Issue by Nuranto** [nexcess/magento-turpentine#949]
Cart is not empty after logout.
If I purge frontend cookies, cart goes empty.
After logout, frontend value change.
Thing is, there is 2 frontend cookies... Probably the cause, but why ? We use a different domain to serve assets, and a cookie is created for this domain, it should'nt... I don't understand the option "Normalize Cookie Regex" and "Normalized Cookie Target", but may be it is the solution ? If so, it would be interesting to rewrite the comment in an understandable way :)

(Mage 1.8.1 / Turpentine 0.6.6)

Thanks for your work guys.

**Comment by miguelbalparda** [comment]
When you say "a cookie is created for this domain, it should'nt" why do you think this is a problem caused by Varnish/Turpentine?

**Comment by miguelbalparda** [comment]
@Nuranto any feedback on this?

**Comment by Nuranto** [comment]
Sorry...
I will try to test this without Varnish/turpentine to be sure....

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.

**Comment by Nuranto** [comment]
(Sorry, I forgot to update this issue : It was not related to turpentine...)
