### ISSUE TITLE
Faster without varnish?

### ISSUE THREAD

**Issue by studio2f** [nexcess/magento-turpentine#950]
I'm a bit of a neophyte, so please bare with me if I'm interpreting this wrong, but as far as I can tell Varnish w/turpentine is actually slower than my server without it at all. Uncached requests serve faster than cached hits. Any idea how to diagnosis why this would be happening?

![varnishhist outpu](https://dl.dropboxusercontent.com/u/8230194/varnish.png)

Thanks in advance.

**Comment by miguelbalparda** [comment]
Have you seen #902?

**Comment by studio2f** [comment]
@miguelbalparda thanks for your help (yet again!). My apologies-- like I said I'm a bit of a noob here.

My varnishhist example wasn't generated by a siege attack. These are real users creating real sessions and browsing my store. I believe the cache was fully warmed. 

Is the idea that ESI should be disabled?

**Comment by miguelbalparda** [comment]
I wouldn’t say ESI should be disabled. varnishhist is new to me, I have never used it before. I don't quite understand the image you are showing us, can you elaborate the issue with some more info?

**Comment by studio2f** [comment]
(#) represents non-cache hits (|) represents cache hits.

The x-axis scale is response time. Left is faster responses than the right. Cache hits should be on the left (faster). Non-cache hits on the right. 

What I'm seeing (shown above) is backwards. Non-cache hits are processed and served in .001 seconds (1e-3) and cached hits are served slower in 1 second (1e0). Varnish is processing requests slower than the server processes on it's own. Varnish w/turpentine is actually slower than my server without it at all.

More info:
http://www.uptimemadeeasy.com/monitoring/all-you-really-need-to-know-about-varnishhist/

**Comment by miguelbalparda** [comment]
Weird stuff. Are you sure Varnish is correctly configured or even being hit at all? I can understand the graph but it doesn't make sense at all since Varnish should be in front of apache and serve cached resources only without even asking apache. You can check what happens if you stop apache and leave varnish running, it should serve some pages for a while.

**Comment by studio2f** [comment]
The excellent folks @crucialwebhost explained to me what’s happening. We use Cloudflare. Varnishhist isn't accurately showing what's happening with our server (or varnish) because Cloudflare is handling many if not most of our hits before they even get to varnish. Disable Cloudflare and Varnishhist displays a much more accurate picture on how varnish is preforming.
