### ISSUE TITLE
How to correctly remove ESI options set in turpentine_esi.xml

### ISSUE THREAD

**Issue by rossmc** [nexcess/magento-turpentine#951]
I'm wondering what is the best practice to remove the ESI options set in `turpentine_esi.xml`?

To give some context I found that after I installed the turpentine module & got it working with Varnish, my dynamic cart my header was not working, it was displaying the default Magento topcart and not the one from our theme.

While debugging the issue I found if I removed the below code block from `turpentine_esi.xml` my dynamic cart started working properly, correctly holding the number for cart items for each user.

    <reference name="cart_sidebar">
        <action method="setEsiOptions">
            <params>
                <access>private</access>
                <flush_events>
                    <sales_quote_save_after/>
                </flush_events>
            </params>
        </action>
    </reference>

I believe that as the our theme's topcart is defined in the `header` this is why it continued to work after removing the above code, infact when I removed the header esi options set in `turpentine_esi.xml` I could see that my dynamic cart broke, not holding the correct number of items for each user.

So my question is how do I remove the `cart_sidebar` block from `turpentine_esi.xml` without deleting it from that file?  Can I put something in my own layout `local.xml` which would remove it so I can maintain upgrade-ability?

**Comment by aricwatson** [comment]
I'm actually working up a way to do this via config in local.xml, will hopefully merge it into devel today or tomorrow.

**Comment by aricwatson** [comment]
I've just merged https://github.com/nexcess/magento-turpentine/pull/970 which allows you to override the settings in turpentine_esi.xml via your local.xml config:

```
 <reference name="header">
    <action method="setEsiOptions">
        <params>
            <disableEsiInjection>1</disableEsiInjection>
        </params>
    </action>
</reference>
```

Unless problems pop up, this will be in the next update of master!

**Comment by ADDISON74** [comment]
This is a great solution. Is it included in Wiki?

**Comment by aricwatson** [comment]
Thanks - I will update the docs once it's live in the master branch.

**Comment by rossmc** [comment]
Thanks @aricwatson, nice work

**Comment by aricwatson** [comment]
This has been added to the wiki.
