### ISSUE TITLE
Missing "Caching Options" page content from latest dev branch

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#953]
A few moments ago I set up a VM having Debian 8, Varnish 4 (from varnish repo), Magento 1.9.2.1/Magento 1.9 Sample.

I downloaded the latest Turpentine dev branch (updated 3 days ago) for testing @craigcarnell addition related to maintenance page. Well, in backend "Caching Options" section/page is completely empty. I cleared the cache on disk, I restarted apache and varnish, same result. Could you please check if this page is in the package? It is so strange it never happened to me.

Edit: I downloaded the master branch, I deleted all Turpentine's traces, I installed the master version. Caching Options page is as it should be (Backend, Normalization Options, TTLs, ...), not empty.

**Comment by miguelbalparda** [comment]
Unable to reproduce with the latest devel branch.

**Comment by ADDISON74** [comment]
Did you evaluate this issue starting from scratch?
