### ISSUE TITLE
Warming Cache script needs a check

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#954]
I added a sitemap for a Magento 1.9.2.1/Magento Sample 1.9.1.0, and I generated in magento root. I checked the content and there are a lot of positions for categories, products and CMS pages.

I restarted varnish service and apache to get all from zero. I am trying to use warm-cache.sh script. I run ./warm-cache.sh http://IP_ADDRESS/sitemap.xml and here is the message:

Getting URLs from sitemap...
Warming 0 URLs using 4 processes...

As you can see there are no URLs warmed up by this script. I visited the website in categories and it moves like I am touching every link for the first time. X-VarnishHit 1 after reloading the visited page.

In my opinion this script is not doing its job. Please not I have only one website which needs one sitemap.

**Comment by mosesdinakaran** [comment]
How many urls are there in your sitemap XML

**Comment by ADDISON74** [comment]
Not many. It is a Magento 1921 with Magento Sample 1.9.1.

**Comment by ADDISON74** [comment]
Here is the sitemap.xml file content saved in Magento root directory: 

<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>http://192.168.159.100/women/new-arrivals.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/women/tops-blouses.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/women/pants-denim.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/women/dresses-skirts.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/men/new-arrivals.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/men/shirts.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/men/tees-knits-and-polos.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/men/pants-denim.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/accessories/eyewear.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/accessories/jewelry.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/accessories/shoes.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/accessories/bags-luggage.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/home-decor/books-music.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/home-decor/bed-bath.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/home-decor/electronics.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/home-decor/decorative-accents.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/sale/women.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/sale/men.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/sale/accessories.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/sale/home-decor.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/women.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/men/blazers.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/men.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/accessories.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/home-decor.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/sale.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/vip.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.5</priority></url><url><loc>http://192.168.159.100/aviator-sunglasses.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/jackie-o-round-sunglasses.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/retro-chic-eyeglasses.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/isla-crossbody-handbag.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/florentine-satchel-handbag.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/leather-tablet-sleeve.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/flapover-briefcase.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/rolls-travel-wallet.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/roller-suitcase.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/body-wash-with-lemon-flower-extract-and-aloe-vera.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/bath-minerals-and-salt.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/shea-enfused-hydrating-body-lotion.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/titian-raw-silk-pillow.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/shay-printed-pillow.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/carnegie-alpaca-throw.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/park-row-throw.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/gramercy-throw.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/herald-glass-vase.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/stone-salt-and-pepper-shakers.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/fragrance-diffuser-reeds.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/geometric-candle-holders.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/madison-lx2200.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/madison-rx3400.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/16gb-memory-card.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/8gb-memory-card.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/large-camera-bag.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/madison-earbuds.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/madison-overear-headphones.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/madison-8gb-digital-media-player.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/compact-mp3-player.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/french-cuff-cotton-twill-oxford-578.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/slim-fit-dobby-oxford-shirt-580.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/plaid-cotton-shirt-582.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/oxford-sport-coat-480.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/linen-blazer-590.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/stretch-cotton-blazer-592.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/chelsea-tee-735.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/chelsea-tee-736.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/chelsea-tee-737.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/merino-v-neck-pullover-sweater-566.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/lexington-cardigan-sweater-571.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/core-striped-sport-shirt-555.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/bowery-chino-pants-551.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/the-essential-boot-cut-jean-553.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/flat-front-trouser-554.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/nolita-cami-596.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/tori-tank-595.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/delancy-cardigan-sweater-597.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/ludlow-oxford-top-599.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/elizabeth-knit-top-601.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/essex-pencil-skirt-537.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/racer-back-maxi-dress-613.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/ludlow-sheath-dress.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/lafayette-convertible-dress.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/tribeca-skinny-jean.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/dumbo-boyfriend-jean.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/park-avenue-pleat-front-trousers-683.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/barclay-d-orsay-pump-nude.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/borgha-ankle-boot-556.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/hana-flat-charcoal-557.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/dorian-preforated-oxford-558.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/wingtip-cognac-oxford-559.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/suede-loafer-navy-560.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/classic-hardshell-suitcase-589.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/modern-murray-ceramic-vase-484.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/luggage-set.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/vase-set.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/3-year-warranty.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/5-year-warranty.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/camera-travel-set.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/mp3-player-with-audio.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/pillow-and-throw-set.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/a-tale-of-two-cities.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/alice-in-wonderland.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/khaki-bowery-chino-pants.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/pearl-strand-necklace.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/blue-horizons-bracelets.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/pearl-stud-earrings.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/swing-time-earrings.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/silver-desert-necklace.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/swiss-movement-sports-watch.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/pearl-necklace-set-test.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/around-the-world-in-80-days.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/falling-by-i-am-not-lefthanded.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/if-you-were-by-keshco.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/can-t-stop-it-by-shearer.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/love-is-an-eternal-lie-by-the-sleeping-tree.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/fire-kalima-remix-by-unannounced-guest.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/madison-island-vip-membership-1-year.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/broadway-pump.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/ellis-flat.html</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url><url><loc>http://192.168.159.100/home</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.2</priority></url><url><loc>http://192.168.159.100/about-magento-demo-store</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.2</priority></url><url><loc>http://192.168.159.100/customer-service</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.2</priority></url><url><loc>http://192.168.159.100/enable-cookies</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.2</priority></url><url><loc>http://192.168.159.100/privacy-policy-cookie-restriction-mode</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.2</priority></url><url><loc>http://192.168.159.100/service-unavailable</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.2</priority></url><url><loc>http://192.168.159.100/private-sales</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.2</priority></url><url><loc>http://192.168.159.100/reward-points</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.2</priority></url><url><loc>http://192.168.159.100/company</loc><lastmod>2015-10-05</lastmod><changefreq>daily</changefreq><priority>0.2</priority></url></urlset>

As you can see there are a lot of URL's which should be warm-up. If I run 

./warm-cache.sh http://192.168.159.100/sitemap.xml

I get the following message: 

Getting URLs from sitemap...
Warming 0 URLs using 2 processes...

warm-up script is not working at all it needs a revised. I visited some links from sitemap.xml. All have Hits 1 instead of 2. The page is taking for the first time hundreds of miliseconds, the second visit only 45 ms, now it is warmed up.

**Comment by Fel1xx** [comment]
@ADDISON74 Hi. As for my experience this usually happens if you don't have the 'xpath' CLI tool installed. Not sure about your distro, but in debian/ubuntu it is in package 'libxml-xpath-perl'. Hope that helps.

**Comment by ADDISON74** [comment]
Thank you for your suggestion. It is a Debian 7.9 distribution. I installed "libxml-xpath-perl" package, but it is not improving anything. Executing warm-cache.sh it gives me the same message:

Getting URLs from sitemap...
Warming 0 URLs using 2 processes...

As you can see warming URLs is zero which is bad. Any suggestions?

**Comment by ADDISON74** [comment]
IT WORKED on other distribution I installed from scratch. I guess it was a package missing or something. Now using "./warm-cache.sh http//IP_ADDRESS/sitemap.xml", I get the following nice seeing result:

Getting URLs from sitemap...
Warming 127 URLs using 2 processes...

@aricwatson: could you please insert this information in your wiki related to warming cache using that script file? For Debian/Ubuntu distributions libxml-xpath-perl package must be installed.

Thank you @Fel1xx for your help. This issue can be CLOSED.

**Comment by ADDISON74** [comment]
QUESTION: 

I warmed up the cache using this script. A number of 127 URLS are now in cache (according to the result message I got from this script). 

Why visiting the website I am not getting the warmed up pages? For the first time the time load is long then it is very short (Varnish working). Why the warming URLs have no positive effect? Hit is 1, it should be 2 if I am visiting a page after warming the cache.

**Comment by aricwatson** [comment]
Couple issues - first, if you're going to a cached page but with a new session, the request will be passed through varnish in order to get a good session. The 2nd request should be fast.

Second, the caching script is warming the cache for *public* pages and ESI blocks. Blocks that are cached *privately* will *not* be warmed, as those must be per-session. So even if it's not the first request - if you head to page that has several private ESI blocks, there will still be some work being done outside Varnish to generate content for those private ESI blocks, which will then be cached for later use in that session.

**Comment by ADDISON74** [comment]
In this moment based on your answer I will not use warm script anymore. As I understood Turpentine has its own internal mechanism for warming the cache. Thank you.
