### ISSUE TITLE
First Request is never cached 

### ISSUE THREAD

**Issue by thampe** [nexcess/magento-turpentine#957]
Hi,

every new request without a frontend cookie can be not cached.

Relevant snippet from ``version-3.vcl``:  

    # no frontend cookie was sent to us AND this is not an ESI or AJAX call
    if (req.http.Cookie !~ "frontend=" && !req.http.X-Varnish-Esi-Method) {
        if (client.ip ~ crawler_acl ||
                req.http.User-Agent ~ "^(?:{{crawler_user_agent_regex}})$") {
            # it's a crawler, give it a fake cookie
            set req.http.Cookie = "frontend=crawler-session";
        } else {
            # it's a real user, make up a new session for them
            {{generate_session}}# call generate_session;
            return (pipe);
        }
    }

Since the last two versions (``0.6.5`` and ``0.6.6``) when no frontend-cookie is present the request goes straight to the backend server (``return (pipe)``). This a bit of a problem for our shop, since most first requests go to a  page where a *vaild* form_key and CSFR protection is not really necessary, but a fast page load is.

As always thanks for your help.

**Comment by craigcarnell** [comment]
@thampe Was going to look into this. I've noticed a jump in first page load time too

**Comment by ADDISON74** [comment]
I confirm this issue. Even the cache is warmed by other visitors, always the first time page visit takes a lot of time to load.

**Comment by craigcarnell** [comment]
I think this is because return pipe should only be the case if session generation is turned off in varnish

**Comment by craigcarnell** [comment]
https://github.com/nexcess/magento-turpentine/pull/959

**Comment by miguelbalparda** [comment]
Have you seen #924 @thampe @craigcarnell @ADDISON74?

**Comment by thampe** [comment]
Yes I have seen the issue, I think @craigcarnell solution (#959) is smarter and fits better for certain setups. Most pages have a seo-freindly url and can not be matched reliably with a reg-ex.

**Comment by miguelbalparda** [comment]
Merged, feel free to try this in devel and please let us know if you find any issues.
