### ISSUE TITLE
Can you add ESI cache policies to a template file?  Trying to fix ajax wishlist.

### ISSUE THREAD

**Issue by rossmc** [nexcess/magento-turpentine#962]
Is it possible to add ESI cache policies to a Magento phtml template file?  

To expand on why I ask, on our store we're using the [VS_Ajax module](http://www.magentocommerce.com/magento-connect/vs-ajax-add-to-cart-add-to-wishlist-add-to-compare-paging-toolbar.html) which doesn't play nice with turpentine.

With this module the mark up for the add to wishlist button on the product and category listings pange is changed, and has a different form key depending on the users logged in.  If varnish cache's the page before a user logs in, a logged in customer will be instructed to that they need to  log in before they add a product to the wish list, or vice versa.

For instnace the mark up with the Ajax wishlist turned on is:

    <a href="#" onclick="ajaxWishlist("http://our-domain.com/wishlist/index/add/product/242/form_key/WXLqGQuMFGOglelc/","242";);return false;" class="link-wishlist">

And with it turned off, it's:

    <a href="http://our-domain.com/wishlist/index/add/product/413/form_key/LNjeYewcIfZ5ZvYi/" class="link-wishlist">

The PHP responsible for this code is:
        
	<?php $i=1; foreach ($_productCollection as $_product): ?>
		
		<?php if(Mage::getStoreConfig('ajax/wishlistcompare/enabledpro')){?>
			<ul class="add-to-links">
				<?php if ($this->helper('wishlist')->isAllow() and $wishlist) : ?>
					<li><a href="#" onclick='ajaxWishlist("<?php echo str_replace($http[0], $http[1], $this->helper('wishlist')->getAddUrl($_product)); ?>","<?php echo $_product->getId()?>");return false;' class="link-wishlist"><?php echo MAGE::helper('ThemeOptionsBlacknwhite')->getIcon('wishlist'); ?><span id='ajax_wishlist_loading<?php echo $_product->getId()?>' class="ajax-loader-item" style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>' alt="" /></span></a></li>
				<?php endif; ?>
				<?php if($_compareUrl=$this->getAddToCompareUrl($_product) and $compareproducts): ?>
					<li><span class="separator">|</span> <a href="#" onclick='ajaxCompare("<?php echo str_replace($http[0], $http[1], $_compareUrl); ?>","<?php echo $_product->getId()?>");return false;' class="link-compare"><?php echo MAGE::helper('ThemeOptionsBlacknwhite')->getIcon('compare'); ?><span id='ajax_loading<?php echo $_product->getId()?>' class="ajax-loader-item" style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>' alt="" /></span></a></li>
				<?php endif; ?>
			</ul>
		<?php }else{?>
			<ul class="add-to-links">
				<?php if ($this->helper('wishlist')->isAllow() and $wishlist) : ?>
					<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo MAGE::helper('ThemeOptionsBlacknwhite')->getIcon('wishlist'); ?></a></li>
				<?php endif; ?>
				<?php if($_compareUrl=$this->getAddToCompareUrl($_product) and $compareproducts): ?>
					<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo MAGE::helper('ThemeOptionsBlacknwhite')->getIcon('compare'); ?></a></li>
				<?php endif; ?>
			</ul>
		<?php } ?>
		
	<?php $i++; endforeach ?>

I tried putting this PHP into a `block` with a layout update with the esi caching policy:

    <catalog_category_default>
        <reference name="product_list">
            <block type='catalog/product_list' name='wishlist_compare' template='ajax/catalog/wishlist-compare.phtml'>
            	    <action method="setEsiOptions">
				        <params>
				            <access>private</access>
				        </params>
				    </action>
            </block>
        </reference>
    </catalog_category_default>

But this wouldn't work as the PHP code is in a loop `foreach` so I can't grab data such as `$_product` in my new `wishlist_compare` block.

It would be much easier if I could just add the ESI cache policy to the template?  Is this possible?  Any other solutions welcome.

**Comment by rossmc** [comment]
I'm wondering if this would make any difference after all.  If it is possible to set an esi policy in the template file would it work as the php code in question is in a foreach loop, can varnish handle that?

**Comment by aricwatson** [comment]
I don't believe setting the policies would work in a template file. You might have better luck setting a policy on the block that contains all these products (the parent block), and setting *that* for private caching - i. If you run into problems with the ajax part, I'd suggest trying to blacklist the URLs that the ajax code is using.
