### ISSUE TITLE
403 forbidden error in header caused by logged in customers

### ISSUE THREAD

**Issue by rossmc** [nexcess/magento-turpentine#963]
I've encountered an issue with varnish when a logged in user visits a page that has not been cached the resulting html page given back to them has a **403 Forbidden nginx/1.4.6 (Ubuntu)** error in the header section of the page, where the logo, navbar are etc.

![capture](https://cloud.githubusercontent.com/assets/2452991/10098350/9caa7f3a-6378-11e5-962f-20d762cbdb37.JPG)

There is nothing in my turpentine error log but there is in my NGINX error log:

	$ sudo cat /var/log/nginx/error.log
	2015/09/25 10:21:47 [error] 6883#0: *9127 access forbidden by rule, client: 127.0.0.1, server: staging.example.ie, request: "GET /turpentine/esi/getBlock/method/esi/access/private/ttl/7200/hmac/792b5a0b692e443b333d05c67da46b43b2894112a529bc9d491ee1ae6587d643/data/.9SNe-3SWNx-0DG1igFbueN2iD6oX0Px5UAy8UKa6aJeS6iGeL-QzDW518ZNfFbSx.UCkgmgsQudLS-7Yw7xlvFq8dRYYHyzvSnedsQr-SIdjJOc6qPPCZDz.thRPlO55ZbfrbyajL10WOM9hY.sW0aISLHNaMh-zKoxa3coOgK.RaVwdxwDQNko-kLgBFCpCi5dlKjeqtwCnbCtxaVlUS5TxWUlMj0x8SwmG3TAsj-dZ6wPu-IqERrZCfx12HzY2EXV4tP04qlcGsvrgKYt91dE-10NL15A2zICMeISM9JCzX-W8n9nyEVGxdedFpDUKBvqM7O3-cTzHs-3ZKCagKOSudNe3eiBaHBFX2yf.vWAlc-E0fr6-NsPuwoHxwCQcdTjC22n4z0Cab8Y5IQI09bAYZXVH0bUOsOVG7n7utY=/ HTTP/1.1", host: "staging.example.ie", referrer: "http://staging.example.ie/kiddies-scarf"

The issue temporarily goes away when I clear the cache but can then occur again later.  Any thoughts on how I can fix this or even just turn off the Varnish cache for product pages as I would be happy to have it on just the Homepage & Category pages.

**Comment by miguelbalparda** [comment]
Have you tried #924?

**Comment by rossmc** [comment]
@miguelbalparda, I've read through them but I'm not sure which method I should try, I don't really understand the problem being described there.

Do you mean updating the VCL as suggested by the poster or from the solution your recommended, [846](https://github.com/nexcess/magento-turpentine/pull/846).

Also do you know if there is a way to disable caching on product pages for the time being?

Thanks

**Comment by miguelbalparda** [comment]
Sorry, I meant #942. Let me know if that helped.

**Comment by rossmc** [comment]
@miguelbalparda how do I download that branch?  I don't see how to select the [#942 ceckoslab:devel](https://github.com/nexcess/magento-turpentine/pull/942) branch on the [main github page for turpentine](https://github.com/nexcess/magento-turpentine).  Sorry if that's a NOOB question.

What is that code doing?  Am I right  in thinking if I put *catalog/product/view* into the *guest caching blacklist*, none of the product pages will be served from varnish cache, regardless of the user being signed in or or not?

**Comment by miguelbalparda** [comment]
1. git clone -b ceckoslab-devel devel https://github.com/ceckoslab/magento-turpentine.git
2. Yes. You should modify the patch to suit your needs.
Please let me know if this worked, we are gathering feedback about #942 to merge it to our devel branch.

**Comment by rossmc** [comment]
Thanks, will keep you posted

**Comment by rossmc** [comment]
@miguelbalparda that git clone command did not work, see below.  I alswo tried cloning the master branch to try and checkout ceckoslab's branch but it was not there ??

Downloads:$ git clone -b ceckoslab-devel https://github.com/ceckoslab/magento-turpentine.git
	Cloning into 'magento-turpentine'...
	fatal: Remote branch ceckoslab-devel not found in upstream origin
	Unexpected end of command stream

	Downloads:$ git clone https://github.com/nexcess/magento-turpentine.git
	Cloning into 'magento-turpentine'...
	remote: Counting objects: 7546, done.
	remote: Compressing objects: 100% (39/39), done.
	remote: Total 7546 (delta 17), reused 0 (delta 0), pack-reused 7492
	Receiving objects: 100% (7546/7546), 1.57 MiB | 693.00 KiB/s, done.
	Resolving deltas: 100% (2423/2423), done.
	Checking connectivity... done.
	Downloads$ cd magento-turpentine/
	magento-turpentine: (master)$ git status
	On branch master
	Your branch is up-to-date with 'origin/master'.

	nothing to commit, working directory clean
	magento-turpentine: (master)$ git branch 
	* master
	magento-turpentine: (master)$ git branch -av
	* master                                                         f89ae64 Merge pull request #934 from nexcess/devel
	  remotes/origin/HEAD                                            -> origin/master
	  remotes/origin/Strategery-Inc-damian/cache-management-extended c04d4a6 refs #817 fixed merge conflicts
	  remotes/origin/devel                                           835c671 Merge pull request #959 from craigcarnell/bugfix/generate-session
	  remotes/origin/devel-varnish4                                  c8b2c29 Merge branch 'devel' into devel-varnish4
	  remotes/origin/feature-better-1.8-compat                       2d9a452 better decision making for esi form key vs real form key
	  remotes/origin/feature-varnish-future-compat                   feacc72 update v4 vcl
	  remotes/origin/fix-1.8-compat                                  c1b9917 implement fix based on @EvrijnSD workaround
	  remotes/origin/fix-fpm-headers                                 1eb78b7 add fix for fpm duplicate content-type header responses
	  remotes/origin/fix-litespeed-esi                               37c6b5f add possible fix for litespeed esi issues to v3 vcl
	  remotes/origin/master                                          f89ae64 Merge pull request #934 from nexcess/devel
	  remotes/origin/merge-187                                       b85b57b rework #187 changes
	  remotes/origin/patch-kount-compatibility                       bb3b3cb fix compatiblity with kount extension
	magento-turpentine: (master)$

**Comment by rossmc** [comment]
@miguelbalparda I've noticed that if I remove the `store` cookie from the browser the issue does not occur anymore but then I have the issue that a logged in customer cannot be in the correct store for them.

**Comment by miguelbalparda** [comment]
The correct command is git clone -b devel https://github.com/ceckoslab/magento-turpentine.git, sorry about that.

**Comment by rossmc** [comment]
@miguelbalparda no problem I'll try it now,  what do you think could be causing the issue, the store cookie seems to be causing it somehow.

I also tried creating a custom_include.vcl with the below but to no avail.

    sub vcl_fetch {
        if (beresp.status >= 400) {
            return (hit_for_pass);
        }
    }

**Comment by rossmc** [comment]
@miguelbalparda I've tested the ceckoslab branch and while it removes the 403 error with it I loose the `store` cookie so all customers see prices without VAT/Sales Tax, whereas customers from europe should see the prices with tax so the `store` cookie is needed.

**Comment by rossmc** [comment]
I got varnish to ignore all URLs ending with a `.html` by adding `.*.html$` to the URL Blacklist setting in the Magento admin at System > Configuration > Turpentine > Caching Options under URL-based caching.

It's not ideal but at least Varnish is working for my homepage & Catalog listings pages and I no longer have a 403 error!

**Comment by miguelbalparda** [comment]
I'll close the issue for now, if you ever find something different or someone else faces this we will reopen it. Also please let us know if you find some issues using the code #942.

**Comment by rossmc** [comment]
@miguelbalparda feedback on #942, it does not work on multi-store setups, the store cookie is lost with varnish on.

**Comment by obukhow** [comment]
I had the same issue. The reason is for some ESI-holes "data" parameter in the URL starts with a dot symbol. I.e. 

`http://example.com/turpentine/esi/getBlock/method/esi/access/private/ttl/0/hmac/123/data/.qGPQ0YixsP3bFHr`

And most nginx configs contain the following rule

```
location ~ /\. { deny all; }
```

That rule intended to protect hidden files from download via direct link. So nginx decides we trying to get hidden file which starts with a dot symbol and denies access.

**Comment by MWilkinson** [comment]
Just a suggestion - but in the Helper/Data.php file, the 2 functions urlBase64Encode/urlBase64Decode substitute / for . and + for -
It appears that it's the / for . substitution causing the issue, how about changing it for a / to _ character to work around this issue ?

**Comment by sebastianwahn** [comment]
Still facing this issue.

I am also having URLs containig a dot `39d9/data/.Q-OwjhJ6` (only the relevant part).
Also, the nginx config has the entry with:
```
location ~ /\. { deny all; }
```

If i remove the `deny all;` it works fine. 

I suggest that you translate the "/" in a different sign like mentioned in the previous comment.
