### ISSUE TITLE
Failed on save Configuration

### ISSUE THREAD

**Issue by peterhomburg** [nexcess/magento-turpentine#966]
Hi,

if i try to save the configuration in Backend it ends with message:

Failed to apply the VCL to 127.0.0.1:6082: Got unexpected response code from Varnish: 106 Message from VCC-compiler: Syntax error in condition, expected '(', '!' or variable name, found 'true' (input Line 151 Pos 5) if (true && req.url ~ "[?&](utm_source|utm_medium|utm_campaign|utm_content|utm_term|gclid|cx|ie|cof|siteurl)=") { ----####--------------------------------------------------------------------------------------------------------- Running VCC-compiler failed, exit 1 VCL compilation failed

I take a look in the generated VCL and find in line 151:

if (true && req.url ~ "[?&](utm_source|utm_medium|utm_campaign|utm_content|utm_term|gclid|cx|ie|cof|siteurl)=") {

I have installed Varnish 2.1.5 on CentOS 6.4

If varnish 4 is installed (on myVM) the generated VCL looks like:

if (req.url ~ "[?&](utm_source|utm_medium|utm_campaign|gclid|cx|ie|cof|siteurl)=") {

without 'true'

Do you have any idea?

Best Wishes

peter

**Comment by ADDISON74** [comment]
use only Varnish 3 or 4. set up a VM for testing.

did you follow correctly every step in installation? 
https://github.com/nexcess/magento-turpentine/wiki/Installation

check my posts into this issue #948.

**Comment by miguelbalparda** [comment]
I saw his error appearing when the correct version of varnish is not selected in the admin. Which version of turpentine are you using? Are you seeing the same error after selecting the correct version in Turpentine admin panel?

**Comment by aricwatson** [comment]
Agreed - I'd suggest using Varnish 3 or 4.

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.
