### ISSUE TITLE
ESI config. question: addtocart popup displaying several times

### ISSUE THREAD

**Issue by m-overlund** [nexcess/magento-turpentine#973]
I'm using a module which fires a popup, after adding a product to the cart.
Normally the popup only fires once, but when varnish is activated it fires several times.

The modules checks for core/session ( https://github.com/clerkio/clerk-magento/blob/master/design/template/powerpopup.phtml ):

    Mage::getSingleton('core/session')->getProductAddedToCartFlag(true)

And i've tried to set the following ESI options to prevent it from displaying several times:

```
			<action method="setEsiOptions">
				<params>
					<access>private</access>
					<flush_events>
						<sales_quote_save_after/>
						<checkout_cart_product_add_after/>
						<checkout_cart_update_items_after/>
						<checkout_cart_product_update_after/>
					</flush_events>
				</params>
			</action>
```

Do i need to set additional settings, like registry keys or others?

**Comment by m-overlund** [comment]
Magento is set to not go to checkout/cart after a product is added to cart, so i think the issue is that the block doesn't get flushed before the customer goes to the cart.

But how do i flush the cache after the product is added, when the customers stays on the product-list or product-view?

**Comment by aricwatson** [comment]
This is a tricky one because what I suspect you'd want to happen is for the ajax script that's being called to actually clear the cache when it handles adding a product to the cart. How to do that in the third-party module is the tricky part I suspect. Perhaps you can figure out what blocks it's using and add the same flush events for those blocks?

**Comment by m-overlund** [comment]
@aricwatson it's not a ajax script - the popup just shows after page reload by the standard add to cart method.

I've tried to use dispatchEvent to create an event after the popup has loaded, and setting ESI to flush on that event, but that doesn't seem to work.

Tried using ajax as method too, but then it doesn't load at all.

Isn't it the right way to do it?

(If i set ttl to 0, it works as expected.)

**Comment by aricwatson** [comment]
Apologies, somehow I thought it was doing an ajax call to add the product to the cart w/out leaving the product list/view. I see the problem - if you put a flush event on the product list/view pages, you'll be flushing cache quite a bit! I'll see if we can come up with any other options.

**Comment by aricwatson** [comment]
It just occurred to me that you might benefit by setting `<only_cache_if>empty</only_cache_if>` for the pop-up block ... if you haven't already resolved the problem.
