### ISSUE TITLE
All ESI calls are 302 redirected after session user agent validation activation

### ISSUE THREAD

**Issue by ramzy11** [nexcess/magento-turpentine#975]
Hi,

When activating the user agent validation in sessions, and when switching to another user agent, all calls of esi blocks are redirected 302 ?

Any help please ?

Thanks

**Comment by miguelbalparda** [comment]
Can you add some more info @ramzy11? Logs, code, server/software specs, anything you consider related.

**Comment by ramzy11** [comment]
Hi @miguelbalparda 

Thaks for your reply here's some extra informations

We are running a Magento EE 1.12 behind a Varnish 3
The website pages contains several ESI blocks (private/ etc.. / )
Content is loaded from varnish, ESI blocks are correctly processes then cached..

The problem is that when i change my browser's user agent, none of the ESI blocks gets rendered (blanks in stead)
In my Apache logs i can see the esi blocks calls, but with 302 redirections.

we did some debuging and we tracked it down to session validation :
With user_agent session validation enabled, Magento throws an exception here : 

in app/code/core/Mage/Core/Model/Session/Abstract/Varien.php:340
public function validate()
{
    if (!isset($this->_data[self::VALIDATOR_KEY])) {
        $this->_data[self::VALIDATOR_KEY] = $this->getValidatorData();
    }
    else {
        if (!$this->_validate()) {
            $this->getCookie()->delete(session_name());
            // throw core session exception
            throw new Mage_Core_Model_Session_Exception('');
        }
    }

    return $this;
}

and all ESI requests gets 302 redirected.

**Comment by aricwatson** [comment]
Apologies, I haven't had a chance to look closely at this yet - however I wonder if the issue is that you are changing the user agent on an active session, which is causing the validation issue?

**Comment by aricwatson** [comment]
Closing for lack of feedback. Let us know if you're still experiencing problems and we'll gladly reopen!
