### ISSUE TITLE
Varnish 4.0.3 C-Compiler failed: error: no previous prototype for ‘generate_uuid’

### ISSUE THREAD

**Issue by RaunoVV** [nexcess/magento-turpentine#976]
Hi,

I have built Varnish 4.0.3 from source on OpenSuse 12.1 and when trying to run it with Turpentine generated config it fails to start with error:

Message from C-compiler:
./vcl.dIi0L05v.c:896:6: error: no previous prototype for ‘generate_uuid’ [-Werror=missing-prototypes]
cc1: all warnings being treated as errors

Running C-compiler failed, exited with 1

VCL compilation failed

I'm running varnish with these options:
-a :8080 -T localhost:6082 -u varnish -g varnish -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m -p syslog_cli_traffic=off -p thread_pools=4 -p thread_pool_max=1500 -p max_restarts=6 -p cli_buffer=16384 -p feature=+esi_ignore_other_elements -p vcc_allow_inline_c=on -p connect_timeout=300

Any ideas?

P.S Didn't find any related issues.

Regards,
Rauno

**Comment by aricwatson** [comment]
Can you post your Turpentine generated config you're trying to use?

**Comment by RaunoVV** [comment]
It's here http://pastebin.com/DVbTA2xN

**Comment by aricwatson** [comment]
I've was able to load that VCL with no errors generated (varnish-4.0.3 revision b8c4a34).

Looking at your error messages more closely, it sounds like perhaps your varnish was compiled such that it treats warnings as errors - `cc1: all warnings being treated as errors`. Can you try recompiling without this option?

**Comment by RaunoVV** [comment]
Hum, didn't use any specific options while building. So this shouldn't be a problem. For temporary fix i deleted the first part of Inlince-c code and now the vcl complies, but how important that part of code is?

Removed this part:
C{
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <pthread.h>
static pthread_mutex_t lrand_mutex = PTHREAD_MUTEX_INITIALIZER;
void generate_uuid(char* buf) {
pthread_mutex_lock(&lrand_mutex);
long a = lrand48();
long b = lrand48();
long c = lrand48();
long d = lrand48();
pthread_mutex_unlock(&lrand_mutex);
sprintf(buf, "frontend=%08lx%04lx%04lx%04lx%04lx%08lx",
a,
b & 0xffff,
(b & ((long)0x0fff0000) >> 16) | 0x4000,
(c & 0x0fff) | 0x8000,
(c & (long)0xffff0000) >> 16,
d
);
return;
}
}C

**Comment by miguelbalparda** [comment]
That part is important, I suggest you to compile again Varnish setting the option @aricwatson told you as false. See http://stackoverflow.com/questions/8132594/disable-werror-ini-configure-file for more info.

**Comment by RaunoVV** [comment]
Didn't manage to use that flag/option. Tried Varnish 3 and everything compiled well and worked as it should be.

**Comment by Zankierka** [comment]
I'm posting it only so if anybody else also has this problem they will be able to solve it in quick way.
To solve it you just need to declare function line before:
```
C{
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <pthread.h>
static pthread_mutex_t lrand_mutex = PTHREAD_MUTEX_INITIALIZER;
void generate_uuid(char* buf); //This line solves this issue
void generate_uuid(char* buf) {
pthread_mutex_lock(&lrand_mutex);
long a = lrand48();
long b = lrand48();
long c = lrand48();
long d = lrand48();
pthread_mutex_unlock(&lrand_mutex);
sprintf(buf, "frontend=%08lx%04lx%04lx%04lx%04lx%08lx",
a,
b & 0xffff,
(b & ((long)0x0fff0000) >> 16) | 0x4000,
(c & 0x0fff) | 0x8000,
(c & (long)0xffff0000) >> 16,
d
);
return;
}
}C
```
