### ISSUE TITLE
Empty config "Normalize Cookie Regex" value leads to unexpected behaviour

### ISSUE THREAD

**Issue by ceckoslab** [nexcess/magento-turpentine#977]
* I am using devel branch revision 51910a56db92370469af3654cc21e73ef5ac032a
* I enabled the feature in Turpentine that creates fake session / cookie for me
* Config value of "Normalize Cookie Regex" and "Normalized Cookie Target" are empty

I noticed that cookie domain of the fake cookie is is empty because when "Normalize Cookie Regex" is empty we always try to use for cookie domain "Normalized Cookie Target".

I am showing an example from my compiled VCL file:

```
if(req.http.Host ~ "") {
set resp.http.Set-Cookie = resp.http.Set-Cookie + "; domain=";
} else {
set resp.http.Set-Cookie = resp.http.Set-Cookie + "; domain=" + regsub(req.http.Host, ":\d+$", "");
}
```

This condition ```if(req.http.Host ~ "")``` always returns `true` because regular expression string is empty.

From my point of view this is a bug but I want to hear second opinion from THE COMMUNITY.

My suggestion is if "Normalize Cookie Regex" or "Normalized Cookie Target" are empty then to have have something like this in VCL file:

```
if(false && req.http.Host ~ "") {
set resp.http.Set-Cookie = resp.http.Set-Cookie + "; domain=";
} else {
set resp.http.Set-Cookie = resp.http.Set-Cookie + "; domain=" + regsub(req.http.Host, ":\d+$", "");
}
```

**Comment by ADDISON74** [comment]
I am struggling for month with wrong redirects. For example I add a product for a category to compare, I go to other category then remove from side comparison module. Instead of remaining on the same page, I will be redirected to the page where I added the last product to comparison. Probably you are right, this could be a matter of cookies.

**Comment by thampe** [comment]
@ADDISON74 I had a similiar issue. The problem is that magento encodes the redirect url inside the remove url which is cached by your varnish server. You can fix it if you build the compare url manually without the encoded url parameter:

```php
// default
$this->helper('catalog/product_compare')->getRemoveUrl($_item);
// manually
$this->getUrl('catalog/product_compare/remove', array('product' => $_item->getId()));

**Comment by ADDISON74** [comment]
@thampe: Could you please let me know which file are you editing?

**Comment by thampe** [comment]
* ``app/design/{theme}/{package}/template/catalog/product/compare/sidebar.phtml``
* ``app/design/{theme}/{package}/template/catalog/product/compare/list.phtml``

Or override the helper ``Mage_Catalog_Helper_Product_Compare``

**Comment by ADDISON74** [comment]
Let's continue the discussion here: #895
