### ISSUE TITLE
Question for SSL support

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#981]
After reading lots of documentation, Magento has a mechanism to deal with SSL Offloading. There is an option which can be set up in Magento for letting know about SSL Offloading (Admin -> System -> Configuration -> Web -> Secure, Offloader header. By default it has value of "SSL_OFFLOADED".

In your wiki about SSL_Support, Pound adds in its configuration this directive AddHeader "Ssl-Offloaded: 1", then in Apache .htaccess SetEnvIf Ssl-Offloaded 1 HTTPS=on. This is correct.

1) Why do you recommend in Magento Admin changing Offloader header from SSL_OFFLOADED value to HTTP_SSL_OFFLOADED?

2) Does it matter the case sensitive in letters? SSL_OFFLOADED = Ssl_Offloaded? 

3) Is it OK that in Pound Ssl-Offloaded has a - between words then in Magento Admin _?

4) Are the settings related to headers well done in Pound configuration? Did anyone tried in a production environment?

Even it is working using your wiki page as it is I wanted to clarify this setup. Thank you.

**Comment by ADDISON74** [comment]
Solved and closed

**Comment by aricwatson** [comment]
@ADDISON74 If you have time, please let us know how you fixed the problem!

**Comment by ADDISON74** [comment]
It won't be a problem. I will come back here with my configuration and helping all understanding the directives.

**Comment by ADDISON74** [comment]
SSL offloading means you won't use your webserver for dealing with secure connections. Doing this you will give more power to your webserver, SSL module is time/resource consuming for the webserver. A proxy server like Pound can do SSL offloading for you using a very small amount of resources from your system. I really do recommend this implementation always when you have secured connections, or a mix of secured/unsecured connections.

POUND (IP:80, IP:443) => VARNISH (8090) => APACHE (8080)

We will disable module ssl in Apache. Pound will deal with both incoming ports 80 and 443. All secured connections will be passed decrypted after Pound. Configuration for Pound can be found in Turpentine Wiki with my comment to set RewriteLocation to 0 or 2 for mix of secured/unsecured connections.

Let's take the questions from above: using this directive in Pound configuration <strong>AddHeader "Ssl-Offloaded 1" </strong> and having created before a file to show you all information about PHP, in your browser in section "PHP Variables" you can find this variable _SERVER["HTTP_SSL_OFFLOADED"] set to 1. This variable will be used to informed Magento SSL is done on the proxy.

1) Why do you recommend in Magento Admin changing Offloaded header option from SSL_OFFLOADED value to HTTP_SSL_OFFLOADED? Because you will inform Magento to check if this server variable is set. _SERVER["HTTP_SSL_OFFLOADED"] from above gives you information which is the variable used to informed about offloading. That's why you set it up to HTTP_SSL_OFFLOAD.

2) Does it matter the case sensitive in letters? SSL_OFFLOADED = Ssl_Offloaded? The answer is no.

3) Is it OK in Pound configuration Ssl-Offloaded has a - between words then in Magento Admin _? Well, check how is the server variable in PHP set up. It is OK.

4) Are the settings related to headers well done in Pound configuration? Did anyone tried in a production environment? The settings related to SSL Offloading are working as expected.

What other settings must be done?

There is one more very important setting to be implemented. Magento checks and uses this variable _SERVER["HTTPS"]. If it is not set you will have trouble. You can set it up adding a header in Pound configuration, but most administrators prefer to add this directive <strong>SetEnvIf Ssl-Offloaded 1 HTTPS=on</strong> into Magento root .htaccess. It says if that header is set there is SSL offloading and set HTTPS variable up for being used by Magento. Be careful to add this line at the end of the file or other places but not between any <IfModule ...> statement.

Keep Pound on the both incoming ports and passing secured/unsecured connections to Varnish on port 8090. If you want to give away Varnish for a while, you have to edit only Pound configuration file setting both Backends to port 8080 (Apache) instead of initial 8090 (Varnish).

**Comment by aricwatson** [comment]
Thank you!

**Comment by ADDISON74** [comment]
One more thing, pay attention how your SSL certificate is passed to Pound. You don't have a lot directives for your configuration file like in Apache or Nginx. You must concatenate your key file, intermediate certificate (if there is one) file and your self-certificate/issued certificate by a CA file in one file with pem extenstion. You must keep this order in your file. If you don't do this and use only .crt or .crt file converted to .pem format restarting Pound you will get errors like this one" <strong>SSL_CTX_use_certificate_chain_file failed - aborted</strong>".
