### ISSUE TITLE
Duplicate Mainmenu when using Buyshop and Varnish/Turpentine

### ISSUE THREAD

**Issue by fbkowo** [nexcess/magento-turpentine#982]
I'm using Magento 1.9.0.1 with the Buyshop-Theme and Varnish 4.1 together with Turpentine-Plugin 0.6.6.

That all works well, but the Mainmenu is shown twice. 

With debug enabled i can see in system.log that the block "catalog.topnav.menu" is check twice:

2015-10-14T20:30:13+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: header
2015-10-14T20:30:13+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: top.menu
2015-10-14T20:30:13+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: catalog.topnav.menu
2015-10-14T20:30:13+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: catalog.topnav.menu
2015-10-14T20:30:13+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: topcart
2015-10-14T20:30:13+00:00 DEBUG (7): TURPENTINE: Set Varnish cache flag header to: 1
2015-10-14T20:30:13+00:00 DEBUG (7): TURPENTINE: Set ESI flag header to: 0
2015-10-14T20:30:13+00:00 DEBUG (7): TURPENTINE: Matched router: standard

I've tried to disable the ESI-Block in turpentine_esi.xml and local.xml in theme directory, with blocks like:

```
<reference name="catalog.topnav.menu" type="buyshopconfig/navigation">
            <action method="setEsiOptions">
                <params>
                         <disableEsiInjection>1</disableEsiInjection>
                </params>
            </action>
</reference>
```

but without success.

Would appreciate any help or hint.

Kind regards,
Wolfgang

**Comment by aricwatson** [comment]
Unfortunately, theme conflicts like this are very tricky to track down without direct access to the system.

One approach might be to remove *all* ESI policies in local.xml/turpentine_esi.xml, flush all the caches and see if the problem persists. Then start adding the policies back in for various blocks and see if you can isolate a block policy that's causing the problem.

Another option would be to try using `<method>ajax</method>` on that block to see if that helps.

**Comment by miguelbalparda** [comment]
Closing for lack of feedback.

**Comment by drk1** [comment]
Hi, I encountered the same issue with Porto theme (minicart and megamenu).
I finally fixed it with adding the following esi to my theme's local.xml header node:

`<reference name="header">
       		<action method="setEsiOptions">
                <params>
                	<disableEsiInjection>1</disableEsiInjection>
                    <method>ajax</method>
                    <access>private</access>
                    <flush_events>
                        <wishlist_item_save_after/>
                        <wishlist_item_delete_after/>
                        <sales_quote_save_after/>
                        <controller_action_layout_render_before_catalogsearch_result_index />
                        <persistent_session_expired/>
                    </flush_events>
                </params>
            </action>
...
`

Maybe this could help someone.
