### ISSUE TITLE
Use Turpentine in a mutliple Magento sites

### ISSUE THREAD

**Issue by andreaseba89** [nexcess/magento-turpentine#986]
Hi,

I have a server with two Magento websites and a Varnish instance.
They are using different domain names.

I setup the first website and the cache works well.
In the second website, instead, cache not works.

I read that Turpentine didn't support multiple backend.
In the release 0.6.7. Turpentine supports them?

Thanks

**Comment by aricwatson** [comment]
I haven't tested this, but I suspect you'd run into conflicts with the version of Turpentine on each site both trying interact with the same instance of Varnish.

Our standard practice is to set up Varnish to listen on its own IP, so I'd recommend just running two instances of Varnish on separate IPs. Or if that's not feasible, perhaps separate ports would work?

**Comment by aricwatson** [comment]
Closing for lack of feedback.
