### ISSUE TITLE
No nano /etc/sysconfig/varnish on CentOS 7 with Varnish 4.0.3

### ISSUE THREAD

**Issue by jgeerdink** [nexcess/magento-turpentine#989]
Hi,

I try to find the /etc/sysconfig/varnish on my CentOS 7 with Varnish 4.0.3, but that file does not exist.
Where can I find this file to fix the issue for Varnish data to write over length limit

**Comment by miguelbalparda** [comment]
I don't quite understand this issue. Can you give is some more info? I specifically don't understand the part about /etc/sysconfig/varnish

**Comment by ADDISON74** [comment]
This is not a Turpentine issue. It is related to your Varnish installation. I suggest searching with Google for Varnish installation CentOS. It could be a systemd issue (configuration file could be in other places). Once you make running Varnish service then you can go further to install and configure Turpentine on your Magento.

Run in Terminal "ps -ef | grep varnish".  you should see the path to your configuration file. If you don't see anything you did not set up Varnish for running. Find a tutorial.

**Comment by ADDISON74** [comment]
Read this too: https://wiki.archlinux.org/index.php/Varnish

You startup parameters for Varnish should be in a file named varnish.service. Find this file location.
