### ISSUE TITLE
106 Message from VCC-compiler: Expected ';' got '"; "' (program line 174), at ('input' Line 58 Pos 56) set req.http.Cookie = req.http.X-Varnish-Faked-Session ";

### ISSUE THREAD

**Issue by dshaw002** [nexcess/magento-turpentine#990]
Updated the admin backend directory and varnish started caching the new admin directory (dbwlaccess). Added the new admin directory to the URL blacklist, but nothing changed. I checked the /var/default.vcl file and saw that the URL blacklist wasn't updating the default.vcl file. I manually added the dbwlaccess directory to the vcl file. I clicked on Apply Varnish Config, and got this error:

Failed to apply the VCL to 10.249.156.155:6082: Got unexpected response code from Varnish: 106 Message from VCC-compiler: Expected ';' got '"; "' (program line 174), at ('input' Line 58 Pos 56) set req.http.Cookie = req.http.X-Varnish-Faked-Session "; " req.http.Cookie; -------------------------------------------------------####----------------- Running VCC-compiler failed, exit 1 VCL compilation failed

Pastebin for the VCL:
http://pastebin.com/Q07mRFNq

**Comment by miguelbalparda** [comment]
Have you searched the repository for this error? There are several issues with the exact same issue. This usually happens when you don't select the correct Varnish version in the admin.
