### ISSUE TITLE
Aheadworks Popup Extension

### ISSUE THREAD

**Issue by evensis** [nexcess/magento-turpentine#995]
Hi guys,

Interesting one, we're using the aheadworks pop-up extension which displays a discount code on first load of the page. However, since installing turpentine this popup shows every single time you goto any page on the website.

Which suggest to me that its cookie variable isn't being set for some odd reason.

Can see this in the code of the Aheadworks extension which sets the variable not to show the pop up again:

    /**
     * Save viewed popup into cookie
     */
    public function setViewedPopup($id)
    {
        /** @var $cookies   Mage_Core_Model_Cookie */
        $cookies = Mage::getModel('core/cookie');
        if (!$cookies->get(self::COOKIE_NAME . $id)) {
            $cookies->set(self::COOKIE_NAME . $id, $id, Mage::helper('popup')->getCookiesLifetime());
        }
    }

For some odd reason, it appears that the cookie is never set. I've tried various concoctions of setting ESI options within the template. The only thing I can do is break the popup via using the Ajax method, or if using ESI, the popup shows regardless on every page due to the cookie not being set. I can confirm the ESI call is working as im breaking into it with xdebug. I've tried also setting it to ttl 0 to ensure it is never cached, and this unfortunately has the same issue.
I've debugged through to the Magento cookie model, can see the 'setcookie' function being executed, but nothing appearing within the $_COOKIE after this has been done.

Any ideas? I'd rather not make this session based.

Thanks

**Comment by aricwatson** [comment]
I'm guessing that Varnish is stripping out the set-cookie header that is coming from the back-end (via the extension). You may need to make some custom changes to your VCL to prevent this behavior. [Here](https://www.varnish-cache.org/docs/3.0/tutorial/cookies.html) is more info about cookies and Varnish in general. 

Another option might be to use client-side javascript to set the cookie and show/not show depending on the cookie?

> The only thing I can do is break the popup via using the Ajax method

How does this break it?

**Comment by evensis** [comment]
Thanks for the info, will have a play around with it, failing that will do the client side set cookie method as that's a guaranteed win.

Pretty sure the reason it doesn't show using Ajax is the code has a javascript function in it that shows the popup via the onload event, ajaxing in the block is thereafter so not triggering the event. More just an incompatibility with the use of ajax and the aheadworks team not anticipating a varnish environment (although come magento 2 its going to be a requirement!).

**Comment by aricwatson** [comment]
Sounds good, setting it up to work with front-end code should take care of the problem - but let us know if not! We'll be happy to reopen the issue.
