### ISSUE TITLE
Blank page after clear cache

### ISSUE THREAD

**Issue by augpaschal** [nexcess/magento-turpentine#996]
Hello,

I have enable only Varnise Page  and Varnish ESI Block in magento cache manager. But when i select these two options to do clear , after some seconds i get a blank page (url : ... /index.php/manage/cache/massRefresh/ )

Any ideas?

**Comment by miguelbalparda** [comment]
Please add your Magento and Turpentine version plus your Magento and php error logs. Without this info we can't do much.

**Comment by augpaschal** [comment]
Magento 1.9
Turpentine 0.6.7

I havent any error admin page or in logs (system & exceptions)

**Comment by miguelbalparda** [comment]
That is extremely strange, something should be logged if you see a WSOD. Set your display_errors directive and print all the errors to see if you can debug the white screen.

**Comment by augpaschal** [comment]
After clear cache (from Cache Store Management) I get a 503 error with following details:

Error 503 Service Unavailable
Service Unavailable
Guru Meditation:
XID: 196528319
Varnish cache server

Any idea?

**Comment by aricwatson** [comment]
Are you sure that the Magento instance that Varnish is using is running correctly, and that Turpentine is correctly installed and running? Try turning on debug options in Turpentine and let us know if you see any useful error messages in the logs.

**Comment by augpaschal** [comment]
first load of page is slowly but second is fast (with age:xxx, xxx>0), so i think that turpentine ruuning correctly

**Comment by aricwatson** [comment]
Do you have any other caching extensions, or other cache types enabled?

**Comment by augpaschal** [comment]
No, only two option related with varnish are enabled

**Comment by aricwatson** [comment]
Hmm... Often 503 errors like that are because Varnish is having some problem communicating with the back-end (the magento install on apache/nginx) - have you double-checked that Varnish is using the right IP/ports, and that the web server is working properly? Anything in the server logs?

**Comment by aricwatson** [comment]
Closing for lack of feedback.
