### ISSUE TITLE
Disabling Turpentine caching does not disable Varnish caching

### ISSUE THREAD

**Issue by srvrmnky** [nexcess/magento-turpentine#997]
When disabling the Turpentine caches in the Admin config, I would expect Varnish to essentially act as a direct passthru, however it appears to still be caching page content. This causes lots of problems unless I manually disable the caching in the varnish config file.

Our servers are currently running Varnish 3.0.7, and we're also using a Redis session and caching backend.

**Comment by Silarn** [comment]
Didn't post with my regular account.

**Comment by aricwatson** [comment]
If you disable Turpentine, Varnish will be left running with whatever VCL settings were last applied to it. If you want it to just pass everything through, you'll need to apply a new VCL specifying that to Varnish, via command line tools.

**Comment by Silarn** [comment]
Okay, this wasn't clear.

**Comment by aricwatson** [comment]
Sorry! I'll go ahead and close this issue, but let us know if you have any other questions/problems!
