### ISSUE TITLE
Turpentine @ responsive design sites

### ISSUE THREAD

**Issue by augpaschal** [nexcess/magento-turpentine#999]
Hello,

Can i tell me how turpentine behaves at responsive design sites? A page seen in mobile is different from same page in desktop. How the cache operate in this case?

**Comment by miguelbalparda** [comment]
Have you read the documentation or even tested with a responsive theme? Please do it before asking any questions as most of the stuff is already there.

**Comment by aricwatson** [comment]
This is really going to depend on how the responsiveness has been achieved. Usually, it involves font-end technologies like javascript and css media queries, which shouldn't be affected by using Varnish/Turpentine. When I test on the 1.9.x demo site (with responsive theme) I don't see any problems.

**Comment by aricwatson** [comment]
Closing for lack of feedback.
